<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bz415716" nsURI="http://www.eclipse.org/emf/texo/test/model/issues/bz415716"
    nsPrefix="bz415716">
  <eClassifiers xsi:type="ecore:EClass" name="TestBz415716_One">
    <eStructuralFeatures xsi:type="ecore:EReference" name="two" upperBound="-1" eType="#//TestBz415716_Two"
        eOpposite="#//TestBz415716_Two/one"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestBz415716_Two">
    <eStructuralFeatures xsi:type="ecore:EReference" name="one" eType="#//TestBz415716_One"
        eOpposite="#//TestBz415716_One/two"/>
  </eClassifiers>
</ecore:EPackage>
