<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="svg" nsURI="http://org.eclipse.gmf.tooling.examples.svg" nsPrefix="org.eclipse.gmf.tooling.examples.svg">
  <eClassifiers xsi:type="ecore:EClass" name="Playground">
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="12"
        eType="#//Player" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="2" eType="#//Goal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal"/>
</ecore:EPackage>
