<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bz371509"
    nsURI="http://www.eclipse.org/emf/texo/test/model/issues/bz371509" nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="EClass0">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toClass1" ordered="false"
        eType="#//EClass1" eOpposite="#//EClass1/toClass0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="many" upperBound="-1" eType="#//EClass1"
        eOpposite="#//EClass1/many"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toClass0" ordered="false"
        upperBound="-1" eType="#//EClass0" eOpposite="#//EClass0/toClass1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="many" upperBound="-1" eType="#//EClass0"
        eOpposite="#//EClass0/many"/>
  </eClassifiers>
</ecore:EPackage>
