<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="NetworkInfrastructure" nsURI="platform:/resource/DroolsHelloWorld/model/NetworkInfrastructure.ecore"
    nsPrefix="NetworkInfrastructure">
  <eClassifiers xsi:type="ecore:EClass" name="Router">
    <eStructuralFeatures xsi:type="ecore:EReference" name="switches" upperBound="-1"
        eType="#//Switch" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch"/>
</ecore:EPackage>
