<?xml version="1.0"?>
<ecore:EPackage name="test" nsPrefix="test" nsURI="http://www.example.org/test" xmi:version="2.0" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <eClassifiers name="OneThreeTwo" xsi:type="ecore:EClass" />
  <eClassifiers name="FourFiveSix" xsi:type="ecore:EClass" />
  <eClassifiers name="EightTenEle" xsi:type="ecore:EClass" />
</ecore:EPackage>