<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bz390773"
    nsURI="http://www.eclipse.org/emf/teneo/samples/issues/bz390773" nsPrefix="bz390773">
  <eClassifiers xsi:type="ecore:EClass" name="Main">
    <eStructuralFeatures xsi:type="ecore:EReference" name="other" eType="#//Other"
        containment="true" eOpposite="#//Other/main">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@OneToOne(mappedBy=&quot;main&quot;, cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH}, fetch = FetchType.EAGER, optional = true)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Other">
    <eStructuralFeatures xsi:type="ecore:EReference" name="main" eType="#//Main" eOpposite="#//Main/other"/>
  </eClassifiers>
</ecore:EPackage>
