<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testPackage" nsURI="http://testPackage" nsPrefix="testPackage">
  <eClassifiers xsi:type="ecore:EClass" name="FirstClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testReference" eType="ecore:EClass SpecializationAggregation.ecore#//SecondClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecondClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="FirstSubClass" eSuperTypes="SpecializationAggregation.ecore#//FirstClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializationReference"
        eType="ecore:EClass SpecializationAggregation.ecore#//SecondSubClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecondSubClass" eSuperTypes="SpecializationAggregation.ecore#//SecondClass"/>
</ecore:EPackage>
