<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testPackage" nsURI="http://testPackage" nsPrefix="testPackage">
  <eClassifiers xsi:type="ecore:EClass" name="SuperType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TestReference" eType="ecore:EClass CyclicDependentModularizationHierarchy.ecore#//AnotherType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubType" eSuperTypes="CyclicDependentModularizationHierarchy.ecore#//SuperType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnotherType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TestReference" eType="ecore:EClass CyclicDependentModularizationHierarchy.ecore#//AnotherType2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnotherType2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TestReference" eType="ecore:EClass CyclicDependentModularizationHierarchy.ecore#//SubType"/>
  </eClassifiers>
</ecore:EPackage>
