<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Bz424797" nsURI="http://www.eclipse.org/emf/texo/test/model/issues/bz424797"
    nsPrefix="Bz424797">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractSuper424797" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sub4242797" eSuperTypes="#//AbstractSuper424797"/>
  <eClassifiers xsi:type="ecore:EClass" name="Other4242797"/>
</ecore:EPackage>
