<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sdl"
    nsURI="http://www.hub.sam.generated.de/sdl" nsPrefix="sdl">
  <eClassifiers xsi:type="ecore:EClass" name="SdlCreate" eSuperTypes="#//InstanciationCreate #//SdlAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agent" ordered="false"
        lowerBound="1" eType="#//SdlAgent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlAssignment" eSuperTypes="#//SdlAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        lowerBound="1" eType="#//EvaluationExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false"
        lowerBound="1" eType="#//SdlVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlReset" eSuperTypes="#//SdlSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlOutput" eSuperTypes="#//SdlAction #//InstanciationCreate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="via" ordered="false" eType="#//SdlGate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        eType="#//SdlSignal" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" ordered="false" eType="#//EvaluationExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlSignalInstance" eSuperTypes="#//CommunicationEvent #//SdlInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//SdlVariableSlot"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" ordered="false"
        lowerBound="1" eType="#//SdlAgentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" ordered="false"
        eType="#//SdlAgentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlSet" eSuperTypes="#//SdlOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        lowerBound="1" eType="#//EvaluationExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlAgentInstance" eSuperTypes="#//SdlInstance">
    <eOperations name="initializeBehavior" ordered="false" lowerBound="1"/>
    <eOperations name="leadsTo" ordered="false" lowerBound="1" eType="#//SdlAgentInstanceSet">
      <eParameters name="path" ordered="false" lowerBound="1" eType="#//SdlChannelPath"/>
    </eOperations>
    <eOperations name="continuesWith" ordered="false" upperBound="-1" eType="#//SdlChannelPath">
      <eParameters name="path" ordered="false" lowerBound="1" eType="#//SdlChannelPath"/>
    </eOperations>
    <eOperations name="dispatchSignal" ordered="false" lowerBound="1">
      <eParameters name="s" ordered="false" lowerBound="1" eType="#//SdlSignalInstance"/>
      <eParameters name="via" ordered="false" lowerBound="1" eType="#//SdlGate"/>
    </eOperations>
    <eOperations name="run" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agentInstanceSet" ordered="false"
        eType="#//SdlAgentInstanceSet" containment="true" eOpposite="#//SdlAgentInstanceSet/agentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" ordered="false"
        eType="#//SdlCompositeStateInstance" containment="true" eOpposite="#//SdlCompositeStateInstance/owningInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningInstanceSet" ordered="false"
        eType="#//SdlAgentInstanceSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false"
        eType="#//SdlAgentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offspring" ordered="false"
        eType="#//SdlAgentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlDataValue" abstract="true" eSuperTypes="#//InstanciationValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlAgent" eSuperTypes="#//CoreAbstractionsTypedElementsTypedElement #//InstanciationMultiplicityFeature #//CommunicationMedium"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SdlAgentKind">
    <eLiterals name="process"/>
    <eLiterals name="block" value="1"/>
    <eLiterals name="system" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlProcedure" eSuperTypes="#//CoreAbstractionsBehavioralFeaturesBehavioralFeature #//CoreAbstractionsTypedElementsTypedElement #//SdlBehaviorElement #//SdlClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedureStateAutomaton"
        ordered="false" lowerBound="1" eType="#//SdlStateAutomaton" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlAgentInstanceSet" eSuperTypes="#//InstanciationSlot #//CommunicationContext">
    <eOperations name="terminate" ordered="false" lowerBound="1">
      <eParameters name="agent" ordered="false" lowerBound="1" eType="#//SdlAgentInstance"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputQueue" upperBound="-1"
        eType="#//SdlSignalInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agentInstance" ordered="false"
        eType="#//SdlAgentInstance" eOpposite="#//SdlAgentInstance/agentInstanceSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlVariable" eSuperTypes="#//CoreAbstractionsStructuralFeaturesStructuralFeature #//CoreAbstractionsTypedElementsTypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" ordered="false"
        eType="#//EvaluationExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlAgentType" eSuperTypes="#//SdlBehaviorElement #//SdlClassifier #//CoreAbstractionsBehavioralFeaturesBehavioralFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agent" ordered="false"
        upperBound="-1" eType="#//SdlAgent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="#//SdlAgentKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAgentType" ordered="false"
        upperBound="-1" eType="#//SdlAgentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" ordered="false"
        upperBound="-1" eType="#//SdlChannel" containment="true" eOpposite="#//SdlChannel/agentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gate" ordered="false" upperBound="-1"
        eType="#//SdlGate" containment="true" eOpposite="#//SdlGate/agentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlDataType" eSuperTypes="#//EvaluationDataType #//CoreAbstractionsNamespacesNamespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false"
        upperBound="-1" eType="#//SdlOperation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlVariableSlot" eSuperTypes="#//InstanciationSlot"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlChannel" eSuperTypes="#//CoreAbstractionsNamespacesNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" ordered="false" lowerBound="1"
        upperBound="2" eType="#//SdlChannelPath" containment="true" eOpposite="#//SdlChannelPath/channel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agentType" ordered="false"
        lowerBound="1" eType="#//SdlAgentType" eOpposite="#//SdlAgentType/channel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlChannelEnd" eSuperTypes="#//CoreAbstractionsOwnershipsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agent" ordered="false"
        eType="#//SdlAgent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gate" ordered="false" eType="#//SdlGate"
        eOpposite="#//SdlGate/channelEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" ordered="false"
        eType="#//SdlChannelEnd" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" ordered="false"
        lowerBound="1" eType="#//SdlChannelPath"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlChannelPath" eSuperTypes="#//CoreAbstractionsRelationshipsDirectedRelationship #//CoreAbstractionsNamespacesNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" ordered="false"
        upperBound="-1" eType="#//SdlSignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" ordered="false"
        lowerBound="1" eType="#//SdlChannel" eOpposite="#//SdlChannel/path"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlGate" eSuperTypes="#//CoreAbstractionsNamespacesNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receive" ordered="false"
        upperBound="-1" eType="#//SdlSignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="send" ordered="false" upperBound="-1"
        eType="#//SdlSignal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channelEnd" ordered="false"
        upperBound="-1" eType="#//SdlChannelEnd" eOpposite="#//SdlChannelEnd/gate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agentType" ordered="false"
        lowerBound="1" eType="#//SdlAgentType" eOpposite="#//SdlAgentType/gate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlSignal" eSuperTypes="#//CommunicationEventType #//CoreAbstractionsBehavioralFeaturesBehavioralFeature #//SdlClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlTimer" eSuperTypes="#//SdlSignal"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlTrigger" eSuperTypes="#//CommunicationInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" ordered="false"
        lowerBound="1" eType="#//SdlTransition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlInputInstance" eSuperTypes="#//CommunicationListener">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningStateInstance" ordered="false"
        eType="#//SdlCompositeStateInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlVariableAccessEvaluation" eSuperTypes="#//SdlEvaluation"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlVariableAccess" eSuperTypes="#//EvaluationFeatureAccessExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlProcedureFrame" eSuperTypes="#//SdlInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlOpenRange" eSuperTypes="#//SdlRange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false"
        lowerBound="1" eType="#//SdlOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        lowerBound="1" eType="#//EvaluationExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlTimerActiveExpression" eSuperTypes="#//EvaluationBehavioralFeatureAccessExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlOperation" eSuperTypes="#//CoreAbstractionsTypedElementsTypedElement #//CoreAbstractionsBehavioralFeaturesBehavioralFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlRange" eSuperTypes="#//CoreAbstractionsElementsElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlProcedureCall" eSuperTypes="#//EvaluationBehavioralFeatureAccessExpression #//InstanciationCreate #//SdlAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedure" ordered="false"
        lowerBound="1" eType="#//SdlProcedure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SdlParameterKind">
    <eLiterals name="In"/>
    <eLiterals name="Out" value="1"/>
    <eLiterals name="InOut" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlLiteralExpression" eSuperTypes="#//EvaluationLiteralExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlNowExpression" eSuperTypes="#//EvaluationExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlPidExpression" eSuperTypes="#//EvaluationExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="#//SdlPidExpressionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlRangeCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlOperationCall" eSuperTypes="#//EvaluationBehavioralFeatureAccessExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlLiteral" eSuperTypes="#//EvaluationLiteral #//CoreAbstractionsNamespacesNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlClosedRange" eSuperTypes="#//SdlRange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" ordered="false"
        lowerBound="1" eType="#//SdlOpenRange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" ordered="false"
        lowerBound="1" eType="#//SdlOpenRange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlParameter" eSuperTypes="#//SdlVariable #//CoreAbstractionsBehavioralFeaturesParameter #//CoreAbstractionsTypedElementsTypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="#//SdlParameterKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SdlPidExpressionKind">
    <eLiterals name="Self"/>
    <eLiterals name="Sender" value="1"/>
    <eLiterals name="Offspring" value="2"/>
    <eLiterals name="Parent" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlPackage" eSuperTypes="#//CoreAbstractionsNamespacesNamespace #//SdlNamespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedPackage" ordered="false"
        upperBound="-1" eType="#//SdlPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="#//SdlPseudoState #//SdlNamedState"/>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//SdlPseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="History" eSuperTypes="#//Start"/>
  <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//Stop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        eType="#//EvaluationExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//SdlPseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlBehaviorElement" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" ordered="false"
        eType="#//SdlBehavior" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlAbstractState" abstract="true" eSuperTypes="#//CoreAbstractionsElementsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" ordered="false"
        upperBound="-1" eType="#//SdlTrigger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlAction" abstract="true" eSuperTypes="#//CoreAbstractionsElementsElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlChoice" eSuperTypes="#//SdlTrigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" ordered="false"
        upperBound="-1" eType="#//SdlRange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlBehavior" eSuperTypes="#//CoreAbstractionsElementsElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlCompositeState" eSuperTypes="#//CoreAbstractionsTypedElementsTypedElement #//SdlState #//SdlBehavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlElse" eSuperTypes="#//SdlChoice"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlCompositeStateInstance" eSuperTypes="#//SdlInstance #//CommunicationProcess">
    <eOperations name="initializeStates" ordered="false" lowerBound="1"/>
    <eOperations name="executeTransition" ordered="false" lowerBound="1"/>
    <eOperations name="executeAction" ordered="false" lowerBound="1"/>
    <eOperations name="enterState" ordered="false" lowerBound="1">
      <eParameters name="s" ordered="false" lowerBound="1" eType="#//SdlState"/>
    </eOperations>
    <eOperations name="leaveActualState" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualState" lowerBound="1"
        eType="#//SdlStateInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" ordered="false"
        eType="#//SdlStateInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningInstance" ordered="false"
        eType="#//SdlAgentInstance" eOpposite="#//SdlAgentInstance/behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggered" ordered="false"
        eType="#//SdlInputInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" ordered="false"
        eType="#//SdlAgentInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" ordered="false"
        lowerBound="1" eType="#//SdlStateStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlPseudoState" abstract="true" eSuperTypes="#//SdlAbstractState"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlInput" eSuperTypes="#//CoreAbstractionsTypedElementsTypedElement #//SdlTrigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//SdlVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" ordered="false"
        lowerBound="1" eType="#//SdlSignal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlImidiate" eSuperTypes="#//SdlTrigger"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlStateInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualState" ordered="false"
        upperBound="-1" eType="#//SdlStateInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlStateNode" eSuperTypes="#//SdlPseudoState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" ordered="false"
        upperBound="-1" eType="#//SdlState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlStatePartitionInstance" eSuperTypes="#//SdlStateInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlStateAutomaton" eSuperTypes="#//SdlBehavior #//CoreAbstractionsNamespacesNamespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" ordered="false"
        upperBound="-1" eType="#//SdlAbstractState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" ordered="false"
        upperBound="-1" eType="#//SdlTransition" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedState" ordered="false"
        upperBound="-1" eType="#//SdlNamedState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" ordered="false"
        lowerBound="1" eType="#//Start" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlState" eSuperTypes="#//SdlNamedState #//CoreAbstractionsStructuralFeaturesStructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" ordered="false"
        upperBound="-1" eType="#//SdlAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" ordered="false" upperBound="-1"
        eType="#//SdlAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlStatePartition" eSuperTypes="#//SdlState #//SdlBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partition" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//SdlStateType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlTransition" eSuperTypes="#//CoreAbstractionsElementsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" ordered="false"
        upperBound="-1" eType="#//SdlAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="#//SdlAbstractState" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//SdlAbstractState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" ordered="false"
        lowerBound="1" eType="#//SdlTrigger" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlStateType" eSuperTypes="#//SdlClassifier #//CommunicationCommunicator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateAutomaton" ordered="false"
        lowerBound="1" eType="#//SdlStateAutomaton" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" ordered="false"
        upperBound="-1" eType="#//SdlState" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlSplit" eSuperTypes="#//SdlPseudoState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" ordered="false"
        eType="#//EvaluationExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answer" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//SdlChoice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//SdlPseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stop" eSuperTypes="#//SdlPseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlClassifier" abstract="true" eSuperTypes="#//SdlNamespace #//CoreAbstractionsGeneralizationsClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false"
        upperBound="-1" eType="#//SdlVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedure" ordered="false"
        upperBound="-1" eType="#//SdlProcedure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlNamespace" abstract="true" eSuperTypes="#//CoreAbstractionsNamespacesNamespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsTypedElementsType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlNamedState" abstract="true" eSuperTypes="#//CoreAbstractionsNamespacesNamedElement #//SdlAbstractState"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlInstance" abstract="true" eSuperTypes="#//InstanciationInstance #//InstanciationValue">
    <eOperations name="resolveSlot" ordered="false" lowerBound="1" eType="#//SdlVariableSlot">
      <eParameters name="v" ordered="false" lowerBound="1" eType="#//SdlVariable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false"
        eType="#//SdlVariableSlot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingInstance" ordered="false"
        eType="#//SdlInstance" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlOperationEvaluation" eSuperTypes="#//SdlEvaluation"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlEvaluation" abstract="true" eSuperTypes="#//EvaluationEvaluation">
    <eOperations name="updateContext" ordered="false" lowerBound="1">
      <eParameters name="c" ordered="false" lowerBound="1" eType="#//SdlInstance"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false"
        lowerBound="1" eType="#//SdlInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlLiteralEvaluation" eSuperTypes="#//SdlEvaluation"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlPrimitiveValue" abstract="true" eSuperTypes="#//SdlDataValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="SdlPidExpressionEvaluation" eSuperTypes="#//SdlEvaluation"/>
  <eClassifiers xsi:type="ecore:EClass" name="PidValue" eSuperTypes="#//SdlPrimitiveValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        lowerBound="1" eType="#//SdlAgentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlGeneralValue" eSuperTypes="#//SdlDataValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SdlStateStatus">
    <eLiterals name="STARTED"/>
    <eLiterals name="RUNNING" value="1"/>
    <eLiterals name="STOPED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteSyntaxSdlQualifier" eSuperTypes="#//CoreAbstractionsElementsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathItem" upperBound="-1"
        eType="#//ConcreteSyntaxSdlPathItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteSyntaxSdlPathItem" eSuperTypes="#//CoreAbstractionsElementsElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false" lowerBound="1"
        eType="#//ConcreteSyntaxSdlScopeUnitKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="#//PrimitiveTypesString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteSyntaxSdlIdentifier" eSuperTypes="#//CoreAbstractionsElementsElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="#//PrimitiveTypesString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" ordered="false"
        eType="#//ConcreteSyntaxSdlQualifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConcreteSyntaxSdlScopeUnitKind">
    <eLiterals name="Package"/>
    <eLiterals name="SystemType" value="1"/>
    <eLiterals name="ProcessType" value="2"/>
    <eLiterals name="BlockType" value="3"/>
    <eLiterals name="Signal" value="4"/>
    <eLiterals name="Procedure" value="5"/>
    <eLiterals name="System" value="6"/>
    <eLiterals name="Block" value="7"/>
    <eLiterals name="Process" value="8"/>
    <eLiterals name="StateType" value="9"/>
    <eLiterals name="State" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsTypedElementsType" abstract="true"
      eSuperTypes="#//CoreAbstractionsNamespacesNamedElement">
    <eOperations name="conformsTo" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//CoreAbstractionsTypedElementsType"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsTypedElementsTypedElement"
      abstract="true" eSuperTypes="#//CoreAbstractionsNamespacesNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="#//CoreAbstractionsTypedElementsType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsBehavioralFeaturesParameter"
      abstract="true" eSuperTypes="#//CoreAbstractionsNamespacesNamedElement #//CoreAbstractionsTypedElementsTypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsBehavioralFeaturesBehavioralFeature"
      abstract="true" eSuperTypes="#//CoreAbstractionsNamespacesNamespace #//CoreAbstractionsClassifiersFeature">
    <eOperations name="isDistinguishableFrom" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="n" ordered="false" lowerBound="1" eType="#//CoreAbstractionsNamespacesNamedElement"/>
      <eParameters name="ns" ordered="false" lowerBound="1" eType="#//CoreAbstractionsNamespacesNamespace"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//CoreAbstractionsBehavioralFeaturesParameter" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsStructuralFeaturesStructuralFeature"
      abstract="true" eSuperTypes="#//CoreAbstractionsClassifiersFeature #//CoreAbstractionsTypedElementsTypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsCommentsComment" eSuperTypes="#//CoreAbstractionsOwnershipsElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" ordered="false" eType="#//PrimitiveTypesString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotatedElement" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsOwnershipsElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsOwnershipsElement" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement">
    <eOperations name="allOwnedElements" ordered="false" upperBound="-1" eType="#//CoreAbstractionsOwnershipsElement"/>
    <eOperations name="mustBeOwned" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsOwnershipsElement" derived="true"
        containment="true" eOpposite="#//CoreAbstractionsOwnershipsElement/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false"
        eType="#//CoreAbstractionsOwnershipsElement" derived="true" eOpposite="#//CoreAbstractionsOwnershipsElement/ownedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsCommentsComment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsInstancesInstanceSpecification"
      eSuperTypes="#//CoreAbstractionsNamespacesNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" ordered="false" upperBound="-1"
        eType="#//CoreAbstractionsInstancesSlot" containment="true" eOpposite="#//CoreAbstractionsInstancesSlot/owningInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsClassifiersClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" ordered="false"
        eType="#//CoreAbstractionsExpressionsValueSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsInstancesInstanceValue"
      eSuperTypes="#//CoreAbstractionsExpressionsValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" ordered="false"
        lowerBound="1" eType="#//CoreAbstractionsInstancesInstanceSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsInstancesSlot" eSuperTypes="#//CoreAbstractionsOwnershipsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningInstance" ordered="false"
        lowerBound="1" eType="#//CoreAbstractionsInstancesInstanceSpecification" eOpposite="#//CoreAbstractionsInstancesInstanceSpecification/slot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//CoreAbstractionsExpressionsValueSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definingFeature" ordered="false"
        lowerBound="1" eType="#//CoreAbstractionsStructuralFeaturesStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsElementsElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" ordered="false" lowerBound="1"
        eType="#//PrimitiveTypesInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsVisibilitiesNamedElement"
      abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" ordered="false"
        eType="#//CoreAbstractionsVisibilitiesVisibilityKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CoreAbstractionsVisibilitiesVisibilityKind">
    <eLiterals name="public"/>
    <eLiterals name="private" value="1"/>
    <eLiterals name="protected" value="2"/>
    <eLiterals name="package" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsConstraintsNamedElement"
      abstract="true" eSuperTypes="#//CoreAbstractionsOwnershipsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" ordered="false"
        eType="#//CoreAbstractionsConstraintsNamespace" derived="true" eOpposite="#//CoreAbstractionsConstraintsNamespace/ownedMember"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsConstraintsNamespace"
      abstract="true" eSuperTypes="#//CoreAbstractionsConstraintsNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRule" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsConstraintsConstraint" containment="true"
        eOpposite="#//CoreAbstractionsConstraintsConstraint/context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMember" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsConstraintsNamedElement" derived="true"
        containment="true" eOpposite="#//CoreAbstractionsConstraintsNamedElement/namespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsConstraintsNamedElement" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsConstraintsConstraint"
      eSuperTypes="#//CoreAbstractionsConstraintsNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false"
        eType="#//CoreAbstractionsConstraintsNamespace" eOpposite="#//CoreAbstractionsConstraintsNamespace/ownedRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" ordered="false"
        lowerBound="1" eType="#//CoreAbstractionsExpressionsValueSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedElement" upperBound="-1"
        eType="#//CoreAbstractionsOwnershipsElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsNamespacesNamedElement"
      abstract="true" eSuperTypes="#//CoreAbstractionsOwnershipsElement">
    <eOperations name="allNamespaces" upperBound="-1" eType="#//CoreAbstractionsNamespacesNamespace"/>
    <eOperations name="isDistinguishableFrom" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="n" ordered="false" lowerBound="1" eType="#//CoreAbstractionsNamespacesNamedElement"/>
      <eParameters name="ns" ordered="false" lowerBound="1" eType="#//CoreAbstractionsNamespacesNamespace"/>
    </eOperations>
    <eOperations name="separator" ordered="false" lowerBound="1" eType="#//PrimitiveTypesString"/>
    <eOperations name="qualifiedName" ordered="false" lowerBound="1" eType="#//PrimitiveTypesString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="#//PrimitiveTypesString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" ordered="false"
        eType="#//PrimitiveTypesString" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" ordered="false"
        eType="#//CoreAbstractionsNamespacesNamespace" derived="true" eOpposite="#//CoreAbstractionsNamespacesNamespace/ownedMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" ordered="false"
        eType="#//ConcreteSyntaxSdlIdentifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsNamespacesNamespace"
      abstract="true" eSuperTypes="#//CoreAbstractionsNamespacesNamedElement">
    <eOperations name="getNamesOfMember" ordered="false" upperBound="-1" eType="#//PrimitiveTypesString">
      <eParameters name="element" ordered="false" lowerBound="1" eType="#//CoreAbstractionsNamespacesNamedElement"/>
    </eOperations>
    <eOperations name="membersAreDistinguishable" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMember" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsNamespacesNamedElement" derived="true"
        containment="true" eOpposite="#//CoreAbstractionsNamespacesNamedElement/namespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsNamespacesNamedElement" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsSuperClassifier" abstract="true"
      eSuperTypes="#//CoreAbstractionsNamespacesNamespace">
    <eOperations name="inheritedMember" ordered="false" upperBound="-1" eType="#//CoreAbstractionsNamespacesNamedElement"/>
    <eOperations name="parents" ordered="false" upperBound="-1" eType="#//CoreAbstractionsSuperClassifier"/>
    <eOperations name="allParents" ordered="false" upperBound="-1" eType="#//CoreAbstractionsSuperClassifier"/>
    <eOperations name="inheritableMembers" ordered="false" upperBound="-1" eType="#//CoreAbstractionsNamespacesNamedElement">
      <eParameters name="c" ordered="false" lowerBound="1" eType="#//CoreAbstractionsSuperClassifier"/>
    </eOperations>
    <eOperations name="hasVisibilityOf" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="n" ordered="false" lowerBound="1" eType="#//CoreAbstractionsNamespacesNamedElement"/>
    </eOperations>
    <eOperations name="inherit" ordered="false" upperBound="-1" eType="#//CoreAbstractionsNamespacesNamedElement">
      <eParameters name="inhs" ordered="false" upperBound="-1" eType="#//CoreAbstractionsNamespacesNamedElement"/>
    </eOperations>
    <eOperations name="maySpecializeType" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="c" ordered="false" lowerBound="1" eType="#//CoreAbstractionsSuperClassifier"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedMember" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsNamespacesNamedElement" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsSuperClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsClassifiersFeature"
      abstract="true" eSuperTypes="#//CoreAbstractionsNamespacesNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuringClassifier" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsClassifiersClassifier" derived="true"
        eOpposite="#//CoreAbstractionsClassifiersClassifier/feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsClassifiersClassifier"
      abstract="true" eSuperTypes="#//CoreAbstractionsNamespacesNamespace">
    <eOperations name="allFeatures" ordered="false" upperBound="-1" eType="#//CoreAbstractionsClassifiersFeature"/>
    <eOperations name="instanciate" ordered="false" lowerBound="1" eType="#//InstanciationInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsClassifiersFeature" derived="true"
        eOpposite="#//CoreAbstractionsClassifiersFeature/featuringClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsExpressionsExpression"
      eSuperTypes="#//CoreAbstractionsExpressionsValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" ordered="false"
        eType="#//PrimitiveTypesString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" upperBound="-1"
        eType="#//CoreAbstractionsExpressionsValueSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsExpressionsValueSpecification"
      abstract="true" eSuperTypes="#//CoreAbstractionsOwnershipsElement">
    <eOperations name="isComputable" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eOperations name="integerValue" ordered="false" lowerBound="1" eType="#//PrimitiveTypesInteger"/>
    <eOperations name="booleanValue" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eOperations name="stringValue" ordered="false" lowerBound="1" eType="#//PrimitiveTypesString"/>
    <eOperations name="unlimitedValue" ordered="false" lowerBound="1" eType="#//PrimitiveTypesUnlimitedNatural"/>
    <eOperations name="isNull" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsExpressionsOpaqueExpression"
      eSuperTypes="#//CoreAbstractionsExpressionsValueSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsMultiplicityExpressionsMultiplicityElement"
      abstract="true" eSuperTypes="#//CoreAbstractionsOwnershipsElement">
    <eOperations name="lower" ordered="false" lowerBound="1" eType="#//PrimitiveTypesInteger"/>
    <eOperations name="upper" ordered="false" lowerBound="1" eType="#//PrimitiveTypesUnlimitedNatural"/>
    <eOperations name="lowerBound" ordered="false" lowerBound="1" eType="#//PrimitiveTypesInteger"/>
    <eOperations name="upperBound" ordered="false" lowerBound="1" eType="#//PrimitiveTypesUnlimitedNatural"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" ordered="false"
        eType="#//PrimitiveTypesInteger" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" ordered="false"
        eType="#//PrimitiveTypesUnlimitedNatural" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperValue" ordered="false"
        eType="#//CoreAbstractionsExpressionsValueSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerValue" ordered="false"
        eType="#//CoreAbstractionsExpressionsValueSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsLiteralsLiteralInteger"
      eSuperTypes="#//CoreAbstractionsLiteralsLiteralSpecification">
    <eOperations name="isComputable" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eOperations name="integerValue" ordered="false" lowerBound="1" eType="#//PrimitiveTypesInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsLiteralsLiteralString"
      eSuperTypes="#//CoreAbstractionsLiteralsLiteralSpecification">
    <eOperations name="isComputable" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eOperations name="stringValue" ordered="false" lowerBound="1" eType="#//PrimitiveTypesString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        eType="#//PrimitiveTypesString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsLiteralsLiteralBoolean"
      eSuperTypes="#//CoreAbstractionsLiteralsLiteralSpecification">
    <eOperations name="isComputable" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eOperations name="booleanValue" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsLiteralsLiteralNull"
      eSuperTypes="#//CoreAbstractionsLiteralsLiteralSpecification">
    <eOperations name="isComputable" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eOperations name="isNull" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsLiteralsLiteralSpecification"
      abstract="true" eSuperTypes="#//CoreAbstractionsExpressionsValueSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsLiteralsLiteralUnlimitedNatural"
      eSuperTypes="#//CoreAbstractionsLiteralsLiteralSpecification">
    <eOperations name="isComputable" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eOperations name="unlimitedValue" ordered="false" lowerBound="1" eType="#//PrimitiveTypesUnlimitedNatural"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesUnlimitedNatural"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsRedefinitionsRedefinableElement"
      abstract="true" eSuperTypes="#//CoreAbstractionsNamespacesNamedElement">
    <eOperations name="isConsistentWith" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="redefinee" ordered="false" lowerBound="1" eType="#//CoreAbstractionsRedefinitionsRedefinableElement"/>
    </eOperations>
    <eOperations name="isRedefinitionContextValid" ordered="false" lowerBound="1"
        eType="#//PrimitiveTypesBoolean">
      <eParameters name="redefined" ordered="false" lowerBound="1" eType="#//CoreAbstractionsRedefinitionsRedefinableElement"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinedElement" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsRedefinitionsRedefinableElement"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redefinitionContext" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsSuperClassifier" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsChangeabilitiesStructuralFeature"
      abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadOnly" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsMultiplicitiesMultiplicityElement"
      abstract="true" eSuperTypes="#//CoreAbstractionsElementsElement">
    <eOperations name="lowerBound" ordered="false" lowerBound="1" eType="#//PrimitiveTypesInteger"/>
    <eOperations name="upperBound" ordered="false" lowerBound="1" eType="#//PrimitiveTypesUnlimitedNatural"/>
    <eOperations name="isMultivalued" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eOperations name="includesCardinality" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="C" ordered="false" lowerBound="1" eType="#//PrimitiveTypesInteger"/>
    </eOperations>
    <eOperations name="includesMultiplicity" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="M" ordered="false" lowerBound="1" eType="#//CoreAbstractionsMultiplicitiesMultiplicityElement"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" ordered="false"
        lowerBound="1" eType="#//PrimitiveTypesBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" ordered="false"
        eType="#//PrimitiveTypesInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" ordered="false"
        eType="#//PrimitiveTypesUnlimitedNatural"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsGeneralizationsGeneralization"
      eSuperTypes="#//CoreAbstractionsRelationshipsDirectedRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specific" ordered="false"
        lowerBound="1" eType="#//CoreAbstractionsGeneralizationsClassifier" eOpposite="#//CoreAbstractionsGeneralizationsClassifier/generalization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" ordered="false"
        lowerBound="1" eType="#//CoreAbstractionsGeneralizationsClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsGeneralizationsClassifier"
      abstract="true" eSuperTypes="#//CoreAbstractionsTypedElementsType #//CoreAbstractionsClassifiersClassifier">
    <eOperations name="general" ordered="false" upperBound="-1" eType="#//CoreAbstractionsGeneralizationsClassifier"/>
    <eOperations name="parents" ordered="false" upperBound="-1" eType="#//CoreAbstractionsGeneralizationsClassifier"/>
    <eOperations name="conformsTo" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//CoreAbstractionsGeneralizationsClassifier"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsGeneralizationsGeneralization" containment="true"
        eOpposite="#//CoreAbstractionsGeneralizationsGeneralization/specific"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" ordered="false"
        upperBound="-1" eType="#//CoreAbstractionsGeneralizationsClassifier" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsRelationshipsRelationship"
      abstract="true" eSuperTypes="#//CoreAbstractionsOwnershipsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedElement" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//CoreAbstractionsOwnershipsElement"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAbstractionsRelationshipsDirectedRelationship"
      abstract="true" eSuperTypes="#//CoreAbstractionsRelationshipsRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//CoreAbstractionsOwnershipsElement"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//CoreAbstractionsOwnershipsElement"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PrimitiveTypesUnlimitedNatural" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PrimitiveTypesString" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PrimitiveTypesBoolean" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PrimitiveTypesInteger" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PrimitiveTypesObject" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanciationInstance" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement">
    <eOperations name="createSlots" ordered="false" lowerBound="1"/>
    <eOperations name="initialize" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" ordered="false" eType="#//InstanciationSlot"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanciationSlot" abstract="true">
    <eOperations name="createInitialValues" ordered="false" lowerBound="1"/>
    <eOperations name="initialize" ordered="false" lowerBound="1"/>
    <eOperations name="updateValue" ordered="false" lowerBound="1">
      <eParameters name="v" ordered="false" lowerBound="1" eType="#//InstanciationValue"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        upperBound="-1" eType="#//InstanciationValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanciationValue" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanciationCreate" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement #//EvaluationBehavioralFeatureAccess">
    <eOperations name="create" ordered="false" lowerBound="1" eType="#//InstanciationInstance">
      <eParameters name="context" ordered="false" lowerBound="1" eType="#//InstanciationInstance"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" ordered="false"
        lowerBound="1" eType="#//CoreAbstractionsClassifiersClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanciationMultiplicityFeature" abstract="true"
      eSuperTypes="#//CoreAbstractionsStructuralFeaturesStructuralFeature #//CoreAbstractionsMultiplicitiesMultiplicityElement">
    <eOperations name="instanciate" ordered="false" lowerBound="1" eType="#//InstanciationSlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationDataType" abstract="true"
      eSuperTypes="#//CoreAbstractionsTypedElementsType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" ordered="false"
        upperBound="-1" eType="#//EvaluationLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationExpression" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement #//CoreAbstractionsTypedElementsTypedElement">
    <eOperations name="instantiate" ordered="false" lowerBound="1" eType="#//EvaluationEvaluation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subExpression" upperBound="-1"
        eType="#//EvaluationExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationLiteralExpression" abstract="true"
      eSuperTypes="#//EvaluationExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" ordered="false"
        lowerBound="1" eType="#//EvaluationLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationFeatureAccessExpression" abstract="true"
      eSuperTypes="#//EvaluationExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" ordered="false"
        lowerBound="1" eType="#//CoreAbstractionsClassifiersFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationLiteral" abstract="true" eSuperTypes="#//CoreAbstractionsOwnershipsElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationEvaluation" eSuperTypes="#//CoreAbstractionsElementsElement">
    <eOperations name="initializeSubEvaluations" ordered="false" lowerBound="1"/>
    <eOperations name="updateContext" ordered="false" lowerBound="1">
      <eParameters name="c" ordered="false" lowerBound="1" eType="#//InstanciationInstance"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subEvaluation" upperBound="-1"
        eType="#//EvaluationEvaluation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        lowerBound="1" eType="#//InstanciationValue" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationBehavioralFeatureAccessExpression"
      abstract="true" eSuperTypes="#//EvaluationBehavioralFeatureAccess #//EvaluationFeatureAccessExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationBehavioralFeatureAccess" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
        eType="#//EvaluationExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavioralFeature" ordered="false"
        lowerBound="1" eType="#//CoreAbstractionsBehavioralFeaturesBehavioralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationProcess" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement">
    <eOperations name="consume" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="listener" ordered="false" lowerBound="1" eType="#//CommunicationListener"/>
      <eParameters name="event" ordered="false" lowerBound="1" eType="#//CommunicationEvent"/>
    </eOperations>
    <eOperations name="run" ordered="false" lowerBound="1"/>
    <eOperations name="start" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" ordered="false"
        upperBound="-1" eType="#//CommunicationListener" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationEventType" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement #//CoreAbstractionsTypedElementsType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationContext" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement">
    <eOperations name="update" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" ordered="false"
        upperBound="-1" eType="#//CommunicationProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pendingEvents" ordered="false"
        upperBound="-1" eType="#//CommunicationEvent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationListener" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement">
    <eOperations name="listensTo" ordered="false" lowerBound="1" eType="#//PrimitiveTypesBoolean">
      <eParameters name="e" ordered="false" lowerBound="1" eType="#//CommunicationEvent"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationEvent" eSuperTypes="#//CoreAbstractionsElementsElement #//InstanciationValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationInput" abstract="true"
      eSuperTypes="#//CoreAbstractionsClassifiersFeature #//CoreAbstractionsTypedElementsTypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationMedium" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedClassifier" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//CommunicationCommunicator" eOpposite="#//CommunicationCommunicator/medium"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationCommunicator" abstract="true"
      eSuperTypes="#//CoreAbstractionsElementsElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="medium" ordered="false"
        upperBound="-1" eType="#//CommunicationMedium" eOpposite="#//CommunicationMedium/associatedClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdlSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//SdlPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" eType="#//SdlAgent"/>
  </eClassifiers>
</ecore:EPackage>
