<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="example" nsURI="org.example" nsPrefix="example">
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mp3s" upperBound="-1" eType="#//MP3"
        transient="true" eOpposite="#//MP3/player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MP3">
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Player" transient="true" resolveProxies="false" eOpposite="#//Player/mp3s"/>
  </eClassifiers>
</ecore:EPackage>
