<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abebibidaboes" nsURI="http://hub.de/rcore/examples/abebibidaboes" nsPrefix="gml">
  <eClassifiers xsi:type="ecore:EClass" name="DinulAufribiBoguBigubifrinulaugutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriBubonulAuFrifrigugusnus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusDaBebiBinulauBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGunulaufriBefrifriDaGubetor" ordered="false" upperBound="-1" eType="//EbuBubobuGunulius" eOpposite="//EbuBubobuGunulius/euGubobebuBobetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubiguGugusbugusGusBoBuFribuGusTus" instanceTypeName="typeAlbedaNulAuGudafribebuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBiFriBoGubugudafrifridacus" eSuperTypes="//DuFriBubonulAuFrifrigugusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufrifriFribebiboFriguguslius" ordered="false" eType="//AGusDaBebiBinulauBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuguFrigusnulauboDaTor" eSuperTypes="//DinulAufribiBoguBigubifrinulaugutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubefriFrifribulus" eType="//AubiguGugusbugusGusBoBuFribuGusTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafribeGusgugugucus" ordered="false" eType="//BifrinulauDagubunulaubibulus" eOpposite="//BifrinulauDagubunulaubibulus/efridaBibeNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuguDadabuBoguslus" eSuperTypes="//AGusDaBebiBinulauBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albuBibuguguNulaubefrinulaubuGuses" ordered="false" eType="//AlbuguFrigusnulauboDaTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbuBeboNulius" instanceTypeName="typeDubibuBeBodagusNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubibiNulAububiBees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusbuBeBibebonulautor" upperBound="-1" eType="//BibudanulAuBunulius" eOpposite="//BibudanulAuBunulius/ebugubudanulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABibenulauboguBees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebidadanulauBibidaBitus" ordered="false" eType="//BiBiFriBoGubugudafrifridacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbuBubobuGunulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aDaNulaubogusgubiGusbiGubodacio" eType="//AnbuBeboNulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibebuGunulAuguGusBoBegutus" ordered="false" upperBound="-1" eType="//BiBiFriBoGubugudafrifridacus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubenulauguBiboNus" ordered="false" eType="//AubibiNulAububiBees"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGubobebuBobetin" eType="//AGusDaBebiBinulauBilus" eOpposite="//AGusDaBebiBinulauBilus/anGunulaufriBefrifriDaGubetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbogusbiGuGusbinulIus" abstract="true" eSuperTypes="//DinulAufribiBoguBigubifrinulaugutin //EbuBubobuGunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBufridagusgusAuDadaes" eType="//AnbuBeboNulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biFriBeguGuBubobibecio" eType="//AubiguGugusbugusGusBoBuFribuGusTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBiBedaBogusGusbudaNulAutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGusbubodabifriGunulauLus" ordered="false" upperBound="-1" eType="//AGusDaBebiBinulauBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BafrigusgusdanulAunulIus" instanceTypeName="typeBaguBuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibudanulAuBunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGusbibeDaDabudaLius" ordered="false" upperBound="-1" eType="//AuguDadabuBoguslus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebugubudanulius" ordered="false" upperBound="-1" eType="//AubibiNulAububiBees" eOpposite="//AubibiNulAububiBees/bagusbuBeBibebonulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAunulAutin" instanceTypeName="typeBeGusnulaubebuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Begusgubogusgufribibogusbibebecio" eSuperTypes="//AGusDaBebiBinulauBilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFriboNulAubodaBobitor" instanceTypeName="typeDaDabufridatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Audafrigusbogustor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabogubinulaufriBecus" eType="//AnbuBeboNulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digugusboCus" eType="//AubiguGugusbugusGusBoBuFribuGusTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBogubigusGunus" eType="//AnbuBeboNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibibobubuDafrilius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiboBigusdaGunulius">
    <eLiterals name="EFribebudafribufridagusbies"/>
    <eLiterals name="AnulaudaguboDaboBiTus"/>
    <eLiterals name="DiBudaGusbigufrigusdatin"/>
    <eLiterals name="Bebunulaubogufribedagusgugusnus"/>
    <eLiterals name="DogusFrigudagusBetus"/>
    <eLiterals name="BrAunulaudagudagusbues"/>
    <eLiterals name="BrAunulAuNulauguBibobobigulius"/>
    <eLiterals name="DoFribuDabifriboguBeTor"/>
    <eLiterals name="BraudaBebobigusgubigusDatus"/>
    <eLiterals name="AlfrinulaugunulauboNulAugusbenulAuNus"/>
    <eLiterals name="DagububoBebuBigusbucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusgusbeBedaNulauDadatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Be" eSuperTypes="//Audafrigusbogustor //EbuBubobuGunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aGusBobibodacus" eType="//BrAunulAutin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="egudaBugugusNulAuBibulus" ordered="false" upperBound="-1" eType="//EbuBubobuGunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifrinulauDagubunulaubibulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efridaBibeNulautin" ordered="false" upperBound="-1" eType="//AlbuguFrigusnulauboDaTor" eOpposite="//AlbuguFrigusnulauboDaTor/dafribeGusgugugucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alAuBibeGunulaufrinulaugusBoes" ordered="false" upperBound="-1" eType="//ABibenulauboguBees"/>
  </eClassifiers>
</ecore:EPackage>
