<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="a" nsURI="http://hub.de/rcore/examples/a" nsPrefix="YZXW">
  <eClassifiers xsi:type="ecore:EEnum" name="AugugubudabebuBibifribibibulius">
    <eLiterals name="Edagusaudaes"/>
    <eLiterals name="BabobuBedadabobebibubuBuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AgugusgudabiBebicio">
    <eLiterals name="BinulAuFriBinulaubinulautin"/>
    <eLiterals name="EufribinulaudaGubiNus"/>
    <eLiterals name="Bibugusbunulaugusfribotin"/>
    <eLiterals name="DobenulaugusNulaubudaCio"/>
    <eLiterals name="FaGusbuGusnulaubibiNulAutus"/>
    <eLiterals name="BabobibubeguBenulaufrinulAuNulAuFriCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBebogusbiBidatin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadabeTin" abstract="true" eSuperTypes="//FaBebogusbiBidatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abunulaubedabebibodadacio" ordered="false" eType="//FaBebogusbiBidatin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbenulAuBuboGuFries" ordered="false" eType="//FaBebogusbiBidatin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euGusbebilius" eType="//AgugusgudabiBebicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubifrinulAuBiBoes" eSuperTypes="//FaBebogusbiBidatin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diGubeguBucus" eType="//AgugusgudabiBebicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="afrigusdaDaBeBoLus" ordered="false" upperBound="-1" eType="//EubifrinulAuBiBoes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bibibidabinulaufribufries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBibobubobibeGuBebetus" eType="//AgugusgudabiBebicio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baBoGuBolus" upperBound="-1" eType="//AgugusgudabiBebicio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusbiguFribefricio" ordered="false" eType="//FaNulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaubigubodabeBeButor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedanulauBufrigusfrinulaubeboNus" ordered="false" eType="//FaNulaucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAunulaubugusgusbubuGuboBitor" ordered="false" eType="//FadabeTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGuDaBiGusGufribiguGusBiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuDabebiBeBofritin" ordered="false" eType="//FadabeTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBugusGugusGusboboGudabeGuGunulius" ordered="false" upperBound="-1" eType="//FadabeTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabegusBogusgusAubuBufrifrifribiboguscio" abstract="true" eSuperTypes="//FaBebogusbiBidatin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aucus" eType="//AugugubudabebuBibifribibibulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eunulaugugusgusbufrifrilius" eSuperTypes="//EubifrinulAuBiBoes //Bibibidabinulaufribufries"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAuBinulAuboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbinulauguDanulauBuBiCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboDaboGusdaGusGubegues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anaunus" eType="//AugugubudabebuBibifribibibulius" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
