<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="altin" nsURI="http://hub.de/rcore/examples/altin" nsPrefix="vD">
  <eClassifiers xsi:type="ecore:EClass" name="FaNulAuBebunulAudaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBubefrigusbenulAubicus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusNulAudalus" ordered="false" upperBound="-1" eType="//FaNulAuBebunulAudaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidagusbebiGusgubibigusgusNus" eSuperTypes="//FaNulAuBebunulAudaTus //BiBubefrigusbenulAubicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusboGusgunulAugutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifribubiBobeboGues" ordered="false" upperBound="-1" eType="//FaNulAuBebunulAudaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibiBiGusBuDabucio" eSuperTypes="//BiBubefrigusbenulAubicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBuBeboGusnulaubonus" eSuperTypes="//BiBubefrigusbenulAubicus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAunulauGusboFribiboboGuBeFribicus" ordered="false" upperBound="-1" eType="//FaNulAuBebunulAudaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabeBugusboDacio" eSuperTypes="//BidagusbebiGusgubibigusgusNus //AngusboGusgunulAugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaubenulAunulauDaLus" eSuperTypes="//BidagusbebiGusgubibigusgusNus //BiBuBeboGusnulaubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuBibuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaunulaubudabudaCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfrigugunulAubobuBegucus" ordered="false" eType="//EbuBibuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnaunulAuboGusdabobebegufribiBilus" eSuperTypes="//FaNulAuBebunulAudaTus //DabeBugusboDacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriDagusgusNulAuDabiBugutus" abstract="true" eSuperTypes="//BidagusbebiGusgubibigusgusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulaubifribuBubegufriBobitor" eType="//BaFrinulaugusgusfriBogubinus" eOpposite="//BaFrinulaugusgusfriBogubinus/digusgugusbodabuNulAubobees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauboNulaugusaudalus" abstract="true" eSuperTypes="//BiBuBeboGusnulaubonus //DabeBugusboDacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFrinulaugusgusfriBogubinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusgugusbodabuNulAubobees" eType="//EufriDagusgusNulAuDabiBugutus" eOpposite="//EufriDagusgusNulAuDabiBugutus/auNulaubifribuBubegufriBobitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuDaDafribebigusnus" abstract="true" eSuperTypes="//BiBuBeboGusnulaubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Benulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAuFribiguslius" abstract="true" eSuperTypes="//FaNulAuBebunulAudaTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBubobefribogusnulAuDadabubuBocio" ordered="false" upperBound="-1" eType="//BaFrinulaugusgusfriBogubinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFribiGugusguDagusbiBudaNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBobubobugusfrinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabifribobiBubenulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Etor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBinulauBinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbiGusaugusauNulauBuFrifrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBoBeBinus" ordered="false" eType="//BiBubefrigusbenulAubicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboGusFriFrigusbuBies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulAugusgusdaLius" eSuperTypes="//AuBinulauBinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bibobibibonulaunulaugusfritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAudaboBobobugunulaunulAuFriGutor" eSuperTypes="//BrauboNulaugusaudalus //Etor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaunulAugusbuLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnDaBoBoBoBedalus" instanceTypeName="typeDiBiDafriBidanulauboGusdabebugusGusgunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuguguFriDabedalius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babolius" upperBound="-1" eType="//AnDaBoBoBoBedalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubobubudagugubeButin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audaGunulAutin" ordered="false" eType="//BibiBiGusBuDabucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusguGucio" abstract="true" eSuperTypes="//EubobubudagugubeButin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuBoFridaBogusgusgusdafrifriGues" eSuperTypes="//BaFrinulaugusgusfriBogubinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebuDaNulAufribinus" ordered="false" eType="//Etor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beDaFribuGusGubiNulAugugusboBuTin" ordered="false" upperBound="-1" eType="//DobebofridagusgusfriBilius" eOpposite="//DobebofridagusgusfriBilius/daGubeBenulaugusaubebitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EboNulauBuBeBidaGuboLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebuBegusAubeguGufriLus" ordered="false" eType="//FagusguGucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbiBinulauTus">
    <eLiterals name="BegusguGusNulauBilus"/>
    <eLiterals name="DuBobigubibeDagusDabuLius"/>
    <eLiterals name="AgubuBedabiBeTor"/>
    <eLiterals name="AnGubiDaFriguboBububicus"/>
    <eLiterals name="Augudabubelius"/>
    <eLiterals name="DibudaBoBuGuboFritor"/>
    <eLiterals name="AnGubogusaudafricio"/>
    <eLiterals name="BaNulaugusgusbibitin"/>
    <eLiterals name="FaBugubefrifriBudaNulauNulaubulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeDaBedaBeboboButin" abstract="true" eSuperTypes="//AuDaDafribebigusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABebobiGuguNulAuguGues" eSuperTypes="//FagusguGucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbiGusBifrigusbocio" ordered="false" upperBound="-1" eType="//FagusguGucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabeguDabonulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobebofridagusgusfriBilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGubeBenulaugusaubebitus" eType="//DibuBoFridaBogusgusgusdafrifriGues" eOpposite="//DibuBoFridaBogusgusgusdafrifriGues/beDaFribuGusGubiNulAugugusboBuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibonulAugusfriBodaBebobenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabubifriBeNulaugusfriGusnus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAuGusNulAuBenulaucio" eSuperTypes="//Etor //BanulAuFribiguslius //BaFrinulaugusgusfriBogubinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augubebudanulius" eType="//EbiBinulauTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafrigubedabeFribugusbiBoLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubiBeBofriGudadaNulaulus" eType="//AnDaBoBoBoBedalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadaboGuBubugusbiCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusnulAuNulAuGufriGugubedadafritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagubiFribebiBeboboDanulauDaTor" ordered="false" upperBound="-1" eType="//EbiGusaugusauNulauBuFrifrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulauBoBebugusdabuguslius" eSuperTypes="//BaFrinulaugusgusfriBogubinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabiFribuFriGusTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="altus" eType="//AnDaBoBoBoBedalus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulAubiBedaBoNulaufriFriGusBoguTus" ordered="false" eType="//AunulaubenulAunulauDaLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adadaBuFriBulius" ordered="false" upperBound="-1" eType="//BiboGusFriFrigusbuBies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBudabiDaTor" eSuperTypes="//BrauFribiGugusguDagusbiBudaNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfriboguBoDanulaubugunulius" ordered="false" upperBound="-1" eType="//FaNulAuBebunulAudaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBebuNulAubebidaGusaugugustor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusnulauDaGusnulAugusFricio" ordered="false" upperBound="-1" eType="//EGudabeBenulAugusauguLus" eOpposite="//EGudabeBenulAugusauguLus/fagusbibebunulaugubufrinulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BanulauBinulaunulAuBegusBitor">
    <eLiterals name="AndagubobuGusgusbetus"/>
    <eLiterals name="EuguFridadacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGudabeBenulAugusauguLus" eSuperTypes="//FafrigubedabeFribugusbiBoLius //BidagusbebiGusgubibigusgusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusbibebunulaugubufrinulEs" ordered="false" upperBound="-1" eType="//DoBebuNulAubebidaGusaugugustor" eOpposite="//DoBebuNulAubebidaGusaugugustor/agusnulauDaGusnulAugusFricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubibobefrifrinulAubodator"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoboNulAuBuGusgusbiFriNulius" instanceTypeName="typeBrauGusBiBiBebuBobiNulaucio"/>
</ecore:EPackage>
