<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bibues" nsURI="http://hub.de/rcore/examples/bibues" nsPrefix="lD">
  <eClassifiers xsi:type="ecore:EClass" name="DodanulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DunulaugusauNulAuguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulauDadaGusBubeGulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabiboGusDadagusbibofrilius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DogusGugubogusbues">
    <eLiterals name="BeBebuBubobubuBobunulaudaTin"/>
    <eLiterals name="AnaunulaufribeBobecus"/>
    <eLiterals name="BeDabuboGunulaufriBeTor"/>
    <eLiterals name="DabeBofribidaBeNus"/>
    <eLiterals name="DuBiNulAugusbinulAuBebolus"/>
    <eLiterals name="AlboBoBiGusfrigusnus"/>
    <eLiterals name="AnbifrinulAubiGunulaulius"/>
    <eLiterals name="DobeGuBoCus"/>
    <eLiterals name="FanulaubibeNulauBoguGuBuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuboguguFrilus" instanceTypeName="typeDugusAuGudabeBudabebobogusBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibubefriBugudagudanus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EbedaBigusdaGubeguEs">
    <eLiterals name="DodabuBeBobefrinus"/>
    <eLiterals name="EgubeNulaubegudatin"/>
    <eLiterals name="BigusfrifribufribogugubobubuBuDabugulus"/>
    <eLiterals name="DobedagusfriboGunulIus"/>
    <eLiterals name="AunulauboGunus"/>
    <eLiterals name="BraubonulauGusnulaufrinulAuBoTin"/>
    <eLiterals name="DagusbigusbobedanulauFridagusfricus"/>
    <eLiterals name="DogusgubobeGuGubufribiBuGudalius"/>
    <eLiterals name="DaBeGusBiBogusbecio"/>
    <eLiterals name="BifriGuboNulAucio"/>
    <eLiterals name="AnbedabuDabeNus"/>
    <eLiterals name="BebebonulaubuGusbigusnulaubodaguCio"/>
    <eLiterals name="DofribebuBigucio"/>
    <eLiterals name="DobifrifriBeBobinules"/>
    <eLiterals name="BebuboGusbifriguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBogufribefribonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibugusbibuboDafriboGusbenulauFrifritus" eType="//DunulaugusauNulAuguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibuGuboFridafribeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfriboBobibues" ordered="false" upperBound="-1" eType="//DunulaugusauNulAuguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusbonulauBoes" abstract="true" eSuperTypes="//DibubefriBugudagudanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibubeBubefriFrilus" ordered="false" upperBound="-1" eType="//BibuGuboFridafribeLius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anFribedabobenulaunus" eType="//EbedaBigusdaGubeguEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AfrinulaubebuBibebigusnulIus">
    <eLiterals name="Anfridabodagubebubicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubuBobefriDaboGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufribodabodagusgubuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadaBobegubitor" eSuperTypes="//BabiboGusDadagusbibofrilius //BenulauDadaGusBubeGulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AdaGusGusbububunulauGuBufriBogusgusgububoTus" instanceTypeName="typeBaBedaBofrigudaEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Edanulaucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadaBiBinulAuGucio" eSuperTypes="//AlBogufribefribonus //DibubefriBugudagudanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGufrigustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriBeguGusGunulaubeEs" eSuperTypes="//DodanulAunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusBoGubidaBuDabiCus" ordered="false" eType="//AubuBobefriDaboGulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eDaBobeBitor" eType="//DogusGugubogusbues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusGugusDagunulaufridanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldaBebonulAunulauDagubolus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dadabelus" eType="//AdaGusGusbububunulauGuBufriBogusgusgububoTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusgusDaEs" eSuperTypes="//DunulaugusauNulAuguses //FadaBobegubitor //BagusGugusDagunulaufridanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifribibofriNus" ordered="false" upperBound="-1" eType="//BagusGugusDagunulaufridanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadaguBubuDabocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabenulaubitor" eType="//EuboguguFrilus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubufriboGusfrigusdaBogusaunulaubelius" instanceTypeName="typeEuFrifrigusaububofribugubocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauDabiBenulAubelius" abstract="true" eSuperTypes="//AgusgusDaEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigunulaunulauboBibobibebugudagunus" eSuperTypes="//BibuGuboFridafribeLius //BabiboGusDadagusbibofrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusdaBogusgutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbebiBibiFribugufrifribilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibefrigusguboFriBuBeGuGuBelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albububiBiDaBeboNulAudalius" ordered="false" upperBound="-1" eType="//BadaguBubuDabocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusAuguBuboBuboNulauguslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubobubigusgubebeFriGufriGusBiBecus" ordered="false" eType="//DufriBeguGusGunulaubeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBonulaunulAuNulAubeCus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afribenulaufritus" eType="//AdaGusGusbububunulauGuBufriBogusgusgububoTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubigusbuGunulauBibuboBonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulAugusaubogusBuboBoButus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiDaNulaugubunulAudabuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doNulAufriNulAubeNulaugustin" ordered="false" eType="//DunulaugusauNulAuguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bebobugunulius" eSuperTypes="//DufriBeguGusGunulaubeEs //BenulauDadaGusBubeGulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBibigufriguFriDaboNus" instanceTypeName="typeAboGusfriguNulaubilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusdaBegusGuFrinulaucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubidaGusaubibeguTin" eType="//EuboguguFrilus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnguBibibiBudabebifrinulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubigugudaGusguNus" instanceTypeName="typeBibinulAunulauGusBebobobuCus"/>
</ecore:EPackage>
