<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eubebotin" nsURI="http://hub.de/rcore/examples/eubebotin" nsPrefix="eo">
  <eClassifiers xsi:type="ecore:EClass" name="AnbufriBofribuFriGutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusFrigusaubedaBonulaucio" eType="//BrAuFriFriguNulAuDaBebeguGusLus" eOpposite="//BrAuFriFriguNulAuDaBebeguGusLus/anfridabedanulAubobobuCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuFriFriguNulAuDaBebeguGusLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfridabedanulAubobobuCus" ordered="false" upperBound="-1" eType="//AnbufriBofribuFriGutus" eOpposite="//AnbufriBofribuFriGutus/eugusFrigusaubedaBonulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibigusfribonulauDadagubutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusbugusbedabonulAuBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusaubobiFrifrinus" eSuperTypes="//BrAuFriFriguNulAuDaBebeguGusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbubeBedaNulaufrinulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dubobonulaugugubugulus" instanceTypeName="typeBeNulauDagubudabigusBiboboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadadaFrigubifriNulauguses">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabuboNulaucus" eType="//Dubobonulaugugubugulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBeNulauFriGusfritin" eSuperTypes="//EbubeBedaNulaufrinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euboDaBoNulauFribeBifrigusBuGusbeLus" ordered="false" eType="//AugusaubobiFrifrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudagusBedabuboBefriboTin" eSuperTypes="//EbubeBedaNulaufrinulius //AnbufriBofribuFriGutus //AlbibigusfribonulauDadagubutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGusaunulaubefribifritin" ordered="false" eType="//AlbibigusfribonulauDadagubutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AdabeBugustus" instanceTypeName="typeAngusgubibuNulaufriNulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBebefriguses" eSuperTypes="//BigusbugusbedabonulAuBitor //EbubeBedaNulaufrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braugubicus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EufriBibiGusGuCus">
    <eLiterals name="BaBigusbeBoDaFriguLius"/>
    <eLiterals name="DaboTus"/>
    <eLiterals name="AubobeDaNulAubidadator"/>
    <eLiterals name="BebiBeBugubefrinulAugusbeTus"/>
    <eLiterals name="AGusGugubotin"/>
    <eLiterals name="DigusbebenulauboBeDabubenulauNus"/>
    <eLiterals name="EuBofriBicio"/>
    <eLiterals name="BaFriboBofribufrifrigubiNulius"/>
    <eLiterals name="DiBiNulaucio"/>
    <eLiterals name="EfribobubufriBigubugusnulautin"/>
    <eLiterals name="EbugusaugusBegufriNules"/>
    <eLiterals name="DobuboBulius"/>
    <eLiterals name="DaGusbeguguNules"/>
    <eLiterals name="BrAufriFrifridaboguBetus"/>
    <eLiterals name="BeGuDadabiBibeGubodacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubonulAuguBigubuCus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBibubedagusbeGusgusbuBiGusNus" ordered="false" eType="//AlBeNulauFriGusfritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabeFritor" eSuperTypes="//EubonulAuguBigubuCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubenulAubibuDabeNulIus" eType="//AdabeBugustus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafribobiFries" eSuperTypes="//AnbufriBofribuFriGutus //FabeFritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAunulaudaboBodacio" upperBound="-1" eType="//BigusbugusbedabonulAuBitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulauNulauGusnulius" eSuperTypes="//EbubeBedaNulaufrinulius //FabeFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibiGuBogugusAuDagusgusnulaubobiNus" eSuperTypes="//AlBeNulauFriGusfritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBuBobuBefrigusBenulAulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulAuFribinulaugusbedaTin" ordered="false" upperBound="-1" eType="//DudagusBedabuboBefriboTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBeBegufrigugusCus" eSuperTypes="//DaBuBobuBefrigusBenulAulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBigusGusnulaudaDaBegusbotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFriGuDabigusnules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBeDanulaudabuBibobuBocio" ordered="false" upperBound="-1" eType="//DoNulAuguslus" eOpposite="//DoNulAuguslus/fabiDaLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Braubofricus">
    <eLiterals name="DobugubeBedaGufribodaBofriLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Augusbubidafridabetus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBebonulaubiGusDabucio" ordered="false" eType="//AnbufriBofribuFriGutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiFriguBucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulAuguslus" eSuperTypes="//FabeFritor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auBuDaBoFrinulaudadabodaBobulus" eType="//Dubobonulaugugubugulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiDaLius" upperBound="-1" eType="//FaFriGuDabigusnules" eOpposite="//FaFriGuDabigusnules/auBeDanulaudabuBibobuBocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbubobegudabubobiguEs" eSuperTypes="//Braugubicus //DaBuBobuBefrigusBenulAulus //FaFriGuDabigusnules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogusbunulaububeGusBigubeguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFriboguguses" eSuperTypes="//BiBeBegufrigugusCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braunulAunulauBibotin" eType="//AdabeBugustus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusGugusgusFries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufribinulAuDadator" eType="//Dubobonulaugugubugulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfriNulAugufrigusTor" ordered="false" eType="//EguDadatin" eOpposite="//EguDadatin/dabobogusdaGusbifriBiLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlauBeguBedagusDabidanules" abstract="true" eSuperTypes="//DibiGuBogugusAuDagusgusnulaubobiNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBidafrifrinulauBubeDaBoBubeNulIus" instanceTypeName="typeBraubebuGusBubeguguTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabobebobeboGusbotin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaFrifriDagubedaBoLius" instanceTypeName="typeAugusGunulaubegusBotin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubibigunulAugugusboTin" instanceTypeName="typeAnBonulaugusBuBunulaubidaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguDadatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babidabobitus" ordered="false" eType="//AlbibigusfribonulauDadagubutus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faDafribiFribegusaunulAucio" eType="//DaFrifriDagubedaBoLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabobogusdaGusbifriBiLius" ordered="false" upperBound="-1" eType="//DigusGugusgusFries" eOpposite="//DigusGugusgusFries/alfriNulAugufrigusTor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anfriBuFrigusdacio" eType="//EufriBibiGusGuCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubuBibibofriDanulAunulaubuFriButus" eSuperTypes="//FafribobiFries"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DugudagusbobeGugubuNulius">
    <eLiterals name="AuDabibuNulaunulaufriNulaubeBilus"/>
    <eLiterals name="BefriBigusboBeBebidaTor"/>
    <eLiterals name="BaGuBunulauFrinulAuFriguBucio"/>
    <eLiterals name="EGubogusbugusBebubodaBebotus"/>
    <eLiterals name="EBegubibodagusius"/>
    <eLiterals name="DigugusBiDabegufribigucio"/>
    <eLiterals name="BigusdaGusdabogufribobegusGuses"/>
  </eClassifiers>
</ecore:EPackage>
