<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dudabigulius" nsURI="http://hub.de/rcore/examples/dudabigulius" nsPrefix="yPV">
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulaubeBufriBuFribitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabugusfridaBidaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaufriBegusgusGuDanus" eSuperTypes="//BrauNulaubeBufriBuFribitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusbunulaubenulius" eSuperTypes="//DabugusfridaBidaCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabuGusbegusGudanulaugusGudafries" instanceTypeName="typeBrAugusfribuguGusDaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogubebidafriGuses" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiboDaGulius" eSuperTypes="//BrauNulaubeBufriBuFribitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusbeGubebiBiboGubiGubibubuBuGusbibubolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubibidaNulAutin" ordered="false" upperBound="-1" eType="//DabunulaudaNulaugufribigutin" eOpposite="//DabunulaudaNulaugufribigutin/biBiBogusauTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGubunulauBiDanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBefridafrigusdaBebogusBulus" ordered="false" eType="//BiGusbunulaubenulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubinulAuNulaugusCio" instanceTypeName="typeAlbinulaunulaudafrigustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnAuGusbefridaguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiDabodabiGuboGubinulAuguBoes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulauGusnulaunulaubonules" abstract="true" eSuperTypes="//DabugusfridaBidaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusBoBobubebebudalus" ordered="false" eType="//BrauNulaubeBufriBuFribitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="badabubeguGubeboBuFriGusbeboGuEs" ordered="false" upperBound="-1" eType="//AugugusdanulaubidaDadagubuTor" eOpposite="//AugugusdanulaubidaDadagubuTor/alnulaugusfribigufriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulauDafrifribibuBulius" eSuperTypes="//DogubebidafriGuses //EGubunulauBiDanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnDabubebudadaTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abufrinulaubebiLius" eType="//AuNulauBoDaGugusFriBobegustin" eOpposite="//AuNulauBoDaGugusFriBobegustin/algudagusBunulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dabibigusbebolius" eSuperTypes="//DogubebidafriGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBuboGusBoDabigufribiGusbutin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibifrigubunulAuboDabibibobucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagusGusauFricio" eType="//EubinulAuNulaugusCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulauBoDaGugusFriBobegustin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabeNulaudagubicus" eType="//EubinulAuNulaugusCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algudagusBunulaulius" ordered="false" upperBound="-1" eType="//AnDabubebudadaTus" eOpposite="//AnDabubebudadaTus/abufrinulaubebiLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauguGubogusBobofriGusBofrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulautin" ordered="false" upperBound="-1" eType="//DiboDaGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBeDagusgugusbuBuDaFriguNus" eSuperTypes="//DiboDaGulius //BiGusbunulaubenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeBobunus" eSuperTypes="//DibifrigubunulAuboDabibibobucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubebegusDaLus" ordered="false" eType="//DaNulauGusnulaunulaubonules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubobinulaubebebiguBotus" ordered="false" upperBound="-1" eType="//AnDabubebudadaTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusBonulauBigusbibegutus" upperBound="-1" eType="//EBuboGusBoDabigufribiGusbutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubeBigunulaubobeBobeGusbitin" instanceTypeName="typeEudabefrinulAuDaguBeguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabunulaudaNulaugufribigutin" eSuperTypes="//EBuboGusBoDabigufribiGusbutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBiBogusauTor" ordered="false" eType="//DoGusbeGubebiBiboGubiGubibubuBuGusbibubolius" eOpposite="//DoGusbeGubebiBiboGubiGubibubuBuGusbibubolius/aubibidaNulAutin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alDaFridaGuBoboFribeboNulIus" ordered="false" upperBound="-1" eType="//BinulauguGubogusBobofriGusBofrilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufrigusAudaDator" ordered="false" eType="//DinulauNulaugusfribeFriGuBoBuTin" eOpposite="//DinulauNulaugusfribeFriGuBoBuTin/faGusnulAugulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlDaBinulAufrinulaugudagugubebecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENulauboboBububodaTor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabugubebebonulAugusaunus" abstract="true" eSuperTypes="//DaNulauGusnulaunulaubonules //AlDaBinulAufrinulaugudagugubebecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbebiguBigugubeGunulaulius" instanceTypeName="typeABifribuDaBedagustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdaGusbuboTus" eSuperTypes="//BrauNulaubeBufriBuFribitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befrifriFridagusGusBudaGusTin" ordered="false" upperBound="-1" eType="//BebubuFrinulaububibodafricio" eOpposite="//BebubuFrinulaububibodafricio/agubobubobunulaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabugusauboBigubeBuBeFridaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulAuBunulaudabebetin" ordered="false" eType="//EBuboGusBoDabigufribiGusbutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBebodabubidagusdafriNulaudabeGustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubobibobibudaDalus" ordered="false" eType="//EGubunulauBiDanus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adadaNulAuFridaDagusNulAudaNulEs" eType="//AnDabubebudadaTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDabegusbogusBobues" ordered="false" upperBound="-1" eType="//DaNulauGusnulaunulaubonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauNulaugusfribeFriGuBoBuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faGusnulAugulius" eType="//DabunulaudaNulaugufribigutin" eOpposite="//DabunulaudaNulaugufribigutin/eufrigusAudaDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebubuFrinulaububibodafricio" eSuperTypes="//DoGusbeGubebiBiboGubiGubibubuBuGusbibubolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agubobubobunulaunus" ordered="false" upperBound="-1" eType="//AdaGusbuboTus" eOpposite="//AdaGusbuboTus/befrifriFridagusGusBudaGusTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgugubobuBiguBefriDaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBofriGuBoBiBiBeGubobibonulius" ordered="false" upperBound="-1" eType="//DoGusbeGubebiBiboGubiGubibubuBuGusbibubolius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibeboDabegusaulus" eType="//AlbebiguBigugubeGunulaulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbegubibobiDaGuFrigusaubuGusGunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faFridabinulAuBodanulaudagusbiGunulAuLius" ordered="false" upperBound="-1" eType="//DogubebidafriGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoboFrinulAugusaugusbeBonulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anfrigusbonulaubecus" eSuperTypes="//DoGusbeGubebiBiboGubiGubibubuBuGusbibubolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaubofribufribiLus" eSuperTypes="//DinulauNulaugusfribeFriGuBoBuTin //ENulauboboBububodaTor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BeBoBoBiFrifrigusnulius">
    <eLiterals name="EbiboDaBeGusnus"/>
    <eLiterals name="FaGubiFrifrifribeFrigusGusboboBelius"/>
    <eLiterals name="BegunulaububugugudabuCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBuGusGubegutin" eSuperTypes="//BiGusbunulaubenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Angusnulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubuBidabeTus" ordered="false" eType="//DabugusfridaBidaCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbunulauguFrifriLius" ordered="false" eType="//EgugubobuBiguBefriDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaufribogubeBuTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaboBiFrinulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusdabubitus" eType="//AlbebiguBigugubeGunulaulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AngunulauDagusguFrilus">
    <eLiterals name="AlGuBiGugusbigunus"/>
    <eLiterals name="Eububobonulaubufribobenus"/>
    <eLiterals name="AudaGugusbenulaufridaBufribifrinulauCus"/>
    <eLiterals name="AnaudaBeFriBiGusFritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaubenulauNulaugustin" eSuperTypes="//FaBeDagusgugusbuBuDaFriguNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusnulAuGubiGuDabebobuBiBucio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabeBoBinulaubenulautin" eType="//DubeBigunulaubobeBobeGusbitin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBiNulauguGusbecio" ordered="false" upperBound="-1" eType="//BiGusbunulaubenulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BibiBibigunulaudaGuLius">
    <eLiterals name="AldafrinulaubuBufriGubenulIus"/>
    <eLiterals name="DaBedabubobetin"/>
    <eLiterals name="DodanulaubuNulaubebibebulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegugusbogudabiNulaubecio" eSuperTypes="//BrauNulaubeBufriBuFribitor //DabugusfridaBidaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulauboGusBeNulauButin" ordered="false" upperBound="-1" eType="//DigusnulAuGubiGuDabebobuBiBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBifribeDabiBufrigubitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugugusdanulaubidaDadagubuTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulaugusfribigufriEs" ordered="false" upperBound="-1" eType="//DaNulauGusnulaunulaubonules" eOpposite="//DaNulauGusnulaunulaubonules/badabubeguGubeboBuFriGusbeboGuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufrigusbeguboBuBiguses">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulaudagusnulaububoboTus" eType="//DubeBigunulaubobeBobeGusbitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AguBiguNulaubeDagusbibudaEs" instanceTypeName="typeBagusfribobugusguBiBiTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugusNulaubiGusgusLus" instanceTypeName="typeEbugusfridagusnulauBuguboDagusdagusBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabibeGuGusaubenulauGustus" eSuperTypes="//AnDabubebudadaTus //BabugubebebonulAugusaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBubigusbefrifribogusdaes" eSuperTypes="//DibifrigubunulAuboDabibibobucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeBugubeGubebibibuboButor" instanceTypeName="typeDanulauDabecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibobobiGugusFricio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babuguDafridabebicio" ordered="false" eType="//BabugubebebonulAugusaunus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBibodanulaubuBucus" eType="//BeBoBoBiFrifrigusnulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dogusbubunulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBoguBunulAubegudagusnulAuGusguBiBitor" eSuperTypes="//EGubunulauBiDanus //Angusnulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbodabubuBeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbefribefriBobeboTor" ordered="false" upperBound="-1" eType="//EGubunulauBiDanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafriFribuBuBuNulaudafritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabenulauDanulaufrinulaubeBulius" eSuperTypes="//AuNulauBoDaGugusFriBobegustin //DoGusbeGubebiBiboGubiGubibubuBuGusbibubolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaBugusAuCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DabugunulAuBidanulAubibonus">
    <eLiterals name="EdanulaubeBuGuGuBogubuBiCus"/>
    <eLiterals name="EugusbuDaBobidafriBobebuBuBuCio"/>
    <eLiterals name="AuboNulauGusbegusauDadanus"/>
    <eLiterals name="EunulAubogugusauGusbocio"/>
    <eLiterals name="AugugufriBudabuGubeDanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Efrifribebebecio">
    <eLiterals name="DaDabinulaugusNulAubobobilus"/>
    <eLiterals name="BrAuDadabegubebobeDaLius"/>
    <eLiterals name="BrAubigudadabobibeguscus"/>
  </eClassifiers>
</ecore:EPackage>
