<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dibobugubolius" nsURI="http://hub.de/rcore/examples/dibobugubolius" nsPrefix="exw">
  <eClassifiers xsi:type="ecore:EClass" name="AlDagusBoBeboBuBubebenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuGunulauFritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFrifribinulaububifriTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibigudadafriNulAugudaDadafribegusNus" ordered="false" eType="//AlDagusBoBeboBuBubebenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufrifribedaNulaugusfrinules" eSuperTypes="//AlDagusBoBeboBuBubebenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusnulaugubiFricus" ordered="false" eType="//AubodafrinulauGuNulaudagusguFriNus" eOpposite="//AubodafrinulauGuNulaudagusguFriNus/binulaugusnulAudadagusboBunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbuBoFridaBeGubigunulius" instanceTypeName="typeAuDagusgusbeFridaguBufriGutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldabuNulauDabidadabubitor" eSuperTypes="//AlbuGunulauFritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBobeDabuGudagugusnulauCio" upperBound="-1" eType="//AlDagusBoBeboBuBubebenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Braunulaubugufritor" instanceTypeName="typeAuboBigudadatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubodafrinulauGuNulaudagusguFriNus" eSuperTypes="//Dulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaugusnulAudadagusboBunus" ordered="false" upperBound="-1" eType="//DufrifribedaNulaugusfrinules" eOpposite="//DufrifribedaNulaugusfrinules/braugusnulaugubiFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbefrifriFriNulaubeTus" eSuperTypes="//AlbuGunulauFritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafrigusbobeDaBuBiFriBetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBiDaNulaubeBebefribeNus" ordered="false" upperBound="-1" eType="//BaFrifribinulaububifriTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audanulaubenulAuBobonulaucus" eType="//AnbuBoFridaBeGubigunulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bifribudafribubibufribibubuNulIus" eType="//AnbuBoFridaBeGubigunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BefriNulauBunulauBubocio">
    <eLiterals name="DanulaugusFribibeButor"/>
    <eLiterals name="AunulaubiFriCio"/>
    <eLiterals name="BebufrinulAubofriGubugusTor"/>
    <eLiterals name="BenulaububofrigusguGusbeNulauBinus"/>
    <eLiterals name="DubonulauBedaBoes"/>
    <eLiterals name="AnbubiBoboTor"/>
    <eLiterals name="BenulauBoDator"/>
    <eLiterals name="BeBefriDabibiGudaguFrinulIus"/>
    <eLiterals name="AnBenulauFrinulAuFribobibedaEs"/>
    <eLiterals name="DabebidanulAugutus"/>
    <eLiterals name="FaGuBigubebifries"/>
    <eLiterals name="DigusbuBobeboguDaGucio"/>
    <eLiterals name="FabubedaBoBebuFriFribinus"/>
    <eLiterals name="DofrigugubegugusDagugusaubues"/>
    <eLiterals name="BraudaBifribubenulAubues"/>
    <eLiterals name="DiBogusnulius"/>
    <eLiterals name="DiBogusaufriGuGubobobunus"/>
    <eLiterals name="AnAuGusfribinules"/>
    <eLiterals name="AunulauBubegustus"/>
    <eLiterals name="BefriBegusbiBuDaGuGuDaCio"/>
  </eClassifiers>
</ecore:EPackage>
