<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="begusgusnus" nsURI="http://hub.de/rcore/examples/begusgusnus" nsPrefix="WS">
  <eClassifiers xsi:type="ecore:EDataType" name="BanulauFriboBobuFriBoFriBolus" instanceTypeName="typeBibudafribunulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogufrinulaubogusDabeNulauBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBedaGuFriboBeFrilius" abstract="true" eSuperTypes="//DogufrinulaubogusDabeNulauBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguboBebicus" ordered="false" eType="//DogufrinulaubogusDabeNulauBolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidagudaBobeFrigusBucus" eSuperTypes="//DogufrinulaubogusDabeNulauBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGubebubeGubegusBiDaBuBugucio" eSuperTypes="//AuBedaGuFriboBeFrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BibuBegugusaubefritor" instanceTypeName="typeAnauFribuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulAugudatin" ordered="false" eType="//DogufrinulaubogusDabeNulauBolius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufribidatin" eType="//BanulauFriboBobuFriBoFriBolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaudadaGubedaCio" eSuperTypes="//AuBedaGuFriboBeFrilius //BidagudaBobeFrigusBucus //DuGubebubeGubegusBiDaBuBugucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigubedaBobedaLius" ordered="false" upperBound="-1" eType="//Anulaucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaudaFrigusBebuTin" ordered="false" upperBound="-1" eType="//BraufrigugufribuGuDabecus" eOpposite="//BraufrigugufribuGuDabecus/bagusbugubobitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuFriFrilius" instanceTypeName="typeDunulauBegusDabugusAubetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBidabibugubofrilius" abstract="true" eSuperTypes="//AuBedaGuFriboBeFrilius //AnulaudadaGubedaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubugufrifriDafribubiGutus" eSuperTypes="//AuBedaGuFriboBeFrilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogusnulaugusnulAuDadacio" eType="//BibuBegugusaubefritor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusnulauBoBedaDafrifrifriNulauBiNus" abstract="true" eSuperTypes="//BidagudaBobeFrigusBucus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbidabobiGusdabuGusbudaGuLus">
    <eLiterals name="AnbibunulaubunulaugubeBuDabubitus"/>
    <eLiterals name="BraubugusnulaugusNulauBoFrifricio"/>
    <eLiterals name="EGuGugufriFridabutus"/>
    <eLiterals name="EunulAugusgusbufribigugugustus"/>
    <eLiterals name="AubibebiboBeBeGubeButus"/>
    <eLiterals name="DuBobeBuGusBonulius"/>
    <eLiterals name="EunulAubuGusbeBibuFribenulaubenulaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraufrigugufribuGuDabecus" eSuperTypes="//AubugufrifriDafribubiGutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBubifriBegufriGubeGunus" eType="//AnulaudadaGubedaCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusbugubobitor" ordered="false" upperBound="-1" eType="//AnulaudadaGubedaCio" eOpposite="//AnulaudadaGubedaCio/binulaudaFrigusBebuTin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dutin" eType="//AlbidabobiGusdabuGusbudaGuLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doNulAuBigugubebogufriboGues" ordered="false" eType="//DuGubebubeGubegusBiDaBuBugucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DadadaFrifriBibigubebebeguNulIus" instanceTypeName="typeBegusgubinulaufriguguBeDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidaFridagusdabobubitor" eSuperTypes="//AlGusnulauBoBedaDafrifrifriNulauBiNus //DuGubebubeGubegusBiDaBuBugucio"/>
</ecore:EPackage>
