<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="faes" nsURI="http://hub.de/rcore/examples/faes" nsPrefix="QUV">
  <eClassifiers xsi:type="ecore:EClass" name="Dunulaunulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibefriGugusauguboes" ordered="false" eType="//AgubugugubibeGubogubunus" eOpposite="//AgubugugubibeGubogubunus/eubugubudaBedaBetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaubuBibeDabitin" eSuperTypes="//Dunulaunulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBibedaes" eSuperTypes="//DonulaubuBibeDabitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobubuBofriGuslus" ordered="false" upperBound="-1" eType="//Dunulaunulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgubugugubibeGubogubunus" eSuperTypes="//DiBibedaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubugubudaBedaBetus" ordered="false" upperBound="-1" eType="//Dunulaunulaulus" eOpposite="//Dunulaunulaulus/bibefriGugusauguboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbobebeboBogububeCio" eSuperTypes="//DiBibedaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubogusBubogugulus" ordered="false" upperBound="-1" eType="//BraubiBubucus" eOpposite="//BraubiBubucus/euBofrinulAububeGubulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubiBubucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBofrinulAububeGubulus" ordered="false" upperBound="-1" eType="//AbobebeboBogububeCio" eOpposite="//AbobebeboBogububeCio/braubogusBubogugulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebuDaguFritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didagusbufriLius" ordered="false" eType="//BraubiBubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuFriFriNulauDaNulAubedagusBolus" instanceTypeName="typeBeFribobuboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabufridaBubiFrifriBibunulEs" eSuperTypes="//Dunulaunulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andaguLus" ordered="false" eType="//Dunulaunulaulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGusAuBigufribibofribebubies" ordered="false" upperBound="-1" eType="//DiBibedaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebibugusbeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGubefrigufrifriBibofritor" ordered="false" upperBound="-1" eType="//Dunulaunulaulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauguGuscio" eType="//AngubugugusnulaunulaugugunulAubuGusBeNus" eOpposite="//AngubugugusnulaunulaugugunulAubuGusBeNus/doguguBiGuGubobiGugucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnulauBuBebifrigues">
    <eLiterals name="FaDanulAubutus"/>
    <eLiterals name="AlDabudafribufrilus"/>
    <eLiterals name="AGusbiTin"/>
    <eLiterals name="Bigubububebees"/>
    <eLiterals name="BeNulaubeBues"/>
    <eLiterals name="AlfridabuguguBubiGustin"/>
    <eLiterals name="AldaEs"/>
    <eLiterals name="DoBiGuBonulaubuBofriBibebuNus"/>
    <eLiterals name="DugufriGusfriDadaBiBubufrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebeGusnulAugusauGues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dodaNulAugusguGunulius" eType="//DuFriFriNulauDaNulAubedagusBolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusFriboBibunulAuBeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadabuGunulaububies" ordered="false" upperBound="-1" eType="//BraubiBubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngubugugusnulaunulaugugunulAubuGusBeNus" eSuperTypes="//BebibugusbeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusNulAudafriguTus" eType="//BebeGusnulAugusauGues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doguguBiGuGubobiGugucio" ordered="false" eType="//BebibugusbeTor" eOpposite="//BebibugusbeTor/brauguGuscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfriNulauBodabonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubenulaugusDagusaubotin" ordered="false" eType="//AbobebeboBogububeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnCus" eSuperTypes="//DonulaubuBibeDabitin //BraubiBubucus //BebeGusnulAugusauGues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agudagusbeGuNulAuDadaboEs" ordered="false" upperBound="-1" eType="//BebeGusnulAugusauGues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eububoBifriDaFritin" eType="//BebibugusbeTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibubebibifribugusNulauBobiCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="efriGudabinulaucus" upperBound="-1" eType="//EnulauBuBebifrigues" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubegubeNulaugudaBicus" upperBound="-1" eType="//DagusFriboBibunulAuBeLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnauBiboGufriDabunulAunulaubuTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuguGubobobeGudabiDadadaes" eSuperTypes="//BebuDaguFritor //AnCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efrinulaudabufrinulAubigubibogulus" ordered="false" upperBound="-1" eType="//DibubebibifribugusNulauBobiCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlGusbiBoBefrigubinulaulius">
    <eLiterals name="BebubuGubonulAubububidatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusBifrinulAucus" eSuperTypes="//AgubugugubibeGubogubunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusGuDaFrinulIus" eSuperTypes="//BebuDaguFritor //DiBibedaes //AnCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusfriBoFridaFrigubegusgutus" ordered="false" eType="//BraubiBubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Augubobogutin" eSuperTypes="//BebibugusbeTor //BrauGusBifrinulAucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audadagusGuFridafriGustus" eType="//AlGusbiBoBefrigubinulaulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FanulauboBodaboguBebees" instanceTypeName="typeAubibuDaBenulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGufriBofrinulaunulAubobiGusNulauTor" abstract="true" eSuperTypes="//BraubiBubucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauGusnulaugusbecio" eSuperTypes="//BebuDaguFritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albebibibidaBugusbibeBinus" ordered="false" upperBound="-1" eType="//BrauGusBifrinulAucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriBuDabiDagusNulauBebubuNus" eSuperTypes="//DibubebibifribugusNulauBobiCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AldafrigusbuBobutor" instanceTypeName="typeBeBobigusfriBufribiLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeBubunulAubobeDadabues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulaunulauNulAulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albuboNulAububucus" ordered="false" eType="//BabeBubunulAubobeDadabues"/>
  </eClassifiers>
</ecore:EPackage>
