<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dibodabutin" nsURI="http://hub.de/rcore/examples/dibodabutin" nsPrefix="wwM">
  <eClassifiers xsi:type="ecore:EClass" name="AnnulaunulAuGuscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogunulaunulaubeNulAuDabobufriGustor" eSuperTypes="//AnnulaunulAuGuscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alauDabubonulAubotor" ordered="false" eType="//AnnulaunulAuGuscus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusnulAugugubigugusbubeBibegusnulautin" upperBound="-1" eType="//AnnulaunulAuGuscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdanulauFrinulaucio" eSuperTypes="//DogunulaunulaubeNulAuDabobufriGustor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusdaBefriGusfrifriTus" instanceTypeName="typeDubuDadabibodagusDanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeguDaBidacus" eSuperTypes="//AdanulauFrinulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusbobigubebibubebubobuboFricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBobedanulaugusnulAuBibuLius" eSuperTypes="//AnnulaunulAuGuscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudadabuBibogusnus" ordered="false" eType="//AdanulauFrinulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBodabuBuNulauTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusfrigusNulauBuBodagutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daguBigusBotus" eType="//DugusdaBefriGusfrifriTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusBoNulAulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eubogusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBeBoBogulius" ordered="false" eType="//DigusbobigubebibubebubobuboFricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbiBuFriGues" eSuperTypes="//AdanulauFrinulaucio //BeguDaBidacus //FagusBoNulAulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGusfriGusbebeFriBeguslius" ordered="false" upperBound="-1" eType="//AnulaufribigusaubiGusBebubilius" eOpposite="//AnulaufribigusaubiGusBebubilius/bifrigusfribodabiBubibuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboBubiGuBogusTus" eSuperTypes="//FagusBoNulAulius //AgusfrigusNulauBuBodagutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBobofriNulaunulaubigusBiCus" upperBound="-1" eType="//DigusbobigubebibubebubobuboFricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabeNulAubububoboes" eSuperTypes="//AnnulaunulAuGuscus //DogunulaunulaubeNulAuDabobufriGustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibunulaunulaudator" ordered="false" upperBound="-1" eType="//DoBobedanulaugusnulAuBibuLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="audafriBiNulAuBufrigucio" ordered="false" eType="//DuLius" eOpposite="//DuLius/dibebidafrinulaudator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFrinulAuGuNulAudaTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabebedadanulAugusguBugusBenulius" eType="//FabeNulAubububoboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabobiGusGusbeNulaunulauNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braufriGusfridaNulaubegusAutor" ordered="false" upperBound="-1" eType="//DogunulaunulaubeNulAuDabobufriGustor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGudabebubibefribuBilius" ordered="false" upperBound="-1" eType="//Abibibobetor" eOpposite="//Abibibobetor/biboBubobebigubifrifriDabotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADabobenulIus" eSuperTypes="//DiboBubiGuBogusTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BenulaubebudabebeBibiBegufriFribelius" instanceTypeName="typeDibigusfrigusguGubiBucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabiGusBiGuNulaudagubiBuGusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabogusDagusbogusboNulAutus" ordered="false" eType="//DigusbobigubebibubebubobuboFricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuDaGuGusbiDagusAufriBibiGusGulus" eSuperTypes="//BiFrinulAuGuNulAudaTin //DoBobedanulaugusnulAuBibuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBonulaufridaBonulautor" eSuperTypes="//DiboBubiGuBogusTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAugusauFriFries"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubifribuDaDanulaubulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabeBiBiGusgufriFriFrilus" eSuperTypes="//AuBodabuBuNulauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augubegugubedabigusbogustin" upperBound="-1" eType="//Eubogusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuDabubeBidaBiDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusnulaubenulAubiGuGustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebebudanulauBiguBiBefriNus" ordered="false" eType="//DagusGuBuBefribubugusBonulIus" eOpposite="//DagusGuBuBefribubugusBonulIus/beDabuFrifrigufriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoboguGuCio" eSuperTypes="//DogunulaunulaubeNulAuDabobufriGustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusAunulaunulAuBies" eSuperTypes="//DuDaGuGusbiDagusAufriBibiGusGulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBidaGuboGusbofritus" ordered="false" upperBound="-1" eType="//DogunulaunulaubeNulAuDabobufriGustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaufribigusaubiGusBebubilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifrigusfribodabiBubibuEs" ordered="false" eType="//AbiBuFriGues" eOpposite="//AbiBuFriGues/anGusfriGusbebeFriBeguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusbeGubiBiGuBiLius" eSuperTypes="//DabobiGusGusbeNulaunulauNus //DigusbobigubebibubebubobuboFricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaDagunulaububies" eSuperTypes="//DoboguGuCio //ADabobenulIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DibeguGuBufriTor" instanceTypeName="typeDufrinulAuBidacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusNulAunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubodadabodaGusbigusAuFriTus" upperBound="-1" eType="//DabeBiBiGusgufriFriFrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGudaGugubodabitus" eSuperTypes="//FabiGusBiGuNulaudagubiBuGusius //BeguDaBidacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaudagusnulius" ordered="false" upperBound="-1" eType="//BeGusAunulaunulAuBies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBonulaububebonulauDanus" abstract="true" eSuperTypes="//AbiBuFriGues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auFriDaNulaugunulauNulAufriLus" eType="//DugusdaBefriGusfrifriTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulAubogusbelius" ordered="false" eType="//AbigugugusgusgusBoFrigugubobiTus" eOpposite="//AbigugugusgusgusBoFrigugubobiTus/bedabebeNulaudagusauLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadanulauNulauGusbetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabefriguBelus" eType="//DibeguGuBufriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbobibegusBuNulAuNulaudaes" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafrinulauGusbebebebuboGusfriBegusNulEs" eSuperTypes="//DuDabubeBidaBiDaes //DagusnulaubenulAubiGuGustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dudabunulaunulaucus" eType="//DibeguGuBufriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriDabibebuDabulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBuNulAuGusius" ordered="false" upperBound="-1" eType="//DabobiGusGusbeNulaunulauNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babunulAuBoGudadadanulAucio" ordered="false" eType="//AnnulaunulAuGuscus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabebuBubeguBecio" ordered="false" eType="//DagusnulaubenulAubiGuGustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobububoFrigusbocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguGusauNulaubegusius" ordered="false" eType="//BeguDaBidacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbinulaufriBelus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enulaubeboBobudatus" eType="//BenulaubebudabebeBibiBegufriFribelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuDagusdanulAudanulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBibeNulauboBugusGudagunus" ordered="false" eType="//FagusBoNulAulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuguguNulauFriCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubiBiGusaubudabubeFriBitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusboBibenulaucio" ordered="false" upperBound="-1" eType="//BagusbeGubiBiGuBiLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguGusauGusnulaudaGusauTor" ordered="false" upperBound="-1" eType="//FabeNulAubububoboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusGufribodadabeBubotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrigusCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faGusguBoGubugubugunulaulius" upperBound="-1" eType="//DobububoFrigusbocio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDabuGudadafribidaguNulaubunulius" ordered="false" upperBound="-1" eType="//FabiGusBiGuNulaudagubiBuGusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BanulAubobidacus" instanceTypeName="typeEbufribiDagubibefribiGusdabecio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BedafriBeguGusfribefriDanulauNules" instanceTypeName="typeBeBubefrinulAugusNulAulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaboGufribebigusbigubofridabicus" abstract="true" eSuperTypes="//FabeNulAubububoboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafriboCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibugubigubegusnulaububugusgugugutor" ordered="false" upperBound="-1" eType="//FabiGusBiGuNulaudagubiBuGusius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dadabebuboboFridabeDator" eType="//BenulaubebudabebeBibiBegufriFribelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeGusAunulauBunulauGusgusNulaufritin" instanceTypeName="typeFaGufrinulAufribogugunulaubodafricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiguGubegudabubebuBudaguBiGuslius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baGuBiguBibudatin" eType="//BanulAubobidacus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusgusFriBubeBeCio" eSuperTypes="//AgusfrigusNulauBuBodagutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BenulaunulaubiGusgusDaGusdagusnulius" instanceTypeName="typeDaGuBidaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbofribuFrifricio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudaGudanus" eSuperTypes="//BiFrinulAuGuNulAudaTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusAububuguDagufriguCio" eSuperTypes="//BagusbeGubiBiGuBiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiBeGububebugusgusCus" eType="//AnulaufribigusaubiGusBebubilius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBibufribulius" eType="//DibeguGuBufriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBeboBidabeBoGucus" eSuperTypes="//AdanulauFrinulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusbuNulaufrigufribubunus" ordered="false" eType="//AnnulAugusauFriFries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eFribifridabecio" eType="//BenulaunulaubiGusgusDaGusdagusnulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaguFriGuBebinulaubuNulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusnulAububuBefriBicus" eSuperTypes="//AGusNulAunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobebudadaguBibuBotor" upperBound="-1" eType="//BenulaunulaubiGusgusDaGusdagusnulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBugustin" upperBound="-1" eType="//BenulaunulaubiGusgusDaGusdagusnulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AFrigufriDagusbiBonulaugusBebiBuBoBeBoFricio" abstract="true" eSuperTypes="//DuFriDabibebuDabulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaufribeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbigugugusgusgusBoFrigugubobiTus" abstract="true" eSuperTypes="//DogunulaunulaubeNulAuDabobufriGustor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algusdabenulautin" eType="//BanulAubobidacus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedabebeNulaudagusauLus" ordered="false" eType="//AlBonulaububebonulauDanus" eOpposite="//AlBonulaububebonulauDanus/benulAubogusbelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabidaDabeNulAubelius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binulaufribudafriboGuscus" eType="//BenulaunulaubiGusgusDaGusdagusnulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="br" eType="//BeGusAunulauBunulauGusgusNulaufritin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabugucus" eType="//BanulAubobidacus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofrinulauDanulaubuNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobiBibobeBubidaGucus" ordered="false" upperBound="-1" eType="//DaboGufribebigusbigubofridabicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBubidadadabufriboBitin" eSuperTypes="//DuDabubeBidaBiDaes"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbobubiFridagubees" instanceTypeName="typeDibiGugusbibubuNulAugusBoFriFriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefridaBiguDaTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusNulauFriboGuEs" eSuperTypes="//DiNulaufribeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADaGusboBuBebibegububeButus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AufriBebuNulaunulaulus" instanceTypeName="typeBrAunulaugusbobuBigubeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiFribobeDabidabufrinulaugusNulautus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dodanulaudagustus" eSuperTypes="//BaDagunulaububies //FabeNulAubububoboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebuBuGuNus" eType="//AufriBebuNulaunulaulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBiNulaubuNulAudaTin" eSuperTypes="//DobububoFrigusbocio //DuBubidadadabufriboBitin //BiFrinulAuGuNulAudaTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDaGubunulaubutin" ordered="false" upperBound="-1" eType="//DogunulaunulaubeNulAuDabobufriGustor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribubogubogusTor" ordered="false" eType="//AngusnulAububuBefriBicus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebibugusgusnulauboGusius" ordered="false" upperBound="-1" eType="//BigusNulauFriboGuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Augusaufribenulaunus">
    <eLiterals name="BigusgubibebebebigusBofribudabogusbuFries"/>
    <eLiterals name="BibudabiNulAubibiDaGuBiGubeTus"/>
    <eLiterals name="BebiGusgugusbegubuGusGugudagutin"/>
    <eLiterals name="DubofriDafriDabinulAufrinulaufribiBibutin"/>
    <eLiterals name="BeGusGusdadagugustus"/>
    <eLiterals name="EbunulaudafriGubiGusgutin"/>
    <eLiterals name="FafriGusFriguNulAuBebubucus"/>
    <eLiterals name="BrAuGuGusboGusgusguscus"/>
    <eLiterals name="BraubiFrinulauNulauBuNus"/>
    <eLiterals name="EgugusbebiboDacio"/>
    <eLiterals name="DadagusBiGugubolius"/>
    <eLiterals name="BenulauGugubuNulaulus"/>
    <eLiterals name="AgunulaubibuGusGunulAucus"/>
    <eLiterals name="EnulAuNulauBeBiBuCus"/>
    <eLiterals name="BeBefribinulIus"/>
    <eLiterals name="Dadabobutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBebunulautin" eSuperTypes="//AbigugugusgusgusBoFrigugubobiTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albibeGubobiDaguGuboBubebunus" ordered="false" eType="//Dodanulaudagustus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dodabebenulauBogusnulauDafriGusBubies" ordered="false" eType="//DabeBiBiGusgufriFriFrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FafribebiBogusdaBifrigufriGuNules" instanceTypeName="typeABugusaugusBibonulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugubuGusbeGusNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abibibobetor" eSuperTypes="//EuDagusdanulAudanulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboBubobebigubifrifriDabotus" ordered="false" eType="//DabobiGusGusbeNulaunulauNus" eOpposite="//DabobiGusGusbeNulaunulauNus/aGudabebubibefribuBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABoGuGubebiNulaulius" abstract="true" eSuperTypes="//Eubogusnus //BaDagunulaububies //DobububoFrigusbocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGusBofriBugusboBues" ordered="false" upperBound="-1" eType="//DabobiGusGusbeNulaunulauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudagusgusbedabifriNulauNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulauboBiBufridaBigugunus" abstract="true" eSuperTypes="//AlbiguGubegudabubebuBudaguBiGuslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulaugufritus" eSuperTypes="//AlbiguGubegudabubebuBudaguBiGuslius //AnulaufribigusaubiGusBebubilius //AugusAububuguDagufriguCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAugusfriGusbinulauDaNus" ordered="false" upperBound="-1" eType="//BagusbigusbeDaBoguBenus" eOpposite="//BagusbigusbeDaBoguBenus/diGusauDabeBugusbeDadaguslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbebibuDaboboBetor" instanceTypeName="typeDuBufriBoGusfribidabebunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegugubeBefriGubodabinulAulius" eSuperTypes="//FagusBoNulAulius //DonulauboBiBufridaBigugunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaDagubebiFriGunulaunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babedaGuBoBonulAutin" ordered="false" upperBound="-1" eType="//DaGudaGugubodabitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeDaBoBuGuboBiBibucio" instanceTypeName="typeEufribifrifribiGubebecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofribeDabuboBeFribibogubebedaTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeBulius" instanceTypeName="typeDifrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusbigusbeDaBoguBenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGusauDabeBugusbeDadaguslus" ordered="false" eType="//ANulaugufritus" eOpposite="//ANulaugufritus/aunulAugusfriGusbinulauDaNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bidagufribuguslus" eSuperTypes="//DuDabubeBidaBiDaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abubonulaubuGusGugubuGulius" upperBound="-1" eType="//DobobugusGusbibonulaudaguslus" eOpposite="//DobobugusGusbibonulaudaguslus/anbiBibufribubeGuBefrifriBufriTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadabuBobubogusBiFries" eSuperTypes="//DabeBiBiGusgufriFriFrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="efrigugusdafriBebebutor" upperBound="-1" eType="//BedafriBeguGusfribefriDanulauNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubobibuBiboNulaunus" eSuperTypes="//BaDagunulaububies"/>
  <eClassifiers xsi:type="ecore:EClass" name="Egusbies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBofriGuboGufrigudagusbiguDagustus" eSuperTypes="//DoBobedanulaugusnulAuBibuLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duDaNulauNulauguBoBifrinulauLus" eType="//AnbebibuDaboboBetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BenulauBoBobeboBiBugugusnulaudaFrinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusbiFriGuslius" eSuperTypes="//AnulaufribigusaubiGusBebubilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBebuguBiFrinulAugusAuBocio" instanceTypeName="typeFabibobedabuBebebulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiNulautus" instanceTypeName="typeAuDafriGuFriGusbigubofributus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BenulAufribeNulAuBicus" instanceTypeName="typeDuFrifriBibubinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadagusgusbiBodacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibugusbuFridaBebunules" eSuperTypes="//DagusnulaubenulAubiGuGustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBibeGuBocus" ordered="false" eType="//DonulauboBiBufridaBigugunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulAuBoBuguBoDabefricus" ordered="false" upperBound="-1" eType="//DagusnulaubenulAubiGuGustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibedabuFribodaFriDabotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlDagubefrinulauBuGugutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebuDabigugusbiLius" ordered="false" upperBound="-1" eType="//AubifribuDaDanulaubulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbegusBebugusfridaBibinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abebudaBigusAuGusbuBugugulus" eType="//DibeguGuBufriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuDabubebogusgunulauLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBuguBuFribuGudagusbeEs" eType="//DigubuNulaugusBoBecus" eOpposite="//DigubuNulaugusBoBecus/ebobogubedabiboBufritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGuNulauBidadaEs" eSuperTypes="//BibugusbuFridaBebunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubiBodadagusbecio" ordered="false" upperBound="-1" eType="//DigusbobigubebibubebubobuboFricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubigusNus" abstract="true" eSuperTypes="//DigusbobigubebibubebubobuboFricio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BebifribubobeFriBoLus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AubeNulauBenulauGuBenulAuTor">
    <eLiterals name="DufriDaGuGudaFridalius"/>
    <eLiterals name="EgudabogubefrigusGusbuGusbelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeguFrinulaunulaubefriEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeguFriBubebotin" eSuperTypes="//AGusNulAunus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EubinulAububeCus">
    <eLiterals name="DaDabubenulauTus"/>
    <eLiterals name="BagusBobuGusbubibodaDanulauLius"/>
    <eLiterals name="BrauBigusbufrilus"/>
    <eLiterals name="DoBoBinulauGunulaubeNulAubocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagubeGusgusdabeguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngubinulAuguCio" eSuperTypes="//EbegusBebugusfridaBibinus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlgusnulaubibigusgudaGuslus">
    <eLiterals name="AnbiFrigusbiBeguBuBibubebetin"/>
    <eLiterals name="BrAunulaubedaEs"/>
    <eLiterals name="A"/>
    <eLiterals name="AugudaGusnulauDalius"/>
    <eLiterals name="DofribeDaBibuBobofritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbugusAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBudaboCus" eSuperTypes="//AbiBuFriGues"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBebufriguBoBeBebibucio" eSuperTypes="//BagusbigusbeDaBoguBenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaboBiBiFritor" ordered="false" upperBound="-1" eType="//FabeNulAubububoboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DabiNulaufribonulaudaTor">
    <eLiterals name="DabiguBiguFrigusNules"/>
    <eLiterals name="DubodabuDafriBulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobobugusGusbibonulaudaguslus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beFrigugubeGuBodaButin" eType="//BeDaBoBuGuboBiBibucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbiBibufribubeGuBefrifriBufriTin" ordered="false" upperBound="-1" eType="//Bidagufribuguslus" eOpposite="//Bidagufribuguslus/abubonulaubuGusGugubuGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaBuGusbiBibedalus">
    <eLiterals name="EbuBuNulauBuboboBedaBecio"/>
    <eLiterals name="BraubuguBebuboBufriLus"/>
    <eLiterals name="DogusGusgusdaFribugusgusbeGubenulius"/>
    <eLiterals name="ENulaudaGustin"/>
    <eLiterals name="DabeFriDabigunulAubidaGubiTus"/>
    <eLiterals name="AdaboBobidaGusNulaubibifrilus"/>
    <eLiterals name="ABugugunulaubebocus"/>
    <eLiterals name="BeBoBonulaubobicus"/>
    <eLiterals name="AldanulAubufriGufriBoGuGues"/>
    <eLiterals name="EubefrigusnulauDaFrinulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabufrigusnulaugugudanulaufriBefributus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobiBoboBebobeFribibilius" instanceTypeName="typeABiFribeguDaBiCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuNulaubugusBebegusBiCio" instanceTypeName="typeAlgufriBiBidanulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufribobogububebeNulAunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboGusGugubodaCus" eSuperTypes="//AlBonulaububebonulauDanus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augunulAububegusNulaudalus" eType="//DobiBoboBebobeFribibilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGugusgusgubiBiguscus" eSuperTypes="//BiBudaboCus //DobububoFrigusbocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faboGusAuFrigusdabitor" eType="//AubeNulauBenulauGuBenulAuTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibububonulAuGuBedabeBitin" abstract="true" eSuperTypes="//AnnulAugusauFriFries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiBedabebofridaBebuNus" ordered="false" eType="//BaDagunulaububies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulauBufriBibotor" eSuperTypes="//DafrinulauGusbebebebuboGusfriBegusNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndagubefribiGubebutor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BeBeNulaugusaubuDaTus">
    <eLiterals name="DudadabubiguGuBenulaucio"/>
    <eLiterals name="Da"/>
    <eLiterals name="DobebuGusnulaunulAudaGulus"/>
    <eLiterals name="BrauboBifrigusfries"/>
    <eLiterals name="FagufriGusaubibubegusbulius"/>
    <eLiterals name="AubogusbifriGufrigudaGusTin"/>
    <eLiterals name="DaBeBidabeBonus"/>
    <eLiterals name="DafrifrinulAuNulauBobobees"/>
    <eLiterals name="BibiGuBegusBeDadaes"/>
    <eLiterals name="Be"/>
    <eLiterals name="BrauNulaubunulAucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubibuGunus" eSuperTypes="//DufribobogububebeNulAunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaNulaugugusbidalus" ordered="false" upperBound="-1" eType="//AbofribuFrifricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubidabibiboNulaucus" instanceTypeName="typeEboNulAuGububonulAubuNulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefridaGuBobuGubuBigubiDaNulauGusnulAunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doNulAufrigusfribetor" upperBound="-1" eType="//AnbebibuDaboboBetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubuNulaufriBibefriNus" instanceTypeName="typeBiNulaugugunulAugudagusbobutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuLius" eSuperTypes="//AbiBuFriGues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibebidafrinulaudator" ordered="false" eType="//FabeNulAubububoboes" eOpposite="//FabeNulAubububoboes/audafriBiNulAuBufrigucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogugusdabeBogusboDaGuDaDaEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DidabeGugues" instanceTypeName="typeBebifridabubuFribinulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigubuNulaugusBoBecus" eSuperTypes="//AdanulauFrinulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebobogubedabiboBufritor" ordered="false" upperBound="-1" eType="//BrAuDabubebogusgunulauLus" eOpposite="//BrAuDabubebogusgunulauLus/baBuguBuFribuGudagusbeEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabigusbugusbubudagubodaes" ordered="false" eType="//AngusnulAububuBefriBicus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubuFriNulauGufribedaboNulaufrifriGues" upperBound="-1" eType="//AGusNulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubobubuDaBuBuGusBuLus" eSuperTypes="//BeguDaBidacus //DobububoFrigusbocio //BibububonulAuGuBedabeBitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabobubogusDaDagusfrilus" eType="//AufriBebuNulaunulaulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebebinulaububiBedabues" ordered="false" upperBound="-1" eType="//DuFriDabibebuDabulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusGuBuBefribubugusBonulIus" abstract="true" eSuperTypes="//DoBobedanulaugusnulAuBibuLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biFriboGusCio" eType="//BenulaubebudabebeBibiBegufriFribelius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebiguFribiNulaudabuboEs" ordered="false" eType="//FaGugusgusgubiBiguscus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beDabuFrifrigufriLius" ordered="false" eType="//DagusnulaubenulAubiGuGustus" eOpposite="//DagusnulaubenulAubiGuGustus/bebebudanulauBiguBiBefriNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbibubeboBunulAubobiDaTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enulaufribuTor" upperBound="-1" eType="//BedafriBeguGusfribefriDanulauNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabeboBibiGusgusNulEs" eSuperTypes="//FaDagubebiFriGunulaunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaudaBufridator" ordered="false" upperBound="-1" eType="//BaBofriGuboGufrigudagusbiguDagustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnnulAubobibibinus">
    <eLiterals name="DoBeBigubenulaufridacus"/>
    <eLiterals name="AlBubobefribiguNulauLus"/>
    <eLiterals name="DubuBeBiboguBobubegusnus"/>
    <eLiterals name="AbuBuGusGudaCus"/>
    <eLiterals name="AlgusfribuGubifriButus"/>
    <eLiterals name="AubibugunulauGusdaNulAuLius"/>
    <eLiterals name="BafriDabibenulaubebibogubeFribitin"/>
    <eLiterals name="BagubiboBegusgusbenus"/>
    <eLiterals name="DuBeGufrinulauguTor"/>
    <eLiterals name="DabiBuDanulius"/>
    <eLiterals name="DabeNulaunulAubeBeDalius"/>
    <eLiterals name="AnNulAubuBuguFriguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufridanulauBuTor" eSuperTypes="//AlBonulaububebonulauDanus //EubobubuDaBuBuGusBuLus //EubiBiGusaubudabubeFriBitin //BaDagunulaububies"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubedanulaudaDabeboBogubotus" instanceTypeName="typeDoDabofriboboboBeboboBobefritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafrinulaunulauBinulaubedaBonulauCio" eSuperTypes="//DigusGufribodadabeBubotus //EubiBiGusaubudabubeFriBitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fafribubiNulAubonulAuFriFriNus" eType="//AubuNulaufriBibefriNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfribeFribedabiNus" eSuperTypes="//DigusGufribodadabeBubotus"/>
</ecore:EPackage>
