<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dogufribebobutus" nsURI="http://hub.de/rcore/examples/dogufribebobutus" nsPrefix="au">
  <eClassifiers xsi:type="ecore:EClass" name="BeGusdanulAubuGubolus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadaboBufrifritus" abstract="true" eSuperTypes="//BeGusdanulAubuGubolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndafriGusgunulauFriguCus" eSuperTypes="//BeGusdanulAubuGubolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulAuguFribiBidaTor" ordered="false" eType="//FadaboBufrifritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuDagusbiBiFribigubodagusBubenulauTus" eSuperTypes="//AndafriGusgunulauFriguCus //FadaboBufrifritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebubiBodagusaugubonulauBubudanus" eType="//FadaboBufrifritus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagubebeguguFribenulauFriguboes" eType="//FadaboBufrifritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusnulaubonulAubebibubobeGuslus" eSuperTypes="//BeGusdanulAubuGubolus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EufribiBedabefrigusBebigubinus" instanceTypeName="typeAlbubuBegusfriguDabuNulaubofribogues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DidaBebogusgudabeCio" instanceTypeName="typeDaBibufrifrifrigusbuboTin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BibeGusbuguGusdanulAubuCus">
    <eLiterals name="AnboFriGugubefrigusBiNulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedagusbibiNulauGubuBuNulautus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabobenulauNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eufribebudafribobilius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubiBefriBinulaunulAuguDabuTin" eSuperTypes="//AuDagusbiBiFribigubodagusBubenulauTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedaDaBiGuGusbuEs" eType="//BibeGusbuguGusdanulAubuCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusAudanulAubebebobigusauBuNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusBidabuBifribidadaNulius" eType="//EufribiBedabefrigusBebigubinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbibebegubiguGusGusdalus" eSuperTypes="//DubiBefriBinulaunulAuguDabuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagufriBedaFribeBobefrinulAufribogubunulaugusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudanulaufribeDaBidabunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulAuNulaubudafries" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulAudagusFrilus" ordered="false" upperBound="-1" eType="//AuDagusbiBiFribigubodagusBubenulauTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuguBugufridagubuBegubeboLus" instanceTypeName="typeDubenulAuboFriboDanulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauDadaBubinulauBebudaes" eSuperTypes="//DonulAuNulaubudafries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulaubuBibodaDaBulus" ordered="false" eType="//FagufriBedaFribeBobefrinulAufribogubunulaugusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibuGusbubeGusdaFriNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBeFriNulaufridaNulauboNulauNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulauNulaubegutin" eSuperTypes="//BeGusdanulAubuGubolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faGusaubeBifribobebubicus" upperBound="-1" eType="//BaBugubebuNulAudadaes" eOpposite="//BaBugubebuNulAudadaes/auNulAudaBibidabonulaugusbegugusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbenulaubogusfriBiGusBuFriBeNulAulius">
    <eLiterals name="FabebeBudabobodatin"/>
    <eLiterals name="FagusBubugusgubudacus"/>
    <eLiterals name="EBubiDanulAugusBugubiDagusbelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuFribofrinulAuBuBuBubodafrilus" abstract="true" eSuperTypes="//DibuGusbubeGusdaFriNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBinulAuBobeguDanulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraububeboBoBoBedabuBetus" eSuperTypes="//DudanulaufribeDaBidabunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeBefribubicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbogusguGugubibebotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eudaGusboGufribeFrifribuBetin" eType="//EufribiBedabefrigusBebigubinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusaubenulauFrifrinulAufriboCus" eSuperTypes="//Eufribebudafribobilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboNulaugubolius" eSuperTypes="//DaBinulAuBobeguDanulEs //BagusAudanulAubebebobigusauBuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efribigusfriBobeNulaububeboNulAuBiTor" ordered="false" upperBound="-1" eType="//BedagusbibiNulauGubuBuNulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaFribunulAudabunulauBitin">
    <eLiterals name="EnulauGuBobunulaubobeDanulius"/>
    <eLiterals name="AndaDaNulaudabogusAubebeBobutor"/>
    <eLiterals name="DoFrifribiDafriBifrigusgusEs"/>
    <eLiterals name="EGusguNulAuBeGuBiguGusBenus"/>
    <eLiterals name="DaBibedagusFribuCus"/>
    <eLiterals name="BeFrinulauNulaunulaubeBoGusnulius"/>
    <eLiterals name="AlbigubofribibuBinules"/>
    <eLiterals name="DubogufriBobibibodator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusbeGusGusaucio" eSuperTypes="//DugusnulaubonulAubebibubobeGuslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafriNulAuDafriDatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubibobeBiDaCus" ordered="false" eType="//AnbibebegubiguGusGusdalus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badaLius" eType="//DidaBebogusgudabeCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufriNulaunulaububoTus" ordered="false" upperBound="-1" eType="//BinulauBubidabubinulauBiBebunus" eOpposite="//BinulauBubidabubinulauBiBebunus/digunulAuBegusbigusbeGulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibebidaGubiDagusbebogusbobetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biDaBiguslius" eType="//DudanulaufribeDaBidabunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauFrinulauCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AngudaBodaNulaudabobuGubibenus" instanceTypeName="typeBeBegusBuBuBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudafriBodaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulaufrifrigubedanulAuNulaufriguNulius" ordered="false" eType="//BeGusdanulAubuGubolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBugubebuNulAudadaes" eSuperTypes="//AnbibebegubiguGusGusdalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulAudaBibidabonulaugusbegugusius" ordered="false" upperBound="-1" eType="//BraunulauNulaubegutin" eOpposite="//BraunulauNulaubegutin/faGusaubeBifribobebubicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusguBubebubuGusbiFribeguGusbues" eSuperTypes="//AbogusguGugubibebotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGuBobobobogugusFriDaboDabitin" eType="//AndafriGusgunulauFriguCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Dibufribigustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fa">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eguNulauBigubobigusgustus" eType="//DidaBebogusgudabeCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babogusbidanulAuFrifriguNules" ordered="false" eType="//ENulaubibegusgusbufrigunus" eOpposite="//ENulaubibegusgusbufrigunus/eufrigusAudagusfrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBogubuGusbofrigubuFribulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaNulaubegusbidaFridabegusBitus" ordered="false" upperBound="-1" eType="//DonulAuNulaubudafries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eudaGusBidagudagugugudaLus" eType="//BaFribunulAudabunulauBitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobebebubugubuGulius" abstract="true" eSuperTypes="//EBogubuGusbofrigubuFribulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faNulaubigusBeLius" upperBound="-1" eType="//BaFribunulAudabunulauBitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudanulAuGusbiGusauGuslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidabofrigusboEs" ordered="false" upperBound="-1" eType="//DobebebubugubuGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibenulAubifriGusnulaucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubonulAuBubinulauboTus" eType="//DidaBebogusgudabeCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobeFribunulauGubuGubogusbies" abstract="true" eSuperTypes="//BedagusbibiNulauGubuBuNulautus //DugusaubenulauFrifrinulAufriboCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DadabibogusAubibegusboLus" instanceTypeName="typeAngusBedaBibobefriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enulaugunules" eSuperTypes="//AnbibebegubiguGusGusdalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauBubidabubinulauBiBebunus" eSuperTypes="//EudafriBodaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digunulAuBegusbigusbeGulus" ordered="false" upperBound="-1" eType="//DafriNulAuDafriDatin" eOpposite="//DafriNulAuDafriDatin/dufriNulaunulaububoTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguguDadadanulaufriFritus" eType="//DonulAuNulaubudafries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaubibegusgusbufrigunus" abstract="true" eSuperTypes="//DaBinulAuBobeguDanulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufrigusAudagusfrilius" ordered="false" upperBound="-1" eType="//Fa" eOpposite="//Fa/babogusbidanulAuFrifriguNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AngusbeBeBudabiTor" instanceTypeName="typeBibibofribunulAubeGuBiFriBifribogusnules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuNulAubibubigusnulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuboBecio" abstract="true" eSuperTypes="//DudanulAuGusbiGusauGuslius //DibuGusbubeGusdaFriNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubodafridaBiTin" ordered="false" eType="//DafriNulAuDafriDatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FafribigusEs" instanceTypeName="typeAfribuFriGustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubibebuBibibigusgusTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboBenulaubufriguguTus" eSuperTypes="//DibuGusbubeGusdaFriNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibubeNulAufrinulAubogudabuFrinulauDaCus" eSuperTypes="//AnbibebegubiguGusGusdalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBubeBoBudaBidadaBodaDagufrilus" eSuperTypes="//BagusguBubebubuGusbiFribeguGusbues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulauGuBocio" ordered="false" eType="//BeGusbeGusGusaucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulaufriBubobeGusBugusAubuBoLius" eType="//AlbenulaubogusfriBiGusBuFriBeNulAulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifriboNulAufriBobiTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGubonulAuguboBubitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbobinulauGuscio" eSuperTypes="//DobebebubugubuGulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBubobunulaunulauLus" eType="//DibenulAubifriGusnulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigufriGubodabodaBoBebeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibobibonulauFribebifriCus" ordered="false" eType="//DafriNulAuDafriDatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AndafrinulauboboboBoBoBuDadaCio">
    <eLiterals name="BebuBeBunulAunulIus"/>
    <eLiterals name="BrauboBeLus"/>
    <eLiterals name="BeBubuNulaudadadacio"/>
    <eLiterals name="DunulAugugubeDafrinulAutor"/>
    <eLiterals name="DugusbuBifrigubiBiFriBetor"/>
    <eLiterals name="EuGusbefribobobubonulauCus"/>
    <eLiterals name="BibuNulaubuguNus"/>
    <eLiterals name="DaguBobibefriGudabogusAubibelius"/>
    <eLiterals name="AGusnulaubogusGusbugusgusFribenulAuLus"/>
    <eLiterals name="DogububobiFriBogusguTin"/>
    <eLiterals name="EuBunulaugugusbeGusfribubolius"/>
    <eLiterals name="BagugubinulAugubobuDanus"/>
    <eLiterals name="ABeBidaBoNulauNulAububiLius"/>
    <eLiterals name="AlauBubibegugusdadatin"/>
    <eLiterals name="DububogudaBobebonulaugudafrinulauTin"/>
    <eLiterals name="AlfriBuGunulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BadaNulaufriFriboNulauGuCio">
    <eLiterals name="AbiBiBofriNules"/>
    <eLiterals name="AugubuBefrigusbiGutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADanulaufribebeFridaButor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbinulAubodanus" eType="//AndafrinulauboboboBoBoBuDadaCio" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
