<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eunulaubobodaes" nsURI="http://hub.de/rcore/examples/eunulaubobodaes" nsPrefix="N">
  <eClassifiers xsi:type="ecore:EClass" name="AFriBeBugusGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagubinulAubonulauBetus" abstract="true" eSuperTypes="//AFriBeBugusGutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubegusaububiBitor" ordered="false" eType="//AFriBeBugusGutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBunulautor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbubobeBoDabebeBoBoguscio" ordered="false" eType="//FagubinulAubonulauBetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibiBebudaboGusGues" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DuGubiGusbebibudaBoguses">
    <eLiterals name="AdabubogusnulaubidagusgusNules"/>
    <eLiterals name="EBuBogusbuBebetor"/>
    <eLiterals name="AnfrifrifribugusDagufriTor"/>
    <eLiterals name="BabibunulauBuNulauboBoes"/>
    <eLiterals name="AbugusnulAubobetin"/>
    <eLiterals name="DuGusgusAubobeBiGusBoguDacus"/>
    <eLiterals name="EubenulauguBitus"/>
    <eLiterals name="DiGusaubugulius"/>
    <eLiterals name="AnFrinulauBobofriboDator"/>
    <eLiterals name="DabebuFribibofriBiBegusBigusNulEs"/>
    <eLiterals name="AdabobofriBibedabibufrinulauBiTin"/>
    <eLiterals name="DiDafrifriGugusnulaubodadaGusIus"/>
    <eLiterals name="AuguNulaugusauGusBunulAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfridanulauGuboguCus" eSuperTypes="//DibiBebudaboGusGues //AFriBeBugusGutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beFriBebelius" eType="//DuGubiGusbebibudaBoguses" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadafribobenulAufrigusfrinulAudaTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alDabibegusBogusbegudafritor" eType="//DuGubiGusbebibudaBoguses" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbeNulaudaNulaunulAuBoBolus" ordered="false" eType="//DudabonulAubebubudatus" eOpposite="//DudabonulAubebubudatus/alfribiFriBiBibugusbiGubuBiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdaGusaunulaubeGusguGufricus" eSuperTypes="//AFriBeBugusGutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="afrinulAuGutin" ordered="false" upperBound="-1" eType="//DibiBebudaboGusGues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubuFriguFribugubobogugunulAulus" eSuperTypes="//AFriBeBugusGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudabonulAubebubudatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfribiFriBiBibugusbiGubuBiNus" ordered="false" upperBound="-1" eType="//BadafribobenulAufrigusfrinulAudaTor" eOpposite="//BadafribobenulAufrigusfrinulAudaTor/anbeNulaudaNulaunulAuBoBolus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebububodafriFribeGuDabiLius" ordered="false" eType="//AlBunulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ENulauBoBonulaubobebubiCio" instanceTypeName="typeBraububifridabefribebeGusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnauGubebubotin" eSuperTypes="//BadafribobenulAufrigusfrinulAudaTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daDaBefribuBoGuTin" upperBound="-1" eType="//ENulauBoBonulaubobebubiCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauFribeGusgusbobibiDaBicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuboFribenulauGububeguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadanulAuguboGufriDatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfribibiBunulaudaguboNulauBuTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGudabogusgusbofrigusdatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafrigusdanulAubenus" eType="//ENulauBoBonulaubobebubiCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EboNulauNulauBuNulaugubecus" instanceTypeName="typeBinulaufriBeBudafrigusFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusguDagubinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFriDabifrifrifriBelius" ordered="false" eType="//AfridanulauGuboguCus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agusBigusFrinus" eType="//DuGubiGusbebibudaBoguses" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabefrigusgunulAubeDaGuslus" instanceTypeName="typeDabeBefribubibufridanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubebigubinulaugusTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anNulAuFriBobunulaucio" eType="//FabefrigusgunulAubeDaGuslus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AldaBogusfrinulAugudagusbutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGuFribunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodabofriNulaubufriDanulaunus" eSuperTypes="//AlGuFribunulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabuBudafribuguGulius" ordered="false" eType="//FadanulAuguboGufriDatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaDadanulauNulaubugusbeEs" instanceTypeName="typeBedaFribonulauLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusguboDagusbebeDagudalius" eSuperTypes="//FagubinulAubonulauBetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edagusbidadanulauTor" eType="//EboNulauNulauBuNulaugubecus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudaFrigusBugusbobenus" ordered="false" upperBound="-1" eType="//AubuFriguFribugubobogugunulAulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diboBoNulautor" eType="//EdaGusaunulaubeGusguGufricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaugugusfribudabibiBeFriBuFribilius" eSuperTypes="//BrAubebigubinulaugusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulauNulaubibobobiDabodafriTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabenulAufriTus" upperBound="-1" eType="//FaDadanulauNulaubugusbeEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobuGusguNulAufrinulAulius" abstract="true" eSuperTypes="//DudabonulAubebubudatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobiBonulaubobebelius" ordered="false" upperBound="-1" eType="//AnGudabogusgusbofrigusdatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBonulauDaBigubilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeDaBoDaGusfrinulauDabuguboes" instanceTypeName="typeAlfribebuBuBegusNulaufribilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBofrifriguses" ordered="false" upperBound="-1" eType="//AnGudabogusgusbofrigusdatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabebobuguboLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubebugusFrifricio" eType="//FaDadanulauNulaubugusbeEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabobonulaudacus" eType="//ENulauBoBonulaubobebubiCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BefribuguBigusfriguslus" instanceTypeName="typeBebinulaudaNulaugusGuGuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBobebeGubiFritin" eSuperTypes="//DugusguboDagusbebeDagudalius //DobuGusguNulAufrinulAulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBeBudaNulaubuGuses" ordered="false" upperBound="-1" eType="//Alius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBiBunulauBofriFriGusIus" ordered="false" eType="//AfridanulauGuboguCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobubibebiguDabucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Digusboes" instanceTypeName="typeAunulAuguBunulAudabobodaFritin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgusdagusnulauBubifridaBetus" instanceTypeName="typeAubobufrigustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuBogusnulauBeGusbegusgububoes" abstract="true" eSuperTypes="//AldaBogusfrinulAugudagusbutin"/>
</ecore:EPackage>
