<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="binulaudagusfricio" nsURI="http://hub.de/rcore/examples/binulaudagusfricio" nsPrefix="Q">
  <eClassifiers xsi:type="ecore:EDataType" name="BaboFriBenulAugubigusbifridabogusBiGubiDaes" instanceTypeName="typeBrAuBeBufribugunulauGusDabibogusbobolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBoBoFridabebetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBuBeguGubudacio" ordered="false" upperBound="-1" eType="//EuGudaFrinulautin" eOpposite="//EuGudaFrinulautin/baGubebeBifribogusbibuguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Eugubibifribinulaubebobicus" instanceTypeName="typeBrAuBuGusgubibunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGudaFrinulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGubebeBifribogusbibuguslius" ordered="false" eType="//AuBoBoFridabebetin" eOpposite="//AuBoBoFridabebetin/euBuBeguGubudacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fanulaunules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBibuBobuDabenulautus" eType="//BaboFriBenulAugubigusbifridabogusBiGubiDaes" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifribofribuNulaunulIus" eSuperTypes="//Fanulaunules //AuBoBoFridabebetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abobudanulAubefricus" ordered="false" upperBound="-1" eType="//DaGuBebigubobebubibies" eOpposite="//DaGuBebigubobebubibies/edabubibebeTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbenulaugusCio" eSuperTypes="//DifribofribuNulaunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobiFribiGubiBefriboTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alDafribiTin" eType="//BaboFriBenulAugubigusbifridabogusBiGubiDaes" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobuFrigubedabobebibucus" ordered="false" eType="//AnnulauGubeBunulaufriNulautor" eOpposite="//AnnulauGubeBunulaufriNulautor/aubiBoboguBuBeboBiGuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGuBebigubobebubibies" abstract="true" eSuperTypes="//AuBoBoFridabebetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edabubibebeTor" ordered="false" eType="//DifribofribuNulaunulIus" eOpposite="//DifribofribuNulaunulIus/abobudanulAubefricus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albudadaboboBogustor" upperBound="-1" eType="//Fanulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EubonulauBigunulaufriLus">
    <eLiterals name="AlBuBobiBogusGusbeTor"/>
    <eLiterals name="BaGusNulaubeBugusBiboFritin"/>
    <eLiterals name="AunulauDafrigusbeBodadanus"/>
    <eLiterals name="DubiBodaguBiGustin"/>
    <eLiterals name="BeBoboGusaubobubibeCus"/>
    <eLiterals name="DaBoBegubibofriDabedaEs"/>
    <eLiterals name="BrauDaNulAuBibofribuBefries"/>
    <eLiterals name="AbunulaubibubiGusfrigubitin"/>
    <eLiterals name="BeDaBoNulaubobinulauguBibulus"/>
    <eLiterals name="BeBuBogusBeFriLus"/>
    <eLiterals name="DabobuNulaubibiBoGubibobeGubenus"/>
    <eLiterals name="EufriNulAubeGusbeCus"/>
    <eLiterals name="BrAubibedabenulaugubuFriGuslus"/>
    <eLiterals name="EudadabunulAubebibiboNulAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauBenulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braubibogubobebocus" eSuperTypes="//DobiFribiGubiBefriboTor //EuGudaFrinulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbubugunulAudanulAububugubeboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="efriFriTus" eType="//Eugubibifribinulaubebobicus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgunulaudaBuBobebidaNulaubeBilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfrinulaububigusBofriGulius" ordered="false" upperBound="-1" eType="//BanulauBenulAucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAugubinulauboLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubigufriGusnulAubenulauTor" ordered="false" upperBound="-1" eType="//EuGudaFrinulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuguboBuBonules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBiBeboBinulAuDagusnulaubobuBuBucus" ordered="false" upperBound="-1" eType="//Fanulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuguBodadabiLius" instanceTypeName="typeAGusgusBebibebeBeNulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoguBiBubigusbebobefrilius" abstract="true" eSuperTypes="//EuGudaFrinulautin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duguFrilius" upperBound="-1" eType="//BaboFriBenulAugubigusbifridabogusBiGubiDaes" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AgusbudagusGudabubiFribibiBuBeTin">
    <eLiterals name="EunulaugusGusdagudabidagubitor"/>
    <eLiterals name="BinulauBiBefrinus"/>
    <eLiterals name="AnaugusBiGusDafrinulAuFribiGuslius"/>
    <eLiterals name="BraubefriFrinulaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBebulius" eSuperTypes="//AuguboBuBonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboBibodaBubigusfrinules" eSuperTypes="//EgunulaudaBuBobebidaNulaubeBilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dadabefriLus" eType="//EubonulauBigunulaufriLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulAubunulauboNulaugusguFribiLus" ordered="false" upperBound="-1" eType="//Braubibogubobebocus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbibinulAugugusbiDacus" eType="//DobiFribiGubiBefriboTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubifriNulaugusbibicus" upperBound="-1" eType="//AuBoBoFridabebetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubudaboGuboboguTus" eSuperTypes="//AuguboBuBonules //DaGuBebigubobebubibies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugubedagubibibuCio" ordered="false" eType="//AuguboBuBonules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dudabudabigugubuGusBocus" eType="//BaboFriBenulAugubigusbifridabogusBiGubiDaes" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bebugusbunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabuguBobebuGusguGusbuBecio" eType="//AgusbudagusGudabubiFribibiBuBeTin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulauGudatus" ordered="false" upperBound="-1" eType="//DobiFribiGubiBefriboTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbeFrigufrigulius" instanceTypeName="typeAuguBifriNulAubunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfribufriguBofriFrinulAuBonus" abstract="true" eSuperTypes="//EgunulaudaBuBobebidaNulaubeBilius //DifribofribuNulaunulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebiBidalus" ordered="false" eType="//EgunulaudaBuBobebidaNulaubeBilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusbonulauNulaulus" ordered="false" upperBound="-1" eType="//DifribofribuNulaunulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulauDagubegunulauBefriTin" eSuperTypes="//DobiFribiGubiBefriboTor //AuBoBoFridabebetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulauBiGudaguTus" eType="//AgusbudagusGudabubiFribibiBuBeTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBofriBenulAuBebifriLius" eSuperTypes="//AnfribufriguBofriFrinulAuBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBifribigusbufritus" ordered="false" upperBound="-1" eType="//AuBoBoFridabebetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Anulaubebenulius" instanceTypeName="typeBibonulaubegubifriBofrifribigusCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulauBobibugugusnulauTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafrinulaudabeFriBiBubobeGusNus" abstract="true" eSuperTypes="//Braubibogubobebocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibefrifriBuBies" ordered="false" upperBound="-1" eType="//BaNulauDagubegunulauBefriTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibufribiBebogusbitor" ordered="false" eType="//AboBibodaBubigusfrinules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobobofriDaBinulaunules" ordered="false" eType="//EgunulaudaBuBobebidaNulaubeBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdadagusDaBigusCus" eSuperTypes="//DoguBiBubigusbebobefrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGuGuGuBegusbeDaDaTor" ordered="false" upperBound="-1" eType="//AnfribufriguBofriFrinulAuBonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGubeBiGulus" eSuperTypes="//Fanulaunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulAuguGuDaBebeguGusDaTor" ordered="false" eType="//EuGudaFrinulautin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abegusgubidabibogubunulAuBibitus" ordered="false" upperBound="-1" eType="//AnbenulaugusCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusbodaGusGusgusBuDanulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duNulaudaBebubenulAubodaTor" ordered="false" eType="//Fanulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAubeBofriBicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafriDafriBoGusdafriBidaNulAubegulius" ordered="false" upperBound="-1" eType="//AuguboBuBonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauGubeBunulaufriNulautor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubiBoboguBuBeboBiGuCio" ordered="false" upperBound="-1" eType="//DobiFribiGubiBefriboTor" eOpposite="//DobiFribiGubiBefriboTor/dobuFrigubedabobebibucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbebiBunulauBobedanulaudacio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DodaNulaudaBegusbutus" instanceTypeName="typeFaNulaufrigusBugusNulauDagusCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusbufrigusgusfriboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusBoBudagubuFriguFrifrigusbibunus" eSuperTypes="//DifribofribuNulaunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiguBeFribedaBoNulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaufribeGusAunulAudabogubeGugusbiGustus" eSuperTypes="//EGubeBiGulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doFrifriBoBoGusnulaubiDaFrifriLius" eType="//EubonulauBigunulaufriLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulaunulAubibobiNulEs" ordered="false" upperBound="-1" eType="//EGubeBiGulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAufribebuDaBubegusauBiboguguBegudafridaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudagusgunulius" ordered="false" upperBound="-1" eType="//EgusbufrigusgusfriboTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAunulauGuDabudaBeGusdabunulAutor" eSuperTypes="//AnfribufriguBofriFrinulAuBonus"/>
</ecore:EPackage>
