<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eugugusgubudadafrilus" nsURI="http://hub.de/rcore/examples/eugugusgubudadafrilus" nsPrefix="tmux">
  <eClassifiers xsi:type="ecore:EClass" name="BebugugusfriboBugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibuBuguBunulaugusCus" eSuperTypes="//BebugugusfriboBugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnguNulAubegusaufribogusbidaguFriFries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBugudabuboguBibugusaudacio" eSuperTypes="//BebugugusfriboBugustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFribobibuFrigusgustin" ordered="false" upperBound="-1" eType="//BebugugusfriboBugustus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abufriBefridaBobicio" ordered="false" eType="//BibuBuguBunulaugusCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafridaFriTin" ordered="false" eType="//BebugugusfriboBugustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DodafridadafrinulauGugusAuNus" instanceTypeName="typeEdanulauGuBeBibibeGugusnulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbibibebeNulaunules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulaunulius" ordered="false" upperBound="-1" eType="//BibuBuguBunulaugusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubigusauBinulaufritor" abstract="true" eSuperTypes="//BibuBuguBunulaugusCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubogudaBuBetus" upperBound="-1" eType="//BibuBuguBunulaugusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubibeGugusgusauguslius" instanceTypeName="typeEuguGusBidagugugusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibogusDabogunulauNus" eSuperTypes="//AbibibebeNulaunules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euGusauBunulauBebitin" upperBound="-1" eType="//DodafridadafrinulauGugusAuNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AbubufriBilius">
    <eLiterals name="DibugusGubinulaubegubelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAubogusDabiBucus">
    <eLiterals name="BinulauboBogunulauGuGusBocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusBuGusgusguGusFribetus" eSuperTypes="//BebugugusfriboBugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobobebuboNulAutin" eSuperTypes="//AubigusauBinulaufritor //AnguNulAubegusaufribogusbidaguFriFries"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiboFrigusGufrinulAubeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusAuGufribifriguGuLius" ordered="false" eType="//AbibibebeNulaunules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubugufridadabutin" ordered="false" upperBound="-1" eType="//DobogunulaubodaFribodabeguscus" eOpposite="//DobogunulaubodaFribodabeguscus/bebiBudanulaubicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobogunulaubodaFribodabeguscus" eSuperTypes="//BebugugusfriboBugustus //BeBugudabuboguBibugusaudacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebiBudanulaubicio" ordered="false" upperBound="-1" eType="//DiboFrigusGufrinulAubeLus" eOpposite="//DiboFrigusGufrinulAubeLus/braubugufridadabutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusgusBedaGusgusBodabibutus" eSuperTypes="//AnguNulAubegusaufribogusbidaguFriFries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doGusbenulaufribeboGubodalius" eType="//AbubufriBilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABogufriFriTin" eSuperTypes="//BebugugusfriboBugustus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaGuBobifribuDafrifriGusNus" instanceTypeName="typeBrauBubobugusfriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibibogudaGusbeBonus" abstract="true" eSuperTypes="//BeBugudabuboguBibugusaudacio //DobogunulaubodaFribodabeguscus //DobobebuboNulAutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbogusDabiGustor" eType="//DagusgusBedaGusgusBodabibutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGudabugubees" abstract="true" eSuperTypes="//DibogusDabogunulauNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augubobobudagudaBibobogusbeNulEs" ordered="false" upperBound="-1" eType="//BibibogudaGusbeBonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbiGusbuNulaubobugubuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubodabubobeDadaGusGusbobigusBuLus" ordered="false" eType="//DiboFrigusGufrinulAubeLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabubunulauNulauBoBubilus" ordered="false" upperBound="-1" eType="//BibibogudaGusbeBonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abefribogubebinulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafrigusdaNulaubenulauBebitin" ordered="false" upperBound="-1" eType="//FagusBuGusgusguGusFribetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuDaguguboboBuboBibobedadadaTus" eSuperTypes="//DobogunulaubodaFribodabeguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dodanulaubuBoDadaFriNules" eType="//AbibibebeNulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EboBiBeBegubuBoFrigusGusbugusgusauLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebiNulaubobugusdafrinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogusbebunulaunulauCio" eType="//DodafridadafrinulauGugusAuNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGuGusgusbodabufrifriBuBubudaBiLius" abstract="true" eSuperTypes="//DiboFrigusGufrinulAubeLus //AbibibebeNulaunules //DuDaguguboboBuboBibobedadadaTus //DagusgusBedaGusgusBodabibutus"/>
</ecore:EPackage>
