<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albubilius" nsURI="http://hub.de/rcore/examples/albubilius" nsPrefix="L">
  <eClassifiers xsi:type="ecore:EClass" name="BiboGuGuguBifrifriFrigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBuboNulaubuguguNulaubobobiguLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubiguGubeguNus" eSuperTypes="//BiboGuGuguBifrifriFrigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibegudadaboEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubebonulaudadaBoDaTus" ordered="false" upperBound="-1" eType="//FaBuboNulaubuguguNulaubobobiguLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifribuGusGuBiGusgunulauDalus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EGusbubigusgusDagulius" instanceTypeName="typeAlbiguguGuguGuFrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBobiBeLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigusIus" eType="//EGusbubigusgusDagulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBinulauboNus" instanceTypeName="typeEbiDaguguLus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Eugusaubofrigubecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Bagusnulaugucus" instanceTypeName="typeEbuBuNulaugubiTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubuGusgusboGusbenulauBuNules" eSuperTypes="//DibegudadaboEs //DiBobiBeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriGusboboguFribidaBifritus" eSuperTypes="//BiboGuGuguBifrifriFrigulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebogubibudafritor" ordered="false" upperBound="-1" eType="//BiboGuGuguBifrifriFrigulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnAubofriFrifribofrinulaunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AldaBuDaDagusBofriBobubitin" instanceTypeName="typeDogusbuBuDagusdanulaubilus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnnulauBeBiGufrigusTin">
    <eLiterals name="DibugusbigusnulauGusbifrifriGustus"/>
    <eLiterals name="FanulaubibeguBeBonus"/>
    <eLiterals name="BenulAuNulaudaBiGusbobubibodalius"/>
    <eLiterals name="BibinulaubibibiFriboNulAubogutus"/>
    <eLiterals name="AFriGuFrinulauGusGuGusnulaulus"/>
    <eLiterals name="BiBinulAuBoGusbudaguBiNules"/>
    <eLiterals name="FabebiBebebiGubegusnulAutor"/>
    <eLiterals name="DubeGunulaubiGusAubies"/>
    <eLiterals name="DibebufribuBugusautin"/>
    <eLiterals name="EgunulAudabigusbeLus"/>
    <eLiterals name="BebibubebufriBibunulaubues"/>
    <eLiterals name="DabebigubinulAuGusGufrilius"/>
    <eLiterals name="DafridaFrinulaubibuGusDaBelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaguBebeBebobenulauBibubilus"/>
</ecore:EPackage>
