<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="banulaunus" nsURI="http://hub.de/rcore/examples/banulaunus" nsPrefix="pVy">
  <eClassifiers xsi:type="ecore:EEnum" name="ABuFriNulaunulaulus">
    <eLiterals name="Dobunulaulius"/>
    <eLiterals name="FafridanulAudaNulius"/>
    <eLiterals name="DuNulaubelus"/>
    <eLiterals name="Aulus"/>
    <eLiterals name="EuNulauBiNulAuguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DugubonulaufrigusGubenulauGuEs">
    <eLiterals name="AububeGubebubegutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAuGudaFriNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBoDafrinulAubogusgugusnulius" ordered="false" upperBound="-1" eType="//EdagusbebebuBicus" eOpposite="//EdagusbebebuBicus/duFriFriGusaubofries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGudaFrigudaBeDaGuBubuGuBunus" eSuperTypes="//AunulAuGudaFriNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulAufriBeguses" eType="//DugubonulaufrigusGubenulauGuEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusgunulaubuguFridanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdagusbebebuBicus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFriFriGusaubofries" ordered="false" upperBound="-1" eType="//AunulAuGudaFriNus" eOpposite="//AunulAuGudaFriNus/auBoDafrinulAubogusgugusnulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duguDanulauTor" eType="//DugubonulaufrigusGubenulauGuEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGuGubigusdagusaubiGusnus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabeGufrinulauBubibubulius" eType="//DugubonulaufrigusGubenulauGuEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abiBubiBoNus" eType="//DugubonulaufrigusGubenulauGuEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGuGufriBonulauBotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGusdaBefriboGusboBinulEs" upperBound="-1" eType="//FaGusgunulaubuguFridanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugusGunulauGuBoGusbofricio" instanceTypeName="typeAudaDafrigusDaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABeFrigusgusfribiGuguBoBifriLus" abstract="true" eSuperTypes="//DaGuGufriBonulauBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusGusdagubogugusnulAubigulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboFrigusnulAubenulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugubiBoBigusbubibefriguBilus" eType="//ABuFriNulaunulaulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusNulaubuNulauGusGuslus" ordered="false" upperBound="-1" eType="//AunulAuGudaFriNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufriBobidabubetin" eSuperTypes="//AunulAuGudaFriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubibugusDaguNulaufriBububuGudatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabigubeGudafritus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgugunulAugusaugunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidagutin" eType="//ABeFrigusgusfribiGuguBoBifriLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euboGusbodabuDafritin" ordered="false" eType="//ABeFrigusgusfribiGuguBoBifriLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuboBoGusdabofrinulaubuDaDaBicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBelus" ordered="false" eType="//DiboBoBebobibotin" eOpposite="//DiboBoBebobibotin/eguBoDaGuBebiguFridacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibifribuGusGububiBibodalus" ordered="false" eType="//AnGudaFrigudaBeDaGuBubuGuBunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubububiBobeGubeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufrigusBelus" ordered="false" upperBound="-1" eType="//FaGusgunulaubuguFridanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbofribeDaBugusgudaNus" eSuperTypes="//DaGuGufriBonulauBotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabogusbenulaubebefriGusbetor" instanceTypeName="typeDuNulaubogusnulauboDafribibonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusBigudaboGugusAunus" abstract="true" eSuperTypes="//AunulAuGudaFriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagubuBiguBubuGufrifrinulaubiBeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabebobiBubibobonulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fafribunulAubugufrinulIus" eType="//BraugusGunulauGuBoGusbofricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaFriNulauboBobobucio" eSuperTypes="//EdagusbebebuBicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dodabelius" eSuperTypes="//AubububiBobeGubeTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" upperBound="-1" eType="//DabogusbenulaubebefriGusbetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGubobuGugusGusfrinulaubugubeBogubuEs" abstract="true" eSuperTypes="//BabigubeGudafritus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aEs" eType="//ABuFriNulaunulaulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabuGunulaufrigusdaguTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beFribibinus" eType="//DabogusbenulaubebefriGusbetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabibunulauBinulAuBenulAufriTor" instanceTypeName="typeFadaboBofributus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBiNulAuBoguTor" abstract="true" eSuperTypes="//FaGusgunulaubuguFridanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufribeFribebuguNulaubufriguNus" ordered="false" upperBound="-1" eType="//AubububiBobeGubeTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anbidabubufrifrilius" eSuperTypes="//Allius //DabuGunulaufrigusdaguTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EFribubebebiGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiboBoBebobibotin" abstract="true" eSuperTypes="//AunulAuGudaFriNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguBoDaGuBebiguFridacus" ordered="false" eType="//DuboBoGusdabofrinulaubuDaDaBicio" eOpposite="//DuboBoGusdabofrinulaubuDaDaBicio/anBelus"/>
  </eClassifiers>
</ecore:EPackage>
