<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="babitus" nsURI="http://hub.de/rcore/examples/babitus" nsPrefix="BO">
  <eClassifiers xsi:type="ecore:EClass" name="EbigubodabibigusBefridaguboes" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogusbibenulaubeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeBigububebobodabudalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfrigusguguboDanulauBibunulauFriTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baboGuGusbuGusBeFridaFricus" ordered="false" eType="//EbigubodabibigusBefridaguboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfribobuBenulAububotor" eSuperTypes="//EbigubodabibigusBefridaguboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBubiNulauTor" ordered="false" eType="//AlfrigusguguboDanulauBibunulauFriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AububobeNulAuNulauNulaubenulaubitin">
    <eLiterals name="BaGububiBenus"/>
    <eLiterals name="DanulaufrigusDaDadafridaNulautor"/>
    <eLiterals name="BaBiGuboGudadanulaunulauguFrinus"/>
    <eLiterals name="AlguguboGuEs"/>
    <eLiterals name="AugudaBebegusbodaguslus"/>
    <eLiterals name="BeGusBeGusBobunulius"/>
    <eLiterals name="EfrifribobebiguguNulAuCio"/>
    <eLiterals name="AugusdabubiBolius"/>
    <eLiterals name="BabobenulAudanulAuDagugusNules"/>
    <eLiterals name="DibigusdaNulAucus"/>
    <eLiterals name="EbenulAufrinulAufrigudagucio"/>
    <eLiterals name="FanulAuBoNulaufribeGustin"/>
    <eLiterals name="AlgudabibedanulaugusGusLius"/>
    <eLiterals name="AngusbuGuGugusGusdagusgusdalius"/>
    <eLiterals name="DiGusBees"/>
    <eLiterals name="DoNulaugudaBubeFrigusbicio"/>
    <eLiterals name="DoGusBeDabigusgucio"/>
    <eLiterals name="AlBibofriBebuEs"/>
    <eLiterals name="BedagusnulAuDaNulaudaguBefribuBiTin"/>
    <eLiterals name="AdabububibeTin"/>
    <eLiterals name="BabuboGusdaGusbiDagusautin"/>
    <eLiterals name="AbugusBulius"/>
    <eLiterals name="BraudadaGufriEs"/>
    <eLiterals name="Aubunulaugusbugugugusbecus"/>
    <eLiterals name="AlNulauBibogudanules"/>
    <eLiterals name="EdadagusButin"/>
    <eLiterals name="BabebebugubiBiGubibodaNulauGucus"/>
    <eLiterals name="AFrigusbefribugusFribubilius"/>
    <eLiterals name="DogusbigusbuBeboTus"/>
    <eLiterals name="AlDabubeFribobobebobebugudaLius"/>
    <eLiterals name="DodabogubigusBuBebeNus"/>
    <eLiterals name="DodaguNulaugugufribedaBifribilius"/>
    <eLiterals name="EbeFriBigusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraunulaubinulaubobifriDabububutin" instanceTypeName="typeAnbigusBubebegubobuBefritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuboBufribiboTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaububigusnulaudabugubulius" ordered="false" eType="//AlfrigusguguboDanulauBibunulauFriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnaufribuBinulaudaDafriFriboGucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabonulauGusfriBoBeBenulius" eSuperTypes="//DogusbibenulaubeEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBodaNulauBifriBugusdagugudaCus" ordered="false" eType="//AlfrigusguguboDanulauBibunulauFriTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulaudaBoBebegubobefribobebeguEs" upperBound="-1" eType="//AlfrigusguguboDanulauBibunulauFriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiGuBebuBoBoFrifrigusbedagusbiBilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusNulauBuBedaBegusaudaboTor" ordered="false" eType="//AfribobuBenulAububotor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubobebogusGuNulAucus" eType="//BraunulaubinulaubobifriDabububutin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaNulAuBiboguBigusBelius" ordered="false" eType="//BraubeBigububebobodabudalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngunulauGufridagusbidanulauBegunulIus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagubenulaubiFribobefrifries" ordered="false" eType="//DuboBufribiboTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFrinulaudaBifriBigubibebuNules" ordered="false" eType="//AnbiGuBebuBoBoFrifrigusbedagusbiBilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugubodaDaboFribonulaudaboBoGuEs" ordered="false" upperBound="-1" eType="//EbiDaBuGuboLus" eOpposite="//EbiDaBuGuboLus/bebubugusFriBiBiGusdaguDaTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulauBiBobeBubigusius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabebobubobubobeNulauboNulauLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadaNulaubufriNulius" ordered="false" upperBound="-1" eType="//AlfrigusguguboDanulauBibunulauFriTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anFriBibigugulus" ordered="false" upperBound="-1" eType="//DagusaubuGusBiDaBoBucus" eOpposite="//DagusaubuGusBiDaBoBucus/euGusboboGuGusDafriBibilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBoFriboBibeBiBenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibeBoNulauFrigustus" ordered="false" upperBound="-1" eType="//DuboBufribiboTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EuBibibedator">
    <eLiterals name="BraudaBigusCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauBiBolius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubobebobinulaubegulus" ordered="false" upperBound="-1" eType="//AngunulauGufridagusbidanulauBegunulIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eNulAunulauBoBebucio" ordered="false" eType="//BraubeBigububebobodabudalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BibinulAubuFriDaBiNulAuLus">
    <eLiterals name="BrAubegunulAufries"/>
    <eLiterals name="AuBeGusnulaubifriBitor"/>
    <eLiterals name="DonulaubobofriGuNulaubefriEs"/>
    <eLiterals name="BaguguLius"/>
    <eLiterals name="AngusBubebiGutus"/>
    <eLiterals name="DaFriGugusbinulauBebobefricus"/>
    <eLiterals name="AlnulaubebebenulauBeboEs"/>
    <eLiterals name="AndaBiBoNulauTin"/>
    <eLiterals name="DuBiDaFriBubebenulaububofriDaguslius"/>
    <eLiterals name="AguFrifriFriBobeBonulAubibeGugubecus"/>
    <eLiterals name="AnbebubudaBicus"/>
    <eLiterals name="AuDabugufrinulauBegucus"/>
    <eLiterals name="AlfriGuNulautin"/>
    <eLiterals name="DubuFriBebugusGusbotor"/>
    <eLiterals name="AdagububuguNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebugufrifrinulAubobotor" eSuperTypes="//FabebobubobubobeNulauboNulauLus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BibefrifribufrigudabiboTin">
    <eLiterals name="DuBenulaubebugusbobiDaBoLius"/>
    <eLiterals name="BabeBuBubibibobeGusguGusbibufribitus"/>
    <eLiterals name="AndabedabuGuguscus"/>
    <eLiterals name="BafriFriNulAuguFribubudaGusbudabuLius"/>
    <eLiterals name="AlDaBufrinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibubuDaGuBebuGuNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibeBebegugubegusbiBotin" abstract="true" eSuperTypes="//BabonulauGusfriBoBeBenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbiDaBuGuboLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebubugusFriBiBiGusdaguDaTor" ordered="false" upperBound="-1" eType="//AngunulauGufridagusbidanulauBegunulIus" eOpposite="//AngunulauGufridagusbidanulauBegunulIus/eugubodaDaboFribonulaudaboBoGuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeFriNulaunulaufrigucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabogusbegusfribudagulus" upperBound="-1" eType="//AnbiGuBebuBoBoFrifrigusbedagusbiBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubobeDadafribebocio" instanceTypeName="typeFaBobiDaBebeBeBibifridafrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobuFribudadabubeGusbebeLius" eSuperTypes="//BraubeBigububebobodabudalius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudaguBubibenulauBecus" eType="//BebugufrifrinulAubobotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBuNulauFribiNulauBeDanulIus" abstract="true" eSuperTypes="//DogusbibenulaubeEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubuGusgusbibebiDagusnulauGulius" ordered="false" eType="//BabeFriNulaunulaufrigucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="audaBiBibebubigusbiguCus" ordered="false" eType="//FaBonulaubunulaubeDabugusbidabutor" eOpposite="//FaBonulaubunulaubeDabugusbidabutor/dufriboguguFrinulauBufribubebeTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AgusnulauboboBoboCus" instanceTypeName="typeDonulaufrifriGuDator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAugusBifriLius" eSuperTypes="//DibeBebegugubegusbiBotin //AnbiGuBebuBoBoFrifrigusbedagusbiBilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusbigusDaboBoNulAutus" ordered="false" eType="//FafriFriBufribiboGusGutus" eOpposite="//FafriFriBufribiboGusGutus/aldafriguBifriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnDabeBofriGuBiguses" eSuperTypes="//AngunulauGufridagusbidanulauBegunulIus //DuBoFriboBibeBiBenus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BanulAubinulaudaNulAuFriNus" instanceTypeName="typeDuBugudabubebigusnulautor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DububonulaunulauNus" instanceTypeName="typeAlbudabibidabobifribees"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegufribeBotor" eSuperTypes="//BabeFriNulaunulaufrigucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbofridabiDatus" abstract="true" eSuperTypes="//FabebobubobubobeNulauboNulauLus //AnaufribuBinulaudaDafriFriboGucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafriFriBufribiboGusGutus" eSuperTypes="//BegufribeBotor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldafriguBifriTus" ordered="false" upperBound="-1" eType="//DunulAugusBifriLius" eOpposite="//DunulAugusBifriLius/doGusbigusDaboBoNulAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusDadaBonulAubuGubonulaunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigubodagusbinulaulius" eType="//AububobeNulAuNulauNulaubenulaubitin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBibiFrigunulaudaFribonus" ordered="false" upperBound="-1" eType="//DodabiTin" eOpposite="//DodabiTin/alnulAubenulAulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EfrifrifribuguBedaguGusGunulauTor">
    <eLiterals name="Befrigubigusgusgustor"/>
    <eLiterals name="BiBobiBubugubogusnulAuBeGues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaubifriBiGusbugusLius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faguBeboGuboguLus" ordered="false" eType="//AnbiGuBebuBoBoFrifrigusbedagusbiBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulaubofriDacio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubobedaBonus" instanceTypeName="typeEgusdadanulaugusgufrifriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubogugububuGuFriGusnulAuLius" eSuperTypes="//FafriFriBufribiboGusGutus //BabonulauGusfriBoBeBenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebubeFridabudatin" eSuperTypes="//EbigubodabibigusBefridaguboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBuFrigudagusGunulaudaBoGusbunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGuGubonulaufriBifribodaFriguGusbotin" ordered="false" eType="//DibubuDaGuBebuGuNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebubeNulAuguFriBuGusBoLius" instanceTypeName="typeFaNulAunulaubifriBeCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabubigubebobuDanulauTor" eSuperTypes="//EbiDaBuGuboLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguboGunulauguDabiNulauFrilius" ordered="false" eType="//BigusBeBuguDaDaBigusBoLus" eOpposite="//BigusBeBuguDaDaBigusBoLus/danulaubofriNulAubuBidagusfribofrinulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAuGufribilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBoboBuBeBubobubegusNulaubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriGusBebiFribobulus" eSuperTypes="//AngusDadaBonulAubuGubonulaunus //AnulaubifriBiGusbugusLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibibufriGusgubegubuTus" ordered="false" eType="//DodabogusGusgusbobutor" eOpposite="//DodabogusGusgusbobutor/danulAuNulAuguGusGububefriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBoNulaugulus" abstract="true" eSuperTypes="//FafriFriBufribiboGusGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusgusbobigusbiBibetus" abstract="true" eSuperTypes="//BenulAuGufribilus //EbigubodabibigusBefridaguboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulauFridabobibuguTin" eSuperTypes="//EubogugububuGuFriGusnulAuLius //AnulaubifriBiGusbugusLius //AlBoNulaugulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAububigusDabegusbigustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusBeBuguDaDaBigusBoLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulaubofriNulAubuBidagusfribofrinulaulus" ordered="false" upperBound="-1" eType="//BabubigubebobuDanulauTor" eOpposite="//BabubigubebobuDanulauTor/eguboGunulauguDabiNulauFrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAubibofriGusBibeBedacio">
    <eLiterals name="DubibuFribuNulAuFritor"/>
    <eLiterals name="AuboguboBoDagusbebugugusnules"/>
    <eLiterals name="AnbonulaudabeBuboCio"/>
    <eLiterals name="DubebuBofribebedaBeBonus"/>
    <eLiterals name="EbodaTin"/>
    <eLiterals name="EugusbuBodagusbuBigubufrifriguBicus"/>
    <eLiterals name="AnbebedanulAuNulauBelus"/>
    <eLiterals name="EuBeNulaugusguBubiFrigusNulaugues"/>
    <eLiterals name="BraugunulaunulAunulEs"/>
    <eLiterals name="DanulauBobubidaGusbiBuGubinus"/>
    <eLiterals name="FanulaugusauboBeNulauBigubecio"/>
    <eLiterals name="FaNulauDagusBobeguGuCus"/>
    <eLiterals name="BefribobegugusBonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafriBoBibebetin" eSuperTypes="//EubogugububuGuFriGusnulAuLius //DaBuNulauFribiNulauBeDanulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auDaFribuGubibibigusDabibodadafries" ordered="false" upperBound="-1" eType="//BabeFriNulaunulaufrigucus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dudanulaufribiDabobunulAubilius" eType="//DububonulaunulauNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuGubibibebebofrigusBitus" eSuperTypes="//BaBoboBuBeBubobubegusNulaubocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBeBufriGusdabeBuBocio" upperBound="-1" eType="//FaBebibubeGunulauTin" eOpposite="//FaBebibubeGunulauTin/didabebuFridaTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubodaBoDalius" instanceTypeName="typeBrAuboBeguGusGusbeDagusbolus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabegusAubogusfribetin" instanceTypeName="typeEuBunulaubidanulaufribufriDaGuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodabogusGusgusbobutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faDaBuBefrigusbiDanus" ordered="false" upperBound="-1" eType="//BraubeBigububebobodabudalius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulAuNulAuguGusGububefriTus" ordered="false" eType="//DufriGusBebiFribobulus" eOpposite="//DufriGusBebiFribobulus/dibibufriGusgubegubuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufriBubofriBeBoCus" eSuperTypes="//AnulaubifriBiGusbugusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusaubuGusBiDaBoBucus" eSuperTypes="//EbiDaBuGuboLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGusboboGuGusDafriBibilius" upperBound="-1" eType="//FabebobubobubobeNulauboNulauLus" eOpposite="//FabebobubobubobeNulauboNulauLus/anFriBibigugulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faNulaubugusbonulAuboFribuBuGusBucio" ordered="false" upperBound="-1" eType="//AnDabeBofriGuBiguses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagugudaBiBuBeboguslus" ordered="false" eType="//BigusBeBuguDaDaBigusBoLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifrinulaufriNulAuboCus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobudadabigufrilus" ordered="false" eType="//AbofridabiDatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfriBiGubiDaDaGuslius" ordered="false" upperBound="-1" eType="//AnulaubifriBiGusbugusLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFrigusbubocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFriguboDanulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlguBinulauDanulAubodanulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AgugubogufriDabees">
    <eLiterals name="AufriGusboDaBeFriBoguslus"/>
    <eLiterals name="DonulauGusAuGuslus"/>
    <eLiterals name="FabibibedagusBigubifriBedaBibuBebitor"/>
    <eLiterals name="FabuBeBebebibiNulauDaCus"/>
    <eLiterals name="BefriGubiBegusbebies"/>
    <eLiterals name="BaGubufriLus"/>
    <eLiterals name="AbegusfribeDafridaLus"/>
    <eLiterals name="DabiBuBibiBebobibibeTin"/>
    <eLiterals name="BaGusgugusNulaunulaubefrigubolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodabiTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulAubenulAulius" eType="//AngusDadaBonulAubuGubonulaunus" eOpposite="//AngusDadaBonulAubuGubonulaunus/doBibiFrigunulaudaFribonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBinulauNulAuGubiNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BagusDabegusnulauDaGusdaGunulaucus" instanceTypeName="typeBraunulaubobugusbiCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboGuGusGusGusbebeBidalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFrigufriDabugusbobudaDanulius" eSuperTypes="//DufriBubofriBeBoCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudagudagubibubotin" ordered="false" upperBound="-1" eType="//EugusgusbobigusbiBibetus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubeguNus" ordered="false" eType="//EubebubeFridabudatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AFridanulaubibiFriNulIus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DoGuguBeguDaNulaubugusboBebolius">
    <eLiterals name="BaBiguFriboBiGusboNulauBudaTus"/>
    <eLiterals name="AlbeBibubebunulaububutus"/>
    <eLiterals name="DofribibebububeGudanulaubefriguCus"/>
    <eLiterals name="AuBibeguDabiGuBofribiGuslus"/>
    <eLiterals name="BenulaubibubuBubobobonulAuDatus"/>
    <eLiterals name="BebibigufriBedafriGugusgusBilius"/>
    <eLiterals name="BabedaGusBuguBebuboBubobebudafriBiNus"/>
    <eLiterals name="BrAubibiFriDabilius"/>
    <eLiterals name="BenulaudanulAudafrilus"/>
    <eLiterals name="FaBogusbiGusgusbedabibonus"/>
    <eLiterals name="BebudagusfriGusnus"/>
    <eLiterals name="DibigusdanulAugudaguscus"/>
    <eLiterals name="DafriBeBuBoBoGusbonulAudagusCio"/>
    <eLiterals name="DobebunulAunulaugusBonulaubiguguscio"/>
    <eLiterals name="DabofribibiBibobogubugusLius"/>
    <eLiterals name="AubobibubebiNulaugustor"/>
    <eLiterals name="EuGudabuBodagunulautus"/>
    <eLiterals name="AlbinulaubegusBugusbufridacio"/>
    <eLiterals name="DibuBuBedagusbudatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeboFriGusbiBeBufriDaes" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAuFribiBoNulauTus" instanceTypeName="typeBabebebebonulaubenulIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusdabuDaDaboBuCus" instanceTypeName="typeAngubebiBetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBonulaubunulaubeDabugusbidabutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufriboguguFrinulauBufribubebeTus" ordered="false" upperBound="-1" eType="//DaBuNulauFribiNulauBeDanulIus" eOpposite="//DaBuNulauFribiNulauBeDanulIus/audaBiBibebubigusbiguCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBegusbudadabebogusBucio" eSuperTypes="//DodabiTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aguGusbifriDanulaubuNulauDacus" eType="//DogusdabuDaDaboBuCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibenulauBiGusBobobuNus" abstract="true" eSuperTypes="//BaNulauBiBobeBubigusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAugubedaGudabinus" eSuperTypes="//EunulauBiBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADadagusFriFriBunulEs" eSuperTypes="//DufriBubofriBeBoCus //BrAububigusDabegusbigustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBibeBuboNulAubotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algusfridaFriNulaufriTus" ordered="false" eType="//AuBegusbudadabebogusBucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dububiNulAubefricus" ordered="false" upperBound="-1" eType="//DodabogusGusgusbobutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusbiguFrifridabegutin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigunulAugusguguDaNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbuboGusfrifrifribiEs" eSuperTypes="//BrAububigusDabegusbigustor //DiNulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulAuGusGudadaBilus" ordered="false" upperBound="-1" eType="//BabubigubebobuDanulauTor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braunulAuboTus" eType="//DububonulaunulauNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubufriguFribeBoboDanus" ordered="false" eType="//AnnulAugubedaGudabinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBegudagunulAuGunulaubotin" ordered="false" eType="//BegufribeBotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBebibubeGunulauTin" abstract="true" eSuperTypes="//AngunulauGufridagusbidanulauBegunulIus //DufriBubofriBeBoCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifriDagusbiCus" ordered="false" eType="//AuboGuGusGusGusbebeBidalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="didabebuFridaTin" ordered="false" eType="//BrAuGubibibebebofrigusBitus" eOpposite="//BrAuGubibibebebofrigusBitus/alBeBufriGusdabeBuBocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaufribubibebebiGugudatus" eSuperTypes="//AnBinulauNulAuGubiNus //EubogugububuGuFriGusnulAuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGusFrifriBuBubobugusgutor" ordered="false" upperBound="-1" eType="//AnaufribuBinulaudaDafriFriboGucio"/>
  </eClassifiers>
</ecore:EPackage>
