<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dicio" nsURI="http://hub.de/rcore/examples/dicio" nsPrefix="wfu">
  <eClassifiers xsi:type="ecore:EClass" name="BibeGusaubeFrinulauGusguslius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiboDanules" ordered="false" upperBound="-1" eType="//AuBobubogusbuLus" eOpposite="//AuBobubogusbuLus/fadaBubobegulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBobubogusbuLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadaBubobegulius" ordered="false" upperBound="-1" eType="//BibeGusaubeFrinulauGusguslius" eOpposite="//BibeGusaubeFrinulauGusguslius/fabiboDanules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abigusfries" upperBound="-1" eType="//AlTor" eOpposite="//AlTor/dafrifribuNulaubunulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlTor" abstract="true" eSuperTypes="//BibeGusaubeFrinulauGusguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafrifribuNulaubunulaulius" eType="//AuBobubogusbuLus" eOpposite="//AuBobubogusbuLus/abigusfries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugubunulauBeGunulauFriguEs" eSuperTypes="//BibeGusaubeFrinulauGusguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGusgufriboGudabinulius" ordered="false" eType="//AnbeNulIus" eOpposite="//AnbeNulIus/biboFrigugusbuGusbeboNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubegubedaBefriTor" instanceTypeName="typeDuFridaBugubiDanulaubigusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Edabidatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Danules" eSuperTypes="//AuBobubogusbuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufrinulauBeBoguLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibugunulauBuDanulauCio" upperBound="-1" eType="//BraubegubedaBefriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGudadabugusnulauCus" eSuperTypes="//AuBobubogusbuLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbogubobufriBeBeButor" instanceTypeName="typeEugusGusdaBuBeBiBucio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FafrifrinulauNulaubiNulAuBies">
    <eLiterals name="AubidabiBobubebebiBuLius"/>
    <eLiterals name="EuBinulaugusgugusfribobuBudagusfritin"/>
    <eLiterals name="AnBigugunulaudaFriBegusIus"/>
    <eLiterals name="AnBoBobebugubibubebiEs"/>
    <eLiterals name="BaDagufribebifriGuses"/>
    <eLiterals name="EguboBoboCus"/>
    <eLiterals name="FadaDaGusfriGuDanulautin"/>
    <eLiterals name="FaGusBugusauBeBedanulautin"/>
    <eLiterals name="DofriBububobodagusgusBubifries"/>
    <eLiterals name="FanulAubifriboBuBunulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubegunulauGufrilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augusbiBogubibiGusGuscio" eType="//AlbogubobufriBeBeButor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiNulaunulaubibegusauNulaugusBobeCus">
    <eLiterals name="AldaFrifriFribeGuBiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BedaGusbobibeBibegubifridaboNulEs" instanceTypeName="typeDunulaudaDadabilius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FadadagusGusFrinulaulius">
    <eLiterals name="EGufriguguBinulaugutor"/>
    <eLiterals name="AuBubeFricio"/>
    <eLiterals name="BabugusnulAubibeBidabenulaunulIus"/>
    <eLiterals name="DofrifridaBefridaNulAugubebebugusgunulIus"/>
    <eLiterals name="BibeFribobigufriFriBuGubies"/>
    <eLiterals name="EbubuBobiDagudaBidaguslius"/>
    <eLiterals name="Dogufrinulautor"/>
    <eLiterals name="DobudaboBedaBeguTor"/>
    <eLiterals name="DububeBogusbebigusfriBobeBuBocio"/>
    <eLiterals name="DigusgusnulaubenulAufrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubodabubogusbunulAubutor" instanceTypeName="typeDabuBiBebobiBuBifritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauguFribugunulaubuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGufrinulaufriBibeBoFricio" ordered="false" upperBound="-1" eType="//AubegunulauGufrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudabobugusbogububigusGusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobugubodagububobubogubigustus" eSuperTypes="//AuBobubogusbuLus //AubegunulauGufrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Anbobonulaunulaufribugubucus" instanceTypeName="typeBabiguNulaunulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibibodaDafriBiBucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EGusauguFrigusbilus">
    <eLiterals name="FaGusbigubebegusdaTin"/>
    <eLiterals name="AugubuNulaubobufrigubiBocio"/>
    <eLiterals name="DufriDagusgusboBebibonulauCus"/>
    <eLiterals name="BenulaubefrigusFriNulautin"/>
    <eLiterals name="AubiGusnulauNulAugusfrilius"/>
    <eLiterals name="AldabefriGunules"/>
    <eLiterals name="DoDanus"/>
    <eLiterals name="FadaBebufribuNulaudabuNulEs"/>
    <eLiterals name="Fabinulaubifrinus"/>
    <eLiterals name="DuNulaudaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eugusgusbubububinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abibegubodagusGusFrigubecus" ordered="false" eType="//AuBobubogusbuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusaunulaunulauBeguguGusfriboBibibiTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlauBebeNulAunulauBoBoDaGusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguBiGugusaufribugusnulauFribiTin" ordered="false" eType="//AnGudadabugusnulauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnFriBebudadagufribeBidaGusgusaucio" abstract="true" eSuperTypes="//EudabobugusbogububigusGusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGubibiGusfrigusBidabiNulautor" eSuperTypes="//BibeGusaubeFrinulauGusguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeguDaguDabuguGuslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafrigusbiBoDabubuNulAutor" ordered="false" upperBound="-1" eType="//Danules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faboBubuBeBefribidabeboCus" ordered="false" upperBound="-1" eType="//BrauguFribugunulaubuLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboFrigugusbuGusbeboNules" ordered="false" eType="//AugubunulauBeGunulauFriguEs" eOpposite="//AugubunulauBeGunulauFriguEs/diGusgufriboGudabinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbuBodabuGuNus" eSuperTypes="//EudabobugusbogububigusGusTin //Eugusgusbubububinus //AnbeNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbiDagusgusBonus" ordered="false" upperBound="-1" eType="//DaBeBuGuBiDagusAubigugubebebunulAugucio" eOpposite="//DaBeBuGuBiDagusAubigugubebebunulAugucio/dogusbenulaubobecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBeBuGuBiDagusAubigugubebebunulAugucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusbenulaubobecus" ordered="false" eType="//DugusbuBodabuGuNus" eOpposite="//DugusbuBodabuGuNus/anbiDagusgusBonus"/>
  </eClassifiers>
</ecore:EPackage>
