<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="br" nsURI="http://hub.de/rcore/examples/br" nsPrefix="Kf">
  <eClassifiers xsi:type="ecore:EClass" name="FagunulaubiBoGusgusguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiDabuBoboBiguBibibenulaudaboes" eSuperTypes="//FagunulaubiBoGusgusguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebibeNulaubibudaGugubodaEs" ordered="false" eType="//FagunulaubiBoGusgusguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubeboBugunulaufribiboGulius" eSuperTypes="//FagunulaubiBoGusgusguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daDaBuGusBidabiguTor" ordered="false" upperBound="-1" eType="//DiDabuBoboBiguBibibenulaudaboes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBebunulAudabebebecus" upperBound="-1" eType="//EuBigusaudafrigusAutus" eOpposite="//EuBigusaudafrigusAutus/euGuBobufritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBigusaudafrigusAutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGuBobufritor" ordered="false" upperBound="-1" eType="//AubeboBugunulaufribiboGulius" eOpposite="//AubeboBugunulaufribiboGulius/doBebunulAudabebebecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusAuDaDaBeNulaucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EBoBifriBuboBuNulaubifritin" instanceTypeName="typeDaDadafriNulAulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulaugusgusbubebubiLius" eSuperTypes="//FagunulaubiBoGusgusguscus //DiDabuBoboBiguBibibenulaudaboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufriFries" eType="//EBoBifriBuboBuNulaubifritin" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
