<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dilius" nsURI="http://hub.de/rcore/examples/dilius" nsPrefix="En">
  <eClassifiers xsi:type="ecore:EClass" name="BrauboguGubodaDatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daboBeboboBebudatus" upperBound="-1" eType="//Abebobefribetus" eOpposite="//Abebobefribetus/bebodabugusbegunulAuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EdaDabugusgufribeboBucus" instanceTypeName="typeAlBeBobifrigusFrifrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abebobefribetus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebodabugusbegunulAuLus" ordered="false" upperBound="-1" eType="//BrauboguGubodaDatin" eOpposite="//BrauboguGubodaDatin/daboBeboboBebudatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EgusbububuGuBogusIus">
    <eLiterals name="AnbunulaubuDagutin"/>
    <eLiterals name="DaBiboBenulauboBibubebubugusgusnus"/>
    <eLiterals name="FaBiBofrifriDaNulAufriGusFribulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusGubiBoDaBuNulaubeguEs" instanceTypeName="typeAnaudaNulAuGutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaguguboDanulaufriboLius" instanceTypeName="typeAuboFridanulAuBoBudaNulaugusnulaugubelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaFriFriBubebubonulauDaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubofribunulAubedabinulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auBobebunulautus" eType="//DogusGubiBoDaBuNulaubeguEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobobiguGusboguses" eSuperTypes="//DaFriFriBubebubonulauDaLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusbeBefrinulAubuGusnulauBiguBoBiCio" ordered="false" upperBound="-1" eType="//Abebobefribetus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abuguBogusBeguscio" eType="//FaguguboDanulaufriboLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABenulaufribiDanulautor" abstract="true" eSuperTypes="//Abebobefribetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabiGusGusaugugusguGuguBobeBoLus" ordered="false" upperBound="-1" eType="//BrauboguGubodaDatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dodabefritin" abstract="true" eSuperTypes="//DaFriFriBubebubonulauDaLius //BrauboguGubodaDatin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBobidabibogustor" eType="//EgusbububuGuBogusIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BebeDaBeGudaGuDaBobobeGusTin">
    <eLiterals name="AnbidaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuboBinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAuDaEs" eSuperTypes="//BrAubofribunulAubedabinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabeBogubicus" eSuperTypes="//DaFriFriBubebubonulauDaLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AububodabuGudaboTor" instanceTypeName="typeFaBoNulaubedaEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeguBubebufriBufriguGusTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebudafrinulaunulius" eType="//BebeDaBeGudaGuDaBobobeGusTin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edadaTus" upperBound="-1" eType="//EdaDabugusgufribeboBucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaBeLius">
    <eLiterals name="BraunulauDaFriDabobudabonus"/>
    <eLiterals name="Ebugugusbefritin"/>
    <eLiterals name="EunulAudaGufrigudanulaucus"/>
    <eLiterals name="EunulaubebofrinulAuBofriFritin"/>
    <eLiterals name="AlGuboBobugusFries"/>
    <eLiterals name="AFriNulauBeBiboDagusbuGusDadabeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabeFriFriboGutus" instanceTypeName="typeDanulaugusAunulaudabobibigustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubeNulAubebeguCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfrigusbubibegusbuBugudaBuDaGunules" eSuperTypes="//DaFriFriBubebubonulauDaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusBegubibobigusbiGuGusaulus" eSuperTypes="//Abebobefribetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubuGusbofrigugusaugubinulaudagulus" eType="//EgusbububuGuBogusIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGudabububegubuBebitor" eSuperTypes="//Dodabefritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagugudabeGusNulAuFriLius" eSuperTypes="//AnbeguBubebufriBufriguGusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusbiGugubebefributor" eSuperTypes="//AlnulAuDaEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGubinulaunulauFrinulaubeBufrifrilus" eSuperTypes="//DaFriFriBubebubonulauDaLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugubobuBeFriboCus" eType="//FaBeLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abodagusboGusnulaunulauGusauDaes" ordered="false" eType="//BrauboguGubodaDatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbubuGuNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Anulaudadadabogusbilius" instanceTypeName="typeFabodadagusgusfrifriEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EBeguDanus" instanceTypeName="typeDunulAudabubeGugusgusaubobibeBefriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusbunulAubobobies" eSuperTypes="//DaFriFriBubebubonulauDaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfribogusFridabuboguguBetor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiBiNulaudaTus">
    <eLiterals name="AugusfribenulauGucus"/>
    <eLiterals name="BigubefriboGudaDadaBiguTin"/>
    <eLiterals name="AnbuBonulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBeNulAubuBegufriguBigudabibonulAulius" eSuperTypes="//AbubuGuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaugusdagusBiguGusbibigusNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EBufrinulauFriguslus">
    <eLiterals name="BibobidaNulaubuFrigustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboDabenulAuguDaGudaEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuguBebigubibifridaguBugustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabiBeGuBegubiNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGusnulauFriNulauGusaugues" ordered="false" upperBound="-1" eType="//DobobiguGusboguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdaboBifridaBoguNulAuBuDaes" eSuperTypes="//BrAubofribunulAubedabinulius //AnfribogusFridabuboguguBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubigusguBobiNulaufriCus" eSuperTypes="//DabeBogubicus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusbodagunulaubebiTus" ordered="false" upperBound="-1" eType="//ABenulaufribiDanulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbubeNulaubufribedabucus" abstract="true" eSuperTypes="//AfrigusbubibegusbuBugudaBuDaGunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAuguGubeBeDaBedabegusgutin" eSuperTypes="//AfrigusbubibegusbuBugudaBuDaGunules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BagugusNulIus" instanceTypeName="typeDagugugubigusGubigusbeguGubicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabudaBuBufritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbobelus" ordered="false" upperBound="-1" eType="//DagusbiGugubebefributor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusgusBeGuboBigusDaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgubibubebigusGuGubobolus" eSuperTypes="//AugusBegubibobigusbiGuGusaulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babofribeBiEs" eType="//DiBiNulaudaTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albedatin" ordered="false" eType="//AbubuGuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBubigugusgubees">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doNulaububobobebenus" eType="//FaguguboDanulaufriboLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebobeFribobudaes" ordered="false" upperBound="-1" eType="//AlbubeNulaubufribedabucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bebebedabibilus" eSuperTypes="//BrauboguGubodaDatin //AlnulAuDaEs //ABenulaufribiDanulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubuNulaubobobinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabiGudabubobubebetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlFriGuFribibububunus" abstract="true" eSuperTypes="//DagugudabeGusNulAuFriLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubobebefribibiBegugusgusbies" ordered="false" upperBound="-1" eType="//DaFriFriBubebubonulauDaLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiDagusbuGuNulaubigucus">
    <eLiterals name="AuBoBogusbelus"/>
    <eLiterals name="EBenulaubofrigulius"/>
    <eLiterals name="FagusGuguBebelus"/>
    <eLiterals name="EgusbinulaugubiGusAuCus"/>
    <eLiterals name="FabiGunulAunulaubibedanus"/>
    <eLiterals name="EfrigunulauBoGusbegubofrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabifribobibiBunulAuBubeBucio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Dibufrifridagusgudabubenules">
    <eLiterals name="BraugunulauGusfriguGusgugusdaBibetin"/>
    <eLiterals name="BiGubiGubebuNulauGudabeNules"/>
    <eLiterals name="AnfribobeBubebefritus"/>
    <eLiterals name="EudagusAudacio"/>
    <eLiterals name="DiBiGufriNulaubufriBefriBifribodaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafridanulAuBobobuBugubiboLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albubibeGuguGuNulEs" eType="//Anulaudadadabogusbilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusaugusDaBoBiGusbecus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBobigusbotus" upperBound="-1" eType="//EgusbububuGuBogusIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiGuBidacio" instanceTypeName="typeAlDagugugusauNulauBiTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABuBuBigusFrinulaufribogubeCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AdaboGufridabiLus" instanceTypeName="typeFanulaunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofriGusbenulaubebebeBeGusAulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafridadaNulauBubiboGuboes" eType="//FaBeLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibibunulAufrifribunulaudabibitin" eType="//DabeBogubicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBefriTin" instanceTypeName="typeAnauguboBuBenulaububilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibubigubugubiFrigusbofriNulaugusfrifritin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BibedafrinulauDafrigugusbocus">
    <eLiterals name="BraubuguBolus"/>
    <eLiterals name="EuBefrigugubuNulauGuGusAuFriTus"/>
    <eLiterals name="BebuBoDaguBitor"/>
    <eLiterals name="AldabonulaububuDacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBefriBedadadabidadaBudalius" abstract="true"/>
</ecore:EPackage>
