<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dalus" nsURI="http://hub.de/rcore/examples/dalus" nsPrefix="WOrE">
  <eClassifiers xsi:type="ecore:EClass" name="EboDabibegusdafriguGuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobebogustor" eSuperTypes="//EboDabibegusdafriguGuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGubobonulaubeBifriFriFrifriTin" ordered="false" upperBound="-1" eType="//BibuBobuNulauBigusnus" eOpposite="//BibuBobuNulauBigusnus/agusGudabegusNulaubeguGulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BadaBofriFribinus" instanceTypeName="typeAlGusGusguBibibeNulaubogustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibuBobuNulauBigusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusGudabegusNulaubeguGulus" ordered="false" eType="//Dobebogustor" eOpposite="//Dobebogustor/alGubobonulaubeBifriFriFrifriTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusnulaubedagusaubiDafritus" ordered="false" upperBound="-1" eType="//Dobebogustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AgubodaguGusTor" instanceTypeName="typeEbibeFriboGusbubugusbebibiDaguguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusgusbunulAubiguGugunulIus" eSuperTypes="//Dobebogustor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibegusbiGusfridaFribubutin" eType="//BadaBofriFribinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FadaGusbiLius" instanceTypeName="typeDoDaNulAuDabeBobuBobuBulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbonulAugusLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfrigusnulaunulaunulius" ordered="false" upperBound="-1" eType="//Dobebogustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGusbogubugusLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAuFribuBenus" eSuperTypes="//BibuBobuNulauBigusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGuboBubebuGufrinus" ordered="false" upperBound="-1" eType="//Dobebogustor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBuGubigufriguNus" eType="//EboDabibegusdafriguGuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoboGusDagunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auGusbefriDaGuDacio" eType="//AgubodaguGusTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albeGusgusguguses" ordered="false" eType="//AlbonulAugusLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Begusgubidabetor"/>
</ecore:EPackage>
