<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aunulaugusbees" nsURI="http://hub.de/rcore/examples/aunulaugusbees" nsPrefix="BW">
  <eClassifiers xsi:type="ecore:EDataType" name="Dafribebonulaubegusgucio" instanceTypeName="typeEGusnulAudaDabogusGugusBiboCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBigubibefridanules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badaBigufriGubuNus" eType="//Dafribebonulaubegusgucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbugusGusnulAudadagusnulaulius" eSuperTypes="//DoBigubibefridanules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DibibubeBeFrigusnulaububufridaGuEs" instanceTypeName="typeBifrinulaubuBeGusgusGunulauBoFritus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuDafrinulauBuBiBuBufriboFridacio" instanceTypeName="typeBiBububeFrigusgubinulaubebebidanus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AguBubedadadabeGusBigustus">
    <eLiterals name="BabeguGugubigusdagusFriFribunus"/>
    <eLiterals name="DudaNulAubeFribitin"/>
    <eLiterals name="DabuBibitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusBoNulaufriBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugusFridaboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBoBubigusBogusbubobecus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DufriGusdafrigusnulaugubegusFriCus">
    <eLiterals name="DaBonulaugugugugusnulauBebuGulus"/>
    <eLiterals name="BabodabefriGugugusgunulAubiFriBuNus"/>
    <eLiterals name="BedagusBofriGusTin"/>
    <eLiterals name="BrauBuBegusBegusBofriGustor"/>
    <eLiterals name="BraubogusDabutor"/>
    <eLiterals name="DobobugusauBoBiDaGusauDaBotus"/>
    <eLiterals name="BrAudaBibuGugusguEs"/>
    <eLiterals name="BefridagusaububibofriBedabenulAuCio"/>
    <eLiterals name="BaGusguFriBebobobegubibuboGusbiBobutus"/>
    <eLiterals name="Afridaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuDabefriBoGusgusbugugusdabotus" eSuperTypes="//AnbugusGusnulAudadagusnulaulius //BigusBoNulaufriBetor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AfrinulauNulaunulaufribidaguTus" instanceTypeName="typeAlAuboBeGugusBiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibibobiguGuFriboDabobenus" eSuperTypes="//BigusBoNulaufriBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfribobiBoBuboBoNulius" eSuperTypes="//BibibobiguGuFriboDabobenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBugusgunulaubotus" ordered="false" eType="//BrAugusFridaboes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baboDaGusbenulAubotus" ordered="false" upperBound="-1" eType="//AnbugusGusnulAudadagusnulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABuFrifridaDanulAubuBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaNulauDaDaGusguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbenulAutin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babigusgusbugustus" eSuperTypes="//BibibobiguGuFriboDabobenus //ABuFrifridaDanulAubuBinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alauFribibebugusgusaubedaLius" ordered="false" eType="//EbenulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnAugusbobibenus" instanceTypeName="typeDaBoBeboNulaugubegudagusgubeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBodafriboBoBugulus" eSuperTypes="//AnbugusGusnulAudadagusnulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabodaGuGudabuGusguGubibubebeCus" ordered="false" eType="//AfribobiBoBuboBoNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbebofribebogusLus" abstract="true" eSuperTypes="//DuBodafriboBoBugulus //BigusBoNulaufriBetor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anDaBebiGusgusgutor" eType="//AnAugusbobibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Ebufribunulaugudabecus" instanceTypeName="typeDaguNulAugusgusAuBufrigusguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AguFribedaBebuNules" eSuperTypes="//AudaNulauDaDaGusguslius //DuBodafriboBoBugulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBofribuGusgubibuGusbugusBeLus" eType="//AnAugusbobibenus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
