<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albugustus" nsURI="http://hub.de/rcore/examples/albugustus" nsPrefix="f">
  <eClassifiers xsi:type="ecore:EClass" name="BibonulaubonulaubeCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuNus" eSuperTypes="//BibonulaubonulaubeCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiBiGusbeFrigusBiBufries" ordered="false" eType="//BibonulaubonulaubeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobibegusgusbeGunulaufriDaLus" eSuperTypes="//BibonulaubonulaubeCio //AuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusgusAuLius" upperBound="-1" eType="//AuNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGusfribugudabebiDaGues" ordered="false" eType="//BibonulaubonulaubeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBegunulAubigugububiBubucio" abstract="true" eSuperTypes="//BibonulaubonulaubeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabubuBiGusgusBiDanulaugufriTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusDadabubebefriBibibubitus" ordered="false" upperBound="-1" eType="//DobibegusgusbeGunulaufriDaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dadafribebobutus" abstract="true" eSuperTypes="//DobibegusgusbeGunulaufriDaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubuBegugunulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufriBibubibotor" ordered="false" upperBound="-1" eType="//DobibegusgusbeGunulaufriDaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aubububobegububilius" abstract="true" eSuperTypes="//AuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeDabenulaugusauTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGuGusBubegusgugunus" ordered="false" upperBound="-1" eType="//DobibegusgusbeGunulaufriDaLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beboguBubuBuBubeFribugusnus" ordered="false" eType="//BeBegunulAubigugububiBubucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubeDaGubobiGusbibodaNulaububudatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBudabibufribeguGusfributor" ordered="false" upperBound="-1" eType="//BeDabenulaugusauTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebufriBobigugufrinus" instanceTypeName="typeBaFrigububuBegusnulaubotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbiFriBubiboFribetin" instanceTypeName="typeEBuDaBuDagusaugusguBufribeGusBibiFriboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGusnulaubefrigugusnulaufribobuLus" abstract="true" eSuperTypes="//Aubububobegububilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafribenulauguBuBuGuBufribetus" abstract="true" eSuperTypes="//AuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguBubufribeguTus" upperBound="-1" eType="//Dadafribebobutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusBoNulaudadaLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBoGunulaubogusbifriGusaudaBedaBuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaBiNulauGusbubefrinulAuFrilus" upperBound="-1" eType="//AuNus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aufribifribifribinulaucus" eType="//BebufriBobigugufrinus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
