<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="angusbigusautus" nsURI="http://hub.de/rcore/examples/angusbigusautus" nsPrefix="nXT">
  <eClassifiers xsi:type="ecore:EDataType" name="Eugunulaubogusfrinus" instanceTypeName="typeEbiDagusFriBebufrigusgusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusAudagusfridagusboguboboBebiBeBubigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbeFriDaNulaunulAugustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabuGusbeBubuGuFribigufriCio" eType="//AugusAudagusfridagusboguboboBebiBeBubigulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraudaBinulaubiLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulaudabuBugulus" ordered="false" upperBound="-1" eType="//EbeFriDaNulaunulAugustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadaboGuNulAubobiBodator" eSuperTypes="//BraudaBinulaubiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbenulauDaBogufrifridaTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euBenulAunulauGusBoguBubeBelius" eType="//Eugunulaubogusfrinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Agubifrigubebenulius" instanceTypeName="typeBefrifriBidaFribogusGustor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaDabuGustin" instanceTypeName="typeBrauBigugusGunulaufrigubegusGunulauBedator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefriGubogusnulauBelius" abstract="true" eSuperTypes="//BadaboGuNulAubobiBodator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fafrigusbeboBoGubegusTor" eType="//DaDabuGustin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auDabobeBufrigubeBiboBies" eType="//Eugunulaubogusfrinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFriBubebudabilus" eSuperTypes="//BraudaBinulaubiLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duboNulauTus" ordered="false" upperBound="-1" eType="//AugusAudagusfridagusboguboboBebiBeBubigulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusnulauBibigutus" ordered="false" upperBound="-1" eType="//BigunulaudaboBeGuslius" eOpposite="//BigunulaudaboBeGuslius/badaGusGusAugusfrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigunulaudaboBeGuslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badaGusGusAugusfrinus" ordered="false" upperBound="-1" eType="//BiFriBubebudabilus" eOpposite="//BiFriBubebudabilus/begusnulauBibigutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabebibiGusgustor" instanceTypeName="typeAudafribilus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaBiGusgubinulaubulius">
    <eLiterals name="DoGusAunulaubufrifriBugusboGulus"/>
    <eLiterals name="BraudafriNulius"/>
    <eLiterals name="AldafriDabeFribiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBudaFribinulaugusFribeButin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AububinulaubinulauTor" eSuperTypes="//AlbenulauDaBogufrifridaTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annulauDabuDaFridaboboes" eType="//DaDabuGustin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabebeFribeBiFriLus" ordered="false" upperBound="-1" eType="//BiFriBubebudabilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobufrigusBiFrifribiBubedaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begunulAubugusnulAutor" ordered="false" eType="//BraudaBinulaubiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbuBidabiDaboGuscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anaubofritus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabibinulauboBofrilus" abstract="true" eSuperTypes="//BigunulaudaboBeGuslius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagubuguBeFries" instanceTypeName="typeAnfriguNulAufrigubiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusdabiFrigubetus" eSuperTypes="//AlbenulauDaBogufrifridaTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABuBiNus" eSuperTypes="//BigunulaudaboBeGuslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagubuBoBugusboBoBuNulautin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babubudabubegusbigulius" eSuperTypes="//AbuBidabiDaboGuscus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugufrifriBebebebuBiLius" eType="//FagubuguBeFries" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbobefriboBibeguscus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaNulaunulaubuGusGusautin" ordered="false" eType="//BeBudaFribinulaugusFribeButin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbiboBonulAuGusfrinulaugucus" eSuperTypes="//BadaboGuNulAubobiBodator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbebefridanulauLius" eSuperTypes="//DigusdabiFrigubetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duNulaubiGubegustin" ordered="false" upperBound="-1" eType="//AugusAudagusfridagusboguboboBebiBeBubigulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAuDabuGusguBeCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FabogubebuBudaGuBuBefridagulus">
    <eLiterals name="EnulaufriGusaugunules"/>
    <eLiterals name="AnBuGuFriGutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndaguGuboboboBunulaubuGugubulius" eSuperTypes="//BadaboGuNulAubobiBodator //AugusAudagusfridagusboguboboBebiBeBubigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braudafridanulaufribolus" eSuperTypes="//Anaubofritus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugusBinulaugubuBinules" instanceTypeName="typeFabuNulauFriFrigubiBonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubeBufrifriFriBunulIus" eSuperTypes="//AunulAuDabuGusguBeCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baBotor" eType="//FabogubebuBudaGuBuBefridagulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnboNulaufrigufribebodaFrinulauLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabudaguboboboNulAubugunus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubuBibibobuBoEs" ordered="false" upperBound="-1" eType="//AunulAuDabuGusguBeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBidagusbofridafrinulaufriEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duguNulaunus" eType="//DaDabuGustin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusnulauGuGunulAuDabonulaucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigubuBibiGugunulaufriLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBuNulaugusbiBiFricus" eSuperTypes="//AlbenulauDaBogufrifridaTin //EbeFriDaNulaunulAugustor //Braudafridanulaufribolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aDagubedaes" ordered="false" eType="//BabibinulauboBofrilus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albedafriBetor" upperBound="-1" eType="//Agubifrigubebenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeBugubebuBegudabugusnus" eSuperTypes="//DagubuBoBugusboBoBuNulautin //DobufrigusBiFrifribiBubedaTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBofricus" eType="//DabebibiGusgustor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGubonulaubobuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusAuBebubibuBibiFricio" ordered="false" upperBound="-1" eType="//BraudaBinulaubiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBuGuNulAunulAubucio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abidaGusbunulauguBudaBobibufricus" ordered="false" eType="//BiFriBubebudabilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaGusNulaudabedaDadafribiLus" upperBound="-1" eType="//DagubuBoBugusboBoBuNulautin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aGusbiBotin" eType="//BaBiGusgubinulaubulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbebogusauBiBebofriTus" eSuperTypes="//DigusdabiFrigubetus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiBefriGuBeguBogusdadaboBuNulAubenus">
    <eLiterals name="BraudaGudabenulius"/>
    <eLiterals name="AlaubuguBoBifriGusDagubiTor"/>
    <eLiterals name="BaBoBunulAugusnulAunulauBubebotin"/>
    <eLiterals name="Afrinules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBiBuguboBunulauboes" eSuperTypes="//BabibinulauboBofrilus //BiFriBubebudabilus //Babubudabubegusbigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaDagusbobiboBeGutin" eSuperTypes="//DiBiBuguboBunulauboes //AnboNulaufrigufribebodaFrinulauLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DigusbiGuBogusAudaDaGuBinulaucus" instanceTypeName="typeEuDaDaBuBodaGusbobiBiguguLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoboGudagugusaugusaubinus" eSuperTypes="//DagubuBoBugusboBoBuNulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBobunulauFrifrigufriBebefricus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eugusbobogulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaNulauguGuBoTin" upperBound="-1" eType="//AugusAudagusfridagusboguboboBebiBeBubigulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbefrigusguBibunulaubudaBinules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBuNulaugusbubebidaCus" instanceTypeName="typeDiNulaugulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusfriGusBobiLus" instanceTypeName="typeBedagunulaugusnulaunulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngugubeBebiBuFrinus"/>
</ecore:EPackage>
