<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="babinus" nsURI="http://hub.de/rcore/examples/babinus" nsPrefix="igZ">
  <eClassifiers xsi:type="ecore:EDataType" name="Angusfrinulaubegutin" instanceTypeName="typeEuDagubigubeFrinulAufribilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedabiGubebodafridacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusBiFridabiguBibegubiboes" eSuperTypes="//BedabiGubebodafridacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobobogusaubebiCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diNulAubigusnulauLus" ordered="false" eType="//BidaNulaunulAubiBuTus" eOpposite="//BidaNulaunulAubiBuTus/binulauBugusbububitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAubigububuGubuGubolius" eSuperTypes="//AlgusBiFridabiguBibegubiboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaunulaunulAugusbibeguscio" eSuperTypes="//AnAubigububuGubuGubolius //DobobogusaubebiCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebibiBuBobuDaBifridaBotor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaubebifrinulaudator" ordered="false" upperBound="-1" eType="//DoBudafrifrinulaudabuboguFribeTus" eOpposite="//DoBudafrifrinulaudabuboguFribeTus/diguGunulaubegubinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubuBobibiEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulAunulaunulAubunulius" ordered="false" eType="//BedabiGubebodafridacio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbenulauCio" eType="//Angusfrinulaubegutin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulaufribidabenulAufriBelius" ordered="false" eType="//DodaBiGubodadanulaugubegudaboes" eOpposite="//DodaBiGubodadanulaugubegudaboes/dofrigusbebobeBenulaudadabocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidaNulaunulAubiBuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulauBugusbububitin" ordered="false" eType="//DobobogusaubebiCio" eOpposite="//DobobogusaubebiCio/diNulAubigusnulauLus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audaNulaunulaubiFribotor" eType="//Angusfrinulaubegutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaNulaubefriguguCio" instanceTypeName="typeBagufrigusNulAuguBoGuNulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufrinulaubobeBobiGulus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaboBugusAubogusBinulAuBoFrigusBeguTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulAubugudadaBubibodaTus" ordered="false" eType="//AlgusBiFridabiguBibegubiboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBogusDaBuDaguGusbues" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafridafriGufribudaBuboGusboes" eSuperTypes="//AlgusBiFridabiguBibegubiboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbibenulaubobubeBefribugusNus" ordered="false" eType="//AnAubigububuGubuGubolius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anAuGubodacio" eType="//BaNulaubefriguguCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudafriguDaboboBicus" eSuperTypes="//DubuBobibiEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubogusNulAufricus" instanceTypeName="typeDodabiBebudabunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibebinulaudaDanulEs" eSuperTypes="//BedabiGubebodafridacio //AufrinulaubobeBobiGulus //AnAubigububuGubuGubolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabefriBigubobiCus" ordered="false" upperBound="-1" eType="//EufriGusBogufridabegubucus" eOpposite="//EufriGusBogufridabegubucus/duBeNulAuDaBibunulauFrifritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EuBufriDanulauguBoNulauBeNus">
    <eLiterals name="EubiGudaguDabubiLus"/>
    <eLiterals name="DogufriBogutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobobogusbobinulaubiLius" eSuperTypes="//FafridafriGufribudaBuboGusboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulauBobinulAudadagusFrigutus" eSuperTypes="//FaboBugusAubogusBinulAuBoFrigusBeguTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albuboBuBuBuboguBebigubulus" upperBound="-1" eType="//EubogusNulAufricus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AbunulauGusgusAuNulaunules" instanceTypeName="typeAdaBiBonulaunulauGucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AFridaBugusAuBuBoGuTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebobudabubibubegusfriBiBedaTin" eType="//Angusfrinulaubegutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusfrigusbinulAuFriBiGubebigunulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriDaBebiboGutor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daFrifrifrifrifrifribiguDadaDalius" eType="//AbunulauGusgusAuNulaunules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubutor" eType="//BaNulaubefriguguCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboFrinulAuGusnulaubeDabunus" eSuperTypes="//FaboBugusAubogusBinulAuBoFrigusBeguTin //AlgusBiFridabiguBibegubiboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulaunulAuTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubuBoFrigubibebubiNulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeBoFrinulAunulAubobinus" eSuperTypes="//DobobogusaubebiCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaBiGubodadanulaugubegudaboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofrigusbebobeBenulaudadabocus" upperBound="-1" eType="//DubuBobibiEs" eOpposite="//DubuBobibiEs/annulaufribidabenulAufriBelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAuBebegugusDabucio">
    <eLiterals name="DadabeTor"/>
    <eLiterals name="EgudaFribubicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBobuguboguNulaucio" eSuperTypes="//FanulauBobinulAudadagusFrigutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="E" instanceTypeName="typeAlGunulAububogusbebiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulAubuBoBuBulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alGufriGusdaFridanulauguslus" eType="//E" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubeGusFrigusgudaBibitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedaguboFribonules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBifriBebeFrigusbuFridagutor" eType="//BaNulaubefriguguCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulauGufrinulAuBocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriGusBogufridabegubucus" eSuperTypes="//AngusfrigusbinulAuFriBiGubebigunulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBeNulAuDaBibunulauFrifritin" ordered="false" upperBound="-1" eType="//BibebinulaudaDanulEs" eOpposite="//BibebinulaudaDanulEs/dabefriBigubobiCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abibibunulaubudaTus" upperBound="-1" eType="//DuFriDaBebiboGutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauGuDafridacus" instanceTypeName="typeFaBuBebibocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBoBunulAuFribiBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusbogucus" ordered="false" eType="//DiboFrinulAuGusnulaubeDabunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusfriBinulaubunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alTor" eType="//E" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBubidagusaubebifridalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuDaNulaucus" abstract="true" eSuperTypes="//FafridafriGufribudaBuboGusboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albuBubeBees" eType="//EubogusNulAufricus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGububobigusguBuBeTor" abstract="true" eSuperTypes="//AubeGusFrigusgudaBibitus //FanulauBobinulAudadagusFrigutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaFribuDagusgusbuBonulAunus" abstract="true" eSuperTypes="//BedabiGubebodafridacio //FaGububobigusguBuBeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubebiboFribeBobibibicus" eSuperTypes="//BrauBoBunulAuFribiBulius //DiboFrinulAuGusnulaubeDabunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobodaFriFribugulus" eType="//Angusfrinulaubegutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBugusauguGufribiGusfrigunulaubebobogusGuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubuGuBifriGunulAunus" upperBound="-1" eType="//DaFribuDagusgusbuBonulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbuGubebeBebuGubeBetus" eSuperTypes="//AubeGusFrigusgudaBibitus //FafridafriGufribudaBuboGusboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusBigunulaubigubufriNulaubeLius" eType="//FafridafriGufribudaBuboGusboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlDaNulAugusaubogusgustus" eSuperTypes="//FaGububobigusguBuBeTor //DobobogusbobinulaubiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babobibiBuFriNulaucus" eType="//FaGububobigusguBuBeTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBiGubofrifribuGububobonus" eSuperTypes="//DiboFrinulAuGusnulaubeDabunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabibinulauboGuDafritus" eSuperTypes="//FafridafriGufribudaBuboGusboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuboFriBogusdafrifribibeDaboEs" abstract="true" eSuperTypes="//BebibiBuBobuDaBifridaBotor //BebeBoFrinulAunulAubobinus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Bidabufrifribogusgustin">
    <eLiterals name="DuGusNulAudanulaugusboBidabigulus"/>
    <eLiterals name="EubiNulaubeNulaudabebuFribibotor"/>
    <eLiterals name="Begusdabugubugusbebobubilius"/>
    <eLiterals name="Babigusaubudalius"/>
    <eLiterals name="FabuBoboboBuNulauBoguCus"/>
    <eLiterals name="EuBedadabonulauBiboes"/>
    <eLiterals name="AnbenulauboFrigubenulauTor"/>
    <eLiterals name="BifriboBoGusfrifriguguGubeTin"/>
    <eLiterals name="EunulAudabobeNulauTus"/>
    <eLiterals name="EunulAudabiFribeboGugusGusCus"/>
    <eLiterals name="DobugunulauCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FagusgudanulEs" instanceTypeName="typeEuDaGusbububuFricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaubetin" eSuperTypes="//FaNulaunulaunulAugusbibeguscio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BidadagusBeBegusdabofriTus">
    <eLiterals name="AlbebenulauGudabubeTus"/>
    <eLiterals name="EgugubobebibibeFricus"/>
    <eLiterals name="EubigusgubobubeGusfribeFribedadatin"/>
    <eLiterals name="FabobuBobeguBitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabiBoGuLius" eSuperTypes="//BrauBubidagusaubebifridalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulaugubonulAulius" ordered="false" eType="//BebeBoFrinulAunulAubobinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabebodaBeBuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabeBibubeBobuGusGubotus" eType="//AbunulauGusgusAuNulaunules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braufribeGusBebubinulIus" ordered="false" upperBound="-1" eType="//AunulaubegunulAunulaubonules" eOpposite="//AunulaubegunulAunulaubonules/ebidagusGusbubonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibibobebubobebuNus" abstract="true" eSuperTypes="//FafridafriGufribudaBuboGusboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGuboBubedagusdaNulAugubecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaubiDaguBofribeboBobiBiguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabeDabufridaBoGusnus" upperBound="-1" eType="//AnaubebiboFribeBobibibicus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugubicus" upperBound="-1" eType="//E" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBegusdaGubiGudanulaunulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdaBobunulauFriboEs" eSuperTypes="//AngusfrigusbinulAuFriBiGubebigunulautus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BabedabifriFriTor">
    <eLiterals name="AubudagusgusbuBinulaugusnus"/>
    <eLiterals name="DibebeGusBobunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusBibuGubibecus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BegusbebobiBenulaudadaes" instanceTypeName="typeFagusFriBulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulAubuBodabibubedabiCus" eSuperTypes="//DodaBiGubodadanulaugubegudaboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibedaTus" eType="//BrAuBebegugusDabucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdadabiBiGuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbufribubefriboNulaufriBugusBuBinus" eSuperTypes="//AlgusfriBinulaubunus //BiNulAubuBodabibubedabiCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abidaBogugufricus" ordered="false" eType="//EuNulaunulAuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnulAunulaunulaubibenulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgububuBoBugubunulaufriNus" abstract="true" eSuperTypes="//BrauBoBunulAuFribiBulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfriDaDafrinulaudafridadatin" abstract="true" eSuperTypes="//EbuGubebeBebuGubeBetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBifribedaGutor" ordered="false" eType="//DoBogusDaBuDaguGusbues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusdanulauGucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eufribuBubiNulaugusDabolus" eType="//EuBufriDanulauguBoNulauBeNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubibiguBibigusgusFrifribedalius" instanceTypeName="typeDaGusgusbogusNulaunulauNulauCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusboNulaubegusAubobicio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusGusBebiGusnulaugustus" eType="//Angusfrinulaubegutin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulAubuBubibubogusnus" ordered="false" upperBound="-1" eType="//FafridafriGufribudaBuboGusboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibunulaugusbibugudaBiTin" eSuperTypes="//BebeBoFrinulAunulAubobinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braudaGusgustor" eType="//BrAuBebegugusDabucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agusbubebibibebidanus" eType="//Bidabufrifribogusgustin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBoboBibofridanulauDaCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibiguBiBinulAubifritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigubugusaudabinulAubinus" eType="//AnulAunulaunulaubibenulautor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFridaGusnulAuBocus" ordered="false" eType="//AufrinulaubobeBobiGulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaubegunulAunulaubonules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubifrinulaufrigufrinulaubefriGuGusTin" eType="//EubogusNulAufricus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebidagusGusbubonus" upperBound="-1" eType="//DabebodaBeBuCio" eOpposite="//DabebodaBeBuCio/braufribeGusBebubinulIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauNulaufridabibunulaunules" eType="//DabiBoGuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBebuNulaudaTor" eSuperTypes="//DiboFrinulAuGusnulaubeDabunus //EufriGusBogufridabegubucus //DuFriDaBebiboGutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudabinulauNulaubobuNus" eType="//DoBogusDaBuDaguGusbues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagusnulaugusnulauguscus" eType="//BrauGuDafridacus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diDagusDatus" eType="//Angusfrinulaubegutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbibubobugusDabuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGusbudafriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriBobuboguNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befrifriBiFribubenulauBuNulaubocio" ordered="false" eType="//EuNulaunulAuTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agusfrifribebubegusbeGuLius" eType="//Angusfrinulaubegutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBudafrifrinulaudabuboguFribeTus" eSuperTypes="//AubeGusFrigusgudaBibitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diguGunulaubegubinus" ordered="false" upperBound="-1" eType="//BebibiBuBobuDaBifridaBotor" eOpposite="//BebibiBuBobuDaBifridaBotor/dinulaubebifrinulaudator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibufriBuNulauBoDaTus" eType="//AbunulauGusgusAuNulaunules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulauFridaBonus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebibobiGusgusbubeBibilius" eType="//BrAuBebegugusDabucio" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
