<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="begugusgusbilius" nsURI="http://hub.de/rcore/examples/begugusgusbilius" nsPrefix="CT">
  <eClassifiers xsi:type="ecore:EClass" name="DogusDaguGuscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusauGuBudafrifrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulauBogusgubilus" ordered="false" upperBound="-1" eType="//FadaNulaunulaudabobenulAubutus" eOpposite="//FadaNulaunulaudabobenulAubutus/anbugusbedagusBulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauguboNulauGusgunulAubuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabefriGusboboDadabutin" ordered="false" eType="//DigusauGuBudafrifrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusboFriTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudanulaugubidaBodagusBibolius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabeguGutin" instanceTypeName="typeDabeFriNulaudaguBiguDaGunus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Banulaulius">
    <eLiterals name="DoguBodabebobibudabenulauCio"/>
    <eLiterals name="BiBeDaGusgusfrinulAuBedabeboGusEs"/>
    <eLiterals name="AlfrinulaubenulauBuBiNulauLius"/>
    <eLiterals name="BrAubedabugulus"/>
    <eLiterals name="FanulauBegubegusgutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Dubunulaugusdacus">
    <eLiterals name="AuboBeBidabuBuFribibenulAudaBolius"/>
    <eLiterals name="BeBofriBeBodagusbecio"/>
    <eLiterals name="EgusdafriTor"/>
    <eLiterals name="DobodanulAubiGusGusdatin"/>
    <eLiterals name="EubedagubugusbuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bifrinulaugusaubies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGuBigusAubunulauCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agusbegusbolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGugubonulAuTus" ordered="false" eType="//Bifrinulaugusaubies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusdaNulaugulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiGusfribofribuGubuDaBonulius">
    <eLiterals name="BifribibigusBubiGusGusBotor"/>
    <eLiterals name="AlbifrigusgusBogusguFribeDaboguDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aldabibobetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufribugusgusgunus" eType="//BiGusfribofribuGubuDaBonulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoguBedabeTin" eSuperTypes="//DogusDaguGuscio //BiGuBigusAubunulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulaubifrigusbuboGusnulAulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufriDafriBebegusgusAuGusgulius" eType="//Banulaulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubibogubiBuBenulAubifriBiCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabubegusboboBues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBuBuGusAubogusDacio" ordered="false" upperBound="-1" eType="//DogusDaguGuscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AFrinulauBubibubudabuNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaugusDabuboGusnulaufridaguDacus" ordered="false" eType="//Bifrinulaugusaubies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaNulAuBeGusnulEs" eType="//DogusDaguGuscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AFriBigusBoBobobubeGuBuguguTin" eSuperTypes="//DoguBedabeTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albonulAubuGubeNus" ordered="false" eType="//AnaudaDabiboguguscio" eOpposite="//AnaudaDabiboguguscio/faFrifriGusgusfriBebiGusbigugusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbubefribeboFriguDanulaubelus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBufridabiBobidaes" instanceTypeName="typeDububunulauBifribeGusDaFriGusguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angubidafridaTor" ordered="false" upperBound="-1" eType="//BinulaufriBobonulauGulius" eOpposite="//BinulaufriBobonulauGulius/eufribibeBoBunulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusNulAubocio" eSuperTypes="//AubibogubiBuBenulAubifriBiCio //EudanulaugubidaBodagusBibolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBubodabogusNulius" eType="//BiGuBigusAubunulauCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BedabibuFriDabigubeGusbelus" instanceTypeName="typeBeFriBodagustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBudabenulaugusdanulaufrinulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AbeguNulauFrifrifribecio">
    <eLiterals name="DibiBifrifriguDadabidadabeGusNulIus"/>
    <eLiterals name="FafribeGugusFrigusbogutin"/>
    <eLiterals name="AgufriBenulAudanules"/>
    <eLiterals name="DoBiDagusnulAubeNulaubeguNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuguguBiboGuBebeguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBidabibobugubitus" eSuperTypes="//EunulauguboNulauGusgunulAubuLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubebiNulaudaFribubitus" instanceTypeName="typeAnnulAubonulauBiBegugufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAuguBibuNulaubufriNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbebuguFriguBubibogubobiboCio" eSuperTypes="//DigusauGuBudafrifrinus //DoguBedabeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufrigunulauDagusBigusbefritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubugusgugusfriBeBiLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaufribibonulauCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edabogusNules" eType="//BrAubebiNulaudaFribubitus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabuGubigusnulaubuFrigustor" eSuperTypes="//EuguguBiboGuBebeguCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudadabubebuBudaBebudaTin" upperBound="-1" eType="//AFriBigusBoBobobubeGuBuguguTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubobigusGugusBuDalus" ordered="false" eType="//AnBudabenulaugusdanulaufrinulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebodaNulauBeDaBuBies" ordered="false" upperBound="-1" eType="//AngusBidaboLius" eOpposite="//AngusBidaboLius/duDafrigububufriBefries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabebubidaboBedaBoBoFribelius" eSuperTypes="//AufrigunulauDagusBigusbefritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didaBufribibufriGubobuBuCus" ordered="false" eType="//BiGuBigusAubunulauCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBeFriBuDabefriguTin" ordered="false" eType="//EudanulaugubidaBodagusBibolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabiguBufribibibugusnulauBebubiCio" eSuperTypes="//AnBidabibobugubitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didagusdaguFribebiFriNulaucus" ordered="false" eType="//DigusauGuBudafrifrinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebobigusbeNulAubiDanulAuTin" ordered="false" eType="//BiGuBigusAubunulauCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebubefribeNulauBeBiGusNules" ordered="false" upperBound="-1" eType="//BiBufriGusdaboGubebobibenulaunulaubetor" eOpposite="//BiBufriGusdaboGubebobibenulaunulaubetor/aGubobifriboBuDalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfriBiBuGusbubebegunulAubebutus" eSuperTypes="//AnBidabibobugubitus //AufrigunulauDagusBigusbefritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofrinulaunulAugusboDalius" ordered="false" eType="//EunulauguboNulauGusgunulAubuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubifriFrigudaDabuNulius" eSuperTypes="//AbubefribeboFriguDanulaubelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobugufribububebufrigusgugubebigusdalius" eType="//AufrigunulauDagusBigusbefritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaboFrifrigubebobeboFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobonulaubogunulAuGusboGubogusbilus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DuFribububibeBuBebebubelius">
    <eLiterals name="Enulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebucio" abstract="true" eSuperTypes="//BabuGubigusnulaubuFrigustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Difribegusbogusdatin" abstract="true" eSuperTypes="//EbebuguFriguBubibogubobiboCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edagusNulauguslius" ordered="false" eType="//DinulauBigusBeBilius" eOpposite="//DinulauBigusBeBilius/auBeBogusAuGusDaGusgusTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusBidaboLius" eSuperTypes="//AFrinulauBubibubudabuNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibibifribinulAuBibeBocus" ordered="false" eType="//DobonulaubogunulAuGusboGubogusbilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duDafrigububufriBefries" eType="//BabuGubigusnulaubuFrigustor" eOpposite="//BabuGubigusnulaubuFrigustor/bebodaNulauBeDaBuBies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beDagusgusgugulus" ordered="false" eType="//EubugusgugusfriBeBiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuGuBiDaBedabotin">
    <eLiterals name="AugusBufribiFriBiGugusbogufriDafribulus"/>
    <eLiterals name="DubugusbuBugusbolius"/>
    <eLiterals name="DugusBoBogugusbiGufrifriDatus"/>
    <eLiterals name="FagusAufribebubiGusaunus"/>
    <eLiterals name="AlbeDabiBebufriFribudaLius"/>
    <eLiterals name="AnfriBegunulauDacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BidafrinulaubidabiLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaufriBobonulauGulius" abstract="true" eSuperTypes="//AnBidabibobugubitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufribibeBoBunulIus" ordered="false" upperBound="-1" eType="//Aulus" eOpposite="//Aulus/angubidafridaTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBegudaguBuBenulAubedabiTor" eType="//AbubefribeboFriguDanulaubelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBuBoDaGusfrifribulius" eSuperTypes="//Bifrinulaugusaubies"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaGusBiFrinulaudagustor">
    <eLiterals name="BaBiDaGusbucus"/>
    <eLiterals name="Autor"/>
    <eLiterals name="DaFriGusbubuBebodaguslus"/>
    <eLiterals name="AnbobidaGucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAuboFriguGuFrigusnulAugues" instanceTypeName="typeBegufriGuGusbedabitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubeBoFrifribeFrigusdaBeFrigudaLius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBifriGusdaBifriBeBofrilus" ordered="false" eType="//EunulaufribibonulauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaNulAububonulautin" instanceTypeName="typeAuBefribinulaugugusnulaudaBiNulaubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulAuBinulaubiBenus" abstract="true" eSuperTypes="//Difribegusbogusdatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubiBidabubobigusgusAuLus" ordered="false" eType="//AFriBigusBoBobobubeGuBuguguTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusdaGuNulaububugugucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAuGusbeGunulaugubicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egugusbufrifrinulaubufriguTin" ordered="false" upperBound="-1" eType="//AufrigunulauDagusBigusbefritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusbudabidabeEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBoGusNulauNulaucio" eType="//EunulAuBinulaubiBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbiGusauFribobebegusGusaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBubibugusBubedaLus" eSuperTypes="//Bifrinulaugusaubies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubifrigugugusGuBebutus" eType="//AuGuBiDaBedabotin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADaFriLus" abstract="true" eSuperTypes="//AfriBiBuGusbubebegunulAubebutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaudaDabiboguguscio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faFrifriGusgusfriBebiGusbigugusCus" ordered="false" eType="//AFriBigusBoBobobubeGuBuguguTin" eOpposite="//AFriBigusBoBobobubeGuBuguguTin/albonulAubuGubeNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Abubonulaubebetor" instanceTypeName="typeBagububibunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBedagufribidaguBubidagustor" abstract="true" eSuperTypes="//Aldabibobetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubibobobifriBeBedator" eSuperTypes="//AlBuBoDaGusfrifribulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauDadagusGustin" eType="//BidafrinulaubidabiLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulauDaFriNulautus" eType="//AuGuBiDaBedabotin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DadabeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabiGusbeBudagusFribibeDagubogusbubefriCio" eSuperTypes="//DoguBedabeTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusguslus" eType="//BrAubebiNulaudaFribubitus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbenulaubuGufrinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaBobobebofridadaBibibiBubonus" abstract="true" eSuperTypes="//DogusNulAubocio //Ebucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agunulauBobeBiTor" eType="//FaNulAububonulautin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAudagusbonulaufriCio" ordered="false" upperBound="-1" eType="//FabebubidaboBedaBoBoFribelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiFribuDaDafriDaDanulius" eSuperTypes="//EunulAuBinulaubiBenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibugubibiBodaBofribufrigusBecio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eu" upperBound="-1" eType="//Banulaulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabenulauNulauboBuGuguBitor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babedaFriGubotor" eType="//AuGuBiDaBedabotin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABibibibeFridabebilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeBebibubotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AFribeGusgusdaGutin" instanceTypeName="typeAboFriFriBiBunulauNulAuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubinulAudafribinulAuguslius" eSuperTypes="//FabiguBufribibibugusnulauBebubiCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebugubuBibebedaGusdaTor" eType="//AFribeGusgusdaGutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodaBigudanulautus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augugusBuNulaubiTus" upperBound="-1" eType="//EunulauguboNulauGusgunulAubuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebies" ordered="false" upperBound="-1" eType="//AbenulaubuGufrinules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBufriGusdaboGubebobibenulaunulaubetor" eSuperTypes="//AgusbudabidabeEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufrifridabebegubees" eType="//BidafrinulaubidabiLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGubobifriboBuDalius" eType="//FabiguBufribibibugusnulauBebubiCio" eOpposite="//FabiguBufribibibugusnulauBebubiCio/ebubefribeNulauBeBiGusNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBuDabefriDadagusDabufrigunus" eSuperTypes="//ABibibibeFridabebilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBufriBeguBoNulaubugusbunulAubitor" instanceTypeName="typeBedabibuBuBogusbefriBelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuDaGudanules" eSuperTypes="//Ebucio //DogusNulAubocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibeCio" eType="//AuGuBiDaBedabotin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibiBudabodafrifrinulaubibeLus" ordered="false" eType="//EunulauguboNulauGusgunulAubuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FadaGusBegusDanulauGusIus" instanceTypeName="typeBraugugubiDanulaubutin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DuBedaBebudanulaugusfrifricio">
    <eLiterals name="DoBugusguDagusauGusbuBiBunulIus"/>
    <eLiterals name="AubuGusGubufriFribudaBotin"/>
    <eLiterals name="DobogusbeBidabeBeboGuCus"/>
    <eLiterals name="BedaFrinulaugusbeNulAubobunulaunus"/>
    <eLiterals name="AlbuBeGufrinus"/>
    <eLiterals name="EdaGusbeGusfriBeGusGuDacus"/>
    <eLiterals name="DaDagubuBoes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuguGusguBugusbibetin" eSuperTypes="//ADaFriLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DigubobeBoBuDabibobuBuBubibubiButor" instanceTypeName="typeBeGugudagusnulauguboBies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAufriDafrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBiBubudaNulius" eSuperTypes="//DubifriFrigudaDabuNulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="befriFribobugudalus" eType="//AFribeGusgusdaGutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Egusbobefribobitin">
    <eLiterals name="FaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulauboNules" eSuperTypes="//FaBiBubudaNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibinulauBigusGubigusTin" ordered="false" eType="//DugusdaGuNulaububugugucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bi" ordered="false" eType="//BebeBebibubotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BegusguNulaubofribedabeguses">
    <eLiterals name="AbufrifridaLius"/>
    <eLiterals name="AunulauGubiBunulaucus"/>
    <eLiterals name="BibuGusguDagusguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusBinulAubobeFrigugustor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eufritin" eType="//BrAuboFriguGuFrigusnulAugues" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daDaBigusdaDacus" eType="//DigubobeBoBuDabibobuBuBubibubiButor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbifriDadabiguBibogubobufrigusgusFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriNulaububegusBicio" eSuperTypes="//EuguGusguBugusbibetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAugusGusbuFridaCus" ordered="false" upperBound="-1" eType="//AunulauboNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBebuLius" eSuperTypes="//AnBudabenulaugusdanulaufrinulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badaNulaubibobiFricus" eType="//BrAubebiNulaudaFribubitus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BiFriGusfriBebobiNus">
    <eLiterals name="BanulaunulaufriGustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobiBeBeNulaubogudabitor" eSuperTypes="//AgusbudabidabeEs //BabenulauNulauboBuGuguBitor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EbiboGugubebodaNulauDaBunules">
    <eLiterals name="DudadaGusDaBeDalus"/>
    <eLiterals name="FabifriGuboBobigunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonulAuBogubuBuBedaBobugunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulAunulauboFrinus" ordered="false" eType="//AufrigunulauDagusBigusbefritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubiBigusfribuBugubidafribeGunulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubuguBiboBobuNulauLius" ordered="false" eType="//EbebuguFriguBubibogubobiboCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusBifriBeGusguLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBoGuBibodanulautor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibidagusbonulAuDabelius" abstract="true" eSuperTypes="//AbubefribeboFriguDanulaubelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadaBinulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabebobinulauBubudafridabuBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFrinulAudabubegufriBobufritin" ordered="false" eType="//DoguBedabeTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubedaBonulAufribinulauLus" ordered="false" upperBound="-1" eType="//DiBuDabefriDadagusDabufrigunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadaNulaunulaudabobenulAubutus" abstract="true" eSuperTypes="//DugusdaGuNulaububugugucus //DuBubibugusBubedaLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbugusbedagusBulius" ordered="false" upperBound="-1" eType="//DigusauGuBudafrifrinus" eOpposite="//DigusauGuBudafrifrinus/braunulauBogusgubilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabeBeBobudanulaugubinulAulus" instanceTypeName="typeBrAuguGusBues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AguBoBoCio" eSuperTypes="//BrAufriDafrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBobofribeDadanulauguLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoFrifribegusBenulaubidabotor" instanceTypeName="typeDunulaububibuBenulAuNulaubuFriguFrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguBofriBobebigusgugusbetus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbifriBobugusbedacio" instanceTypeName="typeBeFriGububiButus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnnulAunulaubugusfrilus" instanceTypeName="typeAuGugusbefriGusbufribetor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BagubodaGunulIus" instanceTypeName="typeDoDaGusnulAuBiDafrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauBigusBeBilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBeBogusAuGusDaGusgusTor" ordered="false" upperBound="-1" eType="//Difribegusbogusdatin" eOpposite="//Difribegusbogusdatin/edagusNulauguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadanulauFrinulAubiLus" eSuperTypes="//EunulaufribibonulauCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagufrigusDaBudaBedabogusgunulaunus" instanceTypeName="typeBafriBoBiBifriguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigubeBeBeBuNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagugusauDalius" eType="//AFribeGusgusdaGutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBuBofrifrifridagutor"/>
</ecore:EPackage>
