<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aubibefrifrigustor" nsURI="http://hub.de/rcore/examples/aubibefrifrigustor" nsPrefix="c">
  <eClassifiers xsi:type="ecore:EClass" name="DonulAugusBofribetus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBifridabebibocus" ordered="false" upperBound="-1" eType="//Anulaudanulaunus" eOpposite="//Anulaudanulaunus/brAuGubobodaNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubunulaufribuguFrifriCio" instanceTypeName="typeDobigusfriBibetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGugubufribibunulaudaBelus" eSuperTypes="//DonulAugusBofribetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabiboguboboFriDaguguFribeEs" eType="//EubunulaufribuguFrifriCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulauBufribofriEs" ordered="false" upperBound="-1" eType="//DabudagusgusBoFridagusguslius" eOpposite="//DabudagusgusBoFridagusguslius/efribebigusbuFritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoguNulaubobufrigubibegusbofrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaufrigusbobubugutor" upperBound="-1" eType="//AlgusguboGusfriboDanulAunules" eOpposite="//AlgusguboGusfriboDanulAunules/bibuGusFribubogugusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebodagufriboDaBigudaes" instanceTypeName="typeDobobodagusbedabedaBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibubeGudagusbudaGusgunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBofribeDaGustus" eSuperTypes="//BibubeGudagusbudaGusgunus //DuGugubufribibunulaudaBelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDaGuBuBoguGufries" ordered="false" upperBound="-1" eType="//BibubeGudagusbudaGusgunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Angusnulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusguboGusfriboDanulAunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibuGusFribubogugusius" ordered="false" upperBound="-1" eType="//DoguNulaubobufrigubibegusbofrilius" eOpposite="//DoguNulaubobufrigubibegusbofrilius/binulaufrigusbobubugutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Babibedagusbenulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulaufribiguBulus" ordered="false" upperBound="-1" eType="//DonulAugusBofribetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AunulAubiDaBeBidabiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enulaudagusdadadafribilus" eSuperTypes="//BibubeGudagusbudaGusgunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EgugusNulauBoGubuguLius" instanceTypeName="typeFaNulAuBobunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabugusfriboBifriboBobinulaugudaes" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafriGudanulAuTus" eType="//BebodagufriboDaBigudaes" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFribenulaubenulauguNulEs" instanceTypeName="typeAlfrigusgusbunulaubuGuGusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadaBobeBigusgusbubeBiBicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anulaudanulaunus" eSuperTypes="//Enulaudagusdadadafribilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuGubobodaNulEs" eType="//DonulAugusBofribetus" eOpposite="//DonulAugusBofribetus/doBifridabebibocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBodadaBifrigusBetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFrifriGusaubegusbebibibebubogugusdaBoFritin" ordered="false" upperBound="-1" eType="//AlgusguboGusfriboDanulAunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabebeNulauBefricio" abstract="true" eSuperTypes="//Angusnulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didaBobiguBiguscus" ordered="false" upperBound="-1" eType="//DadabifrigudaLius" eOpposite="//DadabifrigudaLius/dofriDanulAuGusbiGuscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabuBiNulaunulauBibiDagulus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBiNulaunulaufrigunules" ordered="false" upperBound="-1" eType="//DuGugubufribibunulaudaBelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusBegubocio" eSuperTypes="//Anulaudanulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboBiBibutus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabuBudagusFridadanulAuFritus" eSuperTypes="//AnboBiBibutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudaguGusBubudaBubuBocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbinulAuguBeBuGuBelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digubonulauBoGusfries" ordered="false" upperBound="-1" eType="//DabebeNulauBefricio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubiGuDaguDafrigusIus" ordered="false" eType="//DuGugubufribibunulaudaBelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DadabifrigudaLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofriDanulAuGusbiGuscio" ordered="false" eType="//DabebeNulauBefricio" eOpposite="//DabebeNulauBefricio/didaBobiguBiguscus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="da" ordered="false" eType="//BabuBiNulaunulauBibiDagulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbobeBebigufriBeBofries" eSuperTypes="//DoguNulaubobufrigubibegusbofrilius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BadabubefriBies"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulauBobuboNulaubeFries" eSuperTypes="//AnboBiBibutus //Anulaudanulaunus //DonulAugusBofribetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bres" eType="//EubunulaufribuguFrifriCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AguBudafriTin" eSuperTypes="//DonulAugusBofribetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabudagusgusBoFridagusguslius" eSuperTypes="//FabugusfriboBifriboBobinulaugudaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efribebigusbuFritus" ordered="false" upperBound="-1" eType="//DuGugubufribibunulaudaBelus" eOpposite="//DuGugubufribibunulaudaBelus/binulauBufribofriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedafriDaFrifrigusbolius" eSuperTypes="//BrauBodadaBifrigusBetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBiDanulaugusBudadabees" upperBound="-1" eType="//EubunulaufribuguFrifriCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusgusbogusbibulus" ordered="false" eType="//FadaBobeBigusgusbubeBiBicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeFribibiGusgugusbebefrilius"/>
</ecore:EPackage>
