<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="befritor" nsURI="http://hub.de/rcore/examples/befritor" nsPrefix="pxOs">
  <eClassifiers xsi:type="ecore:EClass" name="Babufribobobigues" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGusFribiCus" ordered="false" eType="//AnFribogubiTin" eOpposite="//AnFribogubiTin/aubibigusauGusdanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaFrinulAuFriBubonulaubifridaBenulius" eSuperTypes="//Babufribobobigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfribuBubebiBedaguBogusbebiGuTus" eSuperTypes="//Babufribobobigues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diboGusaugusgusDaBidabugusnulAubolius" ordered="false" upperBound="-1" eType="//Babufribobobigues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albebugusaubuGusdabibubonus" ordered="false" upperBound="-1" eType="//Brautor" eOpposite="//Brautor/alboGusboFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FagudaNulAulus" instanceTypeName="typeEgubibogusBibibebogubutor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbeBobiNulAugusBibolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebegusEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aulus" eType="//FagudaNulAulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DobiBoFribeGusBeguBedaes" instanceTypeName="typeAubebuGusaufrifriCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabogusaubinulaugusGuscio" instanceTypeName="typeBaGuboNulaubeFriGusdatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabufribiBeboDaDabobinulautor" abstract="true" eSuperTypes="//EfribuBubebiBedaguBogusbebiGuTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="banulAuGusBobonulAuboGues" eType="//FagudaNulAulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubiGues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlboGusbinulaudaNulAuguboDaCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bibefribotin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbiguguBodaDaguNules" eSuperTypes="//EubiGues //AlboGusbinulaudaNulAuguboDaCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebidaBoBoBoBufrifricio" ordered="false" eType="//Babufribobobigues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabifrigusFritus" ordered="false" upperBound="-1" eType="//AlboGusbinulaudaNulAuguboDaCus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agugufriGubegunus" eType="//DobiBoFribeGusBeguBedaes" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulAunulaunulAuBoBocio" ordered="false" upperBound="-1" eType="//AlboGusbinulaudaNulAuguboDaCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulAubiDanulaubotus" upperBound="-1" eType="//DuGugugusBubobiBudabinus" eOpposite="//DuGugugusBubobiBudabinus/bebegusBeBobobidaBolus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulauGudaBeguBogudaGusbuDatus" ordered="false" eType="//EunulauFribefrigulius" eOpposite="//EunulauFribefrigulius/alguDabiNulAuGugusDaFritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubogusbegusgusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euFribobodadadaBeGusFriTin" ordered="false" upperBound="-1" eType="//EubiGues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abudaGubogusAugugusBelius" ordered="false" upperBound="-1" eType="//DaDaFrinulAuFriBubonulaubifridaBenulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbebobuFribogusbobolius" instanceTypeName="typeDabuDaDaBuBeFridaDafriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBeDabinulauNulauBinulauLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulauBibiGusDabuDaDafriLius" eType="//DoBubibibees" eOpposite="//DoBubibibees/biBenulaubobeBelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlauBogubodagufriLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duNulaububuDaCio" ordered="false" upperBound="-1" eType="//EfribuBubebiBedaguBogusbebiGuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BegusbibuguDabububegusfrifribiNulaubotus" instanceTypeName="typeEubuBinulauBibebiBobucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFribogubiTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubibigusauGusdanus" ordered="false" eType="//Babufribobobigues" eOpposite="//Babufribobobigues/duGusFribiCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabubidadabudadadaTus" ordered="false" eType="//DaDaFrinulAuFriBubonulaubifridaBenulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabebufrifribebobuFribees" ordered="false" upperBound="-1" eType="//BafriBedabidaes" eOpposite="//BafriBedabidaes/dabeBefribudanulaugunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBubibibees" eSuperTypes="//DaBeDabinulauNulauBinulauLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faDagugubebiGustin" eType="//Bibefribotin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afribubodabubotor" upperBound="-1" eType="//Bibefribotin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBenulaubobeBelius" ordered="false" upperBound="-1" eType="//DaBeDabinulauNulauBinulauLius" eOpposite="//DaBeDabinulauNulauBinulauLius/danulauBibiGusDabuDaDafriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGugugusBubobiBudabinus" eSuperTypes="//AlboGusbinulaudaNulAuguboDaCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebegusBeBobobidaBolus" ordered="false" eType="//AbiguguBodaDaguNules" eOpposite="//AbiguguBodaDaguNules/banulAubiDanulaubotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AbuDaboGufriCio" instanceTypeName="typeDaBiguDaFriBodadaFribebiFriEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbudabubogubedaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafriBedabidaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabeBefribudanulaugunus" ordered="false" eType="//AnFribogubiTin" eOpposite="//AnFribogubiTin/dabebufrifribebobuFribees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AboBeBodabubifritus" instanceTypeName="typeDaBobibubeguLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulaubonulauLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibubonulaufriGubobonulAudaNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABogusNulaubeGusboDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubiGuFriboLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DunulAugubibubefrinulauGubelus">
    <eLiterals name="DogusnulaufriboDaDagusButus"/>
    <eLiterals name="FagusBogunulauGufriGusBubuGusfriNus"/>
    <eLiterals name="EdabiguBoboGuBiEs"/>
    <eLiterals name="AuBigusauboFrinulAugusfriFribetin"/>
    <eLiterals name="ABugusboBeFriNulaubigusius"/>
    <eLiterals name="EFribudabiDafries"/>
    <eLiterals name="AbegusbebebeGubotin"/>
    <eLiterals name="AbenulAuboboguBeDagusfrigusbogusius"/>
    <eLiterals name="DibibugusbiNulaubuBinus"/>
    <eLiterals name="EuBeBedaBogusbibelius"/>
    <eLiterals name="BagufrigusfriBefribeGuscus"/>
    <eLiterals name="BrauboBebiGuFrigusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Angunulaulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anguNulaubiGunulAuguEs" eType="//DunulAugubibubefrinulauGubelus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Dubogusnulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FaBebegudaFribeguFribobidaboBiLius">
    <eLiterals name="EubinulaufriBoBelius"/>
    <eLiterals name="DubiBiBebinulaubobefribugusauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AguFriguNulAugusnulaubutor" abstract="true" eSuperTypes="//BebegusEs //ABogusNulaubeGusboDatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaunulaubuBebocio" ordered="false" eType="//BebibebeDaBibubuBebeBinulauBodaTin" eOpposite="//BebibebeDaBibubuBebeBinulauBodaTin/eGuGugusGunulauguBedadadagusbigucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifrigudaFriNulauFribiTor" eSuperTypes="//AbudabubogubedaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebibebeDaBibubuBebeBinulauBodaTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGuGugusGunulauguBedadadagusbigucus" ordered="false" eType="//AguFriguNulAugusnulaubutor" eOpposite="//AguFriguNulAugusnulaubutor/binulaunulaubuBebocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AbibobebigusAubobinulaugusfrilus">
    <eLiterals name="EuDadanulAudaBinulaugusNulAunus"/>
    <eLiterals name="BebobeBobetin"/>
    <eLiterals name="EBidabobibiDaTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBeGudaboguLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuNulauDabidafrinulAubucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusGusbibubunulAugusGulius" eSuperTypes="//DaDaFrinulAuFriBubonulaubifridaBenulius //BebegusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusguBeNulauBuguslius" abstract="true" eSuperTypes="//FabufribiBeboDaDabobinulautor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnBebebuBeNulaugusnulaunulaulius" instanceTypeName="typeEuBufriGubufrigusfritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bafrinulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubeGulus" ordered="false" upperBound="-1" eType="//Babufribobobigues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFribinulauBeBobubufributin" eSuperTypes="//BebibebeDaBibubuBebeBinulauBodaTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AufrinulauBugusdanulius" instanceTypeName="typeDafribedaGudabibitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoGusgugusAubodaDadafribebolius" instanceTypeName="typeBaGusaunulauGuscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusbogusfriNules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobonulauBufrinulaufrigugudagusBefriNus" ordered="false" upperBound="-1" eType="//DaNulaubonulauLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braufrinulaulus" ordered="false" upperBound="-1" eType="//DifrigudaFriNulauFribiTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigunulaugusnulauFriDacio" eSuperTypes="//AguFriguNulAugusnulaubutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaDabefribubebetor" instanceTypeName="typeAlBebigusfribibiDaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabiGudaNulAugusaubeFrinulAubobues"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauDabonulaugunules" eSuperTypes="//DaNulaubonulauLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabugusbuguGubifriLius" abstract="true" eSuperTypes="//AngusbogusfriNules //BebegusEs //ABogusNulaubeGusboDatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babenulAufriNulaubiNulaubutor" ordered="false" eType="//DoBubibibees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Brautor" abstract="true" eSuperTypes="//DaNulaubonulauLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alboGusboFricus" eType="//EfribuBubebiBedaguBogusbebiGuTus" eOpposite="//EfribuBubebiBedaguBogusbebiGuTus/albebugusaubuGusdabibubonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBibiNulauBebobubeFriBeTus" instanceTypeName="typeAuGusbeBodanulaubufribibofriFriCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAufrigudabibubebinus" eSuperTypes="//DubogusbegusgusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufrigubebogusnulAugusGuBunulAubenulautor" ordered="false" upperBound="-1" eType="//EfribuBubebiBedaguBogusbebiGuTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augusTus" upperBound="-1" eType="//AbuDaboGufriCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobiguGusboGuFriFriboFribubies" ordered="false" upperBound="-1" eType="//DunulaudaGufrigufriNulAuTus" eOpposite="//DunulaudaGufrigufriNulAuTus/brAubigues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EufribobebonulaubiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaDabees">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="andabeFributor" eType="//BegusbibuguDabububegusfrifribiNulaubotus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBeFrigufribinulauGubuFrinulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauFribefrigulius" eSuperTypes="//DubiGuFriboLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alguDabiNulAuGugusDaFritin" ordered="false" eType="//AbiguguBodaDaguNules" eOpposite="//AbiguguBodaDaguNules/benulauGudaBeguBogudaGusbuDatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Banulaubidabetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alboguBoFrifriboboBuTus" eType="//BaDabefribubebetor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beguNulaufribidaboFrinulius" eType="//FabufribiBeboDaDabobinulautor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauFriLus" eType="//Dubogusnulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuFriBufribiBeboNulauGusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlboFridaguGusEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eucus" eType="//DobiBoFribeGusBeguBedaes" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eufribebotus" eType="//DuBibiNulauBebobubeFriBeTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DobegugubugusbeboBetor" instanceTypeName="typeDofribibubogusbegusBibonulauguNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBibifriBubegusnulaulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAubufriGusgudaBudatin" eType="//AbuDaboGufriCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabofriFribebiNulAudacus" abstract="true" eSuperTypes="//BrAufrigudabibubebinus //DoBubibibees"/>
  <eClassifiers xsi:type="ecore:EClass" name="DunulaudaGufrigufriNulAuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albeGusbuFrinulaudalus" ordered="false" eType="//Bafrinulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubigues" ordered="false" upperBound="-1" eType="//BrAufrigudabibubebinus" eOpposite="//BrAufrigudabibubebinus/dobiguGusboGuFriFriboFribubies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuguGusfrinulauBeGusGunus" instanceTypeName="typeDibefriguBofriBebenulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAuGubinulaubebetor" abstract="true" eSuperTypes="//DubogusbegusgusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBubobuboGufridaFriTin" ordered="false" eType="//EunulauFribefrigulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibeGunulAudadabutor" eType="//FagudaNulAulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBeGusbifribibeTus" instanceTypeName="typeEudagusauBubiFrifribuBuFribelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriFrinulauGufriGunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidagubegubuGuBobilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagunulauNulaugubuBoNulaubutus" eSuperTypes="//AngusbogusfriNules //EubiGues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DidagubufriDaFribeFriNulautus" instanceTypeName="typeAlgubodaBibubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusnulauDaboDacio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dabigusbugustor" eSuperTypes="//Banulaubidabetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadaBeBoDabuguBitor" ordered="false" eType="//DunulaudaGufrigufriNulAuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaDabubobuBubetor" instanceTypeName="typeBabefribunulAuboFriGuBiboNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufrigubeguBibonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiFriFrinulAuBefrigusLus" eSuperTypes="//DunulAuGubinulaubebetor //AlboFridaguGusEs"/>
</ecore:EPackage>
