<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eubotus" nsURI="http://hub.de/rcore/examples/eubotus" nsPrefix="kdv">
  <eClassifiers xsi:type="ecore:EClass" name="BibobibobogusdaGusBobunulAuGusIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiFriNulaugusguguBefridaEs" instanceTypeName="typeAGunulaufrinus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FabibidaBibocio">
    <eLiterals name="Albibigugudadator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubenulAuGusdaBecus" abstract="true" eSuperTypes="//BibobibobogusdaGusBobunulAuGusIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anfrinus" upperBound="-1" eType="//FabibidaBibocio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaunulAubinulaugusFritus" eSuperTypes="//AnaubenulAuGusdaBecus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebububenulaugusnus" eType="//FabibidaBibocio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBoDabobenulauBogusgucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudagububiGusBegusnulAuBudanus" eSuperTypes="//FaBoDabobenulauBogusgucio //BibobibobogusdaGusBobunulAuGusIus //DiNulaunulAubinulaugusFritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dodafrinulaubutor" eSuperTypes="//DiNulaunulAubinulaugusFritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAugustin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diguGusguslus" eType="//FabibidaBibocio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofrinulauFribibiCus" ordered="false" eType="//FaBoDabobenulauBogusgucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoboBegusaubugugufrilius" eSuperTypes="//FanulAugustin"/>
</ecore:EPackage>
