<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dogugugufridabetor" nsURI="http://hub.de/rcore/examples/dogugugufridabetor" nsPrefix="mpT">
  <eClassifiers xsi:type="ecore:EClass" name="DaGubefridaDabubues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaboGusNulaugusauFriNulauboTus" upperBound="-1" eType="//Eubobebitin" eOpposite="//Eubobebitin/brauGusnulAuGusBuguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AbifriguLius" instanceTypeName="typeAngusBobedagugues"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulAunulaufriBoboboBeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFridaBeboBugubeEs" eSuperTypes="//DaGubefridaDabubues //ANulAunulaufriBoboboBeEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albodagunulAuNulaulius" eType="//AbifriguLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnfribiBibeNulAudanules" instanceTypeName="typeBrAubunulaubeDaBifrigusBubebicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eudadabebugustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beGusgubebudabebebunulius" ordered="false" upperBound="-1" eType="//ANulAunulaufriBoboboBeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlauBubefrifrifrigubobobibifrigues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiDabefrifriBegubuBegucus" instanceTypeName="typeFabuBebeGugusbobulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eubobebitin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGusnulAuGusBuguses" ordered="false" upperBound="-1" eType="//DaGubefridaDabubues" eOpposite="//DaGubefridaDabubues/dadaboGusNulaugusauFriNulauboTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBogudagusFrifries" abstract="true" eSuperTypes="//AlauBubefrifrifrigubobobibifrigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="Algusbibubodabugusbutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAubunulAubububiBobubeBolus" ordered="false" eType="//AlauBubefrifrifrigubobobibifrigues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobegusFridadabedagusauNulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaudadabebefriBeDaBuguscio" eSuperTypes="//DaGubefridaDabubues //Eudadabebugustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulaunulAuGufriGusnulauBigucio" ordered="false" upperBound="-1" eType="//AlauBubefrifrifrigubobobibifrigues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbubofribuBugubotor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egusbibuBegubuCus" eType="//AbifriguLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgubibegufriGugudabogusbeCus" eSuperTypes="//Eudadabebugustus //ANulAunulaufriBoboboBeEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adabeBofriboguNus" ordered="false" upperBound="-1" eType="//ANulAunulaufriBoboboBeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbebiBoNulAuGusAuBecus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begusBegusdagusnulaunulAunulius" eType="//AnfribiBibeNulAudanules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabinulauBiboGusLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badaNulAuBoCus" ordered="false" upperBound="-1" eType="//ANulAunulaufriBoboboBeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabiBodabeGusNulauTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="antor" eType="//BiDabefrifriBegubuBegucus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibogubodagubebubogusButin" ordered="false" upperBound="-1" eType="//AnulaudadabebefriBeDaBuguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBebuBoBebebiBecus" abstract="true" eSuperTypes="//DaBogudagusFrifries //AnulaudadabebefriBeDaBuguscio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aulius" eType="//AnfribiBibeNulAudanules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DifriFriGusfrigufrifribodaTus" instanceTypeName="typeDobeGusGusauBuBebelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafriguBoBigusbogufrigufriDafries"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaGuFrifriDabiDagusBebuboFritor" instanceTypeName="typeBeBifrinulaubufricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusguFribinulaubiGusnus" eSuperTypes="//DaGubefridaDabubues"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BanulAuBebeNulaunulaubebugulus">
    <eLiterals name="AlBubigusboNulAufriFriGulus"/>
    <eLiterals name="EubinulAufribeGunulAuDalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusbubebuGusdadabibifrifritus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibucio" eType="//AnfribiBibeNulAudanules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBuNulauNulaunulaulus" eType="//BiDabefrifriBegubuBegucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusdaBeBibofribodaNus" abstract="true" eSuperTypes="//AlgubibegufriGugudabogusbeCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auFrigusAunules" eType="//DifriFriGusfrigufrifribodaTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DadaguNulAubunules" eSuperTypes="//AlgubibegufriGugudabogusbeCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulauFriBiBiBobuBebiBinulius" ordered="false" upperBound="-1" eType="//FafriguBoBigusbogufrigufriDafries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusBinulaufriBefrigusgunulauTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBunulauDaDaBidaCus" instanceTypeName="typeDibuboBunulaufriDanules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BanulaubidagusbeBeDadafrifrifritus" instanceTypeName="typeAububiBuDaBeNulAubuguscio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BebuBububoBuGusFridatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBububidaBiNulEs" abstract="true" eSuperTypes="//FabiBodabeGusNulauTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobonulAugusAuBobocus" instanceTypeName="typeFafribiBiFridaGubebibodabuNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBodabenulaubiboGuBuboBeNulauCio" instanceTypeName="typeEbebuboBibebelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbubugunulAubugusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubebinulAugugubilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubuFriLus" eType="//BanulaubidagusbeBeDadafrifrifritus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBeBebofrigunulaucio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DoBenulauGubogutus">
    <eLiterals name="DanulAubuGusnulaubibeBidaBuBolius"/>
    <eLiterals name="DiboBifrifribuGusfriBuGusaugusFriFriboboCio"/>
    <eLiterals name="BigusgusdaDagusbudanulautor"/>
    <eLiterals name="AubiGusbibobonulius"/>
    <eLiterals name="FadaDagubiFriCus"/>
    <eLiterals name="BrAuBiFriDanulEs"/>
    <eLiterals name="AlbobidaNulaubofrifritin"/>
    <eLiterals name="DoboNulauBoBigusnulius"/>
    <eLiterals name="AlBobinulAuBuBebugubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndagusBibudaBuCus" abstract="true" eSuperTypes="//DaBububidaBiNulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eNulaububeBodanulaufritus" ordered="false" eType="//EbebiBoNulAuGusAuBecus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="andadabibegusgugusGunulaufrinus" ordered="false" eType="//EbebiBoNulAuGusAuBecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubigusbunulAuBetor" instanceTypeName="typeEuDagusbiBeguFribudadalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlguFriNulaubogusNulauGusCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babofriboGusfribinulauNulaugucio" eType="//AbifriguLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baboNulaubebeNulauFriBofriBiBocio" ordered="false" upperBound="-1" eType="//Eubobebitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusBuBeDanulaubeBedacus" eSuperTypes="//AlgubibegufriGugudabogusbeCus //AnbubugunulAubugusEs //FabinulauBiboGusLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudafribeNulauDabeNulauGusius" ordered="false" eType="//Eubobebitin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daboBonules" upperBound="-1" eType="//BrauBebuBoBebebiBecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubeGuNulaudanulAuGusguTor" eSuperTypes="//FabinulauBiboGusLus //AlauBubefrifrifrigubobobibifrigues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efrigusbogubuCio" eType="//BraubebinulAugugubilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabonulaugusboGuguBetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubibibuBoBoboBunules" ordered="false" eType="//FafriguBoBigusbogufrigufriDafries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubibigusdaBuBinulius" eType="//BraubigusbunulAuBetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraufriBeBigusGusaubiTor"/>
</ecore:EPackage>
