<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="badagusbifricus" nsURI="http://hub.de/rcore/examples/badagusbifricus" nsPrefix="wPKq">
  <eClassifiers xsi:type="ecore:EClass" name="BanulauboDaBiboGustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaugusAutus" abstract="true" eSuperTypes="//BanulauboDaBiboGustor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DafrifrigusDaBidanulEs" instanceTypeName="typeBraufrigusfriboboBebibofributus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DibuDaBeBobefribegusgusCio" instanceTypeName="typeDabigusBuDabucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubefriguBegufrigunulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faDabefribudabodatus" ordered="false" upperBound="-1" eType="//AunulaugusAutus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugugusguBunulaudafriNulaudaBocus" ordered="false" upperBound="-1" eType="//AunulaugusAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBibubiNulaubeDabibubicio" instanceTypeName="typeFanulauBiguBufrifribiBenulAubies"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFrigusnulAudaNulauguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Do"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabofriNulAubegusbeNulauBoGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuBigubeBenulaudator" eSuperTypes="//Do">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGubiBogunulius" ordered="false" eType="//BanulauboDaBiboGustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifribeBofrinulAuNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusbenus" upperBound="-1" eType="//BaBibubiNulaubeDabibubicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbonulaubiboBubiFrifriguTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBobenulauGusfriBegusgubogutor" upperBound="-1" eType="//EunulaunulauboGusGusbitor" eOpposite="//EunulaunulauboGusGusbitor/dubuBugubigugusGusdaDadadaGustor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafriBebidagudacus" ordered="false" upperBound="-1" eType="//AnnulauGusnulaufridabinulaunus" eOpposite="//AnnulauGusnulaufridabinulaunus/efriFriGuBudagubenulauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusdaBiEs" eSuperTypes="//Do">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auBubunus" upperBound="-1" eType="//DafrifrigusDaBidanulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlBeboGufriDafriBeTus" instanceTypeName="typeBaBeNulAunulauFriGubudaBubotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusgusNulauBedafriGusLius" abstract="true" eSuperTypes="//AunulaugusAutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaGufrigugulius" instanceTypeName="typeFadanulaubefriBibofribiboCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BedaBiGusDaGusfrilus" instanceTypeName="typeEugugusGusnulaubeBufriBigubees"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfriGubibofrinus" abstract="true" eSuperTypes="//FagusdaBiEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaunulauboGusGusbitor" eSuperTypes="//DubefriguBegufrigunulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubuBugubigugusGusdaDadadaGustor" ordered="false" upperBound="-1" eType="//AlbonulaubiboBubiFrifriguTin" eOpposite="//AlbonulaubiboBubiFrifriguTin/biBobenulauGusfriBegusgubogutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoguNulaunulaunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaBobiboBebutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagubebedagusdabebolius" ordered="false" upperBound="-1" eType="//Do"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BifribunulauBudaguBies" instanceTypeName="typeABegufriGusaubeGugusBufribeguLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraudagusnulAuTor" instanceTypeName="typeBagubugugugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBebodaFribudafribeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabefribobiBebobeBuNulaudabocus" ordered="false" eType="//AlbonulaubiboBubiFrifriguTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Alaubebegububebunus" instanceTypeName="typeFabiguNulaubogusBefrigusbetus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugubibofriDaNulius" instanceTypeName="typeAlbodadabuGustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlFriNulaubonulAuGubiBuButor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaBebugusAugubegusgusBubunus" ordered="false" eType="//EunulaunulauboGusGusbitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EufriBobiGusfriGusAugusnus" eSuperTypes="//FaGuBigubeBenulaudator //DifribeBofrinulAuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulaububofriguboGuses" ordered="false" upperBound="-1" eType="//AunulaugusAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AugusbiGubuNulaufrigubogusfriBiLius" instanceTypeName="typeABunulaubuDanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBudaBenulAugugunulauLius" eSuperTypes="//FabofriNulAubegusbeNulauBoGuses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebenulaububebonulAubeBoboBilius" ordered="false" upperBound="-1" eType="//AfriGubibofrinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubeBobibububegusFrigusBeboBucio" ordered="false" upperBound="-1" eType="//DifribeBofrinulAuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBuBoboBenulauLus" eSuperTypes="//EufriBobiGusfriGusAugusnus //AngusgusNulauBedafriGusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauGusnulaufridabinulaunus" eSuperTypes="//AudaBobiboBebutus //AlbonulaubiboBubiFrifriguTin //FaFrigusnulAudaNulauguslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efriFriGuBudagubenulauNus" ordered="false" eType="//AlbonulaubiboBubiFrifriguTin" eOpposite="//AlbonulaubiboBubiFrifriguTin/bafriBebidagudacus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babudaDaBubunulauNules" eType="//AlBeboGufriDafriBeTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusAugusAuCio" ordered="false" upperBound="-1" eType="//BanulauboDaBiboGustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AgusGudadaguGusbiboBufricio">
    <eLiterals name="EBoBibebegusnulaunulaulus"/>
    <eLiterals name="AlbunulaubidaBedaguNus"/>
    <eLiterals name="ABegusnulaubuguBidaBelus"/>
    <eLiterals name="AubeDaGusaubeboBefridafriBoCus"/>
    <eLiterals name="DugusbuDagudaguguslius"/>
    <eLiterals name="BedagusnulauBeBonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBigusDabebiguNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuFribibegusGuBugusdabobiGubeBitin" eSuperTypes="//AunulaugusAutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrigubucio" eSuperTypes="//EunulaunulauboGusGusbitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeNulaunulaunulAudagucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubifrifribinulAucio" abstract="true" eSuperTypes="//Do //EufriBobiGusfriGusAugusnus //AlbonulaubiboBubiFrifriguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Adalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeFriGubebuDadacio" abstract="true" eSuperTypes="//Do">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbiBeGusbubugusAugubifries" ordered="false" eType="//AnBigusDabebiguNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dagusbubufribobunules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DabuGusbiboFribeTor">
    <eLiterals name="DunulAuBiBubeGusdaDaDatin"/>
    <eLiterals name="AgusDadanulauDadaBoDabees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dibogusnulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babebinulAulus" upperBound="-1" eType="//AlBeboGufriDafriBeTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AguFribinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufrigusgusTus" upperBound="-1" eType="//EuFribibegusGuBugusdabobiGubeBitin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daboBudabeguses" eType="//BanulauboDaBiboGustor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauDagusdafriBeBoNulaufribiTus" ordered="false" upperBound="-1" eType="//BraubifrifribinulAucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgunulauFriguGubonulauTin" eSuperTypes="//BanulauboDaBiboGustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfriGusgubegusNulaubeBenulaunulauNus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabofriDadabiTin" eType="//BraudagusnulAuTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANulAuBeBoGusgudaBuboBenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euNulaugugusgusbebibibuGunus" ordered="false" upperBound="-1" eType="//EuFribibegusGuBugusdabobiGubeBitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbuGuNulaudaBiNulAuguses" eSuperTypes="//AnBigusDabebiguNulius //FaBudaBenulAugugunulauLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBebiFriDanulaucus" eType="//Adalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeFrinulaunulAudafriboBotor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alBeFribugusBues" upperBound="-1" eType="//AgusGudadaguGusbiboBufricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeBiBubeguBibibubetus" instanceTypeName="typeDobogusguBefribufribubilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBeBodabeboFribiguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abegunulauFribeFrigusGusnules" ordered="false" upperBound="-1" eType="//EuFribibegusGuBugusdabobiGubeBitin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebogubiFrifritus" ordered="false" upperBound="-1" eType="//EfriGusgubegusNulaubeBenulaunulauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfridadabibiguBigudadaGusgues" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGuBogugusBufrigusGutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigunulaugusBifribiguFrigusTin" ordered="false" eType="//FaFrigusnulAudaNulauguslus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBoDabuNulAubinulAuBunulaudalius" ordered="false" upperBound="-1" eType="//AlfridadabibiguBigudadaGusgues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBogufriFriDabubobebuDaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbubebubobegutus" ordered="false" upperBound="-1" eType="//DifribeBofrinulAuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulAunulAugusGuBeNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algusgusbobeGuTus" eType="//DabuGusbiboFribeTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBeguguslus" eType="//BaBibubiNulaubeDabibubicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGububuguGusgusguBicio" eSuperTypes="//BebeFriGubebuDadacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGudafriNulAubiBiGusBodaNus" eSuperTypes="//EuFribibegusGuBugusdabobiGubeBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBudabibogusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuboBuNulaubeNulaubolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedabebibuBegunulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusBidaBogubobefritor" eType="//FaBudaBenulAugugunulauLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EdanulaubebifriBubigusboFribiBiCio" instanceTypeName="typeBeGufriboboNulaubegufribegufribeBeBigufrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobebiGusaufribubiboGuCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AGusbuFriBebogusguGusBiDagusBecus" instanceTypeName="typeDodabibogusauguBenulaunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubuBeBobenulauNulautin" instanceTypeName="typeBifriGusnulaubuGusbifriFrinulaufricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulauGusBiguNulauboBiGulius" eSuperTypes="//BiGuBogugusBufrigusGutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbogubobonulAuBoGuNus" eSuperTypes="//EuBebodaFribudafribeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbobibeboBubiBebogusBufricio" ordered="false" upperBound="-1" eType="//DuFrigubucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafriDaGusGubuguLius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufrigusboBebedaBitin" ordered="false" upperBound="-1" eType="//FaGuBigubeBenulaudator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADaBoBoGucus" eSuperTypes="//FaBudaBenulAugugunulauLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauguboguGubogugusboGusgusBugulius" upperBound="-1" eType="//AlFriNulaubonulAuGubiBuButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibibudadadaDagusBudatin" abstract="true" eSuperTypes="//FaBudaBenulAugugunulauLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusboBubunulEs" eSuperTypes="//AguFribinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befriBibidabobodaBugucus" ordered="false" eType="//EufriBobiGusfriGusAugusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BibofribuNulaudadafribogubotin" instanceTypeName="typeAgusFrifriBiBifrinulauGunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgudanulauBoBobegudabenus" abstract="true" eSuperTypes="//BiGuBogugusBufrigusGutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alnulauboFriBufriCus" upperBound="-1" eType="//BifribunulauBudaguBies" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBonulAugusdaNulAububolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadagufriBobeBebodadagusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBodaBinulauboBegubolus" eSuperTypes="//AuBogufriFriDabubobebuDaTor //EunulaunulauboGusGusbitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauDabobefribiCio" ordered="false" eType="//ADaBoBoGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbunulAuBonulaudaNus" eSuperTypes="//AbogubobonulAuBoGuNus //BeBeBodabeboFribiguscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DibibonulAuGugubeDabedaTin" instanceTypeName="typeBraubebeBudaBebobeNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbefrigusNulAugusBiBuDaFrigubuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euNulaubeGusAugusgusguguguslius" eType="//FabofriNulAubegusbeNulauBoGuses"/>
  </eClassifiers>
</ecore:EPackage>
