<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bibefribetus" nsURI="http://hub.de/rcore/examples/bibefribetus" nsPrefix="av">
  <eClassifiers xsi:type="ecore:EClass" name="AunulaubefriboBefriboBedafriFrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eubogugusgusgusgusdagusius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGuBibidaBuFribedabees" eSuperTypes="//Eubogugusgusgusgusdagusius //AunulaubefriboBefriboBedafriFrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobofriguGusdabobubifribetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibobubofriGubobefriBegugusgusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBegubebofriGusbiNus" ordered="false" eType="//ABifriDagufriGusDaBeBuBotin" eOpposite="//ABifriDagufriGusDaBeBuBotin/braugugubegubonulaunulaunulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaufriFribubobobugucus" eSuperTypes="//Eubogugusgusgusgusdagusius //AunulaubefriboBefriboBedafriFrilius //DobofriguGusdabobubifribetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbiboboNulaugusbitus" eSuperTypes="//EGuBibidaBuFribedabees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebuNulaubigusFriBulius" ordered="false" eType="//BibobubofriGubobefriBegugusgusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BibigugusdadaNulaunulIus" instanceTypeName="typeBiGubibiBonulAuNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBiboguBodaBibicio" instanceTypeName="typeDibibunulauDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="EububefriDagusnus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafribebeFrinulaugusauLus" eType="//BibigugusdadaNulaunulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbebunulaubonulauBegulus" eSuperTypes="//AunulaubefriboBefriboBedafriFrilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biTor" eType="//BibigugusdadaNulaunulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudanulaudagusnulAuBeFriNulautin" abstract="true" eSuperTypes="//BibobubofriGubobefriBegugusgusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euNulAuguBiGuses" eType="//DobofriguGusdabobubifribetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagudaGusNulAubudagusGuGusNus" abstract="true" eSuperTypes="//Eubogugusgusgusgusdagusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGusboFriBeNulauGuslius" ordered="false" eType="//AunulaubefriboBefriboBedafriFrilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebiDafrifriBigusfriGusboBoTor" ordered="false" upperBound="-1" eType="//FanulaubuGusDagubilius" eOpposite="//FanulaubuGusDagubilius/dubibobigubeLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABifriDagufriGusDaBeBuBotin" abstract="true" eSuperTypes="//DudanulaudagusnulAuBeFriNulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugugubegubonulaunulaunulaucus" ordered="false" eType="//BibobubofriGubobefriBegugusgusnus" eOpposite="//BibobubofriGubobefriBegugusgusnus/anBegubebofriGusbiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AldaboNulaubefrigufribebibeNus" eSuperTypes="//EunulaufriFribubobobugucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eNulAugudagucus" eType="//BibigugusdadaNulaunulIus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBoDadafrigusfrigusautus" ordered="false" eType="//BefriBeGusDaboDaDaGusBinulEs" eOpposite="//BefriBeGusDaboDaDaGusBinulEs/doBeBinulauLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabeGusdabibobuLius" abstract="true" eSuperTypes="//DobofriguGusdabobubifribetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGuBibelus" eType="//EunulaufriFribubobobugucus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigugusguscio" eType="//BiBiboguBodaBibicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBibebuGuGugusNulAunulaubobubies"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaubuGusDagubilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibobigubeLus" ordered="false" eType="//DagudaGusNulAubudagusGuGusNus" eOpposite="//DagudaGusNulAubudagusGuGusNus/bebiDafrifriBigusfriGusboBoTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfribugubeBulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGugustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldagusbeBeBeGusfrigubeBoCus" eType="//AldaboNulaubefrigufribebibeNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulAuDagusnulauGubegusAunulAububuguslus" eSuperTypes="//AbiboboNulaugusbitus //FabeGusdabibobuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBugubogusbonulaugubofrifricus" eType="//DudanulaudagusnulAuBeFriNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubuFrifridagusguscus" eSuperTypes="//EGuBibidaBuFribedabees"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobuNulAunulaunulaugusFriNules" instanceTypeName="typeEbidagusGunulauBofribodadaCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiguDaNulaunulAuNulaudabobues" instanceTypeName="typeBebudabiGunulaunulAuTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braufribunulaunules" eSuperTypes="//EunulaufriFribubobobugucus //FabeGusdabibobuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBofriBibugusnulEs" ordered="false" eType="//DagudaGusNulAubudagusGuGusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebeboDanulaugubidaDagusgunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfrigugunulAuBubiDabibuCio" eType="//BibobubofriGubobefriBegugusgusnus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fafriBoes" eType="//DiguDaNulaunulAuNulaudabobues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGubigusFribigusguboGusnulAunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubeGuBefricus" ordered="false" eType="//DudanulaudagusnulAuBeFriNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugudafriBoes" eSuperTypes="//AunulaubefriboBefriboBedafriFrilius //Braufribunulaunules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBoNulauBeDabiBonulaunus" instanceTypeName="typeEgusgusnulaunulAuNulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebebofriguboGusbeGuGuTus" eSuperTypes="//FabeGusdabibobuLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubeguGuDabenulauNus" eType="//BibigugusdadaNulaunulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ABoNulAubeboDabeguNules">
    <eLiterals name="DobeBuBebiBugunulauNulius"/>
    <eLiterals name="Bibodabinulaulius"/>
    <eLiterals name="AnDafriDanulaulius"/>
    <eLiterals name="BiBiBubiBobugusbubuFriBebucio"/>
    <eLiterals name="EugugufriGuDaCus"/>
    <eLiterals name="AlbugububoBoBodadaBufriFriLus"/>
    <eLiterals name="AugusBigusbiDaGubuGusius"/>
    <eLiterals name="Docio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogufriBudabodanus" eSuperTypes="//DagudaGusNulAubudagusGuGusNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulautin" eType="//BibigugusdadaNulaunulIus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebenulAunulaudator" eType="//DoBoNulauBeDabiBonulaunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EgusaubiDagusTor" instanceTypeName="typeEubunulaubofribebibilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnTin" eSuperTypes="//AbiboboNulaugusbitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braububobogutor" ordered="false" upperBound="-1" eType="//BraugudafriBoes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DabiBobuBeguDabonus">
    <eLiterals name="EFridafribufridadadaFrinulautus"/>
    <eLiterals name="DobiGusaudaGunulIus"/>
    <eLiterals name="BibugusbubiFrinulaucus"/>
    <eLiterals name="Fagusbolus"/>
    <eLiterals name="Anulaugufrigusbifridagusnulius"/>
    <eLiterals name="AufriBebibebuBoguGutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ENulauBogusdaBiGusguNulEs" instanceTypeName="typeAlbugusdaGusgusBebobucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabibofridagubibuguTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EBegubobeguGuBonulius" instanceTypeName="typeDuBebuBebugusgutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusaudaGudafridaguBeCio" eSuperTypes="//FabibofridagubibuguTor //Eubogugusgusgusgusdagusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauGusbifriboGusgusbunulius" abstract="true" eSuperTypes="//BibobubofriGubobefriBegugusgusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBuFriBofridabiguBubuBonulEs" ordered="false" upperBound="-1" eType="//EbebunulaubonulauBegulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDagububuGusauBifrilius" eSuperTypes="//DagudaGusNulAubudagusGuGusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulaulus" ordered="false" upperBound="-1" eType="//AbiboboNulaugusbitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AububodaGusbebebugusguBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBiboguBofrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubebuFrigusgunulaunulAugugustin" ordered="false" upperBound="-1" eType="//BebebofriguboGusbeGuGuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DagudabunulAubofrinulAutin">
    <eLiterals name="BigusBodaGusBofriDaFricus"/>
    <eLiterals name="FanulaunulAunulauGusfrigustor"/>
    <eLiterals name="DafriboBibudaboguBubedabiGusBetin"/>
    <eLiterals name="BrAubibibibuGusbidaFrigusdaEs"/>
    <eLiterals name="EbubugugusGuFribubuTor"/>
    <eLiterals name="FagusbinulaufriBudanus"/>
    <eLiterals name="AGuboGusDaDanulEs"/>
    <eLiterals name="AubegusgusbiFriBies"/>
    <eLiterals name="BrauDaBuboFriFrigusNulaunulIus"/>
    <eLiterals name="BiboBobonulauDaTus"/>
    <eLiterals name="BenulauboguGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BefriBeGusDaboDaDaGusBinulEs" eSuperTypes="//EbebunulaubonulauBegulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBeBinulauLius" ordered="false" eType="//AldaboNulaubefrigufribebibeNus" eOpposite="//AldaboNulaubefrigufribebibeNus/biBoDadafrigusfrigusautus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doDabenulaugunulaububobinus" ordered="false" eType="//FanulaubuGusDagubilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusnulAubuDagusfrinulaugulus" eSuperTypes="//FabeGusdabibobuLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbebiEs" eType="//BibigugusdadaNulaunulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugufridagusgugusbebufrigusTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnaugusbiBiGusgusgubofridaLus" instanceTypeName="typeAnBuGusguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabeGusBugusdabifrinulius" eSuperTypes="//Eubogugusgusgusgusdagusius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubobeNulIus" eType="//ABoNulAubeboDabeguNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabedaBigusgusdaNulaubodabeBidacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulAubuBitor" ordered="false" eType="//BraugudafriBoes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAunulAuboBinulaunulaufrifritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulauBegusNulius" eSuperTypes="//AnTin //AfribugubeBulus //DuBiboguBofrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eufribedadabidaBoguscus" eType="//EgusaubiDagusTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubugudaGusdabibilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulaulius" eSuperTypes="//BebeboDanulaugubidaDagusgunules //BaGugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGugusBobugudaDadagusnulAubelius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afrifriTin" eType="//ABoNulAubeboDabeguNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbinulaubeNules" eSuperTypes="//BebebofriguboGusbeGuGuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibiBigusgugusbobuNulauCio" ordered="false" eType="//EuNulAuDagusnulauGubegusAunulAububuguslus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabodabiBifridagusdabutus" ordered="false" upperBound="-1" eType="//FabeGusBugusdabifrinulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angufritor" eType="//ABoNulAubeboDabeguNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiguFrigusbigusnulauGusLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babeDanulaufrinulaubitor" ordered="false" upperBound="-1" eType="//DuBiboguBofrilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubuBebidaboNulautus" ordered="false" upperBound="-1" eType="//AfribugubeBulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusbuBinulaubidaFribotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaBuguNulaubebees" eType="//DoBoNulauBeDabiBonulaunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebeNus" eType="//EBegubobeguGuBonulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DagufribubobuBenulAutor">
    <eLiterals name="EubeNulauguGusbebufribeguBegunulAunus"/>
    <eLiterals name="AuGusGusgusbenulaufriGues"/>
    <eLiterals name="EugusboboBilius"/>
    <eLiterals name="AndaboGubeDaGugusGubibebobobonulIus"/>
    <eLiterals name="EuBiDabibudaNulaugusbilius"/>
    <eLiterals name="DubogubigusbubibiNus"/>
    <eLiterals name="DabeGusbinulaububiDagubutus"/>
    <eLiterals name="DobunulaubuBiDadaNulaudaNus"/>
    <eLiterals name="DibibuboguGusnulauGusfrifrinules"/>
    <eLiterals name="AgusgusNulAuguBigubuNulaunus"/>
    <eLiterals name="AnbebiboDalus"/>
    <eLiterals name="EBuGusgusbubogusdatus"/>
    <eLiterals name="BraufrinulaububeguGubetin"/>
    <eLiterals name="AndadabudaBibibolus"/>
    <eLiterals name="Ebububebofrigusbobutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabobifribeGugusdaBonulauBetus" instanceTypeName="typeDaGubugusdabuBugubobuBucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbebibugusAugusfrifridalius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibugusgubebobifrigusBebedalus" eSuperTypes="//AubugudaGusdabibilus //ABifriDagufriGusDaBeBuBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DunulaugusgusfriBiDanus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAugusfribuBiDaGusnulAuboes" eType="//BiBiboguBodaBibicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulAuguBububifrifribitor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eguGusFriBudabofribolius" eType="//AnaugusbiBiGusgusgubofridaLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fabugububogugusnulaulius" eSuperTypes="//DunulaugusgusfriBiDanus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBubeFribeboGunules" instanceTypeName="typeAlbiBubetor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBibuBoFridaDaBidabeFribinus" instanceTypeName="typeAlGusBubuBeDabuBeNulaunulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBogusbogusnulaudadaBefrifricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBuEs" eSuperTypes="//DagudaGusNulAubudagusGuGusNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBuFriFrifriNulaunus" upperBound="-1" eType="//DiguDaNulaunulAuNulaudabobues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAuBugusnulaufriBegusBiDaBoEs">
    <eLiterals name="Eugusbenulaubinules"/>
    <eLiterals name="EuNulaufrigubegusNus"/>
    <eLiterals name="AuFriDagusaufrigubetus"/>
    <eLiterals name="AubinulauBebofrigusbiFribuDacio"/>
    <eLiterals name="Dubebelus"/>
    <eLiterals name="DagubofriFrinulaudagunulius"/>
    <eLiterals name="DuBegufribuFribidaBibubebiNulius"/>
    <eLiterals name="AuGunulaugugugugusbies"/>
    <eLiterals name="Binulaubenus"/>
    <eLiterals name="Braufricio"/>
    <eLiterals name="BabebofriBoDadagusnulaunulaunulEs"/>
    <eLiterals name="EnulAubuGusbefrifrifribobidafribetus"/>
    <eLiterals name="Albinulaufrigububebies"/>
    <eLiterals name="DaGusdagugugubobodabetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EdaDadafriNulEs" instanceTypeName="typeBrAuBuguBiDabucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbenulauguBeFribuNulAufribocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulAuNulAuNulautin" ordered="false" upperBound="-1" eType="//EugufridagusgugusbebufrigusTin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eguBogusboguNulauguLus" eType="//BiBiboguBodaBibicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubobefridafrifriBofribebitin" instanceTypeName="typeEubugugubegubobedaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusBubeboBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beGuBufriNulaufrifrigusbetor" ordered="false" upperBound="-1" eType="//BraugudafriBoes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBifrigubiBubedatus" eSuperTypes="//AnBogusbogusnulaudadaBefrifricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigugusBefrifrinulAuBiTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBobufrifribuBefrigusaugusbiEs" ordered="false" eType="//BeBifrigubiBubedatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusboGusfrifribufriNules" upperBound="-1" eType="//DaGusBubeboBolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAubobuGubinulauNulaubobetor" eSuperTypes="//AnbebibugusAugusfrifridalius //BibobubofriGubobefriBegugusgusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFribuboboBeFritor" eSuperTypes="//BefriBeGusDaboDaDaGusBinulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuFrigusBeBoguGuLus" eType="//BiBiboguBodaBibicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiguFriFriGusBuBiBebodabucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBenulaubibodaNulAugusguses" eType="//BiBiboguBodaBibicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BefriFriDaGusgubofriBoBefriFritor" instanceTypeName="typeAlauFribobeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDabebugusaudaEs" eSuperTypes="//EunulauGusbifriboGusgusbunulius //EbenulauguBeFribuNulAufribocio //DigugusBefrifrinulAuBiTin //FanulAubobuGubinulauNulaubobetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diFriGuFriboBoDafritus" ordered="false" upperBound="-1" eType="//AububiFrifridabodaBebegusbuDatus" eOpposite="//AububiFrifridabodaBebegusbuDatus/biboBodaGuBibeNulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Badadabubobudagusnules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibunulaudaboDafriFriFrinulEs" eType="//DoBoNulauBeDabiBonulaunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbobiBiBidanulautin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faguboNulaubonulaugusgubies" eType="//BiBibuBoFridaDaBidabeFribinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnDabigusBebibuGubeGusgubedaButus" eSuperTypes="//BebebofriguboGusbeGuGuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBibebobeNulaudabuNulius" ordered="false" eType="//AnFribuboboBeFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuFriboGusnulAuFriGusBogusaudafritor" abstract="true" eSuperTypes="//DubuFrifridagusguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrifriBenulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgugusbobuGusAuCio" eSuperTypes="//EunulauGusbifriboGusgusbunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braugusguBonulauGusaunulius" eType="//DubobefridafrifriBofribebitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBuDagudaBibibobiNus" eSuperTypes="//DigugusBefrifrinulAuBiTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebibibifribibetin" eType="//EgusaubiDagusTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EubibeNulauguBobugubibiboCio">
    <eLiterals name="BigusboBebodaBilus"/>
    <eLiterals name="AngusboDaBuDagustus"/>
    <eLiterals name="EguNulAugubeBefries"/>
    <eLiterals name="FaGusAugusdabebecus"/>
    <eLiterals name="Anguses"/>
    <eLiterals name="FagudabuGusdabogufries"/>
    <eLiterals name="AlBuGusgusdabuEs"/>
    <eLiterals name="DubibiBidaGusdabuGusius"/>
    <eLiterals name="BaBegusnulauDabiBuTin"/>
    <eLiterals name="BagusCus"/>
    <eLiterals name="BagusGuFridaNulAuLus"/>
    <eLiterals name="DuBegugusdabibobibofriTin"/>
    <eLiterals name="AlAuGusaudagusbunulaubobibitus"/>
    <eLiterals name="AubebiboGuguBuTin"/>
    <eLiterals name="FanulaugusBuGuBeBubocio"/>
    <eLiterals name="BefribufriNulaugusnulAunus"/>
    <eLiterals name="BibofriDabulus"/>
    <eLiterals name="DubuguTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ADadafriBibeboDaNules" instanceTypeName="typeAuGubeguNulAuBotin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BedaGuGusnulaugues">
    <eLiterals name="BigusgubofriGusnulius"/>
    <eLiterals name="BraubifrinulauGusGunulaubicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AububiFrifridabodaBebegusbuDatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedabogusAuGudatin" eType="//DobuNulAunulaunulaugusFriNules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboBodaGuBibeNulIus" ordered="false" eType="//EDabebugusaudaEs" eOpposite="//EDabebugusaudaEs/diFriGuFriboBoDafritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBibudagusfriboFribues"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulauDagusGusBoBubonus" eSuperTypes="//EgugusbobuGusAuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eNulAuGusnulAucus" eType="//BibugusgubebobifrigusBebedalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobogusBegusauBunulauDatin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EudafrifriBibibuDanulaububigusbenulAulius" instanceTypeName="typeEbuGusgusboFriBubegufribobicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufrigusNulAuDacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusbufriDaGusnulaudaGusaubolus" ordered="false" upperBound="-1" eType="//EDabebugusaudaEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbigusguboboguBoNulius" ordered="false" upperBound="-1" eType="//BaGugustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBoDabegusauFribiBeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bagusgubinulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babenulaubonus"/>
</ecore:EPackage>
