<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="braudabelus" nsURI="http://hub.de/rcore/examples/braudabelus" nsPrefix="dpyT">
  <eClassifiers xsi:type="ecore:EClass" name="BiBinulAuguBibeFridabibububibotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eugugubefrigulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubedabuBebobuBibefribucus" eSuperTypes="//BiBinulAuguBibeFridabibububibotor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulaugusBeBebiLius" ordered="false" upperBound="-1" eType="//Eugugubefrigulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbofrinulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobiFrigugufribuguslius" instanceTypeName="typeDafrifrigusBiBifriBuguboboNulAulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EfribunulaubegusNulaubifriFritin" instanceTypeName="typeAguNulAubiBonulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabiboDaBubeNulauBeDagusNulautus" abstract="true" eSuperTypes="//EbofrinulEs //Eugugubefrigulus //BiBinulAuguBibeFridabibububibotor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGusFrifribulius" ordered="false" upperBound="-1" eType="//EbofrinulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulauBibibiBuDaGusgusnus" eSuperTypes="//BiBinulAuguBibeFridabibububibotor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbiNulauGusbuBeBuLus" upperBound="-1" eType="//EfribunulaubegusNulaubifriFritin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubenulaubonulaubudabubiBitin" ordered="false" upperBound="-1" eType="//AnaubedabuBebobuBibefribucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGunulauDabeDadaBubeBoes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFriguGusFriNules" ordered="false" eType="//EbofrinulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulauBeNus" eSuperTypes="//BiBinulAuguBibeFridabibububibotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulauguBebugusbocio" eSuperTypes="//BiBinulAuguBibeFridabibububibotor //DaNulauBibibiBuDaGusgusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulaufriBeFribofricus" ordered="false" upperBound="-1" eType="//AubiboGusbuNulauBiboTor" eOpposite="//AubiboGusbuNulauBiboTor/dogusBefrifrigusauguTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubiBubiBoBeBedabidaBoDaBifribilius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibifrigusbigusbibiTus" eType="//DobiFrigugufribuguslius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaunulauGusaugusgubufritin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dafribibefribebinus" instanceTypeName="typeAnulaudaGusbeFrinulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuBebedadabogusguboBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusbobuFriguBeboNulAuguNulius" ordered="false" upperBound="-1" eType="//BiBinulAuguBibeFridabibububibotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DanulauBelius" instanceTypeName="typeDuguBonulAuNulaugudagusbicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusdagusBobotin" eSuperTypes="//DabiboDaBubeNulauBeDagusNulautus //BeGunulauDabeDadaBubeBoes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBoGuBubebinulaugusAuFribedagutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbubobobobenulAugusLus" eSuperTypes="//DagusdagusBobotin //AnaubedabuBebobuBibefribucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifriBeBubeBofriBefribiguguNus" upperBound="-1" eType="//DabiboDaBubeNulauBeDagusNulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DabiBegusGubogugusbububuBeCio">
    <eLiterals name="BegusguBogusaububeBibobeBuDatin"/>
    <eLiterals name="BraugusBibeDanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbunulaudagufriGubebuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebuguguBubibogudabeFribiDaLius" eSuperTypes="//DinulaunulauGusaugusgubufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafrinulauBuBifribogusbubufriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuDatus" eSuperTypes="//BeGunulauDabeDadaBubeBoes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusbugudabudaBigusDatus" ordered="false" upperBound="-1" eType="//AlbuBebedadabogusguboBonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifribedabogubodaGusGutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babeboboBegusbeGudadaes" ordered="false" upperBound="-1" eType="//DoFrinulaubefriboboBeEs" eOpposite="//DoFrinulaubefriboboBeEs/faBeGusgusBiLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bibebigusdadanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGusbiguguDabegutin" ordered="false" upperBound="-1" eType="//EubegusboboboBotin" eOpposite="//EubegusboboboBotin/doBigusbeBidaBoEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGugusgusaufribiBebeGubobeFriGuslus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbedagubiFribegunulauGusBiGunus" instanceTypeName="typeAnboNulAuBudaFriTus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AbuBuBubububefrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alaugubebibibobigutor" eSuperTypes="//BebuguguBubibogudabeFribiDaLius //EbubobobobenulAugusLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagugusBefribifriboNulius" eType="//Dafribibefribebinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusgusBububifries" eSuperTypes="//DafrinulauBuBifribogusbubufriNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubebugusfribiNulEs" eType="//EbunulaudagufriGubebuTin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aFrinulauBubeBoNulius" ordered="false" upperBound="-1" eType="//BaNulauguBebugusbocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibeDabodaBilius" eSuperTypes="//DaNulauBeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusfrigusGusBegufriDaNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoFriguNulaunulaubofrinulauTus" instanceTypeName="typeDobebobebebuBudaNulauDaDacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAubeBugubeNulius" eSuperTypes="//DagusgusBububifries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebubibuboNulaubebocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAufribiGugubuguBobuDabecus" eSuperTypes="//BiBinulAuguBibeFridabibububibotor //BaNulauguBebugusbocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusbogusGuBicus" ordered="false" eType="//DaNulauBibibiBuDaGusgusnus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebogusnulauboBunulautin" eType="//EubedafriBifrigusEs" eOpposite="//EubedafriBifrigusEs/beGusBubefrigubebinulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABibobuBefriGuBidabedagusautus" eSuperTypes="//BrAuDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiboGusbuNulauBiboTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusBefrifrigusauguTor" ordered="false" upperBound="-1" eType="//BaNulauguBebugusbocio" eOpposite="//BaNulauguBebugusbocio/enulaufriBeFribofricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubeboBodagusBefribies" instanceTypeName="typeBibiguGusbiFribuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuBuGusgusguBiBofriBiTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubedafriBifrigusEs" eSuperTypes="//AlbuBebedadabogusguboBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beGusBubefrigubebinulEs" ordered="false" eType="//DinulAufribiGugubuguBobuDabecus" eOpposite="//DinulAufribiGugubuguBobuDabecus/bebogusnulauboBunulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinulaugusaubenulauCus">
    <eLiterals name="BeNulAufridaBibonulauboguses"/>
    <eLiterals name="DogusaubidafriNulauboFrigusNulauLus"/>
    <eLiterals name="EbuboFriBobenus"/>
    <eLiterals name="DiNulAuNulauBinulauFribefrilus"/>
    <eLiterals name="AlbuBuBifrigusGudabobuNulaubocio"/>
    <eLiterals name="AGuBufrigusgubonulAubuBues"/>
    <eLiterals name="BiBoDafrinulauBobegusGubogunus"/>
    <eLiterals name="EuBeBoBebefrinulaufridaCio"/>
    <eLiterals name="DuFriBunulaubefridabubucus"/>
    <eLiterals name="BiboNulauguBidagudaes"/>
    <eLiterals name="BaBebuNulAunulaugusbetus"/>
    <eLiterals name="DafriboCio"/>
    <eLiterals name="EugusgusfrifribiFribuBufritor"/>
    <eLiterals name="BrAunulAuGudadalius"/>
    <eLiterals name="AugusBoGusBoBeBubiDagusbobolius"/>
    <eLiterals name="AdafribinulaunulauDafrifriGubuTus"/>
    <eLiterals name="DagusAuFriFribeBefrigunus"/>
    <eLiterals name="AunulauBeDabonulauBibeEs"/>
    <eLiterals name="AunulauBoBeboBubiBeguCus"/>
    <eLiterals name="DugubiNulauBuButus"/>
    <eLiterals name="AbonulauguBuboboBobodabuboBuNulauCus"/>
    <eLiterals name="FagusbebiguBiDagunulAubogusdaDalus"/>
    <eLiterals name="BiGusfriNulauGuBeBuLius"/>
    <eLiterals name="EuboNules"/>
    <eLiterals name="AlgudabedadafriBigusGusgusBefriNus"/>
    <eLiterals name="DiGusauBeBibinulius"/>
    <eLiterals name="BiFrinulaubogudagusBuNulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafrinulAunulauGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubedaBegudaBobeNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadaDabeFriboDabobiNulAuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibobebofribidaGunulEs" ordered="false" eType="//BibeDabodaBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbedabiBeFrifribeguGustin" eSuperTypes="//DaNulauBeNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaugusBuBubigusBoLius" ordered="false" eType="//DinulaunulauGusaugusgubufritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Da" eSuperTypes="//EubiBubiBoBeBedabidaBoDaBifribilius //EbofrinulEs //DinulaunulauGusaugusgubufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFrigusdanulAuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daNulAuBobebiBobuBebuGubibugububeNus" ordered="false" upperBound="-1" eType="//BibeDabodaBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusgusbebobeboBoNulAuDaboLus" eSuperTypes="//Eugugubefrigulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubedaCio" eType="//DoFriguNulaunulaubofrinulauTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauDaBufriGuGubibeCio" abstract="true" eSuperTypes="//EubiBubiBoBeBedabidaBoDaBifribilius //DadaDabeFriboDabobiNulAuTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigusNulaububoNus" eType="//DoFriguNulaunulaubofrinulauTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoFrinulaubefriboboBeEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBeGusgusBiLius" ordered="false" eType="//DifribedabogubodaGusGutin" eOpposite="//DifribedabogubodaGusGutin/babeboboBegusbeGudadaes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguNulauguBoNus" ordered="false" eType="//Alaugubebibibobigutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulaubufrigufriBobebiguslius" ordered="false" upperBound="-1" eType="//BaNulauguBebugusbocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dabudabues" abstract="true" eSuperTypes="//DaNulauBibibiBuDaGusgusnus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusdadabubiguBibegusIus" eType="//DobiFrigugufribuguslius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebegufribifrigububeguBobocus" eType="//EbofrinulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaguGusgusdadabudagubunulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faGuBofridaBiFriBefrinulaugufrigubugusTus" eType="//BaNulauguBebugusbocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubiGugubofriBegusnus" abstract="true" eSuperTypes="//EubiBubiBoBeBedabidaBoDaBifribilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibugubodabiBegudaGugustor" upperBound="-1" eType="//Dafribibefribebinus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBunulaugusBegunulius" ordered="false" eType="//EbuBunulAugusDabeNulauTin" eOpposite="//EbuBunulAugusDabeNulauTin/dubugusauFribegusbuGutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGusbeFrinulAulius" abstract="true" eSuperTypes="//BaGusfrigusGusBegufriDaNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabiDaboBodagusAubees" eType="//DobiFrigugufribuguslius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibefrigusbuBiBinulauLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagusbufritor" upperBound="-1" eType="//AbuBuBubububefrilius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBubobubobenulAugubuGuCus" upperBound="-1" eType="//Bibebigusdadanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbegufrigusbiDabiFricio" eSuperTypes="//DafrinulauBuBifribogusbubufriNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagusbebuboFriBotus" upperBound="-1" eType="//EbunulaudagufriGubebuTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBeguFribenulAunulaufribodaEs" eSuperTypes="//Bibebigusdadanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubegusboboboBotin" eSuperTypes="//DinulauDaBufriGuGubibeCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulaubeguBeguBigusAucio" eType="//DabiBegusGubogugusbububuBeCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBigusbeBidaBoEs" ordered="false" upperBound="-1" eType="//Bibebigusdadanus" eOpposite="//Bibebigusdadanus/euGusbiguguDabegutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoguguboGunulauguscio" eSuperTypes="//EGusbeFrinulAulius //BibeDabodaBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuBunulAugusDabeNulauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubugusauFribegusbuGutor" ordered="false" upperBound="-1" eType="//BraubiGugubofriBegusnus" eOpposite="//BraubiGugubofriBegusnus/brauBunulaugusBegunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusbuFriboGubugusnulaufriFribucio" eSuperTypes="//DaGugusgusaufribiBebeGubobeFriGuslus //DafrinulauBuBifribogusbubufriNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babiGuslus" eType="//DabiBegusGubogugusbububuBeCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoGugufriGusaugugusnulEs" instanceTypeName="typeEubifribigusGusfriLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbiFribeguGusgusbeFrinulaulius" instanceTypeName="typeDabuDaGusdaBenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaubinulAubibubububuguGuBeNulius" eSuperTypes="//DuBoGuBubebinulaugusAuFribedagutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abogusNulaunulauBigusdagububutus" eType="//BinulaugusaubenulauCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulAunulaufrigusbeGuDaBebocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enulauBebeguFribunulAutus" eType="//AbuBuBubububefrilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAuDaNulaufribuGufrilus" eSuperTypes="//DifribedabogubodaGusGutin //DanulAubeBugubeNulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Dabobubobudafribebues">
    <eLiterals name="EugusgusGubuNulaulus"/>
    <eLiterals name="DiguGuGusbiTor"/>
    <eLiterals name="Eugugubebidabebebucio"/>
    <eLiterals name="DobebibedaDaFribegusgusDacus"/>
    <eLiterals name="EbuFriboNulAubegulius"/>
    <eLiterals name="EboBibibunulAuBiGuboFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBoguBotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBinulaudagustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBeguBigusnulaubobeBuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulauBubiboFriBuBoBiGucio" eType="//DobiFrigugufribuguslius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babufrifribebubiCio" eType="//EfribunulaubegusNulaubifriFritin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGusbinulaudaNus" ordered="false" eType="//AnbuBuGusgusguBiBofriBiTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAugusbidagusbunulaucus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EububiGusdaBilius">
    <eLiterals name="BeDadadaFrigusTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidaNulAudagusGusFritin" eSuperTypes="//DagusdagusBobotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFrigudadadagugusGuscus" ordered="false" eType="//DinulAuDaNulaufribuGufrilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daguGusbenulauDaFrilius" upperBound="-1" eType="//DoFrinulaubefriboboBeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Bi" instanceTypeName="typeBrAuBuBuDaDafrigutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulAuBeBifribobugusBeguslus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugudaBonules" instanceTypeName="typeDubigubibedaBibuNulaubodaBibobofricio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiGusdabufriguscio">
    <eLiterals name="AudabeBebidaBiGusnulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiGusboguNulauguGuNulautus" instanceTypeName="typeDobebiBofribogusTor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BeDabiFrifriboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlFrifriGusGugusbibunulaudaguBelus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBeGusdaGutin" eType="//Dafribibefribebinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbefribugubeNulaugusbufriBeGudabubebetor" eSuperTypes="//EubegusboboboBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfrigudabogufrifrinulauguCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulAubuBiDaBuguDafrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusgusgusbedabeDagubenulEs" eSuperTypes="//EbubobobobenulAugusLus"/>
</ecore:EPackage>
