<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bibonus" nsURI="http://hub.de/rcore/examples/bibonus" nsPrefix="rQi">
  <eClassifiers xsi:type="ecore:EClass" name="Dabebubulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bebigugubunulaugugutus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBeBiCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBegusGubegubibiNus" ordered="false" upperBound="-1" eType="//Dabebubulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabubuBubonulauBebobebues" instanceTypeName="typeEubuBegusgusBofribuBugusauGutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FafriguBinulauGusfridafriCus" instanceTypeName="typeAlbeBogubiboFribotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dabofribebubudabulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiGunulautus" ordered="false" eType="//Bebigugubunulaugugutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafrigusnulaufribugusGuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubegusaubefridanulAutin" eSuperTypes="//Bebigugubunulaugugutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibigufribugudanulaugusFriboBuboGuslus" ordered="false" eType="//EuBeguBenus" eOpposite="//EuBeguBenus/bedaBobegusgusbeDabebutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fadanulaubigutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusfrigusbiBiboNulautus" ordered="false" eType="//DubegusaubefridanulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulauBonulauGufrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daFrigugusgubudanulaufrilus" upperBound="-1" eType="//EuBeBiCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaguBeBigusfrinulaucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfrinulaugusGusBoDacus" eType="//FabubuBubonulauBebobebues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fanulaunulautus" eSuperTypes="//Dabofribebubudabulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBenulaulus" upperBound="-1" eType="//FafriguBinulauGusfridafriCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AgusgubegugubiguFrifrifriBilus" instanceTypeName="typeBanulaubiguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBeBiFrinulaufriGuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauBubufriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiFriguBinulauGubinulautin" eSuperTypes="//DubegusaubefridanulAutin //Dabebubulius //EuBeBiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlauBidabenulaugusbibedadaFrifribuDator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBiBodadabubocio" ordered="false" upperBound="-1" eType="//Fanulaunulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulAubinulaubenules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AndaNulaugubuBefrifriGusbeboFriBebetus" instanceTypeName="typeDubiBoguBugutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBeguBenus" abstract="true" eSuperTypes="//BiFriguBinulauGubinulautin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidagubobubifribuTin" upperBound="-1" eType="//FabubuBubonulauBebobebues" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaBobegusgusbeDabebutus" ordered="false" upperBound="-1" eType="//DubegusaubefridanulAutin" eOpposite="//DubegusaubefridanulAutin/bibigufribugudanulaugusFriboBuboGuslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGuBogusGulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audaNulauGusbeFriBofribigutor" eType="//FabubuBubonulauBebobebues" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daguBofriguGubitor" ordered="false" eType="//Dabofribebubudabulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudabonulAubunulaugusgutin" eSuperTypes="//DaGuBogusGulus //BaguBeBigusfrinulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusBufriBefrifribibinulautor" abstract="true" eSuperTypes="//Fadanulaubigutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubiNulauNulaugusGutus" eSuperTypes="//BeNulAubinulaubenules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbugubibudadaTus" ordered="false" upperBound="-1" eType="//AuNulauBonulauGufrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusboGufribeBigusguguCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagubugubuDabeBoBeFriBebuCus" ordered="false" eType="//BeNulAubinulaubenules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faGugufriBodanulaugustor" ordered="false" upperBound="-1" eType="//Fadanulaubigutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBiBegusdabenulAucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabeBuDafriEs" ordered="false" eType="//DinulauBubufriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbunulauGusDaBobubuBobofrilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babofriboBetor" eType="//AgusgubegugubiguFrifrifriBilus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBuNulauguBiBofridaNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobuGuDabobebodagusbeFrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibibuDabiFrigutin" ordered="false" eType="//Bebigugubunulaugugutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABobinulAugugubebulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubibugusBebibuguguBogubiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAugugububefriDaDaBoGugutus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auFrigusbogusauGusbedabeBuNus" ordered="false" eType="//AlauBidabenulaugusbibedadaFrifribuDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobedabiDagusguNulaufriGutin" eSuperTypes="//AngusBufriBefrifribibinulautor //BiFriguBinulauGubinulautin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaFriGubuLus">
    <eLiterals name="AlgusBoBefriBefriBibogucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABugusnulauFriBoboguses" abstract="true" eSuperTypes="//DobuGuDabobebodagusbeFrinus //Dabofribebubudabulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeboDagusbonulauBibotus" eSuperTypes="//DubegusaubefridanulAutin //AnBeBiFrinulaufriGuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulaubiGunulauBubeDadabegusbiCus" ordered="false" upperBound="-1" eType="//ABugusnulauFriBoboguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbonulauBubiGugutor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusdaBebiGusbidagusBoBelius" abstract="true" eSuperTypes="//BaguBeBigusfrinulaucio //ABugusnulauFriBoboguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngubibugusDabetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiBiguFribebeBuGubibecus" ordered="false" upperBound="-1" eType="//AlauBidabenulaugusbibedadaFrifribuDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBedaboBugusDabeBogusgusdadagubiBunulius" eSuperTypes="//Dabofribebubudabulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Begusbibobibucus" eSuperTypes="//AubibugusBebibuguguBogubiCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusbogusGuGusNulIus" ordered="false" eType="//BaguBeBigusfrinulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AFriNulaububefrinulauNulAutin" instanceTypeName="typeAndaboBodaBunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abobefribilius" eSuperTypes="//AngubibugusDabetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulauGusdaFrigusgugusBigusfricio" upperBound="-1" eType="//BaguBeBigusfrinulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusbegusdadatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefridagusnulAubidanulauGuFritin" eSuperTypes="//DubegusaubefridanulAutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBogusGusbiDadaCus" eType="//BabeboDagusbonulauBibotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Albufritin" instanceTypeName="typeEuGufriBudagusgunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bagusbebitin" eSuperTypes="//EuBeguBenus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBibugubobuBolius" eType="//Albufritin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubinulaubuBudagusFrifriguDafrinulius" upperBound="-1" eType="//BrauGusbegusdadatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadaDaBubiGusbubogubidabidaGulus" eSuperTypes="//AuNulauBonulauGufrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badabudabuGunulauBiboBiEs" ordered="false" upperBound="-1" eType="//DunulAugugububefriDaDaBoGugutus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beboBobeGues" eType="//Albufritin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuguNulaugusboBiGulus" abstract="true" eSuperTypes="//BabeboDagusbonulauBibotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeFriboBebuBudaGunulauCio" instanceTypeName="typeAdabefrinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaGudaBiBulius" eSuperTypes="//AnBuNulauguBiBofridaNulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubodaGusdabeBotor" eType="//Albufritin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubobebidabufribiGubotor" eSuperTypes="//EuBeBiCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibenulAubetus" ordered="false" upperBound="-1" eType="//AbonulauBubiGugutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiGuBedagusdaBoBiboBuDadafrifriFriBefries" abstract="true" eSuperTypes="//Fadanulaubigutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EnulaubuBugusbiGusLius" instanceTypeName="typeAdabenulaubiNulauGusbuBonulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobuGuBuGusNulAugusnulAugusTus" eSuperTypes="//Fanulaunulautus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digubedabunulAucio" eType="//FafriguBinulauGusfridafriCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AbubigubedadaguTor">
    <eLiterals name="AlbunulaugusbiboBuBudaLus"/>
    <eLiterals name="BibeGusGusbebofricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGuguboNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulaufrigusBebebebibebufrilius" abstract="true" eSuperTypes="//AngubibugusDabetor"/>
</ecore:EPackage>
