<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aucio" nsURI="http://hub.de/rcore/examples/aucio" nsPrefix="WtTF">
  <eClassifiers xsi:type="ecore:EClass" name="BraubunulauBenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begubidaDaBeBuBobeCio" eType="//AnnulAuBibibebebunules" eOpposite="//AnnulAuBibibebebunules/euGugusgusDabebibobigusTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaDagusfridabedaBoNulaubebeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudaBugusgusbugusBinus" eSuperTypes="//BaDagusfridabedaBoNulaubebeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdafriBeGugusbubenulaubibofribecio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbuBiDagusbubeGusaubucus" ordered="false" eType="//ABobinulaubedagucus" eOpposite="//ABobinulaubedagucus/aBinulauNulauDabefrigusdaTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoNulAuBies" instanceTypeName="typeBraudaBuboFrifries"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauBifriGuGusBodaes" eSuperTypes="//BaDagusfridabedaBoNulaubebeCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlFriBufriGudabeBobenulaugusBebodagustin" instanceTypeName="typeBinulaubuNulAuBeGuboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAuBunulaububuBues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baguBegusbilus" upperBound="-1" eType="//BaDagusfridabedaBoNulaubebeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnFriBugugusaucus">
    <eLiterals name="BebiFriGunulAubiBebifridaguses"/>
    <eLiterals name="DibedabiBuBoBiBunulauBetor"/>
    <eLiterals name="AnfrifridabodabufriNulius"/>
    <eLiterals name="DoNulaubeBeFrifrifriNulauGusLius"/>
    <eLiterals name="AnFribeBebigustor"/>
    <eLiterals name="AnauBudaBebegubugusdadabofrilus"/>
    <eLiterals name="EDabebebebibebogusguboLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABobinulaubedagucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBinulauNulauDabefrigusdaTin" eType="//EdafriBeGugusbubenulaubibofribecio" eOpposite="//EdafriBeGugusbubenulaubibofribecio/anbuBiDagusbubeGusaubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubodabibeNulAufrigusnus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBebiNulAudabeLus" eType="//AnFriBugugusaucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DogubiBeFribofridagufribulius" instanceTypeName="typeFaBuGugusboNulaudagusbogusautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiBubigusguNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafriBobegubudadabudabibeDaFrilus" ordered="false" eType="//DudaBugusgusbugusBinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDabibuNules" upperBound="-1" eType="//BraubunulauBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DabufridaFrigusius">
    <eLiterals name="Dibubenulaubogusbefribubitus"/>
    <eLiterals name="AnbiNulAunulaubeboBoBeLus"/>
    <eLiterals name="FaBodabuBeGuBobucio"/>
    <eLiterals name="DifribiBodagusbobobenules"/>
    <eLiterals name="DaguBoguFrigusbeBubiGusfribebofriGusnulAuGuscus"/>
    <eLiterals name="BedaBenulauFridalus"/>
    <eLiterals name="DabenulAuBeDabolius"/>
    <eLiterals name="Ebibibobies"/>
    <eLiterals name="DudabeBiGusgusBinulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbibedabobidaCus" eSuperTypes="//BaDagusfridabedaBoNulaubebeCio //AubiBubigusguNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGuDabibodabogusguboes" eType="//BraubunulauBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudagusfriFribegubiFriNulautor" eSuperTypes="//EunulauBifriGuGusBodaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBeFribiBedaBeFriCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bebudabubebobiguscus" eSuperTypes="//ABobinulaubedagucus //EubodabibeNulAufrigusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboBeGusgudator"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauGudaboGuFriNulAuguDaes" instanceTypeName="typeDofribeBeDator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusboGugubigunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibunulauBogustus" eType="//DoNulAuBies" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlBegudaBoBegusguNulauBubonus" instanceTypeName="typeDaBogusbebugusfriBifriboNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusDabedabenulAubugucio" eSuperTypes="//EgusboGugubigunus //DudaBugusgusbugusBinus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeBigusfriGudabeFriboBebies" instanceTypeName="typeBibubeDabenulaubeguBibotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguBegusgusaucus" eSuperTypes="//AnbibedabobidaCus //EgusboGugubigunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusbogusius" eType="//DogubiBeFribofridagufribulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBobiguBilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulAudaNulAuBicio" ordered="false" upperBound="-1" eType="//AnbibedabobidaCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebiNulaubobugusaugulius" eType="//AnnulAuBunulaububuBues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusaunulaubugubofridaFrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusGusfrifrifries"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAuBibibebebunules" eSuperTypes="//DudaBugusgusbugusBinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifribodabenulaudanulAububutin" ordered="false" eType="//EubodabibeNulAufrigusnus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGugusgusDabebibobigusTor" ordered="false" eType="//BraubunulauBenus" eOpposite="//BraubunulauBenus/begubidaDaBeBuBobeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Eunulaunulaugusbubecus">
    <eLiterals name="AunulAuBugusauLius"/>
    <eLiterals name="DaDabeBuBufridacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubibofriBufriLus" eSuperTypes="//AnnulAuBunulaububuBues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbigusaugusgubebeBegugusnulauTor" ordered="false" upperBound="-1" eType="//AudagusfriFribegubiFriNulautor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusfribegusbobubolius" eType="//BeBigusfriGudabeFriboBebies" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BibegusdaBebiDabubuLius">
    <eLiterals name="AuBunulauGubodagusbubugusTus"/>
    <eLiterals name="AuBifribebudabiBuTin"/>
    <eLiterals name="EbofrigusbebinulaugufriBulius"/>
    <eLiterals name="BaBebegusboBidaFrinulius"/>
    <eLiterals name="BraubodaLius"/>
    <eLiterals name="ANulAugusauGusbubebuTus"/>
    <eLiterals name="EGusboBubigusbinules"/>
    <eLiterals name="EgusBebeDabuBunulAuGustor"/>
    <eLiterals name="DiBiboNulAuBugufridaNulEs"/>
    <eLiterals name="DibegusGusbibuguDaDabonus"/>
    <eLiterals name="DifriguDaDaFridabefriBiGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraunulauNulauGusAubofriEs" instanceTypeName="typeBinulaugusAugudaguNulEs"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DobeBuNulAuNulauBubeNus">
    <eLiterals name="Bafribulius"/>
    <eLiterals name="FabubobibububodaBubeBeNus"/>
    <eLiterals name="DobenulauNulauFribiFribuBebiBubucus"/>
    <eLiterals name="DogusDabibunulAuNulaubecio"/>
    <eLiterals name="BinulaugusbiboBibonulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBinulauGubiFribobubufriBidacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euBedadadaBotus" eType="//AlBegudaBoBegusguNulauBubonus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibibobedabiBoBigutor" ordered="false" upperBound="-1" eType="//Dufribidabibogusbebugusautus" eOpposite="//Dufribidabibogusbebugusautus/diBeguBebegubifribelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeGuguBoBibidabinulauLus" instanceTypeName="typeEbubidadalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobefriGusbefriBiBubuGusbilius" eSuperTypes="//EunulauBifriGuGusBodaes //DiBeFribiBedaBeFriCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBiTin" ordered="false" eType="//DudaBugusgusbugusBinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusbobefribonulaugusNulIus" instanceTypeName="typeBegusdaBefrifribuFribubeGulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufrinulAuBoBuBibeLius" eSuperTypes="//EunulauBifriGuGusBodaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGuGubeDabicus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBobibues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audabifribedaGusbues" eType="//DobeBuNulAuNulauBubeNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="danulAufriBibotin" eType="//AlBegudaBoBegusguNulauBubonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubobefribunulaudaNulauguGusius" eSuperTypes="//Eguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dufribidabibogusbebugusautus" eSuperTypes="//DubobefribunulaudaNulauguGusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBeguBebegubifribelus" ordered="false" eType="//AnBinulauGubiFribobubufriBidacus" eOpposite="//AnBinulauGubiFribobubufriBidacus/bibibobedabiBoBigutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaFribuBoFriDaBofribeNulauLus">
    <eLiterals name="BafriFridaDaes"/>
    <eLiterals name="FabifrifribugunulaufriDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBigues" instanceTypeName="typeAudanulaubeBibefrinules"/>
</ecore:EPackage>
