<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dobetus" nsURI="http://hub.de/rcore/examples/dobetus" nsPrefix="eFp">
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBifrifribibiBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugubugunulaubiGusnus" abstract="true" eSuperTypes="//BrAuBifrifribibiBelus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuGusbefrinulauBuGugubucio" instanceTypeName="typeAlfriGusfribubuguBonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGuNulauNulaubinulauBeTus" eSuperTypes="//BrAuBifrifribibiBelus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annulaubebibegusfriEs" eType="//EuGusbefrinulauBuGugubucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusguBidanulaubenules" ordered="false" upperBound="-1" eType="//BraugubugunulaubiGusnus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAugusautin" ordered="false" eType="//BraugubugunulaubiGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBiGunulaugunulautin" eSuperTypes="//BrAuBifrifribibiBelus //BraugubugunulaubiGusnus"/>
</ecore:EPackage>
