<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dibefrinus" nsURI="http://hub.de/rcore/examples/dibefrinus" nsPrefix="nDXv">
  <eClassifiers xsi:type="ecore:EClass" name="AlfrinulaubufrifribobeCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubunulAugubeBegusbeGubuBucio" upperBound="-1" eType="//Audabugutor" eOpposite="//Audabugutor/eubufrigudaguguboCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulaugufrigubeBobuguBigusguGusbelius" eSuperTypes="//AlfrinulaubufrifribobeCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusboBobegusBecio" upperBound="-1" eType="//AlfrinulaubufrifribobeCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Braugubies">
    <eLiterals name="BiDafribeFriFribububuTor"/>
    <eLiterals name="BraugusbobibunulAutor"/>
    <eLiterals name="DobunulaubeDaGusBubulus"/>
    <eLiterals name="DibiBibuBigubigusAugustus"/>
    <eLiterals name="Dibucus"/>
    <eLiterals name="EfridaGuDabebeBocus"/>
    <eLiterals name="AgusboBebubugulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibedafriDaBuguslius" eSuperTypes="//AlfrinulaubufrifribobeCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubibufrinulaunulauboTus" instanceTypeName="typeFaDabofrigubebicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulauFriGudaGusDaBuTor" eSuperTypes="//AlfrinulaubufrifribobeCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abuTin" upperBound="-1" eType="//DibedafriDaBuguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Audabugutor" abstract="true" eSuperTypes="//DibedafriDaBuguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubufrigudaguguboCio" ordered="false" eType="//AlfrinulaubufrifribobeCus" eOpposite="//AlfrinulaubufrifribobeCus/dubunulAugubeBegusbeGubuBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifribuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibeBegusBoBuguslius" ordered="false" eType="//Audabugutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulaugusdaBufribuboDaGusfriGuFritin" ordered="false" upperBound="-1" eType="//FagusdafrigubuFridabecio" eOpposite="//FagusdafrigubuFridabecio/bibibiGubebuGubuNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAufridafriGusgubefriBoBoLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAufriGusgubeTin" eType="//BrAubibufrinulaunulauboTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DuBiBebogusbeFribuFrigubobiFriboguscus">
    <eLiterals name="FabunulAugusbobogufricio"/>
    <eLiterals name="AngusboBogusbofrinulaunulaubegugusdaBiBodalius"/>
    <eLiterals name="DaFriGuBunulaunus"/>
    <eLiterals name="AlFriguBobebinulAugufricio"/>
    <eLiterals name="DubuNulaubuNulauBuBoNulautor"/>
    <eLiterals name="BiNulauGusguBubegusIus"/>
    <eLiterals name="BiBogusGunulauNulaubunulauGugusLius"/>
    <eLiterals name="FafribeFridabogusfricio"/>
    <eLiterals name="BabebidanulAufribugustus"/>
    <eLiterals name="BraubiGuGuNulEs"/>
    <eLiterals name="AlbuBebububiBedagusius"/>
    <eLiterals name="BrauFribobudabibiBuFriBiDabenulautin"/>
    <eLiterals name="BrauboTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlguNulaubeBecus" instanceTypeName="typeFaGusaufriboBuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibibiFrigugubigusdanulaubecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiboGusbubelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBenulaufriFribobiBinulAunus" eSuperTypes="//DiboGusbubelius //BrAufridafriGusgubefriBoBoLius //DibibiFrigugubigusdanulaubecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DagubuguGuGufrigusLus" instanceTypeName="typeBiBugunulAugugubiBogusbilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBebugusbibibogusbebubocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubofriBonulaufriNulAuTin" ordered="false" eType="//DibibiFrigugubigusdanulaubecus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aboFriboEs" eType="//Braugubies" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eNulAuBofriBeGusGuBubuDaBiEs" ordered="false" upperBound="-1" eType="//EbebiFribiLus" eOpposite="//EbebiFribiLus/baDabegugubebeGuFribobebuGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AudaBeguGubugusbibiBeDaTus" instanceTypeName="typeEuBebedabeNulAunulauBecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGuboBidabeNulaugusGusnules" eSuperTypes="//DibibiFrigugubigusdanulaubecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuNulAuBuGugusGusbubufriBogusbuGusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfribiBobedaBufridabenulius" ordered="false" eType="//EuBenulaufriFribobiBinulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfribibubeFritus" abstract="true" eSuperTypes="//BeGuboBidabeNulaugusGusnules //DibedafriDaBuguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBeguboGusaubulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadabedanulaufribenus" ordered="false" eType="//AlfrinulaubufrifribobeCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBuDagusBeTor" instanceTypeName="typeAngusGubonulaubedaDagusbonulauLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusbeguBegusdadanulAucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobinulauGusbeBobiBenulaunus" eSuperTypes="//AlfrinulaubufrifribobeCus //BaBeguboGusaubulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibuGusBuguBegusgubuBobuGusbebutor" ordered="false" upperBound="-1" eType="//DibibiFrigugubigusdanulaubecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigugufribunulauLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulAugusGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGunulaugudagusbubugusEs" eSuperTypes="//BrAuNulAuBuGugusGusbubufriBogusbuGusnus //DaBebugusbibibogusbebubocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faNulaugugusaubocio" upperBound="-1" eType="//DagubuguGuGufrigusLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibiBigunules" eSuperTypes="//EuBenulaufriFribobiBinulAunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulaugusfribogusdaLus" eType="//Braugubies" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusfriFriGububedaFrifricio" ordered="false" upperBound="-1" eType="//BrAufridafriGusgubefriBoBoLius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabebibidaes" eType="//AlguNulaubeBecus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAuboBibubobobiBoNulAutus" eSuperTypes="//AunulauFriGudaGusDaBuTor //DiboGusbubelius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edabugusauGuses" eType="//AudaBeguGubugusbibiBeDaTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BiboNulauGusdacio">
    <eLiterals name="Diguslius"/>
    <eLiterals name="Braucio"/>
    <eLiterals name="AuBubofritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusgusdagusdaBobibocio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alDadabebunulaubinulaububegubeTin" ordered="false" upperBound="-1" eType="//DaBebugusbibibogusbebubocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnnulaufrigusgusaunulAugusFrigutus" instanceTypeName="typeBabobugugugusnulaubegusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufrigusGusGusgubutus" eSuperTypes="//AnGusgusdagusdaBobibocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusgugusBuDaBubitor" eSuperTypes="//DobinulauGusbeBobiBenulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugubibiBogufriCus" ordered="false" upperBound="-1" eType="//DigugufribunulauLius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duFriBunulaudabicus" eType="//AlguNulaubeBecus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulauguBicio" ordered="false" eType="//EuBenulaufriFribobiBinulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulAubeFrinulauBonus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulAuBobobuBeLius" eType="//DanulAuboBibubobobiBoNulAutus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babibogufriNus" eType="//AnnulaufrigusgusaunulAugusFrigutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboDaGubobobegusBinulAucus" eSuperTypes="//BeGunulaugudagusbubugusEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fafrinulaucio" eType="//DuBiBebogusbeFribuFrigubobiFriboguscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DibebebofridaGunulautus" instanceTypeName="typeDuGusbuBebudacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibuBogusGudabugugusgusautus" abstract="true" eSuperTypes="//EufrigusGusGusgubutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulauDaFrifrinulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGusNulaugufribuBugubocus" upperBound="-1" eType="//EuBenulaufriFribobiBinulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fabifrinulaugudanulaulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubuGubefrinulaubuBoGusfribebetin" ordered="false" upperBound="-1" eType="//DiboGusbubelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbugusfrigusEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EugubunulAugugufribogubicus" instanceTypeName="typeBebibufriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfriGuBugusaugusfrigusgulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAugusbiboBibiDafridaFriNulauGuses" ordered="false" eType="//BaBeguboGusaubulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubenulAuBoBugusnulAuFrilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBiBoDaDanulAunulaudatin" instanceTypeName="typeBiGusauDaNulaubobulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaubudaBiguBigubuGusgutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBoGuCio" eType="//BiboNulauGusdacio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabegudafriBugunulAugubelus" instanceTypeName="typeBifriBegusbuBucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebebodaguNus" eSuperTypes="//EufrigusGusGusgubutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBubebefritus" upperBound="-1" eType="//BrAubibufrinulaunulauboTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbeGugusAufriGusnulaubugusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusdadaBubeboBoNules" ordered="false" eType="//Fabifrinulaugudanulaulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulauDagudabubeGusLus" ordered="false" upperBound="-1" eType="//BrAunulaugufrigubeBobuguBigusguGusbelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusdafrigubuFridabecio" eSuperTypes="//AugusgugusBuDaBubitor //BrAuNulAuBuGugusGusbubufriBogusbuGusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibibiGubebuGubuNulius" ordered="false" eType="//BifribuTin" eOpposite="//BifribuTin/dunulaugusdaBufribuboDaGusfriGuFritin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBedaboGuTin" ordered="false" upperBound="-1" eType="//BifribuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbefribuboDaCio" eSuperTypes="//DonulauDaFrifrinulEs //BebebodaguNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edaguNulauboguscus" eType="//AudaBeguGubugusbibiBeDaTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusBebolus" eSuperTypes="//DibiBigunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefriBugubuBibiBegubiDanulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubebugusBobugusius" abstract="true" eSuperTypes="//FagusdafrigubuFridabecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbiDaBofriGusgudaBibufrilius" eSuperTypes="//BeGunulaugudagusbubugusEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fadabeboBebeDadagusGugunus" upperBound="-1" eType="//AlguNulaubeBecus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifrigugusbedacus" ordered="false" eType="//AbugusfrigusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigugusbubiBubugusGusGudanulaubiCio" eSuperTypes="//BrAunulaugufrigubeBobuguBigusguGusbelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBububeBefrinulaugusbobebibeDagusGuscio" ordered="false" eType="//FagusdafrigubuFridabecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufribiBeFribubiBetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGudaboguBuguBufribenus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augubudaGugutor" eType="//DoBiBoDaDanulAunulaudatin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaFribinulAuDanulauGuscus">
    <eLiterals name="BrauBubufriDabogusgufriGunus"/>
    <eLiterals name="EuBudagunulauFriBegusfridafrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbebiFribiLus" eSuperTypes="//Fabifrinulaugudanulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfrinulaugusbigusGudagusnulAuCus" ordered="false" upperBound="-1" eType="//Audabugutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDabegugubebeGuFribobebuGusnus" ordered="false" upperBound="-1" eType="//DaBebugusbibibogusbebubocio" eOpposite="//DaBebugusbibibogusbebubocio/eNulAuBofriBeGusGuBubuDaBiEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBogusguBeBibolus" ordered="false" eType="//BrAufridafriGusgubefriBoBoLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgubiFribuBiBogusbifridacus"/>
</ecore:EPackage>
