<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="be" nsURI="http://hub.de/rcore/examples/be" nsPrefix="Cbf">
  <eClassifiers xsi:type="ecore:EDataType" name="DabeboBeguDabiGuscio" instanceTypeName="typeENulauGusFrinulauguNulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBefribeDaDaBibubegusGudaLius" instanceTypeName="typeBabiGusnulauBobedagububolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulauBoNulauBufritin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobudanus" eType="//DabeboBeguDabiGuscio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abegusgusnulauBocus" ordered="false" upperBound="-1" eType="//EdaguDagubenulAufridaGuLus" eOpposite="//EdaguDagubenulAufridaGuLus/albiFriguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaguGusdanulaunulauBobitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBiBubedabigunulAuDaBoButin" ordered="false" eType="//BibonulaugusauBucio" eOpposite="//BibonulaugusauBucio/biBunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoDaguFriDanulAuguLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aNulaubodaguBocus" ordered="false" eType="//DaguGusdanulaunulauBobitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaugunulauBuBonus" eSuperTypes="//DaguGusdanulaunulauBobitor //DoDaguFriDanulAuguLius //DanulauBoNulauBufritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badaguBiBebubuTor" ordered="false" eType="//BeFriFribobofriGusDanulaubebeCio" eOpposite="//BeFriFribobofriGusDanulaubebeCio/babebudagunulaugusfribeboEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnguFribuBiguboBoBebelus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Audanulaunus" eSuperTypes="//DaguGusdanulaunulauBobitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abuBodaBucus" ordered="false" upperBound="-1" eType="//DanulauBoNulauBufritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeFriFribobofriGusDanulaubebeCio" eSuperTypes="//DanulauBoNulauBufritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biGusgusfrinulautus" eType="//DoBefribeDaDaBibubegusGudaLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babebudagunulaugusfribeboEs" ordered="false" upperBound="-1" eType="//AlNulaugunulauBuBonus" eOpposite="//AlNulaugunulauBuBonus/badaguBiBebubuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabiGusbiBofrifrinulAunulius" instanceTypeName="typeDaBiBiDabonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGububeBeCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGusbibitor" ordered="false" upperBound="-1" eType="//EuBifrifrigubiguDaBunulAuboBogusdaboNus" eOpposite="//EuBifrifrigubiguDaBunulAuboBogusdaboNus/dadaBeFribeBuGudanulAucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBoBubinulAufriNulaugusNus" instanceTypeName="typeBiBoBenulAuGuDanulAufries"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnguGusbobegufribobinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobebogunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidaGusNulaugubigugubeGuCus" eSuperTypes="//BeFriFribobofriGusDanulaubebeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBubuBobogunulaunulAuFritus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusfriNulAuGustus" ordered="false" upperBound="-1" eType="//AnguFribuBiguboBoBebelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AngusBebibidabugusLus" instanceTypeName="typeFagusDafriNulauboGuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusbobiBuNulauDabunus" abstract="true" eSuperTypes="//AlNulaugunulauBuBonus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egugusgusbegucus" eType="//BiBoBubinulAufriNulaugusNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusbobefriBeFribufribuBunulaucus" ordered="false" upperBound="-1" eType="//DaguGusdanulaunulauBobitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibugusbobibenulAugusFribogusautus" ordered="false" upperBound="-1" eType="//DaguGusdanulaunulauBobitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdaguDagubenulAufridaGuLus" abstract="true" eSuperTypes="//AnguFribuBiguboBoBebelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albiFriguses" ordered="false" eType="//DanulauBoNulauBufritin" eOpposite="//DanulauBoNulauBufritin/abegusgusnulauBocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibonulaugusauBucio" eSuperTypes="//DaguGusdanulaunulauBobitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBunulius" ordered="false" upperBound="-1" eType="//DaguGusdanulaunulauBobitor" eOpposite="//DaguGusdanulaunulauBobitor/doBiBubedabigunulAuDaBoButin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBifrifrigubiguDaBunulAuboBogusdaboNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBogusbugusgutor" ordered="false" eType="//DoDaguFriDanulAuguLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaBeFribeBuGudanulAucio" ordered="false" upperBound="-1" eType="//EGububeBeCio" eOpposite="//EGububeBeCio/duGusbibitor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBenulaugugugutin" eType="//DoBefribeDaDaBibubegusGudaLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Begufrifribobigulius" eSuperTypes="//DanulauBoNulauBufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBububeBiDanulAunulAutor" eSuperTypes="//DidaGusNulaugubigugubeGuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDadaGusBebuBeguBuBenus" upperBound="-1" eType="//EGububeBeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabodabeDagunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doFrinulauBuBibeFriBibiBogucus" eType="//BabiGusbiBofrifrinulAunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugugusBogusbonules"/>
</ecore:EPackage>
