<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dobubunulaucio" nsURI="http://hub.de/rcore/examples/dobubunulaucio" nsPrefix="fV">
  <eClassifiers xsi:type="ecore:EClass" name="DoboGuBudabubobebuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGubibiBigubefrinulAubutor" eSuperTypes="//DoboGuBudabubobebuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguBuGubofriGuDabuTor" ordered="false" eType="//DoboGuBudabubobebuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAufribidaBugusbeBoLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBeboboBoBedafrigusdagusbibues" eType="//BaGubibiBigubefrinulAubutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulaubegusgusfrigusfrinulius" ordered="false" eType="//DuTin" eOpposite="//DuTin/dofrinulaubuGusbubibobeBocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebebibegusdaGudanulAuBicus" instanceTypeName="typeBebunulAugufriGusaudacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusBebegubuEs" eSuperTypes="//DoboGuBudabubobebuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fanulauGusnulaufrigusbiGubunus" eType="//BebebibegusdaGudanulAuBicus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BafribubuBonulAubenulius" instanceTypeName="typeDoBiGuguGuNulAuBebegusdaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudabuguDafridagusaulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audadabedabegusgusfriBufribubiBonules" upperBound="-1" eType="//BaGubibiBigubefrinulAubutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabubugusfrigusbuBuGucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeguBeguses" abstract="true" eSuperTypes="//DoboGuBudabubobebuCio //BabubugusfrigusbuBuGucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusdafriNulAudagubecio" eType="//DudabuguDafridagusaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofrinulaubuGusbubibobeBocio" ordered="false" eType="//AnnulAufribidaBugusbeBoLius" eOpposite="//AnnulAufribidaBugusbeBoLius/donulaubegusgusfrigusfrinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGubibuDacio" abstract="true" eSuperTypes="//DudabuguDafridagusaulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eFridaBudaNulius" eType="//BafribubuBonulAubenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibegusfriBibibogusNulauFribeguBoBeBecus" eSuperTypes="//BaGubibuDacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusGusaufriBenulaubobilius" upperBound="-1" eType="//BaGubibiBigubefrinulAubutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndaGusgubuGusbugunulauBicio" eSuperTypes="//BeguBeguses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulauBoNulaufriguboBulius" ordered="false" upperBound="-1" eType="//FagusBebegubuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubedabugubobunulAuNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagusbogubeGuboBenulAuBies" instanceTypeName="typeADaBeFridabibelius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabibubidaBoGustus" instanceTypeName="typeDanulaugubebuBofribeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafriBudaBibodaDabenus" eSuperTypes="//BibegusfriBibibogusNulauFribeguBoBeBecus //DoboGuBudabubobebuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beGusNules" ordered="false" eType="//DuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaubuFriboBoGufriDagucio" eSuperTypes="//AndaGusgubuGusbugunulauBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibeDaBedaGubotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuDadagubibobibecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EudabububuGunulius" instanceTypeName="typeBrauBufribobenulaucio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DugusLius">
    <eLiterals name="DoBeFribuNulaubifriNulIus"/>
    <eLiterals name="DoBenulaubegusbugusEs"/>
    <eLiterals name="BraudafrinulAuFrigugusBufricio"/>
    <eLiterals name="BabiguBiGubifribebodaLius"/>
    <eLiterals name="BiDaguBudabebebebues"/>
    <eLiterals name="ENulaubefriGubeguscio"/>
    <eLiterals name="DafriGusbudagugusbeboFriGusBiNus"/>
    <eLiterals name="BrAuGusbinulauGusNulAuTus"/>
    <eLiterals name="EuDabedaDanulauNulAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauDagusaufritor" eSuperTypes="//DuDadagubibobibecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraufriGusfritus" instanceTypeName="typeEubegusbobibogusGulius"/>
</ecore:EPackage>
