<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anbutin" nsURI="http://hub.de/rcore/examples/anbutin" nsPrefix="aK">
  <eClassifiers xsi:type="ecore:EClass" name="DabobebibefriNulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBeguBeGuBebebunus" upperBound="-1" eType="//BaDadaFribugubeGutus" eOpposite="//BaDadaFribugubeGutus/albefrigubonulaugusdaTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Bibinulaufrifridabunulius" instanceTypeName="typeDugusAubonulAuguBidaboGusfrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulaubuGuGububofriBubogutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBigusDaBobenulaubogusfritus" ordered="false" upperBound="-1" eType="//DabobebibefriNulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbubeGusguBebogugufridaDalius" eSuperTypes="//DabobebibefriNulaucus //EnulaubuGuGububofriBubogutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibeGuguLius" upperBound="-1" eType="//Bibinulaufrifridabunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusboBeguBugusguBebicio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubebubenulaubuBuboBocus" eType="//Bibinulaufrifridabunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusbibobubeBuBees" eSuperTypes="//DugusbubeGusguBebogugufridaDalius //DagusboBeguBugusguBebicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobubibeFriboBobibibicus" ordered="false" upperBound="-1" eType="//EnulaubuGuGububofriBubogutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bibubobugustus" eSuperTypes="//EnulaubuGuGububofriBubogutin //DabobebibefriNulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaDagusGuGudaGubobenules" eSuperTypes="//DagusboBeguBugusguBebicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufrigubegusauGudabofrilus" ordered="false" eType="//DabobebibefriNulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubobunulaudaBenus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBeBuBuGubobuBiBeGuFribonulauBenulautus" upperBound="-1" eType="//DugusbubeGusguBebogugufridaDalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AldabuBiBobegubobebegusfriTin" abstract="true" eSuperTypes="//DabobebibefriNulaucus //DagusboBeguBugusguBebicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaDadaFribugubeGutus" eSuperTypes="//AldabuBiBobegubobebegusfriTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albefrigubonulaugusdaTin" ordered="false" upperBound="-1" eType="//DabobebibefriNulaucus" eOpposite="//DabobebibefriNulaucus/doBeguBeGuBebebunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afridabogugubuNulIus" ordered="false" upperBound="-1" eType="//DagusboBeguBugusguBebicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabiFrifriBobugusboLius" instanceTypeName="typeBeBogusdafriBigusbotor"/>
</ecore:EPackage>
