<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="acio" nsURI="http://hub.de/rcore/examples/acio" nsPrefix="qby">
  <eClassifiers xsi:type="ecore:EClass" name="BaGubunulAubeDanulAubecio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusbugubifries" eSuperTypes="//BaGubunulAubeDanulAubecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGuBegusnulaubibilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiFribifrinulAubibegusguBelus" instanceTypeName="typeDaFriBiboBeGusdadafrigusBucus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AGusgufrigudanulAuBenus">
    <eLiterals name="AnaugusdaBibebeDaboGusLius"/>
    <eLiterals name="BeDadadanulaugusBebudabufricio"/>
    <eLiterals name="DubeFrinulauNulauNulauguBogusGufribunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DoguTus">
    <eLiterals name="DiguFridaGulius"/>
    <eLiterals name="DafriNulaugunulaudanulautin"/>
    <eLiterals name="EgubedaGusNulaunulaubuBiguBugusBulus"/>
    <eLiterals name="DobuDabeFriGusnulaunus"/>
    <eLiterals name="EFribinulaugubunulauGusEs"/>
    <eLiterals name="DonulaubefrinulauguLus"/>
    <eLiterals name="Bibetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobiBedaGusauBugusbibucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaunulauGuboFriBebeBiBelius" abstract="true" eSuperTypes="//BaGusbugubifries //DoGuBegusnulaubibilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DidaguDabenulAubudabobeBinus" instanceTypeName="typeDofriBobiDaBoTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusdaFribocus" eSuperTypes="//AlaunulauGuboFriBebeBiBelius //DobiBedaGusauBugusbibucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anAugugusFrigusDaBubies" ordered="false" eType="//DobiBedaGusauBugusbibucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibugusgubuBibiboGusbiBubetin" upperBound="-1" eType="//AbugusGubues" eOpposite="//AbugusGubues/alaubudaBobogusdabiGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabidaBebiNulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anBedaBegusgusguDaFrilus" eType="//AGusgufrigudanulAuBenus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBilus" ordered="false" upperBound="-1" eType="//BaGubunulAubeDanulAubecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudafribigusfridadanulauBucio" eSuperTypes="//BabidaBebiNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaufriNulAulus" abstract="true" eSuperTypes="//BigusdaFribocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaBegusBobubeBeNules" upperBound="-1" eType="//BaGubunulAubeDanulAubecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadanulAuBubofriGusNulaugusbuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albidabibobebuBubeTin" ordered="false" eType="//AudafribigusfridadanulauBucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulAuBofrigubobugusgudagusbodanulius" ordered="false" eType="//EunulaufriNulAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaunulaubiFrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubegusdaBogugusnulauBiTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabeFribeDabibinulEs" upperBound="-1" eType="//EunulaufriNulAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobunulaufribunulaubenulaugusGuscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauDaguBegubogufriDaEs" instanceTypeName="typeBagugusBoBeBedagugusbinulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebobudafrinulauBegusbodafriTor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugugusBubobeBoGusfrifrigugunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusFrinulaugusNulauBibuBibolius" ordered="false" upperBound="-1" eType="//BebobudafrinulauBegusbodafriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Babobobifribobodaes" eSuperTypes="//AlaunulauGuboFriBebeBiBelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubeDaNulaubebuGusbuBelus" ordered="false" upperBound="-1" eType="//EunulaufriNulAulus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alnulaugusBiBinulAutin" eType="//AGusgufrigudanulAuBenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGubugusGusBegusbunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBigusbibeBulius" upperBound="-1" eType="//BebobudafrinulauBegusbodafriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBoNulauBubifribiBigues" eSuperTypes="//BigusdaFribocus //DoGubugusGusBegusbunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubifrigusbiboBiCus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubodaNulauBedacio" eType="//AlaunulauGuboFriBebeBiBelius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBubibiGusBuBobeNulauguCus" ordered="false" upperBound="-1" eType="//DanulaunulaubiFrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiBibeguGusdabigunulaubidaBoNulius" eSuperTypes="//BaGusbugubifries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibofriBeNulAuDabuLus" ordered="false" eType="//DoNulaubegusBuGusnus" eOpposite="//DoNulaubegusBuGusnus/dibiNulAudaFridaNulaubeboes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebinulaubeBuBogusbuBoBitor" ordered="false" eType="//FaBodaTus" eOpposite="//FaBodaTus/eguFribibegubigufrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufriguFriBubobeGusaubeBiBitor" eSuperTypes="//DiBoNulauBubifribiBigues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baboNulaubiNulaugustor" eType="//AGusgufrigudanulAuBenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dudagusbobigusfrilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auboTus" eType="//AGusgufrigudanulAuBenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlFriFribibeCus" abstract="true" eSuperTypes="//DobunulaufribunulaubenulaugusGuscus //DugugusBubobeBoGusfrifrigugunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dadanulaubugusfribotor" eSuperTypes="//BaGubunulAubeDanulAubecio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebonulauNulaubiboLius" instanceTypeName="typeAnBidagutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibofrinulauGufribibeNulAunus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubuFriEs" ordered="false" upperBound="-1" eType="//BaGubunulAubeDanulAubecio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aNulaubebuFriDaBotor" ordered="false" upperBound="-1" eType="//BaGubunulAubeDanulAubecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBoGusgusbiDabonulaububufrifriBitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubuBoBobinulauCus" eType="//AGusgufrigudanulAuBenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulAuNulAuBoBibudabodabiTus" eSuperTypes="//DanulaunulaubiFrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digudanulaufrifridacus" ordered="false" eType="//BaBoGusgusbiDabonulaububufrifriBitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBidagusbunus" instanceTypeName="typeDigusAufriBibigubebiGusboguscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DigusnulAugusDaGusfribobibobocio" instanceTypeName="typeDonulaunulAuBugunulautin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AldafrifriBugusnulius">
    <eLiterals name="EubugusbubodaBogusBulius"/>
    <eLiterals name="BibibifriDaboGuses"/>
    <eLiterals name="DabifriDabuDabuCio"/>
    <eLiterals name="AldagusbufriGunulautor"/>
    <eLiterals name="DuBububeBoBibeGuFriNulautor"/>
    <eLiterals name="BebifribegubegusNulAuGudabobiBogusdaboes"/>
    <eLiterals name="DubiBidanulaudacus"/>
    <eLiterals name="DaGubeNulaububobobeBenulAubues"/>
    <eLiterals name="DaguFriGugusfribobogusFriNulautin"/>
    <eLiterals name="BifribubegufriLius"/>
    <eLiterals name="Fagugusbodacio"/>
    <eLiterals name="DabobeboGusbiGudadabenulAuGuguboCus"/>
    <eLiterals name="EuFribiGusaugusBebifries"/>
    <eLiterals name="BiNulAugucus"/>
    <eLiterals name="BigusbegusdaDagusNulAufriDacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eubobobubobibidalius" eSuperTypes="//Babobobifribobodaes //Dudagusbobigusfrilius //AlbiBibeguGusdabigunulaubidaBoNulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnBugusbedaGusgusgubigusgusgucio" instanceTypeName="typeEbububobugusBugutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubufribibeFriguButin" eSuperTypes="//Babobobifribobodaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaubebiGusGuBifrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbugusGubues" eSuperTypes="//BigusdaFribocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaubudaBobogusdabiGucus" ordered="false" upperBound="-1" eType="//BigusdaFribocus" eOpposite="//BigusdaFribocus/dibugusgubuBibiboGusbiBubetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubugubudabunulaunulAubucio" eSuperTypes="//DiNulAuNulAuBoBibudabodabiTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AgunulauGubebufridaDanulaudagudabelius" instanceTypeName="typeAuFribufriFrinulAuDafrinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anbibobogusgusbinulius" abstract="true" eSuperTypes="//DiBoNulauBubifribiBigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebebeButin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albiBogusauguBebubeBeguboBetus" upperBound="-1" eType="//DufriguFriBubobeGusaubeBiBitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeguNulaugusbobedaLus" abstract="true" eSuperTypes="//AudafribigusfridadanulauBucio //EubufribibeFriguButin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDabeDabigusfries" ordered="false" eType="//Eubobobubobibidalius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulAunulAugusBonus" upperBound="-1" eType="//DubifrigusbiboBiCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ADanulauGusguNulAuNulAuTor" instanceTypeName="typeDiboguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeboFriguscio" eSuperTypes="//BebobudafrinulauBegusbodafriTor //DubifrigusbiboBiCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daguBonulauBedaBobuTus" ordered="false" eType="//Babobobifribobodaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubinulauNulauboDaguBuGuses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBebuDaCio" ordered="false" upperBound="-1" eType="//DufriguFriBubobeGusaubeBiBitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudanulauBiBogusBoGubuEs" eSuperTypes="//BaGubunulAubeDanulAubecio //Dudagusbobigusfrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algusbegufrifribofriNules" ordered="false" upperBound="-1" eType="//AnnulAuBoBeBegusbonulAuboNus" eOpposite="//AnnulAuBoBeBegusbonulAuboNus/fabeGusboGusgusBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusNulauGubugusbebuboBedadadagutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Begufribibobebudaguscus" instanceTypeName="typeDugusNulAugusBonulauBoboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlauBigusFriNulaulus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EnulAugusBetor">
    <eLiterals name="BadagusBotus"/>
    <eLiterals name="BeDafriGusgusBonulauLius"/>
    <eLiterals name="EudabiBuNulaubiBodafribibuGusbobulius"/>
    <eLiterals name="AbegusAudafriNulauBigusaufribeBeLius"/>
    <eLiterals name="DifriGusFrigusBoGusgusbies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusboDabuDaDanules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabiBibidaBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbonulaugusNulaubufriguboes" abstract="true" eSuperTypes="//AudafribigusfridadanulauBucio //AlFriFribibeCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faDadanulauFriBebebobolus" ordered="false" upperBound="-1" eType="//Babobobifribobodaes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braububedabeGues" ordered="false" eType="//DabibebugufrigugubobebeBeLius" eOpposite="//DabibebugufrigugubobebeBeLius/braudanulaufribiBugugusdacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubofridaNulaubebudaGusnus" eSuperTypes="//FabiBibidaBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubofriNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebigusDagusgusTor" eSuperTypes="//AudafribigusfridadanulauBucio //Anbibobogusgusbinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fanulautus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="difridafrigutus" upperBound="-1" eType="//DubinulauNulauboDaguBuGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuBeBiboGugugusfriboCus">
    <eLiterals name="DinulaubeBoBeboBegusbotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBefrinulAugubofridagudabebobiBuFriLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EfridaDabibubeLius">
    <eLiterals name="AlFriBeBuGusaulus"/>
    <eLiterals name="Babifribobofridabinulautus"/>
    <eLiterals name="BrAunulauBiGusBebufriBedabefribedaTin"/>
    <eLiterals name="BifribiNulAubiTor"/>
    <eLiterals name="DunulaugubeBiGusbobuBuBuEs"/>
    <eLiterals name="AnulaubefribenulauguboBodaboCus"/>
    <eLiterals name="AuBiFridanulAubinulaucus"/>
    <eLiterals name="AuGusgusBulus"/>
    <eLiterals name="DonulAufriBudafrigusNulaudabinules"/>
    <eLiterals name="BafrigubiEs"/>
    <eLiterals name="DubeguDabeBedaDatin"/>
    <eLiterals name="Digubogusbubobugusgutor"/>
    <eLiterals name="Dinulaubigutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibeNulaububedagubees" eSuperTypes="//DufriguFriBubobeGusaubeBiBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braugugudafribenulaubogulus" eSuperTypes="//BaBoGusgusbiDabonulaububufrifriBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuBebuFribiGusAudaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulAuBiBugusnulAuGusfriTor" ordered="false" eType="//BadanulAuBubofriGusNulaugusbuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BiBofriguBobebofriGuscio">
    <eLiterals name="EFrifribebububeguNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudabidabebebobinulauDaBufricus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulaubegusBuGusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibiNulAudaFridaNulaubeboes" upperBound="-1" eType="//AlbiBibeguGusdabigunulaubidaBoNulius" eOpposite="//AlbiBibeguGusdabigunulaubidaBoNulius/bibofriBeNulAuDabuLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aDabudaGubodabuBibobeDagutus" eType="//DugusboDabuDaDanules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuboGuslus" eSuperTypes="//BrAubofriNulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugusbebugusBigusgufriNulAubidabotus" instanceTypeName="typeDufribenulaubibibifritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbugusfrifriBecio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAuBoBeBegusbonulAuboNus" eSuperTypes="//Eubobobubobibidalius //DiGusNulauGubugusbebuboBedadadagutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabeGusboGusgusBilus" ordered="false" upperBound="-1" eType="//EudanulauBiBogusBoGubuEs" eOpposite="//EudanulauBiBogusBoGubuEs/algusbegufrifribofriNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DaBoFribegusAubetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabodaBogusGusBudabuguFribeNus" eSuperTypes="//DufriguFriBubobeGusaubeBiBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGugusgubuguboBiDaGuBiguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusBiboGusBedabidaNulAuGuscus" eType="//DanulaunulaubiFrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubidabiBegusgusTus" instanceTypeName="typeAlGusDanulaunulAuDaBuboNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DofriboBibunus" instanceTypeName="typeDubibogusauGuGuscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EububobibebigubeBibiBibinus" instanceTypeName="typeAlaufridabenulaubonulauNulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuBuBedaBobuFriFries" abstract="true" eSuperTypes="//EudanulauBiBogusBoGubuEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnnulaubidaBucio" instanceTypeName="typeDiBobidabebobeguFriBenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadafriBibiFrigusgusfrigucio" eSuperTypes="//AunulaubebiGusGuBifrinulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBenules" eType="//DaBoFribegusAubetus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbebuNulauguBububitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiFrigusgustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabonulauBebugudaFributin" eType="//DubugubudabunulaunulAubucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Albufribogubufrinulius" eSuperTypes="//DiNulAuNulAuBoBibudabodabiTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulauGusdabuBinulAubutus" ordered="false" eType="//Fanulautus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBuTus" ordered="false" upperBound="-1" eType="//EuDafrigusbuguDaLus" eOpposite="//EuDafrigusbuguDaLus/alBubodaGusDabobigusfriguBubiTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dobunulaubigugubebunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baGusdaFribebebifriTin" eType="//DigusnulAugusDaGusfribobibobocio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriFriNulaufriGunulaugusfrinus" eSuperTypes="//EubebebeButin //AlauBigusFriNulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babigusFribobubebilus" upperBound="-1" eType="//BrAuboGuslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauFribogugusgubiBotus" eSuperTypes="//Dobunulaubigugubebunus //DubugubudabunulaunulAubucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anBoGubinulaudaBocus" eType="//DidaguDabenulAubudabobeBinus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaBunulAuBofriBobobugufrinulius" ordered="false" eType="//DubifrigusbiboBiCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eugues" abstract="true" eSuperTypes="//BadanulAuBubofriGusNulaugusbuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauFridacio" ordered="false" eType="//DoBoNulaubuBoguscio" eOpposite="//DoBoNulaubuBoguscio/diboboNulAunulaunulaubiDaGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EBoBebufribobubebeLus">
    <eLiterals name="EubufribofriNulAuNus"/>
    <eLiterals name="AnauGuBebuBoNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaguFriGusbibeGusnus" instanceTypeName="typeBraunulauboEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeDaBifridabeBugusbenulaufrigusBugusboGutus" eSuperTypes="//AudafribigusfridadanulauBucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AububinulauGuboBibobibolius" instanceTypeName="typeDubuNulauNulaubonulaudacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBegusboBunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaGusbenulauboBinulIus" instanceTypeName="typeDofribobuGusNulauLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubodadaNulAuBigusAuTin" instanceTypeName="typeABoNulAuGusBogusbitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubobeFribeGusaubiBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudadabofriBobibolus" ordered="false" eType="//EunulaufriNulAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodabeboBefriboBuBuBuBeCus" eSuperTypes="//AlFriFribibeCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobefriFridaTus" upperBound="-1" eType="//AudafribigusfridadanulauBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DudabonulAuFribuBotor" instanceTypeName="typeDubiBeGuNulauBetor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuGusauBiBudabenulaudaguBeguLius" instanceTypeName="typeAlbiGuBoGusbiNulAufriNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DabifribuNulauBeBocus">
    <eLiterals name="AlaudabofrigusnulauButor"/>
    <eLiterals name="Bagusdafribugunulaucio"/>
    <eLiterals name="AuBigunulaubunulAububunus"/>
    <eLiterals name="EubibiBoGuDabonules"/>
    <eLiterals name="EuGuboBinulauBefritor"/>
    <eLiterals name="BrAubeDagusguguguFriBubocio"/>
    <eLiterals name="AnfriGusbunulaugusGusbebuNus"/>
    <eLiterals name="DobodaDafrinules"/>
    <eLiterals name="BagusGunulauDanulauBubibibetus"/>
    <eLiterals name="EuBuNulaubobies"/>
    <eLiterals name="AnbebibibuFrigusBiGusGuGusnules"/>
    <eLiterals name="BiNulAuBobebodatin"/>
    <eLiterals name="DiGusBuBubebibedabees"/>
    <eLiterals name="EubiBoguGubebebubeNules"/>
    <eLiterals name="DaDaboBebuNulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusaubonulauBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusgusauBububebucio" ordered="false" upperBound="-1" eType="//EubebebeButin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugunulAunulaulius" eType="//Begufribibobebudaguscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Da" eSuperTypes="//BaGubunulAubeDanulAubecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugubunulAuFriBocio" eSuperTypes="//EbonulaugusNulaubufriguboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbobebigusnulauFriFribidacio" eSuperTypes="//DubifrigusbiboBiCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abuGusgusaugusguTus" eType="//DoGubugusGusBegusbunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBubefribedaBiGuGunulAuFribulus" eSuperTypes="//BaGubunulAubeDanulAubecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bitor" eType="//DudabonulAuFribuBotor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBunulauTor" eSuperTypes="//EudanulauBiBogusBoGubuEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="an" eType="//DofriboBibunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusFriFriBubelus" eType="//AldafrifriBugusnulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Duboguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBodaTus" abstract="true" eSuperTypes="//BaBoGusgusbiDabonulaububufrifriBitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguFribibegubigufrilius" ordered="false" upperBound="-1" eType="//AlbiBibeguGusdabigunulaubidaBoNulius" eOpposite="//AlbiBibeguGusdabigunulaubidaBoNulius/bebinulaubeBuBogusbuBoBitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dodafriDabinulauboLius" upperBound="-1" eType="//BabidaBebiNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EdaBogusbofridabegubiGucio" instanceTypeName="typeBabudaboFrigucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubiDaNulauBebiGuslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauDabeGububibubuDabitor" ordered="false" upperBound="-1" eType="//BibeNulaububedagubees"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubiNulaufriboTor" ordered="false" eType="//BabidaBebiNulEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfriNulaububebotor" eType="//FaGusbenulauboBinulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubiBoNulaufriguBolius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuNulaubonulaudanus" ordered="false" upperBound="-1" eType="//AlbuBuBedaBobuFriFries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulAubeDagusGusGustin" ordered="false" upperBound="-1" eType="//DoGuBegusnulaubibilus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eufribudabuBogunulaufrinulEs" eType="//BrauDaguBegubogufriDaEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabibiNulius" eType="//BrauDaguBegubogufriDaEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebibodadadabuFritor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabebiGusBuFridabububobotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auFriboBobutin" eType="//Begufribibobebudaguscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnulAubegusTus">
    <eLiterals name="EuNulaufriGubiGuguBeguBoboBiTor"/>
    <eLiterals name="AnFrifriDaGusaucio"/>
    <eLiterals name="EuguBiGusgusgububidaNus"/>
    <eLiterals name="AGuTin"/>
    <eLiterals name="DabobuBoDagusguTin"/>
    <eLiterals name="BibebuGuBuGuNulaubebocus"/>
    <eLiterals name="DogusBoNulaubububigucio"/>
    <eLiterals name="AunulauDaGusBonulaugubunus"/>
    <eLiterals name="AnbuGusbifriBobulus"/>
    <eLiterals name="DaBiGugugubobifriDadanulAulius"/>
    <eLiterals name="BinulauBibobeBububonulius"/>
    <eLiterals name="AubinulAugugustor"/>
    <eLiterals name="ENulauGusGusAubugunulaunus"/>
    <eLiterals name="DuFribubifribuBenules"/>
    <eLiterals name="DibeDagusbuNulius"/>
    <eLiterals name="AnnulAugusnulaubebeDaBoFriFribibefriFriButor"/>
    <eLiterals name="DodaNulaudabeGuGuBobobuNus"/>
    <eLiterals name="BagusboguBoGusguButin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBibibinulAuGugusCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beguguBoFribilus" ordered="false" upperBound="-1" eType="//AlbobebigusnulauFriFribidacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibefrifrigusbebubeBogusbidadabugusBuLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="didabiBodabibebiFritin" eType="//DaBoFribegusAubetus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doboNulauFriBoBofrigucus" ordered="false" upperBound="-1" eType="//Eubobobubobibidalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbibugubuBuBubiDaBodagusdaCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auDaDagubebebonulAuBiguslus" eType="//AgunulauGubebufridaDanulaudagudabelius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaunulauGusbeBubonulius" eType="//BrAubofriNulEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBoboGusbebigusgubelus" eType="//FaguFriGusbibeGusnus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusgusFriNulaufriBiBefrinules" instanceTypeName="typeDuGusBoTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BibiDabodabuCio" instanceTypeName="typeAGunulaunulauBeBegucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubibuBeBobobuBebububinules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aGuDabubutus" eType="//DigusnulAugusDaGusfribobibobocio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusauFriGudagusbeBicio" eSuperTypes="//DabebiGusBuFridabububobotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abobedaBuboBicus" ordered="false" upperBound="-1" eType="//DiBoNulauBubifribiBigues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubiBugufrigusgusguslus" eType="//AuBidagusbunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusgusbedagusAugufriCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibeBegusIus" eType="//AGusgufrigudanulAuBenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabibibibufrifriTin" abstract="true" eSuperTypes="//AugusauFriGudagusbeBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifrinulAuBobegunulaudabibibies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angunulaufrinulaudaBoguEs" eType="//DiFribifrinulAubibegusguBelus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fadabidagugusbonules" eType="//EBoBebufribobubebeLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubenulaububudafrigubunulAulus" eSuperTypes="//DanulaunulaubiFrilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeFriGusBoBegusauboNulaulius" instanceTypeName="typeFabodaBigubugusbebolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAuDabocio" eSuperTypes="//BeguNulaugusbobedaLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusdaFrigusNulauboLus" ordered="false" eType="//AlbugusfrifriBecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AGuBigusBiNulauGufrigusBues" instanceTypeName="typeEunulauFrigubibenules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaNulauGufrinulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebibedaNulaunulaubedaNulautor" eSuperTypes="//AbibugubuBuBubiDaBodagusdaCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaubobibebiFridacio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofriguguNulAubunulAuGusnulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigubibiFribugubetin" eType="//EBoBebufribobubebeLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulAunulAuNulEs" ordered="false" upperBound="-1" eType="//Dadanulaubugusfribotor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubuFrigusaugubiBiCus" ordered="false" upperBound="-1" eType="//AlbobebigusnulauFriFribidacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriDaDaGubuBiBigustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaBobogugufridalus" ordered="false" eType="//BabidaBebiNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DigusGusgusBigugugubugusbonus">
    <eLiterals name="FaBuNulaufriFriBedagufrigusgubeBues"/>
    <eLiterals name="AlnulAugudagusnulaunulAugufricus"/>
    <eLiterals name="AuBebenulaubeBogubunulius"/>
    <eLiterals name="Anfrigugusbetus"/>
    <eLiterals name="BibofrinulAuBoguguGubocus"/>
    <eLiterals name="AnDadabegusdabeDaBegusdaDanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBugubeBifrigubiBuTor" eSuperTypes="//Da"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobeBuguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBufribigufriFricio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafribibiGufriBodacio" ordered="false" eType="//BaGusdafrifribubeBoboGugubetin" eOpposite="//BaGusdafrifribubeBoboGugubetin/dunulaunulaugusauNulaubuBugusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBegubenules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EugugufrifribiguBibues" instanceTypeName="typeFanulAunulAugusbutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulauGubiFriboboBebinus" eSuperTypes="//DugugusBubobeBoGusfrifrigugunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobobidafridagubedaGusgusboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGugusfrigufrinulIus" ordered="false" eType="//DiNulAuNulAuBoBibudabodabiTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBofriGubenulauGudadabugudanus" ordered="false" eType="//AlbobebigusnulauFriFribidacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaboBiBeBiGusbugusdabubofrigusNules" abstract="true" eSuperTypes="//BaGubunulAubeDanulAubecio //EubufribibeFriguButin //DobeBuguslus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibodabunulaulius" eType="//DofriboBibunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaugusGubufrifrinulaufrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBoGubibiFridabuLus" eSuperTypes="//AnnulAuBoBeBegusbonulAuboNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abicus" eType="//AGuBigusBiNulauGufrigusBues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DagusbofrinulauboGucio">
    <eLiterals name="AlbiboNulAubububibuNulauDagues"/>
    <eLiterals name="BeguBoBegudaNulaugues"/>
    <eLiterals name="DonulAudaBigusfriBulius"/>
    <eLiterals name="AbebobubibebiGusguFriTor"/>
    <eLiterals name="FadabifriNulius"/>
    <eLiterals name="DobeguguNulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusguGuBiBiguscio" eSuperTypes="//BrAuboGuslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBobeBeboBeGusaudabucus" ordered="false" eType="//EugubunulAuFriBocio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBugusbuNulAuguguNulAubenus" ordered="false" eType="//DobunulaufribunulaubenulaugusGuscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaLius" instanceTypeName="typeDudadagusBedaButin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusnulAububeGuDalus" abstract="true" eSuperTypes="//EugubunulAuFriBocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBiboguFriBebonulaunulaunulAubeBotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFribiFrinulaunulAubuGuGugufritus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EFriguGusFrigubiBotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agubuNulaunulauBoFritor" eType="//AuGusauBiBudabenulaudaguBeguLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbegubebuboTin" eSuperTypes="//AbugusGubues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusBobiNulIus" eType="//Begufribibobebudaguscus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauNulAunulaugusGusNus" upperBound="-1" eType="//AlbuBuBedaBobuFriFries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbeboDaGuguGuscio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibebibenulAuboNulaudadacio" ordered="false" eType="//DubibuBeBobobuBebububinules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabeGusbunulaubobebofrigunulautin" eSuperTypes="//AnnulAuBoBeBegusbonulAuboNus //AudafribigusfridadanulauBucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidagusbuFrinulaugusauDadaBecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugubobeguBiboFribugusBebigunulius" eSuperTypes="//AudabidabebebobinulauDaBufricus //Babobobifribobodaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubobebubeBifriBuBubibodanulius" abstract="true" eSuperTypes="//DobiBedaGusauBugusbibucio //BeguNulaugusbobedaLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibubiBofribonulIus" eType="//AuBidagusbunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBiNulaubofriGuslus" abstract="true" eSuperTypes="//DabebiGusBuFridabububobotin //AlbiFrigusgustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbugusbenulAuGubobebenulauDaEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babibegudadabifriTus" ordered="false" eType="//DibuBebuFribiGusAudaes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulauFridabogusfribigudacus" eType="//DofriboBibunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugudaGusdaboFrinulius" abstract="true" eSuperTypes="//BrAubofriNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBoBeBebiBobonus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Dugubidafribucus">
    <eLiterals name="BagusaugusfribeDator"/>
    <eLiterals name="Dubebecus"/>
    <eLiterals name="DoGuguBebeBuBiGusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusdafrifribubeBoboGugubetin" abstract="true" eSuperTypes="//DofriguguNulAubunulAuGusnulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anautor" eType="//ADanulauGusguNulAuNulAuTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBogusFrigugusbegudabecus" eType="//FaLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulaunulaugusauNulaubuBugusius" ordered="false" upperBound="-1" eType="//BiBufribigufriFricio" eOpposite="//BiBufribigufriFricio/fafribibiGufriBodacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlaugusbinulaudanulauBecio" eSuperTypes="//DoGubugusGusBegusbunules //DaBiNulaubofriGuslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befriguBiNulaufrinus" ordered="false" eType="//FabeGusbunulaubobebofrigunulautin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulaubenulAugudaNulauCio" ordered="false" upperBound="-1" eType="//Eubobobubobibidalius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daDaBoBobenulAubedagunus" ordered="false" upperBound="-1" eType="//EubebebeButin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbenulauGusbefributor" abstract="true" eSuperTypes="//DubugubudabunulaunulAubucio //FaGugusgubuguboBiDaGuBiguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudabigusnulauguDabiBudalus" eType="//DobunulaufribunulaubenulaugusGuscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedaFrigubidabebibetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebobedaboBibinulautin" upperBound="-1" eType="//DanulaubobibebiFridacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibedaBugufribeGusdalius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusNulAuDaGusdabeFribubuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doNulaufrifrigugugues" ordered="false" eType="//AlauBigusFriNulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBoNulaubuBoguscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diboboNulAunulaunulaubiDaGulius" upperBound="-1" eType="//Eugues" eOpposite="//Eugues/brauFridacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusaugusBubogusdadanulauTin" eSuperTypes="//BiBufribigufriFricio //AlbegubebuboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubebebogusbibodaguDaGusboBoes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBeGubofriDaCus" eType="//DigusGusgusBigugugubugusbonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubugusbeBigusbudagugusCio" eSuperTypes="//BrAubofriNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBuGusbibobiBuDagusnulaubocio" abstract="true" eSuperTypes="//AlFriFribibeCus //BraugusguGuBiBiguscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubobuBugubiBugubeFridadalus" ordered="false" upperBound="-1" eType="//AlbiFrigusgustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusfribobobiboNulaucio" eSuperTypes="//Eugues //EuGusaubonulauBonus //BrAubobeFribeGusaubiBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbebubibeGusius" abstract="true" eSuperTypes="//BibeNulaububedagubees">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annulAufriTin" eType="//Begufribibobebudaguscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabibebugufrigugubobebeBeLius" eSuperTypes="//Dudagusbobigusfrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudanulaufribiBugugusdacio" ordered="false" upperBound="-1" eType="//EbonulaugusNulaubufriguboes" eOpposite="//EbonulaugusNulaubufriguboes/braububedabeGues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doBebonulaufriguBububugutor" eType="//AGuBigusBiNulauGufrigusBues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubobiBegusbebenulIus" instanceTypeName="typeBeDagusdanulaufriBoBodatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBifribubebogusgubuguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudaNulAunulaubefridatin" eSuperTypes="//FabodaBogusGusBudabuguFribeNus //AlbuBuBedaBobuFriFries //Braugugudafribenulaubogulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGuGusBifrigusnus" ordered="false" eType="//BaGusbugubifries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeDafrigusaubetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aububetor" eType="//EBoBebufribobubebeLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfriGubeBiFrifrigusNulauLus" eSuperTypes="//Fanulautus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubufribeGusguBuTor" instanceTypeName="typeBebeBiBudaGusbobutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBebiGuBuBobigusbigues" eSuperTypes="//AudafribigusfridadanulauBucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusbufriBuGusdaFrigusNulauDadaes" eSuperTypes="//DiBoNulauBubifribiBigues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBeguBubebifriBugusbugubogulius" ordered="false" upperBound="-1" eType="//AlbugusfrifriBecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabuGuBeGustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGugusaugusbuguboBuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuBobidaboNulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagusgusgusGuGuBiCus" instanceTypeName="typeBraubiboBugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubinulauBebubebeGuBobuBonulaudaes" eSuperTypes="//Dadanulaubugusfribotor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBiboBeFrigusguNulAugubifribinulaugues" upperBound="-1" eType="//AubugusbeBigusbudagugusCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dubinulaudalius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGubunulAuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuguNulAuBibegubudaNus" eSuperTypes="//DabibibibufrifriTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusbobibobobuFriGuNulauBoboGusfribiBubees"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidabogububiboGubiGuscus" abstract="true" eSuperTypes="//DodabeboBefriboBuBuBuBeCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaunulaufrifriGusbigusNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubobebobefriDaBefriNules" eType="//FadafriBibiFrigusgusfrigucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafribifriGusfrinulAudaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGubedagusbeBuFribobugudafries" abstract="true" eSuperTypes="//AlbiFrigusgustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBogusbofrigubunus" ordered="false" eType="//BibefrifrigusbebubeBogusbidadabugusBuLus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibigusBedaBogugusbifribiboDaTor" eType="//DigusGusgusBigugugubugusbonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGubebifrigugubeTor" eSuperTypes="//AlbugusfrifriBecio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabuGusbonulaudaDaguEs" eType="//DigusGusgusBigugugubugusbonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DobobiguguEs" instanceTypeName="typeDugusGubidagugusnulAuDadatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusbeBegusbegusboEs" abstract="true" eSuperTypes="//BrAubobeFribeGusaubiBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauFriBuFribobinulauTin" ordered="false" upperBound="-1" eType="//AlbiBibeguGusdabigunulaubidaBoNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgubeNulaunulaubues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigudabebobiBuguNulAugugusfrilus" eSuperTypes="//AnaubebebogusbibodaguDaGusboBoes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difriDaDabeguNulAuLius" eType="//ADanulauGusguNulAuNulAuTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGusAubuBebuNulaugusNulauNulius" eSuperTypes="//EubenulaububudafrigubunulAulus //BebobudafrinulauBegusbodafriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agubebiBobebefribunus" ordered="false" eType="//AlGusbeBegusbegusboEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuDafrigusbuguDaLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBubodaGusDabobigusfriguBubiTor" eType="//Albufribogubufrinulius" eOpposite="//Albufribogubufrinulius/baBuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigudabeGufriBobufritin" eSuperTypes="//EubufribibeFriguButin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobuboGugusdaGuBuBibibibefrilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augubonulAuBeBedaCio" eType="//EububobibebigubeBibiBibinus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogunulAuguboGusNulEs" eType="//DoguTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaDagufribedabotus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAubelius">
    <eLiterals name="EbegubofrifriBoGudaBibibunulaubutus"/>
    <eLiterals name="AugusgusNulauguGusbulius"/>
    <eLiterals name="EFriGunulaugunulauGubonulaunus"/>
    <eLiterals name="BaguFribebunulauboguscus"/>
    <eLiterals name="Dunulaubuguses"/>
    <eLiterals name="BinulaudaGusboguNulAuCio"/>
    <eLiterals name="DabonulAugusBidafribecio"/>
    <eLiterals name="Abunulaubibitor"/>
    <eLiterals name="AgusnulaufriGuBufribiCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BigugusbuBegusguGutor">
    <eLiterals name="AlFrigusnulauDagusfrilius"/>
    <eLiterals name="AlbuGusbigusAuBebuFrifrifries"/>
    <eLiterals name="FabegugusdagusAuGulius"/>
    <eLiterals name="DuGuBonulAugusAuNulaudaGuGuTor"/>
    <eLiterals name="EuDaguGusbeBudagusgusbiBiFricio"/>
    <eLiterals name="AngubufriboBetus"/>
    <eLiterals name="DadabenulaunulaugusgusBenulauboDaTus"/>
    <eLiterals name="BeBofritin"/>
    <eLiterals name="EunulAugusfribuboBeLius"/>
    <eLiterals name="DabibiBofriBebulus"/>
    <eLiterals name="DigugusAubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AguguBoNulaubebunulaubitus">
    <eLiterals name="DibeBedabegusbenulaunulAubitus"/>
    <eLiterals name="BraubefriNulaubeNus"/>
    <eLiterals name="BabodaNulauGusbubotor"/>
    <eLiterals name="BibunulauguGusgulus"/>
    <eLiterals name="AlbiBodagusbebeNules"/>
    <eLiterals name="DofrinulaubiNules"/>
    <eLiterals name="BebuBegusbubinulaudadabigugusbubuLus"/>
    <eLiterals name="BrAunulaucio"/>
    <eLiterals name="BafriNulaubiBogugugusbonus"/>
    <eLiterals name="EBeBobogusbidanulauBuCus"/>
    <eLiterals name="EuGusAuBunulaufribonulaubuNulaunulEs"/>
    <eLiterals name="FaBiBobiGusfriBobicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidaboDadadaGugusbibebilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didabufribigusauguGusgutor" ordered="false" eType="//DuBubefribedaBiGuGunulAuFribulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBonulAugusGuBegunus" eSuperTypes="//DibuBobidaboNulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAuBobuGusaucio" ordered="false" upperBound="-1" eType="//AlbegubebuboTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AugudafriBeBenulaulus" instanceTypeName="typeFafribofribobiNulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AFribuBofriBiBuBunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusnulaububiTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraububeNulAuboBiBiTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fafribidabelus" eType="//EubodadaNulAuBigusAuTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBuBodaDabeDalus" abstract="true" eSuperTypes="//EubenulaububudafrigubunulAulus //AnGubebifrigugubeTor //DoGubugusGusBegusbunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabiGuBegusnulaunulaubibefriboCio" ordered="false" upperBound="-1" eType="//DofriguguNulAubunulAuGusnulIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobifrinulauBubiGusAunulaufriBecio" eType="//AlaugusbinulaudanulauBecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusbobofriGusbubinulaulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGunulaubugusdanulAugubegues" eSuperTypes="//FabodaBogusGusBudabuguFribeNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibudagugusbogutin" eType="//DobobiguguEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DadabeBubigusdabebelius" eSuperTypes="//AudabidabebebobinulauDaBufricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbiFribogusfribies" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfrigusgugusBogubofricio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ecus" eType="//AugudafriBeBenulaulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euguFribeGugusnulAuTin" eType="//AuBeBiboGugugusfriboCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBeGuDaGusbidaGudaguNulauLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diguGusbebuboGustus" ordered="false" upperBound="-1" eType="//BaGubunulAubeDanulAubecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlAuNulaufriGusfrinulauDanus" abstract="true" eSuperTypes="//DiGugusaugusbuguboBuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldafribobofriGugubibenulauLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGusbebefriGusboBiBoBofrigusaugunulauDaBiLius" eType="//Dudagusbobigusfrilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulauBobegulius" ordered="false" eType="//Dudagusbobigusfrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Digudabogusgulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBedabudagusbebegusbiTor" eSuperTypes="//FadafriBibiFrigusgusfrigucio //AudafribigusfridadanulauBucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baCio" eType="//DiFribifrinulAubibegusguBelus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albebinulaubuBelus" eType="//AnnulaubidaBucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeNulAuguFrifrigusbuGuBubegusDaLus" instanceTypeName="typeDubobiDanulauBuGucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegunulaugunulaubibiDabocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBoGusnulauguNulaugufriGulius" ordered="false" eType="//AldafribobofriGugubibenulauLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnulaubogusGuBiCus" instanceTypeName="typeEubogusguBeBeBilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Fafribudagusgusius" instanceTypeName="typeAudaNulaunulaubeBuNulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubibuBegusdanulIus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baNulaunulaubuFribecus" ordered="false" eType="//DodabeboBefriboBuBuBuBeCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubegubedabiGuCus" abstract="true" eSuperTypes="//EfrigusgugusBogubofricio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EGugusnulaunulius" instanceTypeName="typeBigusdanulaufribibigusTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FadaGudadaguGusfrinulAubobiBodacio" instanceTypeName="typeAdaNulaufrigusbofrigusfricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBifrigubobobebees" eSuperTypes="//DobobidafridagubedaGusgusboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuBiNules" eType="//DabifribuNulauBeBocus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBeBogusnulaunulaudadatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuFrifrifridabibigubutus" eSuperTypes="//BaboBiBeBiGusbugusdabubofrigusNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaugusGusaubebebelius" eType="//EuGusgusbedagusAugufriCio"/>
  </eClassifiers>
</ecore:EPackage>
