<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="difribudacio" nsURI="http://hub.de/rcore/examples/difribudacio" nsPrefix="sFXM">
  <eClassifiers xsi:type="ecore:EClass" name="AldaGusgunulauNulaubeGusbutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagunulaugusdagusBubobulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobobigusfribidaGusdalus" ordered="false" upperBound="-1" eType="//AldaGusgunulauNulaubeGusbutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubogusBonulaugusnulAuguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaufriguLius" eSuperTypes="//AubogusBonulaugusnulAuguCio //AldaGusgunulauNulaubeGusbutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusgusbubibogusboGusbees" eSuperTypes="//AubogusBonulaugusnulAuguCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DadanulAuGubuGubobuGuFriBetin">
    <eLiterals name="AlguboGudagusNulaubuBobies"/>
    <eLiterals name="FaFrifrinulaugufribocus"/>
    <eLiterals name="AnaubebobidaGusbubogusboNus"/>
    <eLiterals name="BabinulAuBetor"/>
    <eLiterals name="EbofribebiDadaBiguboBuNulaugustin"/>
    <eLiterals name="DoGubobebeguGusgusfrinus"/>
    <eLiterals name="AnGusGusgusaugusbeGusguDagutor"/>
    <eLiterals name="BebogufriBogusauButus"/>
    <eLiterals name="ENulaufriBoFribofriguBofrigunus"/>
    <eLiterals name="AdaNulAubidanulAugusauFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EudabubebidafriTor" instanceTypeName="typeBibiBubebonulaugusbelius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubigusBobiBebenulAuNulius" instanceTypeName="typeDidagubofriguboBobeNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeBubugubobogudaNulAuNulEs" instanceTypeName="typeABubiBeDabenulAuBonus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BebunulAuFrinulAunulAulus">
    <eLiterals name="DinulauBeboguBedabetor"/>
    <eLiterals name="BaGusbiGudabibuCus"/>
    <eLiterals name="BiguguboDabobeBegunulaubobeTus"/>
    <eLiterals name="DaNulauboNulaugubofriDanulAufribies"/>
    <eLiterals name="DiBubefridaboBodafriguGusfriCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFriNulaugusguNulaubiBefrinulautus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogugusfriBidafriguEs" eType="//EubigusBobiBebenulAuNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BeGusAuDagudafriBiTin">
    <eLiterals name="AnulAugubigufribiGulius"/>
    <eLiterals name="BeboBubuguGusgubuGusfrigucus"/>
    <eLiterals name="Aufries"/>
    <eLiterals name="FanulaubifriDafridabeBuGusTor"/>
    <eLiterals name="BigusbuBibubees"/>
    <eLiterals name="DabebenulauGubugusaulus"/>
    <eLiterals name="BabibenulAufrinulIus"/>
    <eLiterals name="AnnulaugusnulauGuboBucus"/>
    <eLiterals name="Efridabebegusgugusnulius"/>
    <eLiterals name="BigusbodaGusEs"/>
    <eLiterals name="BeGusdabiboDaBoBunulAuTin"/>
    <eLiterals name="DubebobebigusaubunulAudadalus"/>
    <eLiterals name="BrAufrigusBiGuBubeFribebuBitor"/>
    <eLiterals name="DogubugusbeNules"/>
    <eLiterals name="DonulaufriFriBibiGusbiNulaubelus"/>
    <eLiterals name="DigusAuboDaNules"/>
    <eLiterals name="DunulauboBigubibuBiBebeBofriBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusfridadagusgusgusaugusgufriCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebibedabubitus" ordered="false" upperBound="-1" eType="//DiNulaufriguLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulauBegusBinulauTor" ordered="false" upperBound="-1" eType="//AldaGusgunulauNulaubeGusbutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnauBinulauFridafriguguBuFridaCus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBofriGusauBiNulaubiNus" eType="//FagusgusbubibogusboGusbees"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofriBeBeguFribiGusfrilius" eType="//FagusgusbubibogusboGusbees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnBeGuBiguGusaubonulAuNules">
    <eLiterals name="FaFriguguBonulauGubiBoDabobiBiBeTin"/>
    <eLiterals name="Bibonulaunulaubotin"/>
    <eLiterals name="DibenulauBunulIus"/>
    <eLiterals name="EGunulaubeBugusdafrifriBugusfriBoBoCio"/>
    <eLiterals name="AuBuguBugusgubogugubugusdadator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulauBofricus" eSuperTypes="//AldaGusgunulauNulaubeGusbutin //DagunulaugusdagusBubobulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusdabebenulEs" eSuperTypes="//BenulauBofricus //AubogusBonulaugusnulAuguCio //EuGusfridadagusgusgusaugusgufriCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdabobidaDagusBibiLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnNulaubugugusaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aubedafribefribinus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigubogugusnulauLus" ordered="false" eType="//DonulaubudanulauNulauguboGulius" eOpposite="//DonulaubudanulauNulauguboGulius/aBigusgudagusnulauBenulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagubifribodadaBeBiBidaGustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBebuBibiButus" eType="//BeGusAuDagudafriBiTin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGusDagusdaguBuFriBodator" ordered="false" upperBound="-1" eType="//EuGusfridadagusgusgusaugusgufriCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubuGubonulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabedaDaguLus" eType="//BeGusAuDagudafriBiTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Braudabubonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulaudabubedaBefribobinulius" ordered="false" eType="//EuGusfridadagusgusgusaugusgufriCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubigugusGufriguDabiTor" eType="//AnNulaubugugusaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabeDafridaGugusNulAubuBubilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulauboGusBibebubuguguscus" eType="//BeboDaBobutus" eOpposite="//BeboDaBobutus/abuGufribubodabogusaugufribuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugubiGubidacus" eSuperTypes="//DagunulaugusdagusBubobulius //BenulauBofricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaFriGuboGusbugubufriFriBugusdacus" eType="//BeGusAuDagudafriBiTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiDaBububigusAuButus" eSuperTypes="//EuGusfridadagusgusgusaugusgufriCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGuboFrigubugusgusnulaubutor" ordered="false" upperBound="-1" eType="//DiNulaufriguLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubeguBubuFrifridaLus" eSuperTypes="//AdabobidaDagusBibiLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagusAugusFridaBobifrigustor" instanceTypeName="typeBabuguDabuBubinulaunulaufribeBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaubudanulauNulauguboGulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBigusgudagusnulauBenulautus" ordered="false" upperBound="-1" eType="//Aubedafribefribinus" eOpposite="//Aubedafribefribinus/bigubogugusnulauLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DifribebifriboBoBiBugusfribegulius" instanceTypeName="typeEGusnulauGusAugusdagusgufrigulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFridanulaugunulius" eSuperTypes="//EubeguBubuFrifridaLus //AnNulaubugugusaucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebebogusbeBitin" upperBound="-1" eType="//EubigusBobiBebenulAuNulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulaubeGusdadaFrilus" upperBound="-1" eType="//DabeDafridaGugusNulAubuBubilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedagunulauboDagusBetor" ordered="false" upperBound="-1" eType="//BeGusBonulauBuBotin" eOpposite="//BeGusBonulauBuBotin/fadabedadaBobudaGusbibetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauBubuFriBobugucus">
    <eLiterals name="DaFribugusFrigusdagucus"/>
    <eLiterals name="DaBobifribebibiguFrinulAubiFriBeEs"/>
    <eLiterals name="BidabefriBufribebuBugusfriDabulus"/>
    <eLiterals name="DoBobobinulius"/>
    <eLiterals name="BiDagusfries"/>
    <eLiterals name="AnbugusButor"/>
    <eLiterals name="DoguGusDanulAubebeTin"/>
    <eLiterals name="BefribogubobogubunulauTin"/>
    <eLiterals name="BafridanulAuBeDanulaunules"/>
    <eLiterals name="AlboBebuBoFriGubetor"/>
    <eLiterals name="BaboBibeCus"/>
    <eLiterals name="BraunulauBiBoNulius"/>
    <eLiterals name="AlgubugubuBeboNulAuNus"/>
    <eLiterals name="FagugububiBoboBoNulAubiboBeBenus"/>
    <eLiterals name="BafribibuBeDaBobucio"/>
    <eLiterals name="BabebifriBebuBedabebogusgusbolus"/>
    <eLiterals name="BaBufriboGuGusbebogusGufribulius"/>
    <eLiterals name="DaNulAuNulaugusdaDabebutor"/>
    <eLiterals name="BanulAuGunulAuGusnus"/>
    <eLiterals name="BifriDabebiBebugugusbodaboGusbiEs"/>
    <eLiterals name="EubogusFrigudaBobebiBebeNulAuTor"/>
    <eLiterals name="Ebibogubonulautin"/>
    <eLiterals name="Abibigusaubunulaububoes"/>
    <eLiterals name="BaGuBoguBeBebocio"/>
    <eLiterals name="BifrinulAubifribobitus"/>
    <eLiterals name="BebobegubibeBeDalus"/>
    <eLiterals name="AlnulAunulius"/>
    <eLiterals name="EbufrinulAuNulaunulauBotor"/>
    <eLiterals name="DaboGusBobifrinulaufriboBitus"/>
    <eLiterals name="Digusdabitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeboDaBobutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abuGufribubodabogusaugufribuTus" ordered="false" upperBound="-1" eType="//DabeDafridaGugusNulAubuBubilius" eOpposite="//DabeDafridaGugusNulAubuBubilius/banulauboGusBibebubuguguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbigubuguBodaFrigudagutor" instanceTypeName="typeFaGusbidabuBobiGucus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlFrifriGusBetor">
    <eLiterals name="BabuBofribogusGuDatin"/>
    <eLiterals name="BaBogusAuDabeDaguFriBuGuscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusBonulauBuBotin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulauBoFridafriguDanulius" ordered="false" upperBound="-1" eType="//Braudabubonus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadabedadaBobudaGusbibetin" ordered="false" upperBound="-1" eType="//BeFridanulaugunulius" eOpposite="//BeFridanulaugunulius/bedagunulauboDagusBetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifrigusFribeboFriguGusnulaubogunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuguBenulaunulauFribetus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BafriboboBiFriGuCio">
    <eLiterals name="BrAuDaNulAuguGusbidabobibebotin"/>
    <eLiterals name="DabubiGububenulaubecus"/>
    <eLiterals name="BraudafriboNulius"/>
    <eLiterals name="EubidadaFriBidaboCio"/>
    <eLiterals name="BaFridaguDanulAugusbedalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGudaGusbefribeboBibenules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAubeFrinulaubefriBobelus">
    <eLiterals name="AugusfriBofrinulauBigusbegudalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBeBifribogusfridanulAufricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doBobegusguBibeBigucio" eType="//DadanulAuGubuGubobuGuFriBetin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibiboBinulaubobetor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibugusdaGusGuNulauDaGusBeTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daguFriboFrigusdaboBubulus" ordered="false" eType="//DaGudaGusbefribeboBibenules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBunulaudabogusAubebodaBobelus" ordered="false" eType="//BagubifribodadaBeBiBidaGustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eugusbebicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBidabifriFriboboguslus" eType="//AuguBenulaunulauFribetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuGuDabofrinulaubuguscio" eSuperTypes="//DonulaubudanulauNulauguboGulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duFriFriBobuNulAuGusbifriCus" eType="//AnbigubuguBodaFrigudagutor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EufrifriFrigubiGusbuBobicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBuFriBeFrifrifrifriBunulEs" upperBound="-1" eType="//BenulauBofricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGufriDagusbububogudafriguNulius" eSuperTypes="//BagubifribodadaBeBiBidaGustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagudadaNulAufriBobutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBinulaudaes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugusBidaNulaubibiGucus" upperBound="-1" eType="//AlFrifriGusBetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBofriBinulaudabinulauBetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baNulaunulauboBebenulAuNulAutor" ordered="false" eType="//DabeDafridaGugusNulAubuBubilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DagusGusbigusNulaubobiBelus" instanceTypeName="typeAngusGuDanulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBigufriGusnulaufrifridaGuBuBiFriCus" abstract="true" eSuperTypes="//FagusgusbubibogusboGusbees"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabobibebibenulaubudafribuBeBitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubegusboguFriguNulaubidaBitor" eType="//DadanulAuGubuGubobuGuFriBetin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusbuBoBoFriBububegucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daguBigufribitor" upperBound="-1" eType="//EubigusBobiBebenulAuNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgufriNulaubogunulauguCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubeBebuboDaNulaubiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebofridabibudaTor" eSuperTypes="//DiDaBububigusAuButus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBugubicus" ordered="false" upperBound="-1" eType="//DiNulaufriguLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibenulauDagusgusdadaTus" ordered="false" upperBound="-1" eType="//EuGusfridadagusgusgusaugusgufriCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeFrigubofriBees" eSuperTypes="//AubogusBonulaugusnulAuguCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudanulaugusnulaufriBubugucus" ordered="false" eType="//AuguBenulaunulauFribetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbegusGuBobebobefrifricio" eSuperTypes="//AdabobidaDagusBibiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaBigusbonulaudaBobubenus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubuBunulaugusgusGubugusFriGulius" ordered="false" eType="//BeboDaBobutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbifriBegubunulAubonus" eSuperTypes="//DaGudaGusbefribeboBibenules //AnNulaubugugusaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibedaBudaNulAunulAuFrinulius" ordered="false" upperBound="-1" eType="//BeGufriDagusbububogudafriguNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidabeGufribeGubedabeBuBoLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufrigusbeBoBilius" ordered="false" eType="//AnaubeBebuboDaNulaubiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufrifriBeBoGudabidabebiDabeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eNulauBinulauBugusFribulius" upperBound="-1" eType="//AdabobidaDagusBibiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaubububobuGuBibuguNulautin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubifribeGusBuBifriguslus" ordered="false" upperBound="-1" eType="//DiDaBububigusAuButus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiNulAubobubeGusbobiGubibibonus" eSuperTypes="//DaGudaGusbefribeboBibenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusBoguBugusius" eSuperTypes="//DibiboBinulaubobetor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubigusbeGuDabuguscio" instanceTypeName="typeAuguBoFribubenulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubuBogubodabugusgusCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ANulaudafrilius" instanceTypeName="typeBraubebiNulaugusbuCus"/>
</ecore:EPackage>
