<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dubububudabocio" nsURI="http://hub.de/rcore/examples/dubububudabocio" nsPrefix="Jcli">
  <eClassifiers xsi:type="ecore:EClass" name="AnbebibedaDaFrigufriLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBigusfribinulaubebenus" instanceTypeName="typeBeBofriBebiboBufriFritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlguboDaBiFridabedaFrilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBedabebubunulaububebunulauFriLius" instanceTypeName="typeDiDabodaBofriDaNulAuCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebebiBuBefribodabedaBeLius" instanceTypeName="typeFabubiGugues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFribefriFriBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faDaBodagusfrifrifribiLus" ordered="false" eType="//AlguboDaBiFridabedaFrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufriNulaufrigufriFriDagusBiDator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusAunulAudaBoFrigusauFrinulaunulIus" upperBound="-1" eType="//DobeBigusfrifrigubegusbocio" eOpposite="//DobeBigusfrifrigubegusbocio/brauBeboFribubonulauGusbees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidaGuBibeFriGusbiBugusGusbuGusGuses" abstract="true" eSuperTypes="//AnbebibedaDaFrigufriLus //DuFribefriFriBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFriBoGusbubinulaunus" ordered="false" upperBound="-1" eType="//DidabibuguDaBetor" eOpposite="//DidabibuguDaBetor/eudaguNulaunulaugusAugubugusFrigutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlDaBenulauFrifrifriboFrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbogusbebeTor" eType="//BebebiBuBefribodabedaBeLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dodaBedagusnulaububuEs" ordered="false" eType="//DidaGuBibeFriGusbiBugusGusbuGusGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidabibuguDaBetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguBobuBibobucio" upperBound="-1" eType="//DuFribefriFriBolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudaguNulaunulaugusAugubugusFrigutus" ordered="false" eType="//DidaGuBibeFriGusbiBugusGusbuGusGuses" eOpposite="//DidaGuBibeFriGusbiBugusGusbuGusGuses/alFriBoGusbubinulaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabiBoGuBeBilius" instanceTypeName="typeEuBonulAunulauBubiGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBifriGubufriguGusbofrigusbulus" abstract="true" eSuperTypes="//DidaGuBibeFriGusbiBugusGusbuGusGuses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidagusbofribuBodaBubebibeBees" ordered="false" upperBound="-1" eType="//DoTus" eOpposite="//DoTus/bifrifrifriBifrigusauBiTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofribebigubiDaNulauGucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBuBubegusBufritus" ordered="false" upperBound="-1" eType="//DidaGuBibeFriGusbiBugusGusbuGusGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuGuGudabubuDagunulautor" eSuperTypes="//AlDaBenulauFrifrifriboFrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daGusbibenulauGuslus" eType="//EuBigusfribinulaubebenus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibibotin" upperBound="-1" eType="//BebebiBuBefribodabedaBeLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anbudafrifrifrilius" eSuperTypes="//AnbebibedaDaFrigufriLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBeDabuBigusFribuGudanules" eType="//EuBigusfribinulaubebenus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifrinulaufriNulaufriNulAutor" eType="//AldaNulAubinulaudalius" eOpposite="//AldaNulAubinulaudalius/beBiboDadadadadaGudagusCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagugusbobidaFribigustus" eSuperTypes="//DuFribefriFriBolius //AufriNulaufrigufriFriDagusBiDator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aguBuGuGunulAubebobitin" upperBound="-1" eType="//BebebiBuBefribodabedaBeLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DofrifriFrigubunulius" instanceTypeName="typeAGusGugusbefriNulAugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBubifrigubofriGusbudaGuTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusbeguGunulauLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebegubeBufricio" eType="//FabiBoGuBeBilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnauFriDanulaubies" instanceTypeName="typeBadafrifrifriFribibuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulAuDaGubeDabebiBogusnulAudafriNulauTor" eSuperTypes="//BrAuGuGudabubuDagunulautor //EBifriGubufriguGusbofrigusbulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguBubefribigusaunus" eSuperTypes="//DuFribefriFriBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusfribiGusgusgusgusbetin" eSuperTypes="//Anbudafrifrifrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogubiBogubecus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egusDabuBebodaBeNulAudagusdanus" eType="//BaBedabebubunulaububebunulauFriLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboguGuDagusnulAubecus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfrifriguboGunulaufriboCus" eType="//BaBedabebubunulaububebunulauFriLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbonulaugubunulIus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDaNulAubuCio" ordered="false" eType="//AlDaBenulauFrifrifriboFrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeBibenulaugubiNulaubibufrilus" abstract="true" eSuperTypes="//EguBubefribigusaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibubeBeNulauBeNulaucus" eSuperTypes="//AlDaBenulauFrifrifriboFrilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FadafribuGusbuBuFrinulauTor" instanceTypeName="typeAbiBiDabies"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Donulautus">
    <eLiterals name="DaNulaububebubeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGugusbodadanulAutor" eSuperTypes="//DidaGuBibeFriGusbiBugusGusbuGusGuses //DibubeBeNulauBeNulaucus //DigusbeguGunulauLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eDaFriBigusdaFribegugusnus" eType="//BebebiBuBefribodabedaBeLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ABidadadaBefrigusBoboCio" instanceTypeName="typeAldadagusboDadabudacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiFriBogusdaguGuFrigutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogufrinulauguguboBebeFrigusfriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidaFrigusGusdagusdaBebufribecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldaNulAubinulaudalius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBiboDadadadadaGudagusCio" ordered="false" eType="//Anbudafrifrifrilius" eOpposite="//Anbudafrifrifrilius/bifrinulaufriNulaufriNulAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Efridafribigusbogusnulaudagustus">
    <eLiterals name="Braufribubotus"/>
    <eLiterals name="EunulauFriGuBobugutin"/>
    <eLiterals name="AnaubeBotin"/>
    <eLiterals name="AbobigusgusBogusLius"/>
    <eLiterals name="AnnulaunulAunulauGusgustin"/>
    <eLiterals name="FaBeTor"/>
    <eLiterals name="EgunulAubiBebudabibebudator"/>
    <eLiterals name="Dobebonulaububifrigustor"/>
    <eLiterals name="DifrifriguGusLius"/>
    <eLiterals name="DabefribigusdaNulAuGusNulauFridagustin"/>
    <eLiterals name="AlbogufribiFriDafridafriboFriBucus"/>
    <eLiterals name="DaGusgunulAubobibeboGusnulaugusCio"/>
    <eLiterals name="EdadaDaBefriGunus"/>
    <eLiterals name="DudagufribugusbeDabuBuguLius"/>
    <eLiterals name="EugubugusfriboGububenulius"/>
    <eLiterals name="DabibeBoFriguBibilus"/>
    <eLiterals name="DoGunulaunulaububiguCio"/>
    <eLiterals name="AngusbuBifriGunulaugubudagusguslus"/>
    <eLiterals name="DofriGusGusGusDadacio"/>
    <eLiterals name="AboboBubedaguGunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuguBebugugusDaBegusbeNulAubies" eSuperTypes="//DigusbeguGunulauLus //DagugusbobidaFribigustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubiDagusnulauguDabucus" ordered="false" upperBound="-1" eType="//DuFribefriFriBolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabuGuboBogusbubuGusauBuBubegucio" ordered="false" upperBound="-1" eType="//DibubeBeNulauBeNulaucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebenulAudadaBubibubitin" ordered="false" eType="//AbonulaugubunulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobegusBunulAugusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubibibigusdagunulIus" eType="//AufriNulaufrigufriFriDagusBiDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBubuNulAudanulIus" instanceTypeName="typeBabenulAuBuguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufriBuBoboguGuguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguFrifriNulauFribonulauCio" ordered="false" eType="//DogufrinulauguguboBebeFrigusfriTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abeGuGuBies" ordered="false" upperBound="-1" eType="//DiboguGuDagusnulAubecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EguBuDaBenulAuBibobegusnus" eSuperTypes="//AlguboDaBiFridabedaFrilus //DiboguGuDagusnulAubecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulAugugusbuBibibufriGuDalus" abstract="true" eSuperTypes="//AldaNulAubinulaudalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobeBigusfrifrigubegusbocio" eSuperTypes="//AlguboDaBiFridabedaFrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBeboFribubonulauGusbees" ordered="false" eType="//AufriNulaufrigufriFriDagusBiDator" eOpposite="//AufriNulaufrigufriFriDagusBiDator/egusAunulAudaBoFrigusauFrinulaunulIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubegusBibibibinulaulius" ordered="false" upperBound="-1" eType="//EguBubefribigusaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauBuGusbunulAuBoGuboLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguGusbiLus" upperBound="-1" eType="//DagugusbobidaFribigustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dabubobilus" eSuperTypes="//DigusbeguGunulauLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dunulaubobitin" eType="//Efridafribigusbogusnulaudagustus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBeBiNulaubegucio" ordered="false" upperBound="-1" eType="//DidabibuguDaBetor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudabigusgubibicio" ordered="false" upperBound="-1" eType="//DobeBigusfrifrigubegusbocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dibegusbibifrinus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodadadafribinulAubinulauTor" abstract="true" eSuperTypes="//DobeBigusfrifrigubegusbocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBedabobiBobudabuboguGusguscus" ordered="false" eType="//Anbudafrifrifrilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abeGusaububiBudaboBebigugusBodatus" ordered="false" upperBound="-1" eType="//EubebeNulaudaDaLus" eOpposite="//EubebeNulaudaDaLus/abobiFribofrinulAuGubobeNulAufriFriCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobobuguGubuguBifribebibubobebotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidanulauboBugusBetor" abstract="true" eSuperTypes="//DigusbeguGunulauLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBibigunulaubifriGuCio" ordered="false" upperBound="-1" eType="//AnnulauBuGusbunulAuBoGuboLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauboTor" instanceTypeName="typeAlgubunulauBunulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbinulaufribobubeBoguBucio" instanceTypeName="typeDuFriboGusBoFriBoDaBegucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefriBibeGugufrigusnus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EufrinulAubiGunulaunulius" instanceTypeName="typeAlGusAunulaubiDadaBiboNulAuDafriDaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabubiBiGufrigustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBubiTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdabinulauGuscio" eSuperTypes="//BidanulauboBugusBetor //BidaFrigusGusdagusdaBebufribecus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="di" eType="//EufrinulAubiGunulaunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbufrifribibogubegusbeLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGufriDabebebufribenulauBiboBetus" upperBound="-1" eType="//DogubibudabiGusgues" eOpposite="//DogubibudabiGusgues/anAunulAufriGubububiBebulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulauBubeGugusBigusBeCus" abstract="true" eSuperTypes="//BeBubifrigubofriGusbudaGuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufribidadabeGusnus" ordered="false" eType="//AbonulaugubunulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugusgufribuguboGucus" instanceTypeName="typeBaBuBebonulAubibeBoGucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AguBedaBebiTus" instanceTypeName="typeAlBubobeBobiFrinulauBidaTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuFrigugunulAuNulaubegugunulauCus" instanceTypeName="typeEuBuguguguboBibofriBifriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGugusbubenulAububeguTin" eSuperTypes="//Anbudafrifrifrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuDaBigusbobibubibodaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriGusGusdabobiBeFrifricus" eSuperTypes="//DibubeBeNulauBeNulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusbobofridaBugusbudaes" ordered="false" eType="//DobobuguGubuguBifribebibubobebotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlFribebeGusNulaudadagusbuLius" eSuperTypes="//BeBubifrigubofriGusbudaGuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulAuBedagubutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigubufriBoFrifries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baNulauboBuGubibefriGusbunulEs" ordered="false" upperBound="-1" eType="//BeBubifrigubofriGusbudaGuTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBeGububugusdabulus" ordered="false" eType="//BefriBibeGugufrigusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubofribuBoTus" abstract="true" eSuperTypes="//DobegusBunulAugusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabifrigusAugusgusautor" ordered="false" eType="//AldaNulAubinulaudalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabebebogugugubegusbuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aboDabuBoGuBuguGubiFrinules" ordered="false" upperBound="-1" eType="//DiNulAuDaGubeDabebiBogusnulAudafriNulauTor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafridabubonulauguguses" upperBound="-1" eType="//BebebiBuBefribodabedaBeLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusboGusguguBuCus" ordered="false" eType="//AbonulaugubunulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiFriDabefrinulauBobonulAunulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babuGusGusGusbodagunulaudalius" ordered="false" eType="//DofribebigubiDaNulauGucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraudabebofrifriboBolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafribobuBibuGubibetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogubibudabiGusgues" eSuperTypes="//DidabibuguDaBetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anAunulAufriGubububiBebulus" ordered="false" eType="//AbufrifribibogubegusbeLus" eOpposite="//AbufrifribibogubegusbeLus/anGufriDabebebufribenulauBiboBetus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digubuBuBegubibogusbunulAuTor" upperBound="-1" eType="//Efridafribigusbogusnulaudagustus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAugusbigusbiBonulAugubebiFriTus" instanceTypeName="typeFabeGugugusgusgudadacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGufribobeLius" eSuperTypes="//DibubeBeNulauBeNulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubibefriGuFrifrinulaugusdator" eSuperTypes="//AlbeBibenulaugubiNulaubibufrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubunulauguBibiNulaubefrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogudabofrigububobeTor" instanceTypeName="typeBabubefribebeBeBoguGuBues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGubigusdabugusIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alguBeDagusbonulaugusgusnus" eType="//FaNulauTin" eOpposite="//FaNulauTin/fanulaugusbonulaubobodaNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusgusBefrinulauGubobuBebogubilius" abstract="true" eSuperTypes="//DofribebigubiDaNulauGucio //DobobuguGubuguBifribebibubobebotus //DogubiBogubecus //AlbeBibenulaugubiNulaubibufrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabinulAuBoFrifriBucus" eType="//ABidadadaBefrigusBoboCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAunulaunulauguDaBeFritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuBoGusbofribetin" eType="//BaBedabebubunulaububebunulauFriLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBenulAuBeBunules" eType="//AlbinulaufribobubeBoguBucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DifriBenulAudanus" instanceTypeName="typeAugusbiGusDanulaufrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafridafriNulAubeBidaFrifriTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babofridalus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubenulauDabebobibiTor" ordered="false" eType="//FabubiBiGufrigustus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBubetus" ordered="false" upperBound="-1" eType="//DibubeBeNulauBeNulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbiGusaudadalus">
    <eLiterals name="AuguBodalus"/>
    <eLiterals name="AnBeGuFrifriboguBigusauDanulauLius"/>
    <eLiterals name="EudafrigusBoFrifriTor"/>
    <eLiterals name="BraububuBogufriEs"/>
    <eLiterals name="BanulaudafribeDanus"/>
    <eLiterals name="BegudaboBoGusnulaubenulaufrigustor"/>
    <eLiterals name="BaboDagubetus"/>
    <eLiterals name="EdabebubobifrigusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusbenulauNulAuNus" abstract="true" eSuperTypes="//AlbiFriBogusdaguGuFrigutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguNulauboNulAuboBulus" upperBound="-1" eType="//BafridafriNulAubeBidaFrifriTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="didagusGusgusaunulauGusbobidatus" ordered="false" upperBound="-1" eType="//BidanulauboBugusBetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubegugubeBunulauFrifribububocus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="al" eType="//FadafribuGusbuBuFrinulauTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulaubiBigufriBoBobonulEs" eType="//BraugusgusBefrinulauGubobuBebogubilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgugubobifribebenulauDanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagubodafrinulAuTin" ordered="false" eType="//EugusbenulauNulAuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubebeNulaudaDaLus" eSuperTypes="//EguBubefribigusaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abobiFribofrinulAuGubobeNulAufriFriCio" upperBound="-1" eType="//DodadadafribinulAubinulauTor" eOpposite="//DodadadafribinulAubinulauTor/abeGusaububiBudaboBebigugusBodatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulauTin" eSuperTypes="//DubibefriGuFrifrinulaugusdator //DigubufriBoFrifries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBeBeNulaugusgusfridatus" ordered="false" upperBound="-1" eType="//BidaFrigusGusdagusdaBebufribecus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annulaugusbibedaCio" upperBound="-1" eType="//FabiBoGuBeBilius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulaugusbonulaubobodaNus" ordered="false" eType="//DaGubigusdabugusIus" eOpposite="//DaGubigusdabugusIus/alguBeDagusbonulaugusgusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeGusBofriDabuguBobonulaucus" eSuperTypes="//DiboguGuDagusnulAubecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoTus" eSuperTypes="//BidanulauboBugusBetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifrifrifriBifrigusauBiTor" ordered="false" eType="//EBifriGubufriguGusbofrigusbulus" eOpposite="//EBifriGubufriguGusbofrigusbulus/bidagusbofribuBodaBubebibeBees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlauBinulaufribibutin" eSuperTypes="//DobeBigusfrifrigubegusbocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebogusbobibenulaucio" ordered="false" eType="//AufriNulaufrigufriFriDagusBiDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobebibibonulAuGustin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudabedagusbubebunules" ordered="false" upperBound="-1" eType="//DogufrinulauguguboBebeFrigusfriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusfribibufridaGubigugustus" instanceTypeName="typeEGusbebeboBuguDagusnulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboNulaufriGusdabuguBiGusBebuBelus" abstract="true" eSuperTypes="//DogufrinulauguguboBebeFrigusfriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaguBugusbobiBibuGusdaBies" abstract="true" eSuperTypes="//EnulauBubeGugusBigusBeCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubobonulaubuBebedanules" eType="//EuBigusfribinulaubebenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DoGusBefriBeNulauBebugubegustus">
    <eLiterals name="FaguGusbinulauGusgubebicio"/>
    <eLiterals name="EdaboGusNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anbodabodabigubibebobibelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBeDaGuBuNulAubigusEs" ordered="false" eType="//EBifriGubufriguGusbofrigusbulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabugusAufriBubobogusGusbelus" instanceTypeName="typeBiBuboBoBuFridadagusbolius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubobogubibebobibiguBoNulAuTor" instanceTypeName="typeDafribogusaubobonulaubilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBunulaubeFriFridaDafricio" instanceTypeName="typeAuBobiGusNulauDabibuguGusbunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulAuBebonulAubiguNulaubeBibeboLus"/>
</ecore:EPackage>
