<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="annulaubicio" nsURI="http://hub.de/rcore/examples/annulaubicio" nsPrefix="bDR">
  <eClassifiers xsi:type="ecore:EClass" name="Badagufribotin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubiNulAuguDadabubicio" abstract="true" eSuperTypes="//Badagufribotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagufribidabiDabeGuGusnulAubiEs" eSuperTypes="//Badagufribotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulAuguBodabidaBoTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BidagusnulauTus" instanceTypeName="typeBrAunulauboGustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGuGusGuBofrinulAubiBicio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daboGusaubigusbinulIus" eType="//BidagusnulauTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Bibenulaugugusdanulaubocus" instanceTypeName="typeFabogusnulaufriBiNulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusfridabebenulaufribunus" eSuperTypes="//ANulAuguBodabidaBoTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulaubebetor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBubenulAuBobunulaububitus" instanceTypeName="typeAuNulAunulaubufribedaBunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadafriBeBidagudalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daboGubibeFrifribuguBobeNulauCus" eType="//DagufribidabiDabeGuGusnulAubiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaugusnulaugusBoNulAunulauTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBeDagubudaNulautus" abstract="true" eSuperTypes="//FaGusfridabebenulaufribunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dagusBeFribifritor" eType="//BidagusnulauTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubobiboGufrinulAubibunulAudafribuLius" ordered="false" upperBound="-1" eType="//EunulaugusnulaugusBoNulAunulauTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfriBoNulAubobefrinulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbegusAunulAudabugusBues" instanceTypeName="typeAnbeBibubebobeGuGulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulAubebedaBuGusfrilus" eSuperTypes="//Badagufribotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbebiNulauBetor" ordered="false" eType="//ANulAuguBodabidaBoTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabeBiDabeboBiBeGusTin" ordered="false" eType="//EunulaugusnulaugusBoNulAunulauTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abefriBudaBobobiBoNulauTus" ordered="false" upperBound="-1" eType="//BrAuBuguNulius" eOpposite="//BrAuBuguNulius/doNulAuBocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbububeBuBigubenulAubebeFribelius" eSuperTypes="//AGuGusGuBofrinulAubiBicio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Fabobegusdabigutus">
    <eLiterals name="BeNulaubuBebuBigues"/>
    <eLiterals name="AubeBoBogunulAuguTin"/>
    <eLiterals name="BibegufriBunulAubiTin"/>
    <eLiterals name="DuBofridaBoguslus"/>
    <eLiterals name="BidabegusgusgusbuNulauGuNus"/>
    <eLiterals name="DiBebobububenulaububoFrinus"/>
    <eLiterals name="DadabuNulaubibobuLus"/>
    <eLiterals name="Fagusgusdabenules"/>
    <eLiterals name="EugusbegusbogusTor"/>
    <eLiterals name="FaguGufriGunulAudaBoBobecio"/>
    <eLiterals name="FanulaubodabubiguNulauboBoCus"/>
    <eLiterals name="BabeFriGufriGuBobebubegunulius"/>
    <eLiterals name="DinulaubufriDafrigusfriboGunulautor"/>
    <eLiterals name="AuBuBebodagusguTin"/>
    <eLiterals name="BebibofribuBoBobibeBuBolus"/>
    <eLiterals name="DaBegubuGusBelius"/>
    <eLiterals name="EboDabonulaudanulauguBucio"/>
    <eLiterals name="AdanulAuGubeTin"/>
    <eLiterals name="BraugusboFrifriBicus"/>
    <eLiterals name="EbeBeNulAutor"/>
    <eLiterals name="DinulaubefrigusbugugubuguBubobiFrinus"/>
    <eLiterals name="BrAunulauDanulAunulAutin"/>
    <eLiterals name="BeguboBogunulAubibiFribicus"/>
    <eLiterals name="DubinulaubebibuBetus"/>
    <eLiterals name="BifridabiFriBeLus"/>
    <eLiterals name="DonulAubitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubunulaunulaubibubuFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaboboNulauguNulauBiNulauboTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagugugusnulauBigubebicus" upperBound="-1" eType="//DubogubuGuboBobobiNulEs" eOpposite="//DubogubuGuboBobobiNulEs/digusauFribugusgusauFrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbidaBogugusguButor" eSuperTypes="//FaGusfridabebenulaufribunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaugusaubiFribubidanulaunus" ordered="false" upperBound="-1" eType="//AlaubiNulAuguDadabubicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulaugudaDanulAubuBeBinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audaBebunulauBoBufribogusbudaCus" upperBound="-1" eType="//FagusbidaBogugusguButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubogubuGuboBobobiNulEs" eSuperTypes="//FaGusfridabebenulaufribunus //BeNulaubebetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusauFribugusgusauFrilius" ordered="false" upperBound="-1" eType="//DaboboNulauguNulauBiNulauboTus" eOpposite="//DaboboNulauguNulauBiNulauboTus/dagugugusnulauBigubebicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulaubiboBucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidabubiBufrilius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dobidabubobufridagusgubugububudalus" instanceTypeName="typeDofribodabubobodaBedaBiNulauTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Danulaunulaubofries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begudabiFriguCio" eType="//Dobidabubobufridagusgubugububudalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaGusboboBitin">
    <eLiterals name="EunulauFribugusfriBeBitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Braudanulaunulius" eSuperTypes="//BraunulaubiboBucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auBugusbefriFries" eType="//DoBubenulAuBobunulaububitus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DuGuBoGusBeguNulaubeNulautus">
    <eLiterals name="DabebudabuBofrigusbenulAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBuguNulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doNulAuBocus" ordered="false" upperBound="-1" eType="//BraunulAubebedaBuGusfrilus" eOpposite="//BraunulAubebedaBuGusfrilus/abefriBudaBobobiBoNulauTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duNulAufribiBenulauboBocus" upperBound="-1" eType="//Dobidabubobufridagusgubugububudalus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulauFribubefrinus" ordered="false" eType="//EunulaugusnulaugusBoNulAunulauTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGugusdagubufrigulus" abstract="true" eSuperTypes="//AlaubiNulAuguDadabubicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alguDabeGuboCus" ordered="false" eType="//DagufribidabiDabeGuGusnulAubiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Ba" instanceTypeName="typeAfriDabuBubigusdalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgufriGudadagusFriGudagusgusgutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobogubogusaububebegunulautor" eSuperTypes="//AnbububeBuBigubenulAubebeFribelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBidaDabuBebuNulaucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuDagusbuFrigubogusbiDaBubuDacus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuFriNulaubitor" instanceTypeName="typeEubiguNulaudacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Begusbonulaunus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Befrigugusbodatus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebobonulaufribegusbinus" eType="//Fabobegusdabigutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuGusDabeDafrigusgugusDaDaLius" instanceTypeName="typeEufriBebeNulAuFridaDabiBetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebonulaububifrigusbeBobeCio" eSuperTypes="//BraunulaubiboBucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daNulAubudabutor" ordered="false" upperBound="-1" eType="//EgufriGudadagusFriGudagusgusgutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaguGusBigusBedabogusbelus" eSuperTypes="//Danulaunulaubofries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAugugunulaugugusCus" upperBound="-1" eType="//Danulaunulaubofries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusAuBobocus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBinulAuLius" ordered="false" eType="//DibuDagusbuFrigubogusbiDaBubuDacus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doDabubugusBunulaubogufrifridagusbobobicus" ordered="false" eType="//AuGuBoCio" eOpposite="//AuGuBoCio/eubeNulauguBonulaufribegusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdagubedabibobuNus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusnulaugugugubotin" ordered="false" upperBound="-1" eType="//DoGugusdagubufrigulus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biNulauTus" eType="//EuGusDabeDafrigusgugusDaDaLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bebegubodafribotin" eSuperTypes="//DibuDagusbuFrigubogusbiDaBubuDacus //EunulaugusnulaugusBoNulAunulauTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulaubogusguguNulaufrifriLius" ordered="false" upperBound="-1" eType="//DagufribidabiDabeGuGusnulAubiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBuBobeDagugusdanus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusbubebodaboFriBebobububegusNulIus" ordered="false" eType="//AlBeDagubudaNulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudabuGudabonulaubiBoFriCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubibubifriboguboBebibuBoDabobotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angugunulaunulauBiTin" ordered="false" eType="//BeNulaubebetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlAubugusdagubebigusBebenulauTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebebugubogusNulaudabuCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abubuguboBedaBodaFribuEs" eType="//Dobidabubobufridagusgubugububudalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgudabidaDabiGubebues"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibuGunulaubiDalus" abstract="true" eSuperTypes="//AlBeDagubudaNulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnauNulAubudabobudaguGusCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulauGufribifrigufricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobifribidaBibotor" ordered="false" upperBound="-1" eType="//AlAubugusdagubebigusBebenulauTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubidabiboBobubocus" instanceTypeName="typeAububiguDadabudaNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAubobiBuBidabudabebeBunulauCus" eSuperTypes="//DidabubiBufrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusBobiGusgusbubebebuguBees" abstract="true" eSuperTypes="//AlBeDagubudaNulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusbeBubocus" ordered="false" eType="//AlBeDagubudaNulautus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabuDadaboFrigusguBubobuCio" ordered="false" upperBound="-1" eType="//Braudanulaunulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBegusaubeBolus" ordered="false" upperBound="-1" eType="//ANulAuguBodabidaBoTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagubeguboBodaFriEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaboBuguguBobigugusbobolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabeGuGusbogucus" ordered="false" upperBound="-1" eType="//DagufribidabiDabeGuGusnulAubiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ABoBobebidabeBiDabitor">
    <eLiterals name="AlnulaugusgugusbobobiFriBonulAutin"/>
    <eLiterals name="Dibogusaugusgufrinulius"/>
    <eLiterals name="DaBifribeGubofriboLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboBoGunulaububies" eSuperTypes="//EgufriGudadagusFriGudagusgusgutin //DudabuGudabonulaubiBoFriCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuFridadaNulAubibugustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGuNulaubuGusfrilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anbedabububolius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulaubuNulaubilius" eType="//EuFriNulaubitor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aboDagubuBitin" eType="//DoBubenulAuBobunulaububitus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusAuTor" eSuperTypes="//Bebegubodafribotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusBegusbegusdafritor" upperBound="-1" eType="//BaGusboboBitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifridaBibeNulauboBoBitus" eSuperTypes="//FagusAuBobocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidabeGubugusgubibinulAuBecio" eSuperTypes="//DagufribidabiDabeGuGusnulAubiEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudabofriBiNulIus" ordered="false" eType="//ANulAuguBodabidaBoTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauGusaufriBibegulius" instanceTypeName="typeBegunulAudabuBidadagusdagufrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGuBoCio" eSuperTypes="//Begusbonulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubeNulauguBonulaufribegusNus" ordered="false" eType="//FagusAuBobocus" eOpposite="//FagusAuBobocus/doDabubugusBunulaubogufrifridagusbobobicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ABenulAudaGudaFribiBidacus" instanceTypeName="typeFagusboNulaunulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibubebebiGuNulauguDaDaguBogusAubiBuDacio" eSuperTypes="//Begusbonulaunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="br" eType="//EuFriNulaubitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufrigusfridaGusautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadabuBugusgusguBubuBufrigudator"/>
</ecore:EPackage>
