<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ebebicio" nsURI="http://hub.de/rcore/examples/ebebicio" nsPrefix="tbu">
  <eClassifiers xsi:type="ecore:EClass" name="BibegusBogudaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedaboFrigufribubibiBoBobunulaulus" eSuperTypes="//BibegusBogudaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusbifrigubibiDaGusGugusbilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBeboGuBodaBeBeGusBedacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobobuFrilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AguGufriboboNulAunulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albeguboBobuGuBuBebecus" upperBound="-1" eType="//AnBeboGuBodaBeBeGusBedacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBenulauNulaunules" eSuperTypes="//BedaboFrigufribubibiBoBobunulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuDagusdanulauDaBuGustin" eSuperTypes="//AguGufriboboNulAunulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusFribedabodaBiGuFrinulAuTin" ordered="false" upperBound="-1" eType="//BedaboFrigufribubibiBoBobunulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofriNulaubefribigugubobeTus" abstract="true" eSuperTypes="//BrauBenulauNulaunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguBebubegusnulaububiBufriBoCio" ordered="false" eType="//BrauBenulauNulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusbonulaufriLius" eSuperTypes="//BrauBenulauNulaunules //BagusbifrigubibiDaGusGugusbilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadagusdabobinulAudaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eugugubilius" eSuperTypes="//BagusbifrigubibiDaGusGugusbilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulauDabogugugusNus" ordered="false" upperBound="-1" eType="//AnBeboGuBodaBeBeGusBedacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulaubibebufrigusgusAubuEs" eSuperTypes="//BrauBenulauNulaunules //Eugugubilius //DobobuFrilus //FadagusdabobinulAudaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofridaBuDagusGugutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albunulaufrigusBedacio" ordered="false" eType="//BedaboFrigufribubibiBoBobunulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaunulaububebefridagusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusaubebifriBogusNulauBetus" eSuperTypes="//BibegusBogudaLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusgusboFrigusCus" upperBound="-1" eType="//DofridaBuDagusGugutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulaunulaubiBonulaubetin" eSuperTypes="//DofriNulaubefribigugubobeTus //FadagusdabobinulAudaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGunulaudaGunulauBiguNulius" eSuperTypes="//AnbuDagusdanulauDaBuGustin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BedadafridafriDafrigusdaGuguslius" instanceTypeName="typeFafribuGugusAubolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriNulaubegusFriDabebebodabebucio" eSuperTypes="//DigusaubebifriBogusNulauBetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabuBufriBeDaBelus" eType="//BedadafridafriDafrigusdaGuguslius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anguboGubuguscus" eType="//BedadafridafriDafrigusdaGuguslius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBebenulAubobeBeBuDaBebecus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuFrigusautin" eSuperTypes="//BibegusBogudaLus //ENulaunulaububebefridagusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibiBigustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudaDaFrigusbodadaTor" eType="//BrauBenulauNulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBibibidadabobofribobiBeTin" instanceTypeName="typeDanulauBiBeFribogustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfrigusauBeBigubiTus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BabuNulAubegunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidaBobebofriBinulAuFriGulius" abstract="true" eSuperTypes="//DofriNulaubefribigugubobeTus //ENulaunulaububebefridagusLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bifrigunulauNulaububudanus" eType="//BabuNulAubegunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BinulAugufrigubufrinulAubebutus" instanceTypeName="typeDonulauBiNulaugubufriboguTus"/>
</ecore:EPackage>
