<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eunulaugues" nsURI="http://hub.de/rcore/examples/eunulaugues" nsPrefix="jy">
  <eClassifiers xsi:type="ecore:EEnum" name="FaBeNulAubiGubiGustin">
    <eLiterals name="DafribibeGusfrinulauTor"/>
    <eLiterals name="Dabunulaubogubebidaes"/>
    <eLiterals name="FafrigunulaudaGusFribeFritus"/>
    <eLiterals name="EugusauDadaNulAuFribigulius"/>
    <eLiterals name="FaBobobubeBufricus"/>
    <eLiterals name="DibeBodabunulAudaNulius"/>
    <eLiterals name="BebinulaufriBibofricus"/>
    <eLiterals name="AlbibobuBobetin"/>
    <eLiterals name="BefrinulaubodaBibobibubocio"/>
    <eLiterals name="AbubuGusbeBocus"/>
    <eLiterals name="EbibobodabogusbuguboCus"/>
    <eLiterals name="EubibiGusaugusfritor"/>
    <eLiterals name="DifriBeBoguGubobiBibufriBolius"/>
    <eLiterals name="BedaBobuFriBugusfridafribenulaulus"/>
    <eLiterals name="AlbufrifribugusNus"/>
    <eLiterals name="BabiNulaugusfritus"/>
    <eLiterals name="EBofriDadaBiNulaufribidatin"/>
    <eLiterals name="DuGusbebufrigusdabigusBuNulEs"/>
    <eLiterals name="FagusFridafribiLus"/>
    <eLiterals name="AboguDabubeBubeBebobobudalus"/>
    <eLiterals name="AlbuBubeBiGuNulAuTor"/>
    <eLiterals name="BagusnulAunulaubiBidabubugusfribuNules"/>
    <eLiterals name="DiBuGusBeNulAubidafrigusguNus"/>
    <eLiterals name="AfriguFridabuBenules"/>
    <eLiterals name="EbuNulaubobuBoBoLus"/>
    <eLiterals name="AnFriFriBuBubegubibiGusDaBigusgunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbonulaufriguBoguslius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dadagudagusgudaboDabunus" eType="//FaBeNulAubiGubiGustin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudanulAudagugugusaugusIus" eSuperTypes="//EbonulaufriguBoguslius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraufridabidaFrigusdaGuCio" instanceTypeName="typeDobiFribiBonulauFriGufriBudacus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Fagunus" instanceTypeName="typeBebubedanulauDabuguBidaguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiguBibobubiGusbuBubeFribibibeLus" abstract="true" eSuperTypes="//EbonulaufriguBoguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daFrifrifridaGutus" ordered="false" upperBound="-1" eType="//DudanulAudagugugusaugusIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DugusfrinulaubeGusFries">
    <eLiterals name="BiFriboBunulAugubiguBefritus"/>
    <eLiterals name="BidabuBiGunulius"/>
    <eLiterals name="BraugusNulAubebibuBelius"/>
    <eLiterals name="DidagudaguGugusfriGusbies"/>
    <eLiterals name="BiGugudabuLius"/>
    <eLiterals name="EnulAuBiNulaubenulaubees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifrigusaubobubidaCio" abstract="true" eSuperTypes="//DudanulAudagugugusaugusIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobebeboBugusbifriGusbeBobicus" eType="//FaBeNulAubiGubiGustin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BafribibububefrifrinulaugusgusFritor" eSuperTypes="//BifrigusaubobubidaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euguGuscio" ordered="false" upperBound="-1" eType="//BifrigusaubobubidaCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBogusAunulaubucio" eType="//AlAugufriDaBobutus" eOpposite="//AlAugufriDaBobutus/alGufriBububogustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Eufribebugusaubugustin" instanceTypeName="typeBifriFriguGufrigusaudator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebiboFriBugubofrinulAufrigusfrinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigufriBunulAudadagustor" ordered="false" upperBound="-1" eType="//DudanulAudagugugusaugusIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabuGusFriDanulAuBucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulAuGusfrigubiGulus" eSuperTypes="//BafribibububefrifrinulaugusgusFritor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auboguGuTin" eType="//Eufribebugusaubugustin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABiBigusdafriGufriBiBoBoGusnus" abstract="true" eSuperTypes="//DiguBibobubiGusbuBubeFribibibeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaBuNulaugusgusbebigubeGutor" ordered="false" upperBound="-1" eType="//DiguBibobubiGusbuBubeFribibibeLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biNulaufriBoDabutin" ordered="false" upperBound="-1" eType="//DudanulAudagugugusaugusIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabuBoBeBiBidaBitor" ordered="false" upperBound="-1" eType="//EuGuBuGubiBudaBunulauBuEs" eOpposite="//EuGuBuGubiBudaBunulauBuEs/auGusbebigusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaguBinulAuBiFribonulAuFries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadaNulauBoBubiBeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBubinulauBoDaboTor" ordered="false" eType="//BifrigusaubobubidaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabugusNulauNulautin" instanceTypeName="typeDogugusfriFrifriNulaugusgusgustor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Fadanulaucio">
    <eLiterals name="DunulAugubeguguGuTus"/>
    <eLiterals name="EdaBuNulaulus"/>
    <eLiterals name="EFrifriguguBoFriBeBobodaButor"/>
    <eLiterals name="AfriGusGusbibeDafrifriGusbeNulaubibebitin"/>
    <eLiterals name="DaDanulaulus"/>
    <eLiterals name="DoBubiBoBububinulAugustin"/>
    <eLiterals name="BibeDaDafriBiGusDacio"/>
    <eLiterals name="DudaBegusnulauBiDabeDabonus"/>
    <eLiterals name="ENulAuFriguGusbeBogusgulus"/>
    <eLiterals name="DufribuGubebigusBogusfriDaEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnnulaunulaubeButus">
    <eLiterals name="BebobubigusBuBuBofridaFribeDacio"/>
    <eLiterals name="BebunulAubegudabubibibeDator"/>
    <eLiterals name="AuBiBogusBofribibuboDabofriBobucus"/>
    <eLiterals name="AgubifriGusaubeBuFribonulius"/>
    <eLiterals name="Dubugufrifrilius"/>
    <eLiterals name="AlbefribudaBuFriBelus"/>
    <eLiterals name="BiGusAubofridaBonulaubeBinulaudabodabudafriButor"/>
    <eLiterals name="BeguDanulAutor"/>
    <eLiterals name="Bagusbogusbigusbibunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EububedaCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Didanulaunulaunulautor" eSuperTypes="//BadaNulauBoBubiBeLus //BifrigusaubobubidaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaunulAuboboNules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugunulAuguBuGusFriNulAugugucus" ordered="false" eType="//BafribibububefrifrinulaugusgusFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DobebibibuTor" instanceTypeName="typeDoBubugusBibinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebenulauBuGunulaubudaDalius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BagubibegusNulauGuguBebenus" instanceTypeName="typeBraunulAunulauBidabodafribudabuguTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGuBuGubiBudaBunulauBuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusbebigusnus" ordered="false" eType="//ABiBigusdafriGufriBiBoBoGusnus" eOpposite="//ABiBigusdafriGufriBiBoBoGusnus/dabuBoBeBiBidaBitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBoGubibogusGusBebuFriBefriEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebiBobeFribuNus" eType="//Fagunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBogugusBidaguLius" eSuperTypes="//BifrigusaubobubidaCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulaubuguGuLius" eType="//Fagunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebubiDaGusnulaufriFrigusGusguboTor" eType="//AunulaunulAuboboNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBobudabufrigudaBibefriNus" eSuperTypes="//EunulAuGusfrigubiGulus //BadaNulauBoBubiBeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiFribibiBuFriDabees" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubifrifrifridaGuBudatus" instanceTypeName="typeABoboDabidaGuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuFriBiCus" eSuperTypes="//BebiboFriBugubofrinulAufrigusfrinulius //BafribibububefrifrinulaugusgusFritor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauGubeGusgusbudagubonulautor" eType="//DabugusNulauNulautin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBibeDagusbigusdabibebebulus" eSuperTypes="//BadaNulauBoBubiBeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafrigufribiGufrinulAubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuNulAuBebeboBuTus" eSuperTypes="//Didanulaunulaunulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulauguBiDaBiBonulAutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EBuGusaubinulAubenulautus" instanceTypeName="typeDiBebuGufribibudalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaDaBobudaBufrigusBodaBoDanus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audabobedagusGuBobiguNus" ordered="false" eType="//BebenulauBuGunulaubudaDalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnboDafriNulAuboBinulAunus" instanceTypeName="typeAudabetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBebefribiBibinulaugusBeBebigubibeDaLius" eSuperTypes="//BeBobudabufrigudaBibefriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulAuBoBoBibobebobufritus" eSuperTypes="//BifrigusaubobubidaCio //Didanulaunulaunulautor //EuBebefribiBibinulaugusBeBebigubibeDaLius //EudaDaBobudaBufrigusBodaBoDanus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agusbotin" eType="//DobebibibuTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedaBiGusbebebedanus" abstract="true" eSuperTypes="//BifrigusaubobubidaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusgusnulAubeNus" ordered="false" upperBound="-1" eType="//BiBogugusBidaguLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbigusnulAuFrinulaubiGufribelus" instanceTypeName="typeBrAuguBibugufriDafriBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibebeBenulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daFribiNulAubetin" ordered="false" upperBound="-1" eType="//BebenulauBuGunulaubudaDalius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulauBofribobebefribubebubenulauGuLus" ordered="false" eType="//EFriBubuFribubiboGusdaDabuCio" eOpposite="//EFriBubuFribubiboGusdaDabuCio/daBibodaNulAubobebobuDagustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBoGusbigusfriBubiBiDatus" instanceTypeName="typeADafriBeNulaubedabenulauGusbutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfrinulaunulaugusgubeBuGusBucus" eSuperTypes="//DiguBibobubiGusbuBubeFribibibeLus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BanulAugusbogusnulauBees">
    <eLiterals name="DobudanulaufriBoGucus"/>
    <eLiterals name="FafriGusDabuFribelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbegusNulaubitor" eSuperTypes="//BebiboFriBugubofrinulAufrigusfrinulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dadadabubolius" eType="//AnbigusnulAuFrinulaubiGufribelus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlAugufriDaBobutus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGufriBububogustin" upperBound="-1" eType="//BafribibububefrifrinulaugusgusFritor" eOpposite="//BafribibububefrifrinulaugusgusFritor/doBogusAunulaubucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBibogucio" eType="//Eufribebugusaubugustin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBebebuBunulaubebogutus" ordered="false" eType="//BebiboFriBugubofrinulAufrigusfrinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbunulAufrigubiboLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulIus" eSuperTypes="//BafrigufribiGufrinulAubonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusBudafribicus" ordered="false" eType="//EunulAuBoBoBibobebobufritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeGubufrinulauboBedafriTus" eSuperTypes="//BifrigusaubobubidaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babodabigusbobibeguBicus" upperBound="-1" eType="//EuBebefribiBibinulaugusBeBebigubibeDaLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diFriBugubebeguBofrigunules" ordered="false" eType="//EbegusNulaubitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibebiGusBobiBubudatus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraububebodaDabinus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EunulAubudanulauGuses" instanceTypeName="typeDabefribedagusbiBiBuBuDaEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufribefribonulAunulAunulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebeguDabebeGufribulius" instanceTypeName="typeDuBuBiDalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauGubeBiBoguFribunulAucio" abstract="true" eSuperTypes="//EbonulaufriguBoguslius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBubibeBiGugusguboboguGubeGusGuCus" instanceTypeName="typeAgusbibobeguguBegusDabiguNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofrinulAubebigutor" eSuperTypes="//BadaNulauBoBubiBeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edaboNulAuBegunulaubunulaubeLus" ordered="false" upperBound="-1" eType="//AnulauguBiDaBiBonulAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DidaBogufriBofrigubocus" instanceTypeName="typeBebiDabubuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Befrifrigubibegusbibufritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doguDaGusbubibiBotor" eType="//AnbigusnulAuFrinulaubiGufribelus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaubifribudaBuBenulAuBububecio" ordered="false" upperBound="-1" eType="//AlfrinulaunulaugusgubeBuGusBucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BedabeboGuBitin" instanceTypeName="typeBiGusBofriguBudagusGubuBoboguBeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibeBeGuBefribiBeTus" eSuperTypes="//FaGuFriBiCus //AlfrinulaunulaugusgubeBuGusBucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enulaugubenulAugubebecio" eType="//DubifrifrifridaGuBudatus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnGusdagusBibofribeBuGusgucio" instanceTypeName="typeDigufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusaunulaubobedabebeBedaNus" eSuperTypes="//BraububebodaDabinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibibeNulaugudadabidafriLus" upperBound="-1" eType="//EufribefribonulAunulAunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBenulaubugusbiBeBegulius" instanceTypeName="typeEbobugusbebudafridanulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusbiguGusDagubegulus" abstract="true" eSuperTypes="//AlfrinulaunulaugusgubeBuGusBucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudaFriDaboBinulaucus" ordered="false" eType="//DabuGusFriDanulAuBucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Banulaububunulius" eSuperTypes="//Befrifrigubibegusbibufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndagusBibebiBoBoBubilius" eSuperTypes="//EuBebefribiBibinulaugusBeBebigubibeDaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bebibugusnulaulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubeNulaubibuboBoTus" instanceTypeName="typeDuguBiBebidaFriCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubiFridabuguTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufrigusbudaBegusBicus" eSuperTypes="//EbunulAufrigubiboLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusNulius" instanceTypeName="typeAngutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafriBuBeCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFribidaBelius" ordered="false" eType="//Banulaububunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnnulAuGubobibobeGubobecus" instanceTypeName="typeAlgugusgulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBufribidaFribocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbiBoBefriGufrigusgusgubobuTor" eSuperTypes="//BedaBiGusbebebedanus //EbunulAufrigubiboLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulauboBobebicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbifriBibegues" eSuperTypes="//Bebibugusnulaulius //BagusbiguGusDagubegulus //DabuGusFriDanulAuBucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBuFriBufriGustin" eSuperTypes="//EububedaCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Anaugusdadabibububedagutin" instanceTypeName="typeEufrifribudaFritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EFriBubuFribubiboGusdaDabuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBibodaNulAubobebobuDagustor" ordered="false" eType="//BibebeBenulaucio" eOpposite="//BibebeBenulaucio/banulauBofribobebefribubebubenulauGuLus"/>
  </eClassifiers>
</ecore:EPackage>
