<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dufribigudatus" nsURI="http://hub.de/rcore/examples/dufribigudatus" nsPrefix="tG">
  <eClassifiers xsi:type="ecore:EClass" name="DogusboBebigusguBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAufriboBeFribuDabiGuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="difrifrinulaudanulauBeBofriNus" ordered="false" upperBound="-1" eType="//DogusboBebigusguBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BanulauBuboNulaugucus" instanceTypeName="typeDodadadaDaboGutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BafriBiBeTin" instanceTypeName="typeAlbedaGuBobicus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dabebinulaububunus" instanceTypeName="typeFaGuBobecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboDaBeFribeFrigusBebunulius" eSuperTypes="//BrAufriboBeFribuDabiGuTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubobufrigubidabodabebuGuGusaulius" instanceTypeName="typeDibigufrigusBeguboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulAubobuDabenulaugugutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebugusfriGunulauDadabutus" ordered="false" eType="//DogusboBebigusguBilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abiGubeBebeGucio" eType="//DogusboBebigusguBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabigudaBugusbedabetin" abstract="true" eSuperTypes="//BrAufriboBeFribuDabiGuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebeguFrinulauBobodaEs" ordered="false" eType="//AnboDaBeFribeFrigusBebunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboGusdaNulaugusaubeDaGusIus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fafridaFriGusGudaguGugububuGusbotin" eType="//AubobufrigubidabodabebuGuGusaulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBibuBugusbubunus" ordered="false" eType="//BrAufriboBeFribuDabiGuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Digubiboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabenulaugusgusfriTor" eSuperTypes="//BrAufriboBeFribuDabiGuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubibubibobenulauGuGuFrinulaulus" ordered="false" upperBound="-1" eType="//DogusboBebigusguBilius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dofriguslius" upperBound="-1" eType="//Dabebinulaububunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabubiBobeBifriNulaubonulauBubulus" eSuperTypes="//Digubiboes"/>
</ecore:EPackage>
