<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="alcio" nsURI="http://hub.de/rcore/examples/alcio" nsPrefix="gUZ">
  <eClassifiers xsi:type="ecore:EDataType" name="DubeGugusBoBobibugusbegunulautin" instanceTypeName="typeEdabogugusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibiBubifribufriBonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabiGusgusbuCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudabububunulauBoNulAuCio" eSuperTypes="//AlbibiBubifribufriBonus //DabiGusgusbuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alboGuguguFrinulauCio" eType="//DubeGugusBoBobibugusbegunulautin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBebifribudaguDaes" ordered="false" eType="//DabiGusgusbuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Dobebobues" instanceTypeName="typeEugudaBudabogugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudanulaubegusDabedabeBicio" eSuperTypes="//DabiGusgusbuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBiBobunulAuGugulius" upperBound="-1" eType="//DubeGugusBoBobibugusbegunulautin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibubiBobobenulauCio" upperBound="-1" eType="//EugusDaFribelius" eOpposite="//EugusDaFribelius/euGusGuBebuBinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dobebodanulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebubodagusaubobeCio" ordered="false" upperBound="-1" eType="//AlbibiBubifribufriBonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboGusGusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBedaFribeguBeNulaubebeLus" upperBound="-1" eType="//BraudanulaubegusDabedabeBicio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulAunus" eType="//DoBebogubebuBinulIus" eOpposite="//DoBebogubebuBinulIus/befrinulAuGusGusgufridafritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusgusGusdaDagusgusbubiBoBuCio" eSuperTypes="//EudabububunulauBoNulAuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabibubedabobobeBigusGusaugustor" eType="//Dobebobues" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBubidagustin" ordered="false" eType="//EudabububunulauBoNulAuCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebuBefrinulaugudaBedaBues" ordered="false" eType="//DabiGusgusbuCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daboBububinulaufriLius" ordered="false" upperBound="-1" eType="//FaGusfriGububuFribugusnulius" eOpposite="//FaGusfriGububuFribugusnulius/enulaubebebuBoboGubeBinulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBibigucio" eSuperTypes="//AlbibiBubifribufriBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulauGusnulaubigusgudabibeTus" ordered="false" upperBound="-1" eType="//Dobebodanulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiFriFribobibinulAunulaubenulEs" instanceTypeName="typeAlaugusgusBubobinulaugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaudanulaugusBufrifriCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anDagubiboGunulaufribiBidafritor" ordered="false" upperBound="-1" eType="//Dobebodanulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbenulauBugusbocio">
    <eLiterals name="AlBugubigusGuGusaubidafries"/>
    <eLiterals name="Anulautin"/>
    <eLiterals name="BinulaubebiFribenus"/>
    <eLiterals name="DiFrinulauguDabidaGusbubecus"/>
    <eLiterals name="BibiGubeBofriNulaulus"/>
    <eLiterals name="Aldagusfribilus"/>
    <eLiterals name="AnauFribulius"/>
    <eLiterals name="EdafriBifriGusbigusguBotor"/>
    <eLiterals name="Donulaugucio"/>
    <eLiterals name="BebidadagusAufrinulaugusbeBotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaFridabeboGusnulaucio" eSuperTypes="//AgusgusGusdaDagusgusbubiBoBuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="didanulauBibitin" eType="//DiFriFribobibinulAunulaubenulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboNulAubofridanulaudaBobebidagusgusFrilius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubuBibobiGusboGusbiBiDatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabibibubogubeDaGugusDabogusaulius" abstract="true" eSuperTypes="//BrAuBibigucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bi"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribububunulauFrifribibebolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulAubiGusgugudabegunulaulius" ordered="false" eType="//Dogugusbunulaunulaubobutor" eOpposite="//Dogugusbunulaunulaubobutor/abegububeboTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaDadaboBuBibudaNulauBefribudabeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidagubuBuBoGusbutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egunulautus" ordered="false" upperBound="-1" eType="//Bi"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faboBuBifriGusbuBegusBinus" eType="//Dobebobues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dogugusbunulaunulaubobutor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="didaboBelius" eType="//DubeGugusBoBobibugusbegunulautin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abegububeboTor" ordered="false" upperBound="-1" eType="//AlfribububunulauFrifribibebolus" eOpposite="//AlfribububunulauFrifribibebolus/benulAubiGusgugudabegunulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabibugubeboBunulAufribocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagubuBobodabeDaGuGubuguslius" eSuperTypes="//BinulaudanulaugusBufrifriCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBebogubebuBinulIus" eSuperTypes="//FabibibubogubeDaGugusDabogusaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befrinulAuGusGusgufridafritor" ordered="false" eType="//EuboGusGusnus" eOpposite="//EuboGusGusnus/binulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgudabuNulAulus" eSuperTypes="//AgusgusGusdaDagusgusbubiBoBuCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BabedabeFrifrinus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FabedagubuBoGugusbefrinulEs">
    <eLiterals name="AlBifribuBenulauNules"/>
    <eLiterals name="BefrifrinulauFrinulaugusGufrinulauGuBitor"/>
    <eLiterals name="AnGuBebobigusgusfrinulAuGusaudatus"/>
    <eLiterals name="Dudafrinus"/>
    <eLiterals name="AngusguGusgububegubeEs"/>
    <eLiterals name="Dugusdadadabofribobibitor"/>
    <eLiterals name="DibunulaunulAuBees"/>
    <eLiterals name="AbenulaudaguGuGufrinulauGusfriButus"/>
    <eLiterals name="Dadabocio"/>
    <eLiterals name="DibogusbigusGubububees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FagusgusfriGusnulaugusfrifriBufribuFridanus" instanceTypeName="typeBafriguGusguBeGuBubetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibinulauDagusboTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbiDagunus" eSuperTypes="//FagubuBobodabeDaGuGubuguslius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EnulAubeBoguGuFrigusAuguBolius" instanceTypeName="typeDidaDaBobifribolus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AugusdaGuBenulAudabiNulauguBubolius">
    <eLiterals name="AnbedaBinulaudagusaufribubilus"/>
    <eLiterals name="BabubifrigusbuCus"/>
    <eLiterals name="DoNulaubenulaubeBiFriguBonus"/>
    <eLiterals name="DiBoGusGubuGusTus"/>
    <eLiterals name="AunulauBuGubiBoGubolius"/>
    <eLiterals name="AnNulaugusfribeBotin"/>
    <eLiterals name="AlauGusbebuGubuGuFridaGuDaNus"/>
    <eLiterals name="AgusfridaBegugusBuBoes"/>
    <eLiterals name="Agusbenulautor"/>
    <eLiterals name="EfridaFribubinus"/>
    <eLiterals name="BaGubibigusauBoGusFrigutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusguFriNulaudacio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubiNulaugunulauBebegugusaubedadanus" instanceTypeName="typeBabubuBiBiBonulauGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braubebofrilius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusfriGububuFribugusnulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGusbedabefrinulauCio" ordered="false" upperBound="-1" eType="//FagubuBobodabeDaGuGubuguslius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulaubebebuBoboGubeBinulEs" ordered="false" upperBound="-1" eType="//AgusgusGusdaDagusgusbubiBoBuCio" eOpposite="//AgusgusGusdaDagusgusbubiBoBuCio/daboBububinulaufriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBuBiFriDafriNulaudabetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulaudabubidabecus" ordered="false" eType="//DabiGusgusbuCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusbubigusaugutin" ordered="false" upperBound="-1" eType="//AlfribububunulauFrifribibebolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusbugusbonulaubuBelius" eSuperTypes="//Braubebofrilius //EbiDagunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBebubues" eType="//FabedagubuBoGugusbefrinulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrifriGusauNulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBobogusbogubitin" ordered="false" eType="//EuboGusGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAunulAugusguboBoBies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeguGuBogusdafriBefribubifriboguguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubuBegubefrigudaGugusbiGusdacio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlgubunulAubidatin">
    <eLiterals name="AlbodafribeBibinulaulius"/>
    <eLiterals name="BrAubeDabuGugufriCio"/>
    <eLiterals name="DabeguGugubigusbibelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bebedanulaunus" eSuperTypes="//DoBebogubebuBinulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubidaBeBegusbonulAuFriDaGunulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abodaGusbibogusNulauguGuTor" eType="//FabibugubeboBunulAufribocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fadafrinulaufribogutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabonulAubegusgusgusnulauFriBubuFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulAunulautus" eSuperTypes="//BraudanulaubegusDabedabeBicio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiBibobegusbuBebiBoboguEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodadagudabeFribuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusDaFribelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGusGuBebuBinus" upperBound="-1" eType="//BraudanulaubegusDabedabeBicio" eOpposite="//BraudanulaubegusDabedabeBicio/dibubiBobobenulauCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusNulaunulauBitus" ordered="false" upperBound="-1" eType="//FaGusfriGububuFribugusnulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abifrifrinulauTin" eType="//DiBibobegusbuBebiBoboguEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="efrifridadaguGusnus" eType="//FaGusfriGububuFribugusnulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfribuBigunulauguslius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AudabeBibubibeDabenules" instanceTypeName="typeDunulAuBunulaubefrifrigutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AfriBofriFrinulaudadafrifriBubobicio" instanceTypeName="typeDugusdanulauDafrinulAuNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusgusBigusBobunulius" instanceTypeName="typeAlbufrinulaubiBifridaDabinus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FanulAuBeNulaugues" instanceTypeName="typeEnulaunulaubeBedacus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FafribububogusBuNulaucio">
    <eLiterals name="EFribuguNulauDagugutor"/>
    <eLiterals name="FabebudafriBoBocio"/>
    <eLiterals name="AlDaDanulaugutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Babenulaulius" abstract="true" eSuperTypes="//Bebedanulaunus //Dobebodanulius //Bi">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabifridafridaboBetus" eType="//DiBibobegusbuBebiBoboguEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnBefrifriBibubunulaubuGugusTor" instanceTypeName="typeFanulauGusnulaubeBeguslus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BigubibuBunulAuGusbenus" instanceTypeName="typeAlNulAuFrinulauFriguBugucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBonulauguBegudaBigusDanus" eSuperTypes="//AgusgusGusdaDagusgusbubiBoBuCio //DodadagudabeFribuTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauFrifribobuGuNulius" ordered="false" eType="//DiboNulAubofridanulaudaBobebidagusgusFrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebuBedagusbugusAuFrinulautus" eSuperTypes="//AfribuBigunulauguslius //DodadagudabeFribuTor //DoBebogubebuBinulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagusbifrigubecus" eType="//AnbenulauBugusbocio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBubudanulaudanules" ordered="false" eType="//BrauBuBiFriDafriNulaudabetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeFribegunulauBocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulAuBufribefriboGusaunus" ordered="false" upperBound="-1" eType="//BabonulAubegusgusgusnulauFriBubuFritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulaubogusdagufrifrifriDalus" eSuperTypes="//DabiGusgusbuCio //FaGusfriGububuFribugusnulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuBibobonulAuboGubuBuLius" eSuperTypes="//BrauBuBiFriDafriNulaudabetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauDagusbuDaguGusdabuLius" ordered="false" eType="//EuboGusGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AngusNulauGusgusFrinulaubucus" instanceTypeName="typeBrAuBiFribuBiFribufribeBuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaububifriBebifrigusBuBeguGuboFries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edabibedagusfrifrinulauDaGugusDabefrinulius" upperBound="-1" eType="//DogusgusBigusBobunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbugufriBofriGusdaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibugusguBogustor" eSuperTypes="//Bi"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusbinulAubulius" eSuperTypes="//BibugusguBogustor //BraudanulaubegusDabedabeBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbebeboGuFriBofribebogusbugusAucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babegudadanus" ordered="false" upperBound="-1" eType="//Dobebodanulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulaubuBibubolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudadabofridabues" ordered="false" upperBound="-1" eType="//BidagubuBuBoGusbutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGunulaugubuBobulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angubuBegusbofrigulus" ordered="false" eType="//BrauBuBiFriDafriNulaudabetor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebuFriNulaugusgusgusauNulaubotus" eType="//DaDadaboBuBibudaNulauBefribudabeTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulauFriguBugubiEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubugufrinulauguGubuBoLus" ordered="false" upperBound="-1" eType="//EbiDagunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebeBibubububofriBedaCio" abstract="true" eSuperTypes="//BrAuBibigucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubibibugubifrifribetin" eType="//BabedabeFrifrinus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
