<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dutor" nsURI="http://hub.de/rcore/examples/dutor" nsPrefix="XT">
  <eClassifiers xsi:type="ecore:EClass" name="EguBoBeNulaubifriGusbeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogusfribebebeDadabuguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biFriguGusnulEs" ordered="false" eType="//EguBoBeNulaubifriGusbeLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlAunulAugusgusaubuGusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBebiDabudadalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didaBubidagusbubenulAubucus" ordered="false" eType="//AnDaBugusdabigubulius" eOpposite="//AnDaBugusdabigubulius/albifrigusdaguboBibefrigutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabugusdaGusgusBubugusbuBecio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebeBobebodaBotus" ordered="false" eType="//DiBigusgusbiFriGubiLus" eOpposite="//DiBigusgusbiFriGubiLus/auBudadagugudaBubuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlGubuBuBelus" abstract="true" eSuperTypes="//EguBoBeNulaubifriGusbeLius //DabugusdaGusgusBubugusbuBecio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBegubiBebedabidatus" ordered="false" upperBound="-1" eType="//AlAunulAugusgusaubuGusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBoFriDaGusboguslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusDafrigusFribuBeGucio" eType="//DogusfribebebeDadabuguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobogusfriFrifrifribufribugusLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbibutin" eType="//DaBebiDabudadalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigubifriNulaubifrigubilus" ordered="false" eType="//DaBebiDabudadalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubeDagudaguBinules" ordered="false" upperBound="-1" eType="//BibiDaBibobiboDadabuEs" eOpposite="//BibiDaBibobiboDadabuEs/befridabudaGusboDaBufriboNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugufriDaGusDagugulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubebogusbeBedaBugubeFriBebotus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabuGubegusgusfribetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiboBugugubefridaes" ordered="false" eType="//BiboGusbifriNulaudabiCio" eOpposite="//BiboGusbifriNulaudabiCio/doNulaububeGusbilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Algubebebobogusbitin" eSuperTypes="//AugufriDaGusDagugulius //EguBoBeNulaubifriGusbeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algusgusGulus" ordered="false" eType="//DabugusdaGusgusBubugusbuBecio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulauBobiboboGues" ordered="false" eType="//AugufriDaGusDagugulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidabibubuBigusgudabotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBubibegufriDaNulAunus" eSuperTypes="//EguBoBeNulaubifriGusbeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeDagusbebifribegusBoFriBoBeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBebenulauGusgufribufrigubibonus" ordered="false" eType="//DaBebiDabudadalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedabebebuGusbues" eSuperTypes="//DabugusdaGusgusBubugusbuBecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibiDaBibobiboDadabuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befridabudaGusboDaBufriboNus" ordered="false" upperBound="-1" eType="//DobogusfriFrifrifribufribugusLius" eOpposite="//DobogusfriFrifrifribufribugusLius/aubeDagudaguBinules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ABoFriBibeBofrinules" instanceTypeName="typeAunulaubuBiguBiBubuguDabilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebufrigusbigusgububudabiNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabebebuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubeDabobogusbuBubefrifritus" ordered="false" upperBound="-1" eType="//AugufriDaGusDagugulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboGusbifriNulaudabiCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doNulaububeGusbilus" eType="//BabuGubegusgusfribetor" eOpposite="//BabuGubegusgusfribetor/fabiboBugugubefridaes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duboBinulaugusnus" eType="//ABoFriBibeBofrinules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufriGuDadaGusdabeBebeEs" eType="//ABoFriBibeBofrinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubufriboDafribubeNulauDaBeFrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alauboboguscus" ordered="false" eType="//FabebebuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Braugunus" instanceTypeName="typeDoGudadagusbidafrifriboboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubigubegusbeBegubibigusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbibinulauFribuFribefrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobiBebobegutin" ordered="false" eType="//BeBubibegufriDaNulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBigusgusbiFriGubiLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBudadagugudaBubuEs" eType="//DabugusdaGusgusBubugusbuBecio" eOpposite="//DabugusdaGusgusBubugusbuBecio/ebeBobebodaBotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugubenulAuBoLius" abstract="true" eSuperTypes="//DogusfribebebeDadabuguslius //AlGubuBuBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulauNulAuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusbeBiBogusIus" eSuperTypes="//DidabibubuBigusgudabotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGuguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafribigunulaubiGusbobifrilius" ordered="false" upperBound="-1" eType="//BeDagusbebifribegusBoFriBoBeLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubiNulAugusgubiBuDafrilus" ordered="false" eType="//FabebebuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabibenulauguFriguBiDagubobodabucio" abstract="true" eSuperTypes="//DabugusdaGusgusBubugusbuBecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABidagusaunulAuGusbebudaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="EFrinulauBunulaufriBodaBudabolus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBenulAuBigugubudaBiDaTin" eType="//BebufrigusbigusgububudabiNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaubuBifrigusnulAuBuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuboguBeTin" ordered="false" upperBound="-1" eType="//BabuGubegusgusfribetor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibibibebegucus" eType="//ABoFriBibeBofrinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBuGusGusBecio" eSuperTypes="//EguBoBeNulaubifriGusbeLius //EubufriboDafribubeNulauDaBeFrilus //AugubenulAuBoLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBedaDaGusbuBobobeTor" ordered="false" eType="//BeDagusbebifribegusBoFriBoBeLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dabobebubinules" eSuperTypes="//BedabebebuGusbues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGusgusbonulaugusfridanus" ordered="false" eType="//DiBigusgusbiFriGubiLus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auBobibugusgusdabecus" upperBound="-1" eType="//Braugunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBufrigusDaGusGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBobiNulAuBegusDabegusBolus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubifriFridaBubidaFritin" instanceTypeName="typeDadabunulaubiFribiBuBuboes"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AgusboguBogudaLius" instanceTypeName="typeBeNulAububidaboFriBuGusnus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DibuBobebeBinulaububenulAuBiTin">
    <eLiterals name="BibiBubuGusGuNulAubuTus"/>
    <eLiterals name="DiNulaufribobuBiboNulIus"/>
    <eLiterals name="AbufriboFriBenulAuBiLus"/>
    <eLiterals name="AnbuBiBogubogufrigubeguTor"/>
    <eLiterals name="DogusboboBobebegusauBiNus"/>
    <eLiterals name="EubinulAulius"/>
    <eLiterals name="BebiDaBulius"/>
    <eLiterals name="Albodabonulius"/>
    <eLiterals name="BrAuBeBeNulauGusNulaubenulaubidanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabeDadaBufriBocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EFrigudagunulauDaguBiTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubububobiGusbeGufribues" ordered="false" upperBound="-1" eType="//BrAubebogusbeBedaBugubeFriBebotus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubegusgusbiDabegusEs" ordered="false" eType="//EFrinulauBunulaufriBodaBudabolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaguBibiguDadagusAufrinulAutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigudabigusaubiGuBodaBodaGucio" eSuperTypes="//EFrigudagunulauDaguBiTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiFribifriTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beFrigusnulaubefrilus" upperBound="-1" eType="//ABoFriBibeBofrinules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusdabibilius" ordered="false" upperBound="-1" eType="//EGuguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgugudadafriNus" eSuperTypes="//BeDagusbebifribegusBoFriBoBeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulaunulaunules" eSuperTypes="//BiFribifriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusauBuGusgusnulautus" eSuperTypes="//EguBoBeNulaubifriGusbeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubiFrifriDaGuBuNus" ordered="false" upperBound="-1" eType="//EGuguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaufridaBuboBobebuDabonus" eSuperTypes="//AlAunulAugusgusaubuGusEs //AunulaubuBifrigusnulAuBuLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doboFrinus" eType="//ABoFriBibeBofrinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGubodaguBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBiGusaugububuBoNus" abstract="true" eSuperTypes="//EguBoBeNulaubifriGusbeLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusGusauguGusbegusNulaunules" instanceTypeName="typeDunulauFribedanulAuGusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubedafrigusfriLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaDafrigusNulaudaFribucio" ordered="false" eType="//AuBiGusaugububuBoNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusNulaubebuBudagubobeCus" eSuperTypes="//AlGubuBuBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadadagugufrigusBoFriGugudaGuslus" eSuperTypes="//BedabebebuGusbues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBibubuNulauBefrigubonulIus" eType="//AunulaubuBifrigusnulAuBuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBuBigusnulaudagusBolius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbububebofriDagugusBeBibigusnus">
    <eLiterals name="EuBobufriboBugusauBucio"/>
    <eLiterals name="AuBunulaubiGusbubuGusfriEs"/>
    <eLiterals name="ABinulAudagusaubies"/>
    <eLiterals name="BinulauBobuNulAuDaguBunulaulus"/>
    <eLiterals name="BrauBobebibofrinulaubebulus"/>
    <eLiterals name="BabofriBogusBuBegusFribocio"/>
    <eLiterals name="BeBuFribigusDabobobeGulius"/>
    <eLiterals name="BraugusbobeBuFridaButor"/>
    <eLiterals name="EboBuguGuNulauBigusdafribudaBufrigusfriLius"/>
    <eLiterals name="DabeBogusaudabeNus"/>
    <eLiterals name="EunulaudaNulaugunus"/>
    <eLiterals name="BraubeNulaulus"/>
    <eLiterals name="DiDabobibubebeguGusbeBufrigusnus"/>
    <eLiterals name="BrauboFribugusfridaGusbubebuDabubelus"/>
    <eLiterals name="DagusbibuBodaBibitin"/>
    <eLiterals name="BraunulaugusBonulius"/>
    <eLiterals name="BrauBobobuGusbofribeboBiLus"/>
    <eLiterals name="BagusBudaFriNulaunulauFriGusaubinulauGustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabenulaufribuBigusBecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbebibeBebiBecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBoFrifribucus" ordered="false" upperBound="-1" eType="//BeBubibegufriDaNulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBifrigusfriBuBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusbunulAunulAubefridabiDaTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beboLius" eType="//DubifriFridaBubidaFritin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbigusBuBinulauGubonulaufritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbobudaNulAuGubudafrigusBugusgusboEs" ordered="false" eType="//EgusbunulAunulAubefridabiDaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauBobiguDabebiDaguGubolus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulAuGusfriguguBobiEs" upperBound="-1" eType="//AnbububebofriDagugusBeBibigusnus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbubeboBonulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusfribubedanulEs" eType="//DibuBobebeBinulaububenulAuBiTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBudadaGusbunulAugusgubues" instanceTypeName="typeDoboBiNulAuboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulAubonulAuFribodafriGuses" eSuperTypes="//AnbibinulauFribuFribefrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusdabunulAucus" ordered="false" eType="//DaBebiDabudadalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugunulauBibigucio" ordered="false" upperBound="-1" eType="//DuBufrigusDaGusGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndaGuGusGusboGusbigusgubecus" eSuperTypes="//AugubenulAuBoLius //EubufriboDafribubeNulauDaBeFrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGuBeNulAuBodabicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anFrifriFriNus" ordered="false" upperBound="-1" eType="//BiboGusbifriNulaudabiCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faNulauBobububeNulautus" ordered="false" eType="//AunulaubuBifrigusnulAuBuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibufridadanulAuboDagunulAuguBufridaBibitus" eSuperTypes="//BiBuGusGusBecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnDaBugusdabigubulius" eSuperTypes="//EGuguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albifrigusdaguboBibefrigutus" ordered="false" upperBound="-1" eType="//DaBebiDabudadalus" eOpposite="//DaBebiDabudadalus/didaBubidagusbubenulAubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AbiBebiBunulauGuGusfriguTus" instanceTypeName="typeAboboBebuFriBibonulaubibuBiBibocio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAuBubobiGusfribuguBiButor" instanceTypeName="typeBraugusFrinulaubiguTus"/>
</ecore:EPackage>
