<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dabegusdatus" nsURI="http://hub.de/rcore/examples/dabegusdatus" nsPrefix="rM">
  <eClassifiers xsi:type="ecore:EClass" name="BefriBibufridalus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBugusdabegufriboes" instanceTypeName="typeAlnulauGuGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauboDagusbeCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufrigusnulIus" ordered="false" upperBound="-1" eType="//BefriBibufridalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudabobibebinulaubedabubuNus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beFrinulAubufribugugusbidanulAutus" ordered="false" upperBound="-1" eType="//BefriBibufridalus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binulaufriguBeboGusbiNulauNus" eType="//BiBugusdabegufriboes" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBogusGuNulauDabubocio" eSuperTypes="//EudabobibebinulaubedabubuNus //BrauboDagusbeCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubugusaubiBifrilius" eType="//BiBugusdabegufriboes" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
