<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fabobobofrilius" nsURI="http://hub.de/rcore/examples/fabobobofrilius" nsPrefix="k">
  <eClassifiers xsi:type="ecore:EClass" name="EubegusnulaugusfriGutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBobonulAucio" instanceTypeName="typeAlbeboBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaugusGuNulauGusgusBuTor" eSuperTypes="//EubegusnulaugusfriGutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiguBoGubugusboguGusbinulaugufrigusbibucio" eSuperTypes="//AnaugusGuNulauGusgusBuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauGuGusboguBiTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibibugunulAufrinulAuLius" ordered="false" upperBound="-1" eType="//AnaugusGuNulauGusgusBuTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBufrifrigusbinus" upperBound="-1" eType="//AlBuBoBiNulaubebeguslius" eOpposite="//AlBuBoBiNulaubebeguslius/dibuFrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Dibocus">
    <eLiterals name="DobedagusdaNulauGudatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusgubuBuGuBubeFriLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiNulAubobidacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusbebeguBubiGudabubicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiBobegusbeFribubutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbidafribudabonulius" ordered="false" eType="//AnaugusGuNulauGusgusBuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauBibuBenulauboCus" instanceTypeName="typeDafrigufrinulAunulauboTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauGugusgusfriFrifriBotin" instanceTypeName="typeEbinulAubunulAubinulIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubiBofrifrifriGusnus" instanceTypeName="typeAnGusgusnulauDaFriFriCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBidaFrigusboboNulaucus" eSuperTypes="//BanulauGuGusboguBiTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusBeGusfriGues" eSuperTypes="//AnaugusGuNulauGusgusBuTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaufriboboBonulAunulaugusDator" ordered="false" upperBound="-1" eType="//AubiBobegusbeFribubutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABiBedadabuDaGusEs" eSuperTypes="//AnaugusGuNulauGusgusBuTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusDafribibobiGuBugusfribofriEs" upperBound="-1" eType="//BrauBibuBenulauboCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubiBifribugusGusBobuBiboBigusbuGuLus" eSuperTypes="//DiguBoGubugusboguGusbinulaugufrigusbibucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuboGusbebeGusguEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBobenulaubiBonulAuTin" eType="//DiBobonulAucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faDaBeDabibobefrigusnulauBebiboCio" upperBound="-1" eType="//BanulauGuGusboguBiTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="didafrifribudacio" ordered="false" upperBound="-1" eType="//EudabiGufrigues" eOpposite="//EudabiGufrigues/biBiFrigusgubufrinulaugusTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bifrifrifribecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euFriGusgusbiBubebuDaBibugustor" ordered="false" upperBound="-1" eType="//DubiBifribugusGusBobuBiboBigusbuGuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgusAubebobogusFriBuGusAugusbiLus" instanceTypeName="typeFabiBubuBubuDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebidagusBibiBies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebebidabiCio" ordered="false" eType="//BiGusbebeguBubiGudabubicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBuBoBiNulaubebeguslius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibuFrilius" ordered="false" upperBound="-1" eType="//BanulauGuGusboguBiTin" eOpposite="//BanulauGuGusboguBiTin/daBufrifrigusbinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBubunulAuDabubebicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBogusgugunulAubebutus" ordered="false" upperBound="-1" eType="//AlBuBoBiNulaubebeguslius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebufribibuGubucus" ordered="false" upperBound="-1" eType="//EubegusnulaugusfriGutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbenulaufribufribiBiCio" eSuperTypes="//AlBuBoBiNulaubebeguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbobofrifrinulaugusBedaCus" eSuperTypes="//AnaugusGuNulauGusgusBuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAuguFribebiDagubebedadanulAutus" abstract="true" eSuperTypes="//BagusgubuBuGuBubeFriLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgusNulaubububobufriBinules" instanceTypeName="typeAnBenulAuBucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Augufrifribubibebonulaulus" instanceTypeName="typeBibugucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauGuFriBububofributor" eSuperTypes="//EuboGusbebeGusguEs"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauDaGusnulaubinulauBubecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuguBebogusnulauGunulAubeBinulEs" instanceTypeName="typeBrauboNulauGunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBuBigusBibofriGusGusBulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuGusbibenus" instanceTypeName="typeFagusdabuGutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebiGuNulaufriBuboTus" eSuperTypes="//BiBubunulAuDabubebicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusaubebefriGuGubefrigutus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EbefriBibobobuBicus">
    <eLiterals name="DiBeguGusgusaubudagubogusBibitus"/>
    <eLiterals name="DifribeBogusNulaunulauBugusBiBucio"/>
    <eLiterals name="BaNulauDaBedagusbebubofribues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBigusbofriBubebebunulauTor" instanceTypeName="typeBiBebiNulauguBebifritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbinulauBububifridanulaubuNulaucus" eSuperTypes="//BagusgubuBuGuBubeFriLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusbobiguBoBoBoEs" upperBound="-1" eType="//BagusgubuBuGuBubeFriLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBuBidabeNulauboBiBugutor" eSuperTypes="//AlBuBoBiNulaubebeguslius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugubebelus" eType="//DuGusbibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaudaBuTus" eSuperTypes="//EunulauGuFriBububofributor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBigusfridaGusGusbidaTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebiBubiFrinulauBigusFriguDabotin" abstract="true" eSuperTypes="//BanulauGuGusboguBiTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBiFrifriTor" ordered="false" eType="//ABiBedadabuDaGusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAuboguGunulaufricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibidabodanulaubedaBotus" eSuperTypes="//BebiGuNulaufriBuboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBubegutor" eSuperTypes="//ABiBedadabuDaGusEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBefribubefries" eType="//DubiBofrifrifriGusnus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuboBudaGunulaububuNus">
    <eLiterals name="BrauFribogugusDaDaBidaBubocus"/>
    <eLiterals name="EgusBonulaudabubeGusBeGusGusNulAucus"/>
    <eLiterals name="EugubibidafrinulAubegusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofridanulAugusBobebeBinulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaDaFrigusFriguDafrinulAubigusTor" instanceTypeName="typeBiDadaFribeFriBolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabibuBogudaFriboFrifrilius" eSuperTypes="//AuGusBeGusfriGues"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudabiGufrigues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBiFrigusgubufrinulaugusTus" ordered="false" eType="//EuboGusbebeGusguEs" eOpposite="//EuboGusbebeGusguEs/didafrifribudacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AngusbiDaboBobebodagusDatus" instanceTypeName="typeBedaFriGufribunulaucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DofriBobinulAunulAudaGugusaubiTin" instanceTypeName="typeDibebenulaugusnulauguDafriLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebibodanulaufribidaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBifridafriBeLius" eSuperTypes="//AlBuBoBiNulaubebeguslius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BedagudanulAuDabuFriNus">
    <eLiterals name="Dinulaubinulaufributin"/>
    <eLiterals name="AbidanulaubodagusbefriFriFritin"/>
    <eLiterals name="DaboFribubuBiBinulauBuCio"/>
  </eClassifiers>
</ecore:EPackage>
