<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fabolius" nsURI="http://hub.de/rcore/examples/fabolius" nsPrefix="EHBf">
  <eClassifiers xsi:type="ecore:EDataType" name="AububuguBobuguCio" instanceTypeName="typeAnNulauBunulAudafriFrinulaugusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbubedaGuBebuBetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaboBebenulAuTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBeGudanulaudaBeNulauBuBoguBuTus" upperBound="-1" eType="//AlbubedaGuBebuBetus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusbiNulaubenus" ordered="false" eType="//AlbubedaGuBebuBetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulauBigubodaEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoNulAuBeBeboBuBeguBeCus" instanceTypeName="typeAlnulAuBonulaubobubufribonulaubuDacus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AunulAudaDadagusaufribuDaFrigusCus" instanceTypeName="typeBabigugucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoguBoBobefriTor" eSuperTypes="//AlbubedaGuBebuBetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabigubutor" ordered="false" upperBound="-1" eType="//BraunulauBigubodaEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeguFriDabuGubinulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBidanus" eType="//AunulAudaDadagusaufribuDaFrigusCus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbedafribuBugusgusGusfritor" eType="//AunulAudaDadagusaufribuDaFrigusCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABobiBudagudacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBuFriBiGusgugusguGusLus" abstract="true" eSuperTypes="//DaboBebenulAuTus //BeguFriDabuGubinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaudafriDabegusBuTin" eSuperTypes="//ABobiBudagudacio //EBuFriBiGusgugusguGusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFrigubedanulAubeBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diboboDagusboboDaguslius" upperBound="-1" eType="//DaboBebenulAuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiGusbubigusTin" instanceTypeName="typeEnulauFrigusbebebeguDagues"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBubuBeDaBibobeGugusbuLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabodagusboFrigudaBeBeNulauLus" instanceTypeName="typeAlbonulaudafriFribebiBolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubuBibodaBegugusbegues" eSuperTypes="//AnulaudafriDabegusBuTin //BiBubuBeDaBibobeGugusbuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusnulAunulaubofribubebiGusgusnules" eSuperTypes="//AlbubedaGuBebuBetus //EBuFriBiGusgugusguGusLus //BraunulauBigubodaEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aguFrigusbufribiguBoTin" ordered="false" eType="//DaboBebenulAuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonulAuGusbifribugubuguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusbuboFribinulAubiDalius" abstract="true" eSuperTypes="//BeguFriDabuGubinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabuguBoBebudatus" eSuperTypes="//BiBubuBeDaBibobeGugusbuLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobufridabobeFriGusfrinulAufriTin" instanceTypeName="typeDoFriFrinulAuBibuGuguguguDabucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlfridaGububebiFribonus" instanceTypeName="typeFabigugufridaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabuguDabugusdagunulaugugunulAuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbenulaunulAuNus" eType="//AububuguBobuguCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaboBudagusAuBugusdaGucus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibofribibiFriGusGusdafriLius" eType="//DiGusbubigusTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlnulauBebuGubiBefrinulauTus" instanceTypeName="typeDubobeBobedaBubogugusbedabucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnfriBuGufrinulius" instanceTypeName="typeFagusBoguNulaubeBunulAucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaguBugusNulauBegusGustor" instanceTypeName="typeFabubiguNulaububibugulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBidaGusbebutus" instanceTypeName="typeBraubiDaguBicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbufribogusnulIus" eSuperTypes="//FabuguBoBebudatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euNulaubugusGusboBogubudanus" ordered="false" upperBound="-1" eType="//BiBubuBeDaBibobeGugusbuLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabiNulius" upperBound="-1" eType="//DonulAuGusbifribugubuguLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusDafriBoBodabugusauGutor" eSuperTypes="//DaboBudagusAuBugusdaGucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusAuguBiBeguBeboboLius" eSuperTypes="//AlbubedaGuBebuBetus //BiBubuBeDaBibobeGugusbuLus //BeFrigubedanulAubeBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifrifriguFribebubobunulaubugusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaFrigusBeBunulaugubiNus" ordered="false" upperBound="-1" eType="//DoguBoBobefriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbiBuBidadaDafridaTin" abstract="true" eSuperTypes="//AlbufribogusnulIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuGusbelius" instanceTypeName="typeFaFrifrifrifrifriBibunules"/>
</ecore:EPackage>
