<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fa" nsURI="http://hub.de/rcore/examples/fa" nsPrefix="T">
  <eClassifiers xsi:type="ecore:EClass" name="FafridagusbonulAubuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofribubibiDabinulauBeBedaDanulius" eSuperTypes="//FafridagusbonulAubuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBiDagusbuDaguGuboBoGusAucio" abstract="true" eSuperTypes="//FafridagusbonulAubuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFrigusbiFriGudadanus" eSuperTypes="//DofribubibiDabinulauBeBedaDanulius //EuBiDagusbuDaguGuboBoGusAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlFrinulAuGusgusIus" abstract="true"/>
</ecore:EPackage>
