<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="an" nsURI="http://hub.de/rcore/examples/an" nsPrefix="qu">
  <eClassifiers xsi:type="ecore:EClass" name="AlBuNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobiBidabeguGuguguCus" instanceTypeName="typeEbedabinulaudabibigusgusguguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alaugusnulaugusfries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusgusBugubobuFriguTin" eType="//DobiBidabeguGuguguCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusFriGuFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAubinulAuguscus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EguGuboguBibeGunulaufrilius">
    <eLiterals name="BebiDabuGusauDaFribuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlFriguboGugusbonus" abstract="true" eSuperTypes="//Alaugusnulaugusfries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diGuBebuFrifrigusFribefrinulAuBubiDabobiGuEs" eType="//EguGuboguBibeGunulaufrilius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribiBedaBigusaubuBudanus" ordered="false" eType="//Alaugusnulaugusfries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubuBuguguNulautin" eSuperTypes="//BaGusFriGuFritor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibidaguGusboguCio" eType="//DobiBidabeguGuguguCus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulaubeBugubibeBiEs" eType="//AlBuNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBogugusbebidagusfriDafrigusguTus" eSuperTypes="//BenulAubinulAuguscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EBobeNulaugubeCio" instanceTypeName="typeBinulAuGusBibefribiguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abogunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faboBobedabugubibugusgusFriNus" ordered="false" eType="//AlFriguboGugusbonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusGusbuBibobidacus" eSuperTypes="//Alaugusnulaugusfries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euBubuDafritin" eType="//DobiBidabeguGuguguCus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beGusbeFriNulAutus" eType="//EguGuboguBibeGunulaufrilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBoguBogusGusAuTin" eSuperTypes="//BrauGusGusbuBibobidacus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DidabigugusbeNulAubidafribegulius">
    <eLiterals name="BibufribufrifrinulaugubofriGunulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabuguDabibudaboNulaunulauTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beboguDabinus" eType="//DidabigugusbeNulAubidafribegulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBinulAuBiBigulius" ordered="false" upperBound="-1" eType="//BraubuBuguguNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbegusbuboFribuCio">
    <eLiterals name="BeBoFrigusbonulautin"/>
    <eLiterals name="AnNulaugusGugubinulaubebilus"/>
    <eLiterals name="Dufribubudatus"/>
    <eLiterals name="DoGudaBufrifrifribebebiBiGuguscio"/>
    <eLiterals name="AlfrigufrigusgusBogusbubeCio"/>
    <eLiterals name="BiBoBiBiGubeBuBoBulus"/>
    <eLiterals name="AlGudagusgugusgusnulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaDanulAubegusbegusbecio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babogusnules" eType="//DobiBidabeguGuguguCus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBufribebebogufrigufributor" ordered="false" eType="//AlnulauBofribibebiBifrilus" eOpposite="//AlnulauBofribibebiBifrilus/duBefribugubogubebicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Difrigudabonules" instanceTypeName="typeAnAunulAugusboGusGusnulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulAubodabefriGuBuBuCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiGusgudaGubeFrifribiGulus">
    <eLiterals name="BeBibibubibobodabebicio"/>
    <eLiterals name="EubeGusauGuBugubugubiBegusCio"/>
    <eLiterals name="BadaBeBibonulaunulAufrifrinules"/>
    <eLiterals name="BaBeBeTin"/>
    <eLiterals name="AngugubobubiGufribufribulius"/>
    <eLiterals name="AndagugusBuBigubebigusfribonules"/>
    <eLiterals name="DugusdadabofrigusAuboCus"/>
    <eLiterals name="BrAuGubidanus"/>
    <eLiterals name="BegusbifriDaBobeFribuGudanulaudanulauGusius"/>
    <eLiterals name="DaBibuguDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigubufridabenulaudaTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EgusbibeBuBofribeBiGusTin" instanceTypeName="typeDaNulaubugufrigusboNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaGugusgusNulaubobolus">
    <eLiterals name="DiNulaubiGusAugusbeLius"/>
    <eLiterals name="AuBibebolus"/>
    <eLiterals name="BigudabubogusGusaubelus"/>
    <eLiterals name="DugusDagusGusaubuBegusbiBoEs"/>
    <eLiterals name="AudabiNulAubidanulauGusbubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulauBofribibebiBifrilus" abstract="true" eSuperTypes="//Abogunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBefribugubogubebicio" ordered="false" eType="//DaDanulAubegusbegusbecio" eOpposite="//DaDanulAubegusbegusbecio/anBufribebebogufrigufributor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euboBoNulaubegusnus" ordered="false" eType="//BrauBogugusbebidagusfriDafrigusguTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraufridaGusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubugusbibubuGuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andabubobiBuBofriboFrinules" ordered="false" upperBound="-1" eType="//BraufridaGusEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biNulaugusboBoBogusGuTus" upperBound="-1" eType="//DidabigugusbeNulAubidafribegulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubefrigugusGubuCio" abstract="true" eSuperTypes="//FabuguDabibudaboNulaunulauTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabeBoDabobinulaunulAudaCus" instanceTypeName="typeAlgusgusnulAuFribefribuGusdaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulAunus" eType="//BraufridaGusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusgudagusAubogusDagubeFrifrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beguBuTus" eType="//DidabigugusbeNulAubidafribegulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbefribugusBunulauguBeNulaufrilus" abstract="true" eSuperTypes="//AlBuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoboboBoBebefriFrigubotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difridaBidabigugunulAubuBibuTor" eType="//AnbegusbuboFribuCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algusgusdanulauFricio" upperBound="-1" eType="//FabeBoDabobinulaunulAudaCus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dodagugusfribubefrigusgusbebuBobuNus" ordered="false" eType="//DabuFrifriGusbebeFrigububiTor" eOpposite="//DabuFrifriGusbebeFrigububiTor/dobuNulAufrigusboBibigugufriGucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaunulAubobebiguCus" eSuperTypes="//DaDanulAubegusbegusbecio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibogufrigufriBedabuNules" ordered="false" eType="//Abogunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiBeguslius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabenulauBuBoNules" eType="//DaDanulAubegusbegusbecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BefribunulaububonulAunulAuBecio" instanceTypeName="typeDugufridaDagubiNulauBeDafrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulAuBonulaufriBees" eSuperTypes="//BraubuBuguguNulautin //BraufridaGusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaguBofribefrifrinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadabofriDatin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babidabobiGusBunulAutus" ordered="false" eType="//FaguBofribefrifrinulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuDabodagusdabibuBoGunules" eSuperTypes="//BabiBeguslius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beNulaulus" eType="//BiGusgudaGubeFrifribiGulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabofridabinulauDagusFriBebodalius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifribiBudagusfrifrigusFriboNulauBitor" eSuperTypes="//EugusgudagusAubogusDagubeFrifrilus //DubefrigugusGubuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAubobugugucus" eType="//FabeBoDabobinulaunulAudaCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fadanulaufrigubibolus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauBegusdabunulaunulaucus">
    <eLiterals name="BefriBefribeBiBuBugunulaubigusbicio"/>
    <eLiterals name="DibubugusfriBobebudaCio"/>
    <eLiterals name="AubefribiBuBinulauDaEs"/>
    <eLiterals name="DafribeGuguNulAuGulus"/>
    <eLiterals name="BadaBuguBiBuBubedagutus"/>
    <eLiterals name="FabufrigusgusBefrigugusgusfridafritor"/>
    <eLiterals name="AudaBubunulEs"/>
    <eLiterals name="FadabogububeBiFriboBegubolus"/>
    <eLiterals name="BraudabiBofriFrigusfribebuFries"/>
    <eLiterals name="DubenulauBubidabefriBoGugusEs"/>
    <eLiterals name="EudagusGubuGusbetus"/>
    <eLiterals name="EbobeDaNulaunulaugububutor"/>
    <eLiterals name="DigunulAuguNulaudaGutor"/>
    <eLiterals name="DobeTor"/>
    <eLiterals name="DuTor"/>
    <eLiterals name="DogusdagusGusDaNulAububobiGubiCus"/>
    <eLiterals name="AnGusGuFribuGuBenulaubububuBocio"/>
    <eLiterals name="DaBoboGusBonulauNulauTus"/>
    <eLiterals name="AnaugusbigusNulauBobegugutor"/>
    <eLiterals name="AlgusfriboFrigusDatus"/>
    <eLiterals name="AnbibeGusnulAuguBiBulus"/>
    <eLiterals name="DadadaEs"/>
    <eLiterals name="BadagusnulaubefriBolus"/>
    <eLiterals name="Ebetus"/>
    <eLiterals name="DiBobogusNulaubobugusFribiGustus"/>
    <eLiterals name="AubeFriguBufriBenulIus"/>
    <eLiterals name="BaboguNulaunulauBigusGufribocus"/>
    <eLiterals name="AlDaFribebobenulauDadabonulius"/>
    <eLiterals name="BibigusgubegusfridabiGusbobebebobulius"/>
    <eLiterals name="EubunulAufriDabidaBelius"/>
    <eLiterals name="EgusdaguFribogusaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBiDabibogusbobofribeCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulAugubidaTor" ordered="false" upperBound="-1" eType="//AlBuNules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubonulauboFriGudabebebeNulius" ordered="false" eType="//BenulAubinulAuguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibeNulaubebogugunulAubogusaulius" eSuperTypes="//AlnulaunulAubobebiguCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulauGusBebodaFritor" eType="//FadabofriDatin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAunulAufribobiboguslus" ordered="false" upperBound="-1" eType="//BinulAubodabefriGuBuBuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbiNulAubuTus" instanceTypeName="typeBigubeFriDaGubeBigustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboboGuFriBidaBiBigusTus" eSuperTypes="//BrauBogugusbebidagusfriDafrigusguTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augusnulAugusnulAugunulauLus" eType="//DidabigugusbeNulAubidafribegulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBedaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifriBebegusboBibuboNulauBinus" eSuperTypes="//FaBiDabibogusbobofribeCio //FaguBofribefrifrinulEs //AlnulaunulAubobebiguCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaguBegunulAuDabigutin" abstract="true" eSuperTypes="//BeNulAuBonulaufriBees">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auDaNulauboguBebiTus" eType="//BefribunulaububonulAunulAuBecio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabibifriBibububoes" eType="//EgusbibeBuBofribeBiGusTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BifriBebeBeBobeBidabibiLus" instanceTypeName="typeBraudabiFrifribenulaufrinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuFriGuguBiBeNulaulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebubegubeBoGutus" instanceTypeName="typeFaBiGusDabinulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbegubunulaunulauLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBuguNulaugubobuFrinus" upperBound="-1" eType="//DidabigugusbeNulAubidafribegulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AGusBobibiBuBedaguboBees" instanceTypeName="typeEudaNulaufribugusnulaubedaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobobeBubiBobifriNulauBiNulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edaBedabofrifriBogunulauNus" ordered="false" eType="//AlnulauBofribibebiBifrilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusgubiDafriBobenus" ordered="false" eType="//AlBuNules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaucio" upperBound="-1" eType="//Abogunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibebuboGuboguFrinulauBicus" ordered="false" upperBound="-1" eType="//BrauBogugusbebidagusfriDafrigusguTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabebunulauBiBonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauBebugusbeBobeEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubegusBudaBibigusauBeTor" upperBound="-1" eType="//FabeBoDabobinulaunulAudaCus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audaguLus" eType="//EbiNulAubuTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebuGusBiNulauBibinulius" eSuperTypes="//AlBedaNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubiDabinulaugusbuEs" instanceTypeName="typeAdaBunulauBiFridabuGusnulIus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EubifriFribeBofribetor">
    <eLiterals name="BiBuNulAuDafrigusius"/>
    <eLiterals name="BrAugubugusnulEs"/>
    <eLiterals name="EFridaGubibidagustor"/>
    <eLiterals name="AlfriBebogubeboNulaufritin"/>
    <eLiterals name="AlbibegufriboGusauNus"/>
    <eLiterals name="BefriDafriNulAudadagudabobiCio"/>
    <eLiterals name="Bidafrinulaubebees"/>
    <eLiterals name="BraufrigugusGuCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidaboGuGubebotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="betin" upperBound="-1" eType="//BefribunulaububonulAunulAuBecio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaunulauBubinus" ordered="false" upperBound="-1" eType="//AlbefrigusTin" eOpposite="//AlbefrigusTin/dobebugusNulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusGusgudanus" eSuperTypes="//AbegubunulaunulauLus //DobobeBubiBobifriNulauBiNulautin //FabebunulauBiBonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabodagubogusGunulaunulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGusdagubeBuDafribeboButin" upperBound="-1" eType="//BeNulAuBonulaufriBees"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugugugusnulautor" eType="//EgusbibeBuBofribeBiGusTin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubobigusbeBuBebeBugugusguses" ordered="false" upperBound="-1" eType="//AnNulAubeDadabobolius" eOpposite="//AnNulAubeDadabobolius/brAunulAububinulAucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBubugusgusnulautin" instanceTypeName="typeDiFribibefribodanulauboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbebuNulauNulauBubuGuslus" eSuperTypes="//EuDabodagusdabibuBoGunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBuDaBeGusdabeFribiboLius" upperBound="-1" eType="//BifribiBudagusfrifrigusFriboNulauBitor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baboGubobobunus" eType="//DobiBidabeguGuguguCus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagudaGusDanus" upperBound="-1" eType="//EbeDagudanus" eOpposite="//EbeDagudanus/aldabeGusbibuBofribiGusAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFriBobidanules" eSuperTypes="//Alaugusnulaugusfries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBifrinulaubodaguGuboGusGusius" ordered="false" upperBound="-1" eType="//BraufridaGusEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubudabidaguBoFriTus" ordered="false" eType="//BaDafribubebedaBoBies" eOpposite="//BaDafribubebedaBoBies/abebuFrigugusBeNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebunulAuNulauBunulAudacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabubinulAuboBobeGusFribotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagubububebuFrigubuNulauguGuDator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beboDadafrigusdagusAuDaTus" upperBound="-1" eType="//EunulauBebugusbeBobeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbofrifridaBunulaudacus" instanceTypeName="typeDudaGunulAuDagusbugusNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABibebibodadaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuDabuBoboBubebobigusauGusbibuguslius" eSuperTypes="//BrauGusGusbuBibobidacus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiDadanulAunulauDaGuGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulaufribibodafribitus" abstract="true" eSuperTypes="//DobobeBubiBobifriNulauBiNulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabifrinulAuBifrifrilius" upperBound="-1" eType="//EuGusGusgudanus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubufriBenulaunus" eType="//BefribunulaububonulAunulAuBecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndabuBububibibugunulAugusdaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusaububuBoLius" ordered="false" eType="//Fadanulaufrigubibolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BiDaBedaguBoDadafrigusbidanus" instanceTypeName="typeFabeFriGusBiBuGusNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBegusbuFriBigububinulAutin" eSuperTypes="//FaBiDabibogusbobofribeCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBuGusFritin" eType="//BiDaBedaguBoDadafrigusbidanus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubebugudagudaboNulAucus" ordered="false" eType="//AbegubunulaunulauLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabuFrifriGusbebeFrigububiTor" eSuperTypes="//EuGusGusgudanus //AudaguBegunulAuDabigutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobuNulAufrigusboBibigugufriGucio" ordered="false" eType="//DoboboBoBebefriFrigubotin" eOpposite="//DoboboBoBebefriFrigubotin/dodagugusfribubefrigusgusbebuBobuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbuFrifrigugusbeBugugufriGusfriNus">
    <eLiterals name="ABobobonulAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBeNulauGusfribenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBudaDanulaunulAuBugubiGuNus" abstract="true" eSuperTypes="//FabuguDabibudaboNulaunulauTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaNulaugusgusaunus" eType="//DibeNulaubebogugunulAubogusaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBogusBuBiDaBeNulaulus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adabufridanulauBitor" ordered="false" eType="//BrauBogugusbebidagusfriDafrigusguTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulaubifriGugufriFricus" abstract="true" eSuperTypes="//AudaguBegunulAuDabigutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbubeBeGusbunulaubeGusGugusdaTor" ordered="false" eType="//AboboGuFriBidaBiBigusTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubufrigusgubeFriDaGusgulus" ordered="false" eType="//DubefrigugusGubuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnulaugubegusDaCio">
    <eLiterals name="BrauDaBuDagudaGusgusTin"/>
    <eLiterals name="BraufriNulauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaes" eSuperTypes="//AnbebuNulauNulauBubuGuslus //Fadanulaufrigubibolus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibuGububigubigues" eType="//AlbuFrifrigugusbeBugugufriGusfriNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuDaBenulAuboGufridaBiLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabidadaguBeBoNulauFrigusBuGusius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiDaGuNulAuguBinus" instanceTypeName="typeEboBeguGuguCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ebibigunulaufrinulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusBogusguNulauBoguses" ordered="false" upperBound="-1" eType="//BrAuDaBenulAuboGufridaBiLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeBubiFriFrinulauFridaes" eSuperTypes="//FaBiDabibogusbobofribeCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Eudabigubugugusbofribicio">
    <eLiterals name="BedaFriFridabebubutor"/>
    <eLiterals name="DiNulaubodaGusnulaugufries"/>
    <eLiterals name="EubuDagudabeBugusfriboNulAubonulaunus"/>
    <eLiterals name="DidagusbebuNulAugusbugusDaguDaboBitin"/>
    <eLiterals name="AnulauFrifribugusgusBebiLius"/>
    <eLiterals name="DaFrigubiDaNus"/>
    <eLiterals name="DoboBonulaububeBetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulaubeDagusBodabobiGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubeGububeEs" eSuperTypes="//AbegubunulaunulauLus //BenulAubinulAuguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didafribububuBuGudabonulaucio" ordered="false" upperBound="-1" eType="//Ebibigunulaufrinulaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabuboBoboguBefriDanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAufribiBoDaGuses" ordered="false" eType="//BrAuDaBenulAuboGufridaBiLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BiFribobobeBegusguTus" instanceTypeName="typeDagufrifribiGuFriGuFricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfriBuGudabugusbies"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dagusgubuguscio" instanceTypeName="typeAGuGusBobenulaugububiguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusfrigusGuBuGusnulAucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAugubedaBedabifritor" eType="//Difrigudabonules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabuGubufrigugubunulauGugusDabuNules" instanceTypeName="typeAnFribobunulauGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubibebubeboNulaudaGubinulaulius" abstract="true" eSuperTypes="//AlBuNules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibugusbebeDaBibuFries" eType="//DiBubugusgusnulautin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braufriGufrifridagubedaGusgusauCio" ordered="false" upperBound="-1" eType="//AnbeBubiFriFrinulauFridaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdabiBogusBidadagusnulIus" eSuperTypes="//EnulaubifriGugufriFricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulaunus" ordered="false" upperBound="-1" eType="//DoBoguBogusGusAuTin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angugubibeNulAugudadadaGusEs" eType="//DidabigugusbeNulAubidafribegulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daboFritin" eType="//BiGusgudaGubeFrifribiGulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaDafriGuBegugububoNulaubuBibibeBeguLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusnulaububoDabinulaubobidabitus" eSuperTypes="//EuGusGusgudanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beboFriGubigusaulus" upperBound="-1" eType="//DoBeNulauGusfribenulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daDaBobiBogusgusauDaFriguGusfritor" ordered="false" eType="//EdabiBogusBidadagusnulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusDaNulAuFrifriguBoTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBuBugusbibibiBobubicus" ordered="false" upperBound="-1" eType="//AGusEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alauNulaunulauDabigusTor" ordered="false" eType="//AubenulauDagudaFrinulaulius" eOpposite="//AubenulauDagudaFrinulaulius/auGusaubibuNulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fadalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubebibonulAuGusBeGudatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abibudagubulus" ordered="false" eType="//AudaguBegunulAuDabigutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EufriBebibubiBebocus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbibinulauboBuGubudanus" instanceTypeName="typeAnGubunulauFribuBugunulAuBobicio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Audabugusbogubugububibebotus" instanceTypeName="typeFanulauGubugusgusNulAuLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBeboguBodagusbibetin" instanceTypeName="typeEugusbiDalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubenulauDagudaFrinulaulius" abstract="true" eSuperTypes="//BifribiBudagusfrifrigusFriboNulauBitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusaubibuNulaulus" ordered="false" upperBound="-1" eType="//BegusDaNulAuFrifriguBoTor" eOpposite="//BegusDaNulAuFrifriguBoTor/alauNulaunulauDabigusTor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAubuDadagunulaubitin" eType="//BabuGubufrigugubunulauGugusDabuNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudadabeBebibeLus" eSuperTypes="//DifriBebegusboBibuboNulauBinus //BrAuDaBenulAuboGufridaBiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulaubitor" eType="//BegusDaNulAuFrifriguBoTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoNulauBiBebeBibegudabeTus" instanceTypeName="typeBefriDabinulAutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbufrifribodaFriGusaubies" eSuperTypes="//Abogunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAububuFriGusbobubeBedaboTor" ordered="false" eType="//DagubububebuFrigubuNulauguGuDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinulaubububoBubibilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaDafribubebedaBoBies" eSuperTypes="//Fadanulaufrigubibolus //EugusgudagusAubogusDagubeFrifrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubeFriBibefribifricio" eType="//BrauBegusdabunulaunulaucus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobubinulAubibiFriBudalius" ordered="false" upperBound="-1" eType="//EufriBebibubiBebocus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebuFrigugusBeNules" ordered="false" upperBound="-1" eType="//EFriBobidanules" eOpposite="//EFriBobidanules/eubudabidaguBoFriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaguBebedaboes" instanceTypeName="typeAugububoboBobitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuDaFrifriFriFriBudaFridadatus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBiGusfriGubogusdaFricio" eSuperTypes="//DabodagubogusGunulaunulaucio //AlnulauBofribibebiBifrilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnulAuGuBigusboboEs" instanceTypeName="typeBaguDagubiBucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboFriDabuBebobeBiDabidafriGusbulius" eSuperTypes="//FaBiDabibogusbobofribeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigudaBibuboBogusDaLius" eSuperTypes="//ABibebibodadaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibibiBibiGugubobiBubeGutin" abstract="true" eSuperTypes="//AlBedaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbigubunulaudabinulauBobetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabenulAudaGunulEs" eSuperTypes="//BraufridaGusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAuDaguBibobobogusbofriTin" eSuperTypes="//BrauGusGusbuBibobidacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBobebebugusFribunus" ordered="false" eType="//AndabuBububibibugunulAugusdaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bacus" abstract="true" eSuperTypes="//Fadalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFrigusNulAuNulAugusDacio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diFribigusAuTus" eType="//EbiNulAubuTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguBenulauBiDadagusgubotin" ordered="false" upperBound="-1" eType="//DiBudaDanulaunulAuBugubiGuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauguBibegugusbutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgubibogusbubuBobibebogusNulAugues" instanceTypeName="typeAudaboDaGusdaBuNulauCus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AubibiNulaubobeNulius">
    <eLiterals name="DobonulaugusDabebunulAuGunulAuLius"/>
    <eLiterals name="BigubibobebobufrifriboDafribibudagusTin"/>
    <eLiterals name="FabodabiboBigusauBogugusguButor"/>
    <eLiterals name="BabuDadanulaudaBifridadacio"/>
    <eLiterals name="AuBonulAubibigusbibifridacus"/>
    <eLiterals name="DodaNulaudagusAucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbeDagudanus" eSuperTypes="//DoBoguBogusGusAuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldabeGusbibuBofribiGusAulus" ordered="false" eType="//AnbebuNulauNulauBubuGuslus" eOpposite="//AnbebuNulauNulauBubuGuslus/dagudaGusDanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BefriGusbeguNulauBifribibebiNules">
    <eLiterals name="AnulaufriDagustus"/>
    <eLiterals name="DoNulauFriBiBicus"/>
    <eLiterals name="EnulaubobinulAunulaufriTin"/>
    <eLiterals name="DanulauGusBibobodator"/>
    <eLiterals name="BagusDabeNulAuTus"/>
    <eLiterals name="EubofridagusGunulAucio"/>
    <eLiterals name="BrauBuBinulaugubunulaubilius"/>
    <eLiterals name="EgusBugusbobidaCus"/>
    <eLiterals name="DabuGuBuGusFricus"/>
    <eLiterals name="DaDafrigusdaBoDaBiguGuNulaunus"/>
    <eLiterals name="Dafrigusgunulius"/>
    <eLiterals name="AnFriboBubenulaugusAubicus"/>
    <eLiterals name="BaguBeDaFriDagusgusgusius"/>
    <eLiterals name="DonulAunulAudaguBotus"/>
    <eLiterals name="AndaBuBigusDafriBoNulauFritor"/>
    <eLiterals name="AubiBeLius"/>
    <eLiterals name="DaBoguBiBicus"/>
    <eLiterals name="AuFriBugusBiBofribibues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiguGusNulAubofribeBuboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubibeGusgudaDacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaubobeDagusbebidabiGusdaLus" eType="//DubebibonulAuGusBeGudatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaunulAugustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbefrigusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobebugusNulaucus" upperBound="-1" eType="//BidaboGuGubebotin" eOpposite="//BidaboGuGubebotin/alaunulauBubinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusfridabiBunulauTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bebobugusbonulaugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBubogudaFribinulaubuGuNulaucio" eSuperTypes="//Abogunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diFriBodaDanulauBubicio" eType="//EubifriFribeBofribetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFrinulaunulauFribuboGubuCio" eSuperTypes="//EbeDagudanus //AlnulaunulAugustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnNulAubeDadabobolius" eSuperTypes="//DiBudaDanulaunulAuBugubiGuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAunulAububinulAucus" ordered="false" upperBound="-1" eType="//DabodagubogusGunulaunulaucio" eOpposite="//DabodagubogusGunulaunulaucio/braubobigusbeBuBebeBugugusguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBidaBibuDabulus" instanceTypeName="typeBraunulauBudaDaNulauBogusboGusbecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeBogusgugusgusnulAuboNulaugusbilus" eSuperTypes="//EugusgudagusAubogusDagubeFrifrilus //BebunulAuNulauBunulAudacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusauFribonulAubonulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusbunulAubeBogusfriCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Afrinulaubugubofrigucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubebiguGugubufrinulAuGulus" ordered="false" eType="//BrauBubogudaFribinulaubuGuNulaucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faboBodagusaunulAuBuDatin" ordered="false" upperBound="-1" eType="//AlnulaunulAubobebiguCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusbodadaFribebutor" ordered="false" upperBound="-1" eType="//EdabiBogusBidadagusnulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fabebubinulaubibenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubibenulAuDadabuNus" eSuperTypes="//DaDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBubunulaugusgusgucus" abstract="true" eSuperTypes="//FaguBofribefrifrinulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusbiGudalus" ordered="false" upperBound="-1" eType="//DigudaBibuboBogusDaLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusbeNulaunulIus" ordered="false" upperBound="-1" eType="//AlnulaunulAugustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusbogusAuNulauBugusautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafriBoBobugusbudanulAubofriBeNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EbibeNulaudabeBuTus">
    <eLiterals name="AlGuBefridaBogugusbenulAufriTin"/>
    <eLiterals name="EubugugubefriguTus"/>
    <eLiterals name="DidabeNulAuGustus"/>
    <eLiterals name="DubinulauBobiDaguNulaulus"/>
    <eLiterals name="DaboBobubuguGusBobebugubuTin"/>
    <eLiterals name="BibiGusbobinulaubuguNules"/>
    <eLiterals name="FabugufribeNulAutor"/>
    <eLiterals name="Aunulaubudabutor"/>
    <eLiterals name="AubibidafriBubegusbetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuguBodadaBibugubotin" instanceTypeName="typeBibuGusNulauBibeNulaubibeGugusGuslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abudagusbibebegubinulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="di" ordered="false" eType="//EuDabodagusdabibuBoGunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubiFribeFrifriGuboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBeNus" eSuperTypes="//AubenulauDagudaFrinulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBeguBogugufriBeGusdagusgucio" ordered="false" upperBound="-1" eType="//AbegubunulaunulauLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFriBobiBegudanulaunulAubibeCus" ordered="false" upperBound="-1" eType="//AfriBuGudabugusbies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaguboboBiGusnulaufrinulius" instanceTypeName="typeFadaNulaudabuBiBubitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbebofribuboBogufricus" instanceTypeName="typeDiDaBobedadagusbobifrigusTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AldagusbofribobufrigusbefriGusauguTor" instanceTypeName="typeDuGudaguBobuBufrigusbeBoBibutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbiGusGusguboGusdabunulAugubiguslius" instanceTypeName="typeBabibobibiGucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobubinulAuDaGunulaugufriguFrilus" instanceTypeName="typeEdabugudagusnulauNulAubudalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbebodagusauBobuNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabiDaNulAugubuBoGusBibuCus" ordered="false" eType="//EudadabeBebibeLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadafrigugusdanulauFrifribiEs" upperBound="-1" eType="//DiBogusBuBiDaBeNulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuBogugunulAudabuBolus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibuGubuBecio" eType="//DobiBidabeguGuguguCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusgusbofriTor" eSuperTypes="//Abogunus //AnbebuNulauNulauBubuGuslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBogusfribugusgugudabunulauDaDafritus" ordered="false" eType="//BabiBeguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuboBuDagusaubuBoes" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBofriBiGugufrifridaBenus" ordered="false" upperBound="-1" eType="//BabiBeguslius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGusbufriGusauGusnulauGusbeLus" ordered="false" upperBound="-1" eType="//EugusfrigusGuBuGusnulAucus"/>
  </eClassifiers>
</ecore:EPackage>
