<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="annulaulius" nsURI="http://hub.de/rcore/examples/annulaulius" nsPrefix="cgt">
  <eClassifiers xsi:type="ecore:EEnum" name="AnNulaufriguBoGubugutor">
    <eLiterals name="AuBies"/>
    <eLiterals name="FagububufridabiguFrinulautor"/>
    <eLiterals name="Dabubufrigusgubebitin"/>
    <eLiterals name="AlbebuNulautin"/>
    <eLiterals name="AnbigubiguBoNulAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusGuBulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DabuboBeGusgusNulAuguscus">
    <eLiterals name="DaDafrigusbugusguses"/>
    <eLiterals name="BeDabonulAunulaudabudaes"/>
    <eLiterals name="BifriBeBiBiNulaunulAugusBuGusGusIus"/>
    <eLiterals name="AdaNulauDadaGusBufriTor"/>
    <eLiterals name="Batin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubobogufribobuBigugusbelus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EubebiDaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaFribiBigusGusguBinulaubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbifridagusaugubiGuscio" eSuperTypes="//DubobogufribobuBigugusbelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriDanulautus" abstract="true" eSuperTypes="//AnGusGuBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulaugusnulauguFrinulAutin" ordered="false" eType="//DaFribiBigusGusguBinulaubitor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubodaguBebiGusgubeCio" eType="//DabuboBeGusgusNulAuguscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaufribugusfriButor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagufridabidadaBudabues" instanceTypeName="typeDibegubigusAuguBubibonus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlboNules">
    <eLiterals name="DiNulauDaFrinulAucio"/>
    <eLiterals name="EudaBudanulAuFrifrinulaunus"/>
    <eLiterals name="AnFridaGububiBogunulaufridaBitus"/>
    <eLiterals name="BibuBobubifriFrifrinulauGusfriguscus"/>
    <eLiterals name="DofrigufriBebiGubicus"/>
    <eLiterals name="DuBigubobeNulaubetus"/>
    <eLiterals name="EDabibefriboNulaudanus"/>
    <eLiterals name="Anbubogubefrigusbucus"/>
    <eLiterals name="Braubinus"/>
    <eLiterals name="BebobiBenulauNulAuTin"/>
    <eLiterals name="FaGuGunulaunulAuGugusBeNules"/>
    <eLiterals name="AbufribiBeBugusboBoGuscio"/>
    <eLiterals name="AudabifriBufriBeFribeDalius"/>
    <eLiterals name="AlnulaubeBobofriBobiFriNus"/>
    <eLiterals name="FabuFribiFribucus"/>
    <eLiterals name="FabibifribibodaDatin"/>
    <eLiterals name="AlAuGusgudagusfriEs"/>
    <eLiterals name="AngusBudabiFriBebedaboNulautor"/>
    <eLiterals name="AngusnulaubibegugubeBibonulaucus"/>
    <eLiterals name="EugusgugusAufrifribiBifriDaDagudalus"/>
    <eLiterals name="Befribenulaudalius"/>
    <eLiterals name="Bebobodabuguslus"/>
    <eLiterals name="AdabeFriTin"/>
    <eLiterals name="DiGuBigufriguGusbotus"/>
    <eLiterals name="EbedabuDafrigunulIus"/>
    <eLiterals name="BrAuGusdadadaNulius"/>
    <eLiterals name="DoBobeFrinulAubegusGusdatin"/>
    <eLiterals name="AlbigunulaugusboEs"/>
    <eLiterals name="BrAuBeDaBoboGusnulaugusbuEs"/>
    <eLiterals name="DoFrifridagubiDabugusGusBuBucus"/>
    <eLiterals name="EdaGusbeTin"/>
    <eLiterals name="DugufribunulaubebebiBigusFriGucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobiGugusfrigusbegubocio" eSuperTypes="//AnGusGuBulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ABebubobubifribogubetin">
    <eLiterals name="AubeBebuBoguTor"/>
    <eLiterals name="AfridaFriFrigusaubufritus"/>
    <eLiterals name="BiBedabubiBiFriFribenulAunulauBecio"/>
    <eLiterals name="AufriBeGubinulAuBefricio"/>
    <eLiterals name="BrAuguBoguGudaGusauLius"/>
    <eLiterals name="FaGusDagubidabuFritin"/>
    <eLiterals name="FaBebebedabeDagusfridagusgudaes"/>
    <eLiterals name="BiDadaGugunus"/>
    <eLiterals name="AuDaBuDaFribinus"/>
    <eLiterals name="Dagusbibebogusgutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulaugugusnulaubibigusFribonules" eSuperTypes="//AnfriDanulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBebugusnulaubodaNulius" abstract="true" eSuperTypes="//DobiGugusfrigusbegubocio"/>
</ecore:EPackage>
