<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anbonulautin" nsURI="http://hub.de/rcore/examples/anbonulautin" nsPrefix="GGRR">
  <eClassifiers xsi:type="ecore:EClass" name="AnbugusBuGusauGusBebudagubuguguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBuLius" eSuperTypes="//AnbugusBuGusauGusBebudagubuguguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubeGusfriboGusbuGugutin" eSuperTypes="//AnbugusBuGusauGusBebudagubuguguTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befriguBoFridaNulIus" ordered="false" upperBound="-1" eType="//BrauBuLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafribedagusBidabeGusgulus" ordered="false" upperBound="-1" eType="//BrauBuLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difribiNulaububefrilius" ordered="false" upperBound="-1" eType="//BebuBeBiBobiDaBoboNus" eOpposite="//BebuBeBiBobiDaBoboNus/anBibubuBedagubudaCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlDabonulauBedaboguscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabidagubeBefrigusBoDadagusTor" ordered="false" upperBound="-1" eType="//AnbugusBuGusauGusBebudagubuguguTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGubeTus" upperBound="-1" eType="//EubeGusfriboGusbuGugutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuboBobibeGugusBees"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AngubebufriEs" instanceTypeName="typeAbebifriBonulaubibegububonulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusBudaGubogusNus" eSuperTypes="//AuboBobibeGugusBees"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabenulauBoGusBelius" eSuperTypes="//EubeGusfriboGusbuGugutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biGusfriBugusgudafritus" eType="//AngubebufriEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnFribigusAubibobobeguTus" instanceTypeName="typeDoBuGusbifribuGuBiNulauLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudabiNulaufriEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudanulAufribeBobeBobetin" eSuperTypes="//BrauBuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagudabeDafrifriFriBubenulaulius" eSuperTypes="//EudanulAufribeBobeBobetin //AuboBobibeGugusBees"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusaubofribobonulAuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebuBeBiBobiDaBoboNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBibubuBedagubudaCus" ordered="false" upperBound="-1" eType="//EubeGusfriboGusbuGugutin" eOpposite="//EubeGusfriboGusbuGugutin/difribiNulaububefrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibiBoBigusGugusboTor" eSuperTypes="//DagudabeDafrifriFriBubenulaulius //AudabiNulaufriEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubobiBefrinulauTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbibunulauNulAuGuBuLus" upperBound="-1" eType="//DibiBoBigusGugusboTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubofriFribebunulautin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiFriBunulaubinulaudabebeFriButus" instanceTypeName="typeBaNulauNulaubiGusbunulaufribifriTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafribogubobigusbiNus" eSuperTypes="//AnbugusBuGusauGusBebudagubuguguTin //AudabiNulaufriEs //AlDabonulauBedaboguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabobubebeBenulaugusDaNulEs" eSuperTypes="//AuboBobibeGugusBees //AudabiNulaufriEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedagusbiboBoBitor" eType="//DiFriBunulaubinulaudabebeFriButus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidafribefriNulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAudadanulauBibibegusAuNulIus" ordered="false" eType="//EubeGusfriboGusbuGugutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebobeNulAugusnulAubobubigutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGudabeNulaubunulius"/>
</ecore:EPackage>
