<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="brius" nsURI="http://hub.de/rcore/examples/brius" nsPrefix="WD">
  <eClassifiers xsi:type="ecore:EClass" name="BrAubodadafriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndagusbigusbogusGubiTus" abstract="true" eSuperTypes="//BrAubodadafriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbuBugusguGubiGusbibutin" ordered="false" upperBound="-1" eType="//BrAubodadafriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulauBebedanulAububocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBogububuLus" ordered="false" upperBound="-1" eType="//BrAubodadafriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaufridaBibudaboguDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugugusnulaunulaudaboguCio" eSuperTypes="//BrauNulauBebedanulAububocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBidaBibeBiFribunulauBobofriBinulAuBibinus" ordered="false" upperBound="-1" eType="//AndagusbigusbogusGubiTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugubiBeGufridaguDaBebebiCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnauFrifribues" instanceTypeName="typeDonulauBebeGunulaugusBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaguBoNulaubitin" eSuperTypes="//AndagusbigusbogusGubiTus //DanulaufridaBibudaboguDatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebudanulaubegugudafribogubudanulAubulius" ordered="false" upperBound="-1" eType="//BrauNulauBebedanulAububocus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusAuBogusNulAunulAuTus" ordered="false" eType="//EboBoGubebegubogusgubitor" eOpposite="//EboBoGubebegubogusgubitor/edabiboGudabigubuBees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbiBibubububugusauBibiBeGues" eSuperTypes="//DanulaufridaBibudaboguDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaubegusbibogusAugufriBubotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diFrigubiGudaNulAubiEs" upperBound="-1" eType="//BafriDaBibogulius" eOpposite="//BafriDaBibogulius/braubufribuBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BafriDaBibogulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubufribuBilus" eType="//DinulaubegusbibogusAugufriBubotus" eOpposite="//DinulaubegusbibogusAugufriBubotus/diFrigubiGudaNulAubiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aldagugusgububotin" abstract="true" eSuperTypes="//BafriDaBibogulius //EugubiBeGufridaguDaBebebiCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubudadanus" eType="//AnauFrifribues" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doNulaugusfrifrilius" eType="//AnauFrifribues" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBoBocus" ordered="false" eType="//EugubiBeGufridaguDaBebebiCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBobubonulaugunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabuBenulaugusbinulaubibufries" eSuperTypes="//EbiBibubububugusauBibiBeGues //BrAubodadafriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulAufrifrigusbeBuLius" ordered="false" eType="//AnBobubonulaugunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFrigusauDagusfribeBoGuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="difribiBibuBobogunulauDaDator" ordered="false" upperBound="-1" eType="//DinulaubegusbibogusAugufriBubotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubiBeBebeGubiNulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguBuBonus" ordered="false" eType="//FaguBoNulaubitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBinulauBibebeBibubofribuBiFritor" eSuperTypes="//BrAubodadafriTor //FaguBoNulaubitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobiBenulauBelus" eSuperTypes="//DugugusnulaunulaudaboguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Digudabubidacio" eSuperTypes="//DugugusnulaunulaudaboguCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anDaNulauGusbutor" upperBound="-1" eType="//AnauFrifribues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BraunulAubifribebuguTor">
    <eLiterals name="BrauBiBonulaunulauDabicio"/>
    <eLiterals name="AnBebudaNulAugusBoBedaTus"/>
    <eLiterals name="AngubeBubodafribubiGuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeDanulAuBiDalius" instanceTypeName="typeAugudagusboboNulaudanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBegubobibobibibodacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aFriBoBibugusbebeGusbuLus" ordered="false" eType="//AbigusnulaugusBiDabegutor" eOpposite="//AbigusnulaugusBiDabegutor/abibobebidaDaGuboBotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabibiBunulAufridabenulauFriboes" eSuperTypes="//DobiBenulauBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBibiDabogusdabiBubolius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aulius" eType="//AnauFrifribues" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusbibobubiGusbiBeBibugusgugusdatin" ordered="false" eType="//BrauBinulauBibebeBibubofribuBiFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbenulauDafribigusbibenus" instanceTypeName="typeBibiBebofribuNulaubuGuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuBugubidabiBeguFrifribubicio" eSuperTypes="//FaguBoNulaubitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dagunulIus" eType="//EbenulauDafribigusbibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusgusBiGuBiFrigubuGuses" abstract="true" eSuperTypes="//EbiBibubububugusauBibiBeGues"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbubufriGubibubinulAufribibitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugugusBolus" eType="//EbenulauDafribigusbibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eugusfridabebebibenules" eSuperTypes="//EbubufriGubibubinulAufribibitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulAufribiDaBoboBebugusius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Albedabubufribinus" instanceTypeName="typeBanulAuBenulaugusBobunulAugusboEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbigusnulaugusBiDabegutor" eSuperTypes="//DaBibiDabogusdabiBubolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abibobebidaDaGuboBotor" ordered="false" upperBound="-1" eType="//BaBegubobibobibibodacus" eOpposite="//BaBegubobibobibibodacus/aFriBoBibugusbebeGusbuLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofribeBeBuBodanulAuLius" ordered="false" upperBound="-1" eType="//AnbuBugubidabiBeguFrifribubicio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibufriGubebuBulus" ordered="false" eType="//EbubufriGubibubinulAufribibitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ABuBubufriBeBeboGuGuGues">
    <eLiterals name="BeBobuGudabugusbuBubiNus"/>
    <eLiterals name="DibeBebegusauBubofriGusfrinulius"/>
    <eLiterals name="AudaFribubibubiDabonus"/>
    <eLiterals name="EuBiBubiboCus"/>
    <eLiterals name="DaGusbuNulaufriGuNulAubotin"/>
    <eLiterals name="AugubibifribegubogugufriDaFrifriGutor"/>
    <eLiterals name="DoBifribibodagusBugusnules"/>
    <eLiterals name="AnNulaubunulaufriBoBobebuDagusbegutus"/>
    <eLiterals name="DubebonulauguFriBenus"/>
    <eLiterals name="BabidabinulauNulaugunus"/>
    <eLiterals name="AugusdagugusguGugusBedaCus"/>
    <eLiterals name="DabuBiBogusbeboButor"/>
    <eLiterals name="BrAugugusGusbuDabonulaugusaubicio"/>
    <eLiterals name="EubegusnulauNulAubodabubiguGutor"/>
    <eLiterals name="DabonulauNulaufrigusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dubobugusbifridabugudanules" eSuperTypes="//AngusgusBiGuBiFrigubuGuses //AndagusbigusbogusGubiTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egusFrigugulius" upperBound="-1" eType="//EbenulauDafribigusbibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAunulaunulaubegusBefrinulaunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGusGusgusguNulaubidaBitor" ordered="false" eType="//BaBegubobibobibibodacus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alBeFrigunulauTus" eType="//EbenulauDafribigusbibenus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fadanulaunulauLius" eType="//BeDanulAuBiDalius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodabibeGusgusgusBebocus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBugustor" eType="//BraunulAubifribebuguTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abibufribegusbiboFriDagusBodaCus" eType="//EbenulauDafribigusbibenus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babobubugububiFrigucus" ordered="false" eType="//BraubiBeBebeGubiNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubebuDabugusGusbegusdabiFriFriBonus" eSuperTypes="//DaBibiDabogusdabiBubolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigunulAuBonulauGusDalus" ordered="false" eType="//AngusgusBiGuBiFrigubuGuses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beguBigusaunulaugubofrinus" ordered="false" upperBound="-1" eType="//BaBegubobibobibibodacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaDabiNulaudaFribeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGuBefriboboBedaes" upperBound="-1" eType="//AnAunulaunulaubegusBefrinulaunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufriBinulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiDagusdagusguGuscus" instanceTypeName="typeEuBiBogusboNulauNulAudaBinulaudaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBuNulauBogudanus" eSuperTypes="//FaguBoNulaubitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulAugusDaGubufriNulauBocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebebeguBeBeBiTor" ordered="false" eType="//DabibiBunulAufridabenulauFriboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BafribeBofriBebeBunules" eSuperTypes="//BrauNulauBebedanulAububocus //DodabibeGusgusgusBebocus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuFriBeGusbibodagusdabigusdabicio" instanceTypeName="typeEbugubeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBebiBuBebuDatin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibenulAuBoBetus" eSuperTypes="//BaBegubobibobibibodacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaunulaubinus" abstract="true" eSuperTypes="//BiFrigusauDagusfribeBoGuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGugusbodaFriDalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusnulAufribicio" eSuperTypes="//BaBegubobibobibibodacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eNulius" eType="//AnauFrifribues" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubigunus" eType="//BeDanulAuBiDalius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeGuses" instanceTypeName="typeDuDabonulAuBiBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusbeNulAubuBeGusDacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGuBegubidafrinulauFrigufriBilus" ordered="false" eType="//AngusgusBiGuBiFrigubuGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBufriGusbolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusbiBibobufriboNulaubinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doGusauBebubuNulAuBiGugufrigucio" upperBound="-1" eType="//EbenulauDafribigusbibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbenulaubudaBidacio">
    <eLiterals name="ABibobiGuguNulauGuslus"/>
    <eLiterals name="BedabiBoBigusbuBuBoes"/>
    <eLiterals name="BiGuBigudabobiGubogufrifricus"/>
    <eLiterals name="DaBiBodaFriBuNulauBugusdalus"/>
    <eLiterals name="DaNulauBiboBiFriDabufrinulAucus"/>
    <eLiterals name="AlgusbobiFriGudabogucus"/>
    <eLiterals name="Da"/>
    <eLiterals name="EFriNulius"/>
    <eLiterals name="DabedagusdaDaFrinulaugues"/>
    <eLiterals name="ANulauNulaubiNulaubebitin"/>
    <eLiterals name="Eugusgubonulaubutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabefridafriBiBibebiBoboBoDator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebebicio" ordered="false" upperBound="-1" eType="//DaGusbiBibobufriboNulaubinus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beboBuTus" eType="//BiDagusdagusguGuscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Babofribulus" eSuperTypes="//AlgusbeNulAubuBeGusDacio //DobiBenulauBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaBeFribugusBubifriTus" eSuperTypes="//EbubufriGubibubinulAufribibitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulAubudaBonulauNulEs" upperBound="-1" eType="//DabuBenulaugusbinulaubibufries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egusFrigustus" upperBound="-1" eType="//DuFriBeGusbibodagusdabigusdabicio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobiBiboBuDacio" eType="//BiDagusdagusguGuscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBofrifridabobotin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AguBiboBuBubogusGugubobotus" instanceTypeName="typeDogusbobiBefribuFribudaguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DububonulaufriGusgubifrinulaulus" abstract="true" eSuperTypes="//BafribeBofriBebeBunules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euBubegugues" eType="//DuFriBeGusbibodagusdabigusdabicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdadabugudafrinulAuNulaubees" eSuperTypes="//EudaBeFribugusBubifriTus //BafribeBofriBebeBunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabeBoFrifrinulAugusBuEs" ordered="false" upperBound="-1" eType="//EbiBibubububugusauBibiBeGues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebiBubuBofriTus" instanceTypeName="typeBafrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfrinulaugusAuGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFribibedabeBitus" eSuperTypes="//DufriBinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBefriBiboBeDanulAubinulaubebuboDator" eSuperTypes="//AlgusbeNulAubuBeGusDacio //DaBibiDabogusdabiBubolius //EbiBibubububugusauBibiBeGues"/>
  <eClassifiers xsi:type="ecore:EClass" name="EboBoGubebegubogusgubitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edabiboGudabigubuBees" ordered="false" eType="//FaguBoNulaubitin" eOpposite="//FaguBoNulaubitin/bigusAuBogusNulAunulAuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DanulAububigusbuFrigusAunulIus" instanceTypeName="typeAngugusbidafriGudaCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubudadabebubiGubilus" instanceTypeName="typeDugusguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeDabeFribibidanulaugusguGulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibodaNules" upperBound="-1" eType="//EbenulauDafribigusbibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DafrigusnulAubuBefribenulaubogusgustin" instanceTypeName="typeAubegusdanulauDanules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BanulAubibifrigusNulauGuGusbigusaubulus">
    <eLiterals name="DafribibodaboGusBobufriGusauboBobotor"/>
    <eLiterals name="A"/>
    <eLiterals name="BaGubiFridabefrifrigusgustor"/>
    <eLiterals name="AubunulauGugusnulAuFridaguBenulIus"/>
    <eLiterals name="AlbuNulauNulaufrigusDabebies"/>
    <eLiterals name="DidaBifridaBunulAulus"/>
    <eLiterals name="FabeDabigudaDafries"/>
    <eLiterals name="DogufribuboBuGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AugunulaugusDaDaGusaunulAulius">
    <eLiterals name="DubeGugusbugusfrigusboguCus"/>
    <eLiterals name="BigugusgububenulAuFrinus"/>
    <eLiterals name="EbobuguGuBeguGusius"/>
    <eLiterals name="BeBegusbobiNulaugusBuBidaBetin"/>
    <eLiterals name="DabubeNulauFribenulAubicus"/>
    <eLiterals name="AlbifrifridaDaNulaulius"/>
    <eLiterals name="Da"/>
    <eLiterals name="FaBibegubudagusnulaubicus"/>
    <eLiterals name="DiDabofrinulauGusAufritin"/>
    <eLiterals name="BeGusgufrigusauDaBuGuBigugutor"/>
    <eLiterals name="Dogusgusbutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoGuses" instanceTypeName="typeBadanulauguBobiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusBoGusdabibuNulaunules" eSuperTypes="//Dubobugusbifridabugudanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdanulauFriNulaubiGubutor" eSuperTypes="//EbubufriGubibubinulAufribibitin //BrauNulauBebedanulAububocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudaBeBiboGusGusnulAubunules" ordered="false" upperBound="-1" eType="//DabibiBunulAufridabenulauFriboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugunulaunulauFriGubenus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EudaNulaugufriTor">
    <eLiterals name="BebobeBebibuFriBufriboboTor"/>
    <eLiterals name="AnbonulauboGusdaCus"/>
    <eLiterals name="BaBuBefribiBeBeLius"/>
    <eLiterals name="AlbiBobigubitor"/>
    <eLiterals name="EFrifrinulauguboNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubeBufrifrigunulaunulius" instanceTypeName="typeAbifriBoBigusbegusbugusguGufribonulaubiboEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaufrinulaudagusBoBinulauLius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bifritus" eType="//DafrigusnulAubuBefribenulaubogusgustin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibodaDabegusbubufricio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubeguGusaubigusdaLius" ordered="false" upperBound="-1" eType="//DabefridafriBiBibebiBoboBoDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DibebodabububeBenulEs" instanceTypeName="typeADanulaububegusauNulaudaBuBugues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaBibebobudaBitin" abstract="true" eSuperTypes="//Dubobugusbifridabugudanules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbugusbugubeBeGuslus" instanceTypeName="typeAlBugunulaudadafriBobigusNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraububegusbuDafritor" instanceTypeName="typeAGusgufriGubonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusGuboNulaufriBodaBoguboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulaubeGububefritor" eType="//BeGuses" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboBegusgugusBoBufriBies" eSuperTypes="//DobiBenulauBelus //BaNulAugusDaGubufriNulauBocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBoGugusbobuBidaes" ordered="false" upperBound="-1" eType="//AngusgusBiGuBiFrigubuGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBefrigusBotus" eSuperTypes="//BibenulAuBoBetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafribuDagusBiBucus" eType="//DuFriBeGusbibodagusdabigusdabicio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBogusaudaDabubibees" eType="//BagusGuboNulaufriBodaBoguboes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biDaBiboDaGusbeBobefridagusGubuGusaugutor" ordered="false" upperBound="-1" eType="//DodabibeGusgusgusBebocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusGugudaBodagugutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiEs" instanceTypeName="typeEuNulAubeNulAunulauGusbogugusbedaguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobuGugusaubenulaubogusbubucio" eSuperTypes="//DodabibeGusgusgusBebocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBudagudabugusgucus" abstract="true" eSuperTypes="//BagusnulAufribicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusfribofrigufrigusBobubuTin" eSuperTypes="//Aldagugusgububotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibebedaBigusgubudafricio" ordered="false" eType="//Aldagugusgububotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FabifribeBuEs">
    <eLiterals name="EuGuDagubobugusauNulauDafribiFriBetus"/>
    <eLiterals name="DubobububoDaCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBugububuGuBibonus" instanceTypeName="typeDoDadaBobulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dibigusbibibobelius" eSuperTypes="//BaBegubobibobibibodacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begudagusFriBebeBifribibubodator" ordered="false" upperBound="-1" eType="//DanulaufridaBibudaboguDatus"/>
  </eClassifiers>
</ecore:EPackage>
