<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bebobebetus" nsURI="http://hub.de/rcore/examples/bebobebetus" nsPrefix="meY">
  <eClassifiers xsi:type="ecore:EClass" name="DuBiBitin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusbogubugusNulautor" eSuperTypes="//DuBiBitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efriDabiBubinulAuTor" ordered="false" upperBound="-1" eType="//DuBiBitin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubebiBubiBeDagubogusnulaudacus" ordered="false" upperBound="-1" eType="//EuFriFridadaguBuboNulauGusBibibiBifribiNulaulius" eOpposite="//EuFriFridadaguBuboNulauGusBibibiBifribiNulaulius/faGuBofrifrifrinulaubiDaCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnboBoBiEs">
    <eLiterals name="EubeBubufriFriGuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribegufriBuGubiBuBubeTus" eSuperTypes="//BigusbogubugusNulautor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doboBucus" ordered="false" upperBound="-1" eType="//BigusbogubugusNulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbebobebidabunulaububiBonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuDaGubobenulauguGusbibitin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubibigusFridabonulauboTus" instanceTypeName="typeAlAuBefribigusbugusbubigusNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbuGubeguBenus" instanceTypeName="typeEbudabebuguBibodabuDabetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibonulAugusGubutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeboboBoCus" eSuperTypes="//DuBiBitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubofricus" eType="//BigusbogubugusNulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaDabiBodaGufriNulauNus" eSuperTypes="//DibonulAugusGubutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abidabebofrinulaunulaucio" ordered="false" upperBound="-1" eType="//BigusbogubugusNulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabeNulAuguslus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFrifridaBegubibenulaufriGusGudaGunus" instanceTypeName="typeAbeBubibudafribubenulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DububeBetin" eSuperTypes="//FaGuDaGubobenulauguGusbibitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabiguNulauBeBubofrigusfrigustor" ordered="false" eType="//DabeNulAuguslus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agusbuFricus" eType="//EubibigusFridabonulauboTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EunulaufribodaGusfriNus" instanceTypeName="typeBraunulauBegubeguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndadabigusboguBudanulauboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDagusbudaGugues" ordered="false" upperBound="-1" eType="//BaDabiBodaGufriNulauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfriNulauBufriDabogucio" abstract="true" eSuperTypes="//BeboboBoCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabiboGusBuGusDanulAuBugusnulEs" ordered="false" upperBound="-1" eType="//AlfribegufriBuGubiBuBubeTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabeNulaubuNulauboBigusButus" eSuperTypes="//BigusbogubugusNulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBifriBiGusbibiEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuFriFridadaguBuboNulauGusBibibiBifribiNulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faGuBofrifrifrinulaubiDaCus" ordered="false" upperBound="-1" eType="//BigusbogubugusNulautor" eOpposite="//BigusbogubugusNulautor/braubebiBubiBeDagubogusnulaudacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGubofriBoBubibebuBiLius" eSuperTypes="//BigusbogubugusNulautor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusbibogugusbibulius" eType="//DuBiBitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbuboboDadadaDagusboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBibibuBiguLus" eSuperTypes="//AndadabigusboguBudanulauboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algubobidadanus" ordered="false" upperBound="-1" eType="//BigusbogubugusNulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EunulaudagusbuBebefriguBolus" instanceTypeName="typeDunulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBiBegusgusLus" eSuperTypes="//AGubofriBoBubibebuBiLius //DububeBetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBoboBifrigusBuBuBoNules" ordered="false" eType="//DibonulAugusGubutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusaufriboguGusBeFribuBifriBuCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidabeNulauboNulius" eType="//AnboBoBiEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubobubigudagulius" eType="//EunulaufribodaGusfriNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibibuBiBodaBibiBigunus" eType="//BaBibibuBiguLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DaGudanulAuDagusfriEs">
    <eLiterals name="DiguBefridaNulauBebebibogusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Audabubunulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibobogusGusAunulauGuCus" eSuperTypes="//EfriNulauBufriDabogucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbebobubetus" upperBound="-1" eType="//Audabubunulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufricio" eType="//EunulaufribodaGusfriNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusbibifribudaFriNus" eSuperTypes="//DuBiBitin //DabeNulAuguslus //Audabubunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agugugusBofriBucio" eType="//EunulaufribodaGusfriNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabuFribeBuboGugusbibifriguLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eububuGusgububonulaubiBiBiBoLus" ordered="false" upperBound="-1" eType="//BaDabiBodaGufriNulauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedadaBoFribibiBuDagudafriNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbobibiGuNulaunulauDaes" ordered="false" eType="//BigusbibifribudaFriNus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audanulaudaBotin" eType="//AnboBoBiEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodabugubuDabeNulAubugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulaugusbogubuDafriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubugusBibiDalius" abstract="true" eSuperTypes="//BigusbibifribudaFriNus //BaBibibuBiguLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuGuGusfriFribigucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulaugudafriDanulaugues" eType="//FaGuDaGubobenulauguGusbibitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibuGuDaBigubotus" abstract="true" eSuperTypes="//AGubofriBoBubibebuBiLius //BaBibibuBiguLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBuGusdabuNulAunus" eType="//BeGusdafriGuGusbebubeEs" eOpposite="//BeGusdafriGuGusbebubeEs/doBubonulaubogubebeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAufribenulaubibegunulius" eSuperTypes="//BaBibibuBiguLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibuBeFribubeBidabetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBebeBuBeNulaufribiBobiTin" abstract="true" eSuperTypes="//BigusbogubugusNulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBifrigunulauBelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBobuguGusgugufriguDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Badabegudanulius" abstract="true" eSuperTypes="//AlfribegufriBuGubiBuBubeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbudaFriBufriBiDalius" eSuperTypes="//DodabugubuDabeNulAubugustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagusBugusDaBotin" eType="//DaGudanulAuDagusfriEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBiBuGufriBuDaguGusboDalus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubutin" eType="//AnboBoBiEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiBiBogudadaguBidalius" eSuperTypes="//AlfribegufriBuGubiBuBubeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbibudabeBunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulauGusgufribubuTor" ordered="false" eType="//BigusbogubugusNulautor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulauboBeBeBobobebufritin" ordered="false" upperBound="-1" eType="//FaBobuguGusgugufriguDatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbofriboBebinus">
    <eLiterals name="AlfribiboGubuDaGustor"/>
    <eLiterals name="DobogusBugusbebunulAubilus"/>
    <eLiterals name="DagusauBoDagusFribiBubolius"/>
    <eLiterals name="BiguBiBubidafrinulaubiNulius"/>
    <eLiterals name="BiGusaubebibocus"/>
    <eLiterals name="DubebugunulauButus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusNulaunulAuBufrigusBuBububedabicus" eSuperTypes="//BaBibibuBiguLus //EuBifrigunulauBelius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edabiBuGuGusbonulAufriGutin" eType="//AbuGubeguBenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbebogusbobobugusfrinulauboBubeGusEs" eSuperTypes="//EuBifrigunulauBelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabeBigusauboNulAudanulAuGusdatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusbiBefrifridafricus" ordered="false" upperBound="-1" eType="//AgusNulaunulAuBufrigusBuBububedabicus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baNulaubibibobobiLus" eType="//EunulaufribodaGusfriNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="audanus" ordered="false" eType="//DuBiBitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulAudabufriNules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fadaGusbuNulAunules" eType="//EubibigusFridabonulauboTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnboFrigusdafribiBuGusBebubetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doFridaBidabunulaubues" ordered="false" upperBound="-1" eType="//FabuFribeBuboGugusbibifriguLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BibenulAubibufribitin" instanceTypeName="typeEuBigugusgunulAuBocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobibugusgusnus" eSuperTypes="//Audabubunulius //DububeBetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faNulAuBobunules" eType="//EunulaudagusbuBebefriguBolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BanulauGusgusfrigubedator" instanceTypeName="typeDafriguBebiFribeBebunulauBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobenulaubutus" eSuperTypes="//EuBifrigunulauBelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDagusgusBoBiFrinulaubiBebees" ordered="false" upperBound="-1" eType="//DodabugubuDabeNulAubugustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabunulaugusnulaubebeNulEs" instanceTypeName="typeAFridafrifries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAugusfribeNulaubuBeGuCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AguGuBeGusGusgusbubeCus">
    <eLiterals name="EbebodaguLius"/>
    <eLiterals name="AbuNulAunulAuDaBodabebitus"/>
    <eLiterals name="DubofridabiboFriNus"/>
    <eLiterals name="FafriBeBuGusBibobuGudaCus"/>
    <eLiterals name="BrauGuboGuFridabifritor"/>
    <eLiterals name="FagusfriGusauguGusGusgusBuEs"/>
    <eLiterals name="BaNulAugusNulAubugusnulauGufridaTor"/>
    <eLiterals name="AubefrinulAutor"/>
    <eLiterals name="AufridadabiNulAuTus"/>
    <eLiterals name="DugudabiNulAuGusGunules"/>
    <eLiterals name="BiNulaubobobiGusfricus"/>
    <eLiterals name="DuBuGubinulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbebogusAugubobubibeBufritor" eSuperTypes="//DuBiBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedafribibeGuBigufrifribiTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAugusfrinulauGubedaBobotin" eSuperTypes="//Audabubunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusdafriGuGusbebubeEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBubonulaubogubebeCio" ordered="false" upperBound="-1" eType="//BibuGuDaBigubotus" eOpposite="//BibuGuDaBigubotus/daBuGusdabuNulAunus"/>
  </eClassifiers>
</ecore:EPackage>
