<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="angusfrigustor" nsURI="http://hub.de/rcore/examples/angusfrigustor" nsPrefix="PCMr">
  <eClassifiers xsi:type="ecore:EClass" name="DoBigudabebigubeGusBeNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbobofribeBebobuFriNulaudanus" instanceTypeName="typeBiNulaudabeguNulaufriGusBeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeguGusAuguFriNulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusbefriBegusBinules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGuBubiDabufrigusbenus" eType="//BebobigufriFriNulaugusLus" eOpposite="//BebobigufriFriNulaugusLus/doGubedadaguNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabuguguDabeBogusbigustus" eSuperTypes="//AlgusbefriBegusBinules //DoBigudabebigubeGusBeNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeBogusAugusius" eSuperTypes="//BeguGusAuguFriNulauTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edanulauBibedaBobifriGusguslus" eType="//AbobofribeBebobuFriNulaudanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubofribidabeBoboDaboDacus" eSuperTypes="//BabeBogusAugusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulauguFribuGugusbelius" eSuperTypes="//BraubofribidabeBoboDaboDacus //AlgusbefriBegusBinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebiboGusGusgubeTin" upperBound="-1" eType="//DoBigudabebigubeGusBeNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebobigufriFriNulaugusLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBugusNulaubuGunulIus" ordered="false" upperBound="-1" eType="//BeguGusAuguFriNulauTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGubedadaguNules" ordered="false" upperBound="-1" eType="//AlgusbefriBegusBinules" eOpposite="//AlgusbefriBegusBinules/euGuBubiDabufrigusbenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAugufriNulauTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaubobeFriBinulauBebibelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbegusbebunulaudaGusbeTin" eSuperTypes="//BraubofribidabeBoboDaboDacus //FaNulaubobeFriBinulauBebibelus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBeBibugugugusfridalius" instanceTypeName="typeAnbudanulaunulaunulaufriBobiGusFrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusBigusDaBuDaBegusbiFrinus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubibufriNulaugubebibotor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAugusgufriboFribunulautor" eSuperTypes="//BraubofribidabeBoboDaboDacus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Anbobogusbenulaubibinulaunus">
    <eLiterals name="DibifribogusAubonulauLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABubugulus" eSuperTypes="//FaNulaubobeFriBinulauBebibelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubugubedaGusbetus" ordered="false" upperBound="-1" eType="//AlgusbefriBegusBinules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnBoNulAugubiGusnulaunulauLius" instanceTypeName="typeBeFriDabiBobibeboBedanus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AufribedabubinulauguNules" instanceTypeName="typeDibubigusfribuboDaBunulaubucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuguFribinulAufribofrinulEs" eSuperTypes="//ABubugulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBofriguBeGusgustor" ordered="false" upperBound="-1" eType="//FaNulaubobeFriBinulauBebibelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeboGusAuBuboBoboBubuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebunulauGusbiDabugusbotus" ordered="false" upperBound="-1" eType="//DugusBigusDaBuDaBegusbiFrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabobegusBuBegusbotus" instanceTypeName="typeDabigusDaBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnNulAudadaBunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beFrigusBonulAuDaboBodagusButin" eType="//AufribedabubinulauguNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabubiBegustin" abstract="true" eSuperTypes="//AlgusbefriBegusBinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaubugufriDaguCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubedagusBibobuBeDabulius" eType="//FaNulaubobeFriBinulauBebibelus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBobubegusius" eType="//Anbobogusbenulaubibinulaunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BebufribedagusDafrilus">
    <eLiterals name="EuDagubofritus"/>
    <eLiterals name="Bibidadacus"/>
    <eLiterals name="DoFribebiBigubuGusgusNus"/>
    <eLiterals name="AudabifrinulAudafribinus"/>
    <eLiterals name="DabuBunulaugubeguFribifrilus"/>
    <eLiterals name="BibobiboGuguEs"/>
    <eLiterals name="Babigucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoboBoNulauNulAubicus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusbubiBibobeBeBeBebonulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuNulAudaboBobibitor" instanceTypeName="typeAnbobobonulauBuBebofrifriBocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnDaNulAubuBogugusIus" eSuperTypes="//FaNulaubobeFriBinulauBebibelus //AnulAugufriNulauTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaFrifrigugunulAudanulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alGubobebibubiBiBobubogusbobuguNus" eType="//Anbobogusbenulaubibinulaunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaudaBenulAubudaBogusbubogusbuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibedadabuFriGuguslius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anGuDafriBuguFriGuscus" eType="//AbobofribeBebobuFriNulaudanus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebiGudabibuTor" ordered="false" eType="//EubibufriNulaugubebibotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBibubiNulAugugubuBuDadaBuTus" eSuperTypes="//AlnulaudaBenulAubudaBogusbubogusbuTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubogugusgusGusnulaubuFrigusAugunulius" instanceTypeName="typeDoGunulAuNulauBoBeFriguscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubububeGusfriBobidafriNulaucio" instanceTypeName="typeABebubiBuBeFriDaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbebibunulaubeguGusLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alDaguBeBeBugunulius" upperBound="-1" eType="//DabubiBegustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeboboDadaBiBubofriBulius" eSuperTypes="//AnnulAugusgufriboFribunulautor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anaunulaunulAubobinulaufricus" eType="//AbobofribeBebobuFriNulaudanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudadabogubenulaubugusdanulauLius" eSuperTypes="//FaNulauguFribuGugusbelius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Albubinus" instanceTypeName="typeAbeFriNulauBodaGubutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudaguGubigunulius" eSuperTypes="//DibedadabuFriGuguslius //BeboboDadaBiBubofriBulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusGuguNulauTor" eSuperTypes="//AnDaNulAubuBogugusIus //BeguGusAuguFriNulauTin //BabeBogusAugusius"/>
</ecore:EPackage>
