<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dabotus" nsURI="http://hub.de/rcore/examples/dabotus" nsPrefix="RX">
  <eClassifiers xsi:type="ecore:EClass" name="AGusNulaubuBoGubulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abibefrifribebulus" ordered="false" upperBound="-1" eType="//DoboGufriguGusNulauBiboGufriGusButin" eOpposite="//DoboGufriguGusNulauBiboGufriGusButin/anfrifricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbubifribeNulAuBudadaBenules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGutor" eSuperTypes="//AlbubifribeNulAuBudadaBenules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGubifrigudaNulAuBoLus" ordered="false" upperBound="-1" eType="//DogubebogusgufribiLius" eOpposite="//DogubebogusgufribiLius/aGusfridadafribetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobubodabibibedaBinulauNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBubegutus" upperBound="-1" eType="//AlbubifribeNulAuBudadaBenules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doFriGusgudabicus" eType="//AlbubifribeNulAuBudadaBenules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobidabinulAubunulauBogucio" eType="//DoboGufriguGusNulauBiboGufriGusButin" eOpposite="//DoboGufriguGusNulauBiboGufriGusButin/bigusfrigubibidagucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Digugugusaubebodator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubeBubiButor" ordered="false" upperBound="-1" eType="//DobubodabibibedaBinulauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauBeguDabobobubotus" instanceTypeName="typeBeguBoLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadaBoBugusbigufriBufriBoBinulAuGusBulus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digubifribubotus" ordered="false" upperBound="-1" eType="//Digugugusaubebodator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogubebogusgufribiLius" abstract="true" eSuperTypes="//Digugugusaubebodator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGusfridadafribetin" ordered="false" eType="//AGutor" eOpposite="//AGutor/daGubifrigudaNulAuBoLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedaBogusbenulaunulaubibitor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="didaBoBegubeNulaulus" eType="//BrauBeguDabobobubotus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabeBobiBiGudafribuBocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabofriDaBeFriBufriTin" ordered="false" eType="//DogubebogusgufribiLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauBobiBiGusbufriBiguNulaubuEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augudafribeBedabigusFrigusius" eType="//BrauBeguDabobobubotus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AldabibufribiBegusdator">
    <eLiterals name="DubububoNulauBeboFribudabelius"/>
    <eLiterals name="AnbebonulAuBodaFriTin"/>
    <eLiterals name="BebedaboGuboFridagusgusTus"/>
    <eLiterals name="AnfriBugubunulAuBiNulaubodanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbegusgubiDabeFribuBugusAutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBibiGubogusboDagubifriTor" abstract="true" eSuperTypes="//DobubodabibibedaBinulauNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnNulAunulAunulAuGuNulAuBonus" instanceTypeName="typeDibiguDaNulAububuBuDabufrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBeFridaBugusaubocus" eSuperTypes="//Digugugusaubebodator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabegudaBigubiBeNulaubiLus" eSuperTypes="//DadaBoBugusbigufriBufriBoBinulAuGusBulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibiBobicio" eType="//AldabibufribiBegusdator" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaubiDalus" eSuperTypes="//DogubebogusgufribiLius //AGutor //DobubodabibibedaBinulauNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBiNulaububiguBobuTus" ordered="false" eType="//AbegusgubiDabeFribuBugusAutin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baNulaubibobebotus" ordered="false" upperBound="-1" eType="//AlBuBedadagudacus" eOpposite="//AlBuBedadagudacus/banulauGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AgusbugusbibubuBecus" instanceTypeName="typeAuGusgubobiDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebigusbuCus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doBiboGuBoDafriCio" eType="//BrauBeguDabobobubotus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoboGufriguGusNulauBiboGufriGusButin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusfrigubibidagucus" ordered="false" eType="//DobubodabibibedaBinulauNus" eOpposite="//DobubodabibibedaBinulauNus/dobidabinulAubunulauBogucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfrifricio" ordered="false" eType="//AGusNulaubuBoGubulius" eOpposite="//AGusNulaubuBoGubulius/abibefrifribebulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dutus" eSuperTypes="//AGutor //DoBibiGubogusboDagubifriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babuFriNulauDanulaubuBifriGubulius" ordered="false" eType="//DobubodabibibedaBinulauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraufrifriDaboguGufrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubiBubegusBifribebubobelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBuBedadagudacus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigudanulAuGusguscio" upperBound="-1" eType="//BaBeFridaBugusaubocus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusgusfricio" ordered="false" eType="//DabegudaBigubiBeNulaubiLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulauGulius" ordered="false" upperBound="-1" eType="//BenulaubiDalus" eOpposite="//BenulaubiDalus/baNulaubibobebotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbogunulAugusAufrinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anboBegusfribeBeGuBegusaunulEs" eType="//AldabibufribiBegusdator" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eubunulaunulaugusbugunulautin" eSuperTypes="//DogubebogusgufribiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digudaBudaboGuslus" ordered="false" eType="//Dutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusbiguboBibubonulaubugusgubuCus" abstract="true" eSuperTypes="//BraubiBubegusBifribebubobelus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebufribeBigusDagugufricus" eType="//AldabibufribiBegusdator" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlGugusnulaudanulAugubudabubicus">
    <eLiterals name="AnGusbebiBebinulaufriBebinulaubiTin"/>
    <eLiterals name="DunulauNulauGusbuboGusGusauLus"/>
    <eLiterals name="AbufribeBebiGulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlBifrigusnulaugusgusbuBoTus">
    <eLiterals name="Albodanulaugugusgugusnus"/>
    <eLiterals name="DudafribebuBedaboboBogubitin"/>
    <eLiterals name="BabebinulAuFriBobeLus"/>
    <eLiterals name="AnBenulAubigusnus"/>
    <eLiterals name="BibuBibibefrigusdanules"/>
    <eLiterals name="AuDabigudaNulautin"/>
    <eLiterals name="BrauDagusgusBuDagusfriBeBuBidaNulEs"/>
    <eLiterals name="DanulauNulAuBefrigudafridanules"/>
    <eLiterals name="AnbiFribedabiGusAuGubunulauFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusgusfribubobuBegusbues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbubefrifrigusgusboBocus" eSuperTypes="//Digugugusaubebodator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algusBubebebeboguBifriGues" eType="//AlGugusnulaudanulAugubudabubicus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaubifrifrigusdaBeGuboFridaboButin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubonulAuLius" ordered="false" upperBound="-1" eType="//AlbubifribeNulAuBudadaBenules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alaugusgustor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedaBibeDabiGubonulAuGusbinulAuBunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaNulAubeguscio" instanceTypeName="typeEunulauGuNulaubolius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AgubibobofrifriguBebuGusnus" instanceTypeName="typeBanulaubibiBuGusBebudaboFriNulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbebenulaubiNulauguslus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusauGugusFriNulAubububucus" eSuperTypes="//Eubunulaunulaugusbugunulautin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebuBibonulaubeguCio" eType="//AgusbugusbibubuBecus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebiGusbeBoBunulautin" ordered="false" eType="//AbegusgubiDabeFribuBugusAutin"/>
  </eClassifiers>
</ecore:EPackage>
