<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dibebebilius" nsURI="http://hub.de/rcore/examples/dibebebilius" nsPrefix="OT">
  <eClassifiers xsi:type="ecore:EDataType" name="BegusDadabebogusbuBiTor" instanceTypeName="typeABuBinulAuFribibebonulAuGudaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBigubeguGusIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGusnulauFriFridaLus" ordered="false" eType="//BiBuBeDabigugunulauBifrigucus" eOpposite="//BiBuBeDabigugunulauBifrigucus/danulauboBegufrifriBoboboBiTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFriBonulAubiDaguNulius" upperBound="-1" eType="//AnGusbunulauGusgugutor" eOpposite="//AnGusbunulauGusgugutor/dogubuguBoBigucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobuNulaunus" ordered="false" eType="//AlnulauBenulauBiguslus" eOpposite="//AlnulauBenulauBiguslus/duBuNulAubiguDaTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbinulAugubuguBedabunulAugusIus" eSuperTypes="//BeBigubeguGusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBuBeDabigugunulauBifrigucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebugufriboFribegusbidagufriFridabiBoes" ordered="false" upperBound="-1" eType="//AlbinulAugubuguBedabunulAugusIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabefridabiGudadaNulautin" eType="//AlbinulAugubuguBedabunulAugusIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulauboBegufrifriBoboboBiTus" ordered="false" upperBound="-1" eType="//BeBigubeguGusIus" eOpposite="//BeBigubeguGusIus/baGusnulauFriFridaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabiBedafribebufribolus" eSuperTypes="//BeBigubeguGusIus //AlbinulAugubuguBedabunulAugusIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBugugubinulaubiTor" ordered="false" eType="//BeBigubeguGusIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AdabugusgusbubiboGusbiBebubuNus">
    <eLiterals name="DibiBiGucio"/>
    <eLiterals name="EbuBuGuGusBegusbilius"/>
    <eLiterals name="AugusguGudabobuGubugusgusNus"/>
    <eLiterals name="AbedabiBiNulauboBuBenulaudadator"/>
    <eLiterals name="AuGusfriboBubeBelus"/>
    <eLiterals name="BiBebufriBoguBofries"/>
    <eLiterals name="BegudadagubudabibiGuguNulaunulaubeLus"/>
    <eLiterals name="AubeBitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusbunulauGusgugutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagubuBeGusdabubeTin" upperBound="-1" eType="//BiBuBeDabigugunulauBifrigucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogubuguBoBigucus" ordered="false" eType="//BeBigubeguGusIus" eOpposite="//BeBigubeguGusIus/alFriBonulAubiDaguNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauNulauBoNulAudanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibefribunulaufriNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulaunulaufriLius" ordered="false" upperBound="-1" eType="//BiBuBeDabigugunulauBifrigucus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aFriGusnulaunulauDaGudalius" eType="//AdabugusgusbubiboGusbiBebubuNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AndaDaBiBegubeGuBiBucus">
    <eLiterals name="EubeDabinulaunus"/>
    <eLiterals name="BraubufriBububetin"/>
    <eLiterals name="Dulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbofridagugubinulAuBogutus" instanceTypeName="typeDiFridadaboBedabuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuDabonulaudaBoBodatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboGusbibudabofricio" ordered="false" eType="//AlbinulAugubuguBedabunulAugusIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafriBudabonulAuguguslius" upperBound="-1" eType="//AlbinulAugubuguBedabunulAugusIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusguNulaunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaDabubiboBoBeGufrinulaubeGuguFrinus" eSuperTypes="//AlGusguNulaunulius //AlbinulAugubuguBedabunulAugusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusBenulAugubofribigulus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Ecus" instanceTypeName="typeDofriNulaugusgusNulaubeDaNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebebiNulauFrigulius" abstract="true" eSuperTypes="//AlbinulAugubuguBedabunulAugusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAunulaugusGusDabubuBiDacus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaDaboguGubogustus" instanceTypeName="typeEboDaBibiCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBenulauguNulauTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BenulAubegusbobicus" instanceTypeName="typeBiFriBedagusbiguBitin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBobebelus" instanceTypeName="typeAnbonulaudagusNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusauFrinulaunulius" eSuperTypes="//BeBigubeguGusIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biDaFriBufriFrilius" eType="//AdabugusgusbubiboGusbiBebubuNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubobubiguNulaudadaBetus" eSuperTypes="//BiBuBeDabigugunulauBifrigucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauFridabuBues" eType="//FaDaboguGubogustus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBubibibofrifrigulius" eType="//BenulAubegusbobicus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBebufriboBenulauBugusBuNus" abstract="true" eSuperTypes="//DiGusBenulAugubofribigulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulaudaBiboGusFribibenulaunus" eSuperTypes="//BeBigubeguGusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubonulauGusBobebeNus" eSuperTypes="//AnBebufriboBenulauBugusBuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulauBenulauBiguslus" eSuperTypes="//BegusauFrinulaunulius //AuNulaudaBiboGusFribibenulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBuNulAubiguDaTor" ordered="false" eType="//BeBigubeguGusIus" eOpposite="//BeBigubeguGusIus/dobuNulaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eubedabinulius" abstract="true" eSuperTypes="//BebebiNulauFrigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubigusBebiDadagunulauButus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebeGuBubeBiFriDabotor" eType="//BenulAubegusbobicus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGusbebegububiboFrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaugugubeBodagusnulAufrinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBoDanulIus" eType="//AnbofridagugubinulAuBogutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusdaBoguBiboes" eSuperTypes="//FaBenulauguNulauTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabobubibiBeGububobugusfrigusbitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusFriGubiGusAudadanulaubuBolus" ordered="false" eType="//EubobubiguNulaudadaBetus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anauBubees" eType="//FaDaboguGubogustus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugudafriguBoBebigusbecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eubigubees"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnDagusbudagusauguBocus" eSuperTypes="//AnGusbunulauGusgugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAubegusgugusfritus" eSuperTypes="//AnGusbunulauGusgugutor //BiBuBeDabigugunulauBifrigucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulaubibegubogugusgusbutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diFriGubebuNulaugusfriGusCus" ordered="false" upperBound="-1" eType="//DaBoGusdabuBifriboboBoNulAucio" eOpposite="//DaBoGusdabuBifriboboBoNulAucio/dadaboBeGusFriboFriboCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebiguFriBubibiBegunulaugusbenus" eSuperTypes="//DabiBedafribebufribolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDafrigusBonulauTor" ordered="false" upperBound="-1" eType="//FaBenulauguNulauTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubeGusnulius" eSuperTypes="//DabiBedafribebufribolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBoguGusbuNulaunulaunulEs" ordered="false" upperBound="-1" eType="//AnulAunulaugusGusDabubuBiDacus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibebidadabogucus" ordered="false" eType="//AnulAunulaugusGusDabubuBiDacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlNulAuBigubiguslius">
    <eLiterals name="DanulaunulaudaLus"/>
    <eLiterals name="DigusnulaubibuNulauBeTus"/>
    <eLiterals name="BenulaugusboBeBiguNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbedanulAuDaBubibiguDaDabeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBoGusdabuBifriboboBoNulAucio" abstract="true" eSuperTypes="//EubonulauGusBobebeNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaboBeGusFriboFriboCus" ordered="false" eType="//AuNulaubibegubogugusgusbutin" eOpposite="//AuNulaubibegubogugusgusbutin/diFriGubebuNulaugusfriGusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiFribinulauFrigububefridaes" eSuperTypes="//EuDabonulaudaBoBodatus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BagugunulAuDaFrifritor" instanceTypeName="typeDifrigusBinulauNulAutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabeDanus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biboBebofridagusguses" eType="//AndaDaBiBegubeGuBiBucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAunulaudaNulAunulaubetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulauguBigusguGunulauguscio" eSuperTypes="//BibefribunulaufriNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBibedabuGusbifries" ordered="false" eType="//AlGusguNulaunulius"/>
  </eClassifiers>
</ecore:EPackage>
