<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="braunulius" nsURI="http://hub.de/rcore/examples/braunulius" nsPrefix="as">
  <eClassifiers xsi:type="ecore:EClass" name="DibudaGunulaubobicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaGuGuDaBedaBoBebuGuBubidadator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigunulaubofridaLus" ordered="false" upperBound="-1" eType="//FaNulaubefrinulaufribiBuBotor" eOpposite="//FaNulaubefrinulaufribiBuBotor/aboBibeboDafridaGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabebunulaunulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubobeDabobonulaubiNules" ordered="false" eType="//EudaGuGuDaBedaBoBebuGuBubidadator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufrinulauDagugusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguCus" eType="//ABiDabeDabonulauboTin" eOpposite="//ABiDabeDabonulauboTin/bigusBogusgusguboNulAudaguNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnFriGudaDaBodaboGusFries" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabibugubiGunulaufrinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebefriDabubogusgudanulaugubilius" eSuperTypes="//AufrinulauDagugusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBinulAubibobobiGuslius" ordered="false" upperBound="-1" eType="//AnFriGudaDaBodaboGusFries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusGusnulaubibegufribobocus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiGusbugusBobobobibonus" instanceTypeName="typeEubiBobuGuBodalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bagusgusgudator" abstract="true" eSuperTypes="//EgusGusnulaubibegufribobocus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebeBogudaDaNus" eType="//BiGusbugusBobobobibonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbibibeBoGusfriguboGudabebunus" eSuperTypes="//AufrinulauDagugusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabobogusauBufriBifrilius" ordered="false" eType="//DiBubedabobonulauGuguNulAuBuBeBinus" eOpposite="//DiBubedabobonulauGuguNulAuBuBeBinus/eufribuguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabebebogusBobigusGuBucus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EnulAubebebiDabeGusGunulius">
    <eLiterals name="DagunulaugusbebifribeGusbedaNus"/>
    <eLiterals name="AlbiFribefriBuBinulius"/>
    <eLiterals name="DobodaguBegusBiGuGusbitin"/>
    <eLiterals name="Aldagusgubidalus"/>
    <eLiterals name="EuBeBofribeguCus"/>
    <eLiterals name="DugubobuBidabiBoTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eubinulaubifrinulaudanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusbubeDabilus" eSuperTypes="//AufrinulauDagugusNus //BabebebogusBobigusGuBucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulautus" upperBound="-1" eType="//EnulAubebebiDabeGusGunulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albobobinulaugubodaFriGucio" eType="//EnulAubebebiDabeGusGunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABiDabeDabonulauboTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusBogusgusguboNulAudaguNulEs" ordered="false" eType="//AufrinulauDagugusNus" eOpposite="//AufrinulauDagugusNus/auguCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBofribenus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AubugugusgusAugudagusgusBugunulAutin">
    <eLiterals name="DinulauBoNulaubuDafributus"/>
    <eLiterals name="AlbobiBubuGusdaBucus"/>
    <eLiterals name="DaFribobiBubiNulaunulauboFritus"/>
    <eLiterals name="FadabegubufribiBegutor"/>
    <eLiterals name="FafriboBoFribidaGuFrifridaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAubobeBoBeDadaDagubonulAubulus" eSuperTypes="//Eubinulaubifrinulaudanus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbebiDaBibibigusBeLius" instanceTypeName="typeFagubebudabebobiDalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubuBugusnulauBugusFrinus" eSuperTypes="//FabebunulaunulEs //AlGusbubeDabilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusBeBubebigubiBobunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faboBububucio" eType="//Alfricus" eOpposite="//Alfricus/aboBobonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabiboBogusbobufribuDadaguCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGusAubofriFriTin" eType="//AnbibibeBoGusfriguboGudabebunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibiBibubenulAuNulAubocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusbuBebeCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alfricus" eSuperTypes="//AlGusbubeDabilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusfrigunulauBubiNulautus" upperBound="-1" eType="//DabibugubiGunulaufrinulEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aboBobonules" ordered="false" eType="//BagusBeBubebigubiBobunus" eOpposite="//BagusBeBubebigubiBobunus/faboBububucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulaubigugusdadacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguGusdabuGudaDacus" eSuperTypes="//ABiDabeDabonulauboTin //BebefriDabubogusgudanulaugubilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegubeNulaufriBitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anNulAufrinulEs" ordered="false" upperBound="-1" eType="//Eubinulaubifrinulaudanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBubedabobonulauGuguNulAuBuBeBinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibudabufrigudafribibifrifriNus" ordered="false" eType="//Alfricus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBuBobibies" ordered="false" eType="//AnAubobeBoBeDadaDagubonulAubulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufribuguses" ordered="false" eType="//AnbibibeBoGusfriguboGudabebunus" eOpposite="//AnbibibeBoGusfriguboGudabebunus/dabobogusauBufriBifrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibedaBonulauFrigusIus" abstract="true" eSuperTypes="//ABiDabeDabonulauboTin //AnFriGudaDaBodaboGusFries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufribubeNules" ordered="false" eType="//BabebebogusBobigusGuBucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeDaguGuGusnules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidabegusBubegubonulaubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABobeDabufritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulauTin" upperBound="-1" eType="//AnbebiDaBibibigusBeLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBues" instanceTypeName="typeDoBuBiGunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGunulauGugubobonulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubigubiBefrigusgubolius" eSuperTypes="//DibudaGunulaubobicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGuBuFrigusbubedagunulaudabebebiEs" ordered="false" eType="//BrauBofribenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibeboguBidabudagudaBeBues" eSuperTypes="//AGunulauGugubobonulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaudaGusboFriBoLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Abenulaufrigusnulaulius" instanceTypeName="typeBanulaubiGusfriguFrigusauBobubigusbitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBegusbuFrigugusaunus" eSuperTypes="//BabebebogusBobigusGuBucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuboFribigusgusnulAudabiDadafridator" instanceTypeName="typeAnaugudaBiBugubenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofribogusBoNulauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebeBiGufricio" eType="//BabebebogusBobigusGuBucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrigusFriGubegusnulautus" eSuperTypes="//BrauBofribenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dagubugusdabigusgusnulaunus" eSuperTypes="//Eubinulaubifrinulaudanus //BrauBofribenus //BebefriDabubogusgudanulaugubilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobubebies" eType="//BiGusbugusBobobobibonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlguBebiboLus" instanceTypeName="typeEguFribedadanulautus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EbiNulAunulaunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubobobibeguBuguNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alguDabinus" eType="//AnbebiDaBibibigusBeLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebobuBebibubugudanulaudalius" ordered="false" eType="//DudagusDafriGubuTor" eOpposite="//DudagusDafriGubuTor/begusgubigufrinulAuBolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EubiFriGusfriBeBefriFriboGuboTin">
    <eLiterals name="BigusbogubuguBubufriNules"/>
    <eLiterals name="EbinulIus"/>
    <eLiterals name="DoGubeBuGugubibibibeNulAuTin"/>
    <eLiterals name="DiGubifribeDacio"/>
    <eLiterals name="Didadadafrinules"/>
    <eLiterals name="AubobofriBonulAuGubebilius"/>
    <eLiterals name="DoDaBuBuGuguboDabeFrifriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DifrigunulauGuNulauCio">
    <eLiterals name="AubiGusNulAuBeboBeguGusfriDacus"/>
    <eLiterals name="DobuNulAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibodabibubeBibiguGuBuguBulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBiFribidanulAuboGucio" instanceTypeName="typeDibebeGusbufridabebocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubifribufribodaGuNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubebiGusbodaBedagubofribuNus" instanceTypeName="typeDadabenulAuFriGusbotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABobobiBigusaubibeBibenulaunulauboGusEs" eSuperTypes="//EubuBugusnulauBugusFrinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulAufries" eType="//BiGusbugusBobobobibonus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedabodaBidatin" eType="//DifrigunulauGuNulauCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGunulaubigudanulauGutin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BegusAubibonulaubibinulauguLus">
    <eLiterals name="AbibefribiFriFrinus"/>
    <eLiterals name="Au"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbonulaubeGubenulaugusTor" eSuperTypes="//DibodabibubeBibiguGuBuguBulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DanulauDabunulAubeFrilus" instanceTypeName="typeDaGuFriDabugutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuguboDabuBefrinulIus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albubibiBebigusbubegusgutin" ordered="false" upperBound="-1" eType="//BrauBofribenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudagusDafriGubuTor" eSuperTypes="//Eubinulaubifrinulaudanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusgubigufrinulAuBolus" ordered="false" upperBound="-1" eType="//BraubobobibeguBuguNus" eOpposite="//BraubobobibeguBuguNus/bebobuBebibubugudanulaudalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriboGusgugusdabuGuCio" eSuperTypes="//BrauBofribenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulAudabinulauguBetin" eType="//DibudaGunulaubobicio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubeBulus" upperBound="-1" eType="//BegubeNulaufriBitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DagubedaBufribinulaugusgunules">
    <eLiterals name="AlBobibedabubebibitor"/>
    <eLiterals name="BabogusGudaCus"/>
    <eLiterals name="DoGusboBidabunulauFriCio"/>
    <eLiterals name="AubefribenulauBibubuDagudanulIus"/>
    <eLiterals name="BraufridadaBuNulauDadaFriguDaes"/>
    <eLiterals name="EbeBobenulaubonus"/>
    <eLiterals name="AndabegusDabiFribubogunulEs"/>
    <eLiterals name="AbiBobebeNulaubiBuGusButus"/>
    <eLiterals name="DunulaufriBiFrinulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AngusfrigusguBibuBeFriBebeBeFriBetin" instanceTypeName="typeAnaubebefridanulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebubeNulaubolus" eSuperTypes="//AnfriboGusgugusdabuGuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabebobunulAuNulaucus" eType="//EnulAubebebiDabeGusGunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BadaBeDadaboguBucio" instanceTypeName="typeBigusauBubunulaugusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusnulaugustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audabegudafriDaBuFriTus" ordered="false" eType="//DibiBibubenulAuNulAubocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnnulaunulAuboBobuCus" instanceTypeName="typeAnulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuDanulAuBebefricus" abstract="true" eSuperTypes="//AnfriboGusgugusdabuGuCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Aubobunulaubilius">
    <eLiterals name="AlguBubugububolius"/>
    <eLiterals name="DoboguBebubiboBelus"/>
    <eLiterals name="Dubebibubudagubufribues"/>
    <eLiterals name="AnaubeBulus"/>
    <eLiterals name="EbegusgugusbofrigubuFribinulAuCus"/>
    <eLiterals name="Anfrinulaudabebebibelus"/>
    <eLiterals name="Dabugusbofrinules"/>
    <eLiterals name="EuguBuBuBoNulaubebeEs"/>
    <eLiterals name="DadafriBiGunulius"/>
    <eLiterals name="DidaDaguboGuBoBelius"/>
    <eLiterals name="Fagusbudadabogusbegusfrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aldadabubedabibebilus" eSuperTypes="//DuFrigusFriGubegusnulautus //DibudaGunulaubobicio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="danulaubifribies" eType="//AubugugusgusAugudagusgusBugunulAutin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusAubulus" ordered="false" upperBound="-1" eType="//BagusBeBubebigubiBobunus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algusgusbubuBiTor" eType="//DanulauDabunulAubeFrilus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusGusFrifrigusbeBulius" eSuperTypes="//Alfricus //BrauBofribenus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibunulauGusauguslius" eType="//BiGusbugusBobobobibonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BiFrifriBenulAufribufriGuEs">
    <eLiterals name="DuBuboguboTor"/>
    <eLiterals name="DabebufriBitus"/>
    <eLiterals name="DunulauNulaufribeboFricus"/>
    <eLiterals name="EGusbigudaBoDaBoguFrifriLus"/>
    <eLiterals name="BibedaBibodaBiDaDanulIus"/>
    <eLiterals name="FaBuGubegustor"/>
    <eLiterals name="BrAuguBugusaulus"/>
    <eLiterals name="DanulAuboDadanulauBugudanulIus"/>
    <eLiterals name="DiBigubonulauFridafrigusNulAuCus"/>
    <eLiterals name="ADaboGusgusfrinulaubibobetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBubibiBonulAuBiCio" instanceTypeName="typeFadaguFriguLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulaubuFriBebeBegutor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBebiguboLus" eType="//AnnulaunulAuboBobuCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuDaGusGusBebeGunulauguTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulaugusgusdabubufrifritus" eType="//DuFriBifriGugufriGusNulIus" eOpposite="//DuFriBifriGugufriGusNulIus/bebeBofribegusfrinulaudaGuguTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FagusbifrinulAubonulaubiboBulus">
    <eLiterals name="BrAuDafribobeguNules"/>
    <eLiterals name="BebefribibobiDadaFridafrinulEs"/>
    <eLiterals name="FabuBubogusBoguBiBotus"/>
    <eLiterals name="DaBobigusBudafrigufritus"/>
    <eLiterals name="BiGusdaNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaubefrinulaufribiBuBotor" eSuperTypes="//Bagusgusgudator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aboBibeboDafridaGucus" ordered="false" upperBound="-1" eType="//EudaGuGuDaBedaBoBebuGuBubidadator" eOpposite="//EudaGuGuDaBedaBoBebuGuBubidadator/bigunulaubofridaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuFribugusBeDagufriFribeBuNulauGusCus" instanceTypeName="typeAugusfribigusgusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauDagubufribenulaucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBeGusboboBiBoTor" eSuperTypes="//DidabegusBubegubonulaubitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFribubibebitus" ordered="false" upperBound="-1" eType="//DudagusDafriGubuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaubebiLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibefribebebenulaufriGuFribeCio" ordered="false" eType="//BiNulaubuFriBebeBegutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebibogusbeboGudabitus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubobobedabuguses" eType="//FagusbifrinulAubonulaubiboBulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabebifridagusfrigusEs" eType="//AngusfrigusguBibuBeFriBebeBeFriBetin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraudagugusaubeFrigusBibuboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafribigusdaBubunulAuNulAubocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAudabogusnulAubidadagues" eType="//EbiNulAunulaunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufribigusguNulEs" eSuperTypes="//EuDaGusGusBebeGunulauguTin //ENulaubebiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabuBiguguBubigusnulIus" eSuperTypes="//ENulaubebiLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Albebibubutor" instanceTypeName="typeBidafrigusfrigusGuGusbobolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBobefribegusBeguGusbubuFriBitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBoBegusBoBobefribiNulius" ordered="false" upperBound="-1" eType="//EgusGusnulaubibegufribobocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabeBugugudadaBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babuGusBoBubuBiBetor" ordered="false" eType="//FafribigusdaBubunulAuNulAubocio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBibegusbeGusbubuBotus" eType="//Aubobunulaubilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdaBiBigusbenulAuFributus" abstract="true" eSuperTypes="//BabeBugugudadaBilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafribogusbefrigudaGusgusbuLius" upperBound="-1" eType="//DuboFribigusgusnulAudabiDadafridator" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagubofriboBeBedanulauBiGusius" ordered="false" eType="//DibodabibubeBibiguGuBuguBulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaFridaBigusfrifrifribogutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlFriboDanulauGuGubuFritin" instanceTypeName="typeFafrinulaudabugusdaBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBibofriguBubuLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbeGusEs" eType="//FagusbifrinulAubonulaubiboBulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euGusbinulAufributor" eType="//Abenulaufrigusnulaulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaDabogusbeguBogutus" instanceTypeName="typeDiDaFribunulaubudabibedacio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuboguBoBoGusauBuGusnulaudabonulaucus" instanceTypeName="typeDoBibibudabuFriBufributin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGubuGubibibifriGuses" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eubufrinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euNulauFriguGunulius" ordered="false" eType="//FabebunulaunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboBubiBogusnulauGuCio" eSuperTypes="//ABobobiBigusaubibeBibenulaunulauboGusEs //BraubifribufribodaGuNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EubeNulAubiBoFrigudafrinulAuFriFricus">
    <eLiterals name="DudagubidabuFribigusbifriNulAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibenulAuBibugusGuBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubuGuDaNulauBobefribefrinus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diGudacio" eType="//Abenulaufrigusnulaulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFribudabegubiEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBuGusnules" ordered="false" upperBound="-1" eType="//DiboBubiBogusnulauGuCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabunulaudabegudaguBubonulius" ordered="false" eType="//DabiboBogusbobufribuDadaguCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoLus" instanceTypeName="typeBidafridaNulaubilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusBobuDanules" eSuperTypes="//BibedaBonulauFrigusIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFribegusbigusnulaubetus" ordered="false" eType="//AnAubobeBoBeDadaDagubonulAubulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGuBegusnulaudabuGusdaBucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibeBegugusboBebiboBigucio" eSuperTypes="//BeGunulaubigudanulauGutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGuboBodabiGubolus" eSuperTypes="//BebefriDabubogusgudanulaugubilius //BeDaguGuGusnules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulauGusaudanulAuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABuDaguGunulauFribibeEs" eSuperTypes="//FabebunulaunulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusdabogusgusDabidatus" instanceTypeName="typeEbobobifrifrigufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaguGusbidabodagusgustus" abstract="true" eSuperTypes="//AgusBobuDanules //DigusNulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobodabibifriDadagubetin" eType="//Aubobunulaubilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBobibobuDadadaBogusnus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EdanulaubebigububigusBebobedalus" instanceTypeName="typeAdaguDaBeguBebobubogusnulaubetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAuguboDagusaugusgubenulautor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dadaguGugusfrilius" eType="//EubeNulAubiBoFrigudafrinulAuFriFricus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babefrigusBuboGusbedator" ordered="false" upperBound="-1" eType="//BibeBegugusboBebiboBigucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibibufribuBogusbuDaBofricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifridaguBuNulAuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadabobiboguBofriTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudaGusgusfribidabonus" eSuperTypes="//BebibogusbeboGudabitus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euBeboBefrigusCus" eType="//EubeNulAubiBoFrigudafrinulAuFriFricus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulAububebues" ordered="false" upperBound="-1" eType="//EBobibobuDadadaBogusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGufriBofribefrifrinulius" eSuperTypes="//AnbibibeBoGusfriguboGudabebunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begubebibegucus" ordered="false" eType="//BebefriDabubogusgudanulaugubilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biDaNulauBuFricio" ordered="false" upperBound="-1" eType="//DibiBibubenulAuNulAubocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaguBogudaguBodanulAuTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbuGusBebeNulaugubububogudaFridaes" ordered="false" eType="//BrauDagubufribenulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubebugunulaubuGusAucio" eSuperTypes="//EBobibobuDadadaBogusnus //ABobeDabufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubenulaubedaNulAugusBiDalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBedaBibidaDabiboguNulauboBinus" upperBound="-1" eType="//DuNulaubigugusdadacio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibegusbudagusGusBebigusaufritus" ordered="false" upperBound="-1" eType="//BraudagugusaubeFrigusBibuboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlAufribufribuguguguguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGubobebubogunulAubifricio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugugusgulius" ordered="false" upperBound="-1" eType="//DofribogusBoNulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriBifriGugufriGusNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebeBofribegusfrinulaudaGuguTor" ordered="false" eType="//EuDaGusGusBebeGunulauguTin" eOpposite="//EuDaGusGusBebeGunulauguTin/aunulaugusgusdabubufrifritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulaudaGusgusbibiboBoboFriGuslus" eSuperTypes="//EBibofriguBubuLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faFribeFriBoguGusTin" eType="//DuFribugusBeDagufriFribeBuNulauGusCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubudagusgusgunulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braufridabobugulius" eType="//DanulauDabunulAubeFrilus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubuFribigubuDabetus" eType="//DuboguBoBoGusauBuGusnulaudabonulaucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlfriFriFrigusNus" instanceTypeName="typeFabubebigusbubegubuGusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubigusnulAufritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboBonulaufriguboTus" eSuperTypes="//AnGusnulaugustus //BeGunulaubigudanulauGutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auCio" eType="//BiFrifriBenulAufribufriGuEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubufriFriFriGusbeNulaubeFridaNulEs" instanceTypeName="typeDobigubiDagutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBiFrigufridabetor" eSuperTypes="//DuFriBifriGugufriGusNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguBugubenulaudafriDabebuTor" ordered="false" upperBound="-1" eType="//DiboBubiBogusnulauGuCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebiFridabegusbebebeBenulAutus" ordered="false" upperBound="-1" eType="//Dagubugusdabigusgusnulaunus"/>
  </eClassifiers>
</ecore:EPackage>
