<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dunulaubutor" nsURI="http://hub.de/rcore/examples/dunulaubutor" nsPrefix="Ki">
  <eClassifiers xsi:type="ecore:EClass" name="EuBiFriNulauDagusdacus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EFribubenulauBibubobogunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulAubeFribebeBegusguFrinus" eSuperTypes="//EuBiFriNulauDagusdacus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AboBoBubocus">
    <eLiterals name="BraudabegufriGusBobinulaunulEs"/>
    <eLiterals name="AnfriFriBibies"/>
    <eLiterals name="AlfribigusDaes"/>
    <eLiterals name="AGuBoBenulauguBunulaunulAuLius"/>
    <eLiterals name="BigubuGunulAuBocus"/>
    <eLiterals name="EufrifribiGuFriFriboboBelus"/>
    <eLiterals name="FaguGuFriBibeguguFriNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagubebufribubonulEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibebuBububuDaFriCio" ordered="false" upperBound="-1" eType="//BiNulAubeFribebeBegusguFrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BabuBebobebicus">
    <eLiterals name="DobeGubidadabubiGuBugustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGuBegusbigunules" eSuperTypes="//BiNulAubeFribebeBegusguFrinus //BagubebufribubonulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobuguDabeDanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albibeBoNulius" ordered="false" upperBound="-1" eType="//DabidabofribebonulAuLus" eOpposite="//DabidabofribebonulAuLus/eubibifrigugusauGuBicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FabinulaunulAuNulaunulAubies">
    <eLiterals name="DagusbobubidaguguBuDaTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulauGusfribuTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaFriguGufribies" instanceTypeName="typeAFriBuboGusbeBigusBogucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Albibudabigusaulus" eSuperTypes="//BiNulAubeFribebeBegusguFrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufribonulaubefribibees" ordered="false" eType="//BeGuBegusbigunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubegusGusbutin" eSuperTypes="//Albibudabigusaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauFrigusAugusfriFriBinulAuNus" eSuperTypes="//DobuguDabeDanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabubuguboboBocio" upperBound="-1" eType="//Ebobonulaububegusbigutin" eOpposite="//Ebobonulaububegusbigutin/bibefriBogusBofrigues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubogubidagusFridaguboDaTus" instanceTypeName="typeBebebiBobefriBoFridabebues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauBidafribucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DodabuboDaNulAuTin" instanceTypeName="typeDadaGubufribodabufribulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboGugubefribibodagugufrinus" abstract="true" eSuperTypes="//EuBiFriNulauDagusdacus //DunulauGusfribuTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubenulaufriGusbuLius" eType="//EubogubidagusFridaguboDaTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EuNulEs">
    <eLiterals name="DafribufribedadaDaButor"/>
    <eLiterals name="BeNulaubidaBoBiBenulautin"/>
    <eLiterals name="BaBugusnulEs"/>
    <eLiterals name="AuDaGusius"/>
    <eLiterals name="DogusnulaubidaGusius"/>
    <eLiterals name="DudaBububebofritin"/>
    <eLiterals name="AubedabeBegusfriDaDaBunules"/>
    <eLiterals name="DinulaububobubegunulAutor"/>
    <eLiterals name="EubegusDaNulautor"/>
    <eLiterals name="DudaDaBogusbiButor"/>
    <eLiterals name="FanulauNulAubigugusbuNulius"/>
    <eLiterals name="FagugusbudabofribeBoguLus"/>
    <eLiterals name="FabuBubobeFriBegubugubecio"/>
    <eLiterals name="BefriFrifriBibees"/>
    <eLiterals name="EugusBobidabubecus"/>
    <eLiterals name="DonulaubufrigunulaugusNulauGusbiDaBobuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebobonulaububegusbigutin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibefriBogusBofrigues" ordered="false" eType="//EunulauFrigusAugusfriFriBinulAuNus" eOpposite="//EunulauFrigusAugusfriFriBinulAuNus/dabubuguboboBocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGusaufribigunules" eSuperTypes="//BeGuBegusbigunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albebunulAuBeDaNulauBidaNus" ordered="false" eType="//EunulauFrigusAugusfriFriBinulAuNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobubibebotus" ordered="false" upperBound="-1" eType="//DaFrifribeNulius" eOpposite="//DaFrifribeNulius/brAubifridagutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulauBiGugusnulaufribebegubifriNulAutor" abstract="true" eSuperTypes="//EubegusGusbutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAugusfribufridabobocus" ordered="false" upperBound="-1" eType="//EubegusGusbutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuboGuboBiBeBigunulautus">
    <eLiterals name="AugubiFrigusbiBibiDagunulAugusguEs"/>
    <eLiterals name="DiFrifriBoBobeBeGusAudagusBebuNulAubeTin"/>
    <eLiterals name="AlBuBiBigunus"/>
    <eLiterals name="FafriGuBibibubuCio"/>
    <eLiterals name="BrauFribegusboGusaulus"/>
    <eLiterals name="BefriBubedaBuFribubigusbeGubeBues"/>
    <eLiterals name="BinulAuBebegusgusbeFrinus"/>
    <eLiterals name="BibuGusFrigusAuLus"/>
    <eLiterals name="DobofribudadaGubifriBunulaucio"/>
    <eLiterals name="Alnulaulus"/>
    <eLiterals name="AubodanulaunulaubudafrigufriBiNus"/>
    <eLiterals name="DaFribobebebuBugusbodafrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubiNulauguNulAuguCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugugubegusgusfribibefrinulauBenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBubibunulauNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDaFriBodadabiBoNulaufrinulius" eType="//BiNulAubeFribebeBegusguFrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribifriBefribuFrigues" eSuperTypes="//Ebobonulaububegusbigutin //EunulauFrigusAugusfriFriBinulAuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubeBoFrigubotor" eSuperTypes="//BagubebufribubonulEs //AlfribifriBefribuFrigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBeBoFridabitin" abstract="true" eSuperTypes="//AunulauBiGugusnulaufribebegubifriNulAutor //BrAugugubegusgusfribibefrinulauBenules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebegusBeBiFriTus" ordered="false" upperBound="-1" eType="//BagubebufribubonulEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulAugubeBobiBoBobocio" upperBound="-1" eType="//DobuguDabeDanus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anGubebubegufrinus" eType="//EubogubidagusFridaguboDaTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbobiBefriFriBunulIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaGusgubifriNulaubefribogusAulus" instanceTypeName="typeFadabeNulAudabidaboGucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusbegusfribonulauGusguscus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBubugusbifritus" eType="//AuboGuboBiBeBigunulautus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBugusgudagusbuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobebiDabubibodabiguguBunules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eububogufribedabogusbogubutor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaFrifribeNulius" eSuperTypes="//EubegusGusbutin //DobebiDabubibodabiguguBunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubifridagutor" ordered="false" eType="//AGusaufribigunules" eOpposite="//AGusaufribigunules/dobubibebotus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubobiguNulius" ordered="false" eType="//EuBiFriNulauDagusdacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigubibiBugunulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doNulauDaGusBoGusBilus" eType="//AboBoBubocus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifrigusBeboboFries" eSuperTypes="//AubeBoFrigubotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babebefribobees" eSuperTypes="//Eububogufribedabogusbogubutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Braugudacio" instanceTypeName="typeBrauBubuBoDaBoNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoGuGunulAuDabunulIus" instanceTypeName="typeAu"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FabobonulauGubodabuNulAubibunulAubidabenus">
    <eLiterals name="Eu"/>
    <eLiterals name="DibebobigusGuFrinulauGusBiBuDalus"/>
    <eLiterals name="AnbobodaGusnulAubibebigusnulAuFribidaLus"/>
    <eLiterals name="BiFribiBunulaunulAufribunulaugudaEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AugugusaugusbofriNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuguGubebibudagububogulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadanulAudaFrigunulAubodacus" ordered="false" eType="//DaFrifribeNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadabedaBoDaBidafribigugusgulius" eSuperTypes="//DuguGubebibudagububogulius //Ebobonulaububegusbigutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAugufriguTor" eType="//BaFriguGufribies" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibubuNulaubofribegusbeguNulauGuscio" ordered="false" eType="//DifridaguboGubebuEs" eOpposite="//DifridaguboGubebuEs/dobeFrinulaufriBobuDatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabuFribiBiDabeNulAuguGues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibonulaudagusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBubeBuNulaulius" ordered="false" upperBound="-1" eType="//AGusaufribigunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuDagugusbobedaBibeNulAubeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobeBuBebibifrifriboNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFrifribigugubobeboBoguFriNulauLus" upperBound="-1" eType="//BigubibiBugunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulAufriBeTor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EboDaDaBuBoBibubitor">
    <eLiterals name="AnboBifriCio"/>
    <eLiterals name="AnFriBiBofribolus"/>
    <eLiterals name="ENulauGunulaunulaubogusaufriFrilius"/>
    <eLiterals name="FaBenulAudaBiGuscus"/>
    <eLiterals name="FaNulauGusNulaufricio"/>
    <eLiterals name="BadadaboGufriCus"/>
    <eLiterals name="BagusnulauguFrigues"/>
    <eLiterals name="Egutin"/>
    <eLiterals name="AldaGusFriBedaBuGuFribugusAugusNulEs"/>
    <eLiterals name="AnbobibubuFriBunulauCus"/>
    <eLiterals name="BiBibuGuDabudafribedalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BiNulaucio" instanceTypeName="typeAugusdaboboGubinulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusBoGusgusAuboBibonulAunulauLius" eSuperTypes="//BiBubibunulauNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abiGusbubonulauBobedabues" eType="//DoGuGunulAuDabunulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusGusbubeBofrinules" eSuperTypes="//AlfribifriBefribuFrigues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AgusGusBuboGusNulaulus" instanceTypeName="typeDaBigusbebebefrifribubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabidabofribebonulAuLus" eSuperTypes="//AlfribifriBefribuFrigues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubibifrigugusauGuBicus" ordered="false" eType="//DobuguDabeDanus" eOpposite="//DobuguDabeDanus/albibeBoNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafribobodabedabeNulaucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulauBubinulauFritus" eType="//AgusGusBuboGusNulaulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBoBoGusbogusgugunulEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doBigusGubifrinus" eType="//FaGusgubifriNulaubefribogusAulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebidaDaDaGububilus" upperBound="-1" eType="//DoGuGunulAuDabunulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusGuGusbeBuDanulAufribogunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aguNulaubeGubiGusauCus" ordered="false" upperBound="-1" eType="//DabidabofribebonulAuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusBedafribiBegusbifritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogubobuGusbuguGusboDabiDabugubudaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBufrigubebudaBegububelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifridaguboGubebuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beDanulaugusbunulauBuguguguCio" ordered="false" upperBound="-1" eType="//DafribobodabedabeNulaucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobeFrinulaufriBobuDatus" ordered="false" upperBound="-1" eType="//FadabedaBoDaBidafribigugusgulius" eOpposite="//FadabedaBoDaBidafribigugusgulius/dibubuNulaubofribegusbeguNulauGuscio"/>
  </eClassifiers>
</ecore:EPackage>
