<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adabegues" nsURI="http://hub.de/rcore/examples/adabegues" nsPrefix="H">
  <eClassifiers xsi:type="ecore:EClass" name="FabedaboBedafribigusdaTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EubeGusfriFrifribefribudaboLus">
    <eLiterals name="EubiBeBiGusbolius"/>
    <eLiterals name="Bebebobugusnus"/>
    <eLiterals name="EbiBebedadaGusgufrigustor"/>
    <eLiterals name="DofrigusGusbuBodagusNules"/>
    <eLiterals name="BidaboNulauBiBenus"/>
    <eLiterals name="BagudadanulaugusboGusIus"/>
    <eLiterals name="AnboGufriDabiguBoguNus"/>
    <eLiterals name="ADadanulaugubuBeBoCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDaGusbigusgusgusbuGusDanulauboGusbulus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbenulaugubufriBotin" eSuperTypes="//EDaGusbigusgusgusbuGusDanulauboGusbulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBiguBodaBebebeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABefriBidaguBuBuBeTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBobugusGufriGuGusTus" ordered="false" upperBound="-1" eType="//AbenulaugubufriBotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edafrifribibobofridafritus" eSuperTypes="//BeBiguBodaBebebeTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eufriBebonulAugunulIus" eType="//EubeGusfriFrifribefribudaboLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGuBogusfribiDaFrilius" ordered="false" eType="//Aldagunulaubilius" eOpposite="//Aldagunulaubilius/efriboGusBelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiDaNulaunulauGusdanus" eSuperTypes="//ABefriBidaguBuBuBeTor //BeBiguBodaBebebeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbifribufrigusNulAuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobebeGusgubodadaCus" ordered="false" eType="//BeBiguBodaBebebeTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabubenulAubeDabeBulus" eSuperTypes="//BiDaNulaunulauGusdanus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BifriBegusGusnulauNulAunulAuNus" instanceTypeName="typeBeBogusdabufrifrigusgusFribiDatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobugusDator" eSuperTypes="//EDaGusbigusgusgusbuGusDanulauboGusbulus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FaBigunulAubogusbodabigugubitus">
    <eLiterals name="BibiFrinulaudaFriBiGusBucio"/>
    <eLiterals name="AboboGuBoBeDabinus"/>
    <eLiterals name="AnaufrifriBunulauButus"/>
    <eLiterals name="FanulaunulAubiBoGubinulAuTus"/>
    <eLiterals name="DugusnulauDabuFribinulAutor"/>
    <eLiterals name="EuBoguboBebogunulauLus"/>
    <eLiterals name="BidagufriFribiGucio"/>
    <eLiterals name="DunulauGubegubugusdacio"/>
    <eLiterals name="DagusdaBoGusnulaubedabiNulius"/>
    <eLiterals name="BigusboboguGubuDabubifridatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Bafridadafritin" instanceTypeName="typeFabeguBigusfrinulaufriBolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnDabiFrigusbibeBudabonulius" eSuperTypes="//AbenulaugubufriBotin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dagunulaubegusfribinulaugucio" instanceTypeName="typeAlgusgusbeBoGusAuBubigutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnGusgugusGusfrigusguBoes" instanceTypeName="typeFabibuNulaudabodabugusBues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBenulaudaBibedatus" instanceTypeName="typeBabuGudafritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aldagunulaubilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efriboGusBelus" ordered="false" eType="//Edafrifribibobofridafritus" eOpposite="//Edafrifribibobofridafritus/biGuBogusfribiDaFrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibibeTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBibebufriFrinus" ordered="false" eType="//AnDabiFrigusbibeBudabonulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBeGusguNulAubeBoCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubofriboBibonulAugusius" eType="//EDaGusbigusgusgusbuGusDanulauboGusbulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiDaGuBebeBidaLus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BigubiBubibobudabugusEs">
    <eLiterals name="EnulaubiBibubucio"/>
    <eLiterals name="DagusgusfriboDaNulAugusgusnulaudanulius"/>
    <eLiterals name="DogugusDanulauBiDaDafricio"/>
    <eLiterals name="EuboguGusDaBebelius"/>
    <eLiterals name="DobefridagusnulEs"/>
    <eLiterals name="EubidanulaugubufriGues"/>
    <eLiterals name="DoboGugunulaubeBugusdabefriFrinulius"/>
    <eLiterals name="AlgusBogusbiBoDabobiBegunulauFries"/>
    <eLiterals name="AububibodagubebuguFrigubonus"/>
    <eLiterals name="DaBegusBogusGuGunulAudabuNules"/>
    <eLiterals name="EuboboNulaubibogusGuBibubufrifrinus"/>
    <eLiterals name="BebidaBuNulAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFribidabebiboBugusauGusAuguguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobiNulAuNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BigubidaguNulaubeLus" instanceTypeName="typeBinulAubiGusbiguNulaugubebues"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABebebogunulaudagusNulauGusAuFriTin" eSuperTypes="//EFribidabebiboBugusauGusAuguguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bifrigubufritin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAuboDagusGusBiboGubobibutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGubunulauBibugugugusdabegusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biFriFrifribebuBiNulaulus" ordered="false" upperBound="-1" eType="//AnDabiFrigusbibeBudabonulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubifries" ordered="false" upperBound="-1" eType="//BiDaGuBebeBidaLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGuDaGusguBodagubibucus" ordered="false" upperBound="-1" eType="//DiBeGusguNulAubeBoCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusdabodaBoNulaubeBegusfrigugusCus" eType="//BanulAuboDagusGusBiboGubobibutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauDaNulautin" abstract="true" eSuperTypes="//ABefriBidaguBuBuBeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudabuGuBeboDaGusnulaubugubifriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiFriFribogusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBiguBubifribilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusbugunulauGusTor" ordered="false" upperBound="-1" eType="//BanulauDaNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusGusdagubonulaubibitus" eSuperTypes="//FabedaboBedafribigusdaTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doFrifriGudagusBibodaboGuscus" ordered="false" eType="//AnDabiFrigusbibeBudabonulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufribebebobiNulaubotor" ordered="false" eType="//DoGusgusnulaubobubuNus" eOpposite="//DoGusgusnulaubobubuNus/diBibuNulaudabebebitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuboboBubugusFribeNulAuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfriNulauBigusgusaugusbolus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anaugusgusGuguBetor" upperBound="-1" eType="//FaBigunulAubogusbodabigugubitus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnNulaufriFribidanulaubuLus" eSuperTypes="//AbenulaugubufriBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dabodabegunulaufricus" eSuperTypes="//Aldagunulaubilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baboes" eType="//AnGusgugusGusfrigusguBoes" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBuboFribodabuguscio" eSuperTypes="//BeBiguBodaBebebeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusgusnulaubobubuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBibuNulaudabebebitor" ordered="false" eType="//FagusGusdagubonulaubibitus" eOpposite="//FagusGusdagubonulaubibitus/aufribebebobiNulaubotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiguguguGububeBoBoGusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeguNulaunulaubifriDafritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBuNulauBigubitus" ordered="false" upperBound="-1" eType="//DobugusDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulaufrinulaudaguBenus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoDaFribegugudabotor" eSuperTypes="//AlbifribufrigusNulAuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBenulauDanulauguBeguGusnus" eSuperTypes="//Aldagunulaubilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBoBudabifridabuDagubuNules" ordered="false" upperBound="-1" eType="//AnbiguguguGububeBoBoGusTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugubobibubebeBogusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusnulEs"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbibiBogusnulauboBogusCio">
    <eLiterals name="BinulauBigubeguGubiFrinulAunulEs"/>
    <eLiterals name="DibeBiboGuboGugudator"/>
    <eLiterals name="AbobifrifriBibebiFriBeLus"/>
    <eLiterals name="AnBeguBiboguBigunulAulus"/>
    <eLiterals name="FabuNulauguTin"/>
    <eLiterals name="DuBeGusdafriGubeGusnulius"/>
    <eLiterals name="EuguNulAudagusbuFritus"/>
    <eLiterals name="EubeFrigubedadabiDaBufriGutin"/>
    <eLiterals name="BrAugunulaugusbugubutor"/>
    <eLiterals name="DiBuBibegulius"/>
    <eLiterals name="BaBubiGusBuboDaFrigufribeCus"/>
    <eLiterals name="AlGusnus"/>
    <eLiterals name="BigugusbogusbibebeNulAutor"/>
    <eLiterals name="DiDaguscus"/>
    <eLiterals name="EbeboBetus"/>
    <eLiterals name="DubinulauBogusauBibibigudaBinulaucio"/>
    <eLiterals name="AuGudaBobees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DuboNulAuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBebedabufrinulAudaCus" abstract="true" eSuperTypes="//DobiNulAuNules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FanulauBoGuDagubodaTin">
    <eLiterals name="AgudabogusFricus"/>
    <eLiterals name="AugusdaDabiboFriDaBufrinulAubuBoes"/>
    <eLiterals name="DufribubobibuBelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboguboBiBegusbunulaulus"/>
</ecore:EPackage>
