<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algusbogunules" nsURI="http://hub.de/rcore/examples/algusbogunules" nsPrefix="DKV">
  <eClassifiers xsi:type="ecore:EClass" name="DofrifriBeGufribiGusgusboBobebolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBuDanulauBoBeBigusbodaBees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadabibofridabebidator" ordered="false" upperBound="-1" eType="//DofrifriBeGufribiGusgusboBobebolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusbubinulauDafriguslius" ordered="false" eType="//DobiFribogusgusgusBoDaguguscio" eOpposite="//DobiFribogusgusgusBoDaguguscio/faNulAuboBuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusDaDabebebebues"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubegusgugusgufribeBibogulius" eSuperTypes="//FaBuDanulauBoBeBigusbodaBees //DofrifriBeGufribiGusgusboBobebolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulAubebiDagububeBuBefritor" ordered="false" upperBound="-1" eType="//DofrifriBeGufribiGusgusboBobebolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaubiDagusaubigunulius" ordered="false" upperBound="-1" eType="//ABubobiNulaunus" eOpposite="//ABubobiNulaunus/fagusnulauBidanulAufribudatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnauFrigusBuGubuBogusAubeguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgudanulauguBogufriguboFribogugunus" eSuperTypes="//DofrifriBeGufribiGusgusboBobebolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigubibuboBobibunulauBiTin" eSuperTypes="//EubegusgugusgufribeBibogulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadagusbubeboDacus" ordered="false" upperBound="-1" eType="//AnauFrigusBuGubuBogusAubeguslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EuBuguFriBelius">
    <eLiterals name="Dinulaugusaucus"/>
    <eLiterals name="DugubuBefridabeFribubinulius"/>
    <eLiterals name="BrauFriBeboBigusFridaBudanulauBebeBubetin"/>
    <eLiterals name="BegusdaBibeguGuboBiBoes"/>
    <eLiterals name="AnbuGufriGuBiboGusAugusbubiCio"/>
    <eLiterals name="DofribunulaugudabigusbudafriLius"/>
    <eLiterals name="BegusfrigugubibunulauBuBoFrifribogusnus"/>
    <eLiterals name="AlbiBiNulaugustor"/>
    <eLiterals name="AugubugusbugusBoBifritor"/>
    <eLiterals name="AudaBeBeTus"/>
    <eLiterals name="DudadaBiGudatin"/>
    <eLiterals name="Bibubinus"/>
    <eLiterals name="BeNulaubogubenulaulius"/>
    <eLiterals name="AbuTus"/>
    <eLiterals name="DigufribuboGubobulius"/>
    <eLiterals name="DobegubeDadaBebeGusgunulEs"/>
    <eLiterals name="DanulAuBifriBifribebobifribies"/>
    <eLiterals name="AlNulAuboguscio"/>
    <eLiterals name="FagusdabeBecus"/>
    <eLiterals name="Eubidadafrinulius"/>
    <eLiterals name="BabiDaGusbebeTor"/>
    <eLiterals name="AufrigusbufribebobofriLius"/>
    <eLiterals name="BibedabefriboFrifriboBobicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubiBugusNulAububuTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiboboGusgusGubebegusTor" ordered="false" eType="//EgubeBuGusnulautor" eOpposite="//EgubeBuGusnulautor/bibogudaNulAufrigusbelus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="andaGusfridagusguboGutor" ordered="false" upperBound="-1" eType="//EgubeBuGusnulautor" eOpposite="//EgubeBuGusnulautor/anfribidagudanulAubiNulauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABubobiNulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusnulauBidanulAufribudatus" ordered="false" eType="//EubegusgugusgufribeBibogulius" eOpposite="//EubegusgugusgufribeBibogulius/anaubiDagusaubigunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlNulAubiFrinulauboDabecus" instanceTypeName="typeAlgusguBedabigulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobiFribogusgusgusBoDaguguscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faNulAuboBuEs" ordered="false" upperBound="-1" eType="//FaBuDanulauBoBeBigusbodaBees" eOpposite="//FaBuDanulauBoBeBigusbodaBees/egusbubinulauDafriguslius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBobegusbogusGusbefribonus" ordered="false" eType="//FaBuDanulauBoBeBigusbodaBees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DofribufridabebedadabubeTor" instanceTypeName="typeEudadabebuNulauBibufrigufriGusbees"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgubeBuGusnulautor" eSuperTypes="//EgudanulauguBogufriguboFribogugunus //EubiBugusNulAububuTor //DobiFribogusgusgusBoDaguguscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibogudaNulAufrigusbelus" eType="//EubiBugusNulAububuTor" eOpposite="//EubiBugusNulAububuTor/fabiboboGusgusGubebegusTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribidagudanulAubiNulauNus" ordered="false" upperBound="-1" eType="//EubiBugusNulAububuTor" eOpposite="//EubiBugusNulAububuTor/andaGusfridagusguboGutor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babibibedanulaugucus" eType="//DofribufridabebedadabubeTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bifribufriBiLius" eType="//DofribufridabebedadabubeTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGugusdaGusdaBedabeBegutus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baBubiboboNus" eType="//EuBuguFriBelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBoGudaNulAucus" instanceTypeName="typeAFribugusauBoLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbuBoDanulaubebobutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binulaunulauBobugusLius" eType="//AlNulAubiFrinulauboDabecus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagubebogusnulaugusbuCus" abstract="true" eSuperTypes="//BiGusDaDabebebebues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aFribobenulAubobubigusius" eType="//DiBoGudaNulAucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusDabefrigubicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eDagusLus" ordered="false" eType="//ABubobiNulaunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difriDabedadaBibubeguscus" upperBound="-1" eType="//EubiBugusNulAububuTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGubefridadabegusbubuBodaNus" ordered="false" eType="//ABubobiNulaunus"/>
  </eClassifiers>
</ecore:EPackage>
