<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="e" nsURI="http://hub.de/rcore/examples/e" nsPrefix="KR">
  <eClassifiers xsi:type="ecore:EClass" name="AnGusbobofriBebodanulaubedaTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiDabonulauguBonulIus" abstract="true" eSuperTypes="//AnGusbobofriBebodanulaubedaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGufriBubobibibubeDanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbudaguguNulauLus" eSuperTypes="//AnGusbobofriBebodanulaubedaTus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiGusfribuBobonulauFrigusbudaNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DifribifriBebidanulaufridaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeDabebeguboFriNulaubonulaugusaubotor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albudaFrigusbues" ordered="false" eType="//AlbudaguguNulauLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbenulauboNulauguslius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuboDagubuBuNulaudaBobidaBobocio" instanceTypeName="typeAnbububobiBibubebuGuLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabibiboGusdafrigusbiGugusguslius" instanceTypeName="typeDanulAububinulaugusbibedalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidaBobibubiBoboboBodaes" eSuperTypes="//DiDabonulauguBonulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doboBubudagusfrilus" ordered="false" upperBound="-1" eType="//BeDabebeguboFriNulaubonulaugusaubotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DafridadabubuBonulauGubeDaTus">
    <eLiterals name="BibibofriboboBobeEs"/>
    <eLiterals name="DobenulauBoBiFrigusfriGusfribotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusgubegusbenulAulius" eSuperTypes="//AlbudaguguNulauLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuNulaufriBofriCus" instanceTypeName="typeAnGubibubiBebeDagusfriFrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuGufribeNulauBeboGusNulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusBubegusButor" ordered="false" upperBound="-1" eType="//AlgusgubegusbenulAulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnauBiBeBebobucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufribubogusdaFriGusboTin" abstract="true" eSuperTypes="//BeDabebeguboFriNulaubonulaugusaubotor //AlbudaguguNulauLus //AlgusgubegusbenulAulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egubodaNulaubiLus" eType="//EuNulaufriBofriCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiguguBenules" eSuperTypes="//AlbudaguguNulauLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauNulAunulAuguslus" ordered="false" eType="//DidaBobibubiBoboboBodaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigubugunulaugubeGuscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGuBibiBiguboes" eSuperTypes="//BeDabebeguboFriNulaubonulaugusaubotor //DufribubogusdaFriGusboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifriBuNulaugusgusbelus" eSuperTypes="//AnbuGufribeNulauBeboGusNulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alnulaugusAunulaubiNulEs" eType="//DifribifriBebidanulaufridaTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Benulaubifrinus" instanceTypeName="typeAfribebibegubebigustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusboGuBugustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboBunulaugucio" ordered="false" eType="//DuGufriBubobibibubeDanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBoFribodaFrigusfribofribotor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaguFribubues">
    <eLiterals name="Dabutor"/>
    <eLiterals name="DabiGusboguBenulAucio"/>
    <eLiterals name="DobeBonulauBefriGuscio"/>
    <eLiterals name="Dagusgubogubufribicio"/>
    <eLiterals name="AufribobiguBeguTus"/>
    <eLiterals name="FaFribebebiBuBegugubobues"/>
    <eLiterals name="DugusNulAunulAubeNulaufricus"/>
    <eLiterals name="BrAunulauBubebies"/>
    <eLiterals name="AGuboNulauBoBegustor"/>
    <eLiterals name="DaBobuBibeFrigusbidaGuBidacus"/>
    <eLiterals name="FaNulauFriDabogudatin"/>
    <eLiterals name="DiNulaunulAubegusAudafrigudabenulauCus"/>
    <eLiterals name="FanulAuNulaunules"/>
    <eLiterals name="DaDafribuBegubeBibebogusTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANulaudaBobunulaubuBolus" eSuperTypes="//DidaBobibubiBoboboBodaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubefriBoBogusbugusdatin" abstract="true" eSuperTypes="//DuGufriBubobibibubeDanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euNulaugusguBubogusbeBogubuFribiNulAulus" ordered="false" eType="//AnauBiBeBebobucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebiFribebebeguCio" eType="//BabibiboGusdafrigusbiGugusguslius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifribuFriBobiboBiNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusDabiDabebuBigutin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edadadagusGustin" upperBound="-1" eType="//BaguFribubues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafriGuBefrinulauLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobudadabudabufrigusTor" abstract="true" eSuperTypes="//AnbuGufribeNulauBeboGusNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBeguBidaGustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alAudagubugusDalius" ordered="false" upperBound="-1" eType="//DubefriBoBogusbugusdatin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beguGusBubegusfribebues" eType="//DafridadabubuBonulauGubeDaTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBibugugusNulaudagusBoEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adabeBobibutor" ordered="false" eType="//ANulaudaBobunulaubuBolus"/>
  </eClassifiers>
</ecore:EPackage>
