<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aubobucio" nsURI="http://hub.de/rcore/examples/aubobucio" nsPrefix="qTZM">
  <eClassifiers xsi:type="ecore:EDataType" name="ABidabeBeNulaubudaboNulaudaFries" instanceTypeName="typeDufriBibonulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiBobubogugubudanulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusfrifrifrifrifrinulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBibugusbobelius" ordered="false" eType="//AlbiBobubogugubudanulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoguGusFriBoDabugubiBibibecus" instanceTypeName="typeBadafribenulaugusfrifrigusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusbinulaudanulAuBegusGunulauBucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euguBegubogubeDabinus" ordered="false" eType="//AugusfrifrifrifrifrinulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Bibubigugusbegustin">
    <eLiterals name="BabobunulaubuLus"/>
    <eLiterals name="EbeNulauNulAubodaBiBudaGuslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebufribebiguDanulAuButus" eSuperTypes="//AlbiBobubogugubudanulius"/>
</ecore:EPackage>
