<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albebubebinus" nsURI="http://hub.de/rcore/examples/albebubebinus" nsPrefix="Zx">
  <eClassifiers xsi:type="ecore:EEnum" name="Fagusgusgunulaudagugunus">
    <eLiterals name="AnfribegusnulauGusbolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBoNulaubinulAuboBubebinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aldaBegubibidaBibuboboguNus" eType="//Fagusgusgunulaudagugunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbebigusBoBubobigusgues" eSuperTypes="//DiBoNulaubinulAuboBubebinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidabiDaBofribuBogusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbenulauBegufribogubiGusnulius" abstract="true" eSuperTypes="//DidabiDaBofribuBogusius //DiBoNulaubinulAuboBubebinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDaBibigunulaubeDabeNus" ordered="false" upperBound="-1" eType="//DidabiDaBofribuBogusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnFriboGufriBonulauCio" eSuperTypes="//DidabiDaBofribuBogusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulaufriDagusaudagubifrifriBigusgucus" ordered="false" upperBound="-1" eType="//DiBoNulaubinulAuboBubebinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeBufribebies" eSuperTypes="//AlbebigusBoBubobigusgues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuFrifriBonulauGubigusfriGusbetin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusAubegusfriGusgusBegugulius" eSuperTypes="//AlbebigusBoBubobigusgues"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuBubebiNulAufriBebinulAugusbinulAutus">
    <eLiterals name="DogusFribugunulauFrigusbolus"/>
    <eLiterals name="AnaubebeGusfriBefribinus"/>
    <eLiterals name="BefriBoboBibufrifrinulius"/>
    <eLiterals name="AnauDanulaubobiBubuCus"/>
    <eLiterals name="BanulAuFribibibibobenus"/>
    <eLiterals name="BraunulAudafrigusgudaboFries"/>
    <eLiterals name="BiBiguDaNulauboBuguBitin"/>
    <eLiterals name="Do"/>
    <eLiterals name="BrAuboDabibubuFribinulauboEs"/>
    <eLiterals name="DanulaubiBibubonulAubobobebebilus"/>
    <eLiterals name="EgusfriguNulAudaFrifries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBububenulaubigusbuGusCus" abstract="true" eSuperTypes="//AlbenulauBegufribogubiGusnulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBiboGusbubonulautin" ordered="false" eType="//DiBoNulaubinulAuboBubebinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubefrinulAufriLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaudagusBoGugudadalius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgubebeNulAutin" instanceTypeName="typeFabudabofrinulAunulAuBifrifridagusGubiBuGusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGunulauBubibunules" eSuperTypes="//AlnulaudagusBoGugudadalius //EuBububenulaubigusbuGusCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubibibefriBegusGuBofrifriNus" eType="//AuBubebiNulAufriBebinulAugusbinulAutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudaBuBubeBubifribobuBiguNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBogufrigusfriTus" ordered="false" upperBound="-1" eType="//AlbebigusBoBubobigusgues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anfriBugusbubeBulus" eType="//AuBubebiNulAufriBebinulAugusbinulAutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBebuboBedadaBubeGusbolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGusnulauboNulauGusbiLus" ordered="false" eType="//AlbeBufribebies"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBiFrifriBuguBebeNulauboNulaucio" eType="//AuBubebiNulAufriBebinulAugusbinulAutus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibefrifriBugusdabicio" ordered="false" upperBound="-1" eType="//EgusAubegusfriGusgusBegugulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubiGusgusbuFribegusgusDator" instanceTypeName="typeEudaGusgutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoboBufriBibuGubugusDaes" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafriBenulaubofridabibigusauBocus" ordered="false" upperBound="-1" eType="//EgusAubegusfriGusgusBegugulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfrinulAubues" abstract="true" eSuperTypes="//AnFriboGufriBonulauCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBolus" eType="//Fagusgusgunulaudagugunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EboboguGudadafritus" eSuperTypes="//DidabiDaBofribuBogusius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBigusBobibobunulauDagusgubues" eType="//Fagusgusgunulaudagugunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusbufrigusbugusBeBecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifriBuboNulaubigugugustor" eSuperTypes="//AnFriboGufriBonulauCio //DoboBufriBibuGubugusDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadadaFribuNulaubicio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DunulAuBedabiguguGubebebugubeNulius">
    <eLiterals name="BrauBebetus"/>
    <eLiterals name="DubuBuNulauBugusCus"/>
    <eLiterals name="BebedabobuBoguGusCus"/>
    <eLiterals name="AfriGugusAuNulaufrifribuGubifributor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubobonulaubigusbidaButus" eSuperTypes="//EfrinulAubues //AlbenulauBegufribogubiGusnulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulaubeBuguBuDabutus" abstract="true" eSuperTypes="//AuFrifriBonulauGubigusfriGusbetin //AnFriboGufriBonulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBegufrilius" eSuperTypes="//DubobonulaubigusbidaButus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aguBibigubebidagusbuGufrigunus" eType="//AlgubebeNulAutin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubifriboDaes" eType="//Fagusgusgunulaudagugunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BagusbiFridaGusBidabebudafrinus" instanceTypeName="typeDogugudabebies"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnguDaFribububuBubolus" eSuperTypes="//DidabiDaBofribuBogusius //DoboBufriBibuGubugusDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBoBibofrifridaBuDanus" eSuperTypes="//AubefrinulAufriLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauguGusgudaGusBubeBoBefrinulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibenulAuguFriguBugubuNules" abstract="true" eSuperTypes="//FadadaFribuNulaubicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudaBotus" eSuperTypes="//AlbenulauBegufribogubiGusnulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auBibegubudaFriCio" eType="//DubiGusgusbuFribegusgusDator" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibobodaBedafriFries" eSuperTypes="//DinulauguGusgudaGusBubeBoBefrinulauNus //AnFriboGufriBonulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBuBebegusaubeBofribebutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biNulauNulaudabifribebotin" eType="//BagusbiFridaGusBidabebudafrinus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGubibidaLus" ordered="false" eType="//BifriBuboNulaubigugugustor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babobeboBibifribodagusbibubufrinulIus" ordered="false" eType="//EuBububenulaubigusbuGusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgugusdabofribuFrinulauNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBobudagubiGubugulius" ordered="false" upperBound="-1" eType="//DudaBotus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duDaBonulAufriNulAuboFrinulius" ordered="false" upperBound="-1" eType="//DinulauguGusgudaGusBubeBoBefrinulauNus"/>
  </eClassifiers>
</ecore:EPackage>
