<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anulaubees" nsURI="http://hub.de/rcore/examples/anulaubees" nsPrefix="jTT">
  <eClassifiers xsi:type="ecore:EClass" name="DudadaNulAunulauBoguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDagufrinulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegubigusgusfriGusNus" eSuperTypes="//DudadaNulAunulauBoguTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubeGues" ordered="false" eType="//DudadaNulAunulauBoguTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgububububegusGubotor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Audadabebunules" instanceTypeName="typeFabubuBegufriBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusdafriBoguGusbuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBidanulaububegusfriDalus" eSuperTypes="//AlGusdafriBoguGusbuTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annulAudaDanulaunulEs" eType="//Audadabebunules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Do" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBubebobonulAufriFrilus" eSuperTypes="//AlGusdafriBoguGusbuTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alBunulAuFriBobigustus" eType="//Audadabebunules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dogubegutus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngubobiguDagusfribebifriBigusEs" eSuperTypes="//AlGusdafriBoguGusbuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euFrigugububiGuBuBibitor" ordered="false" eType="//EgububububegusGubotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusfribigusfribiGuGusgubecus" eSuperTypes="//Dogubegutus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Audabebogusgusaubogudator">
    <eLiterals name="AudaGusbues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EubebebiGusaunulaugusdabobecus">
    <eLiterals name="AnulaudaDaDaBodabidaBofribenus"/>
    <eLiterals name="DinulauBuBunulaunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbigudaNulauBedafrifriBocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuboBoGugusgufrifribenulauGulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diNulaubuDanulAunulaubuBobigubucus" ordered="false" upperBound="-1" eType="//Dogubegutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubibebiBuDagusgusBobenulauTus" instanceTypeName="typeEbiBigusdabuBugustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobebunulius" eSuperTypes="//EuboBoGugusgufrifribenulauGulius //BrauBubebobonulAufriFrilus //Dogubegutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albebibeCus" ordered="false" upperBound="-1" eType="//Do"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusdanulauBeguGusfribulus" eSuperTypes="//AlgusfribigusfribiGuGusgubecus //AbigudaNulauBedafrifriBocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euFribudanulaunulaugugunulauFrigusTus" upperBound="-1" eType="//AngubobiguDagusfribebifriBigusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidabiboGusDadaboBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubububibeGusbodagusgusbibonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusgusbuCus" eSuperTypes="//Dobebunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriDaBiGusNulaubucus" abstract="true" eSuperTypes="//DudadaNulAunulauBoguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusboNulauboNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulaudabuBobodagutor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Dofribudadagubobogudabolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlboGubudaFrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobibuGubobegugusbiNulAucus" eSuperTypes="//BiNulaudabuBobodagutor //BiBidanulaububegusfriDalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubeDanulAugusguFrigunules" eType="//BidabiboGusDadaboBitin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aGusbiBebuDanulAuFriTus" eType="//EubebebiGusaunulaugusdabobecus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBiNulauDabogugugudaBitor" eSuperTypes="//EuboBoGugusgufrifribenulauGulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Bibidagunulaugusaugutin">
    <eLiterals name="EudaGuboBiFridadacus"/>
    <eLiterals name="AubeNulAubebofriGusbigusLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBoGusBoFribees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusaufridaBoBeLus" ordered="false" upperBound="-1" eType="//EuboBoGugusgufrifribenulauGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabifribifridabeguBuDaEs" eSuperTypes="//AlgusfribigusfribiGuGusgubecus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubiBibeboFrigusbucio" eType="//Audabebogusgusaubogudator" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugugubiButus" abstract="true" eSuperTypes="//AlGusdafriBoguGusbuTin //BiNulaudabuBobodagutor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FaFridafribucio">
    <eLiterals name="DibogusBibegusBobibeDaBunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuboGuboGuTor" instanceTypeName="typeDugububodadabenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dabonulaugusbigucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigubuDafribudanulIus" abstract="true" eSuperTypes="//BidabiboGusDadaboBitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difriGusbogunulAuGusfribobifriBecio" eType="//EubebebiGusaunulaugusdabobecus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auGugubogusBiFries" eType="//EubibebiBuDagusgusBobenulauTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabobeBebubuLius" eSuperTypes="//Dobebunulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AfribiDaDabidaGusgusgusLius" instanceTypeName="typeDibubibedaBofriBogusBoBuButor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgubunulaufriBegunulAuguBogusnulAunus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBebubegubegubufrigusIus" instanceTypeName="typeBeBenulauBuBubiFrinulauguDaBudalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubiGusbofrifribefriboNulaugusboTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baboBogubobugusgulius" upperBound="-1" eType="//DudadaNulAunulauBoguTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBubobogusBedalus" ordered="false" upperBound="-1" eType="//DudadaNulAunulauBoguTin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alBuDaGuslius" eType="//Dofribudadagubobogudabolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfrinulauTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBinulauboGusDacio" eType="//EubibebiBuDagusgusBobenulauTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuguDaboBebuFribiFribinulAuGubugubunus" instanceTypeName="typeBefriBobeBebeNulaubebenulIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBeNulaunulAuBeBeBodaguBeNulAubufritin" instanceTypeName="typeDobeguGuGusauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefribidagunulauGusfriGusEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaububinulaubuGubunulaunus" eType="//AuBiNulauDabogugugudaBitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaguGusbonulIus" eSuperTypes="//BagusdanulauBeguGusfribulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulaubeBuguBeNulauguses" ordered="false" upperBound="-1" eType="//AbigudaNulauBedafrifriBocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusGubiNulauGusgubogusNulAulius" eSuperTypes="//BaBoGusBoFribees"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibunulAugusauBubifrigusFrinulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daGusbolus" eType="//EubebebiGusaunulaugusdabobecus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabibibeBubufribonulaunulAuBuTor" eSuperTypes="//AbigudaNulauBedafrifriBocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doguboGutor" eType="//Dofribudadagubobogudabolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnaugusboGuBiBofriBuGugutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulaubidaDanulaunus" ordered="false" upperBound="-1" eType="//AngubobiguDagusfribebifriBigusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGubedabebegutus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebigubifrigusguNus" eType="//AfribiDaDabidaGusgusgusLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusBiFriBibuDaGuGuBifriboboes" abstract="true" eSuperTypes="//BrauGusboNulauboNules //DaGusgusbuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBogusbobobobibuButor" eSuperTypes="//EufriDaBiGusNulaubucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dibobobuguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaboGubigugudabigudaTin" abstract="true" eSuperTypes="//BiGusBiFriBibuDaGuGuBifriboboes //DobibuGubobegugusbiNulAucus //EufriDaBiGusNulaubucus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauguBubefrigusbudacio">
    <eLiterals name="BrAugusnulAufrifriboBuGusbofribotor"/>
    <eLiterals name="FaNulaugubedaFriFriBotor"/>
    <eLiterals name="EubidagusAuboNulaulius"/>
    <eLiterals name="BrAugusBoDabebibuBeGugusnules"/>
    <eLiterals name="BefrigusauBobigusdaGuDabotus"/>
    <eLiterals name="BegusGubegububuguFrinulaububeBocio"/>
    <eLiterals name="AnboBuguguguDadanulAugugusAubibulus"/>
    <eLiterals name="FaDagudagusgusaunulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBedaguGusbogusbebetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebogusgusdaFriNulaufrifrifrigufriGusboCio" eType="//AlgusfribigusfribiGuGusgubecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabubobeguBiBoBubobuboguDaDadalus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauGusBuBeguGuscio" eType="//EubibebiBuDagusgusBobenulauTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudadafrigusgusnulauFritus" eSuperTypes="//Do"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbubobebiBifriFriguLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfrigusFrigusboFrigusbutor" ordered="false" eType="//BidabiboGusDadaboBitin"/>
  </eClassifiers>
</ecore:EPackage>
