<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="afriguguses" nsURI="http://hub.de/rcore/examples/afriguguses" nsPrefix="oL">
  <eClassifiers xsi:type="ecore:EClass" name="BaBibodanulaububefrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusnulauguNulAubidabutin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DugusBeFriDaBeBufribeGusbenulius">
    <eLiterals name="AbeguBeGufridabigufrifrinus"/>
    <eLiterals name="AlbigubebiDanulAutus"/>
    <eLiterals name="EuGuGusfritus"/>
    <eLiterals name="AlgusBiFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlfriBofriBonulAuboEs" instanceTypeName="typeBraunulauTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobeBebubebobinulaububotin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriguFrinulaunulaubofrigusNulius" eSuperTypes="//BaBibodanulaububefrinus //EugusnulauguNulAubidabutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AguboNulaubuFribubogusnulAufries" eSuperTypes="//DuFriguFrinulaunulaubofrigusNulius //DobeBebubebobinulaububotin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BabebeBobogusgusdator">
    <eLiterals name="BrauGubebobebebiBocus"/>
    <eLiterals name="DibuBitin"/>
    <eLiterals name="EudagubebonulauGuses"/>
    <eLiterals name="EbubugusbuFrinulaubigusbecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBeBoBububogusGusBubegusius" eSuperTypes="//DobeBebubebobinulaububotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBifriBeBonulaunulaunus" ordered="false" upperBound="-1" eType="//AguboNulaubuFribubogusnulAufries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bibifribibifrifricus" abstract="true" eSuperTypes="//DuFriguFrinulaunulaubofrigusNulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebeBudabibotin" eType="//AlfriBofriBonulAuboEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauBibiBibubiNulAuTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Difritor" instanceTypeName="typeDigusFriFrigusDanulaubegunules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBufrifribobonulAuFributus" instanceTypeName="typeBabobeFriGusbinulauBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudanulauDadaDator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aufribugudaBuBoboBenus" eType="//Difritor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbobubedaboBufrifribotor" abstract="true" eSuperTypes="//DuFriguFrinulaunulaubofrigusNulius //Bibifribibifrifricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBibiDafriGugusBiBocus" eType="//EugusnulauguNulAubidabutin"/>
  </eClassifiers>
</ecore:EPackage>
