<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ditor" nsURI="http://hub.de/rcore/examples/ditor" nsPrefix="uD">
  <eClassifiers xsi:type="ecore:EEnum" name="DoBofriBonulaufribibubiNus">
    <eLiterals name="AbegusfribeBoes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabodagusgusauFribobitor"/>
</ecore:EPackage>
