<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="begugudafribigunus" nsURI="http://hub.de/rcore/examples/begugudafribigunus" nsPrefix="kfX">
  <eClassifiers xsi:type="ecore:EClass" name="BiguDabugusbobibeFribinulAubeDanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbobiBoBues" eSuperTypes="//BiguDabugusbobibeFribinulAubeDanules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobeBuFribobedanulaugusGugusguGuses" ordered="false" upperBound="-1" eType="//BiguDabugusbobibeFribinulAubeDanules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubugudadagusAudabeguLius" upperBound="-1" eType="//BiguDabugusbobibeFribinulAubeDanules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiNulaubegusfrigusbetin" instanceTypeName="typeBibufriFribobeNulAuDatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFrigusbigusAuNus" eSuperTypes="//AnbobiBoBues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubibobefriGusbubeTin" ordered="false" upperBound="-1" eType="//BiguDabugusbobibeFribinulAubeDanules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebubeNulaufriBeguBeBoes" eType="//DiNulaubegusfrigusbetin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubiNus" eSuperTypes="//BiguDabugusbobibeFribinulAubeDanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeguBiBegubugubidafribobolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bagubonulaububugubecus" eSuperTypes="//BeguBiBegubugubidafribobolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabugusbogusDabitor" eSuperTypes="//BiguDabugusbobibeFribinulAubeDanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadadafrinulaufribeBitin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuGusdaFrigusBuGudaCio">
    <eLiterals name="AuDabuboBoboFribeFriDator"/>
    <eLiterals name="DogusdaFriNulaubibuBuboNules"/>
    <eLiterals name="AubidaBubibefrigusbeDafribitus"/>
    <eLiterals name="BidaGudanulaubiDalius"/>
    <eLiterals name="DiDaGusGusaugufricio"/>
    <eLiterals name="EbugubidabefriTin"/>
    <eLiterals name="DodaFriguFrinulaunus"/>
    <eLiterals name="BabofriBogusdafrifribifrinus"/>
    <eLiterals name="AlGusDaGubofritus"/>
    <eLiterals name="AlbugusbogubidaNulaubiTor"/>
    <eLiterals name="DibuFrigusAuGusgusbigusBibuFritus"/>
    <eLiterals name="FabenulaugusnulAuBenulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alaunulaubobugunulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuguBiguBofriBicio">
    <eLiterals name="DonulauDabutus"/>
    <eLiterals name="DiBobibifributor"/>
    <eLiterals name="Fabobibodabecio"/>
    <eLiterals name="DiguBobibofrigubeguBuTor"/>
    <eLiterals name="DiBobeBudaDaDanulaunulaucio"/>
    <eLiterals name="BidaGusaudaBifrifriCio"/>
    <eLiterals name="BabibenulEs"/>
    <eLiterals name="DoGusbobiFriboBubuFrilius"/>
    <eLiterals name="DaBidaGuNulAuNulaunulaubufriGues"/>
    <eLiterals name="DigusboBubebuNules"/>
    <eLiterals name="BabenulauNulauBiTus"/>
    <eLiterals name="BiBebibidaboboFriDabugusboFricus"/>
    <eLiterals name="BiNulaubeDaBeBibifriLius"/>
    <eLiterals name="DonulauDaFribibobefriBinulaucus"/>
    <eLiterals name="DubibinulauBetor"/>
    <eLiterals name="AlGubogunulauGuBogusBoBibeBees"/>
    <eLiterals name="DunulaufriguDaes"/>
    <eLiterals name="BiDabitus"/>
    <eLiterals name="BigusFrigusfrifriDafriFries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubeBeBoBobiGusgubiFrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faboFridadaBuDaboBiLus" eType="//EuGusdaFrigusBuGudaCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebeDaFriBibubugusbugustin" ordered="false" eType="//FabugusbogusDabitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DaBofridagufriGusgudaDanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBedaboguFriNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaubogufriboGugustor" ordered="false" eType="//Alaunulaubobugunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFriGuFribeFrinus" eSuperTypes="//DubiNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBibiguBebifrigusDaCus" eType="//EuguBiguBofriBicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaudaBunulaunulAuDaGustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulAuGugubies" ordered="false" upperBound="-1" eType="//Alaunulaubobugunulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubiboBigugusGusnus" eType="//EuGusdaFrigusBuGudaCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboguBonulaubufribibotin" eSuperTypes="//BiguDabugusbobibeFribinulAubeDanules //DadadafrinulaufribeBitin //FaNulaudaBunulaunulAuDaGustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAuDabugusbobuBibeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulaubeBefrifrigusdaBeguguslus" abstract="true" eSuperTypes="//Bagubonulaububugubecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiDanulAudanulauboLius" eSuperTypes="//BeFrigusbigusAuNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiFribiguGubidagudaNules" instanceTypeName="typeBedabibeBofribebedaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdabufribidanulauBibeBebobeFriBiLius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EBigusNulauBiFritin">
    <eLiterals name="EfridabuFribibubigusbenulaubicus"/>
    <eLiterals name="DaBubeGuses"/>
    <eLiterals name="DobubenulAubofrinulAuBucio"/>
    <eLiterals name="BebibogugusfriGuGusfriDacus"/>
    <eLiterals name="BebubinulaubogusgusnulAuNus"/>
    <eLiterals name="AlBigudator"/>
    <eLiterals name="BabonulAugusaugubuBucio"/>
    <eLiterals name="BrAuBugubidagusdaNulauCus"/>
    <eLiterals name="DunulaugusnulaubuBudaBibegusCio"/>
    <eLiterals name="DagusDaGudadadagustus"/>
    <eLiterals name="DabugusBedaBuguDaBuFrinulEs"/>
    <eLiterals name="Dobofribibegusaufritus"/>
    <eLiterals name="AfrigusFrinulaudafriguBudalus"/>
    <eLiterals name="AdaguGuBobonules"/>
    <eLiterals name="AlbegubogububefriEs"/>
    <eLiterals name="BraubeDaFriNulaudafriEs"/>
    <eLiterals name="BrAuguDagusaugusbefriNulius"/>
    <eLiterals name="Eubugusbibinulius"/>
    <eLiterals name="AdafriBedaNulaudaLus"/>
    <eLiterals name="BraugusnulaubuguBigutor"/>
    <eLiterals name="BeDagusguBobegusbinulAubiboGutin"/>
    <eLiterals name="AubeBubobunulauGunulAuBuNulaulius"/>
    <eLiterals name="BenulAuGuBufribudaButus"/>
    <eLiterals name="FabeBiBegudaboGulus"/>
    <eLiterals name="FaBonulaunulauNulauBeNulAubucio"/>
    <eLiterals name="AubebibugunulaudanulauCus"/>
    <eLiterals name="BaBigusDator"/>
    <eLiterals name="EudaBudadabeBegusgunulauBubibofricio"/>
    <eLiterals name="Albogubigusnulius"/>
    <eLiterals name="AlNulaunulaugusbiBifrigustus"/>
    <eLiterals name="AugusnulAugubeGunus"/>
    <eLiterals name="AnBoFribuDabefrigusauDafritus"/>
    <eLiterals name="DanulauBoBoBeBoboGusGuscio"/>
    <eLiterals name="AnaugugusDaDanulius"/>
    <eLiterals name="BebeBiGuBoBoGusfriFrigusboGububiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BabebeBeboGusbenus">
    <eLiterals name="DugusbudaGuDagusboboBicio"/>
    <eLiterals name="BabiboBeBogunules"/>
    <eLiterals name="AuBiBuDabeBubebibiBoTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobibebobonulauDadabogubulus" abstract="true" eSuperTypes="//FabugusbogusDabitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EudagusaudabeguBugusbitus" instanceTypeName="typeDagubiGusboGusdatin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusdagusbuguBugubibelius" instanceTypeName="typeEuboGubinulaudabibodanulaulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DinulAuBogusgubobobeboNulAucio">
    <eLiterals name="EBeBoGusdadanus"/>
    <eLiterals name="Augusnulaugusaugunus"/>
    <eLiterals name="DoBegugudaBufries"/>
    <eLiterals name="AuFriFriBofriFribotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndagusDaboBiboBugufriCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbidabunulaubebeFriBeBegusbecio" ordered="false" eType="//Alaunulaubobugunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbubiGusboGuGusdalus" instanceTypeName="typeAGuBenulaugubogufribiNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugugugugusgusdabibubibeCus" eSuperTypes="//DubiNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifriBuBobubegusNulauNulAuLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augusgusgufributin" eType="//AlbubiGusboGuGusdalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anbotus" eSuperTypes="//DugugugugusgusdabibubibeCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuDaGuBunulaubodabonulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusdaFriBees" eSuperTypes="//BeFrigusbigusAuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusGufribeNulautus" ordered="false" upperBound="-1" eType="//FabugusbogusDabitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eugusbugusbolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusbonulaubiBenulaufrigudaCio" eType="//FaNulaudaBunulaunulAuDaGustin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebigusaubofriBuboDaboCus" ordered="false" eType="//BiboguBonulaubufribibotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudaBenulAubuCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DanulaubegusBeBugusBedagusbenus" instanceTypeName="typeAnguFrifriFriNulaufridaguFrifrinulAubigustor"/>
</ecore:EPackage>
