<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="digulius" nsURI="http://hub.de/rcore/examples/digulius" nsPrefix="YgR">
  <eClassifiers xsi:type="ecore:EClass" name="EuNulAunulauFribolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusbuBegunulAubigugunulAuboFriGuFriCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubobiNulauBitin" ordered="false" upperBound="-1" eType="//EuNulAunulauFribolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaufridabodanulauBibuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aufribibufrigusgunus" eSuperTypes="//EuNulAunulauFribolus //AnGusbuBegunulAubigugunulAuboFriGuFriCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebiGububobiGusgugufrifrifrifriBoNules" ordered="false" upperBound="-1" eType="//DonulaufridabodanulauBibuTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beFrifribufrinulauGusGuDabeTor" ordered="false" eType="//EuNulAunulauFribolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraudabinulAucio" instanceTypeName="typeBiDaGubudaGusaubuFridaFribebidaguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGugusbuFribenulaudagutus" abstract="true" eSuperTypes="//AnGusbuBegunulAubigugunulAuboFriGuFriCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobibugusgusfrifribigusAucus" ordered="false" upperBound="-1" eType="//DonulaufridabodanulauBibuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBifribogusDaBocus" eSuperTypes="//AGugusbuFribenulaudagutus //DonulaufridabodanulauBibuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFriBobogudaBeBobogubenulaufricio" ordered="false" eType="//EuNulAunulauFribolus"/>
  </eClassifiers>
</ecore:EPackage>
