<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bitor" nsURI="http://hub.de/rcore/examples/bitor" nsPrefix="UyD">
  <eClassifiers xsi:type="ecore:EClass" name="Eubodafribenulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlFriBiNulaugunulaububogulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabedabiDaguDaGudabeBuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBugusbeGudaguCio" eSuperTypes="//FabedabiDaguDaGudabeBuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBiguGusnulaunulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="difribunulaubufriFridaBuDabogusbefribicus" upperBound="-1" eType="//Eubodafribenulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DobubeBinus">
    <eLiterals name="DaGubobuCus"/>
    <eLiterals name="BeFribibeGuguscio"/>
    <eLiterals name="AubodagusgufribobuDabibuBees"/>
    <eLiterals name="BabifrinulaubufribuboGubodabugusbuLius"/>
    <eLiterals name="EBofriGusAugubuBoboNulius"/>
    <eLiterals name="EbeboBibuBobubelus"/>
    <eLiterals name="FaNulaufribogubebugudabedanus"/>
    <eLiterals name="FaboBigusNulaubibobuCio"/>
    <eLiterals name="AlbebiBinulaugusbubuNules"/>
    <eLiterals name="DudaboDabubiGusBoBebobiboDaes"/>
    <eLiterals name="AlGuBeBigusdafriNules"/>
    <eLiterals name="EubeBeBiGuFrinulAuboGustus"/>
    <eLiterals name="DuguBinulAuCus"/>
    <eLiterals name="FaGusbeFritin"/>
    <eLiterals name="BiGudaBoBigusaubedaTus"/>
    <eLiterals name="AlaubofribiBubeBubinus"/>
    <eLiterals name="EudaBibegufrigusnulauNulAucio"/>
    <eLiterals name="Abibees"/>
    <eLiterals name="EgusgusbebuDagustus"/>
  </eClassifiers>
</ecore:EPackage>
