<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="augubetus" nsURI="http://hub.de/rcore/examples/augubetus" nsPrefix="e">
  <eClassifiers xsi:type="ecore:EClass" name="DububobebedabiBedaGufribidabegulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBebuFriguFribiNulAugusnus" ordered="false" upperBound="-1" eType="//DobebidabobobobeboBeBobetin" eOpposite="//DobebidabobobobeboBeBobetin/anDagubugusbudaBuBodaNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobebidabobobobeboBeBobetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibiBucio" eType="//DububobebedabiBedaGufribidabegulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBiBebigububoboGuGugusgusBeEs" ordered="false" eType="//DububobebedabiBedaGufribidabegulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anDagubugusbudaBuBodaNulEs" ordered="false" upperBound="-1" eType="//DububobebedabiBedaGufribidabegulus" eOpposite="//DububobebedabiBedaGufribidabegulus/eBebuFriguFribiNulAugusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAubobobiNulaugusgubotus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusNulauGuBinulAunulauNulAuNus" eSuperTypes="//AlnulAubobobiNulaugusgubotus"/>
</ecore:EPackage>
