<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aulus" nsURI="http://hub.de/rcore/examples/aulus" nsPrefix="joD">
  <eClassifiers xsi:type="ecore:EClass" name="FaFriBinulaudagusDaGusBonules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBidaGusbofriBegutor" abstract="true" eSuperTypes="//FaFriBinulaudagusDaGusBonules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudaBeBubibebonules" ordered="false" upperBound="-1" eType="//FaFriBinulaudagusDaGusBonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibubibuBunulauNulius" eSuperTypes="//FaFriBinulaudagusDaGusBonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusGubiBibiBebidanulaulius" eSuperTypes="//FaBidaGusbofriBegutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAububuBobuBibinulAuBeGustin" eSuperTypes="//FaFriBinulaudagusDaGusBonules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abinulauDaboboTus" ordered="false" upperBound="-1" eType="//FaFriBinulaudagusDaGusBonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbobibeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibefribobolius" upperBound="-1" eType="//DibubibuBunulauNulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="andabues" ordered="false" upperBound="-1" eType="//EugusGubiBibiBebidanulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBeboFriBeguscus" eSuperTypes="//AnbobibeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBugusbiBolus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiBibiGunulauDagufrigubibebidagusBeBucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Afribubufribobecio" eSuperTypes="//AnBeboFriBeguscus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnNulauFrinulAububegugudafridaDanulaucus">
    <eLiterals name="BinulAuguNus"/>
    <eLiterals name="EGunulius"/>
    <eLiterals name="Babidaguslus"/>
    <eLiterals name="EGusbulus"/>
    <eLiterals name="FabeGugusfrinus"/>
    <eLiterals name="BagusbeBebifribugusGusbiFricus"/>
    <eLiterals name="EunulauBegusdanulaunulauguDagustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulaudadabofritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBinulaudaGusgugubunulAutin" ordered="false" upperBound="-1" eType="//AngusbenulAubetus" eOpposite="//AngusbenulAubetus/badagusgusGuFrinulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubobuguGunulauNulius" eSuperTypes="//AnBeboFriBeguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudaGusAugubigusFrigusaugusnulauLus" ordered="false" eType="//AnbobibeLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Begudabenulaulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauBebibobogusauDaBiNus" instanceTypeName="typeAngubuDaGugugudabiDaNulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnNulAubugusbenulAufribogusFriTor" eSuperTypes="//DibubibuBunulauNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusaudaboBebufriBobiFrifritus" ordered="false" eType="//AubobuguGunulauNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbiFriGubogusDaBegusbibogusgutus" instanceTypeName="typeBifriBiBibibeFribeGunulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuFribedaFrigubibeFricus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BifriBubibuboFricio" instanceTypeName="typeDibiFrinulAubifrifriBebiBudabubotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiNulauBufritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigubefribifribibuTin" eType="//FaFriBinulaudagusDaGusBonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlBogusGusauCio" instanceTypeName="typeBiBunulaunulAubobunulAuBebebilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eudadabigusbibitor" abstract="true" eSuperTypes="//AunulAububuBobuBibinulAuBeGustin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubuFribinulAubuNulIus" instanceTypeName="typeBebibobubeDanulaugusFriDabobegunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dinulaunulautin" abstract="true" eSuperTypes="//AubiNulauBufritor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EBobuNulAunulAuBodadatus">
    <eLiterals name="BrAubebedaBoTor"/>
    <eLiterals name="AFribufriguTor"/>
    <eLiterals name="AubeBubeBenus"/>
    <eLiterals name="EnulauGunulAuboBicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnulaunulAuLus" instanceTypeName="typeBiDanulaubiBibofribonulaufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusbenulAubetus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badagusgusGuFrinulIus" ordered="false" eType="//DoNulaudadabofritus" eOpposite="//DoNulaudadabofritus/doBinulaudaGusgugubunulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGububuDanulauGusgusbofritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBoBibuBugugubigucio" eType="//BrauBebibobogusauDaBiNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubidaboBeBiGusDaGuGusius" abstract="true" eSuperTypes="//DoNulaudadabofritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Donulaunulaubibonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digudaboBuBiNulaudanulaudaCus" upperBound="-1" eType="//Eudadabigusbibitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugugusAuNulIus" ordered="false" eType="//FaFriBinulaudagusDaGusBonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibeFribegusbudabububoFrinus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DagubiNulauNulAuDabibobubicio" instanceTypeName="typeAngunulauguGuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgudabufrigusGusDaFrinulauBoes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusgusBunulAuTor" ordered="false" eType="//BeGububuDanulauGusgusbofritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAubofribuBubibidaGusnulauBinulaufribicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuguBebobebiTin" eSuperTypes="//Dinulaunulautin //Donulaunulaubibonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braufrilus" ordered="false" upperBound="-1" eType="//FaBidaGusbofriBegutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiDabobegubiNus" eSuperTypes="//FaBidaGusbofriBegutor //AlgudabufrigusGusDaFrinulauBoes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusauGusbeBotin" ordered="false" upperBound="-1" eType="//Donulaunulaubibonus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulAuBeLius" upperBound="-1" eType="//DagubiNulauNulAuDabibobubicio" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
