<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bidalius" nsURI="http://hub.de/rcore/examples/bidalius" nsPrefix="We">
  <eClassifiers xsi:type="ecore:EClass" name="DaBedaboBogusdaDadadanulauCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBefribebogubinulaunulauguFritus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabuNulaubibibobuCus" instanceTypeName="typeBrauGusbogusBeNulaugusbofribebees"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndaBebobegusGusBuguguscus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubenulauBinus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusNulauDaNulauTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alaunulautor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabunulaubonulauDacio" eType="//AnfrigubedaFrilius" eOpposite="//AnfrigubedaFrilius/braubegugusFridaBoTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbeBefrigubigusnulauGubobinus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBibuboGuBiBigusCio" instanceTypeName="typeAlbubogusfriBuFriNulAuFritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuDagusboGubeGusbubebodaNus" abstract="true" eSuperTypes="//Alaunulautor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braugubudafriGusius" eType="//DiBibuboGuBiBigusCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribobogufrifriBoDalus" upperBound="-1" eType="//DugunulaudaDagusgunulAubiboTus" eOpposite="//DugunulaudaDagusgunulAubiboTus/eubeBedadadabeNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAububunulauDacus" eSuperTypes="//DuDagusboGubeGusbubebodaNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andabeguGusgufribees" ordered="false" upperBound="-1" eType="//AndaBebobegusGusBuguguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfriGubeBeNulaudaBeFrinulautin" eSuperTypes="//AndaBebobegusGusBuguguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbogusNulauFrigusguGustin" abstract="true" eSuperTypes="//DubenulauBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBibeBuNulaubeBeBeBegugunules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Anfridabebubudagutor" instanceTypeName="typeBadafriBoboGusgusfrifrinulaububeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusNulaunulautor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubebobitor" ordered="false" upperBound="-1" eType="//FaDaBoBeGubugugulus" eOpposite="//FaDaBoBeGubugugulus/duFriGusdafrinulaugudabiBigucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaubuDaguBunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFriDabuBulius" abstract="true" eSuperTypes="//EbogusNulauFrigusguGustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebibebibeguBufrigubeFries" upperBound="-1" eType="//BeBefribebogubinulaunulauguFritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagufrigunulaugusbegubuLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faNulaubedafricio" eType="//DiBibuboGuBiBigusCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaDaBoBeGubugugulus" abstract="true" eSuperTypes="//DaBedaboBogusdaDadadanulauCus //FagufrigunulaugusbegubuLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAubeCio" eType="//Anfridabebubudagutor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFriGusdafrinulaugudabiBigucus" ordered="false" eType="//EgusNulaunulautor" eOpposite="//EgusNulaunulautor/eubebobitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiguNulaunulaufriGubenulaubunus" eSuperTypes="//AlfriGubeBeNulaudaBeFrinulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfrigubedaFrilius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubegugusFridaBoTor" ordered="false" upperBound="-1" eType="//Alaunulautor" eOpposite="//Alaunulautor/fabunulaubonulauDacio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguBigubebobinulaucus" ordered="false" eType="//DubenulauBinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuGusnulauBeBuGubeBeGustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBuDaBulius" ordered="false" eType="//AlfriGubeBeNulaudaBeFrinulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Dolus" instanceTypeName="typeAfribeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Edagusaubibebogues" eSuperTypes="//DubenulauBinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGubonulauNulAutor" ordered="false" eType="//EuBuBebebeBiFriBiFriLius" eOpposite="//EuBuBebebeBiFriBiFriLius/faguFriBubuBodabocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbeNulAugubeGusnus" eSuperTypes="//EbeBefrigubigusnulauGubobinus //AlNulaubuDaguBunulius //AnFriDabuBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBefrigusaubetin" ordered="false" upperBound="-1" eType="//BrAububunulauDacus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubeNulaugusbibefribunus" ordered="false" upperBound="-1" eType="//Alaunulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBifriGuguNulaugunulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duGusBidaBoFribigusius" eType="//DiBibuboGuBiBigusCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBuguBebiGufrigusgusbotin" ordered="false" upperBound="-1" eType="//EgusNulauDaNulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BeboBeBibigusTor">
    <eLiterals name="BiFrifriGugusbebegusDaNus"/>
    <eLiterals name="BrauBeboFridafriNus"/>
    <eLiterals name="BrAudaBodaBuFrigufries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBuBebebeBiFriBiFriLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaBegufrifribogunulaudator" upperBound="-1" eType="//Edagusaubibebogues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faguFriBubuBodabocus" ordered="false" eType="//Edagusaubibebogues" eOpposite="//Edagusaubibebogues/diGubonulauNulAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusDafriGusbogutor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badaBibibutor" ordered="false" eType="//AbeNulAugubeGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBoDabibidafriboGusgusguboBubigusbolus" eSuperTypes="//BiguNulaunulaufriGubenulaubunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufriBobinulAubibobunulius" ordered="false" upperBound="-1" eType="//AlNulaubuDaguBunulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGusgusNulAubiBiBiTor" eType="//BrAuGusnulauBeBuGubeBeGustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauBinulAubuBoBigusgugugusBeBudabiboFriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubiFrigusFriGuGusBoGuNulAuGusbuBudaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGudabodagubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulauBugufribuGusgusbidagugubidafrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeFrigubedaBedaButin" eSuperTypes="//EubiFrigusFriGuGusBoGuNulAuGusbuBudaes //AlfriGubeBeNulaudaBeFrinulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusbuGusBegubenulaubiBocio" ordered="false" eType="//BiguNulaunulaufriGubenulaubunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiguboNulauGusaudanulauNulaugubuLius" eSuperTypes="//DuDagusboGubeGusbubebodaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugudaguguguNulaubidatin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anauBiguguslius" eType="//BeboBeBibigusTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufriguBifridaBefriLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaufribuguGusnulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dibedagusdabubogusbegustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubibenulaunulAubobebiBinus" eType="//DiBibuboGuBiBigusCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doDagusbulus" ordered="false" eType="//BinulauDaBiBonulauNulautin" eOpposite="//BinulauDaBiBonulauNulautin/dunulaubodadafribucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofriGusbidaNulaunulauFrigunus" abstract="true" eSuperTypes="//EgusNulauDaNulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGudabidabinulaubobofritus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAuDabinulauLius" eSuperTypes="//BeBifriGuguNulaugunulIus //EnulauBugufribuGusgusbidagugubidafrilius //Dibedagusdabubogusbegustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badabigunulaulius" eType="//Dolus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBifriFriBiBonulaubobigusbibicio" ordered="false" upperBound="-1" eType="//FaDaBoBeGubugugulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusBubeguDaGusguGusbenulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBiLius" ordered="false" upperBound="-1" eType="//EuBuBebebeBiFriBiFriLius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBudalus" eType="//DabuNulaubibibobuCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufribebiBegufribugusbies" eSuperTypes="//EgusNulaunulautor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBigusbufrilus" eType="//DiBibuboGuBiBigusCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABebiFrifribibiFrinules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baBiboBeBuguNulaugucus" eType="//Anfridabebubudagutor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euboFrifrigunulAunulaubebucus" ordered="false" upperBound="-1" eType="//Brauboes" eOpposite="//Brauboes/bagugusbebeNulAuBuNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EgusdabebuboBibogusdabetus" instanceTypeName="typeDiNulauGusNulAubeBebeDafribitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebigugufrifrifriBiGuscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofribodaguBobuBibogusLus" ordered="false" upperBound="-1" eType="//EuBuBebebeBiFriBiFriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabiGusNulAuBonulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabobebidaBugusBefriLus" ordered="false" eType="//BeBifriGuguNulaugunulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabufribegusbeGugusgusnulauboNus" instanceTypeName="typeAlBobebogusbibuboBues"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaboBiBonulauBuBoNulaufrigustor" abstract="true" eSuperTypes="//EuBuBebebeBiFriBiFriLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulauguguNulaugusBees" ordered="false" eType="//DufribebiBegufribugusbies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuDagubugufriboBogusgufriguslus" eSuperTypes="//AbeNulAugubeGusnus //AGudabodagubitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="du" ordered="false" eType="//EgusNulauDaNulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBubifrinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugunulaudaDagusgunulAubiboTus" abstract="true" eSuperTypes="//BeBefribebogubinulaunulauguFritus //AnFriDabuBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubeBedadadabeNulius" ordered="false" eType="//DuDagusboGubeGusbubebodaNus" eOpposite="//DuDagusboGubeGusbubebodaNus/anfribobogufrifriBoDalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diNulAubobobofrinus" ordered="false" eType="//DoBubiNulaucio" eOpposite="//DoBubiNulaucio/banulauBibeGubogusbilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Brauboes" eSuperTypes="//BenulAuDabinulauLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagugusbebeNulAuBuNulius" upperBound="-1" eType="//ABebiFrifribibiFrinules" eOpposite="//ABebiFrifribibiFrinules/euboFrifrigunulAunulaubebucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauDaBiBonulauNulautin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulaubodadafribucus" ordered="false" eType="//Dibedagusdabubogusbegustus" eOpposite="//Dibedagusdabubogusbegustus/doDagusbulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubiGusbugudaBobeguslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafricus" ordered="false" eType="//EuDagubugufriboBogusgufriguslus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBubiboBubibebuTor" eType="//DiBibuboGuBiBigusCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DabubudaGubebibonulius">
    <eLiterals name="AnbeGudadabifribenus"/>
    <eLiterals name="BegubuBuBeDagunulius"/>
    <eLiterals name="DaGusDaNulauGusGusFridanulaunus"/>
    <eLiterals name="BiBiBofrigufriBeDabilius"/>
    <eLiterals name="Dudabegubunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dibunulaudadafribocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAudadaGuboBoNulaubuFritor" abstract="true" eSuperTypes="//Dibedagusdabubogusbegustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusBigusBuBibotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAuBubuTin" eSuperTypes="//BaboBiBonulauBuBoNulaufrigustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebufrifriBiBobuBoGusgusboEs" ordered="false" upperBound="-1" eType="//BiGusBubeguDaGusguGusbenulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBubiNulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedabobebogubufritus" upperBound="-1" eType="//EbogusNulauFrigusguGustin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulauBibeGubogusbilius" ordered="false" upperBound="-1" eType="//DugunulaudaDagusgunulAubiboTus" eOpposite="//DugunulaudaDagusgunulAubiboTus/diNulAubobobofrinus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidadaguBufribuDagusCio" eType="//DabuNulaubibibobuCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DobebogusbefriDagudaDabifriDabeboEs" instanceTypeName="typeDinulAuBobuboboGusdabelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBuFriGusNulAuGububeCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabuBubeBibeFriguguNules" eType="//BraubuDaBiDadaBibebiGusfriGudator" eOpposite="//BraubuDaBiDadaBibebiGusfriGudator/benulAubeBiBodaButus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuDanulauguNulauDaBonus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiBoboDabibudalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbobeBodaboBifriBenulauTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguGusdanulaubibubetor" ordered="false" eType="//DinulauBinulAubuBoBigusgugugusBeBudabiboFriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeBebiGufriNulauGufribicus" eSuperTypes="//BenulaufribuguGusnulEs //EnulauBugufribuGusgusbidagugubidafrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabegudanulAuBobeFribodagustor" instanceTypeName="typeDoDabinulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFrifrinulaububigusaucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBoGubedanulaudagubobotin" eSuperTypes="//Dibedagusdabubogusbegustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBufriDanulaububunulaulus" ordered="false" upperBound="-1" eType="//FagufrigunulaugusbegubuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlgusBibibuBogugusbiGusLus">
    <eLiterals name="DabuBebidaguNus"/>
    <eLiterals name="AunulAugusbudabuNulaulus"/>
    <eLiterals name="DagusbeboGubibogusfrigubitor"/>
    <eLiterals name="BraubeFrigusdanulAunus"/>
    <eLiterals name="BiboDabuGusBucus"/>
    <eLiterals name="BeNulaunulAubinulaubobinulaulus"/>
    <eLiterals name="FaGusFriNulaububebofrigusbiBebegusGuslus"/>
    <eLiterals name="Dibegusaubenules"/>
    <eLiterals name="DuguBibogusgusnulAuBibogutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Babunulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulaudabunulAudanulaubuBibitor" ordered="false" upperBound="-1" eType="//AufriguBifridaBefriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebebutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGudabodabiFridaBeBunules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audabibenus" eType="//FabegudanulAuBobeFribodagustor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbibibiDaGusauDaTin" instanceTypeName="typeDoBubodadagusnulauNulaubodaFriFriFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbogudaBilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beGusnulAucio" upperBound="-1" eType="//Anfridabebubudagutor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoDagusGusDaBubeBiBies"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobiGusgudaGunulauBeGusGugubotus" instanceTypeName="typeAlGubugunulauGubibuDafribinulaubobucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubugusgudaDagubibunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duguboNulAubebetus" eType="//DabuNulaubibibobuCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubucus" abstract="true" eSuperTypes="//DaBedaboBogusdaDadadanulauCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedafrilus" upperBound="-1" eType="//EugudaguguguNulaubidatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DagudabudabefriBodabiNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubeBobubeBifrigusnulauCio" eSuperTypes="//AufriguBifridaBefriLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ditus" eType="//EbibibiDaGusauDaTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusFriDagusfriDaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbodabiGuboBedanulAuDacus" eSuperTypes="//EubiGusbugudaBobeguslus //BiGusBubeguDaGusguGusbenulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulaugusGunulAubeGuNules" upperBound="-1" eType="//EuDagubugufriboBogusgufriguslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAuBibibubibiBibuNules" instanceTypeName="typeBedadagufribubogutor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DonulAubegusDaDaboBugubiNulius">
    <eLiterals name="AlGusnulAubodabuGuslius"/>
    <eLiterals name="BanulaubodaboFrigusboBugusnulEs"/>
    <eLiterals name="AnBuFrifriBefribibobibutin"/>
    <eLiterals name="BibuBibebeDagusDatin"/>
    <eLiterals name="AlAudabubiBigusBenulAutin"/>
    <eLiterals name="AlbefribiBofrigusnulaucus"/>
    <eLiterals name="FabuNulaugugusguLius"/>
    <eLiterals name="AuBobeBoFriBofribonulaulius"/>
    <eLiterals name="AuFriBunulaudaBibonus"/>
    <eLiterals name="AgusbububiGubuFritor"/>
    <eLiterals name="Dalus"/>
    <eLiterals name="BrAufrigusBoboguFribifriguFritor"/>
    <eLiterals name="DidadaBinulAububenulAuGuTus"/>
    <eLiterals name="DagugufribibubenulAufrigutin"/>
    <eLiterals name="EgusbugusgusbogusTus"/>
    <eLiterals name="Aubibubibubobobebunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DoGusDafriDanulAugucus">
    <eLiterals name="EuNulauDaBubiBeDabobiCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BigusbonulAugusdabifricio" instanceTypeName="typeDuNulaubebiNulaudaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaGuFribeBufriBebugudafriguCio" eSuperTypes="//DubenulauBinus //AnFriDabuBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algusauBiBiGusguboTor" ordered="false" upperBound="-1" eType="//DoDagusGusDaBubeBiBies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugusguBibeFrinulauFriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anAuBefribugugunulaucus" eType="//DufribebiBegufribugusbies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbiNulauBobonulauGusBeTus" instanceTypeName="typeAfrinulAuBubeboEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGugugugusBoDagusbobubeguLus" eSuperTypes="//Brauboes"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaGudaGusguBoGubuBunulAunus" instanceTypeName="typeDunulaugusAudabunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulAuBiDanulIus" abstract="true" eSuperTypes="//BrAubucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigubobees" eType="//BigusbonulAugusdabifricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubuDaBiDadaBibebiGusfriGudator" eSuperTypes="//AlNulaubuDaguBunulius //DuBoGubedanulaudagubobotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulAubeBiBodaButus" ordered="false" eType="//EBuFriGusNulAuGububeCus" eOpposite="//EBuFriGusNulAuGububeCus/fabuBubeBibeFriguguNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AguFridaguNulAuNus" instanceTypeName="typeAlnulaufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusauBoBobonulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anAububodaNulAuBoFriBuBuBuGusgusdafriboEs" ordered="false" eType="//EbeBefrigubigusnulauGubobinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbufrinulaunulaudabiBeGusAulius" eSuperTypes="//BrAubucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AldanulAudaDaGusbodaNulEs" instanceTypeName="typeAnbufrifribudabedagusbigufribuBeGuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubuGugunulAuLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadaGusbutus" abstract="true" eSuperTypes="//DubeBobubeBifrigusnulauCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braunules" eType="//Dolus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBodabubiBufridator" ordered="false" eType="//BiGusBubeguDaGusguGusbenulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofribubigusaufribegunulAuTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabububugunulAutor" eType="//DabubudaGubebibonulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBuDanulAuguFrinulAubocio" instanceTypeName="typeDodabinulaubenulaubiBicus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuGunulaubigusFrifrilus" instanceTypeName="typeE"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBedaBebebobulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugubibidabebibubeButus" ordered="false" upperBound="-1" eType="//EugudaguguguNulaubidatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufriNulauFribiLius" eSuperTypes="//BrAugusguBibeFrinulauFriTor //DubenulauBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoFriNulaugugugugusfrifrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguGusGusgubutor" eSuperTypes="//EBuFriGusNulAuGububeCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abobeBitor" eType="//EbibibiDaGusauDaTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriGuDanulaufriFriguBiFriBiBilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBiBinus" eType="//Dolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBebibeLus" eSuperTypes="//Dibunulaudadafribocio //EgusNulauDaNulauTin //DagusFriDagusfriDaNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusnulaubogusauGubiLius" ordered="false" eType="//AndaBebobegusGusBuguguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAuguBubuGuCus" eSuperTypes="//Ebebutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AudaDanulAuboDaBibonulIus" instanceTypeName="typeFagunulaubiguNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alfrifrigusbebunulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusFribegufribiEs" ordered="false" upperBound="-1" eType="//EuBuBebebeBiFriBiFriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bilius" eSuperTypes="//BrAubucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBuDadadanulaububibuLus" upperBound="-1" eType="//EubiFrigusFriGuGusBoGuNulAuGusbuBudaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedadabiNulaugusbebibidanulAuDacio" eSuperTypes="//DuBoGubedanulaudagubobotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulauBegusauguBinulaugusIus" ordered="false" eType="//DubeBobubeBifrigusnulauCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAuBeGuDanulaunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagubububobegusgufriGuFricus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Digusfridagudagustin" instanceTypeName="typeBigufribebiFribibulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGuboBeDaGusbidagubeguTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaugudadafriBuBogubebiBies"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbudafriGuBiBebugusdalius" instanceTypeName="typeDaBibeGubeBeNulauBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofriDafridaGusguguFribiLius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BifribuGuNulAugusBeBenulAuTus">
    <eLiterals name="BrAudabugubibegusbeGubeLus"/>
    <eLiterals name="BegusGusnulaufriBibeGusauNulaugusGusTor"/>
    <eLiterals name="AnGusdabubebibedaguLius"/>
    <eLiterals name="Anbibinulaubunulaubilus"/>
    <eLiterals name="DubiFribiBudabeFrilius"/>
    <eLiterals name="AnfriBoFriBifridaboBefritin"/>
    <eLiterals name="EGuGusNulauBoBuNules"/>
    <eLiterals name="AuBenulauBeguEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnDafribogugunulaububocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBoguGugusDagugusGusAubebenulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulauguBoTin" ordered="false" eType="//DufribebiBegufribugusbies"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alGusBeGuboguBitin" eType="//Dolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnboguFrifridanulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBobibebeBogusgubonulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagunulauDabedafribogusFriGufriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafridabebeguGusdaGunulaubiBicio" eSuperTypes="//EuBuBebebeBiFriBiFriLius"/>
</ecore:EPackage>
