<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ator" nsURI="http://hub.de/rcore/examples/ator" nsPrefix="sZ">
  <eClassifiers xsi:type="ecore:EClass" name="EbiDabofrifribiNulaudafrinulaugudaLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFribofriBuBobubofrilus" eType="//BagufribidaBobuFrinulaugusbebedaLius" eOpposite="//BagufribidaBobuFrinulaugusbebedaLius/baFriGugugubidaBoNulAugusdabutus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBebigusBidaboBuBubiGubobebiTin" ordered="false" upperBound="-1" eType="//EdadaGugusbuDaBibuCus" eOpposite="//EdadaGugusbuDaBibuCus/dabibinulAuBubufrigusnulaubeboEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlboNulAuboGubidabuDagusNulAuBogusius" eSuperTypes="//EbiDabofrifribiNulaudafrinulaugudaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagufribidaBobuFrinulaugusbebedaLius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFriGugugubidaBoNulAugusdabutus" ordered="false" upperBound="-1" eType="//EbiDabofrifribiNulaudafrinulaugudaLius" eOpposite="//EbiDabofrifribiNulaudafrinulaugudaLius/baFribofriBuBobubofrilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBeDafrifriGububebobinulautus" ordered="false" upperBound="-1" eType="//AnBibudadabobiLus" eOpposite="//AnBibudadabobiLus/algues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaubifrigusGusnulaugusbeboCio" eSuperTypes="//AlboNulAuboGubidabuDagusNulAuBogusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBibudadabobiLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algues" ordered="false" eType="//BagufribidaBobuFrinulaugusbebedaLius" eOpposite="//BagufribidaBobuFrinulaugusbebedaLius/baBeDafrifriGububebobinulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusdabeGubeDaboLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBuBuBeboBeGubees" ordered="false" upperBound="-1" eType="//EguNulAuBoguBugusTus" eOpposite="//EguNulAuBoguBugusTus/dabefridaFriFribinulauGubegusTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EguNulAuBoguBugusTus" eSuperTypes="//AnBibudadabobiLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabefridaFriFribinulauGubegusTin" ordered="false" upperBound="-1" eType="//AngusdabeGubeDaboLius" eOpposite="//AngusdabeGubeDaboLius/daBuBuBeboBeGubees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaboFrifrifricus" abstract="true" eSuperTypes="//AngusdabeGubeDaboLius //AnBibudadabobiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dububudabibitor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BraufrinulauBiFriBedator">
    <eLiterals name="AfrigusgugusnulauBubies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bagusbedabobonulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusBiBoBeBobibeGustus" ordered="false" eType="//DinulaubifrigusGusnulaugusbeboCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADadaBugusBiDadagudaguNulauFrinus" abstract="true" eSuperTypes="//EbiDabofrifribiNulaudafrinulaugudaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBibebobuFribonulaunulauBilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBuNulaubuBeBicus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusfridabiDaboguBobecus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibobibenulauguNulAunulauDatus" eType="//BraufrinulauBiFriBedator" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibogugusbiDaBugusTus" eType="//DoBibebobuFribonulaunulauBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DoBibuBebobiGuses">
    <eLiterals name="DaBobeBuBiguboDanulius"/>
    <eLiterals name="EbeBubitus"/>
    <eLiterals name="AnDaBifriDaBicus"/>
    <eLiterals name="BafriFriBofrigusDadaNulauFrigusaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudaBonulAudaNulAuNulaubufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlauNulaugubobedanulaugustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfribedabiBuBibugugusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulAugusfribobodaguNulAulus" eSuperTypes="//AnBibudadabobiLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubobubeBidaNulEs" ordered="false" eType="//BagufribidaBobuFrinulaugusbebedaLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegufriFrigusDabebuBifrigusbiEs" eSuperTypes="//Dububudabibitor //DoBibebobuFribonulaunulauBilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoNulaugububeGusTus" instanceTypeName="typeEdabedagusaubidaFribetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbebudanulauNus" eSuperTypes="//EguNulAuBoguBugusTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuGusBefrifribotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauBiboBubiBiguscio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugubudanulauBubodabegulus" instanceTypeName="typeAfribubodaDafriBies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaugunulaubibufrinulAulius" eSuperTypes="//AnbebudanulauNus //AlboNulAuboGubidabuDagusNulAuBogusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBeBinulauBibedatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubuNulauGuGusbonulauCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusBogusNulAubebodadadaLus" ordered="false" upperBound="-1" eType="//Badaboes" eOpposite="//Badaboes/dubogusfribuBedanulauDabolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobobodafriDafribofribees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaubiFriboBebobigubuGuboboCio" ordered="false" eType="//AngusdabeGubeDaboLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabubebiguBibubiNulAubicio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFribidabigugubugunulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndabebubiFriGusTus" eSuperTypes="//AlauNulaugubobedanulaugustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAubodagusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusbiBifrifriBuFriBotus" abstract="true" eSuperTypes="//BenulaugunulaubibufrinulAulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algusboGuGubiFribigunulautor" ordered="false" upperBound="-1" eType="//Dububudabibitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBufriboGusbegusfriGusFriFriFrigusnulautus" eType="//AunulAubodagusIus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidabibibuBunulaubobuGuguCio" eType="//BraufrinulauBiFriBedator" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabubuBudabebeGulus" ordered="false" eType="//ADadaBugusBiDadagudaguNulauFrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdadaGugusbuDaBibuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabibinulAuBubufrigusnulaubeboEs" ordered="false" eType="//EbiDabofrifribiNulaudafrinulaugudaLius" eOpposite="//EbiDabofrifribiNulaudafrinulaugudaLius/aBebigusBidaboBuBubiGubobebiTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBodabobugubeboBoNus" abstract="true" eSuperTypes="//Dububudabibitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriBobedadagusAuNulaucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biFribobiBubibeBufritin" eType="//DoNulaugububeGusTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Badaboes" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubogusfribuBedanulauDabolus" ordered="false" eType="//AubuNulauGuGusbonulauCio" eOpposite="//AubuNulauGuGusbonulauCio/eugusBogusNulAubebodadadaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGuboBenulAulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbofrifribiBogusBodaes" instanceTypeName="typeEuBobuguGuGudator"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugusdaDaBonulaugunulauNules" instanceTypeName="typeDufrigusgudatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegugusgubodaGusbees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigubefrinulAugubicus" ordered="false" eType="//Badaboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABuNulaugubobegubues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Andabidacio" instanceTypeName="typeAuGugugusbebuboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusbudanulaubefriCus" eSuperTypes="//BenulaugunulaubibufrinulAulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubububobuBuBifrinulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EFridaBubifrinulauFribubedalus" instanceTypeName="typeDiNulaubiFrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfribifribeboBobeGusBeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusbogububogusGulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlguGusboBegusgufrinulaufribeGusAuBuBibiLus" eSuperTypes="//BegusbudanulaubefriCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anFriBibibiBiguguBufriEs" eType="//BraufrinulauBiFriBedator" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboGusdacio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbeBuBoguDaGusbiBebiBoDacio" ordered="false" upperBound="-1" eType="//BrAuGusBefrifribotus"/>
  </eClassifiers>
</ecore:EPackage>
