<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aunulaubibutus" nsURI="http://hub.de/rcore/examples/aunulaubibutus" nsPrefix="ojPG">
  <eClassifiers xsi:type="ecore:EClass" name="BrAuboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafriBebibugusbeFrinulAuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGubebubifribenulaubinulAudabelus" eSuperTypes="//BrAuboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGusbiNulaunulauBudaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusauGusbibutor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EBibiBuGubebobubeNulAulius">
    <eLiterals name="EubiGuBiBebufrigusBuNulaubulius"/>
    <eLiterals name="EunulAubifritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabeGusgubebicio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BibufriDaGusFridaBedabogusauCus">
    <eLiterals name="AnBiguGuGusBeboDadagugugusGusBues"/>
    <eLiterals name="BabibeBoFrigusAububies"/>
    <eLiterals name="EubiBibiDanulius"/>
    <eLiterals name="AubobiDaDafribigubuGusBebenulaudaBoBilus"/>
    <eLiterals name="AubiboBoBibefriFriBebetor"/>
    <eLiterals name="Anbebeguguscus"/>
    <eLiterals name="FaNulaubibiDaguscus"/>
    <eLiterals name="DaFriGubogudaBubeBies"/>
    <eLiterals name="AnGusdanulauBoguGuBuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Albenulaubecus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabuNulauGusBuBoGulius" eType="//BaGusauGusbibutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubeguDanus" upperBound="-1" eType="//BaGusauGusbibutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulauFriBoGuFriGubudaGusnulius" eSuperTypes="//AGubebubifribenulaubinulAudabelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibiFriboButor" eSuperTypes="//AGubebubifribenulaubinulAudabelus //Albenulaubecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusbeGububelius" upperBound="-1" eType="//AGubebubifribenulaubinulAudabelus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="befribigusDaDabiBuBiBitor" ordered="false" eType="//DunulauFriBoGuFriGubudaGusnulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubudagusFribenulaubeDaBubebolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBuboguBubebibunulaunulauDabutus" ordered="false" upperBound="-1" eType="//BeBigubonulaubogudaLius" eOpposite="//BeBigubonulaubogudaLius/ebefrigusbobedadaBofridanulaubilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuNulaunulaunulaububocio" instanceTypeName="typeBagusfriDabeBegunulaulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EugusbuCus" instanceTypeName="typeDaNulaunulauDabedabigusBenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboGuBogubiBunulauBeGudaDatin" eSuperTypes="//DibiFriboButor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAudabegusguBebibiBetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubonulaudafribeBeNulius" eType="//BibufriDaGusFridaBedabogusauCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusguGusBoDafridabugusgubudaguGubiBinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbuBebogubicus" eType="//EugusbuCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlauGusgusnulaubibuFribebidadanulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGusbuBebuBefriFrinulautus" ordered="false" eType="//AboGuBogubiBunulauBeGudaDatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbudaBidabibuDaBiBubeTus" eSuperTypes="//EubudagusFribenulaubeDaBubebolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBigubonulaubogudaLius" abstract="true" eSuperTypes="//DibiFriboButor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebefrigusbobedadaBofridanulaubilius" upperBound="-1" eType="//EubudagusFribenulaubeDaBubebolus" eOpposite="//EubudagusFribenulaubeDaBubebolus/euBuboguBubebibunulaunulauDabutus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusfridagusbocus" ordered="false" upperBound="-1" eType="//BaGusauGusbibutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulauguguBuBifriNulauCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbobiNulAubegusbubugusFriDadaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabebeNulAutin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauboGusfribobegudacus" eSuperTypes="//FafriBebibugusbeFrinulAuCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="altus" eType="//EBibiBuGubebobubeNulAulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboGuDafrigugulius" eSuperTypes="//BrauboGusfribobegudacus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiGubebunulAuGufribebebeTus" instanceTypeName="typeEunulauboFrifrifriGutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbeboguboGusnulIus" instanceTypeName="typeDoBoBugusgusbeFribiBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AFrigudabigufricio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egubigusbotus" ordered="false" eType="//EbobiNulAubegusbubugusFriDadaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboFriNulAugusbibiFriBibocio" eSuperTypes="//BrauboGusfribobegudacus //BraunulauguguBuBifriNulauCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dugusbugusguguscus" abstract="true" eSuperTypes="//BraunulauguguBuBifriNulauCus //BeBigubonulaubogudaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AguNulaunulaufrifribudafricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofrifridanulauboGusAuBeBufrilius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abenulAuBoGusguLus" eType="//AuNulaunulaunulaububocio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabufriBibunulauBoes" instanceTypeName="typeBrAunulaugusFriBogubiBubuGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulaudaboBudafrinulaucio" eSuperTypes="//DofrifridanulauboGusAuBeBufrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BefribobugusAuFriBuGusbugubelus" instanceTypeName="typeDoBeDafribedagusguBubuDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiFrigugudaGusgububiNulaubocus" eSuperTypes="//BaGusauGusbibutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Algusbefrigusfrigudabogusgusius" eSuperTypes="//BeBigubonulaubogudaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboboBuBenulaucus" eSuperTypes="//BaGusauGusbibutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeNulaudadanulAubibeguguBotor" instanceTypeName="typeDogugugugucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuGusBefrilius" instanceTypeName="typeAunulaubuBeguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBeGusbuDabigutor" eSuperTypes="//AboGuBogubiBunulauBeGudaDatin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubegusfriDaDatus" instanceTypeName="typeEugudaNulaubiBebefrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusboguses" eSuperTypes="//EbobiNulAubegusbubugusFriDadaTus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiBubobebunulaufrifriguFrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EgusGusbeguBuDatin" instanceTypeName="typeAngunulaudanulAubetor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AGusBunus">
    <eLiterals name="AnguBibeguGusbobebebuguTor"/>
    <eLiterals name="DadabiNulaubibeDagulius"/>
    <eLiterals name="AubinulaufrigusGusAubetor"/>
    <eLiterals name="DiboBoNulaudalus"/>
    <eLiterals name="Fabenulaubocus"/>
    <eLiterals name="AlBigusdabufribibofriboCus"/>
    <eLiterals name="AnulAugusBoguBoNus"/>
    <eLiterals name="AubinulauFrigusdaNulauBunus"/>
    <eLiterals name="FadabebufriguBelus"/>
    <eLiterals name="BrauDafrifrifribodaDadaboCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebinulaudaboGubiFrigusfribiboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBeFrifribeBebinulaucus" eType="//DabufriBibunulauBoes" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulaugubuBedaDaguNulaubefriCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dafriBenulAuNus" upperBound="-1" eType="//EugusbuCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaunulauguBebiBunulAububeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbobiNulaudabububulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alnules" eType="//AlbeboguboGusnulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusnulaugusBonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBoBudafrigunulaudanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraufriguguBuGusbegusbogusbotin" eSuperTypes="//DunulauFriBoGuFriGubudaGusnulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafrigubeGubobiBebiguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfribufriDagubuGuFricus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabifriBegutor" eSuperTypes="//DibiFriboButor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraudabuGusaudanulius" instanceTypeName="typeAlnulAutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dibibogusbonulaubebofricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBenulauBubunulius" ordered="false" upperBound="-1" eType="//FafriBebibugusbeFrinulAuCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EugufrigubibofriBiGusbuCus" instanceTypeName="typeBraubeDabobenulaunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBonulauBidaDadaboNulautin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabeBiDabocio" eType="//AlbeboguboGusnulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Digubibenus" eSuperTypes="//BebinulaudaboGubiFrigusfribiboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulAuNulaufribunulauFriTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubiDabubiguGuBubiNus" eType="//EBibiBuGubebobubeNulAulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AldagusGusBufrigubeLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubogudabuboboBefrifrigubeFritus" eType="//BiBubobebunulaufrifriguFrilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndafrinulAubeguscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabiBebibeBiguNulaubobodanus" instanceTypeName="typeEBoguboFribubugusbugusdanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulauGudabidafribeNulauLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnauboDabidabuTin" eSuperTypes="//EfribufriDagubuGuFricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGubobefriGudaguFriGusBinulaufrinus" eSuperTypes="//AldagusGusBufrigubeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauboGusAubobunulAubiguBufriCus" ordered="false" upperBound="-1" eType="//DabeGusgubebicio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulaunulaububobebiBuBububotus" ordered="false" eType="//BrauboGusfribobegudacus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulaugudaguBoDanulaubiTor" upperBound="-1" eType="//BaGusauGusbibutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBebobigusBibigusEs" abstract="true" eSuperTypes="//BaBeGusbuDabigutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuDabefrigusAunulaudadafrifribubotor" eSuperTypes="//FafriBebibugusbeFrinulAuCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlDaGusgububuBoes" instanceTypeName="typeBinulaugusfriNulaubecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiboBibiBobuDagunulaudaTin" instanceTypeName="typeAnDaBidaBidaGuGusbedagusauGuTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlGusdaguFriFrigusNus" instanceTypeName="typeBrAuNulaubibubobebegusbetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAufriguBifriGusbobuNus"/>
</ecore:EPackage>
