<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dies" nsURI="http://hub.de/rcore/examples/dies" nsPrefix="xC">
  <eClassifiers xsi:type="ecore:EClass" name="EunulAuFriBubiguboBoGudatin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufribonulaubufrigusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubeBuboNulauguBeNulEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodabiNulaugufries"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulauGuNulauBofribububebiTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaugusaubuFribuNulauFridaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufridaBonulauNulAucus" eSuperTypes="//AlnulauGuNulauBofribububebiTor //AnaugusaubuFribuNulauFridaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodagusnulAunulAufribobefribulus" abstract="true" eSuperTypes="//EubeBuboNulauguBeNulEs //EunulAuFriBubiguboBoGudatin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DibububoNulAulus">
    <eLiterals name="DoboFriFriGuBuFribudanus"/>
    <eLiterals name="BabubibenulAuBodabibenulauboguTin"/>
    <eLiterals name="DugubunulAubobuboGuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadafrifriBoBiBiTin" eSuperTypes="//EunulAuFriBubiguboBoGudatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braubufrinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDanulaububebunulaubodafricus" upperBound="-1" eType="//BadafrifriBoBiBiTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuFrifrigusgubibuCio" eSuperTypes="//EunulAuFriBubiguboBoGudatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daFribeguGusNules" upperBound="-1" eType="//AlnulauGuNulauBofribububebiTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebeBugugusbubuBofribufriguslius" ordered="false" upperBound="-1" eType="//EubeBuboNulauguBeNulEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBudaNulauboBiBenulaubogusguslus" ordered="false" eType="//Braubufrinules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibibiboboNulaububuNus" upperBound="-1" eType="//BadafrifriBoBiBiTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGubibugusFriBugudacus" eSuperTypes="//AnaugusaubuFribuNulauFridaLius //DodagusnulAunulAufribobefribulus //EufridaBonulauNulAucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algubinulauGucus" eType="//DibububoNulAulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDabuBifridabuLius" upperBound="-1" eType="//EuFrifrigusgubibuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBiboboDaBobebucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDanulaugubigugubiGubiLus" abstract="true" eSuperTypes="//AlnulauGuNulauBofribububebiTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diguFribuGugusfrigufrinulIus" eType="//EubeBuboNulauguBeNulEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBugusBuboGusaububeDadabeCio" eType="//DodabiNulaugufries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafrigudabegusBotus" eType="//DibububoNulAulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbebugusBogusfriLius" abstract="true" eSuperTypes="//AlnulauGuNulauBofribububebiTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaboFribobinulauguBobucus" instanceTypeName="typeDagubobubububuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabibunulauBebiGutor" eSuperTypes="//AnaugusaubuFribuNulauFridaLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoGuDaGusdafrigubodaLius" instanceTypeName="typeAngusboDaBiGubodaTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbiGusBigubonules" eSuperTypes="//AbebugusBogusfriLius //Braubufrinules"/>
</ecore:EPackage>
