<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eugusnules" nsURI="http://hub.de/rcore/examples/eugusnules" nsPrefix="Ib">
  <eClassifiers xsi:type="ecore:EClass" name="DobudaBebibedanulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaboBogusguBoFriFriTor" abstract="true" eSuperTypes="//DobudaBebibedanulauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abifriFribuguButor" eType="//DobudaBebibedanulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfrigusBiGunulaubibifrinulaulus" eSuperTypes="//FaboBogusguBoFriFriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eububoBefriBebububibeGusLius" ordered="false" eType="//DobudaBebibedanulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusbudaFrigusdabibibofriBogusGutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaDaDaDaguFritus" instanceTypeName="typeEBinulaubebiBogusgutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibebobuGugusbuFriNulAufrigucus" eSuperTypes="//AgusbudaFrigusdabibibofriBogusGutin //EfrigusBiGunulaubibifrinulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubobodanulaudatin" ordered="false" upperBound="-1" eType="//FaboBogusguBoFriFriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubebubefrinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuGusFriGusgusgufriNulAunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faNulAuBodaBeguguscio" eType="//DaDaDaDaguFritus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBobegucio" eSuperTypes="//AgusbudaFrigusdabibibofriBogusGutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusboDaboguGubuGusbefritus" ordered="false" eType="//BagusbeGusgusnulaucio" eOpposite="//BagusbeGusgusnulaucio/befrinulaudaNulauGusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabiDaboDagulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBigubibobibebobibulus" instanceTypeName="typeDinulaudafriGusbubenulAubebodatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusbeGusgusnulaucio" eSuperTypes="//DobudaBebibedanulauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befrinulaudaNulauGusCus" ordered="false" eType="//AuBobegucio" eOpposite="//AuBobegucio/dagusboDaboguGubuGusbefritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EfridaDabuBoDanulaubunus" instanceTypeName="typeBeBibebifribubifribubunulAuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubodabebibubiCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabobigusAufriBebonules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duDabuBefribeEs" eType="//FaBigubibobibebobibulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedabeBegusgusgusnules" eSuperTypes="//DobudaBebibedanulauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abobinus" ordered="false" upperBound="-1" eType="//DuguNulauGusNulauNulAuGucus" eOpposite="//DuguNulauGusNulauNulAuGucus/braubigugusGuNulaudafribobebobulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuguNulauGusNulauNulAuGucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebudabibobogusguNulAuFribuNules" ordered="false" upperBound="-1" eType="//AubebubefrinulEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubigugusGuNulaudafribobebobulius" ordered="false" eType="//BedabeBegusgusgusnules" eOpposite="//BedabeBegusgusgusnules/abobinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFrigusbebiBofriguBobinulaunules" eSuperTypes="//EbuGusFriGusgusgufriNulAunulius //FaboBogusguBoFriFriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulAubigubefriboLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauGuBubibogufriTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbibiBobudagubiNus" eSuperTypes="//BiFrigusbebiBofriguBobinulaunules //BagusbeGusgusnulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulAutin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedabeGusbebuguBoBebiTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiboBefrifrinulAudaGusNulaubutor" eSuperTypes="//BiFrigusbebiBofriguBobinulaunules"/>
</ecore:EPackage>
