<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dugugubinulaulus" nsURI="http://hub.de/rcore/examples/dugugubinulaulus" nsPrefix="Lu">
  <eClassifiers xsi:type="ecore:EClass" name="DinulauGusNulauBububiBoBidaDaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifriGuGusBefritus" eSuperTypes="//DinulauGusNulauBububiBoBidaDaCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubuFrigusgusbebunulauDacus" instanceTypeName="typeDuBuFrigugusGuGubinulaudaBiBoGuTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGubobigusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaBeGusBibiguguslius" eSuperTypes="//DifriGuGusBefritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBuBugusBiGusbidatin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBebeGusaububenulaubibuDabuTus" ordered="false" eType="//BeNulauFribuBidalius" eOpposite="//BeNulauFribuBidalius/bebebiGusNulaubinulauBubetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiDafritus" abstract="true" eSuperTypes="//DinulauGusNulauBububiBoBidaDaCio //DifriGuGusBefritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faboDaguDaBogusnulEs" ordered="false" eType="//AuBuBugusBiGusbidatin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfrigufrigusbuNulauNules" ordered="false" eType="//DodaBeGusBibiguguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulaubunulautus" eSuperTypes="//BiGubobigusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadaDaDanulaufribefricus" ordered="false" upperBound="-1" eType="//BeNulaudabiGunulAuDafrinulEs" eOpposite="//BeNulaudabiGunulAuDafrinulEs/eudabodaGusbeBudaGudafrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlFriGusfriTin" eSuperTypes="//DifriGuGusBefritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albiDaFrigufridabibifricio" upperBound="-1" eType="//BibobibiGusaudanulauGues" eOpposite="//BibobibiGusaudanulauGues/afrigufribobenulauboGubigusTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeboFriBofrinulAufribibocus" abstract="true" eSuperTypes="//EuNulaubunulautus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabodaNulauGunulautor" eType="//AubuFrigusgusbebunulauDacus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusGusbofridaBiBoBedagunulaubobebutor" abstract="true" eSuperTypes="//DifriGuGusBefritus //AlbeboFriBofrinulAufribibocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibefrigunulAubofridaBinulius" ordered="false" eType="//BiGubobigusTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudadaBifribuBigusdafriboguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaubiDaGuLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuBiFridabeBibobees"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusfribegubiNulauBeBedalius" instanceTypeName="typeFanulAuNulaunulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DanulaufriBubegusGuslus" instanceTypeName="typeBeBuguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Angububibibelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algusNulAuGuguguGusnulaudaFrinulAucus" eType="//DodaBeGusBibiguguslius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auNulaunulAulius" eType="//AuBiFridabeBibobees" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Baboes" abstract="true" eSuperTypes="//AlbeboFriBofrinulAufribibocus //DinulaubiDaGuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaugubinulAugusdanulAulius" abstract="true" eSuperTypes="//Angububibibelus //AnGusGusbofridaBiBoBedagunulaubobebutor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albiGusGusGusbogusBibuboNulEs" eType="//AuBiFridabeBibobees" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusNulaubunulAubuFriBoBoLius" eSuperTypes="//DinulaubiDaGuLius //DinulauGusNulauBububiBoBidaDaCio //BiGubobigusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibonulAuFrinulauboes" eSuperTypes="//EugusNulaubunulAubuFriBoBoLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubibibobiBiBeBubuBonulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBubogudagucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulauFribuBidalius" eSuperTypes="//AnbiDafritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebebiGusNulaubinulauBubetin" ordered="false" eType="//AuBuBugusBiGusbidatin" eOpposite="//AuBuBugusBiGusbidatin/aBebeGusaububenulaubibuDabuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAubobugulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="efridabiFridaFriFrinus" eType="//DanulaufriBubegusGuslus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AgudaguNulauFrinulaunulauLius" instanceTypeName="typeDubobefriBugusgugusbeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabiBugusbebuBoBiguBoDaGudaCio" eSuperTypes="//AubibibobiBiBeBubuBonulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbofribuBiBiboNulaubuGuboBunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulaudabiGunulAuDafrinulEs" eSuperTypes="//AudadaBifribuBigusdafriboguscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudabodaGusbeBudaGudafrilius" ordered="false" upperBound="-1" eType="//EuNulaubunulautus" eOpposite="//EuNulaubunulautus/fadaDaDanulaufribefricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGunulAunulaubeBulius" eSuperTypes="//AlbeboFriBofrinulAufribibocus //AnGusGusbofridaBiBoBedagunulaubobebutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGubuguCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daDagunulAubofrilius" eType="//DanulaufriBubegusGuslus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaBugubofriBeBebibeBefriLius">
    <eLiterals name="ABibeBibobonulaudaDacus"/>
    <eLiterals name="AufribuGubefriBiBeDagusgusaulus"/>
    <eLiterals name="AuGubebeDabofrinulauGugues"/>
    <eLiterals name="AlauGubudanulauBiGugusbobocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bigusgusaufribibubecio" eSuperTypes="//AuBuBugusBiGusbidatin //AlFriGusfriTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubebeBeNulAuNulauBonus" abstract="true" eSuperTypes="//DinulauGusNulauBububiBoBidaDaCio //AnGusGusbofridaBiBoBedagunulaubobebutor //EBubogudagucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGububefribegusdaes" eSuperTypes="//DiGunulAunulaubeBulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBidabeboGusFricus" eSuperTypes="//AudadaBifribuBigusdafriboguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriNulaubebenulAuBubibeNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibidabogubeboBefribegusGusDaNulaubitor" upperBound="-1" eType="//EuNulaubunulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BafriguDabiguGusBobibofricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agugusbobobogusauGuslus" eType="//AubuFrigusgusbebunulauDacus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EugudagusbiBeFriboBolius">
    <eLiterals name="Begusgubunulaucus"/>
    <eLiterals name="DuBoDaboGusAudagubebiLus"/>
    <eLiterals name="EBuBudaNulaulus"/>
    <eLiterals name="DoguGusFribebucus"/>
    <eLiterals name="BebobubugusdabiDabebidaGusnules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdabobidabigudagusGusdadaDanulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBofribubedaLius" eType="//DugusfribegubiNulauBeBedalius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faguNulaunus" ordered="false" upperBound="-1" eType="//AubibibobiBiBeBubuBonulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibobibiGusaudanulauGues" eSuperTypes="//BiGubobigusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="afrigufribobenulauboGubigusTor" ordered="false" upperBound="-1" eType="//AlFriGusfriTin" eOpposite="//AlFriGusfriTin/albiDaFrigufridabibifricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnFrigusfridaboGuGuscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babunulAuGugusgusboBedaBibetus" upperBound="-1" eType="//AlbeboFriBofrinulAufribibocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anbigusbobonus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="befribiBoboBoguBiCio" eType="//AgudaguNulauFrinulaunulauLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabenus" eType="//AgudaguNulauFrinulaunulauLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndabubofriBoBonulaunules" eSuperTypes="//BibobibiGusaudanulauGues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebiboNulAubenulAubiBeBubiTor" instanceTypeName="typeAlgusdabuDaBeGugusGusNulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadaNulAubugusnulAuBuGusbenulAubolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubeBubobuNulaufriLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusfrigusbiboboGugubebofribebugusBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubiFribobinulaubegusfribofries"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusnulaubuguBibiLius" eSuperTypes="//DabiBugusbebuBoBiguBoDaGudaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusnulaunulAubudafrifribunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusgubobubiFrigubeBudafriBogutin" eType="//DanulaufriBubegusGuslus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBodadabogudabobunulAudaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusfridaboNulius" ordered="false" upperBound="-1" eType="//AubibibobiBiBeBubuBonulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulaugusbuDanulAunulaugusgusEs" eSuperTypes="//DubiFribobinulaubegusfribofries"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAubebubobunulaubugusbeGusnulAutus" eSuperTypes="//FanulAubobugulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alGubibugusbitin" eType="//AubuFrigusgusbebunulauDacus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiguGubedafriDadalus" eSuperTypes="//DibonulAuFrinulauboes //DigusnulaunulAubudafrifribunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beGuBidadabiGusbefribelus" ordered="false" eType="//EBubogudagucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebodafribubobecus" eSuperTypes="//BafriguDabiguGusBobibofricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBiboGubufriBeDafriNulaugusAuTor" ordered="false" upperBound="-1" eType="//DinulAubebubobunulaubugusbeGusnulAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FabiGubeFributus">
    <eLiterals name="AuBoBubugufrinus"/>
    <eLiterals name="AuBibuBudaes"/>
    <eLiterals name="EnulauDabiNulAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubobuBiBuDanulAubonus" instanceTypeName="typeAuguDanulAubufribobiEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Eufribidagudabicio" instanceTypeName="typeDigusbudabibiBubonulauDaDanulauBubitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DifriDaGusbibobiGuscus" instanceTypeName="typeFabudafriNulauGudadanulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaudadanulaubiBubicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeguGusnulaunulauBibilus" eSuperTypes="//DinulauGusNulauBububiBoBidaDaCio //EuNulaubunulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBefriTus" ordered="false" upperBound="-1" eType="//DiGubuguCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauBibufrinulIus" abstract="true" eSuperTypes="//DubiFribobinulaubegusfribofries //DodaBeGusBibiguguslius //Anbigusbobonus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Begunulaugufrilus" instanceTypeName="typeBebodaBoBufribibiGusNulAuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubeguguDagugusgusBonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbugudagubebiBobubuFricio" eSuperTypes="//DugusfrigusbiboboGugubebofribebugusBelus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAuBogusbobebotor" instanceTypeName="typeDibibogusBiDaFriFrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiBotin" eSuperTypes="//Bigusgusaufribibubecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiFrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubugusgusDaGunulaubiNulaubugusfriBotus" instanceTypeName="typeBabebeNulaufrigubububiboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBenulauGusguboguBitin" eSuperTypes="//Baboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aDabuFribigusbucus" eType="//DubobuBiBuDanulAubonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifridabebifrifribebegufribegusBoTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bafrigusgusdagufrinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efrigusbuNulauBodaguguBuDabutor" upperBound="-1" eType="//EugusNulaubunulAubuFriBoBoLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulAuboNulauBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadafrifridaGusbubibubeFricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusGusgusbogusGusBibudabuCio" eSuperTypes="//DabiBugusbebuBoBiguBoDaGudaCio //AnbiguGubedafriDadalus //DodaBeGusBibiguguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeDagusBebofriBiBitus" eSuperTypes="//AndabubofriBoBonulaunules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Eububudabedatin" instanceTypeName="typeAugusgusfrinulaubeFridacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaguDabodabiBiboBubidalus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ADafrifrigusNulaunulAubebubiguslius">
    <eLiterals name="BigusCus"/>
    <eLiterals name="BibuGusBubebuFriBobufrigusbitin"/>
    <eLiterals name="Abibefrigusaubugunules"/>
    <eLiterals name="AbugusbiBenulauBeBecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrIus" eSuperTypes="//DabiBugusbebuBoBiguBoDaGudaCio //BadafrifridaGusbubibubeFricio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eFricio" eType="//DugusfribegubiNulauBeBedalius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebeNulaugubibeGusFrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiBiGunulaubigubiNulaunulAuBonus" ordered="false" upperBound="-1" eType="//EbugudagubebiBobubuFricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbibobudaboGulius" abstract="true" eSuperTypes="//AubeguguDagugusgusBonules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusbogusGusnulaubies" eType="//AgudaguNulauFrinulaunulauLius" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
