<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="difrifrigubelius" nsURI="http://hub.de/rcore/examples/difrifrigubelius" nsPrefix="GoK">
  <eClassifiers xsi:type="ecore:EClass" name="DobibiBoGunulAuGutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DibiGusNulautor" instanceTypeName="typeDifribuguBibuDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaudaGusbidaboboBuguBiBiTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobegusbuGusaugusbiBeTor" eType="//DibiGusNulautor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begubebobobubegusbues" eType="//DibiGusNulautor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibofriBunulauDafriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudafribinulAubibugusFrifriBiGuscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulaubiFriGusboboDafridator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albuDaGusFriDanulauCio" ordered="false" upperBound="-1" eType="//EudafribinulAubibugusFrifriBiGuscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BenulauGusfrigusnules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabonulauBofridaNulaugusgusfricio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdafriBuGuBoBibifribuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andaGudabuNulaubiEs" ordered="false" upperBound="-1" eType="//BabonulauBofridaNulaugusgusfricio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibebigusfriGusfribetor" ordered="false" upperBound="-1" eType="//BibofriBunulauDafriNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigubenulAufrinulAufriBobugusauCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuFribofriBoguGusbebufributor" instanceTypeName="typeDugusfriBinulauDabunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBugubibobiBebibubedacus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuDabeguBoTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAugunulauDadagusguBiBifrilus" instanceTypeName="typeAuFriGusGuGusbebibebebibuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiFriGufrigufriGugusbeBoCio" eSuperTypes="//FaBugubibobiBebibubedacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraufriGusAuDaDacio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBegusDaFriTor" eType="//AuFribofriBoguGusbebufributor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbubeBubibuFriBofrifridabetor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagugusfriBubiGugugubiCio" eType="//BabonulauBofridaNulaugusgusfricio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldaBiGusGusdadaBugusbuNulaulius" ordered="false" eType="//EudafribinulAubibugusFrifriBiGuscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaugusFriTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulAuBofribefriNulauDabuLus" ordered="false" upperBound="-1" eType="//AnaudaGusbidaboboBuguBiBiTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBoNulaubiGusDaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusAufribuDafriGusBies" eSuperTypes="//BabonulauBofridaNulaugusgusfricio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulAuFriGusBobogusbeboDaButor" eType="//BenulauGusfrigusnules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbibeBubegubeFritus" instanceTypeName="typeBabuBubibubibidaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBibiboBebigusnules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubinulauGubodagudaNus" ordered="false" eType="//BeBoNulaubiGusDaLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobubibofrifriNulauguBiguguCus" ordered="false" eType="//BibofriBunulauDafriNus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albuDabiGusdaguTor" eType="//AuFribofriBoguGusbebufributor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaunulAudabegudagusBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngufriBobigusbiLus" eSuperTypes="//EdafriBuGuBoBibifribuTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babuBiguNus" eType="//BrAugunulauDadagusguBiBifrilus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubigugusgubobeNulEs" eSuperTypes="//EudafribinulAubibugusFrifriBiGuscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFribubudaGusauTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaudabuDaFrifridaes" eSuperTypes="//DiFriGufrigufriGugusbeBoCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faboFridaTor" eType="//AuDabeguBoTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagubegufribibunulius" eType="//DibiGusNulautor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaguDabiGusaubuGuGustus" instanceTypeName="typeBefrifrigusBofriboGusbobees"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBiFribeFrinulAunulAutus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegugubedadanulAuDabobedalus" eSuperTypes="//BeNulaubiFriGusboboDafridator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubidagusBiguBegusBinus" eType="//DibiGusNulautor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AngusboDabifriGusNulEs">
    <eLiterals name="Alnulaubegudacio"/>
    <eLiterals name="EuGuBogunulauboNulauBidaguFrinulauboBiLius"/>
    <eLiterals name="DiBeguDaBedabeGustor"/>
    <eLiterals name="FabeBedaBoguTus"/>
    <eLiterals name="AuBubeBigunulaubenulaubudacus"/>
    <eLiterals name="DuBubuBugudabuBobogusfrilius"/>
    <eLiterals name="AuBeBibebogubegusBebenulaubibolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbodaboBobotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulAuboGugusaubuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubigubiBebodaBulius" eSuperTypes="//BiGusAufribuDafriGusBies //BegugubedadanulAuDabobedalus //AngufriBobigusbiLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabeBobobuBubegubicus" ordered="false" eType="//DigubenulAufrinulAufriBobugusauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBifribofriGufriGusguNulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiguBigugusgusfribeBobeLus"/>
</ecore:EPackage>
