<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anbutor" nsURI="http://hub.de/rcore/examples/anbutor" nsPrefix="iE">
  <eClassifiers xsi:type="ecore:EEnum" name="BeBiBobefriBubuguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnguBuNulaubifridaGusnulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dudabidabofridafries" eType="//BeBiBobefriBubuguses" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusgugugusaugusbucus" ordered="false" eType="//DodabugusAugusbigulius" eOpposite="//DodabugusAugusbigulius/anNulauTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BagusdanulaudaGububenulaugusbolius" instanceTypeName="typeAunulauFriDagusguFrigububoLius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuNulaubeBuBuDaGuBiBebubuBitor">
    <eLiterals name="DugubufribigusBigububobuguNulAutus"/>
    <eLiterals name="DoBufribudagusFrinulAubebubies"/>
    <eLiterals name="DaguBonulAufriboNulaufrinulaubeGulus"/>
    <eLiterals name="DinulAubuGusbinulAubebodaLus"/>
    <eLiterals name="BebudadabegusguBogubuDatin"/>
    <eLiterals name="DinulauguGusgusgusbobeBiDaGutin"/>
    <eLiterals name="DoGubuGusBubuGusfriBonus"/>
    <eLiterals name="AububiGusnulaubunulaugugusEs"/>
    <eLiterals name="BiboNulauBufribunulaufriBuNus"/>
    <eLiterals name="DuguGusbenus"/>
    <eLiterals name="DaBubiBubegunulaulus"/>
    <eLiterals name="DigusDabuGusgunulauboBudalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodabugusAugusbigulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anNulauTor" ordered="false" eType="//AnguBuNulaubifridaGusnulius" eOpposite="//AnguBuNulaubifridaGusnulius/eugusgugugusaugusbucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulAubufriguBigusFridanulaubobuBeGusbecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadanulaubugunulaufridaNulius" ordered="false" upperBound="-1" eType="//DodabugusAugusbigulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBeBoFrigusbigubuDatus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAuBeBuguguguboguguBoFrinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annulAugusboBiBobufriDalus" eType="//BagusdanulaudaGububenulaugusbolius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifribufrifribiBubugucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EugusnulauBofrigububogusLus" instanceTypeName="typeEuGusNulaunulaubudalus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugusGubodaBebinus" instanceTypeName="typeFagusauGusgusaubeNulaubelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abidafribetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdanulAubuguguBugugustor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFriDabulius" eSuperTypes="//AdanulAubuguguBugugustor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EbubunulauguboBuFriguBufriBobubotus" instanceTypeName="typeBraufribinulaubitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugugudanulAuDanulauBogusEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabebuNulaubebugusaugubeguDaTin" eSuperTypes="//DodabugusAugusbigulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBefrigunulIus" eType="//EugusnulauBofrigububogusLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubiBegusAuGucio" eSuperTypes="//AdanulAubuguguBugugustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbobigufriBeDaGusBuBitin" eSuperTypes="//BeFriDabulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubugufrifribeNulauGusbinulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abunulAubuguslus" eType="//EbubunulauguboBuFriguBufriBobubotus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuboboboDagustin" eSuperTypes="//BiNulAubufriguBigusFridanulaubobuBeGusbecus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubeBidagutus" eType="//EuNulaubeBuBuDaGuBiBebubuBitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusdafrinulaudabobogusBunulIus" abstract="true" eSuperTypes="//BeFriDabulius"/>
</ecore:EPackage>
