<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="efrigutus" nsURI="http://hub.de/rcore/examples/efrigutus" nsPrefix="mo">
  <eClassifiers xsi:type="ecore:EClass" name="AbeNulAubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedabeGubugutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBobiGusnulautus" instanceTypeName="typeDonulauboguguboguBebegugubiguguTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulAubinulaubigusbibubiBucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fadabibodabigusius" eType="//BaBobiGusnulautus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaubogubebebiCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biDaGusfridaBibilus" eType="//BaBobiGusnulautus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anFribubunulaubiGutor" eType="//BaBobiGusnulautus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubibinulAubeDanulaugusgusbeNulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babenulaubuBobenus" eType="//BaBobiGusnulautus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusdaboNules" upperBound="-1" eType="//EugububibobofriDafribogusius" eOpposite="//EugububibobofriDafribogusius/diguNulauNulAubebuBebees"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albeDaGusnulaunulaunulius" ordered="false" upperBound="-1" eType="//BeboBiNulAunulAuBubulus" eOpposite="//BeboBiNulAunulAuBubulus/bebuNulaunulaugusboBuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulAuDabibufriGufriNulAucio" eSuperTypes="//DinulaubogubebebiCus //DubibinulAubeDanulaugusgusbeNulius //BedabeGubugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofriBinulaunulauBoBogusnulAubogusBiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabibeFriGusbegufriFridaguGuscio" ordered="false" upperBound="-1" eType="//DinulaubogubebebiCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugububibobofriDafribogusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diguNulauNulAubebuBebees" ordered="false" upperBound="-1" eType="//DubibinulAubeDanulaugusgusbeNulius" eOpposite="//DubibinulAubeDanulaugusgusbeNulius/fagusdaboNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubidabeBubuguFriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulAuGuBedalus" eSuperTypes="//EubidabeBubuguFriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnAubebidabolius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibubigusBugudaBilus" eType="//BaBobiGusnulautus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebubeBibiGubuNus" abstract="true" eSuperTypes="//DofriBinulaunulauBoBogusnulAubogusBiLius //DubibinulAubeDanulaugusgusbeNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubugubeBigugusgusCio" eSuperTypes="//AnAubebidabolius //DinulaubogubebebiCus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaguDagunulEs">
    <eLiterals name="DigusbeBibeBubuBebotor"/>
    <eLiterals name="EunulauboFrinulauBifritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBunulAuBodabogusGusgufriBodanus" abstract="true" eSuperTypes="//EugububibobofriDafribogusius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuguBobugusDaGunulaugugusEs" instanceTypeName="typeFaboNulAunulauGuFriBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobefridabenulaubugudanulius" eSuperTypes="//DubibinulAubeDanulaugusgusbeNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudagububeFrinulauBuGuguDaGusbecus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufridaboBeboguBenulAudaTin" abstract="true" eSuperTypes="//BedabeGubugutor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibeNulauBubegufriBeTus" eType="//BaBobiGusnulautus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabebegugusaunulEs" abstract="true" eSuperTypes="//AudagububeFrinulauBuGuguDaGusbecus //DofriBinulaunulauBoBogusnulAubogusBiLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daGusbibenulauBiNulIus" eType="//BaguDagunulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlboguboDaguGusbubugucus" abstract="true" eSuperTypes="//EuNulAuDabibufriGufriNulAucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beDabibuBiTor" ordered="false" eType="//EubidabeBubuguFriTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBeFribububiDagubidaDagudaFricus" upperBound="-1" eType="//AubugubeBigugusgusCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboNulaugufriBiboBoGuBuGuBicus" eSuperTypes="//BiNulAubinulaubigusbibubiBucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulAubobegusAudagubebogunus" ordered="false" eType="//AnAubebidabolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbogusbeguBuGusboDabibunus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babibenulaunulauDabefries" eType="//BaBobiGusnulautus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulauboNulAunules" ordered="false" upperBound="-1" eType="//DubibinulAubeDanulaugusgusbeNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBebebiGuBebubofrifrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAugubedaBudabuEs" instanceTypeName="typeEuboBuBunulAuBufricio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EugusCus" instanceTypeName="typeDudagusBunulIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EbibeBoBeBegusnulAubeNules" instanceTypeName="typeDudaGusbiboGububidaboboBuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeboBiNulAunulAuBubulus" eSuperTypes="//FaBebebiGuBebubofrifrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBiGubuguBuDafriDaNulius" upperBound="-1" eType="//FaNulAuGuBedalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebuNulaunulaugusboBuNus" upperBound="-1" eType="//DubibinulAubeDanulaugusgusbeNulius" eOpposite="//DubibinulAubeDanulaugusgusbeNulius/albeDaGusnulaunulaunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaDabiguboboBeBiGusius">
    <eLiterals name="FaguBeBodanulauGusGutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobebiGugugusDaBeCus" abstract="true" eSuperTypes="//BebubeBibiGubuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaboBoBudafrigusfribubuBoFribees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubinulauBodagubucio" ordered="false" upperBound="-1" eType="//FaBebebiGuBebubofrifrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBuGuGusbeBoLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigugubebebibuBeFribeBoDaguTor" eSuperTypes="//BedabeGubugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGubuBiNulaudaCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAufribubigusbofricio" eType="//AuguBobugusDaGunulaugugusEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofriDaNulaudator" eSuperTypes="//DubibinulAubeDanulaugusgusbeNulius //BigugubebebibuBeFribeBoDaguTor //Dobefridabenulaubugudanulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBogusBiGusbiGusbiguGugubies" instanceTypeName="typeAgusNulAudanulaubedagugustus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBifrifriBebuBilus" instanceTypeName="typeEudafribuDanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfrifriNulaugusautus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusbuboGusbedafribobiguscus" ordered="false" eType="//EufridaboBeboguBenulAudaTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubeFrigugubububudabobubutor" instanceTypeName="typeDubuBuBegusbiBogusBuBudanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Digugunulaunulaunulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbudabubodaGusnulAubonus" instanceTypeName="typeAlBedaguNulaufribilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BibuBiBibebobiDatus" instanceTypeName="typeEgunulauGusNulaufribeGudagues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulauDaFriDabuDaButin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusfriBunulAufriBegusbobudalius" abstract="true" eSuperTypes="//AbeNulAubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBeDabodadanulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BeNulAugusBufrigusnulAugusfricus">
    <eLiterals name="AubufriGusBufrigusGunulaunus"/>
    <eLiterals name="BaGusnulauFribuBunulaucus"/>
    <eLiterals name="AudadanulAufribegusBobeNulaubutin"/>
    <eLiterals name="AnbibeBiboguGufribubobuGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubifriBiboFricio" eSuperTypes="//AudagububeFrinulauBuGuguDaGusbecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabobeDanus" eSuperTypes="//FaboBoBudafrigusfribubuBoFribees"/>
</ecore:EPackage>
