<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="braugububitin" nsURI="http://hub.de/rcore/examples/braugububitin" nsPrefix="MIH">
  <eClassifiers xsi:type="ecore:EClass" name="AuNulaubuNulaubibuguFriNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbunulauBibibibibedacus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EugusDagugusboGuDanulAubiGusius" instanceTypeName="typeFanulaunulaufrigustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fanulaufribodafribibinus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusBiboboBibobegusAuguboNus" eSuperTypes="//DugusbunulauBibibibibedacus //Fanulaufribodafribibinus //AuNulaubuNulaubibuguFriNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BagubobeBuGusbidacio" instanceTypeName="typeAfrinulauBoTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbenulaugusBebibucio" eSuperTypes="//Fanulaufribodafribibinus //BaGusBiboboBibobegusAuguboNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGuguDanulauguGusaudabebotus" ordered="false" eType="//Fanulaufribodafribibinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebiGusbidagubodaGusDanulaulius" instanceTypeName="typeDibiboboGuGubobonulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusboGunulAudaBufritor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EububigubobobofribeTin" eSuperTypes="//FagusbenulaugusBebibucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daFribeBegugusfrigubeLus" ordered="false" upperBound="-1" eType="//FagusbenulaugusBebibucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusbebufrifrifribiEs" ordered="false" eType="//EuBiGubuBoNulius" eOpposite="//EuBiGubuBoNulius/braubugusfriBobiTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EguFribibubedabuDagusbitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusFrifriGusbobuGuboNulAubiTor" ordered="false" upperBound="-1" eType="//EububigubobobofribeTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaguNulAuFriboTor" instanceTypeName="typeDibugusboBobogubebetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboBuboFrigudaGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebofriDafriNulauDagusgubuBifriBoGusnus" eSuperTypes="//AuboBuboFrigudaGulius //BaGusBiboboBibobegusAuguboNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBefriFrinulAubobobedatus" eType="//BagubobeBuGusbidacio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGububeBibuBibobuDagusEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audafriGusbuBedaBufriDalus" ordered="false" eType="//Fanulaufribodafribibinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFriguboTor" ordered="false" upperBound="-1" eType="//FagusbenulaugusBebibucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraufribibibuFribidafrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabibeboBedadaDadatin" ordered="false" eType="//ABedadaBiDagusNulEs" eOpposite="//ABedadaBiDagusNulEs/auBebeBufrigusFriBoTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibogusBodadadagusauNulAuboTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABedadaBiDagusNulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBebeBufrigusFriBoTus" ordered="false" upperBound="-1" eType="//BraufribibibuFribidafrinus" eOpposite="//BraufribibibuFribidafrinus/fabibeboBedadaDadatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiguboBuBibedabitor" eSuperTypes="//FagusbenulaugusBebibucio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BigusDabegubiBuBeGudatin">
    <eLiterals name="DuFriBiBebonulaufriGufritin"/>
    <eLiterals name="BraudabogusNulauBuNus"/>
    <eLiterals name="DiGuBidaBibudagusfriBonulauBebolus"/>
    <eLiterals name="EubuBubebeFribugusbugutin"/>
    <eLiterals name="AbenulAubebebibegubulius"/>
    <eLiterals name="EuGubobodabedagusgucio"/>
    <eLiterals name="Dugusgubetor"/>
    <eLiterals name="AlbebiBifrigusDabues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DadabubuBebibiBubotor" abstract="true" eSuperTypes="//DugusbunulauBibibibibedacus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DubobiBibuGuscus">
    <eLiterals name="EDafribiNulauDabolus"/>
    <eLiterals name="EGusgusbobinulAufridaFriBibetus"/>
    <eLiterals name="DugusbugusGusbeFrigutin"/>
    <eLiterals name="AuFriBebubuDanulauGudabutus"/>
    <eLiterals name="EuGusboFrifriBifritor"/>
    <eLiterals name="BrAunulaufridabeguFriBotus"/>
    <eLiterals name="Anbufrinulaugusgusbofrigunus"/>
    <eLiterals name="DiBobuBobubunulIus"/>
    <eLiterals name="AnGusBoBunulautus"/>
    <eLiterals name="BaDabonulAububudagusNules"/>
    <eLiterals name="EbebebigugusBelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlgusdabeNulaunulIus">
    <eLiterals name="EuBebiGuBobidadaBiboGusfriboBudalus"/>
    <eLiterals name="DafribidadafriBoBuboBefriBodaTin"/>
    <eLiterals name="AuguboNulaubugusAudalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaboFrinulauBiBoDaBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnNulAubogubedaGufribiboBiLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabidagubedaFribeguFricus" instanceTypeName="typeDagudabigubigubiguCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabebibubiNulauCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albofribinulaudaNulaubenus" upperBound="-1" eType="//AnNulAubogubedaGufribiboBiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBubuFridagubeGubuBolius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuFrigusbicus" abstract="true" eSuperTypes="//EguFribibubedabuDagusbitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBedabegusbilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eGusbues" eType="//DubobiBibuGuscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulAutin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbibobuboGubibonulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acio" upperBound="-1" eType="//DubobiBibuGuscus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBobibibobibobies" ordered="false" eType="//FagusbenulaugusBebibucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaudaNulAucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagudaGusgufriGubecus" instanceTypeName="typeDofribeBigusBuBefriButus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbenulauFrinules" instanceTypeName="typeAnbuDabeBoBibeBoNulAunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubobinulAuGusbobuGubelius" eSuperTypes="//EguFribibubedabuDagusbitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dinulauNulaunus" eType="//AbenulauFrinules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afrinulius" eType="//DubobiBibuGuscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBiGubuBoNulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusbeBoGusbonulAuLus" ordered="false" upperBound="-1" eType="//DibogusBodadadagusauNulAuboTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubonulaufrigusAubebogusdabetor" eType="//BagubobeBuGusbidacio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubugusfriBobiTin" ordered="false" eType="//EububigubobobofribeTin" eOpposite="//EububigubobobofribeTin/auGusbebufrifrifribiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANus" abstract="true"/>
</ecore:EPackage>
