<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abigusgugues" nsURI="http://hub.de/rcore/examples/abigusgugues" nsPrefix="Y">
  <eClassifiers xsi:type="ecore:EClass" name="AngusgusGudabiBubugusaudaFribunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAudaNulaugusTor" eSuperTypes="//AngusgusGudabiBubugusaudaFribunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBidadabugusNulAutin" ordered="false" upperBound="-1" eType="//AngusgusGudabiBubugusaudaFribunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuFribibibuboes"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebibugubeGusfrinulaugusnus" instanceTypeName="typeDuBigusguFrigubeBenulaucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabubuGububuGusbiBoguslius" instanceTypeName="typeDobogusNulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulAuBobufridafribibucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulauBedaGuguslus" ordered="false" upperBound="-1" eType="//EuFribibibuboes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabeGunulauguBiBuFribinulaunulauDafriEs" ordered="false" eType="//AngusgusGudabiBubugusaudaFribunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabuGubiBibibofricus" eSuperTypes="//EuFribibibuboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabugusgusGuFricio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabuBoNulaulius" eSuperTypes="//BiNulAuBobufridafribibucus //AnulAudaNulaugusTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGusbobudagusGuBebudaNulaulus" ordered="false" eType="//AnulAudaNulaugusTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibebobobunulauBoguBebuguslius"/>
</ecore:EPackage>
