<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="andabulius" nsURI="http://hub.de/rcore/examples/andabulius" nsPrefix="Rl">
  <eClassifiers xsi:type="ecore:EClass" name="EBubeFribeFrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDabebeBues" eSuperTypes="//EBubeFribeFrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulAuGusNulAubebuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AFriboNulAuguses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunus" ordered="false" eType="//EBubeFribeFrinulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulaubiboGusaubonulaudanulius" ordered="false" upperBound="-1" eType="//BiGusfrigudafriNulauBebeboGustin" eOpposite="//BiGusfrigudafriNulauBebeboGustin/dabugugubodaGuGufridaFribulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusfrigudafriNulauBebeboGustin" eSuperTypes="//DaDabebeBues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabugugubodaGuGufridaFribulus" eType="//AFriboNulAuguses" eOpposite="//AFriboNulAuguses/beNulaubiboGusaubonulaudanulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusbibuBudadabidalius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobogugusgubuGunulius" ordered="false" upperBound="-1" eType="//AFriboNulAuguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabibebegudabidabiDaGusBeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBinulaufridaGusNulEs" ordered="false" eType="//BiGusfrigudafriNulauBebeboGustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusbibigusBifriDaboLus" eSuperTypes="//DaDabebeBues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BafriBiNulauBobuguNus" instanceTypeName="typeFadagubiGuboNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Begugubugudagutor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auGusbebudaFriBegubebeFridaLius" eType="//BafriBiNulauBobuguNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnaubenulaudaFriboCio" instanceTypeName="typeBraubedadaBeguFrifricus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DidagubeGusbegusfritus" instanceTypeName="typeEunulAubeboBonulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabiguBiGusnulaufridaNulaudaboTin" instanceTypeName="typeFabuGusaugusBuFrigutor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DibuBebogusGubeNulius">
    <eLiterals name="EBenulAuLus"/>
    <eLiterals name="AubiNulaugusaunulius"/>
    <eLiterals name="EunulaunulauBiGusGusnus"/>
    <eLiterals name="AlBuBebugusnulauFriNus"/>
    <eLiterals name="EfriboGuBinulauBiBiFridafriFriDator"/>
    <eLiterals name="DoDaGusguBibotor"/>
    <eLiterals name="AubeGusBugusBeNulauLus"/>
    <eLiterals name="BibeguGusdaFribudaGuDabonulaunulius"/>
    <eLiterals name="DibebiGugunulAuFrilus"/>
    <eLiterals name="DigusgubobiboBicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBonulAuBubuBoFritin" eSuperTypes="//DigusbibuBudadabidalius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBedabubees" instanceTypeName="typeBebinulauBobobonulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraububedabiNulaubiLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baBebenulauBeguNulAuCus" eType="//DibuBebogusGubeNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlnulaunulAunulaudabifribubunulautus" instanceTypeName="typeAnbuGusguDanulAuBufriBeGuGulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Babibobugubelius" instanceTypeName="typeBefrifrigusBiDaFriGuBelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuguBiGusFribibibobidator" eSuperTypes="//AFriboNulAuguses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBegusguGusBogusgusDadabucus" ordered="false" upperBound="-1" eType="//EunulAuGusNulAubebuNules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusboguGugudaBiBobubodaGudaFrinulauTor" ordered="false" upperBound="-1" eType="//BraububedabiNulaubiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DubiNulAugubobudafriGusGusbiLius">
    <eLiterals name="AnbogusgusfriBuBeguGuNulius"/>
    <eLiterals name="DoBoFriGuBibeBobofries"/>
    <eLiterals name="Aufrigusgubifricus"/>
    <eLiterals name="DugusfribedagubiBofriTor"/>
    <eLiterals name="AuboNulauguTor"/>
    <eLiterals name="BraunulaubugusBefrigusLus"/>
    <eLiterals name="DoGusFribefriGusfritor"/>
    <eLiterals name="AlgusAubeGusbebebilus"/>
    <eLiterals name="BiBobebuguBuBebiCio"/>
    <eLiterals name="BifribububoBibebibubobufritor"/>
    <eLiterals name="AnbeGuguGububobodalius"/>
    <eLiterals name="AnbiBuNulaubiGunulauguBeNus"/>
    <eLiterals name="BeGusbofribuBonulAubifrinus"/>
    <eLiterals name="BafribeguFribiDafriGusAubofrigustus"/>
    <eLiterals name="FafriBebububobinus"/>
    <eLiterals name="Audagufribibufrinulaugues"/>
    <eLiterals name="AlbuFrigubeguNulaububucus"/>
  </eClassifiers>
</ecore:EPackage>
