<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aucio" nsURI="http://hub.de/rcore/examples/aucio" nsPrefix="lg">
  <eClassifiers xsi:type="ecore:EClass" name="BeBebebogusbegusgusgucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibegusaunulaubibogusBeFriCus" eSuperTypes="//BeBebebogusbegusgusgucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaFrinulaubebiBeDafriGues" ordered="false" upperBound="-1" eType="//BeBebebogusbegusgusgucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribefriDaLius" eSuperTypes="//BeBebebogusbegusgusgucus //DibegusaunulaubibogusBeFriCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubeNulAugusboGusaunulAubofributus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AgusbinulAuBugusDaGusbucus">
    <eLiterals name="FabenulAubuNulaugugusguguses"/>
    <eLiterals name="DuGufriGubicus"/>
    <eLiterals name="BibenulAuNus"/>
    <eLiterals name="AFrigudadabibeGusbonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeboNulauBebogusEs" abstract="true" eSuperTypes="//BeBebebogusbegusgusgucus //DibegusaunulaubibogusBeFriCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafriGufribibetus" ordered="false" upperBound="-1" eType="//BeBebebogusbegusgusgucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadagusgusguBiNulAugusBetin" eSuperTypes="//BeBebebogusbegusgusgucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bibubobobebibebegubufrinulautor" eSuperTypes="//BeBebebogusbegusgusgucus //BeboNulauBebogusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bidadadanulautin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubegusauBobitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Brius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGusNulauboGusnulAucus" ordered="false" eType="//Bibubobobebibebegubufrinulautor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="didabibogusnulaubidaGuBebubobubutus" ordered="false" upperBound="-1" eType="//DagusgunulAufriNus" eOpposite="//DagusgunulAufriNus/alBenulaunulAufriGusgusfriGusLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubiBoDanulauDafribocus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudaBiguBiGunulaudaguscus" ordered="false" eType="//AlfribefriDaLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaubeBodagusBobigusdagusNulaugudaLus" ordered="false" upperBound="-1" eType="//DibegusaunulaubibogusBeFriCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaudaboCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="afritin" upperBound="-1" eType="//Bibubobobebibebegubufrinulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DuFrigudadagusnulauBiBeCio">
    <eLiterals name="BabeNulaucio"/>
    <eLiterals name="BrauTus"/>
    <eLiterals name="BibebofriDaguGuslus"/>
    <eLiterals name="AlBiNulaubibefriBegunus"/>
    <eLiterals name="EunulaufrigusboDanulaunulaunules"/>
    <eLiterals name="DiGunulaunulaufrinulauBoBitin"/>
    <eLiterals name="EuBibiDator"/>
    <eLiterals name="BagubonulauBubefriLius"/>
    <eLiterals name="EuBubugunulAunulaubuBobeLus"/>
    <eLiterals name="BeDaBoFriBugusdaBedaTor"/>
    <eLiterals name="EuBiguBugusbebelus"/>
    <eLiterals name="BefribonulAunulAunulIus"/>
    <eLiterals name="FafribeboNulauDanules"/>
    <eLiterals name="AunulaubuDagusbugucio"/>
    <eLiterals name="AnGudaBofrilus"/>
    <eLiterals name="AnnulauBegusNulAunulius"/>
    <eLiterals name="DiBeGunulAuDadadalus"/>
    <eLiterals name="DogusgudabegusNulauguTus"/>
    <eLiterals name="DanulaufriguguFrigufries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBeNulauBoBuBenules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ENulaugusBodanulAutus">
    <eLiterals name="AlbuBibugubebebobonulaubulus"/>
    <eLiterals name="BeGusgusbobinulauBeNulaunules"/>
    <eLiterals name="DoBoBudaGufriBinulAuFriDaBubecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DigusfrifrinulAuTor" instanceTypeName="typeEFribobenulaugufriFriNulaububidadaTin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DodabuNulauFribudagudator">
    <eLiterals name="AubeGuBenulaunulAuBucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibiBidadanulAubebegusBedaBucus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebiBedadanulaubuBodacio" ordered="false" eType="//AubiBoDanulauDafribocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaubifrigufribiGugusgugusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabiguguBoes" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebodanulaufriboDanulauBibutin" eType="//AubiBoDanulauDafribocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BraubedaBuGuGusbetor">
    <eLiterals name="AubobuGuBuBiguBetus"/>
    <eLiterals name="DogusauguFriGuFribocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EguBebidaFrigugugudator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albubiGugusbiGuCus" ordered="false" upperBound="-1" eType="//FabufriBobigusgusgugustor" eOpposite="//FabufriBobigusgusgugustor/albigusfribulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EguguguBoDabibiBedabonus" eSuperTypes="//Bibubobobebibebegubufrinulautor //DabiguguBoes //EunulaudaboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufrifrigudabobuBitin" eSuperTypes="//Brius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFribeDabuCio" ordered="false" eType="//EubeNulAugusboGusaunulAubofributus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubobiFriBoNulius" eSuperTypes="//AubiBoDanulauDafribocus //Brius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulAufribuGusgusauboNulAuBebulus" ordered="false" upperBound="-1" eType="//EunulaudaboCus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabunulaudalus" eType="//BraubedaBuGuGusbetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusgunulAufriNus" abstract="true" eSuperTypes="//DibegusaunulaubibogusBeFriCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBenulaunulAufriGusgusfriGusLus" ordered="false" eType="//Brius" eOpposite="//Brius/didabibogusnulaubidaGuBebubobubutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugusDaguNulauBefriCio" instanceTypeName="typeEubudaDabobinulaugusBigusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguBifribiBogusbunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubibuGusbegunulius" eSuperTypes="//EubeNulAugusboGusaunulAubofributus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabubuNulauBofridaguBilus" ordered="false" upperBound="-1" eType="//EunulaudaboCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abuBiGusAufribegusBubobeBilius" upperBound="-1" eType="//BaGuGubigubonulaunulauNulaufrifritor" eOpposite="//BaGuGubigubonulaunulauNulaufrifritor/egubidadagubibibogulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedaNulauGugusauguboDacus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiFrinulAuBenulAuTor" instanceTypeName="typeEgubofriNulaubofriDaEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobuBebufribeBelius" instanceTypeName="typeDudabobiBees"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagugudaBidaGusBiBibolius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguNulAubibeFrigugusDaNus" eType="//FadagusgusguBiNulAugusBetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifrigubobogusauLius" eSuperTypes="//AlfribefriDaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Algusbenulaugusnulautus" eSuperTypes="//DaBeNulauBoBuBenules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulaugusNulauTus" upperBound="-1" eType="//Bibubobobebibebegubufrinulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BiboNulAubebidagusNulEs" instanceTypeName="typeFaBibigusgubiBoDaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudabeGubetin" abstract="true" eSuperTypes="//EguBebidaFrigugugudator //BeboNulauBebogusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbifriBuNulauDaboBebenulAutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AdaGugusGuBuNus" instanceTypeName="typeDofribugusgusGubuGunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBuBibubobenulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulauBubobodaCus" ordered="false" eType="//DagusgunulAufriNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbibonulAufriNulaucio" eSuperTypes="//EguBebidaFrigugugudator //DufrifrigudabobuBitin //Bibubobobebibebegubufrinulautor //Algusbenulaugusnulautus //AudabeGubetin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DanulaufridafriBunulauTin">
    <eLiterals name="BrauBubinulauNulaunulaudaLius"/>
    <eLiterals name="AlfriguDaBoguBeGuButus"/>
    <eLiterals name="EgusbiDaBuBubibuNulaubedatus"/>
    <eLiterals name="DabobofriNulautus"/>
    <eLiterals name="BedagubibobiLius"/>
    <eLiterals name="DibuGusDabiTor"/>
    <eLiterals name="DaBubigusbiBibubibelius"/>
    <eLiterals name="AnGusbubeBogugusdanulAudaFridanus"/>
    <eLiterals name="BaBonulaugusbunulAubitin"/>
    <eLiterals name="BeBoboGuBiBuGusgusbedaTor"/>
    <eLiterals name="AldaBebugusFriBefribiDabiNus"/>
    <eLiterals name="DibubogubiboFriNulauGubiLus"/>
    <eLiterals name="DuFribigunus"/>
    <eLiterals name="EgusGudabobegugusgusdabudaboNulAudacus"/>
    <eLiterals name="AGusGuboTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibubufribiGunulaubonus" eSuperTypes="//EubibuGusbegunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAudaBebogugusAuCus" ordered="false" upperBound="-1" eType="//DifrigubobogusauLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBeGusnulaunulauDagububuDatus" ordered="false" eType="//DufrifrigudabobuBitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BegubiBoBobubibies" instanceTypeName="typeAdabebugusbigugusAutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuGusFridanulAuBoLus" instanceTypeName="typeEgudafridanulauBufriDaguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Augusgusbebobibocus" eSuperTypes="//DanulaubifrigufribiGugusgugusius //AudabeGubetin //Brius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFridaBulus" eSuperTypes="//BagugudaBidaGusBiBibolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGusFribuBeGuBuDaes" ordered="false" eType="//AbifriBuNulauDaboBebenulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulauGusfribiNulAugugusFribuNus" eSuperTypes="//BeFridaBulus //AbifriBuNulauDaboBebenulAutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBoFribefrifrigusgugusbuDalius" instanceTypeName="typeAnbiBuNulauDadatin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubiFribunulauDaLius" instanceTypeName="typeEGusbubigugusfrinulaubiBilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Efribufribofrifrigutor" instanceTypeName="typeAlfriGusGufrigusguBuBuBuDaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusdaGugusdabobeguGuscio" eSuperTypes="//AbifriBuNulauDaboBebenulAutin //Bibubobobebibebegubufrinulautor //FadagusgusguBiNulAugusBetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dibigusnulaunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagugusGufricus" eType="//DuFrigudadagusnulauBiBeCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBiBodaguFrigulius" upperBound="-1" eType="//EubibuGusbegunulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faGufributin" eType="//DiFrinulAuBenulAuTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBigusbubuBudaGuGusbibebunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfriGusauBonulAubobiBofricus" ordered="false" eType="//EguBifribiBogusbunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibibuDaNulaunulauBiFriNules" eSuperTypes="//AlbibubufribiGunulaubonus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augusboDaboLius" eType="//AuGusFridanulAuBoLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbufrifrifriDaBidaBifries" ordered="false" upperBound="-1" eType="//EubeNulAugusboGusaunulAubofributus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiguBuGububunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeDabegufrigudaBiguBigusbubudanulAulus" eSuperTypes="//DufrifrigudabobuBitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBeguDadagusGunulAuguscus" upperBound="-1" eType="//DaBeNulauBoBuBenules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgusBedaBeBugusbinulauGusDalius" instanceTypeName="typeDidabodagusaunulAucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubobinulIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Bees" instanceTypeName="typeBafridaguguGufriBibotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuguFridafriGuBoBeBeboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebefribubeguDadaBilius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuboBudabobeNulauLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabububobiBiGunulaubogusius" instanceTypeName="typeDagusauFrinulaufribotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBuBifrifribuFribiBoEs" eSuperTypes="//Dibigusnulaunus //DigusdaGugusdabobeguGuscio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulaubogufriEs" upperBound="-1" eType="//DuFrigudadagusnulauBiBeCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusGufriboNulaubibedabuLus" eType="//AdaGugusGuBuNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBiFriDaguNulEs" eType="//DiFrinulAuBenulAuTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBedanulaudafrilius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufribibiBodafriEs" eSuperTypes="//AlfribefriDaLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eudabues" eType="//BraubiFribunulauDaLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabufriBobigusgusgugustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albigusfribulus" ordered="false" upperBound="-1" eType="//EguBebidaFrigugugudator" eOpposite="//EguBebidaFrigugugudator/albubiGugusbiGuCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusguFribeguBibububebodaTus" ordered="false" upperBound="-1" eType="//DuguFridafriGuBoBeBeboTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fadabedabeguLus" eType="//AlgusBedaBeBugusbinulauGusDalius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubodaBobiBoguboNulauTor" upperBound="-1" eType="//AudabeGubetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BidagusdaBobibubigunulIus">
    <eLiterals name="EdaFrigusbeDagusgusBegusbeGusgusgusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Begusbidabiguslus" eSuperTypes="//BeFridaBulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGuGubigubonulaunulauNulaufrifritor" eSuperTypes="//Augusgusbebobibocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egubidadagubibibogulus" ordered="false" eType="//EubibuGusbegunulius" eOpposite="//EubibuGusbegunulius/abuBiGusAufribegusBubobeBilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGusFribenulAuBubebeNulaulus" ordered="false" upperBound="-1" eType="//DabiguguBoes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubefriFriBinulaugutus" ordered="false" upperBound="-1" eType="//EuNulauGusfribiNulAugugusFribuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBiBudafriGusnules" eSuperTypes="//EguBifribiBogusbunules //BaBigusbubuBudaGuGusbibebunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFribiBubifrinulaucio" upperBound="-1" eType="//AubiBoDanulauDafribocus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDaboBubinulaubiTin" upperBound="-1" eType="//EguBebidaFrigugugudator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobubeGugusGubebecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBegusGufrinulaunulaugububetor" ordered="false" eType="//DufrifrigudabobuBitin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubugusbodabebiGuDabibifribitin" upperBound="-1" eType="//DifrigubobogusauLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AgusfriDabetor" instanceTypeName="typeAudadaguboBufriTor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EdabobibobeNulaulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FabuFriBeGububibiBubiBuBiEs">
    <eLiterals name="AndabuNulaucio"/>
    <eLiterals name="BeGudabobugusbuBifriBidabunulAuBofriCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafribigusgusboGuDator" eSuperTypes="//BraubobinulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dunulIus" eType="//DabububobiBiGunulaubogusius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufriBibogusgudaBubodaBibonulAulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfribobunulauBigusdaguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AububudagusbuBidabobugusnules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuGusdaFrifrifrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAudagudagusgudafriNus" abstract="true" eSuperTypes="//BeFridaBulus //Brius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibogusgubifriGusboGudagunulaunules" ordered="false" upperBound="-1" eType="//DaBeNulauBoBuBenules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGuBibiBufriGugusDaFribibiLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabobiBuGustus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaNulAuboFriGusGusbububudator">
    <eLiterals name="Babofridatin"/>
    <eLiterals name="BeboFrinulAuBifridalus"/>
    <eLiterals name="AnbuBudafriBoFribenulauFridaFricus"/>
    <eLiterals name="AlbeFribobibiNulAubuBenulaulus"/>
    <eLiterals name="BeBoBuFriDaNulauBogutus"/>
    <eLiterals name="AlbiFribedaFribuBocio"/>
    <eLiterals name="AgusaugusdaGubiTor"/>
    <eLiterals name="BanulAuBuNus"/>
    <eLiterals name="BibegusbeGubonulaunus"/>
    <eLiterals name="AudagusguBogusguGusNules"/>
    <eLiterals name="DuboBoBoNulAubuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabunulAunulaubucio" eSuperTypes="//AlfribefriDaLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabeBoBegugusbebecio" ordered="false" upperBound="-1" eType="//BaBuBibubobenulaulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusBibeTor" eType="//BraubiFribunulauDaLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabegusgusAuguCus" upperBound="-1" eType="//EuBoFribefrifrigusgugusbuDalius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFridafridadaBiguGuscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eguNulaugunulaudatus" ordered="false" eType="//DobebebidaBubibiBetus" eOpposite="//DobebebidaBubibiBetus/aubeBuGusAuGubiGuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabuguFrifrigusbeGusbelius" instanceTypeName="typeBebebibonulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbudaBuGusbudanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaBibebebelius" eSuperTypes="//DagusgunulAufriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusGusgusius" eSuperTypes="//Dibigusnulaunus //DibegusaunulaubibogusBeFriCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBigubigusgusDafritor" upperBound="-1" eType="//BegubiBoBobubibies" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnGugubobiFrifrifribodaCus" instanceTypeName="typeDubiGusFriFribifrifriGuBigucus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BanulaubinulAuGusaubibuNulEs">
    <eLiterals name="EnulaunulaudagusGusbeGugutus"/>
    <eLiterals name="AuBufriNulaubiBibonules"/>
    <eLiterals name="EGubegusbunulAuGusdafriFriEs"/>
    <eLiterals name="AnfribuCus"/>
    <eLiterals name="BraudaNulauBuBiBebuNus"/>
    <eLiterals name="BagubunulAuNulauBedadaGulius"/>
    <eLiterals name="DinulauGubitin"/>
    <eLiterals name="DiDabuDaBonulaubiBogunus"/>
    <eLiterals name="Bi"/>
    <eLiterals name="DobedaNulAubobuFriguTor"/>
    <eLiterals name="BigusdagusGusauGusgufriguCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BafriBigusDagunulaufribuTus" eSuperTypes="//AbibonulAufriNulaucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babebeGubeFriNulauDaBigugubelus" eType="//BraubiFribunulauDaLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fanulaubugustus" eType="//DobuBebufribeBelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdafriBigugusboBogusNules" eSuperTypes="//Augusgusbebobibocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dadabolus" eSuperTypes="//BraubobinulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboBedaDafribinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugusBiGusbuDabiBogudaFriLius" eType="//DobuBebufribeBelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbegusgusNulaudadagusGusNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibodadabunulAuFriboBecio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anes" eType="//EuGusdaFrifrifrilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BefrigubeboboguFribofrinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudaGuBubebofribuGusguGuTin" ordered="false" eType="//DobubeGugusGubebecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubegusbeFriBefrifridabibenus" eSuperTypes="//BaBigusbubuBudaGuGusbibebunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abeguDaDaBubudadaDagusbues" ordered="false" upperBound="-1" eType="//BeBebebogusbegusgusgucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobodaBonulaubegusgusaucus" eSuperTypes="//DigusdaGugusdabobeguGuscio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubibiguNulauDabiDaNulius" eType="//DiFrinulAuBenulAuTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugusDagusnulAuNulauCus" eSuperTypes="//AudabeGubetin //BraubobinulIus //DibiBidadanulAubebegusBedaBucus //BebefribubeguDadaBilius //DanulaubifrigufribiGugusgugusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobedaBuguFridabegutor" ordered="false" eType="//Augusgusbebobibocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADabigusbuboNulauBedaNulAubobolius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusgusaudafriDanulAuBeCio" ordered="false" eType="//DuGusGusgusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAufrifrinulaugusbifriBedaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeBufrigufriGusbinulaubutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobebebidaBubibiBetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubeBuGusAuGubiGuEs" ordered="false" upperBound="-1" eType="//EFridafridadaBiguGuscus" eOpposite="//EFridafridadaBiguGuscus/eguNulaugunulaudatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusfriGuses" eSuperTypes="//Bidadadanulautin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BeGuGuGufribiGubigubolus">
    <eLiterals name="DadabibiGuguFribiGusdaEs"/>
    <eLiterals name="DudafribebobiboFrigubiBoBoDadabeCus"/>
    <eLiterals name="Ebubulius"/>
    <eLiterals name="AudagusbiguFribunulauguslius"/>
    <eLiterals name="BegusbofrinulauBenulius"/>
    <eLiterals name="BrAubogubinulAunus"/>
    <eLiterals name="AlbiBoboboGusbenulaugusDaBefriLius"/>
    <eLiterals name="Bagugugusfrifrigusgusbebebocio"/>
    <eLiterals name="EuBobobuboguDagubegustor"/>
    <eLiterals name="DadabeBidabuGusgufrigusAulus"/>
    <eLiterals name="DudaGusnulaunulius"/>
    <eLiterals name="BeNulaubuGusbefribitus"/>
    <eLiterals name="DudanulauNulaudaCus"/>
    <eLiterals name="FaboBubofriNulauBibies"/>
    <eLiterals name="DifriBinulaudaGuDaGubunus"/>
    <eLiterals name="EBobuBubeNulAudaes"/>
    <eLiterals name="FabigusbofriFribubegusius"/>
    <eLiterals name="AlgubufribobigubunulEs"/>
    <eLiterals name="AubuGubeFribebuFriDator"/>
    <eLiterals name="DufriBeBogusgugusnulAuboBinulauTus"/>
  </eClassifiers>
</ecore:EPackage>
