<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dabogucio" nsURI="http://hub.de/rcore/examples/dabogucio" nsPrefix="Vx">
  <eClassifiers xsi:type="ecore:EEnum" name="BeBuBonulauBudadafrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiboGusauGusDadanulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbogugusfriLius" ordered="false" eType="//BraubenulAugunulaubefricio" eOpposite="//BraubenulAugunulaubefricio/biboGubuBobobelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgugubodaGubugubeFridaBoGusbilus" instanceTypeName="typeBifriBuGusGubobobigubibuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBogubebogusaubebugusFriFribucus" eSuperTypes="//DiboGusauGusDadanulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFribeBifriGubeGubucio" ordered="false" eType="//DiboGusauGusDadanulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baGusboCus" eType="//AlgugubodaGubugubeFridaBoGusbilus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BifriboBibobubefriBeguTor">
    <eLiterals name="BinulaunulAubobubifriFribelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubenulAugunulaubefricio" eSuperTypes="//DoBogubebogusaubebugusFriFribucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboGubuBobobelius" ordered="false" eType="//DiboGusauGusDadanulius" eOpposite="//DiboGusauGusDadanulius/anbogugusfriLius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binulAugusgunulauguFrifritin" eType="//BeBuBonulauBudadafrinulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlGusbebuBebofribogunulauTus">
    <eLiterals name="DuGusfriBigusbubogunulaucio"/>
    <eLiterals name="AbigugusAuBonulauBunulius"/>
    <eLiterals name="AfrinulAugubibilius"/>
  </eClassifiers>
</ecore:EPackage>
