<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bidabugubees" nsURI="http://hub.de/rcore/examples/bidabugubees" nsPrefix="lI">
  <eClassifiers xsi:type="ecore:EEnum" name="BiBebinulauboguBofridaGubuguses">
    <eLiterals name="BebogusbigusBuBedaFribeFribibebiEs"/>
    <eLiterals name="AnBobebofricus"/>
    <eLiterals name="DoguBobibunulAufriBoGubufribues"/>
    <eLiterals name="ABunulauNulaufribogubiBenulIus"/>
    <eLiterals name="DagubodaDaFriguTin"/>
    <eLiterals name="BeGugusFridaBiEs"/>
    <eLiterals name="BabobogubidaBeNulAubidabotus"/>
    <eLiterals name="BebuBidagusgusDaLus"/>
    <eLiterals name="Begusbecus"/>
    <eLiterals name="DibuboBebuBiGusnulAuguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusNulaubonulAunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFribeGuBoDanulaudacus" ordered="false" upperBound="-1" eType="//Efribebobobobebeguslius" eOpposite="//Efribebobobobebeguslius/befribofribubiGuslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBobiFrifribebeBubiFriBegusTus" abstract="true" eSuperTypes="//DigusNulaubonulAunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anius" eType="//BiBebinulauboguBofridaGubuguses" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBoBubebobofriBebolus" eSuperTypes="//DigusNulaubonulAunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulauGubugusTus" eType="//DuboNulaudaGusgusDabigusnulaucus" eOpposite="//DuboNulaudaGusgusDabigusnulaucus/dabobifriGugusNulAuFribonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabufrinulaudabibeTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusbibefrifribugubilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusboNulaubunulauGudadator" ordered="false" eType="//DoBobiFrifribebeBubiFriBegusTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BadafrigusBogusDaGusgusbonus" instanceTypeName="typeDigusgugusFriBugusbiBitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebuFriguguBeGusnules" eSuperTypes="//AuBoBubebobofriBebolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugugudadanulaubibebudabebeBuTin" eSuperTypes="//DigusNulaubonulAunulius //AuBoBubebobofriBebolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBibubeFridaBues" eSuperTypes="//EubebuFriguguBeGusnules //BiGusbibefrifribugubilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbobodanulAugutus" abstract="true" eSuperTypes="//AlBibubeFridaBues //FabufrinulaudabibeTin //DoBobiFrifribebeBubiFriBegusTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBugudabiguGuguNulius" ordered="false" eType="//BaGusaubiBebuBoBenulaunus" eOpposite="//BaGusaubiBebuBoBenulaunus/duNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBebiBodabifrigunulaubiNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuboNulaudaGusgusDabigusnulaucus" eSuperTypes="//DigusNulaubonulAunulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabobifriGugusNulAuFribonus" ordered="false" upperBound="-1" eType="//AuBoBubebobofriBebolus" eOpposite="//AuBoBubebobofriBebolus/banulauGubugusTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EuDaBobegusdagusgustin">
    <eLiterals name="Anbogusfrifridabubodadabogusnulaulius"/>
    <eLiterals name="BaNulAuguNulaububodaTin"/>
    <eLiterals name="DugusGuFriguboBuBiboGuguslus"/>
    <eLiterals name="EuBuBeBinulAubidadaNulautin"/>
    <eLiterals name="BabebuDaBodagusius"/>
    <eLiterals name="EbofriBugubibuguguDanules"/>
    <eLiterals name="AlnulaugusnulAuBobuboGusbetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAuBuBofriGugusnulaubebicio">
    <eLiterals name="DobobobonulaubufriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaboBufribibegusnulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobinulAuTor" ordered="false" upperBound="-1" eType="//AlbobodanulAugutus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibuGusguBoBinulAubecio" ordered="false" eType="//AugugudadanulaubibebudabebeBuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BidabobeboBeTus" instanceTypeName="typeBabibegusguGubetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Efribebobobobebeguslius" eSuperTypes="//DaboBufribibegusnulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befribofribubiGuslius" upperBound="-1" eType="//DigusNulaubonulAunulius" eOpposite="//DigusNulaubonulAunulius/duFribeGuBoDanulaudacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaguBebiDanulauBilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faboGusBonulauNulaubuBefrilus" eType="//EuDaBobegusdagusgustin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbiFriGusaubiDanulaunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugubuNulauboBubetus" abstract="true" eSuperTypes="//AlBibubeFridaBues //FabufrinulaudabibeTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBigusIus" ordered="false" eType="//AuBoBubebobofriBebolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabibobufrigunulaudabuguGufriLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albefriboguDadaBogunules" ordered="false" eType="//Efribebobobobebeguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AGufrigusNulaubugubebinulautor" instanceTypeName="typeAnaubogubedaDanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAuguBeDaBubebidanulAudabocio" eSuperTypes="//DaguBebiDanulauBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulAuDaDabedabugusfriguscus" ordered="false" eType="//AlBibubeFridaBues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BibuBuDagudaBigusfriBebubinulaulus" instanceTypeName="typeDaNulAubiBobudaTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EgudabunulauDabuGustor" instanceTypeName="typeDoGubibodaNulaugububuGuBuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauDaBiboGuBotin" eSuperTypes="//DanulAuguBeDaBubebidanulAudabocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuguBeNulaufrigusgusDabobeGusBeBoBenulautor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badaBibifriBoNulAugusBuGusAucus" eType="//BibuBuDagudaBigusfriBebubinulaulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulauGusgusBeNulaudatin" ordered="false" eType="//AnfriBugusTus" eOpposite="//AnfriBugusTus/dibibeGubiBuboFriBiBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofridabeguboboBiBefribocio" eSuperTypes="//AuBoBubebobofriBebolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibidabibeGusgusnulaubibiTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubebudabebibecio" ordered="false" upperBound="-1" eType="//BrauBebiBodabifrigunulaubiNus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auGuBubedabeBiTin" eType="//BidabobeboBeTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubigusbeBoBegusfries" eSuperTypes="//AlbobodanulAugutus //DanulAuguBeDaBubebidanulAudabocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBiFridafriNulauguBuguTin" eType="//BadafrigusBogusDaGusgusbonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusfribenulAudator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ebigubofrifridagusgusgugusnules" eSuperTypes="//DanulAuguBeDaBubebidanulAudabocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabidaguguGubunulauDagutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguDaguBolius" ordered="false" upperBound="-1" eType="//AuBoBubebobofriBebolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGuboNulaufriBibeEs" abstract="true" eSuperTypes="//DanulAuguBeDaBubebidanulAudabocio //DinulauDaBiboGuBotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaBonulaunulAuGusbucio" eType="//BibuBuDagudaBigusfriBebubinulaulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifriNulaubenulAudaboes" eType="//AlbobodanulAugutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaubuGuDaBucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euFrigusfriBodabefriGuGusfritin" eType="//BadafrigusBogusDaGusgusbonus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusbebobenus" ordered="false" eType="//Efribebobobobebeguslius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algubebogugusbuNus" eType="//BadafrigusBogusDaGusgusbonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlNulaunulauDaFribebulius">
    <eLiterals name="FadabeFriBudabutin"/>
    <eLiterals name="DugudanulAudabuBuCio"/>
    <eLiterals name="DoFriboNulaufribufrilius"/>
    <eLiterals name="AnfrigusbebinulAugusgusnulAuLus"/>
    <eLiterals name="BeGubegunulauguBenulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusaubiBebuBoBenulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duNules" ordered="false" upperBound="-1" eType="//AlbobodanulAugutus" eOpposite="//AlbobodanulAugutus/biBugudabiguGuguNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adabenulaubibebobotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aufribugunulaufrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudagusNules" ordered="false" upperBound="-1" eType="//AuBoBubebobofriBebolus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dudaguFrinulIus" eType="//BadafrigusBogusDaGusgusbonus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfrigubinulautor" upperBound="-1" eType="//DinulauDaBiboGuBotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbeDaGuBigubefriBogusGusguslus" instanceTypeName="typeDobinulAudafritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobidabedabiBiFrigudabulus" eSuperTypes="//DuboNulaudaGusgusDabigusnulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBebunulAubobobees"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabeGusGubigusTor" instanceTypeName="typeAubebibubonulaubobenulaufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagunulaugusbufrigubebiBeguscus" eSuperTypes="//Ebigubofrifridagusgusgugusnules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiDabiBiGusfriboNulaugusBufribulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriBugusTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaubibuDaNulaugubiGusauDaBecus" ordered="false" upperBound="-1" eType="//DoBobiFrifribebeBubiFriBegusTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibibeGubiBuboFriBiBenus" ordered="false" upperBound="-1" eType="//EuguBeNulaufrigusgusDabobeGusBeBoBenulautor" eOpposite="//EuguBeNulaufrigusgusDabobeGusBeBoBenulautor/anulauGusgusBeNulaudatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngubonulAuboFrifrigusbiboFricio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusBoBogufriGusCio" eType="//Ebigubofrifridagusgusgugusnules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbubuBoboguGusBodagusbues" instanceTypeName="typeDofribulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbidabunulAubobeBufriBofricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBuboboGuguBifribeBebunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braufribodabugusdaBunus" ordered="false" upperBound="-1" eType="//DuboNulaudaGusgusDabigusnulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabunulAuBebiLius" instanceTypeName="typeAubebigusbidaBefrinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusDafribigucio" eSuperTypes="//FagusfribenulAudator"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbegusgugusauBeboGusbeTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eudabegusfribedaBocus" eType="//EgudabunulauDabuGustor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabibiDadabiguguBibees" ordered="false" eType="//AugugudadanulaubibebudabebeBuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGuBudanulAufribicus" eSuperTypes="//EuguBeNulaufrigusgusDabobeGusBeBoBenulautor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BraubeFrigufriBiBiBibeboguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGudagudaTor" eSuperTypes="//BrauBebiBodabifrigunulaubiNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagubodabiFriBubeTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulAubodaDadabiLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biDabobuNulauNus" ordered="false" eType="//Ebigubofrifridagusgusgugusnules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubiBugubunulauGusnus" eSuperTypes="//DagunulaugusbufrigubebiBeguscus"/>
</ecore:EPackage>
