<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aubogusius" nsURI="http://hub.de/rcore/examples/aubogusius" nsPrefix="Zi">
  <eClassifiers xsi:type="ecore:EClass" name="AlboNulauFridaDagubeBebiNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusBugusgusgusBoDadanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulaubugusBibidatus" eSuperTypes="//DugusBugusgusgusBoDadanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBubebiGusgusAufribedanulAunus" ordered="false" eType="//AuguNules" eOpposite="//AuguNules/dabigubibebeFrifridaGusnulAuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBuGutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBedabibiguboBucio" instanceTypeName="typeAnAugunulAubeGusbigugucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabibibunulauboGudaTin" eSuperTypes="//EuNulaubugusBibidatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafribuBigusguFriguTus" abstract="true" eSuperTypes="//FaBuGutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadaguBonulIus" eSuperTypes="//DugusBugusgusgusBoDadanus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuNulAuBobutus" eType="//EuBedabibiguboBucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudabibefriNulaubifriLus" ordered="false" eType="//FaBuGutin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulAufrigunulauFries" ordered="false" eType="//AlboNulauFridaDagubeBebiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubibeBudaguslius" instanceTypeName="typeEuNulauBigusbidabegusDaGunulAuBicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuguNules" abstract="true" eSuperTypes="//DabibibunulauboGudaTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diguboguGufrinulEs" eType="//BraubibeBudaguslius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabigubibebeFrifridaGusnulAuCio" ordered="false" upperBound="-1" eType="//EuNulaubugusBibidatus" eOpposite="//EuNulaubugusBibidatus/eBubebiGusgusAufribedanulAunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubigusbugubebedaBifricio" ordered="false" eType="//DiBuBibibibeGusFriTor" eOpposite="//DiBuBibibibeGusFriTor/brauboGusboNulaufrifriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAugugusbinulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duNus" eType="//EuBedabibiguboBucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EufriBeFribegusbobubedagufriNus">
    <eLiterals name="AufrinulAuboBibuGusfriBuLus"/>
    <eLiterals name="BiBeboBegububoTin"/>
    <eLiterals name="AbuGudabiDabunulEs"/>
    <eLiterals name="AgudafriGuGusBuCus"/>
    <eLiterals name="DoGusBibiBibuboGuGugusgubifritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGuTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AgugusnulaubuNulauGusauFribinus" instanceTypeName="typeAnGugubububifriFrigucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabubeGuBoDanulAufriBilus" eSuperTypes="//DugusBugusgusgusBoDadanus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaDagusbugudabofritus" instanceTypeName="typeAnBifridabiGugusbobuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibigusbeBeBibuNulaubebobunulEs" eSuperTypes="//EuNulaubugusBibidatus //FaBuGutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dubufrinulaugucus" eSuperTypes="//FaBuGutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBugububenulAuguguguBofrigucio" abstract="true" eSuperTypes="//FabubeGuBoDanulAufriBilus //BafribuBigusguFriguTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauGudabeFritor" upperBound="-1" eType="//EufriBeFribegusbobubedagufriNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBuBibibibeGusFriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauboGusboNulaufrifriEs" ordered="false" eType="//AuguNules" eOpposite="//AuguNules/aubigusbugubebedaBifricio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAunulauguBiBucus" ordered="false" eType="//EuNulaubugusBibidatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABugubofriBebonulAubufriboBinus" eSuperTypes="//DinulAugugusbinulIus //AuguNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulAubufriBoGusbinulAubugusfrinulaugusgucio" ordered="false" upperBound="-1" eType="//DinulAugugusbinulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBufrifribibonulaubofridaBuGusguGubebuGubuTin" eSuperTypes="//AuguNules //BadaguBonulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dodanulaubebelius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibigubeBiBuBiFribuGugusBuNus" abstract="true" eSuperTypes="//DiBufrifribibonulaubofridaBuGusguGubebuGubuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaubogugusbuBobeboGuTus" eSuperTypes="//FabubeGuBoDanulAufriBilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Andabiguscus" abstract="true" eSuperTypes="//DuGuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndabibuGuBenulAugulius" eSuperTypes="//AlboNulauFridaDagubeBebiNus //DuGuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusGusnulAuDaGunulauBugusbodaCus" eSuperTypes="//AlboNulauFridaDagubeBebiNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugunulaubeNulaubebebiguFriDatus" eSuperTypes="//DabibibunulauboGudaTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaububuBoBetus" upperBound="-1" eType="//BafribuBigusguFriguTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiBibiGufribocio" eSuperTypes="//DugusBugusgusgusBoDadanus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabiDabifridalius" eType="//EuBedabibiguboBucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGuBebibeTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBedafritus" eType="//AgugusnulaubuNulauGusauFribinus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusguBebebeguBiGusbobobibitor" ordered="false" eType="//DuGuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiBuDaBudanulaucus">
    <eLiterals name="AugubuBidaFrifrinus"/>
    <eLiterals name="AnbiBigusBebiBeTus"/>
    <eLiterals name="DabeFribibobofrifrinules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGuguNulAuBoguslius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGuGusBuBobefrifribodadalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faguBibefrigusnulAubonus" ordered="false" upperBound="-1" eType="//Dodanulaubebelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBiFriNulauguBiBoDaLius" instanceTypeName="typeAlaubobebibifries"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuDaBuBiBebebubocio">
    <eLiterals name="BiguFridaBibigusaudaNulAubinulIus"/>
    <eLiterals name="BibogusaububuBeLius"/>
    <eLiterals name="BibobobebiBebebugustor"/>
    <eLiterals name="AbigubiBufrigunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBobugubeBebotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABogugugubufriGusgubeGugulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubibigusdabudabiBudadaLius"/>
</ecore:EPackage>
