<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="babefridatin" nsURI="http://hub.de/rcore/examples/babefridatin" nsPrefix="yQ">
  <eClassifiers xsi:type="ecore:EClass" name="BabeGufribibiboBefritus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DufriFribibibibuBubelius" instanceTypeName="typeAGusaubibobiBucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriFriBonulaugubugusbudanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusgusfricio" ordered="false" upperBound="-1" eType="//BabeGufribibiboBefritus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulauboDadacus" ordered="false" upperBound="-1" eType="//BabeGufribibiboBefritus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubobuFribidaTor" ordered="false" upperBound="-1" eType="//BabeGufribibiboBefritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuGusAubefriGusbibuguGutor" instanceTypeName="typeDabiBigusgusdaDagusaunulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BraubedafribonulauGusBilius">
    <eLiterals name="BefridabogusGusAuBuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiboBiBinulauBodaBuFrinus">
    <eLiterals name="BifriGusnulaudadadator"/>
    <eLiterals name="An"/>
    <eLiterals name="DonulaudagugububeGusdatus"/>
    <eLiterals name="ABebuNulAuboguTus"/>
    <eLiterals name="AlBubedabuBenulAufrifriBeboEs"/>
    <eLiterals name="BrAunulaugubebiGusius"/>
    <eLiterals name="AlbiGusfrinulaubonulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusboguguNulaugusgubiDanulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fadadator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egugusbeguBibecio" ordered="false" upperBound="-1" eType="//BagusboguguNulaugusgubiDanulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusnulAubeDafriboBofridaBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubugusGusBobuTor" abstract="true" eSuperTypes="//BagusboguguNulaugusgubiDanulautor //DuFriFriBonulaugubugusbudanus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biFribibefribeGusgufrilius" eType="//AuGusAubefriGusbibuguGutor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anBobibebigusbiEs" eType="//DiboBiBinulauBodaBuFrinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabobudanulAuBelus" instanceTypeName="typeBagusbegusfriNulAuBonulauguBunulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebibebebeGusfrinulauguLius" eSuperTypes="//BagusboguguNulaugusgubiDanulautor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diLus" eType="//AuGusAubefriGusbibuguGutor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dobinulaudatus" eSuperTypes="//BagusboguguNulaugusgubiDanulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaubiBigusaucus" eSuperTypes="//BabeGufribibiboBefritus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AndagusgusfriBunulauGubonus" instanceTypeName="typeFabuGusaugusNulaudaBuboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFriboGuNulaubeBeBiboTor" eSuperTypes="//EugusnulAubeDafriboBofridaBicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duDabobuNulaubuBugubetor" ordered="false" upperBound="-1" eType="//DobubibibuBobobitor" eOpposite="//DobubibibuBobobitor/digusgusfribiBobedagusnulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusauBidaboDaguguNulAuLus" eSuperTypes="//EubebibebebeGusfrinulauguLius //BabeGufribibiboBefritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobubibibuBobobitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusgusfribiBobedagusnulius" eType="//BaFriboGuNulaubeBeBiboTor" eOpposite="//BaFriboGuNulaubeBeBiboTor/duDabobuNulaubuBugubetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DodaboBofrigusBeBues" instanceTypeName="typeEnulauBiguBigusfricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulauGulius" abstract="true" eSuperTypes="//DagusauBidaboDaguguNulAuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babeBuDafribubugugusbigusgusNus" ordered="false" eType="//AuNulauFrigubibubonus" eOpposite="//AuNulauFrigubibubonus/duDanulAubuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlAubinulAubufrinulEs" instanceTypeName="typeBebibiGusBibuDabufritor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EboBoboGugusaubebotus" instanceTypeName="typeAubibobenulaubigubobelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dodagusdabodafrifricus" eSuperTypes="//DagusauBidaboDaguguNulAuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubogusBebeGusNulauBitor" ordered="false" eType="//EugusnulAubeDafriboBofridaBicio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duboGusbonulaugusbubucio" eType="//AlBebuBeBebetin" eOpposite="//AlBebuBeBebetin/braudaBifriBifrifribuBuBibebibotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulauDaboBegustin" eSuperTypes="//BabeGufribibiboBefritus //DuFriFriBonulaugubugusbudanus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BagusbofrifribuBogusAugugugulius" instanceTypeName="typeAlNulaufriDafridatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudanulAugubunulaubeBobubunus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusbugusBufrinulaubiBidabilius" ordered="false" upperBound="-1" eType="//DagusauBidaboDaguguNulAuLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBubibuBugubugusfrifriFriguBees" ordered="false" upperBound="-1" eType="//DobubibibuBobobitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Braubunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebefriDaFribubebebilius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babebedaBuBugusNus" ordered="false" upperBound="-1" eType="//BaBufribiFribuboDafritus" eOpposite="//BaBufribiFribuboDafritus/baBigusbiBoDaGubigusdadanules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBufribiFribuboDafritus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBigusbiBoDaGubigusdadanules" eType="//BebefriDaFribubebebilius" eOpposite="//BebefriDaFribubebebilius/babebedaBuBugusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbobinulaubunulaufriCus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudanulaudaboFrigusdatus" upperBound="-1" eType="//EnulauGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGuBoFriBegusNus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doboDagusfriBigusFrigusfrifriBoes" ordered="false" upperBound="-1" eType="//Dobinulaudatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuNulauFrigubibubonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duDanulAubuCio" upperBound="-1" eType="//EnulauGulius" eOpposite="//EnulauGulius/babeBuDafribubugugusbigusgusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DububuBebuDaDabibotus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebebiboDaBofrigubigusnulEs" ordered="false" upperBound="-1" eType="//EbobinulaubunulaufriCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusgugufribenulaugusLus" instanceTypeName="typeAngusGugubiguGusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBubegudafrinulauBidaEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulius" ordered="false" eType="//DagusauBidaboDaguguNulAuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubigusnulaudaguGunules" instanceTypeName="typeBeBonulAunulAubonulauNulaubeDacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaubegusbunulauGusauBilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulaufribuFriguGusdaCus" eSuperTypes="//EnulauGulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AudagusbubidaboGuEs">
    <eLiterals name="A"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Braubogusfridabulus" instanceTypeName="typeEBeguguBoFributus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EubinulauDaBeBiNulauTus">
    <eLiterals name="AguDanulAuGuNulaucus"/>
    <eLiterals name="DugunulAugusbiLius"/>
    <eLiterals name="EubibuFriguFrinulaubuGuBubibiFritor"/>
    <eLiterals name="EuBefriGusgusbibiBigububinules"/>
    <eLiterals name="AuDaGubiBugusBeNus"/>
    <eLiterals name="DuGuBubonulaufriGusFrigusius"/>
    <eLiterals name="EuFrinulauCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAubuBuguBeguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndafriNulaubidaFriDatus" abstract="true" eSuperTypes="//BaFriboGuNulaubeBeBiboTor //BaBufribiFribuboDafritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibubinulAugusauboBubegubotin" ordered="false" eType="//BenulaubegusbunulauGusauBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusnulaubuBefribobitin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBobiBeNulaulius" upperBound="-1" eType="//BabeGufribibiboBefritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaugusbeGusBebudanulauguGudator" eSuperTypes="//EubebibebebeGusfrinulauguLius //EBubegudafrinulauBidaEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuguDaBonulaugusboLius" instanceTypeName="typeAlBoBibuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBobebegusdafrinulauTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBebuBeBebetin" eSuperTypes="//AlnulAubuBuguBeguses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudaBifriBifrifribuBuBibebibotus" ordered="false" upperBound="-1" eType="//Dodagusdabodafrifricus" eOpposite="//Dodagusdabodafrifricus/duboGusbonulaugusbubucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusGusgufridabebefriGusBiBoFriBebibecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobigunulaububedanulauNulaubufriFritin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagunulaubunulaubegusFries" eType="//BagusbofrifribuBogusAugugugulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudabubuBucus" ordered="false" eType="//AuNulauFrigubibubonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaFridanulauGuGusgusEs" abstract="true" eSuperTypes="//EBubegudafrinulauBidaEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuguFriBoGuDaBoBoLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGubibeNulAunulaugutor" abstract="true" eSuperTypes="//BebefriDaFribubebebilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusAuguGusbuboCus" ordered="false" upperBound="-1" eType="//EuGuBoFriBegusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribuNulaufriBeGugusGusfriBiEs" eSuperTypes="//AuNulauFrigubibubonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulaubibubeBogusbodagustin" ordered="false" eType="//BinulaubiBigusaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdafribibefrifribiNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifribibegusFridabuTor" eSuperTypes="//BaFriboGuNulaubeBeBiboTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBeDagusbubegucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldaNulAudaguEs" abstract="true" eSuperTypes="//DububuBebuDaDabibotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBuBigutin" ordered="false" upperBound="-1" eType="//EBubegudafrinulauBidaEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulAuBoNulAudabetus" eSuperTypes="//AldaNulAudaguEs //BaFriboGuNulaubeBeBiboTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusaubibeguFribebutin" eSuperTypes="//DobigunulaububedanulauNulaubufriFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauguguBufridaGusBoBebefribeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGugusgunulauGugusGunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBibuBogufritor" upperBound="-1" eType="//AlNulAuBoNulAudabetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulauBoBibubiNulAubibunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboguboGunulaufridabutin" eSuperTypes="//AndafriNulaubidaFriDatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biDabenulAufrifriTin" ordered="false" eType="//AndafriNulaubidaFriDatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauGusfridaDafridaBefridabenus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diDanulauGusbibeGutus" eType="//DabobudanulAuBelus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbiNulauBuBulus" eSuperTypes="//BebefriDaFribubebebilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaubububiBogusBenulaubogucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGudagubebonulaubotus" upperBound="-1" eType="//EbobinulaubunulaufriCus"/>
  </eClassifiers>
</ecore:EPackage>
