<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bigubuguscus" nsURI="http://hub.de/rcore/examples/bigubuguscus" nsPrefix="CgQkl">
  <eClassifiers xsi:type="ecore:EClass" name="BifribodaDanulaubeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DububinulauBegugusbinulauBulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiBoNulAugugudaBebulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BedaFribubuLus" instanceTypeName="typeEuNulAuNulaubefribolus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EfridanulaunulauguLius" instanceTypeName="typeBabinulauBobufrigubifrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusbiBebenulaufriBedabufrilus" eSuperTypes="//DububinulauBegugusbinulauBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBunulaubibubucio" ordered="false" eType="//BibobubogusbeCus" eOpposite="//BibobubogusbeCus/anulaudagubobeboboguFriFribiBoFritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulaunulauGusNulaufrigusBufrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befriBudabigusbues" ordered="false" upperBound="-1" eType="//AGusbiBebenulaufriBedabufrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AudaNulAuboFridabonulAulus" instanceTypeName="typeAubobibobobocus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbufriBebebigusbiEs" instanceTypeName="typeBabeDaGuDafrinulautus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Braubulus">
    <eLiterals name="DibufribogusAudabeFribuCio"/>
    <eLiterals name="EnulAubiNulAugusgubeFribitus"/>
    <eLiterals name="AnGusaugusbibubobiDagusauguNus"/>
    <eLiterals name="DabubuFribebigusLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobebiBubiFrigubinulauGusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbuNulaubegusBuNulauBobefrifricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABuBobenulaugusbiBulus" eSuperTypes="//DobebiBubiFrigubinulauGusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbonulauFriBiBitor" abstract="true" eSuperTypes="//DugusbuNulaubegusBuNulauBobefrifricio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebebufrigufribebitor" ordered="false" eType="//DububinulauBegugusbinulauBulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusnulAubuguguFrifriNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabuBogusbebeGucio" ordered="false" eType="//DugusbuNulaubegusBuNulauBobefrifricio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBoFriBebibuEs" ordered="false" eType="//DugusbuNulaubegusBuNulauBobefrifricio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daboFriDanulaugusboTor" ordered="false" eType="//BraugugusbeGusbodabutus" eOpposite="//BraugugusbeGusbodabutus/dofrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadaNulaubibuFriCus" abstract="true" eSuperTypes="//DobebiBubiFrigubinulauGusLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusBuGusgusdafribuguFricio" instanceTypeName="typeBaBubiboGubigusgusbelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bidagusgusboes" eSuperTypes="//DububinulauBegugusbinulauBulius //BifribodaDanulaubeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Difrifrifrigusgucio" eSuperTypes="//FaGusnulAubuguguFrifriNus //AnbonulauFriBiBitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EDaGubues" instanceTypeName="typeBibibuBobubeboboboLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbiguBiGusBiGubenulAunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulaufriguGuGuguNulauboNules" eType="//BedaFribubuLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBoGusBobibibuBeTus" eType="//AudaNulAuboFridabonulAulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubiFries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubuDaboNulaufriFriNulauTin" eType="//EfridanulaunulauguLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeNulAubiFriBuboBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaDabedagusbodalus" ordered="false" upperBound="-1" eType="//DugusbuNulaubegusBuNulauBobefrifricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAubibonulAuguguDaes" eSuperTypes="//Bidagusgusboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugusGuTin" eType="//Braubulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeFribonulAubiGubigugubebubebuGufriNulius" eSuperTypes="//BraubeNulAubiFriBuboBolius //AlbiBoNulAugugudaBebulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBeguBidabububofritus" upperBound="-1" eType="//FadaNulaubibuFriCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FadaGuBinulauNulAuBoes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusdafrigugusbibugusLus" eSuperTypes="//EbiguBiGusBiGubenulAunus //BraubeNulAubiFriBuboBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubinulaugusbiBobeBenus" ordered="false" upperBound="-1" eType="//AubiFries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGunulaugubedaEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauNulaudaes" eType="//FadaGuBinulauNulAuBoes" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusfrigufriBobidaFrigusAubues" ordered="false" eType="//BeNulaunulauGusNulaufrigusBufrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bigugunulaubutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabibuNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aguFrigusBuGuNulaugusdaLius" upperBound="-1" eType="//AnbonulauFriBiBitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauBeDaboGusFries" eSuperTypes="//DububinulauBegugusbinulauBulius //ABuBobenulaugusbiBulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeDabeFribenules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibobubogusbeCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aDagusdafribenules" eType="//Braubulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digubunulAububebuLus" eType="//DogusBuGusgusdafribuguFricio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulaudagubobeboboguFriFribiBoFritus" ordered="false" upperBound="-1" eType="//AGusbiBebenulaufriBedabufrilus" eOpposite="//AGusbiBebenulaufriBedabufrilus/baBunulaubibubucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAufriBubobidagudalus" ordered="false" upperBound="-1" eType="//EunulauBeDaboGusFries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulAuDanulAudacus" eSuperTypes="//DugusbuNulaubegusBuNulauBobefrifricio //ABuBobenulaugusbiBulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugugusbeGusbodabutus" eSuperTypes="//BeNulaunulauGusNulaufrigusBufrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofrilus" ordered="false" eType="//FaGusnulAubuguguFrifriNus" eOpposite="//FaGusnulAubuguguFrifriNus/daboFriDanulaugusboTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAuBoboGubuguslus">
    <eLiterals name="BiGusBububugugusBunulAuBoCio"/>
    <eLiterals name="AnbuBuBogusfrigusius"/>
    <eLiterals name="BiFribuBugulius"/>
    <eLiterals name="DubuFribedadagusBegusBonulaudator"/>
    <eLiterals name="AlbeBubinulauNulEs"/>
    <eLiterals name="BenulauNulius"/>
    <eLiterals name="Annulaufries"/>
    <eLiterals name="Binulaubofritor"/>
    <eLiterals name="BabifrigufriBubuGubebigubicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulaunulauFriguguslius" abstract="true" eSuperTypes="//FadaNulaubibuFriCus //AGusbiBebenulaufriBedabufrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudaDabiguNulaugugusfribubibobilus" eSuperTypes="//BraubeNulAubiFriBuboBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBunulaubibugusAufribiNus" eSuperTypes="//AlbiBoNulAugugudaBebulius //AGusbiBebenulaufriBedabufrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbeFriNulaubuTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaubonulaunulAubugugusgusLius" ordered="false" upperBound="-1" eType="//DanulAubibonulAuguguDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuguDabubebobigusbuTin" eSuperTypes="//DaBunulaubibugusAufribiNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebiBifribodaTus" ordered="false" upperBound="-1" eType="//FadaNulaubibuFriCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaFrinulAudabinulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnAubudaguGuNulauCio" eSuperTypes="//AgusdafrigugusbibugusLus"/>
</ecore:EPackage>
