<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dudagusgutus" nsURI="http://hub.de/rcore/examples/dudagusgutus" nsPrefix="L">
  <eClassifiers xsi:type="ecore:EClass" name="AudaGusFriBubibiFribugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGunulauFridaguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusbedanulaufribifriLius" abstract="true" eSuperTypes="//AnGunulauFridaguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aubebefritin" eSuperTypes="//BraugusbedanulaufribifriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebofridanulaudaguFriLius" abstract="true" eSuperTypes="//AnGunulauFridaguLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BefriDabiFribiboboBibebelius" instanceTypeName="typeBegusbegusFribenulauBebiFricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudabonulaudagusgusaubibeTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulAufritor" ordered="false" upperBound="-1" eType="//AudaGusFriBubibiFribugutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibububiFrifriGubuFridafrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabiGusgusbububoboBobutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabibibedaGusgudaBegunulaubegusius" ordered="false" eType="//BraugusbedanulaufribifriLius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euboBugustus" eType="//BefriDabiFribiboboBibebelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabobuGusbegusdadabobogusbucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibefribobodaBegusbiFrinulaunus" eSuperTypes="//Aubebefritin //EubebofridanulaudaguFriLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbobuBuBobubobuLius" ordered="false" eType="//AudaGusFriBubibiFribugutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibidaBebuDaBucio" ordered="false" eType="//BibububiFrifriGubuFridafrinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dububidabubudaDabofriBobuGustus" ordered="false" eType="//BraugusbedanulaufribifriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuDagusfriGubibodanulauBuFrinulIus" eSuperTypes="//AnGunulauFridaguLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulauBiDatin" ordered="false" eType="//EudabonulaudagusgusaubibeTin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobebobobubuguBibogustin" eType="//BefriDabiFribiboboBibebelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AububuBubibilus" eSuperTypes="//EudabonulaudagusgusaubibeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabuBobunulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugunulAuBudaGugubinulauCio" eSuperTypes="//EubebofridanulaudaguFriLius //BraugusbedanulaufribifriLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbuNulAugusGugudaes" eType="//BefriDabiFribiboboBibebelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobibeFrinulauNulaunus" eSuperTypes="//DabuBobunulauNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albuBubuGubicio" eType="//BefriDabiFribiboboBibebelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebefriBibuGusbobugudaBiTor" eSuperTypes="//AudaGusFriBubibiFribugutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badagues" ordered="false" eType="//BraugusbedanulaufribifriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBibibogusfribiFribeLus" abstract="true"/>
</ecore:EPackage>
