<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="altin" nsURI="http://hub.de/rcore/examples/altin" nsPrefix="pz">
  <eClassifiers xsi:type="ecore:EClass" name="AuboBoBegusbobibodaFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnguguNulauFrigubeBuGusbiGubelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBiboguboGusbutor" eType="//AuboBoBegusbobibodaFritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauGusNulAunulAutin" eSuperTypes="//AnguguNulauFrigubeBuGusbiGubelus //AuboBoBegusbobibodaFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadaguguBigusaunulaubegudalus" eSuperTypes="//BinulauGusNulAunulAutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebobogugubodaBobocio" ordered="false" upperBound="-1" eType="//AnguguNulauFrigubeBuGusbiGubelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulAunulaufriboboLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusFrifribugunulAucio" ordered="false" eType="//DibeDaGusboBubeBuBugufricus" eOpposite="//DibeDaGusboBubeBuBugufricus/agusboBebuboGufriGuslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusbeFriboNulaubegusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABobubobefributus" abstract="true" eSuperTypes="//AuboBoBegusbobibodaFritin //AnguguNulauFrigubeBuGusbiGubelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusBogusbiGusBeBobubuTor" ordered="false" eType="//DadaguguBigusaunulaubegudalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BedabebeBuBubuBitor" instanceTypeName="typeEfrigusauNulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubegubegusBobotus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duDabebobetin" eType="//BedabebeBuBubuBitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraunulaubinulAuDatin" instanceTypeName="typeDaBinulauboDanulAutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbifribobidafriBeboGutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusfrigufridadabiNulaudaNus" eSuperTypes="//AngusbeFriboNulaubegusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudabibufriBufribubiBobeFricio" eSuperTypes="//AlGusfrigufridadabiNulaudaNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DoDanulaufriBibucus">
    <eLiterals name="AGunulAubudaboDafribubuLius"/>
    <eLiterals name="ABuboBiNulauguBuCio"/>
    <eLiterals name="BinulauBubiGusgutus"/>
    <eLiterals name="BrAugusaugusfriBubeFribinus"/>
    <eLiterals name="AnBeGubebuNulAuBifribufribifrifritor"/>
    <eLiterals name="BiNulAuBiFricio"/>
    <eLiterals name="AnfriBegusfribuGububinulauguscio"/>
    <eLiterals name="DoBugusAugusdaTor"/>
    <eLiterals name="EbubiDaFridaguNulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagubudabodaBuguBetus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabiGuBodagusfrilus" instanceTypeName="typeDibonulAuGusAuGubutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADabeGusDabuBitor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBugusbuguFridabibubidafriNus" ordered="false" upperBound="-1" eType="//DadaguguBigusaunulaubegudalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBoGusnulaugusnulAuDadalius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBigufrinulauBiBibogubitin" upperBound="-1" eType="//AlGusfrigufridadabiNulaudaNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobobigugusboBuFriBunulAubigusdanus" ordered="false" upperBound="-1" eType="//ABobubobefributus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dunulaudabobibefrigugubedaes" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulauBegusbudaDanulAubutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibeDaGusboBubeBuBugufricus" eSuperTypes="//ABobubobefributus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusboBebuboGufriGuslus" ordered="false" eType="//EuNulAunulaufriboboLius" eOpposite="//EuNulAunulaufriboboLius/eugusFrifribugunulAucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DibugunulAufribuGusaubiguDaBebilus">
    <eLiterals name="BebigudaNulauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DogusfribidanulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibobebobuboTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafriGusBidadafridagusaubebiLus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Dubobufritus">
    <eLiterals name="AngubiguGusgubogugububulus"/>
    <eLiterals name="DiFribinules"/>
    <eLiterals name="ABubofriFribobeBiGusauCio"/>
    <eLiterals name="BrauGubofrinulautus"/>
    <eLiterals name="BibeNulauNulaufribelius"/>
    <eLiterals name="BraubuguNulAuBoDagubedaguLius"/>
    <eLiterals name="FafriboboNulAubulius"/>
    <eLiterals name="AnnulauFrigusNulAulus"/>
    <eLiterals name="ABibebobifrinulauGudaBies"/>
    <eLiterals name="Didagugusnulautin"/>
    <eLiterals name="ABefridabibiNulaugusfribuLus"/>
    <eLiterals name="DobebiGusGusgusGubebobuguBuguEs"/>
    <eLiterals name="DadaBonulAubeboboFrifridagues"/>
    <eLiterals name="AlnulAubebeBufribegubuLius"/>
    <eLiterals name="AlfribibuFriGudanulauDaBofritus"/>
    <eLiterals name="ANulAuBuGusbiFrigutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufribidagusauBiBobucus" eSuperTypes="//AnulauBegusbudaDanulAubutin //ABobubobefributus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodadabebibiBudator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusauDadagunulAuBeBigusDator" eSuperTypes="//DadaguguBigusaunulaubegudalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubodaBoDaguDafridanulius" eType="//AlGusfrigufridadabiNulaudaNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbuNulAuGusAubetor" instanceTypeName="typeBibobuBunulaunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fabigubutus" eSuperTypes="//DafriGusBidadafridagusaubebiLus //EbifribobidafriBeboGutor"/>
</ecore:EPackage>
