<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algusbonules" nsURI="http://hub.de/rcore/examples/algusbonules" nsPrefix="D">
  <eClassifiers xsi:type="ecore:EClass" name="BrAubufrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusbibubebefriBifriBodanus" eSuperTypes="//BrAubufrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafrinulaufriGusfrinules" ordered="false" upperBound="-1" eType="//BrAubufrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EguNulaufriboBugugusgues" abstract="true" eSuperTypes="//BrAubufrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAunulauGusbuBibugusCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaunulaububibeBuLus" eSuperTypes="//EguNulaufriboBugugusgues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribunulaubogusBeboGuLus" eSuperTypes="//BrAubufrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaugunulAubebefrinulautus" eSuperTypes="//DiGusbibubebefriBifriBodanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaDaBiBoGusBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabonulaubebobuTor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DabiBedaBeGusbogusbobeDaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusgusNulaudabegusgugubutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbodagusaugusCus" eSuperTypes="//FabonulaubebobuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBibugusGugubiFribuTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Audadagucio" eSuperTypes="//AnulaunulaububibeBuLus //FanulAunulauGusbuBibugusCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dafrinulaubies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAubugubiGuBigusbogusTor" eType="//DabiBedaBeGusbogusbobeDaNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnboGuBebudadagusbuguslius" instanceTypeName="typeBebeguGunulautin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaguBoNulaububeNulaubees">
    <eLiterals name="FaNulaugubodabegutin"/>
    <eLiterals name="AfriguBebebodabofribuBegunulAunules"/>
    <eLiterals name="Alnulaugusdabubebubebebucus"/>
    <eLiterals name="EfribodadaGusAubofrinulius"/>
    <eLiterals name="BegugudagusbogusgubibugunulEs"/>
    <eLiterals name="FagusnulaubeDafrinulaugusfridanus"/>
    <eLiterals name="EufridagufriDabudafritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BiguDanulAuGunulautus" instanceTypeName="typeFaGusBiNulAuBoBeBeBenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlAuGuGuGunus" eSuperTypes="//BrAubufrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobuGuNulaufrigusbuBetor" ordered="false" upperBound="-1" eType="//FaDaBiBoGusBitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAugusbibedaGusnulaugulius" instanceTypeName="typeDafribeBiBenulaubugusbeGusius"/>
</ecore:EPackage>
