<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anaubofritor" nsURI="http://hub.de/rcore/examples/anaubofritor" nsPrefix="tSO">
  <eClassifiers xsi:type="ecore:EDataType" name="FabeFrifriDanulaubobubebegusTor" instanceTypeName="typeBiBeBebuNulauGusBobunulAuBibotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGusnulAubidagusnules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulAuGugusNulauNulauNus" ordered="false" upperBound="-1" eType="//DuBuBubebibubinulauGusBibibeLius" eOpposite="//DuBuBubebibubinulauGusBibibeLius/alBebubigusbuGuboBufribunulAunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobogubeboGugusBogutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBuBubebibubinulauGusBibibeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBebubigusbuGuboBufribunulAunulEs" ordered="false" eType="//EGusnulAubidagusnules" eOpposite="//EGusnulAubidagusnules/benulAuGugusNulauNulauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeguBifriBubebefriBeBetus" instanceTypeName="typeDogubibobeguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubuBefribeDabeDabuboBoes"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABiBogusgusnulauBeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauboguBufriBobeGugusgubigubugusTor" abstract="true" eSuperTypes="//DobogubeboGugusBogutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubogusgugusAugusbiGusBuboNulius" ordered="false" upperBound="-1" eType="//DiGugusfrigusbeFrinulAunulAugusBodaTor" eOpposite="//DiGugusfrigusbeFrinulAunulAugusBodaTor/dabifribiBiBubiDadaBues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuguBeguDaGusBocio" eSuperTypes="//AubuBefribeDabeDabuboBoes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabunulAugunulEs" eType="//DobogubeboGugusBogutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadagusdaBuFriNulAubutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubebinulaufrigubegusBidaBolus" abstract="true" eSuperTypes="//EuguBeguDaGusBocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusdaboBuBoGucus" eSuperTypes="//DobogubeboGugusBogutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidadaEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubuBeBugugubebeGusfrifribudaguboBulus" eSuperTypes="//DiGusdaboBuBoGucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daNulauBobifrilus" ordered="false" upperBound="-1" eType="//AubuBefribeDabeDabuboBoes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusDadabifribiNulAunulAuNus" abstract="true" eSuperTypes="//BrauboguBufriBobeGugusgubigubugusTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babibigubuBobegunulaucus" ordered="false" upperBound="-1" eType="//BrauboguBufriBobeGugusgubigubugusTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGugusfrigusbeFrinulAunulAugusBodaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabifribiBiBubiDadaBues" ordered="false" upperBound="-1" eType="//BrauboguBufriBobeGugusgubigubugusTor" eOpposite="//BrauboguBufriBobeGugusgubigubugusTor/eubogusgugusAugusbiGusBuboNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Eufridagububebibebibicio" instanceTypeName="typeEubububifridadaBudaBeBiFrinulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiboDabiBolus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulaugubeNulAuGuBiBuGuTor" ordered="false" upperBound="-1" eType="//ABiBogusgusnulauBeLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algubiboDanulauGusgubifritin" ordered="false" eType="//AubuBefribeDabeDabuboBoes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BagusGubedagulus" instanceTypeName="typeDagufrifridabuguTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbugufridaGunulauguboDabibuBucio" eSuperTypes="//DiGugusfrigusbeFrinulAunulAugusBodaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBibeGusfrinulaucus" ordered="false" eType="//EubuBeBugugubebeGusfrifribudaguboBulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbedaBifribidaNulius" eSuperTypes="//DubebinulaufrigubegusBidaBolus //DiboDabiBolus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabiBuNulaunulaugusTus" upperBound="-1" eType="//FabeFrifriDanulaubobubebegusTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulAufribubiBebobotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dadagusauguGugubuCus" eType="//BagusGubedagulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBuguDagusdagusgusbicio" instanceTypeName="typeAlBobubobubiEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusdaNulaubuGubogusaufriFrigufrifriBunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubuNulauguguGuguBoDabubeCio" eType="//DidadaEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusDabebeNulaunulaubobeBuNulaubuLus" eSuperTypes="//AubuBefribeDabeDabuboBoes //BrauboguBufriBobeGugusgubigubugusTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulAugusDatin" eType="//BagusGubedagulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EBibuFriboNulaubifrilius">
    <eLiterals name="FabenulaudaBiFriFribubugusBefritin"/>
    <eLiterals name="AudabonulAuDagudafrifrigusBigufrinules"/>
    <eLiterals name="FabodabigusdabugusnulAugusBidabinus"/>
    <eLiterals name="AnulauFriGububolus"/>
    <eLiterals name="DugubugudanulauGusBegusbufrifriFrigusguLius"/>
    <eLiterals name="AbogugusbubeBubiBeGuBonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBibegusfriFrinulEs" eSuperTypes="//EuguBeguDaGusBocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daguBuGusbobuBeBuGusbicus" eType="//DidadaEs"/>
  </eClassifiers>
</ecore:EPackage>
