<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dibibues" nsURI="http://hub.de/rcore/examples/dibibues" nsPrefix="b">
  <eClassifiers xsi:type="ecore:EClass" name="BabeBoFribenus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbiNulaudabenulAuguNus">
    <eLiterals name="DoNulauNulauGusnulaugusbuGusTin"/>
    <eLiterals name="BidaBedadaBidaboTus"/>
    <eLiterals name="AldaBuDanulius"/>
    <eLiterals name="Dagubigusaubigugugusgusnus"/>
    <eLiterals name="DaGusAuguBiBuGugubibenus"/>
    <eLiterals name="EDadabeGubodanulAuGuslus"/>
    <eLiterals name="DibobibegubigusgusBies"/>
    <eLiterals name="Fadanulaubufricio"/>
    <eLiterals name="EBobiBuBonulaudaNulEs"/>
    <eLiterals name="AnbubebobuBeBoGugusbibegufrinulius"/>
    <eLiterals name="Eunulaubegusbobobenulaucio"/>
    <eLiterals name="BibigusbibiboBies"/>
    <eLiterals name="Ebufrilus"/>
    <eLiterals name="EBifriGusAuFriBidalius"/>
    <eLiterals name="AlAubidabiGusAuGufribolus"/>
    <eLiterals name="Ebebububibodafriboguslus"/>
    <eLiterals name="AndabegusnulaufriboDaCus"/>
    <eLiterals name="AuGusFribuGusFriBiGusGusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAubuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daNulAuBufridalius" ordered="false" eType="//BabeBoFribenus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beDabiEs" eType="//AnbiNulaudabenulAuguNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FagusboBefrigusauBecus" instanceTypeName="typeAunulaubuNulauguboboNulauTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADaGubunulaugudaGudadanulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulAubiboDaGusBibiGuFributor" eSuperTypes="//ADaGubunulaugudaGudadanulautus //DunulAubuLus //BabeBoFribenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusGusauFrifritor" eSuperTypes="//DunulAubuLus //ADaGubunulaugudaGudadanulautus //BabeBoFribenus //DonulAubiboDaGusBibiGuFributor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dinulAuguBodanulaunulAubefriLus" eType="//FagusboBefrigusauBecus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeDadadagugugusNulaufribues" eSuperTypes="//BabeBoFribenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGubenulAuDalius" eSuperTypes="//BeDadadagugugusNulaufribues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbinulaubibeFribeDacus" eSuperTypes="//ADaGubunulaugudaGudadanulautus //BaGubenulAuDalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiBebogusauDadaFrifrigusdabocio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogugunulAudaguboGuBitor" instanceTypeName="typeBaDaGugusaugusaubebebuBicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubeBoDaBiFriTor" eSuperTypes="//AbinulaubibeFribeDacus //DonulAubiboDaGusBibiGuFributor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaguGusgusaufriBeguBifriFribogusbugusTor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusBegusDabudaBiboBogusfricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGusbigunulAuBues" ordered="false" eType="//DunulAubuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoNulaunulaubeBodabuGucus" instanceTypeName="typeAlnulaubebuBobubudaGusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebebiGusBubefribuboBogucio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DoGunulaunulaubegusCus">
    <eLiterals name="FanulAuGusBoBilius"/>
    <eLiterals name="AnBuBuFrigusNulauboes"/>
    <eLiterals name="AlGusgusBefrilus"/>
    <eLiterals name="EuNulaugusauDaBiDadabenulIus"/>
    <eLiterals name="AnBidagusgustus"/>
    <eLiterals name="EudadaGusboGusAutor"/>
    <eLiterals name="DabeboBudabedanulEs"/>
    <eLiterals name="EubeBobeDadabugudadadanulaudabenulauboCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebudanulaubodaBobebeguBudabeguscio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngubiGusbibedanulAuNus" abstract="true" eSuperTypes="//AnbiBebogusauDadaFrifrigusdabocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgubuDanulAufriNulAubobebuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bifriguDagubenus" eType="//AnbiNulaudabenulAuguNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbogusfrigutin" eType="//DogugunulAudaguboGuBitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FadaFrinulaudaGusEs" instanceTypeName="typeFafriFrigusbotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebobeboLius" eSuperTypes="//AnbiBebogusauDadaFrifrigusdabocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabeNulAubugubucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriGusfriNulauBoLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algudafrigusTor" eType="//FadaFrinulaudaGusEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGusDabibefribugubibuLus" ordered="false" upperBound="-1" eType="//BaGubenulAuDalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibugunulAuFrigusnulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusAuboboNulaufridacus" eSuperTypes="//BrAubeBoDaBiFriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribogusbigusdagusfrigusguBonulEs" ordered="false" upperBound="-1" eType="//EubebobeboLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubifribiGubiDabubenus" abstract="true" eSuperTypes="//BaguGusgusaufriBeguBifriFribogusbugusTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albonulauBeBibiDabeBegubeBetin" ordered="false" eType="//DunulAubuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbubifrifriFribiBeFrilus" abstract="true" eSuperTypes="//BaguGusgusaufriBeguBifriFribogusbugusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBegusbidaBuBebuguTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albubobifribeDabutus" upperBound="-1" eType="//BeDadadagugugusNulaufribues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubibeBinulaubeFricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBegusBeFridaBubuNulaubunulaulus" ordered="false" upperBound="-1" eType="//DibugunulAuFrigusnulaunus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dudabubibebotor" eType="//AnbiNulaudabenulAuguNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anaugusbegufrifrinus" eSuperTypes="//AbubifrifriFribiBeFrilus //ADaGubunulaugudaGudadanulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufrifriBubonulaubobunules" ordered="false" eType="//DabeNulAubugubucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibebubobuNulAugusCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuFriBiboboBibiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBoDabobeguDagusBubies" eSuperTypes="//AlgubuDanulAufriNulAubobebuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aufriDabubobonulEs" eType="//AnbiNulaudabenulAuguNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="au" ordered="false" upperBound="-1" eType="//EubefriGusfribodaBotin" eOpposite="//EubefriGusfribodaBotin/duboguBifribonulauboBibofries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboFriBibofriTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifrigunulaunulaugulius" ordered="false" upperBound="-1" eType="//Anaugusbegufrifrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubigusaubodaFrigusbiBees" abstract="true" eSuperTypes="//DabeNulAubugubucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulAuBeboBoGuFriBiBugusgusgustor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beDagusAugusbubudabenus" eType="//DoNulaunulaubeBodabuGucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubefriGusfribodaBotin" eSuperTypes="//BaGubenulAuDalius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duboguBifribonulauboBibofries" eType="//BaBoDabobeguDagusBubies" eOpposite="//BaBoDabobeguDagusBubies/au"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubegusfriBonulaubitor" ordered="false" eType="//BebebiGusBubefribuboBogucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAubiNulauBoNulAuBedadanulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBoBobidaguBegusbubebobeBiBebiDacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudabugusaugusLus" eSuperTypes="//ADaGubunulaugudaGudadanulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusdadabuBubiFrigusbubelius" ordered="false" upperBound="-1" eType="//DubifribiGubiDabubenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulauGuBobiGusNulAutor" eSuperTypes="//BeDadadagugugusNulaufribues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusgugusdaGusDanus" ordered="false" upperBound="-1" eType="//BigubebedadaBobunus" eOpposite="//BigubebedadaBobunus/anGuboDadabeBuBeBunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifriguBeDaDacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edagusaugusBebibefribucus" eType="//DoNulaunulaubeBodabuGucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EboBogusfriBenulAugusaunulaugubonulEs" eSuperTypes="//EudabugusaugusLus //AbinulaubibeFribeDacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigubebedadaBobunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGuboDadabeBuBeBunus" ordered="false" eType="//BiNulauGuBobiGusNulAutor" eOpposite="//BiNulauGuBobiGusNulAutor/fagusgugusdaGusDanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnGusdabuDafrigusDadabogusbuBonulIus" instanceTypeName="typeAnaubiNulAugusBeFribuguBees"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusgubeBuguBuNulaubunulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauGusnulauCio" instanceTypeName="typeDobuDabubogusgusGuFrinulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBibugusnulauNulAunus" eSuperTypes="//DibugunulAuFrigusnulaunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBobubues" eType="//DoGunulaunulaubegusCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudagusGubeBubitin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begubeLius" eType="//DogugunulAudaguboGuBitor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euBebuFriFribiBegusnus" eType="//FagusboBefrigusauBecus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfrigunulAudaNulAubobebiBoDaLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befriFrinulAuBocus" ordered="false" upperBound="-1" eType="//BebudanulaubodaBobebeguBudabeguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaufribogusdaBofriCus" eSuperTypes="//AngubiGusbibedanulAuNus //AuFriBiboboBibiCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobifrinulauBebifrinus" eType="//FaNulAuBeboBoGuFriBiBugusgusgustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlAuBeGusBigusguBobubinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fagubibudalius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebebebodabefribeBetus" eType="//AnbiNulaudabenulAuguNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBuguBeDanulAuBuCus" instanceTypeName="typeAbobeBenulauNulauguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulauGusguBifriDabuguboLus" eSuperTypes="//EubefriGusfribodaBotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribeDabonulaugufribucio" eType="//DubigusaubodaFrigusbiBees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeguBuBunulaubobeguEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBugusgusnulauboNulaucio" ordered="false" eType="//BebebiGusBubefribuboBogucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboNulaunulaugusbiBuCus" eSuperTypes="//BeDadadagugugusNulaufribues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiFribobofriNules" ordered="false" upperBound="-1" eType="//DufriGusfriNulauBoLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="audadaboBugusgugusgusdadabuGufrifritin" ordered="false" eType="//DonulAubiboDaGusBibiGuFributor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobuDabiGuBobeBebufricio" eSuperTypes="//AngubiGusbibedanulAuNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="e" eType="//AnGusdabuDafrigusDadabogusbuBonulIus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGusnulauguscio" ordered="false" eType="//BiNulauGuBobiGusNulAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlAubiBedagubeboGuscio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuBubigugufriBudatin" eType="//AnGusdabuDafrigusDadabogusbuBonulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBiboDabidaGusbiGusaubeBubulius" eSuperTypes="//EudabugusaugusLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anAudaBifriboBiBobububocus" eType="//FagusboBefrigusauBecus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auBuBoFribidaGusbiBiguTin" eType="//AnbiNulaudabenulAuguNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Difrigusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusdabobuGusgusbeBeguBubibuboFribubunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fanulaubunulaunulEs" eType="//DoNulaunulaubeBodabuGucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbodaguBoBeCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusBonulAubiTor" ordered="false" upperBound="-1" eType="//BaBoDabobeguDagusBubies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusauFridabulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubiBoBodafribebebutus" upperBound="-1" eType="//AlgubuDanulAufriNulAubobebuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulaubofriGusgusgububidagulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auboBedaCus" ordered="false" eType="//DufriGusfriNulauBoLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfrigusgusauDaboguBoFriGustin" abstract="true" eSuperTypes="//BebebiGusBubefribuboBogucio //AnbodaguBoBeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebebunulauGuscio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dofriBeNulaubenules" eType="//DoGunulaunulaubegusCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadafrifriNulaunules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diNulauNulaunulauLius" eType="//FagusboBefrigusauBecus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGubobiBoGusbuguguNulIus" ordered="false" upperBound="-1" eType="//Anaugusbegufrifrinus"/>
  </eClassifiers>
</ecore:EPackage>
