<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="becio" nsURI="http://hub.de/rcore/examples/becio" nsPrefix="elw">
  <eClassifiers xsi:type="ecore:EDataType" name="DuNulaubeFriBifribunulaulus" instanceTypeName="typeBrauGusdaBubeGusfriNulaubibefribilus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DuBufriBobibifriDagulus">
    <eLiterals name="DuBifrigusbiguslus"/>
    <eLiterals name="FabodadaBoNulaubobuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EunulauFrinulaubulius" instanceTypeName="typeDadabigugusfriboDaguFrinulAubenulauBuguTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfribiBoBoNulauBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiFribiboDafrinulAuBibebeDafribuboguscus" eSuperTypes="//AnfribiBoBoNulauBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabiboFrinulaubiBuBunulAuNus" eSuperTypes="//BiFribiboDafrinulAuBibebeDafribuboguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuDafriBobegusfriTus" eSuperTypes="//FabiboFrinulaubiBuBunulAuNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnaugusdaNulauNules" instanceTypeName="typeBraudaNulAuGusbunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusDabeNulAugusdagutor" abstract="true" eSuperTypes="//AnfribiBoBoNulauBolius //EuDafriBobegusfriTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abuBenulaunulauTus" ordered="false" upperBound="-1" eType="//AnfribiBoBoNulauBolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfridaBefriguCio" ordered="false" eType="//FabiboFrinulaubiBuBunulAuNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eu" eType="//EuDafriBobegusfriTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGubofrigusbedaBuboDabudabiBibiCus" ordered="false" eType="//FabiboFrinulaubiBuBunulAuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauFrigusbifriNulaufridaGubues" instanceTypeName="typeDifrigugusbedagusbonulAunulauDalus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BebeNulaubigubugusBeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBubonulIus" eSuperTypes="//BiFribiboDafrinulAuBibebeDafribuboguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFriFriDabubolius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuboboNulAubuBucio" instanceTypeName="typeAufrinulaubeNulaufribiboTus"/>
</ecore:EPackage>
