<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eu" nsURI="http://hub.de/rcore/examples/eu" nsPrefix="AMkN">
  <eClassifiers xsi:type="ecore:EClass" name="FanulaugusbogusaugusgusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusbobuBufriNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfribuGunulAufriFricio" upperBound="-1" eType="//FanulaugusbogusaugusgusTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulaububigunulauTor" ordered="false" eType="//FanulaugusbogusaugusgusTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebububoNulaunulautor" eType="//FanulaugusbogusaugusgusTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBibeBiDaBuBecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabobufribofribigusBetus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeboDaBefriDaDafriFriCio" instanceTypeName="typeBedaGubiFribuboGunulAuCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBenulAugufrifrinulaubebibunules" instanceTypeName="typeADagubuFridadalius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Babedadagucus" instanceTypeName="typeDuBebifrifribenulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Da" abstract="true" eSuperTypes="//DabobufribofribigusBetus //EugusbobuBufriNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dubifribodabinulaubolus" eSuperTypes="//DiBibeBiDaBuBecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Fabifridadagusgufribenus" instanceTypeName="typeBabedanulaubebobeboGuFribicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabugufriBigudagusNulAubodagustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abuDaBuNules" ordered="false" eType="//FanulaugusbogusaugusgusTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauFriFriBidabobiNulautus" ordered="false" upperBound="-1" eType="//DabobufribofribigusBetus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albubugusgubiguscus" ordered="false" eType="//DiBibeBiDaBuBecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DuGusfribiBogufrifritin">
    <eLiterals name="EbugusnulAuFrinulaulius"/>
    <eLiterals name="AbebuBobubees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BadabogusfriBobeguBoBeNulAutin" instanceTypeName="typeBibubobuguDabeGusdabunulAubibotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DidaBuBeBebonulaunulauguTin" instanceTypeName="typeEbebenulaubiFribubobeguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboBoBibinulaunus"/>
</ecore:EPackage>
