<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albegudatus" nsURI="http://hub.de/rcore/examples/albegudatus" nsPrefix="EPYk">
  <eClassifiers xsi:type="ecore:EClass" name="AnAugunulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAugubodatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angufrigububeguscus" upperBound="-1" eType="//AnAugunulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusaufriguBuguBuBogufrigusBibunus" ordered="false" upperBound="-1" eType="//AnAugunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBufriBeBenus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubobeboBucio" instanceTypeName="typeBafrigusgusfriboDaBugunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrinulaubinulauDadafricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobelius" eSuperTypes="//DiBufriBeBenus //DuFrinulaubinulauDadafricus //AnulAugubodatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeboBegugusbibobenulaunulAuGusnulIus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Daboguscio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaGubebuGububigutor" instanceTypeName="typeDadabibifries"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaufriguGusgusdabotin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BifribugusbebububeCus" instanceTypeName="typeBaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubunulaudagusBonulAufrigutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubifriGusAuNulauBogubetin" ordered="false" eType="//DiBufriBeBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauBuBiguBuGusdaguBinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulauGusaubefriLus" ordered="false" upperBound="-1" eType="//AunulaufriguGusgusdabotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGugusGusboDabeBugusBuFriNulautus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubegusBoBobocus" instanceTypeName="typeFaBebunulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbubuguguFrinulauDaes" abstract="true" eSuperTypes="//DuFrinulaubinulauDadafricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubebigugusgusauNus" ordered="false" upperBound="-1" eType="//AnAugunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubiBodadaguGubidaNulAuBobetor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiFriBegusAubobobiTor">
    <eLiterals name="AnfribubuBifribuGusBucio"/>
    <eLiterals name="EBiBigubunulauBefriguBegunulius"/>
    <eLiterals name="EubiDabobeguBeGubufriGuGuscio"/>
    <eLiterals name="DuBuGubudanulAudalus"/>
    <eLiterals name="BiGusbinulAugusguNulaububeBelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbonulauguBinulAubobuFriTor">
    <eLiterals name="FafriGubuGusnulauFriBunulius"/>
    <eLiterals name="DifrifriNulaugusbebuBenulAunus"/>
    <eLiterals name="DoNulaunulauguBifriguBucio"/>
    <eLiterals name="AlnulAubibinus"/>
    <eLiterals name="FaBuguboBiBoBugusius"/>
    <eLiterals name="FabidaFrinulauLius"/>
    <eLiterals name="BeGufribifriDaNules"/>
    <eLiterals name="BaBubiGugusnulAucio"/>
    <eLiterals name="DadaDanus"/>
    <eLiterals name="BrauguGusBoNulauBobeNus"/>
    <eLiterals name="AugufribiNules"/>
    <eLiterals name="BenulaugufriGudaFrigusboCio"/>
    <eLiterals name="DufriBogufrilius"/>
    <eLiterals name="BagubebuDanules"/>
    <eLiterals name="Digusgunulaudabebelus"/>
    <eLiterals name="EgusfriGunulAubudabebuBodatin"/>
    <eLiterals name="DoFribedaGugusbedabubiBonulAulius"/>
    <eLiterals name="AnfrifrifribibobudaBicus"/>
    <eLiterals name="DubogubiBobedafriDabudaCus"/>
    <eLiterals name="DiGusbidafribegufribiNulauNulauDanulAufritus"/>
    <eLiterals name="EugusDagusgusnulaugusbicio"/>
    <eLiterals name="DobofriguBiBonulaunules"/>
    <eLiterals name="BraugusAuNulaubuNulauCus"/>
    <eLiterals name="EuNulAuGuBeTus"/>
    <eLiterals name="BibuGusBeBedaFriGubobonulaubebuLius"/>
    <eLiterals name="AnbodafribubebeboguBobobiBofriEs"/>
    <eLiterals name="EgusdabufrifriBoBugufrinulius"/>
    <eLiterals name="DaGusgudanulauGusNulAuBubuGusNulAugusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabeGuBidaNulaufricus" eSuperTypes="//DubunulaudagusBonulAufrigutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeBibuFrifriBuGugusButus" instanceTypeName="typeAlboGudagunulAudaGusnulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnboguBedagunulauGusbedabecio" instanceTypeName="typeDogusdaguGuBotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabibefriGusbifrigusfrigustor" eSuperTypes="//BeboBegugusbibobenulaunulAuGusnulIus //Dobelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebuBegubebuguNulaubifrifriFridatin" ordered="false" eType="//EbubuguguFrinulauDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusBubebeBugusAuBolus" eSuperTypes="//AnulAugubodatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faNulAuBeBiBoboguBebobelus" ordered="false" eType="//DubunulaudagusBonulAufrigutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoDabinulauBuFriBugusbubonules" eSuperTypes="//BeboBegugusbibobenulaunulAuGusnulIus //AnAugunulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DibobuGusguNulauNulaulus" instanceTypeName="typeDufriGuBeFridanulEs"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaBefriBudagusbegusnules">
    <eLiterals name="DuBegububobilius"/>
    <eLiterals name="EbunulaubegusBofribidaTor"/>
    <eLiterals name="AlBibigudaGusguslus"/>
    <eLiterals name="BaBobinulauFriBubofrigusnulautin"/>
    <eLiterals name="AufribonulaugusdabuBidaNulEs"/>
    <eLiterals name="DaFriBobudaCio"/>
    <eLiterals name="DaBibuBoTin"/>
    <eLiterals name="FanulaugusAudafribocus"/>
    <eLiterals name="DububobuButin"/>
    <eLiterals name="FaGusAububobofribegudaes"/>
    <eLiterals name="BaBebogusBubigugues"/>
    <eLiterals name="BrauboBunulAuGudabudalus"/>
    <eLiterals name="DobuBobudagusgusbulius"/>
    <eLiterals name="DoGunulaubefriGugusboes"/>
    <eLiterals name="EbeboBuEs"/>
    <eLiterals name="BaBuFribebububebugusgufriNulAufriLus"/>
    <eLiterals name="DaGusgubobuguBifrifribiBebilus"/>
    <eLiterals name="BigusDabedagusBebudagulius"/>
    <eLiterals name="ADadabinulAuBiguslius"/>
    <eLiterals name="BafrifribiGuguTin"/>
    <eLiterals name="DibibogusBudaGuBetus"/>
    <eLiterals name="AldaguFrifribubegusbugunulaucio"/>
    <eLiterals name="FaFribugusGusbiGutin"/>
    <eLiterals name="Bebobunulautin"/>
    <eLiterals name="BiguDafrigusLius"/>
    <eLiterals name="AlbebobofrigusDatus"/>
    <eLiterals name="EuFriBubibuDafridadaBuBitor"/>
    <eLiterals name="AlbibugunulAufrinulAugugusFriDadanus"/>
    <eLiterals name="BabudabobubebuBetus"/>
    <eLiterals name="BiNulauGusbuBuBobebogusAuTus"/>
    <eLiterals name="EuboBifribegusfrifriboLius"/>
    <eLiterals name="EGusBibiguGuNulAutin"/>
    <eLiterals name="AlfribuboBiNulaubocio"/>
    <eLiterals name="Bibufribubigugues"/>
    <eLiterals name="DogugusgusbifriNulAubotor"/>
    <eLiterals name="EubofribigusfriDaBofriDaFribegubuTor"/>
    <eLiterals name="DogugubeBuFriDaBeDatin"/>
    <eLiterals name="Bebefricio"/>
    <eLiterals name="Dadabibolius"/>
    <eLiterals name="AngusNulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulAubebigusguTus" eSuperTypes="//EbubuguguFrinulauDaes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afritor" eType="//DaGubebuGububigutor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBebiDaGuNulaubofricus" eType="//AubobeboBucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbigusauboDaguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulAubigusBubububonulaubibelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abibegusdaguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Augusgubunus" eSuperTypes="//AnnulauBuBiguBuGusdaguBinules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="befribobibigusBenulAuBibobeBucus" eType="//BeBibuFrifriBuGugusButus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBiguDalus" eSuperTypes="//AnnulauBuBiguBuGusdaguBinules //BaGugusGusboDabeBugusBuFriNulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulauboGusgusnulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBefriGusbuBofriTor" eType="//BraunulAubebigusguTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BegubegusbifridabibuBuDabobinulauNus" instanceTypeName="typeAldabuGusBifricio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbuFrinulaudadaGuBedatin" instanceTypeName="typeDibifriboBuDanulAugusbobobucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBibunulaubogusgusgusbufrigucio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binulaulus" upperBound="-1" eType="//BegubegusbifridabibuBuDabobinulauNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EguGusGuBocio" instanceTypeName="typeDuBoBunulaubobubuGusdaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufrinulaudagudaBiboguBiBugusbobelius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DudanulaubiBeNulauDafribedaNulAudaGuNus" instanceTypeName="typeEGusnulauBiBinulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufribugusnulAuBofridaGusNulauGuBogues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodafrigusGusbibubedabogunulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiguBebiFrifridadaes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dagustus" eType="//AubegusBoBobocus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBoFriBugusbebugusLius" eType="//BaGugusGusboDabeBugusBuFriNulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndabuNulauBeGuCio" abstract="true" eSuperTypes="//DoDabinulauBuFriBugusbubonules //EbubuguguFrinulauDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfridabebufrinulaubiboBinulEs" eSuperTypes="//DabeGuBidaNulaufricus //DiguBebiFrifridadaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braudabebebenus" eSuperTypes="//AnfridabebufrinulaubiboBinulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abidabuFridabenulaunules" eType="//DibobuGusguNulauNulaulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabedabiFribuNulAunulAuBoTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefribuNulAubufrigudabiDabubidalius" eSuperTypes="//Braudabebebenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ebubibigusbobofribulius" eSuperTypes="//DuFrinulaubinulauDadafricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edaFriboBiBibelus" ordered="false" eType="//AunulaufriguGusgusdabotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusBeGusauBeButin" eSuperTypes="//DiguBebiFrifridadaes"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlgusbinulauGusgusBuNus">
    <eLiterals name="DaboboguNulaubelius"/>
    <eLiterals name="EFrinulauDaBogusbuNulaubefriGusDalus"/>
    <eLiterals name="DibeBubiBigusbibiBogusLius"/>
    <eLiterals name="FadanulAucus"/>
    <eLiterals name="AnbeBogusaubiBoBibedaDagusfridagubolus"/>
    <eLiterals name="DoboGububitor"/>
    <eLiterals name="DofriboBibucio"/>
    <eLiterals name="Eubebofrigusfribogusgusgubobinulaulus"/>
    <eLiterals name="BraubodaBofriFribuNules"/>
    <eLiterals name="DagusdadadaBebocio"/>
    <eLiterals name="AnulaunulauBunulaugusAuLus"/>
    <eLiterals name="BeguBunulaudator"/>
    <eLiterals name="DanulaugusfriGusguguNulAuBegusFriEs"/>
    <eLiterals name="AlNulaunulaububudanulAunulauguslius"/>
    <eLiterals name="BeNulaunus"/>
    <eLiterals name="EbuGusgufrigusguboguTus"/>
    <eLiterals name="FafribigubobifriNules"/>
    <eLiterals name="DabinulauGusgusnulAubibibeLus"/>
    <eLiterals name="FafribobifriDagusfrifridabobuLus"/>
    <eLiterals name="BefriFriGusbofritor"/>
    <eLiterals name="DaBiboBidafriBobiboguBocio"/>
    <eLiterals name="DigusgugusgusguBuGustin"/>
    <eLiterals name="ANulaubeGusBodadabunulaugulius"/>
    <eLiterals name="AnBegusnulaubiBiTor"/>
    <eLiterals name="EunulauBoBeDatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabuguGubiBudabibobuguBudadaes" eSuperTypes="//DubunulaudagusBonulAufrigutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faguNulius" ordered="false" upperBound="-1" eType="//Dobelius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugubunulAudagusBiGulius" eType="//AubegusBoBobocus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBedagusBogusBoBogusnus" ordered="false" eType="//AndabuNulauBeGuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DibuGusdaBebudabidabuNulauLius" instanceTypeName="typeAubobiBodanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusBibigusBibubogusIus" eSuperTypes="//AufrinulaudagudaBiboguBiBugusbobelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGubilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusnulaugubobubenulAuCio" upperBound="-1" eType="//DubunulaudagusBonulAufrigutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaguguGuBibedagustor">
    <eLiterals name="Bebogusbenulaunus"/>
    <eLiterals name="AlauNulaubonulaugufriDagusBetor"/>
    <eLiterals name="Andabegubonulius"/>
    <eLiterals name="Eubigubinulaulus"/>
    <eLiterals name="BeGuGugubiDabedaLius"/>
    <eLiterals name="EfriGuGusBobobiNulAuBubicus"/>
    <eLiterals name="AnulauBufribebuGudaboboboNus"/>
    <eLiterals name="DogusfribeguFribobegusbucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulauFriNulAugubinulEs" eSuperTypes="//EufribugusnulAuBofridaGusNulauGuBogues //FaNulAubigusBubububonulaubibelus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBebobefriDafrigusAubues" eType="//BegubegusbifridabibuBuDabobinulauNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiDanulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauguDafriDanulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidafridabugugudaBoCus" eType="//AnboguBedagunulauGusbedabecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusbeBigufriBuboNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlFriboBunulAubulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBeGuboDaBeNulaugues" ordered="false" eType="//BrauGusBeGusauBeButin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabogudaFriBuFriguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBubiBidafribibunulaugusNulauGuslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudabiBudabebocus" eSuperTypes="//AngusbeBigufriBuboNus //FabibefriGusbifrigusfrigustor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braugunulaufribunus" eType="//BegubegusbifridabibuBuDabobinulauNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaNulAubuGusbiguBiBobubibulus">
    <eLiterals name="BeBodaGusbenulaubilius"/>
    <eLiterals name="AnBibuguGusGusgusbenulauGusaugucio"/>
    <eLiterals name="DiGuNulauBoFribenulAubiDaBofritor"/>
    <eLiterals name="DuBodabububiboBogusTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFribedabonulauBubunulAuBolus" eSuperTypes="//DanulauFriNulAugubinulEs //Ebubibigusbobofribulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaGubeEs" eType="//FaNulAubuGusbiguBiBobubibulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndanulAuBitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabobibotor" ordered="false" eType="//AnulAugubodatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebunulautin" upperBound="-1" eType="//FaNulAubuGusbiguBiBobubibulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebubinulAuboBudator" ordered="false" upperBound="-1" eType="//DonulauboGusgusnulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AububoGusbuDanulauBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuguBuBedanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubuBuGusdaDafriCus" eSuperTypes="//AnnulauBuBiguBuGusdaguBinules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulauGubuDacus" eType="//FaNulAubuGusbiguBiBobubibulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBuGusfribiBoBenulauDaTor" upperBound="-1" eType="//AnAugunulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabonulaugugulus" eType="//DaGubebuGububigutor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="augubuguGubudanulAuNus" ordered="false" upperBound="-1" eType="//AufrinulaudagudaBiboguBiBugusbobelius"/>
  </eClassifiers>
</ecore:EPackage>
