<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="braunulaucus" nsURI="http://hub.de/rcore/examples/braunulaucus" nsPrefix="ZwZK">
  <eClassifiers xsi:type="ecore:EClass" name="EugudabuGusNulAunulauGunulauguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiboguBebegusgusguBoTor" eSuperTypes="//EugudabuGusNulAunulauGunulauguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAufribonulaubibudabuCio" eSuperTypes="//BiboguBebegusgusguBoTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubobebogusbigufrigusBunulius" eSuperTypes="//BrAufribonulaubibudabuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaGubiDagusbobuCio" eSuperTypes="//BrAufribonulaubibudabuCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuDabuBigudagusgusdaes" instanceTypeName="typeDagudaBibinulAuNulaubetor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BifriDadabuDaGugubicio">
    <eLiterals name="BabunulAuBoBuguBuBeBiDagusbulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Bigufribies">
    <eLiterals name="BiNulaunulaufrigubinulauDabicus"/>
    <eLiterals name="DuboBobuDagusNulAudabiboTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgusFridaFribuguBefrigusTor" instanceTypeName="typeAubefrigugusgubebetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusbegusfrinulauFrigubiFrifrinus" eSuperTypes="//BiboguBebegusgusguBoTor //AudaGubiDagusbobuCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiDaboDanulaubeBegusCus" instanceTypeName="typeBiNulAugunulaufriBunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Eudagusaugusautin" instanceTypeName="typeDufribolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusfriBogusbibiguguboes" eSuperTypes="//AudaGubiDagusbobuCio //BiGusbegusfrinulauFrigubiFrifrinus //BraubobebogusbigufrigusBunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfridaguBiGusdaboguslius" eType="//AlgusFridaFribuguBefrigusTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaubibedadagusdafritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusdagufribebunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBifriGusaubuGusNulAuGubucus" ordered="false" upperBound="-1" eType="//EugudabuGusNulAunulauGunulauguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubudafriFribeGusbeBiTor" eSuperTypes="//BrAufribonulaubibudabuCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BagubebuDafriBoTus" instanceTypeName="typeABebeguBibuFribobudacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaguBegulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBinulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBibuguGudaBoGuBufriGufribiBugusDaFriLius" eType="//AlNulaubibedadagusdafritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugufrigugunulAugubodator" eSuperTypes="//BrAufribonulaubibudabuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="danulaucus" eType="//BagubebuDafriBoTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuguBuGusFribuFrinulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugugusDagusgunules" eSuperTypes="//EugudabuGusNulAunulauGunulauguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABiGubeBiGubiBotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubuguBegusbolius" ordered="false" upperBound="-1" eType="//BrAufribonulaubibudabuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubenulauboNulaubugubiGusBugusNulaugunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euNulaubudaGusbies" ordered="false" upperBound="-1" eType="//BiboguBebegusgusguBoTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABugubeBiBubeFrinulAulus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Albibofrigugubidator">
    <eLiterals name="DabebenulaugusBubedaDabiBoNulius"/>
    <eLiterals name="AFriGuBeBobugubunulAubeCus"/>
    <eLiterals name="AnBeGudaLius"/>
    <eLiterals name="AlaugubeBeBeBiguDabunus"/>
    <eLiterals name="Augufribebibonulius"/>
    <eLiterals name="AnbegubobuBoGuCio"/>
    <eLiterals name="AubidagusdagusbeBunulAuNus"/>
    <eLiterals name="Enulaucus"/>
    <eLiterals name="BabeboBiBetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBiboBubeGues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafriBunulaufribibucus" ordered="false" eType="//AnGusdagufribebunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AugubiboBobiboes" instanceTypeName="typeDoGusbebegunulaudabubelus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EugusauNulauguGusgusfribucus">
    <eLiterals name="DoFrifrigusnulAucio"/>
    <eLiterals name="DubofrigusdabubidaBoBunus"/>
    <eLiterals name="DubeBebebegubeDabebobuBucus"/>
    <eLiterals name="AuguBeBodafriGubibubofricus"/>
    <eLiterals name="BinulauboboBidabiBofrifribilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaubeguNulauboFribuBiCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBiGusgusGusguGunulaudadaDaes" ordered="false" eType="//AnGusdagufribebunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EBobugubobufriboFrigusnulIus">
    <eLiterals name="DubonulAuGububutin"/>
    <eLiterals name="DabuGusgusfribifriDadadadaCus"/>
    <eLiterals name="BaBiDadanulAugusBoLius"/>
    <eLiterals name="DubenulAuTus"/>
    <eLiterals name="DigubuGuFribiNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGugusBibiDaboGusius" eSuperTypes="//DuBiboBubeGues"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubibinulaubiNulaubububiCus" abstract="true" eSuperTypes="//ABugubeBiBubeFrinulAulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabofribifrinulauDaCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBibeNulAubeBinulaunulAucio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebeBegudadaDaguscus" ordered="false" upperBound="-1" eType="//EubenulauboNulaubugubiGusBugusNulaugunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baboFrifriLus" ordered="false" upperBound="-1" eType="//AlgusfriBogusbibiguguboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBugufriBeNulaubonulAuFriBies" instanceTypeName="typeFagufrigufrinulaubelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlAubinulAuboNus" eSuperTypes="//BiboguBebegusgusguBoTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGugusbenulauLus" ordered="false" eType="//ABugubeBiBubeFrinulAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusdabibuBuBinulaudabiGusNules" eSuperTypes="//BraubobebogusbigufrigusBunulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiDagusbibuEs">
    <eLiterals name="AlFrigusDadafribibifritor"/>
    <eLiterals name="DigusfribeboBeGububuGudatus"/>
    <eLiterals name="DibebebuBigudaDabogusNulauBibubeLus"/>
    <eLiterals name="Bibuguslius"/>
    <eLiterals name="DunulAubodanus"/>
    <eLiterals name="AguBuNulauDabobebibutin"/>
    <eLiterals name="EuGutus"/>
    <eLiterals name="EubuBudabeNulaubiBeGunulautus"/>
    <eLiterals name="AlbebibibuDaBetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaBibubegunulaubues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBodabiGusGusNulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBeGusBeBoDaBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigunulaubufriBegusGubeGulus" abstract="true" eSuperTypes="//BiGusbegusfrinulauFrigubiFrifrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibibibibeGufriguguDaGusius" eType="//AnBibeNulAubeBinulaunulAucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albinulaufrinulAutin" eType="//EBobugubobufriboFrigusnulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EugusbibibogusBogusaugubeBifriTor" instanceTypeName="typeAbobedagusfrigutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuguNulaufrinulauBebutus" abstract="true" eSuperTypes="//BiboguBebegusgusguBoTor //AubudafriFribeGusbeBiTor //ABugubeBiBubeFrinulAulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusbeBuBobibiGusTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabenulauBibebefridaTin" instanceTypeName="typeEugubidaBobobobufriboEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdaboBibuGufriGufribuCus" abstract="true" eSuperTypes="//BaguBegulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafriBugusDaguBiGusius" eSuperTypes="//AnBibeNulAubeBinulaunulAucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albefriNulauDanulAunulIus" eType="//Albibofrigugubidator" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="e" eType="//EugusauNulauguGusgusfribucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGugubuBuguBoGusNulAuTus" eSuperTypes="//FafriBugusDaguBiGusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulauFribiBubotus" ordered="false" eType="//FafriBugusDaguBiGusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dobebubilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugusbeboNulaugubiBodaboTor" eType="//EugusbibibogusBogusaugubeBifriTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebigubiguNulauBubeTin" ordered="false" upperBound="-1" eType="//DigunulaubufriBegusGubeGulus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duFribegusbigustin" eType="//AugubiboBobiboes" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubegubigusius" ordered="false" upperBound="-1" eType="//DagusbeBuBobibiGusTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulauDafriBobeDatin" abstract="true" eSuperTypes="//DuGugusBibiDaboGusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadadaboguBoes" ordered="false" upperBound="-1" eType="//AnGusdagufribebunus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albonulaubiBoes" eType="//EBobugubobufriboFrigusnulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BidaDadafribotor" instanceTypeName="typeAbiBebeBegubuCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeNulAubiDaFribucus" instanceTypeName="typeAnNulaubuBubuBuNus"/>
</ecore:EPackage>
