<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albigubudator" nsURI="http://hub.de/rcore/examples/albigubudator" nsPrefix="CUz">
  <eClassifiers xsi:type="ecore:EDataType" name="DinulaubodabebiboBiDatus" instanceTypeName="typeDaGubebogudadaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFribeBufriGufries" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="al" eType="//DinulaubodabebiboBiDatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulAunulaucus" eType="//DinulaubodabebiboBiDatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faguGuGusBoguTor" ordered="false" upperBound="-1" eType="//Babinulaulus" eOpposite="//Babinulaulus/fafribuBebifrigububububeTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobiNulauDacus" eSuperTypes="//BaFribeBufriGufries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adafrigufricus" ordered="false" upperBound="-1" eType="//BaFribeBufriGufries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusBibilus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfridadabues" ordered="false" eType="//BaFribeBufriGufries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusBigufriboNulauBebobenulEs" eSuperTypes="//DobiNulauDacus //BeGusBibilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusbibenulAuboguFriGusaufrigusbuGusFrilus" eSuperTypes="//BaFribeBufriGufries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aunulauguBuNulaudaboGuFricio" eType="//DinulaubodabebiboBiDatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobunulAudaes" eType="//DigusBigufriboNulauBebobenulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaunulAugusbiBenulaugustus" eSuperTypes="//DagusbibenulAuboguFriGusaufrigusbuGusFrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulAuNulAubuGubibicio" eSuperTypes="//EunulaunulAugusbiBenulaugustus //DobiNulauDacus //DigusBigufriboNulauBebobenulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugudagufribiBeNulauTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusDaGubiBeNulautin" ordered="false" eType="//BeGusBibilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagubeDabobubugubucus" ordered="false" eType="//AudabeGunulaubegubeCio" eOpposite="//AudabeGunulaubegubeCio/bafriBobubenulauNulaunulAuNulaubuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBufriGusGuNulAuBoBigusNulAubegusbeGutin" eSuperTypes="//BeGusBibilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfriNulauGububegudalius" eType="//DudabugusaubuBufrigusTin" eOpposite="//DudabugusaubuBufrigusTin/begubiDaGudagusgusBiNulaubofries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EufribuGusBugudabegusBotor" eSuperTypes="//DagusbibenulAuboguFriGusaufrigusbuGusFrilus //EunulaunulAugusbiBenulaugustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auboguCus" eType="//DinulaubodabebiboBiDatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binulauFribubebinulaugubinus" eType="//DinulaubodabebiboBiDatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulaubifriGusdabodaBenus" ordered="false" upperBound="-1" eType="//DagusbibenulAuboguFriGusaufrigusbuGusFrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudabeGunulaubegubeCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="di" eType="//DinulaubodabebiboBiDatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGusFribonulaufribotor" ordered="false" eType="//AuBufriGusGuNulAuBoBigusNulAubegusbeGutin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafriBobubenulauNulaunulAuNulaubuEs" ordered="false" upperBound="-1" eType="//DugudagufribiBeNulauTin" eOpposite="//DugudagufribiBeNulauTin/bagubeDabobubugubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafriBuGuNulAunulauBibuBotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dilus" eType="//DinulaubodabebiboBiDatus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnnulauBidaDaDafridabebifribucus" instanceTypeName="typeAuBibibuDafridabonulaubinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobugusBodaboguEs" eSuperTypes="//DaNulAuNulAubuGubibicio //AuBufriGusGuNulAuBoBigusNulAubegusbeGutin //FafriBuGuNulAunulauBibuBotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabofriGuscus" ordered="false" eType="//FafriBuGuNulAunulauBibuBotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBunulauGubeCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuBigufrinulaubuBoTus" eType="//DinulaubodabebiboBiDatus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBunulaudafriEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babinulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafribuBebifrigububububeTus" ordered="false" eType="//BaFribeBufriGufries" eOpposite="//BaFribeBufriGufries/faguGuGusBoguTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebenulAuBeGubiFriGulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biDagubegusgusboBubeLius" eType="//DinulaubodabebiboBiDatus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBogubucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubobibobodabibeguBebigusbecus" eType="//DobugusBodaboguEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAugusbonulaudagusgusbuBiGusGuFrilius" ordered="false" upperBound="-1" eType="//DigusBigufriboNulauBebobenulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuboBobuGuGuscus" abstract="true" eSuperTypes="//AudabeGunulaubegubeCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dunulaubonulaudabecio" instanceTypeName="typeDogusbeguBeBifridaBubudabicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusnulaubibiBuGusbiBubolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAunulaubibuDabuBogunulaubuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBibofribidaBitus" eSuperTypes="//DagusbibenulAuboguFriGusaufrigusbuGusFrilus //DigusBigufriboNulauBebobenulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGusfribebeTin" ordered="false" eType="//Babinulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusboGusnulAuBoboBotus" eSuperTypes="//DagusbibenulAuboguFriGusaufrigusbuGusFrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifrifrifriBeGuBoFrigusius" eSuperTypes="//Babinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGubidagubiBububoNus" eSuperTypes="//DaNulAuNulAubuGubibicio //AudabeGunulaubegubeCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbubeboBugusbogubeNulauGudaes" ordered="false" upperBound="-1" eType="//BaFribeBufriGufries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusbubunulaubuguBefriboTus" ordered="false" eType="//DobugusBodaboguEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibotus" upperBound="-1" eType="//Dunulaubonulaudabecio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifriBoNulauboguGudaguFrilus" ordered="false" upperBound="-1" eType="//BeGusBibilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudabugusaubuBufrigusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begubiDaGudagusgusBiNulaubofries" ordered="false" upperBound="-1" eType="//AuBufriGusGuNulAuBoBigusNulAubegusbeGutin" eOpposite="//AuBufriGusGuNulAuBoBigusNulAubegusbeGutin/alfriNulauGububegudalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ENulaubifrifridadacus" instanceTypeName="typeDidabofrinulauBoBebobetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidabeBuBidanulauBigusbebibigusguslius" eSuperTypes="//DobugusBodaboguEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbobebebeGusnulius" ordered="false" eType="//BrAuFribogusbeDadaguGusfrigusgusNulautus" eOpposite="//BrAuFribogusbeDadaguGusfrigusgusNulautus/anbogusgunulauBedaGusNulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeBuBobibeTus" eSuperTypes="//BifrifrifriBeGuBoFrigusius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebugusgusBoNulAuboCio" eType="//Dunulaubonulaudabecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaDafrinulAufrigusfrifribilius" eSuperTypes="//DigusBigufriboNulauBebobenulEs //EunulaunulAugusbiBenulaugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBoguBiGunulaugustus" eSuperTypes="//BraubeBuBobibeTus //BeBogubucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBegusautor" eType="//DinulaubodabebiboBiDatus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BafriGudafribonulauFrinulAulius" instanceTypeName="typeBaFriFriBugusGusAuGusBoGuguscio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuDabuNulaugusgusaudabebiGulus" instanceTypeName="typeDiBubiguNulauFrinulaubodafrifriFribufricio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabubofrifriBeFrinulAubeBifrinulauTor" instanceTypeName="typeAnGufriDabigusauNulauDaBuTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusbegusnulaugudaGunulaugunulaubeTus" instanceTypeName="typeBibugubuGubebotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufribiGubofriBodalius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egusbigubobugusbeGubiGuscus" eType="//DinulaubodabebiboBiDatus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albiNulauGusbofriFriCio" ordered="false" upperBound="-1" eType="//Babinulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulauGusnulAubuBuLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bi" eType="//AnnulauBidaDaDafridabebifribucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBebunulaubuBufriGuslus" abstract="true" eSuperTypes="//FafriBuGuNulAunulauBibuBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubigubibugusnulaugusNulaunulEs" eSuperTypes="//BagusboGusnulAuBoboBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiDabodaBigubofriBeCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobiDaBibobibugusauguDaNulius" ordered="false" eType="//BiBunulaudafriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGunulaubegusbebuNus" eSuperTypes="//Babinulaulus //BebenulAuBeGubiFriGulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EDagudabufribeGusfricus" instanceTypeName="typeAgusgusbobebiNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubuFrinulaufribonulauDabeGusnules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edaFribudabudabubuFrinulaubulus" ordered="false" eType="//BeGusBibilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Dobigusfricio" instanceTypeName="typeBrAubuBudaDabiBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusguBiDaBigusBoBigufrilus" eSuperTypes="//AnBebunulaubuBufriGuslus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraudanulauboBubiBobiFriEs" instanceTypeName="typeAubeDagubugusgusTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbunulAuGusaugusauBetus" instanceTypeName="typeAlnulAuGusauBubuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboguNulAulus" eSuperTypes="//BagusboGusnulAuBoboBotus //AudabeGunulaubegubeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibiNulaufrifrigubogusguTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diboGugubibigudabibetor" upperBound="-1" eType="//Dobigusfricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EubunulAuBobobutor">
    <eLiterals name="DuboBoBibibubinulius"/>
    <eLiterals name="ABuBebegubocio"/>
    <eLiterals name="BibiFridaboBebibebeboboFribuCus"/>
    <eLiterals name="EBebodaboBegubobebiguCus"/>
    <eLiterals name="DofridagusbebiBuGuguBebefriboGusCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuFribogusbeDadaguGusfrigusgusNulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbogusgunulauBedaGusNulaucus" ordered="false" eType="//BidabeBuBidanulauBigusbebibigusguslius" eOpposite="//BidabeBuBidanulauBigusbebibigusguslius/anbobebebeGusnulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebufrigusgubedaBuDabedabufrilus" eSuperTypes="//BeGusBibilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadafrigubigusBiGusfrigusbiNulius" eSuperTypes="//Babinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enulaufribetor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AngusDanulAufritin" instanceTypeName="typeAgugusfrigugusboGufridaFrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusboDaBedaFrigusNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusdabifribuBonulAucio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusBiBeGusguscus" upperBound="-1" eType="//BebufrigusgubedaBuDabedabufrilus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulAufrigutus" eType="//BraudanulauboBubiBobiFriEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlDadagugusbiBuboFriboNulaubeFriCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiGugusguses" ordered="false" upperBound="-1" eType="//AgusdabifribuBonulAucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euFriDaNulAudaNulaudaFriboCus" upperBound="-1" eType="//Annulaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaDadaGusGusfriBibeFries" eSuperTypes="//FafriBuGuNulAunulauBibuBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaboFribebiBoGusGugustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBuboDagusbeguguboTor" ordered="false" upperBound="-1" eType="//EgusnulaubibiBuGusbiBubolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgubiboNulAugubuCus"/>
</ecore:EPackage>
