<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diboes" nsURI="http://hub.de/rcore/examples/diboes" nsPrefix="q">
  <eClassifiers xsi:type="ecore:EClass" name="DigusnulaufriNulAuboBuLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulauBogugugusDabeDatin" ordered="false" upperBound="-1" eType="//DobugufrigusGusBocio" eOpposite="//DobugufrigusGusBocio/egubobeBibuguTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Albebefribigusgustor" instanceTypeName="typeBegudaBebobuBeGubudaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusDaBuGusbobeFriFriguFribeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobububuDaFribuboFricus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusgusdabiBoBudagusnus" ordered="false" eType="//DigusnulaufriNulAuboBuLus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbibebobobigutus" upperBound="-1" eType="//Albebefribigusgustor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiGuBeBifriFribugusnulaucus" eSuperTypes="//DigusnulaufriNulAuboBuLus //DobububuDaFribuboFricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabuBogugufrinulAudalius" upperBound="-1" eType="//DobububuDaFribuboFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulauBufridabodagusnus" eSuperTypes="//DigusnulaufriNulAuboBuLus //DobububuDaFribuboFricus //EugusDaBuGusbobeFriFriguFribeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagudabugusNulauDaBunus" upperBound="-1" eType="//DigusnulaufriNulAuboBuLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGuDabuGubonulauGuLus" ordered="false" upperBound="-1" eType="//DobububuDaFribuboFricus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulaubuLus" ordered="false" upperBound="-1" eType="//AnFrigubudafriGugububetin" eOpposite="//AnFrigubudafriGugububetin/dunulauGubibiboNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigugubeBiDabunulaulius" eSuperTypes="//DobububuDaFribuboFricus //DigusnulaufriNulAuboBuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebodagusaufricio" ordered="false" eType="//DigusnulaufriNulAuboBuLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubiNulaufrinulaubuLus" ordered="false" eType="//DodagusnulaubifriFrigusGusboFribeBoLus" eOpposite="//DodagusnulaubifriFrigusGusboFribeBoLus/faboGuguBiBoBogubedalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFrigusbebeFribeFrinulauGudadagusfricio" eSuperTypes="//DobububuDaFribuboFricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubobigusbinulAuCus" ordered="false" upperBound="-1" eType="//EugusDaBuGusbobeFriFriguFribeLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babubofribefribegusnulius" ordered="false" upperBound="-1" eType="//AGusguboGufribeGufriTor" eOpposite="//AGusguboGufribeGufriTor/ebeBuBugusgusguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbobiguFriBuCio" abstract="true" eSuperTypes="//EnulauBufridabodagusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babigusbubibiBenulAuBetor" ordered="false" upperBound="-1" eType="//EugusDaBuGusbobeFriFriguFribeLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgusBibeGusBifries" instanceTypeName="typeEubibugunulaubucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubefrinulauGusfridadaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnAubiGufriBubonulauGugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofriGusfriGusgusgudadaGusdaBolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaubiBubedaNulauguBonules" eSuperTypes="//AnAubiGufriBubonulauGugustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aububibinulaubulius" eType="//Albebefribigusgustor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAubibiguses" ordered="false" upperBound="-1" eType="//EbobiguFriBuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusgusbiGuFrifriboGusBigutin" eSuperTypes="//DigusnulaufriNulAuboBuLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babebinulAudalius" eType="//Albebefribigusgustor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBofrifriDabiBoGubutus" ordered="false" eType="//AnAubiGufriBubonulauGugustus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaufriGuBogusnulaugunus" ordered="false" upperBound="-1" eType="//DofriGusfriGusgusgudadaGusdaBolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibebigusBubufrinulAuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebobobeGuboGusBubobibogusfribucio" ordered="false" upperBound="-1" eType="//DofriGusfriGusgusgudadaGusdaBolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBidafribunulAubobobibugusdaBeBudabinus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnulauBibodagudagugusdaboTor" instanceTypeName="typeAlfribudaGusnulaubuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubobebogusGuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babufribegubonus" ordered="false" upperBound="-1" eType="//DigusnulaufriNulAuboBuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbibiGuGusguBububies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBufribibuGugutin" ordered="false" eType="//DobububuDaFribuboFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuFrigusboboDabugubuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobobonulaunulaulus" eType="//EnulauBufridabodagusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnFriguboGusBeBubobiBonulius" instanceTypeName="typeAdaGusbibedabuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaubofridaBinulAuBocus" eSuperTypes="//BiGuBeBifriFribugusnulaucus //DigugubeBiDabunulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGuFribuguBogusgunulaufrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubolus" eType="//AnulauBibodagudagugusdaboTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBeboLius" eSuperTypes="//EnulauBufridabodagusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiguNulaufridanulauNules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abebilus" eSuperTypes="//FaBidafribunulAubobobibugusdaBeBudabinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daguscio" eType="//Albebefribigusgustor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldabuBiBunulauNus" ordered="false" upperBound="-1" eType="//AlbibebigusBubufrinulAuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BinulauBiguGunules" instanceTypeName="typeAlnulaugubegubetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibunulauBelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusauGusbibibifriBobiboTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BegusbuBebobuBoNulius" instanceTypeName="typeABudafribuBonulAubebiNulauCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbeGuBidafribigubebotin" eSuperTypes="//EnulauBufridabodagusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aNulaugusBeLus" ordered="false" eType="//AbibiGuGusguBububies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FabububeBibiBoBoBuGugusFriguslius">
    <eLiterals name="DadaBebubeNulauBoGusnus"/>
    <eLiterals name="BigugusGusNulaubutin"/>
    <eLiterals name="AdabuGubonulIus"/>
    <eLiterals name="DaNulaubebiDafrifribugusTin"/>
    <eLiterals name="BraubofriDaBedaNulaucus"/>
    <eLiterals name="DoBobegusbubobunulaubobibigubebies"/>
    <eLiterals name="DubiBodaguscus"/>
    <eLiterals name="DibedaGububiBidaguGusBoDacus"/>
    <eLiterals name="BebebiBunulaufrifriBiguNulaulius"/>
    <eLiterals name="BidabenulaubuNulaucio"/>
    <eLiterals name="BagusgusbuBoBeboBebobobunulAuTor"/>
    <eLiterals name="DaguFriBofriguEs"/>
    <eLiterals name="BagusGubuDaBefrifribubefricus"/>
    <eLiterals name="DaGufrigufribeGusNulaunulaugubocio"/>
    <eLiterals name="EuFrigusfrifrigusdaguNulauNulAuguCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuDabigubufriNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBobunulaufrifribitor" eSuperTypes="//FaNulaubofridaBinulAuBocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebebiBegusFrigusnulaufriLius" ordered="false" eType="//Abebilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBuBofridaguEs" eSuperTypes="//ENulaubiBubedaNulauguBonules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albigunulautus" upperBound="-1" eType="//EuBobunulaufrifribitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugunulAunulAuBugusbobinulautor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AGusbiGusGusgugusdafriBoboGutor" instanceTypeName="typeDuBuBinulaufribuboDafrifribobuBuNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EunulAuboBobogusnulaunus">
    <eLiterals name="DinulaubuDaNulaufrilus"/>
    <eLiterals name="AlfribubobobidabobidaGuBibutor"/>
    <eLiterals name="BibuBubidaNulauBufrilus"/>
    <eLiterals name="EubuguBodabebefriBonulius"/>
    <eLiterals name="BanulaunulauNulaudadadabibufries"/>
    <eLiterals name="DigusBenulAubobugusgusauguBuFriTor"/>
    <eLiterals name="DuBuDanulAubeDabobinulEs"/>
    <eLiterals name="DobubonulAubonules"/>
    <eLiterals name="BabeBenulAubebeNulaunulaubuGusbotor"/>
    <eLiterals name="DaBobubeboguNulaunulauTor"/>
    <eLiterals name="AlFrinulaufrinulauBenulAubelius"/>
    <eLiterals name="DunulauGubunulaububoNulIus"/>
    <eLiterals name="DonulAuBegubees"/>
    <eLiterals name="BefriDaBubunulAugucus"/>
    <eLiterals name="DadadabobunulaugubuFribobiBugusGues"/>
    <eLiterals name="Dibebobenulaunulius"/>
    <eLiterals name="AlbugusBefriBibolus"/>
    <eLiterals name="DobufriBubobolius"/>
    <eLiterals name="EuGuguNulauFriBibiLus"/>
    <eLiterals name="BigudabeFrinus"/>
    <eLiterals name="DaBobedagusbubibunulaugusnulius"/>
    <eLiterals name="DuboBedaFridagusAuBoLius"/>
    <eLiterals name="Bagusaugugusnulautus"/>
    <eLiterals name="FanulAuBubuBidaBobicio"/>
    <eLiterals name="Albudatin"/>
    <eLiterals name="BeBibobebeTin"/>
    <eLiterals name="DubiGunulaufries"/>
    <eLiterals name="AnbunulauBubenulAulus"/>
    <eLiterals name="AnaubobibubufrigusGuBiTin"/>
    <eLiterals name="EnulAuguDaBeBefrigusius"/>
    <eLiterals name="DuNulAufriBobubedaLius"/>
    <eLiterals name="BidaFriBobuBuBoguTor"/>
    <eLiterals name="BenulAunulaufribuBoDaBoGufrilus"/>
    <eLiterals name="DubibifriFribufridaBeTin"/>
    <eLiterals name="AngubebibobiguBiBigusfriCus"/>
    <eLiterals name="DobeGusfrigusauGufrigusaucus"/>
    <eLiterals name="BifrinulAuBufrilius"/>
    <eLiterals name="AugubifrinulAuboNulaubefribinulEs"/>
    <eLiterals name="DabonulaudabuBifrigugubibucio"/>
    <eLiterals name="BebeGugusbubibibebeBiguBebonulius"/>
    <eLiterals name="DuGusgusbobuboGunulAuguses"/>
    <eLiterals name="BiBiFribiGudaBees"/>
    <eLiterals name="BefribiguBiGusgusbubucio"/>
    <eLiterals name="BidanulaugusaufrigugudaboBibitor"/>
    <eLiterals name="AnbebinulAugubiGusGuBitus"/>
    <eLiterals name="FaguDafribiBiFrilus"/>
    <eLiterals name="Dodabubugusnules"/>
    <eLiterals name="BraufribibogusbidanulAutin"/>
    <eLiterals name="AgugusbibobuNulEs"/>
    <eLiterals name="DabodabiGugusnulius"/>
    <eLiterals name="DibobigusBofriGusbigusfriFribinulius"/>
    <eLiterals name="FadaGuboGuFribebobonulaubigububocio"/>
    <eLiterals name="BeDagusaubugubeBonus"/>
    <eLiterals name="EugusbebifrinulAugugubibubiNulauTus"/>
    <eLiterals name="DoDagugusbudabeBubetin"/>
    <eLiterals name="EFribogubolius"/>
    <eLiterals name="Digusbigusbonules"/>
    <eLiterals name="AunulAuBifriGugudaTus"/>
    <eLiterals name="EuGugusdaBubebuTor"/>
    <eLiterals name="DibebofribuFrigugusBonulauBigusbucus"/>
    <eLiterals name="EuFriboGubebubugulus"/>
    <eLiterals name="FaBudabubiDabofriboFridator"/>
    <eLiterals name="DifribudaNulaucus"/>
    <eLiterals name="Dobibofribocus"/>
    <eLiterals name="EgufriNulAubugusgusaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuGubigubibeBinulaufries">
    <eLiterals name="AuFrinulAugububiDalius"/>
    <eLiterals name="AubobubibobugusbobebebuTin"/>
    <eLiterals name="AuguBifribibegusbobiBocus"/>
    <eLiterals name="Fabebunulaubidagusbolus"/>
    <eLiterals name="DobebobenulAubeBeDaNus"/>
    <eLiterals name="ABonulauNulAubidabubiFriGusbobudaFribeLius"/>
    <eLiterals name="AlFriDabiGuslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubonulauBogusnulaunulaufrigunules" eSuperTypes="//EubefrinulauGusfridadaNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abufriBunulIus" ordered="false" upperBound="-1" eType="//AuFrigusboboDabugubuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBubonulaugufriBicio" eSuperTypes="//FaNulaubofridaBinulAuBocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efrigusAugusBuGusfricus" ordered="false" upperBound="-1" eType="//DofriGusfriGusgusgudadaGusdaBolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusAudanulauBunulaudadadagusnulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFrigusfribeBibubebebobobeDaboNus" ordered="false" eType="//EugusDaBuGusbobeFriFriguFribeLus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulaubobodagusBuEs" eType="//BinulauBiguGunules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGubebugubebeBoCus" ordered="false" eType="//EugusDaBuGusbobeFriFriguFribeLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodagusnulaubifriFrigusGusboFribeBoLus" eSuperTypes="//EubefrinulauGusfridadaNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faboGuguBiBoBogubedalius" ordered="false" eType="//DigugubeBiDabunulaulius" eOpposite="//DigugubeBiDabunulaulius/dubiNulaufrinulaubuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusdadaFrifridabeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiBebiBubeGusdabubefriCio" ordered="false" eType="//AnGusgusbiGuFrifriboGusBigutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Egudabibebenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abobiBunulaubofribuBedanulius" ordered="false" upperBound="-1" eType="//AGusauGusbibibifriBobiboTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodafriBoBuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaugusdaguFriBebeGusbilius" eSuperTypes="//AnAubiGufriBubonulauGugustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBifriBocus" upperBound="-1" eType="//EuBuBofridaguEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbenulAudagugugusfries" eSuperTypes="//BaBeboLius //AuFrigusboboDabugubuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doFriGunulaudatus" upperBound="-1" eType="//EnulauBufridabodagusnus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difribenulAudanulaudatus" eType="//AnFriguboGusBeBubobiBonulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebogububobidabefriboGuBitus" eType="//AlgusBibeGusBifries" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabigusBofriBugusBefrigusLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agusnulaububeBifrigustin" eType="//FabububeBibiBoBoBuGugusFriguslius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBeDagusnulaufrinus" eType="//FabububeBibiBoBoBuGugusFriguslius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeguNulAunulaugusBiBebobiGuBefriNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugudaGusdafribitor" instanceTypeName="typeAuBoBubebiBinulAubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFrigubudafriGugububetin" abstract="true" eSuperTypes="//DibunulauBelius //BiGuBeBifriFribugusnulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulauGubibiboNules" ordered="false" eType="//EnulauBufridabodagusnus" eOpposite="//EnulauBufridabodagusnus/alNulaubuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAubugusBeBiBeBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auFrigusfriBedaBubiBudanulaucus" upperBound="-1" eType="//FaBidafribunulAubobobibugusdaBeBudabinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufriBidaBibigusnulAutin" eType="//EuBobunulaufrifribitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobugufrigusGusBocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egubobeBibuguTus" eType="//DigusnulaufriNulAuboBuLus" eOpposite="//DigusnulaufriNulAuboBuLus/banulauBogugugusDabeDatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabobefridaguGusbibegufriBenulEs" instanceTypeName="typeBaBegugububelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusfribeNulaugustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGubogusgusgusbeFrinus" ordered="false" upperBound="-1" eType="//AnbenulAudagugugusfries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiDagusfriBubiBoguGufribeDafriFriguslus" abstract="true" eSuperTypes="//DibunulauBelius //EubefrinulauGusfridadaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulAufriBinulAubobubolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubenulauGusnules" eSuperTypes="//BiDagusfriBubiBoguGufribeDafriFriguslus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EBiDadaboboDadaes" instanceTypeName="typeBraubifriFriGusbuGusgusauTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuFriBugunulaugusbolus" instanceTypeName="typeAldadafrinulauNulaubogusgusaubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eufridabobegulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBenulaubodabuNulAucus" ordered="false" eType="//DobububuDaFribuboFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGubiBoBuFriDagusAufriLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eboFricus" eType="//EuBobunulaufrifribitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudafrinulauTin" eSuperTypes="//Abebilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufriBugugusbiNus" ordered="false" eType="//EbobiguFriBuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBigusaugugusdaFriboGuGusgusNulautus" abstract="true" eSuperTypes="//AnGusgusbiGuFrifriboGusBigutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboBinulauguNulautor" eSuperTypes="//AubobebogusGuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubigusbudaDafridaBebibifriboTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGubigugusautin" ordered="false" eType="//BagusdadaFrifridabeTor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="didagusDaNulauBiNulaugububeBuTus" eType="//BinulauBiguGunules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGusguboGufribeGufriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebeBuBugusgusguscus" ordered="false" upperBound="-1" eType="//EFrigusbebeFribeFrinulauGudadagusfricio" eOpposite="//EFrigusbebeFribeFrinulauGudadagusfricio/babubofribefribegusnulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBegunulaubebeDadaguslius" ordered="false" upperBound="-1" eType="//BiBigusaugugusdaFriboGuGusgusNulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBedabigusbiFribuNulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibobubogusdaDabobidaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabiBifribobobiGusfriNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aufrifrigusfribibobobifriGuDaBetor" eType="//EunulAuboBobogusnulaunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbebifribegunulAuguBuEs" eType="//AGusbiGusGusgugusdafriBoboGutor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagugusnulaubebedanulAufrinus" eSuperTypes="//FaNulaubofridaBinulAuBocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubuBibedaGuguFrigubigusbiguscio" ordered="false" upperBound="-1" eType="//BraubonulauBogusnulaunulaufrigunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusfribuBoBugusBobuNulaulius" eSuperTypes="//AlbibebigusBubufrinulAuTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauDagubefries" eType="//Albebefribigusgustor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadaGusBugusGusbebiBuGuBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBiBigugugubibuboGusDabuGusDabitus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BabugusdabobufriBinus">
    <eLiterals name="DibonulauGuTus"/>
    <eLiterals name="AbebuDanulaudabobotus"/>
    <eLiterals name="EuFrinulauBebeboNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubinulauBodaGulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifriGusbuLius" eSuperTypes="//AuFrigusboboDabugubuNus //DobububuDaFribuboFricus"/>
</ecore:EPackage>
