<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albenulaunules" nsURI="http://hub.de/rcore/examples/albenulaunules" nsPrefix="L">
  <eClassifiers xsi:type="ecore:EClass" name="BeDaBedafrigubebiNulaufrifrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabinulaudadabuBebebobotus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedanulaubefriBiCus" ordered="false" eType="//BeDaBedafrigubebiNulaufrifrinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeguBigubinulaunulaubutus" instanceTypeName="typeAgusGusbugunulAuGuFritin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DigusbigusBenulauboBogusbeboLus" instanceTypeName="typeAnbigugudacus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BibofribigubeBubebogusgubedagudafrilius" instanceTypeName="typeBaGusbufridabedalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulaubebofrigusnulAuGulius" eSuperTypes="//FabinulaudadabuBebebobotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBubiFrifriGuNulaubebucus" instanceTypeName="typeDuGusaububoBubeGusFribubofrifricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabogusbuguBubobeFriNulAunules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedaboBegunulaunules" abstract="true" eSuperTypes="//DabogusbuguBubobeFriNulAunules //ANulaubebofrigusnulAuGulius //BeDaBedafrigubebiNulaufrifrinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubidabeBobuBebofrinules" ordered="false" upperBound="-1" eType="//DabogusbuguBubobeFriNulAunules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="do" eType="//DigusbigusBenulauboBogusbeboLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiboDabiGuslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBefribonulauboFribugusbebutor" upperBound="-1" eType="//BeDaBedafrigubebiNulaufrifrinulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufrinulauNulauBenulaubebecus" ordered="false" eType="//DabogusbuguBubobeFriNulAunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabubeBebibegusbiBegugusnulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabuGusgusgunulaubuBodadalus" eSuperTypes="//BabubeBebibegusbiBegugusnulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beGusBogusBuDalius" eType="//BabubeBebibegusbiBegugusnulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibegusbobobibeboFriboNulEs" abstract="true" eSuperTypes="//ANulaubebofrigusnulAuGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabibebofriBeGusNulauBuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobebiDaFriNules" ordered="false" upperBound="-1" eType="//FabuGusgusgunulaubuBodadalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algusbubudabunulAubulius" ordered="false" eType="//FabinulaudadabuBebebobotus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubuBinulauBibubeGusGusaulus" ordered="false" eType="//EnulaugusbeTin" eOpposite="//EnulaugusbeTin/bigunulaufriBidaLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufriFridabibonulIus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusnulaufrifriGusBebefrilus" eSuperTypes="//BedaboBegunulaunules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eu" eType="//BeguBigubinulaunulaubutus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="augunulaudagunulaulus" ordered="false" eType="//AufriFridabibonulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DububifridaBofriBuTor" eSuperTypes="//BeGusnulaufrifriGusBebefrilus //AlbibegusbobobibeboFriboNulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbegugusboDaBonulaubugusbenus" eType="//BabubeBebibegusbiBegugusnulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Difricus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BeGusbiDaNulauDabeDator"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbofrigugufribiBigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dofrigunulaubibigubudalius" eSuperTypes="//AnbofrigugufribiBigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaubibobedafriboGugusnulAunus" eSuperTypes="//BeGusnulaufrifriGusBebefrilus //Difricus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DifribibonulAudaNulaudaguFritin">
    <eLiterals name="EBiFribebubiBinulaubeTor"/>
    <eLiterals name="AufrigunulAubonulauBuboBies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubefrinulaubiCus" eSuperTypes="//BedaboBegunulaunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulauBigugusDabunulAunulAuButor" ordered="false" upperBound="-1" eType="//BeGusnulaufrifriGusBebefrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusfridabuDabebees" eSuperTypes="//BabubeBebibegusbiBegugusnulIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DagububuBodaGusaufribolius" instanceTypeName="typeAunulAubedabiboguguDaBoTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbiboFribubeBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaFribugusfribiBubonus" ordered="false" upperBound="-1" eType="//DabogusbuguBubobeFriNulAunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgusNulaubinulaugusNulius" instanceTypeName="typeBebibofribuBubecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBubodaBuFrilius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulAububoboNulaubebuGunules" ordered="false" eType="//AnbofrigugufribiBigues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBigubububonulauTin" instanceTypeName="typeDobiGusGusgubiGubuLius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BraufrigusnulAulus">
    <eLiterals name="FabeBegudafriDafribugufritor"/>
    <eLiterals name="DufriGusfrigusGusgubeboBiLius"/>
    <eLiterals name="DugusAugustus"/>
    <eLiterals name="AldadafribidaGusgusfriBeboNulaulius"/>
    <eLiterals name="DifriFrigusLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlfriBogusbebinulAubeguguGubunulauNus" instanceTypeName="typeAunulaububoBolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufrigusbedaBobofrinulaugudator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agububoBeBoNulAuNulEs" ordered="false" upperBound="-1" eType="//BegunulauTin" eOpposite="//BegunulauTin/albuNulaubonulauGubebebebies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EufribibinulaufribebenulAubugunus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBibeDaGububiBogusBifrifriTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="afriGusauBiGusbuBebuboguBugunus" ordered="false" eType="//AufrigusbedaBobofrinulaugudator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulaugusbeTin" eSuperTypes="//DabibebofriBeGusNulauBuLius //BeDaBedafrigubebiNulaufrifrinulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebiBenulAugusbiguses" eType="//AlgusNulaubinulaugusNulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigunulaufriBidaLius" ordered="false" eType="//DabibebofriBeGusNulauBuLius" eOpposite="//DabibebofriBeGusNulauBuLius/aubuBinulauBibubeGusGusaulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBonulaugubogusBefrinulaulus" ordered="false" upperBound="-1" eType="//AlbibegusbobobibeboFriboNulEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audaBobefriBububeBuCio" upperBound="-1" eType="//BiBubiFrifriGuNulaubebucus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubebibufrifriNulauBegufrigusGusfriNulaulius" ordered="false" upperBound="-1" eType="//DububifridaBofriBuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubidaBigusbobies" eSuperTypes="//Difricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difrigusBuguBifriDadabenules" eType="//BiBubiFrifriGuNulaubebucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbudabonulAubeguGusNules" abstract="true" eSuperTypes="//BaGusfridabuDabebees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efriGusbubonulauGubeCio" ordered="false" upperBound="-1" eType="//EufribibinulaufribebenulAubugunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugugusfriBebiGusbigusBidaBefriBoboNus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBoboDaguboBidaBubuDaFribebeBiBees" ordered="false" eType="//FabuGusgusgunulaubuBodadalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabebinulaubogusguFrigufrilus" ordered="false" eType="//EufribibinulaufribebenulAubugunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagugubibugunulaufrifribobiDagusTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubebuDaBeCio" eType="//BiBubiFrifriGuNulaubebucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbefribunulauDaBuBebogustor" eSuperTypes="//AufriFridabibonulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doFrinulaubofriGuDaTus" eType="//EnulaugusbeTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugunulAutin" ordered="false" eType="//AlnulaubibobedafriboGugusnulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegunulauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albuNulaubonulauGubebebebies" ordered="false" upperBound="-1" eType="//AufrigusbedaBobofrinulaugudator" eOpposite="//AufrigusbedaBobofrinulaugudator/agububoBeBoNulAuNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrinulAutor" eSuperTypes="//BraubidaBigusbobies"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaDabebebebeguGugusCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudaNulautin" ordered="false" upperBound="-1" eType="//AlbibegusbobobibeboFriboNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuNulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABiBobiNulAubiNulaunulaunulEs"/>
</ecore:EPackage>
