<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eugugunulaulius" nsURI="http://hub.de/rcore/examples/eugugunulaulius" nsPrefix="ms">
  <eClassifiers xsi:type="ecore:EClass" name="AubiBufrinulAuBufributin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlFrigugusFrigufribuBobinus" eSuperTypes="//AubiBufrinulAuBufributin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBobeFridaBebebiGusbedabefriGuLius" ordered="false" upperBound="-1" eType="//AubiBufrinulAuBufributin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidanulaunulAubufribinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudaGubibeBugubeboNulauCio" ordered="false" eType="//ABubobufrinulaugusNus" eOpposite="//ABubobufrinulaugusNus/faBodaBobiguFriTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaNulaugusBuFrinulaubiDanus" instanceTypeName="typeEbigubobeFrinulAutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBefribebunulauGufribotin" eSuperTypes="//AubiBufrinulAuBufributin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubedabeBibegubibobilus" ordered="false" upperBound="-1" eType="//BidanulaunulAubufribinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadaGusbeGusnulaubufribolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusnulaufrinulaunulaudaBeNus" ordered="false" upperBound="-1" eType="//BidanulaunulAubufribinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuGuGusbogubibilius">
    <eLiterals name="AlaugugugugusBufritor"/>
    <eLiterals name="DiFribebefridaFriGusauboDagusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulAugusNulAugudanulaubibubiDacio" eSuperTypes="//AlFrigugusFrigufribuBobinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGusBoguguGubibidaFrinulius" ordered="false" upperBound="-1" eType="//AbiBibudaGubofrinulaubucio" eOpposite="//AbiBibudaGubofrinulaubucio/baboGusnulAuNulAunulaufribiNulaugucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBidabuBufribobegunulius" ordered="false" upperBound="-1" eType="//DugubiDabudaNulAuFriBuguTus" eOpposite="//DugubiDabudaNulAuFriBuguTus/dobiBuguguFriBecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusaubebeDaguboGuses" eSuperTypes="//AubiBufrinulAuBufributin //AlFrigugusFrigufribuBobinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGuboBigusfribofriBiFribifritus" ordered="false" eType="//AlFrigugusFrigufribuBobinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGugufriDaGufries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eububedafriGugusgusEs" upperBound="-1" eType="//AuGuGusbogubibilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ADaguboboGuNulauBuBubiGubeBinulIus" instanceTypeName="typeBenulaubunulauFriGuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiDafrigusdabefriBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubuBenulauBedabobidanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EboguGusnulauGusdafribeFricio" eSuperTypes="//FadaGusbeGusnulaubufribolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebuFriBubedaCus" ordered="false" eType="//Braubofrigusnulaubolus" eOpposite="//Braubofrigusnulaubolus/badaBidaBeBidanulaugusNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbibubebifriGunulaubolus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabudaguGubiFries" eType="//ADaguboboGuNulauBuBubiGubeBinulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Braubofrigusnulaubolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBefrifrinulAuguBedaguscio" ordered="false" eType="//DiDafrigusdabefriBicio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfrigusnulauCio" ordered="false" upperBound="-1" eType="//DiDafrigusdabefriBicio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="badaBidaBeBidanulaugusNulautin" ordered="false" upperBound="-1" eType="//EboguGusnulauGusdafribeFricio" eOpposite="//EboguGusnulauGusdafribeFricio/ebuFriBubedaCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudabebifrifriboDagusaufrigusFrinus" ordered="false" eType="//AubuBenulauBedabobidanules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagubegusgugugubugusgusfrigusGuscio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubeBogusguGubidadabeguscus" eSuperTypes="//Braubofrigusnulaubolus //BidanulaunulAubufribinus //BiNulAugusNulAugudanulaubibubiDacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlAugubiBufriGusNulAuBifrigustin" abstract="true" eSuperTypes="//FadaGusbeGusnulaubufribolius //BeGusaubebeDaguboGuses //BrAubeBogusguGubidadabeguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabedabeboDatin" ordered="false" eType="//DiDafrigusdabefriBicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BraugubunulauFriBufriLus">
    <eLiterals name="DobunulauguDadaBeBefriGustor"/>
    <eLiterals name="Braubogutus"/>
    <eLiterals name="DubuBigusBedaGusguBibegusnulaubelus"/>
    <eLiterals name="DobobebeBibetin"/>
    <eLiterals name="BraudabodabofribeBunus"/>
    <eLiterals name="EuGudaguDagubonus"/>
    <eLiterals name="AuguGugugusAunulaunulauBuBecio"/>
    <eLiterals name="FaDabonulaunus"/>
    <eLiterals name="BaNulaubeboGusbotus"/>
    <eLiterals name="DubuBeguFriBeBeBoTus"/>
    <eLiterals name="ABobodaFriBeboDabeFriTus"/>
    <eLiterals name="EbunulaubuBodabifriBiGusgusdaBues"/>
    <eLiterals name="AlBugudafriBonulAuBiDator"/>
    <eLiterals name="AbeBeCus"/>
    <eLiterals name="DuGustor"/>
    <eLiterals name="DagusdafribebebufribubuguCus"/>
    <eLiterals name="AlbebiNulEs"/>
    <eLiterals name="EufribuGusBenulaudaNulEs"/>
    <eLiterals name="DogugusGusbibuBububiBocus"/>
    <eLiterals name="DibiNulaudaBuGuFriboBibeBibenulauDaCus"/>
    <eLiterals name="DudabeGusguboGusBofribulius"/>
    <eLiterals name="Badanulaufrigufrifritin"/>
    <eLiterals name="BiGufrigusNules"/>
    <eLiterals name="BabudagusGudabonulAubiTin"/>
    <eLiterals name="AlbobodabobedaDaguBufriCus"/>
    <eLiterals name="EbuNulAuFriBoFriGusAuBoFriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubiBofriNulauCus" eSuperTypes="//BiBefribebunulauGufribotin //BidanulaunulAubufribinus //DiGugufriDaGufries"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FaNulauguDafriNulauDabugubucus">
    <eLiterals name="EufriboNulauGufriBonulauCio"/>
    <eLiterals name="BaBigusgusBubunulAubenus"/>
    <eLiterals name="ADanulaudaGuGusnulauBoGusBiBibutor"/>
    <eLiterals name="AnfribuGunulaubobudanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugusfriBeBogudaGusGusbuguscio" instanceTypeName="typeAldaboFribeBeGusbilus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Augusnulaunulaucio">
    <eLiterals name="DoboFriNulAutor"/>
    <eLiterals name="DobobidaFrinulaubulius"/>
    <eLiterals name="EudaGusBigusNulAuFridanules"/>
    <eLiterals name="BebeGubiBobogugusgusbocus"/>
    <eLiterals name="DoguboguBibibifriDadacus"/>
    <eLiterals name="DidabobibeGugusbobiguscus"/>
    <eLiterals name="AugunulauboBogubobofriboTin"/>
    <eLiterals name="Bebubofrinules"/>
    <eLiterals name="BenulaubinulaubonulEs"/>
    <eLiterals name="BrAuBogubuBoBobocus"/>
    <eLiterals name="AlGusgusbibofrinus"/>
    <eLiterals name="AnbobebedaBubuTin"/>
    <eLiterals name="AugubofribogusNulaubiNulAunus"/>
    <eLiterals name="Dogusdabenulaunulautus"/>
    <eLiterals name="EuGufriboCio"/>
    <eLiterals name="BanulaubeBibebuFribudator"/>
    <eLiterals name="AlbobibuGubogusbulus"/>
    <eLiterals name="FagunulauBeDaBoBubeboNus"/>
    <eLiterals name="AlbubuGusBeBobeNules"/>
    <eLiterals name="AbegufribuBoBoBocus"/>
    <eLiterals name="BiguboGusauGusCus"/>
    <eLiterals name="AuNulauBudaboBobeNus"/>
    <eLiterals name="AlnulauBogusgusgusauboBetus"/>
    <eLiterals name="EuBibugusguboNulaubigubuGustin"/>
    <eLiterals name="EunulauDaDaBobolus"/>
    <eLiterals name="FagugusaubegusfriFriTus"/>
    <eLiterals name="AnulAunulius"/>
    <eLiterals name="Dubebobicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuDaBegusGudaNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobuBebonulaubudagusBobubudator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbefridaBoGufribobeCus" eSuperTypes="//AlFrigugusFrigufribuBobinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusAunulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubogubuBegusLus" eSuperTypes="//EboguGusnulauGusdafribeFricio //BrAubeBogusguGubidadabeguscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EbibufribugubeGusDagulius" instanceTypeName="typeDobibunulAuBebiDalus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FabuFrinulaubigusGusfribicio">
    <eLiterals name="BabubegusButor"/>
    <eLiterals name="DubogusFriBodanulius"/>
    <eLiterals name="DiFribiBuBidabicio"/>
    <eLiterals name="DuBegusdagusbiTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibibugusbobofrigudabogusCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="befriGuDabobenulaudatus" eType="//ADaguboboGuNulauBuBubiGubeBinulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulaubiBoFriBoBuBotus" eSuperTypes="//FadaGusbeGusnulaubufribolius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiNulAuBobebedacus" instanceTypeName="typeAnulAunulauBubufriNulauLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBibeboFribetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagubibubuDafrinulIus" eType="//AubiBufrinulAuBufributin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusDabeDaBiCio" eSuperTypes="//DiGugufriDaGufries //EboguGusnulauGusdafribeFricio //AngusAunulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aFrigufridabofriGutus" ordered="false" eType="//AlAugubiBufriGusNulAuBifrigustin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aFrifribedaFriboboFritor" ordered="false" eType="//AlFrigugusFrigufribuBobinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldabegubegubiNulAubedaNulius" ordered="false" eType="//DabuBebibegues" eOpposite="//DabuBebibegues/adaBuBugusgusBifriBifriTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoDaBoboguBoBebugulus" instanceTypeName="typeEbibebefridaNulauGuButor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusfrigusguFrinulAubinulAubutor" eSuperTypes="//BeGusaubebeDaguboGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadadaguBenulaunulauDadanulEs" abstract="true" eSuperTypes="//DuBibeboFribetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeGusaufriBoGunules" eSuperTypes="//AuDaBegusGudaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABubobufrinulaugusNus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBodaBobiguFriTin" ordered="false" eType="//BidanulaunulAubufribinus" eOpposite="//BidanulaunulAubufribinus/eudaGubibeBugubeboNulauCio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubedagubuBoFrinulIus" eType="//FaNulauguDafriNulauDabugubucus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBuBobebiBoboDaFrinulaufricio" eType="//DoDaBoboguBoBebugulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbodadadabuBiBeguCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBubigububucus" eSuperTypes="//BidanulaunulAubufribinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbiBibudaGubofrinulaubucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baboGusnulAuNulAunulaufribiNulaugucio" ordered="false" eType="//BiNulAugusNulAugudanulaubibubiDacio" eOpposite="//BiNulAugusNulAugudanulaubibubiDacio/daGusBoguguGubibidaFrinulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="efriGusGubunulAuTor" ordered="false" eType="//BeGusaubebeDaguboGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbobiBobiNulauboLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibofriBugusnulaubibegustor" eSuperTypes="//BrAubogubuBegusLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agudaBiTin" eType="//DaNulaugusBuFrinulaubiDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBufrigusgufriGugububolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGufribinulaufribenus" eSuperTypes="//ABubobufrinulaugusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beguDaBubuBunulAufribetin" ordered="false" upperBound="-1" eType="//FagusbobiBobiNulauboLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugusNulAugusfriboBinulauGutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubogusnulaubudabububoBinus" instanceTypeName="typeEubeFriBofriBedabicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubuguGusboBogusCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobububobiboNus" eType="//DaNulaugusBuFrinulaubiDanus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beGubeBiGusbotor" upperBound="-1" eType="//AuGuGusbogubibilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuboGusbeGusdabinulautor" instanceTypeName="typeEuBebuNulauGusNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnboNulauGunulaububocus">
    <eLiterals name="AlfrigusGusaunulaulius"/>
    <eLiterals name="BaBibiGusnulAubudadacio"/>
    <eLiterals name="DigusbeBeBufriGusBugucus"/>
    <eLiterals name="DofriGudafrinulauBeNulaubies"/>
    <eLiterals name="Aldadabebidagusbees"/>
    <eLiterals name="DaboGuNulAudabebobeBoGubofritus"/>
    <eLiterals name="DubegusboBibonulaubobufribucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANulAuFriBuNulAubiNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaFribudaBonulaugubolus" eSuperTypes="//ANulAuFriBuNulAubiNules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafribigufrifritus" eType="//DubogusnulaubudabububoBinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaboBoLus" abstract="true" eSuperTypes="//AbiBibudaGubofrinulaubucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBeFriBofrigusboGugusTin" upperBound="-1" eType="//AlAugubiBufriGusNulAuBifrigustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaudadabufrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabigunulaufribiBiTus" instanceTypeName="typeAbogubinulaubibiTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugubiDabudaNulAuFriBuguTus" abstract="true" eSuperTypes="//AubuBenulauBedabobidanules //AuDaBegusGudaNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobiBuguguFriBecio" ordered="false" eType="//BiNulAugusNulAugudanulaubibubiDacio" eOpposite="//BiNulAugusNulAugudanulaubibubiDacio/doBidabuBufribobegunulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diNulIus" upperBound="-1" eType="//DubogusnulaubudabububoBinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAugusbeBebeBiTor" eSuperTypes="//BeGusaubebeDaguboGuses //BibofriBugusnulaubibegustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadabigusgusnulaubiBuCus" ordered="false" eType="//BebigusbedaBoNulauboEs" eOpposite="//BebigusbedaBoNulauboEs/daguBibidabigusdaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauguTus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BenulauFriNulaubuBocus">
    <eLiterals name="AlBigusBoBinulaunulaucio"/>
    <eLiterals name="BagunulaunulAucus"/>
    <eLiterals name="AgusAubulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeBeBuBeDadaBies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAugusfrilus" ordered="false" eType="//Braubofrigusnulaubolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBunulAudaBoNulAubiBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBofribefriBigugudacio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabuNulaudabebuLius" eSuperTypes="//EbefridaBoGufribobeCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadabegufriBiBegucus" eSuperTypes="//DoBofribefriBigugudacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoguguGudafribiDaGusgusBebees" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabuBebibegues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diboBegunulaudatus" ordered="false" eType="//DubuguGusboBogusCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaBuBugusgusBifriBifriTin" ordered="false" eType="//BagusDabeDaBiCio" eOpposite="//BagusDabeDaBiCio/aldabegubegubiNulAubedaNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebigusbedaBoNulauboEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daguBibidabigusdaes" upperBound="-1" eType="//BenulAugusbeBebeBiTor" eOpposite="//BenulAugusbeBebeBiTor/fadabigusgusnulaubiBuCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiDabiDadanulAuboBugusbiEs" eSuperTypes="//EbefridaBoGufribobeCus //AubuBenulauBedabobidanules //EbibubebifriGunulaubolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebibonus" upperBound="-1" eType="//DobuBebonulaubudagusBobubudator"/>
  </eClassifiers>
</ecore:EPackage>
