<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eunulaucio" nsURI="http://hub.de/rcore/examples/eunulaucio" nsPrefix="NN">
  <eClassifiers xsi:type="ecore:EClass" name="EubeGubeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadanulauguBibunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibiGusAuboguEs" ordered="false" upperBound="-1" eType="//EubeGubeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAunulaudabobiNulaunulius" eSuperTypes="//EubeGubeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaubedabibiBibiGusbecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Algudanulaubobugusnus" eSuperTypes="//DanulaubedabibiBibiGusbecio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubonulaugusgusbeboGubuGubiLus" ordered="false" upperBound="-1" eType="//BifriNulAubiBeGubiTor" eOpposite="//BifriNulAubiBeGubiTor/dobeguFriboBiboFritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBuguBeDabobibodaes" abstract="true" eSuperTypes="//BadanulauguBibunules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubeBuBoguLius" instanceTypeName="typeBrauDabubigusbugusBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbogusGuGuslius" eSuperTypes="//Algudanulaubobugusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabiGuboBofrifrigubebibeTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbubuGusAubudafriBubocus" instanceTypeName="typeBebufrifriguGubufridaFries"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbebeNulaubedagucus" eSuperTypes="//AlnulAunulaudabobiNulaunulius //EBuguBeDabobibodaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubigufriDaBoBibigusdagusnulAuNus" eSuperTypes="//EbogusGuGuslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusDafribocus" ordered="false" eType="//Algudanulaubobugusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiguBonulaubibuBeFridanules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaubenulaunulAuDabunulauBibenus" ordered="false" eType="//Algudanulaubobugusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifriNulAubiBeGubiTor" abstract="true" eSuperTypes="//BiguBonulaubibuBeFridanules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebidanulaugusbiBibinulAuCio" ordered="false" eType="//AlnulAunulaudabobiNulaunulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobeguFriboBiboFritin" ordered="false" upperBound="-1" eType="//Algudanulaubobugusnus" eOpposite="//Algudanulaubobugusnus/dubonulaugusgusbeboGubuGubiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabugubudaTor" eSuperTypes="//EbogusGuGuslius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubebibuBebeGusdabebolus" eType="//AbubuGusAubudafriBubocus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AugusfriDabufrigusCio" instanceTypeName="typeBadabigusgusnulAubiboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusfriBuboNulaubutin" eSuperTypes="//EubeGubeCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euguGuBefriNulauFriCio" eType="//DubeBuBoguLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboNulaubofriBidaNulAugutin" eSuperTypes="//EbogusGuGuslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBiBubunulaugubobibuBeGugusLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGuBeBebobogusbeBibebenus" ordered="false" eType="//Algudanulaubobugusnus"/>
  </eClassifiers>
</ecore:EPackage>
