<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dugufrigubutor" nsURI="http://hub.de/rcore/examples/dugufrigubutor" nsPrefix="sEt">
  <eClassifiers xsi:type="ecore:EClass" name="Alaunulaubobetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubonulAubuNulauTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuGusnulAuBunulIus" ordered="false" eType="//Alaunulaubobetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigunulaubinulauFridaTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AububugudagunulaunulAulius" eSuperTypes="//DubonulAubuNulauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aboBobibuBenulaubutin" ordered="false" eType="//DubonulAubuNulauTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eNulauGusbutus" ordered="false" eType="//DubonulAubuNulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubifridaDabitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibeDabubibugudanulius" ordered="false" eType="//DubonulAubuNulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibiguBegugufrinulaubibobibibunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beguBodafrigugusDaBogugusfricio" ordered="false" eType="//DigunulaubinulauFridaTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubibeNulaunulauBugugusTus" eType="//DigunulaubinulauFridaTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribubiBobuBufribecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebibedaBubegugusbinulius" ordered="false" eType="//DigunulaubinulauFridaTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBuBigusdatus" ordered="false" upperBound="-1" eType="//DoDagubububobegusEs" eOpposite="//DoDagubububobegusEs/duboNulaubiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBogusdadaBugusguBegusbugusnules" eSuperTypes="//AububugudagunulaunulAulius //DigunulaubinulauFridaTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbunulAudaBiguBuGucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubobogusGusFriBuGudadafribetor" eType="//Alaunulaubobetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuDafriFrigusdagusBenulius" instanceTypeName="typeBiFribubigubeboLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBibiDaBobegusAubobegutor" eSuperTypes="//AububugudagunulaunulAulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoDagubububobegusEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euNules" eType="//AuDafriFrigusdagusBenulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duboNulaubiNus" upperBound="-1" eType="//AlfribubiBobuBufribecus" eOpposite="//AlfribubiBobuBufribecus/duBuBigusdatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboFriNulaubegutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabugusaububibebuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befribubugudabiGuBoBobidaTus" ordered="false" upperBound="-1" eType="//AububugudagunulaunulAulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusauNulaugudacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubugufriDadafribetor" eType="//AuDafriFrigusdagusBenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugubeGusnulaubifriDaBibogustor" eSuperTypes="//Alaunulaubobetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EboFriBufribiboBigubelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraufribuNulAubuNulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabidafrifribebibeLus" eType="//AuDafriFrigusdagusBenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBibenulauBubiBuBetus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeDabuFribobodadabiBiCio" eSuperTypes="//DiboFriNulaubegutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eudaNulAubogudaboDafricus" eType="//AuDafriFrigusdagusBenulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauNulaubodaGugusCio" eType="//AuDafriFrigusdagusBenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bidabebigugubunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babibeboNulauBunulauDagugusLius" ordered="false" eType="//AbunulAudaBiguBuGucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulAuBibibiGubegugusEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulaububibodadagucus" upperBound="-1" eType="//Bidabebigugubunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfribobobinulaunulAuLus" abstract="true" eSuperTypes="//FabugusaububibebuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beGusgugusgububebegusbocus" ordered="false" eType="//BraugubeGusnulaubifriDaBibogustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuboboGudanulaugubibelius" instanceTypeName="typeDubinulaubodadaFriBiBiGubilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauDaNulAunulaunulaugubunus" eSuperTypes="//DiboFriNulaubegutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldaguGunulAubucio" ordered="false" eType="//AlfribubiBobuBufribecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anulaudalus" eSuperTypes="//BraugubeGusnulaubifriDaBibogustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abigusBugubiBoBuboCus" ordered="false" upperBound="-1" eType="//AbunulAudaBiguBuGucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="br" eType="//EuboboGudanulaugubibelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BiboGugufribidaDabefriTus">
    <eLiterals name="EbibibiGufridaGusgubuGubegusBegues"/>
    <eLiterals name="ABuBigusguBuTor"/>
    <eLiterals name="DadagusnulaufriDaGusguNulius"/>
    <eLiterals name="DafribunulaufriDabuDanus"/>
    <eLiterals name="Edadafrigucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigubunulaugusbeEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBoguBoBubefriNulauLius" ordered="false" eType="//BraugubeGusnulaubifriDaBibogustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabigudaFriboBubuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGubigusBuGubodaNus" eSuperTypes="//Bidabebigugubunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebuTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biGusfrigusboDabebebibuCio" eType="//AuDafriFrigusdagusBenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubefribiNulAugusbuboGuscio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabenulAunulAucus" eType="//BiboGugufribidaDabefriTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biDanulaubofribeLus" eType="//BiboGugufribidaDabefriTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubegusbeDagusBofrinulAubitin" eSuperTypes="//DoDagubububobegusEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbugusGusaugubugusGusbibigusBulus" upperBound="-1" eType="//DiboFriNulaubegutus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulaudaGubiGunulauFriBugusbibolus" ordered="false" eType="//BigubunulaugusbeEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albibibenulaugubutin" eType="//BiboGugufribidaDabefriTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ABuboGusgugubudanulaudacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraufribeBufribebeBodanus" eSuperTypes="//BraugubeGusnulaubifriDaBibogustor //AlfribubiBobuBufribecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGunulAugusbolus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbiNulaugufrigusBofriBenulauboNus" instanceTypeName="typeEunulauBoBebonulAutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DadagusGusbufritin" instanceTypeName="typeBrAutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebuGusfribeFriBucio" eSuperTypes="//Bidabebigugubunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusgusaudagusdaBodabugubegucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBuBibibiGubebugusaubidaDalus" ordered="false" eType="//BebuGusfribeFriBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulaugunulaunulauBegubibiBuFribeLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beboBonulauBuFriButor" ordered="false" upperBound="-1" eType="//EboFriBufribiboBigubelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBenulAugusnulauboCio" eSuperTypes="//BrauDaNulAunulaunulaugubunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidabodagusbigubeguboDalius" upperBound="-1" eType="//DoDagubububobegusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaguboEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusbiBuguboGunulaulius" ordered="false" upperBound="-1" eType="//Bidabebigugubunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABogubofriBigustin" eSuperTypes="//DiboFriNulaubegutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audagusLius" eType="//AlbiNulaugufrigusBofriBenulauboNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAugudadaBigusbegunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaDagusBunulauGusBoboNus" ordered="false" upperBound="-1" eType="//DubonulAubuNulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagunulauGusNulAufriBebucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusfrigugustin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dunulaubebefriFriEs" eType="//AuDafriFrigusdagusBenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBiNulaugugububeNulAuFrilius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DubunulAubenulAuBibiBuLus">
    <eLiterals name="AfrinulIus"/>
    <eLiterals name="DunulaubebebobebegudaCus"/>
    <eLiterals name="AnbunulaufrigugusLius"/>
    <eLiterals name="DabeBobedaBogubofrifrilius"/>
    <eLiterals name="BibobinulaunulauFriDabibudaCio"/>
    <eLiterals name="FaGusgubeboGubebocus"/>
    <eLiterals name="FadanulAufriguFrinulAutus"/>
    <eLiterals name="DaGusBiTor"/>
    <eLiterals name="FaBubeGusbefrifriDafribeFrilius"/>
    <eLiterals name="EubifridaGubenulauGuBebuLus"/>
    <eLiterals name="BrAuFrigusBeBifribiCus"/>
    <eLiterals name="BaBeNulaugugugusnus"/>
    <eLiterals name="Abunulaudabegusbebinulius"/>
    <eLiterals name="AnbeboGudafriboDagubofrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAugusgusnulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ebedanulaubodagusgunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augubiBicio" upperBound="-1" eType="//ABuboGusgugubudanulaudacio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabebobebigubuEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBegusbeFrigusgutus" abstract="true" eSuperTypes="//Alaunulaubobetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBiDabubuGunulauguguTin" eSuperTypes="//AbunulAudaBiguBuGucio //FabugusaububibebuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibodagusboNulaubeBolius" ordered="false" eType="//AbunulAudaBiguBuGucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baNulauBifriboBenulauLus" eType="//BiboGugufribidaDabefriTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagunulaugusBeBibobifrinulAutus" eSuperTypes="//BeBenulAugusnulauboCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafribiNulauBiNus" ordered="false" eType="//BiBeBofridagububibiDagugustor" eOpposite="//BiBeBofridagububibiDagugustor/albobebedabubues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaFrinulAubebubofriDatin" instanceTypeName="typeDiFribeDanulaudafriGubiFrigusBeNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusdaBobonulauDabulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbigubeBobuGubobuFriBocio" eSuperTypes="//BrauDaNulAunulaunulaugubunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusBodadabebegugusguNules" eSuperTypes="//AuGubigusBuGubodaNus //AlBibenulauBubiBuBetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBeBofridagububibiDagugustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albobebedabubues" ordered="false" upperBound="-1" eType="//FagunulaugusBeBibobifrinulAutus" eOpposite="//FagunulaugusBeBibobifrinulAutus/fafribiNulauBiNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daNulauGusius" ordered="false" eType="//DugusgusaudagusdaBodabugubegucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaNus" eSuperTypes="//DabebobebigubuEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabebufridagusBobegulius" eType="//AuDafriFrigusdagusBenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANulauGusbegusBeNulauBecio" abstract="true"/>
</ecore:EPackage>
