<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dabobobunules" nsURI="http://hub.de/rcore/examples/dabobobunules" nsPrefix="bN">
  <eClassifiers xsi:type="ecore:EClass" name="AunulAuGubigusguBotor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibogufribegubeDabolius" ordered="false" upperBound="-1" eType="//DuFriboBogusBebogugubuNules" eOpposite="//DuFriboBogusBebogugubuNules/euNulaufribedagubeguGugusgudabubiNulaugusnules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBodadabodaBebidaBegusLius" eSuperTypes="//AunulAuGubigusguBotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgufribubinulAugusBufrigusbuguEs" eSuperTypes="//AunulAuGubigusguBotor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befriBoDaBedabidabulius" ordered="false" upperBound="-1" eType="//BiBobeguBiBonulAucus" eOpposite="//BiBobeguBiBonulAucus/eBibonulaugusdaGuBogusbulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBobeguBiBonulAucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBibonulaugusdaGuBogusbulius" ordered="false" eType="//AlgufribubinulAugusBufrigusbuguEs" eOpposite="//AlgufribubinulAugusBufrigusbuguEs/befriBoDaBedabidabulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusbufribufriBuBuBecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbubuNulAuboDafriboDaes" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGugufriCus" ordered="false" eType="//AunulAuGubigusguBotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBegufritus" eSuperTypes="//BiBobeguBiBonulAucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboFribeboNulAuGusaufriDatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBobibofribodabeBebeGusius" ordered="false" eType="//AbubuNulAuboDafriboDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabebebebububiBuButor" eSuperTypes="//AunulAuGubigusguBotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobigunulAudanus" eSuperTypes="//AgusbufribufriBuBuBecus //BiBegufritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beFribuBobues" ordered="false" eType="//BaBodadabodaBebidaBegusLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusdagubobibefriguBunules" ordered="false" upperBound="-1" eType="//AgusbufribufriBuBuBecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofribufribiGusNulaunulius" eSuperTypes="//AgusbufribufriBuBuBecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBobufrinulaufrinulaubuguslus" ordered="false" upperBound="-1" eType="//BaBodadabodaBebidaBegusLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulaugugusBufridacio" ordered="false" eType="//AboFribeboNulAuGusaufriDatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibunulAubodadabuGuDadanus" eSuperTypes="//BiBegufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABudaBugubufridaBugucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoDabenulaugusbinulauNules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EbubodaTus">
    <eLiterals name="AngudagubiCio"/>
    <eLiterals name="DadabibuBunulaugusnulaubeNus"/>
    <eLiterals name="DiBuGubudaBunus"/>
    <eLiterals name="AndanulauDafrigubegusfriGutor"/>
    <eLiterals name="BifrinulaubigugunulAuFrinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiguDaGuGusAunulaugugusFribuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGubifriGubibiBubudafribugulius" ordered="false" eType="//AgusbufribufriBuBuBecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabeGuGusbuBebeNulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriboBogusBebogugubuNules" abstract="true" eSuperTypes="//ABudaBugubufridaBugucus //FabebebebububiBuButor //AlbiguDaGuGusAunulaugugusFribuCio //BabeGuGusbuBebeNulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euNulaufribedagubeguGugusgudabubiNulaugusnules" ordered="false" upperBound="-1" eType="//AunulAuGubigusguBotor" eOpposite="//AunulAuGubigusguBotor/bibogufribegubeDabolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAuboGusbinulaubofribinus" eSuperTypes="//BibunulAubodadabuGuDadanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabudanulaudaBebogues" upperBound="-1" eType="//AunulAuGubigusguBotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusAunulAuNulaulus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudabubeBebugububutus" abstract="true" eSuperTypes="//AbubuNulAuboDafriboDaes //AlgufribubinulAugusBufrigusbuguEs //AboFribeboNulAuGusaufriDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusbeGusbigugusGusTus" abstract="true" eSuperTypes="//ABudaBugubufridaBugucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alAubebufriTus" eType="//EbubodaTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebubofrinulauGusnulAudagubocio" eSuperTypes="//EuGusAunulAuNulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadanulauNulaugusbolius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagusGuBiBeDabeGubugudaLius" instanceTypeName="typeEdabucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbedabenulauBuboGutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="andalius" eType="//FagusGuBiBeDabeGubugudaLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafriBubeTin" ordered="false" eType="//BanulAuboGusbinulaubofribinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bifrigudabudagucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobeGubedagusbiDacio" eSuperTypes="//AgusbufribufriBuBuBecus //FabebebebububiBuButor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidaGufrinulAugusbubugucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaBeguBobogustor" ordered="false" upperBound="-1" eType="//EuGusAunulAuNulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauNulaufridadaEs" eSuperTypes="//BibunulAubodadabuGuDadanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGusbofridabiGusgusdaEs" eType="//Bifrigudabudagucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DinulaugunulauGulus">
    <eLiterals name="Dalius"/>
    <eLiterals name="DabubiBiGusnulius"/>
    <eLiterals name="BabigusbunulAubotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubodaBibigusfridabicus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EboGusgufrigutor" instanceTypeName="typeEBunulaunulAubiNulauNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusfribunulaubugusAubidaCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibubeNulauFriBucio" eSuperTypes="//AlbiguDaGuGusAunulaugugusFribuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alDanulAucio" eType="//EboGusgufrigutor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubeBogusbubulius" ordered="false" upperBound="-1" eType="//BagusfribunulaubugusAubidaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBoguboBiFriGues" eSuperTypes="//AngusbeGusbigugusGusTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusAubunulAubinules" instanceTypeName="typeDufrifrigubonulauBufrigusgutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulauBidaFribigutus" eSuperTypes="//AunulAuGubigusguBotor //BanulAuboGusbinulaubofribinus //AboFribeboNulAuGusaufriDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aufribugusbifrinulautor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfrinulauguBiguNus" ordered="false" eType="//BabiNulAuNules" eOpposite="//BabiNulAuNules/alNulaubilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBiBibofrifriBoGusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agugusgusaufrilius" ordered="false" eType="//BeGuGugugusbugues" eOpposite="//BeGuGugugusbugues/faBebudabuBeBoFritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGuGugugusbugues" eSuperTypes="//AlnulauBidaFribigutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBebudabuBeBoFritin" ordered="false" upperBound="-1" eType="//FaBiBibofrifriBoGusNus" eOpposite="//FaBiBibofrifriBoGusNus/agugusgusaufrilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudagusgusBudaguBoTin" eType="//FabebebebububiBuButor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBoBogusDabubibebuguguCio" ordered="false" upperBound="-1" eType="//BagusfribunulaubugusAubidaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnboNulauguBebiDabufriGusbilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabogusbiguBedabogusgutin" abstract="true" eSuperTypes="//BaBodadabodaBebidaBegusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebubebiboBidadacus" abstract="true" eSuperTypes="//BanulAuboGusbinulaubofribinus //AgusbufribufriBuBuBecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBebiGusBiBiguDaNulAugustin" ordered="false" eType="//FafriTor" eOpposite="//FafriTor/dubibenulAudaBoFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAuGuGuslius" eSuperTypes="//AlgufribubinulAugusBufrigusbuguEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agusnulaulus" eSuperTypes="//BanulAuboGusbinulaubofribinus //BagusfribunulaubugusAubidaCio //AgusbufribufriBuBuBecus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afriGubeFricus" eType="//DugusAubunulAubinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBubeGusbuNulautus" eSuperTypes="//BebubofrinulauGusnulAudagubocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abebegusbigusius" eType="//DinulaugunulauGulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaDadabebiguFribobonulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabubonulaudabunulaubobeBinulius" ordered="false" eType="//BadanulauNulaugusbolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGusbufrigusgusbebunulAuNus" ordered="false" eType="//EBoguboBiFriGues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EudadabidaBigusNulius" instanceTypeName="typeDibiGusdabeBetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuboGuBuFriDaboNulAuFritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabigusfribobobibolius" eType="//AunulAuGubigusguBotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAuBoGufribunulauguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBofriFribenulaubecio" abstract="true" eSuperTypes="//AbubuNulAuboDafriboDaes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBebufrigudaFrigutor" eType="//DugusAubunulAubinules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabedaNulauFribibeEs" ordered="false" upperBound="-1" eType="//EuGusAunulAuNulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeFrigusbubies" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlBiguDabuBofribobeLius" instanceTypeName="typeDiBoGusfribifritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadanulauNulaufridaBibibetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daNulauguFriNules" ordered="false" eType="//DuBofriFribenulaubecio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beFriNulaudaguDaGubebegubetin" upperBound="-1" eType="//EuGusAunulAuNulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubinulaubuGusgugugusauguslius" instanceTypeName="typeAngusgunulaugusGuBeBufribefriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnNulauNulAugufribibulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulAufriNulAubuBifribugusNus" ordered="false" eType="//Aufribugusbifrinulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigubeGusNulaubeFrinus" eSuperTypes="//AboFribeboNulAuGusaufriDatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anNulaubilus" eType="//EboGusgufrigutor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biNulauFribeGusbobubebotor" ordered="false" eType="//BebubofrinulauGusnulAudagubocio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abinulaubobidanulaunulaubefribeGuslius" ordered="false" eType="//AnboNulauguBebiDabufriGusbilius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBufribiDafriFriGusfribiCus" eType="//DugusAubunulAubinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafriTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibenulAudaBoFricus" ordered="false" eType="//BebubebiboBidadacus" eOpposite="//BebubebiboBidadacus/duBebiGusBiBiguDaNulAugustin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebigusdafrifrifriGusauCus" eType="//AlBiguDabuBofribobeLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabiFribeNulaugusFries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBubebiGusbidaGuLus" ordered="false" eType="//DuboGuBuFriDaboNulAuFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubeDaGuFrinus" abstract="true" eSuperTypes="//DofribufribiGusNulaunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobedanus" eType="//EudadabidaBigusNulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubefribeBubefribobifritus" eType="//AlBiguDabuBofribobeLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubebudadaFribinulAuNulius" upperBound="-1" eType="//AnbiNulaufrinulAunulIus" eOpposite="//AnbiNulaufrinulAunulIus/diNulaufrigusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Befrigugubunulaudagubinus" eSuperTypes="//BebubofrinulauGusnulAudagubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebefribububoBibogusfrigutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfribibeboDaDanulauGusTor" upperBound="-1" eType="//FagusGuBiBeDabeGubugudaLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubebebuguBebuTus" ordered="false" upperBound="-1" eType="//EDabigusIus" eOpposite="//EDabigusIus/anBuboGusbefribubegubuBotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusBuNulaunulauGubinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbebiGubidabeFrifriGusnulaunus" eSuperTypes="//BaBodadabodaBebidaBegusLius //AlaubeDaGuFrinus //FafriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDabigusIus" eSuperTypes="//AbubuNulAuboDafriboDaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBuboGusbefribubegubuBotus" upperBound="-1" eType="//BebefribububoBibogusfrigutin" eOpposite="//BebefribububoBibogusfrigutin/dubebebuguBebuTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBebeboBugusfribuDagutor" eType="//AlBiguDabuBofribobeLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguGuNulaunulauGunulAugusbeCio" ordered="false" eType="//DidaGufrinulAugusbubugucus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulauGusfribigusbonulius" eType="//DugusAubunulAubinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnguBiBufribeGuGuBinus" eSuperTypes="//AnboNulauguBebiDabufriGusbilius //DuFriboBogusBebogugubuNules //EuGusAunulAuNulaulus //DuBofriFribenulaubecio //DofribufribiGusNulaunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobubeBonulAubibeGusgustin" eType="//EudadabidaBigusNulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babifrifrifribibobotus" eType="//EubinulaubuGusgugugusauguslius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiNulAuNules" eSuperTypes="//BaBodadabodaBebidaBegusLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulaubilus" ordered="false" upperBound="-1" eType="//Aufribugusbifrinulautor" eOpposite="//Aufribugusbifrinulautor/alfrinulauguBiguNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bifribudanulaudabotor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubuBuBeGubeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braufrinulaubefribebutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubobefribobobecio" ordered="false" eType="//BraudabubeBebugububutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AboGusDaboNulaunulaulius" instanceTypeName="typeEbeguFriGuDagudabogufriTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidanulauBidabubefribiguslius" eSuperTypes="//Braufrinulaubefribebutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulaugugugucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBigusFridabuguFrinus" eSuperTypes="//BaBodadabodaBebidaBegusLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafrinulaubelus" eType="//BebefribububoBibogusfrigutin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBebuBobuGubogubebucus" ordered="false" upperBound="-1" eType="//EDabigusIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabuBufrifrinulaunulaubiEs" eSuperTypes="//DabiFribeNulaugusFries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibebuNulautus" eSuperTypes="//Agusnulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubeGuFribobuTin" eSuperTypes="//AnNulauNulAugufribibulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaGuslius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubonulaubugusEs" eType="//DinulaugunulauGulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusbefriDaBocus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigubogusaubefriGubebies" eSuperTypes="//Bifrigudabudagucus //FaBiBibofrifriBoGusNus //BagusBuNulaunulauGubinus //BiBegufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudadaDatus" eSuperTypes="//AboFribeboNulAuGusaufriDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusfriBunulaunus" abstract="true" eSuperTypes="//BadanulauNulaugusbolius //EDabigusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubebuFriGubebodacio" eSuperTypes="//AboFribeboNulAuGusaufriDatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="difriBudaNulauGusGusbuguGuboGusGusius" ordered="false" eType="//BeFrigusbubies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabebuBiGusNulaufriFriBogusBoTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anNulaugusNulEs" eType="//DugusAubunulAubinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidabobogunulAubobuBibuTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebefribobugubobubegufrinulaucus" ordered="false" upperBound="-1" eType="//DaDaGuslius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egubibofriBuTin" eType="//EudadabidaBigusNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BafridabunulAuBeguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribiboBigusbebofries"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagugusbebegusGusFriDacio" instanceTypeName="typeDifriBogusbuBiBiNulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiNulAugusnulaugugusguDadabitin" instanceTypeName="typeDifrifribebinulaunulAulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebuboBobebubiguTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuguTin" upperBound="-1" eType="//EudadabidaBigusNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdagubebigubeFrigubigusbonulaulus" abstract="true" eSuperTypes="//BabuBufrifrinulaunulaubiEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babiBugubiBobefriGulius" eType="//DiNulAugusnulaugugusguDadabitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboboDatin" eSuperTypes="//DadanulauNulaufridaBibibetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBoFrifribiBogubebeBinulauBefribeTor" abstract="true" eSuperTypes="//DoDabenulaugusbinulauNules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugubiNulaugusgucio" eType="//EbubodaTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alFriDalus" eType="//DiNulAugusnulaugugusguDadabitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBiGusBiFrinulauBibocus" eSuperTypes="//BibunulAubodadabuGuDadanus //BebuboBobebubiguTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauBibubutin" instanceTypeName="typeBebubeGuBiGuGusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBobugubuGusbubibedaDagulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulaububefridaGusAubifriBubies" ordered="false" eType="//BiBobeguBiBonulAucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBenulaugusbobunulAubees" eSuperTypes="//BeFrigusbubies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadaDabenulaugusGusgusbenulaubeGunus" eSuperTypes="//AnguBiBufribeGuGuBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaguBuGusguboDabonulAubuGuNus" eSuperTypes="//BeBiGusBiFrinulauBibocus //BabuBufrifrinulaunulaubiEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebobibeBufrigusgusgusbobees"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlFridafribunulAuGuBidagusbiGuBilius" eSuperTypes="//ABudaBugubufridaBugucus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DubuFriEs">
    <eLiterals name="Begusgusgusnulaugusfribonus"/>
    <eLiterals name="Aubofrigubecus"/>
    <eLiterals name="DobigubugusdaNules"/>
    <eLiterals name="DaDabibubobugusgusfrigunulautin"/>
    <eLiterals name="AFrinulaugusguBefrigusbefritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubiboBuGuses" eSuperTypes="//BagusfribunulaubugusAubidaCio //AnaubuBuBeGubeTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbogusBibocio" eType="//DiNulAugusnulaugugusguDadabitin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboGubinulaugunulEs" upperBound="-1" eType="//BebuboBobebubiguTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaDafribebiGufribinulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubedaFribonulaubebeBegusGusguslus" ordered="false" eType="//EubodaBibigusfridabicus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusBedafribebucus" upperBound="-1" eType="//DuBofriFribenulaubecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnulauNulaulus">
    <eLiterals name="DibeGuDaDagusbinulaugusnulaufriEs"/>
    <eLiterals name="EuBidanulauguGusguBuBiGues"/>
    <eLiterals name="BibogusdaNulaubiboFriGunus"/>
    <eLiterals name="DubobuboDabedaBubofritor"/>
    <eLiterals name="EudanulaubodaGuDaGusbogunules"/>
    <eLiterals name="EFriBigusFrigusDaCus"/>
    <eLiterals name="AuboboFriboboBefribiBiCio"/>
    <eLiterals name="EugusBudafribeBitin"/>
    <eLiterals name="DiNulaubugusGusaufrigusdanus"/>
    <eLiterals name="BebonulAugusgufrilus"/>
    <eLiterals name="DubobiDagusGunulauBocio"/>
    <eLiterals name="DonulAunulauBigusbebinus"/>
    <eLiterals name="DubugusbububibedaBunulIus"/>
    <eLiterals name="AlbeNulAuBidaBoDagusbeBoTin"/>
    <eLiterals name="BaguboGuBeboguboBinulaulius"/>
    <eLiterals name="AubogusAuFribitin"/>
    <eLiterals name="DabebunulaufrigusAuDadaBitus"/>
    <eLiterals name="DoBuDabebibuDagusbonules"/>
    <eLiterals name="BegugusbebufriGusnulautin"/>
    <eLiterals name="EuBeDafrinulauNulAuFriBiBuBebenulaulius"/>
    <eLiterals name="BeBiNulaubotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusdanulaudaGusgucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Binulaugulus" eSuperTypes="//BabeGuGusbuBebeNulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiNulaufrinulAunulIus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diNulaufrigusius" ordered="false" eType="//AlaubeDaGuFrinus" eOpposite="//AlaubeDaGuFrinus/dubebudadaFribinulAuNulius"/>
  </eClassifiers>
</ecore:EPackage>
