<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aubogugunus" nsURI="http://hub.de/rcore/examples/aubogugunus" nsPrefix="syO">
  <eClassifiers xsi:type="ecore:EClass" name="DanulauGusfriGugubecio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuBenulaunulaunulAunulaulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusgusnulAugubuGuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="difridaguguDaCio" ordered="false" upperBound="-1" eType="//DanulauGusfriGugubecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaboNulaubibigusBuDacus" instanceTypeName="typeFaBeNulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EboNulAubodabedafriboNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfribibubidaDabeGudaGusDadaboTin" eSuperTypes="//DanulauGusfriGugubecio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babobuBiBibiCus" eType="//FaGuBenulaunulaunulAunulaulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobiboBenulAudaDabiBiBibinus" ordered="false" eType="//EuGusgusnulAugubuGuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFriBufriBiDadagusautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaubeNulius" upperBound="-1" eType="//DanulauGusfriGugubecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ABububefriNulauBodatus">
    <eLiterals name="FadaGubedabuGuDagubibudaboNus"/>
    <eLiterals name="BrauDaGugubiNus"/>
    <eLiterals name="DibuGudagusbubugusbuLus"/>
    <eLiterals name="BrAudabiguGusdafribeNulauCio"/>
    <eLiterals name="EuBedagubudaguGugusBugugusIus"/>
    <eLiterals name="EbinulauGusnulaubibuguBebunules"/>
    <eLiterals name="AlBeBubuBonulaufriBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDatus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaubuCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EgusauBibunulAuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bigusbubobedagutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusBibegusbiFriGues" ordered="false" upperBound="-1" eType="//FaGuBenulaunulaunulAunulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogububiDaBeDadabudaDabucio" eSuperTypes="//EDatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubuguBugusaugubetor" ordered="false" eType="//FaGuBenulaunulaunulAunulaulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albigusbebuDagusIus" ordered="false" upperBound="-1" eType="//BigusboBefrifrilus" eOpposite="//BigusboBefrifrilus/daBudagubuBifrifribuboNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrifribiBonulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabububedaDafribidaguslus" eSuperTypes="//EuGusgusnulAugubuGuEs //DogububiDaBeDadabudaDabucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faGubefrifriGusBudagusdaBitin" ordered="false" upperBound="-1" eType="//EuGusgusnulAugubuGuEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabobobuboguGustus" eType="//EgusauBibunulAuNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuguBobonulaubeBibibifriLius" eSuperTypes="//BrauFriBufriBiDadagusautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudanulaubogusGuBonulaufriGuscio" ordered="false" upperBound="-1" eType="//BiDabifrigubeguTus" eOpposite="//BiDabifrigubeguTus/eBoboBidaDafribobufritor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusbeBidagusnulaugubitor" ordered="false" eType="//BigusboBefrifrilus" eOpposite="//BigusboBefrifrilus/eubobebelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiDabifrigubeguTus" eSuperTypes="//Bigusbubobedagutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abecus" eType="//ABububefriNulauBodatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBoboBidaDafribobufritor" upperBound="-1" eType="//BrAuguBobonulaubeBibibifriLius" eOpposite="//BrAuguBobonulaubeBibibifriLius/dudanulaubogusGuBonulaufriGuscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebuDanulAunulAulus" abstract="true" eSuperTypes="//DogububiDaBeDadabudaDabucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbibunulautin" eType="//BaboNulaubibigusBuDacus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fagufrinulaubibubebibubicio" eSuperTypes="//DogububiDaBeDadabudaDabucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiGugusdaDagusBifribuNulius" instanceTypeName="typeDibonulAugusfribeboBiBuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBubiGusfribeBudafribolus" eSuperTypes="//DuFrifribiBonulAunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuGusbiFribiNulius" ordered="false" eType="//EuGusgusnulAugubuGuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusboBefrifrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBudagubuBifrifribuboNules" upperBound="-1" eType="//DogububiDaBeDadabudaDabucio" eOpposite="//DogububiDaBeDadabudaDabucio/albigusbebuDagusIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubobebelus" ordered="false" upperBound="-1" eType="//BrAuguBobonulaubeBibibifriLius" eOpposite="//BrAuguBobonulaubeBibibifriLius/digusbeBidagusnulaugubitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubedabeNus" eSuperTypes="//BrauFriBufriBiDadagusautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBunulAuboGusBoBubenulaucus" eSuperTypes="//BrauFriBufriBiDadagusautus //BaBubiGusfribeBudafribolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBufriGudagusbubeDagubonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="an" ordered="false" eType="//FaGuBenulaunulaunulAunulaulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euDabeLius" eType="//ABububefriNulauBodatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auBuDabebibiFribebogusBufrilus" eType="//EgusauBibunulAuNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AunulAubugusgugusaudabedabinulIus" instanceTypeName="typeBifrifrigusFribeBugusnules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaGubufrinulauCus">
    <eLiterals name="BibeDadabiTus"/>
    <eLiterals name="EfrigubonulaububeNulaubiTor"/>
    <eLiterals name="DibeBibibunulaufridagusauTor"/>
    <eLiterals name="BadabuGusFribuboNulaubenulaugustin"/>
    <eLiterals name="Bagues"/>
    <eLiterals name="AnbiBubedaBibobiNulaunulauCio"/>
    <eLiterals name="DadaBuGunulauBegusgusBodabetus"/>
    <eLiterals name="AugusfrigusbobedaBenulAuDafrifries"/>
    <eLiterals name="AugusnulAugustus"/>
    <eLiterals name="DuBobeBofribibutor"/>
    <eLiterals name="AlbiGubufribudaGusbedabotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofribiNulauGuBidabegusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befribodabuFriBeBidadaes" ordered="false" eType="//EboNulAubodabedafriboNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFriGusNulauBobeBuboCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babebeGusguguBufritus" ordered="false" eType="//DofribiNulauGuBidabegusTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAuBubebuGusBeguLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusnulIus" eType="//DaGubufrinulauCus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eudafriBibifridabenus" eType="//AunulAubugusgugusaudabedabinulIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Albibefribidanulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeFriNulaugubigusnus" eSuperTypes="//BrauFriBufriBiDadagusautus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBoFribuBudaBeBiBoNus" eType="//BaboNulaubibigusBuDacus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eubifrigusgusgucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGuFriboBuFriboFribeNus" eSuperTypes="//Albibefribidanulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbogubuFrifriBigusbobebobeBoDaBocus" eSuperTypes="//AnulaubuCio //EboNulAubodabedafriboNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugubiBiguFrifridaBobofrilius" eSuperTypes="//DaBufriGudagusbubeDagubonus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babibodabibuFrigustus" eType="//DiGugusdaDagusBifribuNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusFridafriDaBinulAulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusauNulAuNulautus" eSuperTypes="//EboNulAubodabedafriboNules //EuGusgusnulAugubuGuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubibonulaufribebofribiBuNulIus" ordered="false" upperBound="-1" eType="//BrAuguBobonulaubeBibibifriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGudaboGububudaLius" eSuperTypes="//Bigusbubobedagutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBebubofriBobegusfriboNules" eSuperTypes="//DuFrifribiBonulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriGusbeguguBigusbegusNulauGusguDabulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beDabenulAudaDaNulaunulAuTus" eType="//BaboNulaubibigusBuDacus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufriboBunus" ordered="false" upperBound="-1" eType="//FaGuBenulaunulaunulAunulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbugusgusbiBigusbufricio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angubeGusbudatin" eType="//BraubedabeNus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diGugusdadabiNus" eType="//ABububefriNulauBodatus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
