<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eu" nsURI="http://hub.de/rcore/examples/eu" nsPrefix="rFY">
  <eClassifiers xsi:type="ecore:EClass" name="DufridabiBuGusBucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albiboBoguNulautor" ordered="false" eType="//BaNulaufrifriBuEs" eOpposite="//BaNulaufrifriBuEs/fadaBuFribeBubetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulaufrifriBuEs" eSuperTypes="//DufridabiBuGusBucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadaBuFribeBubetus" ordered="false" eType="//DufridabiBuGusBucio" eOpposite="//DufridabiBuGusBucio/albiboBoguNulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulauNulaudadabifribodaFribedaNulauGustus" eSuperTypes="//DufridabiBuGusBucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabubiBefridaNulaugucio" instanceTypeName="typeAguGunulaugugusgusnulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudabeBofriDaBubunus" abstract="true" eSuperTypes="//DufridabiBuGusBucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBeBoes" ordered="false" upperBound="-1" eType="//DunulauNulaudadabifribodaFribedaNulauGustus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfrinulAuFribofribubonus" ordered="false" upperBound="-1" eType="//DufridabiBuGusBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DugunulaunulauDanulius">
    <eLiterals name="Enulaubufribedalus"/>
    <eLiterals name="Anfrifrinulaubobitus"/>
    <eLiterals name="DoBeFriBibiGudabetus"/>
    <eLiterals name="EFriFriFriguBeBobidabeboGustus"/>
    <eLiterals name="Eunulaudagubibibifritus"/>
    <eLiterals name="DuDabibebofribubues"/>
    <eLiterals name="AfriguboGunulaunulauboes"/>
    <eLiterals name="DoGugusaufridaDaFriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulAuNulaubilus" eSuperTypes="//BaNulaufrifriBuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguDabiBeGubegusbunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ABubifrigusbeNulaufritin" instanceTypeName="typeBiBudafriBoGuBinulauNulAuguscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DunulaugusAuNulaudaguBunules" instanceTypeName="typeBefribuBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauDaBuGufrifriGusfrifries"/>
</ecore:EPackage>
