<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bres" nsURI="http://hub.de/rcore/examples/bres" nsPrefix="XQPX">
  <eClassifiers xsi:type="ecore:EEnum" name="DifrigusboNulaufrifriNulius">
    <eLiterals name="Au"/>
    <eLiterals name="DugusbedadabuDaboBebodadaBiNulius"/>
    <eLiterals name="FaDabibugusgulus"/>
    <eLiterals name="DudabiBeGuDaguLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AufriBubuNulAubuNulaudaNulaufriBotus">
    <eLiterals name="BeGubunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabenulAuBiBubunulauFrinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anbebufribibedabitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBeboBinulauGuDadatus" instanceTypeName="typeBeFriBebifrigusnulAubecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngudaBegufrifricio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBeBububoBufriBebibeNulauLius" eSuperTypes="//Anbebufribibedabitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauDanulAuBodabubibubibues" eType="//AnguguBuNulAunulaugunus" eOpposite="//AnguguBuNulAunulaugunus/audabeBoBeBibiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBuguboFrinulauboFrigues" eSuperTypes="//Anbebufribibedabitor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="andaBeFribubiguscio" eType="//AufriBubuNulAubuNulaudaNulaufriBotus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnboBeGudacio" instanceTypeName="typeDogubugubonulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfrinulaubiNulius" eSuperTypes="//AngudaBegufrifricio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufrinulauBuboes" eType="//AuBeboBinulauGuDadatus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Efribudadator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibeboGuFribibocio" eType="//DifrigusboNulaufrifriNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AbibifribubeGusGuNus" instanceTypeName="typeAnfrigufrifriNulauguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnguguBuNulAunulaugunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audabeBoBeBibiNus" ordered="false" eType="//DiBeBububoBufriBebibeNulauLius" eOpposite="//DiBeBububoBufriBebibeNulauLius/brauDanulAuBodabubibubibues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babebubiNulauFriDaLius" ordered="false" upperBound="-1" eType="//AngudaBegufrifricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFrinulauBoFridabutus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Albogusbocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusAubigubebeboNus" eSuperTypes="//AnguguBuNulAunulaugunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alBobitor" upperBound="-1" eType="//AbibifribubeGusGuNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulaubefrinus" upperBound="-1" eType="//BaBuguboFrinulauboFrigues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulAuDanus" eSuperTypes="//DabenulAuBiBubunulauFrinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobubufriGusgusbubebucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BenulaubeGugusbogusgudabinulauFrinus" instanceTypeName="typeAuGusdabogusGusbelius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BagusNulAubegubinulAudacio">
    <eLiterals name="DigubegusbubebibeCus"/>
    <eLiterals name="DibeguNulaubibibunulAububoDaLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabuNulauNulauguGuBiNulAuGusbefrinulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubuGudaboGusguGusgusdaGusnulius" instanceTypeName="typeFadaBogunulaudanulAunulauCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agusdabogustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBibibubeFrifridaGuGubiTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baguBiGusgusgusNus" upperBound="-1" eType="//DifrigusboNulaufrifriNulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugugubufrigusbugusGusbeBucio" ordered="false" eType="//Efribudadator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusbubogusAubeLius" eSuperTypes="//FabuNulauNulauguGuBiNulAuGusbefrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuguFriBitin" eSuperTypes="//DagusbubogusAubeLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubuFribefribigusbiBecus" eType="//BagusNulAubegubinulAudacio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulaubefriguLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudadanulAugusDabuBibiBicio" ordered="false" upperBound="-1" eType="//DibuguFriBitin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBuLus" ordered="false" eType="//Anbebufribibedabitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BigusBuLus" instanceTypeName="typeBeBuNulaubufribibudacio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DibuBibiBoguNulaufridadaNulAubulus" instanceTypeName="typeBraufriboDafrinulaubuBegusaulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Babibefribibibotin">
    <eLiterals name="AnDaBobuBubibenulaufrinulAubetus"/>
    <eLiterals name="Eubibibegunulaubees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebibudabobogusbugugugucus" eSuperTypes="//BaBuguboFrinulauboFrigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbibubibubinulauBeBitus" eSuperTypes="//BinulAuDanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauboBeguguBeDabeboBonulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudadaFridanulAuNulaufriBuTin" eSuperTypes="//BiFrinulauBoFridabutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiGusnulAunulaucus" ordered="false" upperBound="-1" eType="//Anbebufribibedabitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaDagusBiBeboGusFriBefriboTor"/>
</ecore:EPackage>
