<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eubeguscus" nsURI="http://hub.de/rcore/examples/eubeguscus" nsPrefix="n">
  <eClassifiers xsi:type="ecore:EClass" name="DibeGusBubibefrilius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadabubiBoBoLus" ordered="false" eType="//BegusAunulAuBeFrifrinulauguEs" eOpposite="//BegusAunulAuBeFrifrinulauguEs/brauDabenulaufriDadabinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlboDaGusBobiGusbubefriTin" instanceTypeName="typeEDaNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBogusBufrifritin" eSuperTypes="//DibeGusBubibefrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBidabofriDabuboboboBobecus" ordered="false" eType="//DibeGusBubibefrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlaunulauBigusaunulauBudanus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaguGusaunulaudanus" instanceTypeName="typeBifrigusbifriGusAubiDator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBedabeFriDagucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulauguDabeBofrigusius" eType="//DibeGusBubibefrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodagusGuBunus" eSuperTypes="//DoBogusBufrifritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebibucio" eType="//BaguGusaunulaudanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidaGusgubububuFrifriNulIus" eSuperTypes="//DoBogusBufrifritin //DodagusGuBunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibiNulaudagusNus" ordered="false" eType="//AlaunulauBigusaunulauBudanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdanulauNulaubeEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiBelius" ordered="false" upperBound="-1" eType="//DoBogusBufrifritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabuBobobefriTin" eSuperTypes="//AdanulauNulaubeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbogusDaFriGusbuEs" eSuperTypes="//DodagusGuBunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfrigusgubegugusbenulaugusguCio" eSuperTypes="//DodagusGuBunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagubobedabufrigusBobilius" eType="//AlboDaGusBobiGusbubefriTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuguboFrigusAufribunulAuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusGusFribuGuslius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusBifriBegutor" eType="//AlboDaGusBobiGusbubefriTin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baBogusdadafribifribobitin" eType="//BaguGusaunulaudanus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGubecio" ordered="false" upperBound="-1" eType="//DidaGusgubububuFrifriNulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BidaNulaugutin">
    <eLiterals name="BigububiBotus"/>
    <eLiterals name="DuBigusnulAunulAufrinulauGubeGutin"/>
    <eLiterals name="AlgusboboFriBeboGusaubeDacus"/>
    <eLiterals name="AgusFrinulauBiboFriBecus"/>
    <eLiterals name="BadaboBefriGutor"/>
    <eLiterals name="DuBebibubebenulauTor"/>
    <eLiterals name="AGusbofriBebogusBuDalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBeFridagusnulAudabubobegustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBogusBitus" eType="//AlboDaGusBobiGusbubefriTin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebobibobeBubeBobuDabiNus" ordered="false" eType="//DodagusGuBunus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alDaGusboGuguBogustus" eType="//AlboDaGusBobiGusbubefriTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EfrifriBobibudaes">
    <eLiterals name="Didafribobubebotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBefriFriBoNulaudaDabeGusNus" eSuperTypes="//DaBeFridagusnulAudabubobegustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babebigunulaubulius" upperBound="-1" eType="//AlfrigusgubegugusbenulaugusguCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBubuBedaFribetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGubobebunulAuGusFriBifrifribeNus" ordered="false" eType="//AdanulauNulaubeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbefribibubofribubufribeBugubebogulus" eSuperTypes="//FabuBobobefriTin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DogudaBoGububoBetin">
    <eLiterals name="BibubedafrinulAugusBeGutus"/>
    <eLiterals name="Dibelius"/>
    <eLiterals name="BiGusauboDaBibinus"/>
    <eLiterals name="FaBebidaBoDagugusbegusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AngudaBubuguBiFriBiGuses">
    <eLiterals name="BagububodagusgusaugusTin"/>
    <eLiterals name="AgudaBefribobunulIus"/>
    <eLiterals name="EuFridabebegusgubunus"/>
    <eLiterals name="DaNulaubedaguBiTin"/>
    <eLiterals name="BeGusauGusbubuBeguLius"/>
    <eLiterals name="EubiDabubugusauNulauGusTin"/>
    <eLiterals name="DidabibofribeGunulautin"/>
    <eLiterals name="EbogudabiBiGugudanulaubibogudaCus"/>
    <eLiterals name="BadagubobeBoBobubegusbeBodacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiFriguNulaulius" eSuperTypes="//DaBeFridagusnulAudabubobegustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aubudabogudanulautor" abstract="true" eSuperTypes="//DoBogusBufrifritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBebuguNulaugugutus" eType="//BidaNulaugutin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beDabedagusnulAuFriBufritin" ordered="false" upperBound="-1" eType="//FafrinulaubibeTus" eOpposite="//FafrinulaubibeTus/edabeGugusboBiNulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebefrinulAububofriBucus" instanceTypeName="typeDofribigusfribiDabunulAuGustin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BabubudaDagudagustor">
    <eLiterals name="DabobibonulaugusAubobuguLus"/>
    <eLiterals name="BeguBibiNulaugusAuBoEs"/>
    <eLiterals name="DiGusBicus"/>
    <eLiterals name="BrauDaNulAubulius"/>
    <eLiterals name="DiGusGusbedaDaboFrilius"/>
    <eLiterals name="AudafriBoguFribenulaubocio"/>
    <eLiterals name="AnnulAuGusbidator"/>
    <eLiterals name="EugubebuguBonulAugusfribobonulAububiTus"/>
    <eLiterals name="BebedagugusbuDator"/>
    <eLiterals name="BeBebebigusbobobocus"/>
    <eLiterals name="DidafribuboguBoDafrigusbuNus"/>
    <eLiterals name="BrAubeFrigusbuFribibiEs"/>
    <eLiterals name="EnulaubobegusdanulAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnNulauBibifribogubucio" instanceTypeName="typeBigusFribogusnulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBogubuFribitor" eSuperTypes="//DibeGusBubibefrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibiBefridaFridator" eSuperTypes="//DaBeFridagusnulAudabubobegustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabebodaBinulauDagucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abodaGudabeLus" ordered="false" eType="//AlaunulauBigusaunulauBudanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnFrifridagufrigusgustor" instanceTypeName="typeDaBibuBobebodaBiGusBeDadaTor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiBiboBobubenulAunulAuBicus">
    <eLiterals name="BraubeNulAubugusauguslus"/>
    <eLiterals name="AlfriGusbefriBubobeGusBetin"/>
    <eLiterals name="DufriBibuBoGusbiGusguDaDafritin"/>
    <eLiterals name="EboGuBiBugusbobeBudaboNulaucus"/>
    <eLiterals name="BiboGusBegusgusdaBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgudanulAuBefridanulauBecus" eSuperTypes="//AdanulauNulaubeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBuGusdagusFrigusdaboNulAuFriGusgusboTus" eSuperTypes="//AdanulauNulaubeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufribeNulauFriBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufribunulAudaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGububogugubuGusDacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbugusdaBibenulAubebucus" eSuperTypes="//DaBeFridagusnulAudabubobegustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AFriDaGusGudabidaguGucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbebinulauboBobidaDafrinulaubilius">
    <eLiterals name="DaBoBibibugubobebibenus"/>
    <eLiterals name="AububugusgusAuboGubibiBelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DabubofrigufriboGusaubutus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaDagusBuBuBees"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafrinulaubibeTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedagufribiBeNulauBotor" upperBound="-1" eType="//AlgudanulAuBefridanulauBecus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edabeGugusboBiNulaucus" ordered="false" upperBound="-1" eType="//Aubudabogudanulautor" eOpposite="//Aubudabogudanulautor/beDabedagusnulAuFriBufritin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulaufridabobuGusTin" ordered="false" eType="//DobiBudaBonulaubinulauGustus" eOpposite="//DobiBudaBonulaubinulauGustus/beBobonulAunulauBonulaudaFribuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubibufrinulaunulautus" eSuperTypes="//AlaunulauBigusaunulauBudanus //BrAuguboFrigusAufribunulAuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaububiBuDabiFridagusNus" eSuperTypes="//BibiBefridaFridator //DodagusGuBunus //EbogusDaFriGusbuEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagusBefrinulaufriGugubiBoes" eType="//DogudaBoGububoBetin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusBiNulAuguBegusbefriEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBiBeNulauGuGusbibiGuscus" eType="//DabubofrigufriboGusaubutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifriBigusGusBubinus" eSuperTypes="//AlfrigusgubegugusbenulaugusguCio //AlbefribibubofribubufribeBugubebogulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafriBobobunulauGusbodafriGuBiDafrinules" ordered="false" upperBound="-1" eType="//BenulaububiBuDabiFridagusNus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afriFribegusgusDacio" upperBound="-1" eType="//DogudaBoGububoBetin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBuGusDaBulius" eSuperTypes="//EuBefriFriBoNulaudaDabeGusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edaFriNulauGubues" ordered="false" upperBound="-1" eType="//AGusbebuboNulaubigudaDaTor" eOpposite="//AGusbebuboNulaubigudaDaTor/auGusBigusbiBobodabebonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubobobobobugusFribuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubobuFrifriDagusguBebotus" abstract="true" eSuperTypes="//EuBuGusDaBulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnaubibiFribogusius" instanceTypeName="typeFagugusnulauGuguBuGubobegugusBodaBicio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BifriBibebuBubogusbetin">
    <eLiterals name="BebibinulaubugusbifrinulAudaBeNulAuFribinus"/>
    <eLiterals name="DoFriNulAuBufriBuBiDanulaunulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobiBudaBonulaubinulauGustus" eSuperTypes="//EuBefriFriBoNulaudaDabeGusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBobonulAunulauBonulaudaFribuLius" ordered="false" upperBound="-1" eType="//FafrinulaubibeTus" eOpposite="//FafrinulaubibeTus/benulaufridabobuGusTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusAunulAuBeFrifrinulauguEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauDabenulaufriDadabinus" ordered="false" eType="//DibeGusBubibefrilius" eOpposite="//DibeGusBubibefrilius/dadabubiBoBoLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegugusbigugusBuboguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusGugufritin" eSuperTypes="//DiFriguNulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDabinulaubidaFridabetor" ordered="false" eType="//DaBeFridagusnulAudabubobegustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebibuguboBinulaugucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugudaNulaubuFridadaboBiboTor" instanceTypeName="typeBaBeBunulaugudaCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBidaDabidadaCus" eSuperTypes="//AugusGusFribuGuslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusbebuboNulaubigudaDaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusBigusbiBobodabebonus" ordered="false" upperBound="-1" eType="//EuBuGusDaBulius" eOpposite="//EuBuGusDaBulius/edaFriNulauGubues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubefrigudaGulus" eType="//BabubudaDagudagustor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabogusBobobogufribeBoBefrigugusaubicus" instanceTypeName="typeAnbobiBubenulaubugunulauguTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubudaBeGuTor" instanceTypeName="typeAdanulaudaBubidaNulAutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBiBugusFrifriFriBuBetus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBegusbobeBelus" instanceTypeName="typeAuboBegusBubebiboGunus"/>
</ecore:EPackage>
