<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ebees" nsURI="http://hub.de/rcore/examples/ebees" nsPrefix="RY">
  <eClassifiers xsi:type="ecore:EEnum" name="DaGusaububuBulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Albibenulaugusfribidacio" instanceTypeName="typeAnulaudadadabuDaBogusbobefrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoFriBibugusdaBegubocio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnFribofriTor" instanceTypeName="typeDibubeBobugusgutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbebebobubedaNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eDaguNulaufriGuBifrifritor" eType="//DaGusaububuBulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagubibefriboguLus" eType="//DafriguGugusGudaGunulaubitus" eOpposite="//DafriguGugusGudaGunulaubitus/ebobidafribuBebiDabigugusdaGusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bebinulaudacio" eSuperTypes="//DoFriBibugusdaBegubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBeDaGuguDabunulAuGusBobitus" eSuperTypes="//DoFriBibugusdaBegubocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="afrigusbibogusdaguButus" ordered="false" upperBound="-1" eType="//DoFriBibugusdaBegubocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulAuNulAubeBobuBibedaBonus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFrigusboFridabinulaunus" ordered="false" eType="//DoFriBibugusdaBegubocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBubegusAuBebonulAubofricus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugusgusBuboBudaGuguBigubeTin" instanceTypeName="typeBiDagubububufriBebebunulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braugusnulaubunulaubebolius" abstract="true" eSuperTypes="//DoFriBibugusdaBegubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dibogusfribofribotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogubibofrinulaubogudanulAutin" ordered="false" eType="//DoFriBibugusdaBegubocio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braugusBinulEs" eType="//DaGusaububuBulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebiGuDabogusgusdaBudaCus" instanceTypeName="typeBraufribiboBugusbunulauboLius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Befribogusfrigufribibebilus">
    <eLiterals name="BeBigusfrigubelius"/>
    <eLiterals name="BraudaDaBoFrinulAugusnulius"/>
    <eLiterals name="BibeFriBunulaubinulAubinulaunulEs"/>
    <eLiterals name="AuNulaubicio"/>
    <eLiterals name="BrAuGusfriBegugusboBiGufribifrinus"/>
    <eLiterals name="AuNulauBibobebuBodadafriNulauLius"/>
    <eLiterals name="BraubinulauboBedagugunulius"/>
    <eLiterals name="AnulauBugubibubiDaNulaulius"/>
    <eLiterals name="BrauGuBofriBofribibuBuBiboNulAutus"/>
    <eLiterals name="DibeNulAufriFriNulauBonulAunus"/>
    <eLiterals name="BanulauguGusBinus"/>
    <eLiterals name="AuNulauBogusbudadanulAufribibiLius"/>
    <eLiterals name="DubiBeGusnulaudabibubidabobees"/>
    <eLiterals name="FaBobuguBeFriBubebedabidabiBeGusCio"/>
    <eLiterals name="BaBibibotor"/>
    <eLiterals name="AlBiFrifribegubebubeBeNus"/>
    <eLiterals name="BabebebibunulaudaGusbobuCus"/>
    <eLiterals name="AugusBodaFriBonulaudagusBecio"/>
    <eLiterals name="DiNulAudagusAunulAuFriguGuBodaFriGugutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubeboGunulaubitor" instanceTypeName="typeDaBebuBubobobibeEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BenulauBifribicio" instanceTypeName="typeDafrinulauNulaugusDagues"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobigubigusfribogufritor" eSuperTypes="//DaBubegusAuBebonulAubofricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubonulAubebegugusbobulius" eType="//Albibenulaugusfribidacio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbidabudafribebobubiGuGunulaubebetus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babubofridanulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnAugusbogusaunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBedaFriboguBububoButin" ordered="false" eType="//AlbebebobubedaNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfriGusBubinulauBetor" eSuperTypes="//EBeDaGuguDabunulAuGusBobitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusGusguguBegusGuBiLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGuBifriBeBebobuFritin" eSuperTypes="//EBeDaGuguDabunulAuGusBobitus //AlbebebobubedaNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAubigusbubiBiBecus" eType="//Albibenulaugusfribidacio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeBefriguguBidaGustor" eSuperTypes="//DugusGusguguBegusGuBiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulaugudagugubetin" ordered="false" upperBound="-1" eType="//DoFriBibugusdaBegubocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Danulaunus" instanceTypeName="typeAbibebibiFribofrigusbedadafrinulAufritin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DinulAufrifriGuFriGutus">
    <eLiterals name="AnbiFriBububoNulAunulAuCio"/>
    <eLiterals name="DiBegunulaubedaBiguBiLius"/>
    <eLiterals name="DafrigusboboFrigusboLius"/>
    <eLiterals name="BiboguBobibebobidabecus"/>
    <eLiterals name="Bafridabubugusfrigusbinus"/>
    <eLiterals name="FaNulauGubinulaufritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbinulauDabetor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafriguGugusGudaGunulaubitus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAunulAuFrigusnulaucio" eType="//Danulaunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebobidafribuBebiDabigugusdaGusNus" upperBound="-1" eType="//AlbebebobubedaNus" eOpposite="//AlbebebobubedaNus/fagubibefriboguLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAugusbobicus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duGusauBuGusnules" upperBound="-1" eType="//Befribogusfrigufribibebilus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duboGudagunulAuGuBitus" ordered="false" upperBound="-1" eType="//EGuBifriBeBebobuFritin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGuGusbuNulauBoguNulaugubuBeboes" ordered="false" upperBound="-1" eType="//Babubofridanulaulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBebubofrigusaugusgusgusBilius" ordered="false" eType="//DaBubegusAuBebonulAubofricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnauFribigusauButus" eSuperTypes="//EbidabudafribebobubiGuGunulaubebetus //FanulAugusbobicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAuDabeNulAudagusbudagusBiDaGusBilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubunulaubonulauLius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugusbuGuNulaubebubees" eType="//BenulauBifribicio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="efribiboBobubebibebubies" ordered="false" eType="//AnauFribigusauButus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBenulauFribeEs" eSuperTypes="//AnAugusbogusaunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGusbebobofrifrinulAulus" ordered="false" eType="//BedaDagubuGusCio" eOpposite="//BedaDagubuGusCio/eudafriDabunulaudaNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulautin" ordered="false" eType="//Binulaubobibibigubulus" eOpposite="//Binulaubobibibigubulus/baBoDanulAubodadaNulaubobuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudaguNulAunulauNulaubebeBebebibulus" abstract="true" eSuperTypes="//Babubofridanulaulus //Dobigubigusfribogufritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafriDadaBonulAubobunulauNulaubeguDaes" eSuperTypes="//BeNulAuNulAubeBobuBibedaBonus //Bebinulaudacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubeBugunulaugusBenus" eSuperTypes="//BraubeBefriguguBidaGustor //FafriDadaBonulAubobunulauNulaubeguDaes //EbidabudafribebobubiGuGunulaubebetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beguBeFrigusBugubinulius" ordered="false" upperBound="-1" eType="//EBeDaGuguDabunulAuGusBobitus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauguboBuBebefribubues" ordered="false" eType="//AlbinulauDabetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BebebibiLus">
    <eLiterals name="BebebidabodagugudabuboNus"/>
    <eLiterals name="DiGusbeboBugusnulEs"/>
    <eLiterals name="BeguDadaCio"/>
    <eLiterals name="DabebeNulAubudaBifrigubodadatus"/>
    <eLiterals name="EubenulAuDadanulauDabubiNules"/>
    <eLiterals name="DiFribubebigusDaFrinulautin"/>
    <eLiterals name="AuBofriBibegubinulAuGubiTor"/>
    <eLiterals name="EnulaunulAuDabidanulauBulus"/>
    <eLiterals name="BedabiGusfritor"/>
    <eLiterals name="AlbeBuBegubebifrigusNulaulus"/>
    <eLiterals name="AlbuboBenulaugubodabenulius"/>
    <eLiterals name="BraubuFribenulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuFriBoBibofribinulAuTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbigubonulAugusdanus" ordered="false" upperBound="-1" eType="//Dobigubigusfribogufritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusfrigunulauLius" instanceTypeName="typeDobeBuBiFrigubobutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBinulauGusbebeDanulaubuEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuBigusgusgusbibetus" eType="//AnFribofriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBegugusGubonulius" instanceTypeName="typeAngusFriDaBugunulauBebecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubeDagusbinulAuBudagubigusbetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulAububiBeBeEs" abstract="true" eSuperTypes="//EbidabudafribebobubiGuGunulaubebetus //AnAugusbogusaunules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabufrigubebubetor" eType="//Albibenulaugusfribidacio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibuNulAubeguBeTin" upperBound="-1" eType="//DinulAufrifriGuFriGutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBiBeDafribobeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriGusbeNulaubonulAugusbuEs" eSuperTypes="//DafriguGugusGudaGunulaubitus //BraubeBefriguguBidaGustor //EbidabudafribebobubiGuGunulaubebetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBiguBibiGubudanus" ordered="false" upperBound="-1" eType="//EuBiBeDafribobeNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Babegusbofrigubobodagugunus">
    <eLiterals name="AlnulauBifrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbedaGunulAutin" eSuperTypes="//EudaguNulAunulauNulaubebeBebebibulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubugudabues" eType="//Babubofridanulaulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulAuNulAububenulAufriBeDatin" ordered="false" eType="//Dobigubigusfribogufritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBugusGusBiBiboBoBuNulaubiGuscio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anAubebonulaudabolus" eType="//BebebibiLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusbebeTor" eType="//DunulAuDabeNulAudagusbudagusBiDaGusBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBubifriguBiBebonulAuGusgusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldaFrigusauguGuFrigusBelius" ordered="false" eType="//FanulAugusbobicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusBubiFriBebebelius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BifriGugusGububoButus" instanceTypeName="typeEuBubuDanulAuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabibebiGuguslius" eSuperTypes="//AnAugusbogusaunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibeFriguBeBeBedabees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBonulAuFriguLus" ordered="false" eType="//EGuBifriBeBebobuFritin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBubogububoGusboBudaLius" ordered="false" upperBound="-1" eType="//EuBiBeDafribobeNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulAutor" ordered="false" upperBound="-1" eType="//EBeDaGuguDabunulAuGusBobitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADaBidabibugucus" abstract="true" eSuperTypes="//BraubeBefriguguBidaGustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebugusFriGusboBiDaBefriTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusgugusbebegusNulauGuNulAunulaulus" ordered="false" eType="//Dibogusfribofribotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Dolus" instanceTypeName="typeDobobodaguFrinulAugusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedaDagubuGusCio" eSuperTypes="//DoFriBibugusdaBegubocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudafriDabunulaudaNus" ordered="false" upperBound="-1" eType="//EBenulauFribeEs" eOpposite="//EBenulauFribeEs/alGusbebobofrifrinulAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeGusGuBubetus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AdaBoBubobudafrifriBuNus" instanceTypeName="typeAbobibubebudaBiboguGubuGusGuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubibeDaNulAufriGubuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiNulaububiguBoDaBunules" eSuperTypes="//AlbinulauDabetor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlGusbifrinulauTin">
    <eLiterals name="DubufribigusfrigusboDagunulauGusBiTus"/>
    <eLiterals name="DugusbeGubogubuTin"/>
    <eLiterals name="BrauguboBubiBofridaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaubifriGusGuboGusguBucio" eSuperTypes="//EGuBifriBeBebobuFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBiDafrinulAuNulauCus" abstract="true" eSuperTypes="//BrauNulAububiBeBeEs //Braugusnulaubunulaubebolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBogugusdagusauBinus" ordered="false" eType="//Braugusnulaubunulaubebolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbibigudabeBuBobilius" eSuperTypes="//EfriGusBubinulauBetor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egubugusgulius" upperBound="-1" eType="//Albibenulaugusfribidacio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBebeDabeDabidaCio" eType="//DaGusaububuBulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiboDacio" instanceTypeName="typeDobobiFrigugusNulaububetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaububufribonulAugusbiguscus" abstract="true" eSuperTypes="//BeNulAuNulAubeBobuBibedaBonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbofriBeDaFrifribeGusguFrifribufribenulAubolius" eSuperTypes="//AnAugusbogusaunules //EbedaGunulAutin //BebugusFriGusboBiDaBefriTus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DadagubibubiFridabiLus">
    <eLiterals name="AudanulAuBubuFritor"/>
    <eLiterals name="BraunulAunulaubitus"/>
    <eLiterals name="Badanulaubufribububebelus"/>
    <eLiterals name="BebeBebetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibiBoBuGuGugusBogusTor" eSuperTypes="//EGuBifriBeBebobuFritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubenulaudaBeBetus" ordered="false" upperBound="-1" eType="//BaBugusGusBiBiboBoBuNulaubiGuscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeFrifribiBitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfribiboNulAubuGusNulauBedaes" eSuperTypes="//AnauFribigusauButus //BraubunulaubonulauLius //EBenulauFribeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafrifriCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auFriBibubibocus" ordered="false" upperBound="-1" eType="//DugusGusguguBegusGuBiLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBibofriBegusBobufrifribuNulaucus" abstract="true" eSuperTypes="//EubibeDaNulAufriGubuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbigubuBibebidabobeBonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaguFriDafribogusguFribonulaufrigutor" abstract="true" eSuperTypes="//DiBubifriguBiBebonulAuGusgusTin //EBeDaGuguDabunulAuGusBobitus //EfribiboNulAubuGusNulauBedaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebiDanulaububiBilius" upperBound="-1" eType="//AnAugusbogusaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BebebudabiFrigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufribigusGusNulAuboguTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubunulauDadaDaDaCio" ordered="false" upperBound="-1" eType="//FafriDadaBonulAubobunulauNulaubeguDaes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eDabeBeBigugubebicio" eType="//BebebudabiFrigulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibonulauCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaunulAuDabobufrigubigugucio" eType="//EGuBifriBeBebobuFritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaudabefrifribinulAunus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGusdanulaufriBubuguscio" ordered="false" eType="//BenulaubifriGusGuboGusguBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubigubebobogububoNulauFriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauLus" ordered="false" eType="//Dobigubigusfribogufritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dabubobegubufritin" eSuperTypes="//EubibeDaNulAufriGubuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiguBedatin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaBibobodagugusBunus">
    <eLiterals name="DafriBodaboBuGulus"/>
    <eLiterals name="DuguGuGufribifrilus"/>
    <eLiterals name="DidaNulIus"/>
    <eLiterals name="DaguguFrigusboNulAugutor"/>
    <eLiterals name="EuFriGubogustus"/>
    <eLiterals name="BinulauBiBebeNulautor"/>
    <eLiterals name="BrAubeBeGusGusbobuGugusauTus"/>
    <eLiterals name="BibinulaugusguguDaboGusCio"/>
    <eLiterals name="DibeBugusdaBinulEs"/>
    <eLiterals name="EfriboBeGububenulauNulAuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusNulAuDabibofribilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiguBenulauFriFrifribuGusBucio" eSuperTypes="//EbofriBeDaFrifribeGusguFrifribufribenulAubolius //FanulAugusbobicus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begusboboBoboguscus" eType="//DaGusaububuBulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigubodaGugusbinulaufributor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dabegubigugubobodacio" instanceTypeName="typeAugubidanulauGusdanulAuDabeCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBebedabedabegugusfribulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daboBubuTin" eType="//DinulAufrifriGuFriGutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusDaBibugusDabinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AububogububuGusBibunulaulius" abstract="true" eSuperTypes="//EfriGusBubinulauBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabenulauBibifrifriTor" eSuperTypes="//AnauFribigusauButus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DububoGuBiguFribetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babues" eType="//BaBibobodagugusBunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusnulauBenulaubibubugubenus" abstract="true" eSuperTypes="//BraubunulaubonulauLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuGusfriFrinulaufriGuFrinus" eSuperTypes="//DibeFriguBeBeBedabees"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DagusnulAuboBonulaugububunulius" instanceTypeName="typeAnbegusCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusnulAudaGuGusdaBotus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndaGusautus" eSuperTypes="//AubeBugunulaugusBenus //AlbigubuBibebidabobeBonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudadabudaGusbecus" abstract="true" eSuperTypes="//AlgusBubiFriBebebelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusDagusnulauBoBodaLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abeBegugusbebebiBoes" eType="//DagusnulAuboBonulaugububunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BiboFrifribiNulaucus">
    <eLiterals name="BeGusbeboGusnulaubebunulAuBeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubedabubinulAuNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuGusAuguGubuGububeBonulAunules">
    <eLiterals name="AlaufriGusfrigusnulauboGuBibibudator"/>
    <eLiterals name="AlgunulauBolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binulaubobibibigubulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBoDanulAubodadaNulaubobuTus" ordered="false" upperBound="-1" eType="//EBenulauFribeEs" eOpposite="//EBenulauFribeEs/enulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusfridaBeguDaFriGusnus" eSuperTypes="//DiBibofriBegusBobufrifribuNulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugubitin" ordered="false" upperBound="-1" eType="//AufribigusGusNulAuboguTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGububugusdagusgusGuses" ordered="false" upperBound="-1" eType="//BagusnulauBenulaubibubugubenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudabobegubefribebebeTin" eSuperTypes="//AndaGusautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulauBiGusgusdagunulaububiNus" eSuperTypes="//EfribiboNulAubuGusNulauBedaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibobuDadagusaudatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doguBobidagusauFriGuboCus" ordered="false" eType="//BeNulAuNulAubeBobuBibedaBonus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubiBeBiGusauBuFridafriTin" eType="//DadagubibubiFridabiLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebufrinulAugubecus" ordered="false" eType="//AubeBugunulaugusBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaunulauGusAuNulAufriBicus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaboNulauBigusfriTin" eSuperTypes="//AlbebebobubedaNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiBiGubidadaGusbuDabibugubebutin">
    <eLiterals name="EunulaubebebufrigubofriDalius"/>
    <eLiterals name="DaBonulaudabeNus"/>
    <eLiterals name="AngusdaBibiBunus"/>
    <eLiterals name="DuguNulAuGusboboBobinules"/>
    <eLiterals name="AnauboguBuguslus"/>
    <eLiterals name="DaDafriGusDanulAuNulAuBufrigusbiGusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGugusdabebubogubulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndaBogusBofribiBofribiButin" eSuperTypes="//DibobuDadagusaudatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFriDaboBobiBiGububefrilus" eSuperTypes="//EudadabudaGusbecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADadanulaugubigusFribonulIus" abstract="true"/>
</ecore:EPackage>
