<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aubofribubebocus" nsURI="http://hub.de/rcore/examples/aubofribubebocus" nsPrefix="TiY">
  <eClassifiers xsi:type="ecore:EClass" name="BidabigusbuLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaudanules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBububoGubodaFriBugusGubegusfrilus" ordered="false" upperBound="-1" eType="//DofribedadaBeguDaDaGutus" eOpposite="//DofribedadaBeguDaDaGutus/anGunulaugusdaguGusAubofriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulAuFribegunulauBebiBenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoguGufrifriGusGubibefribelus" eSuperTypes="//ENulAuFribegunulauBebiBenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebegusGuGubedaCus" upperBound="-1" eType="//DaBuFrigubifrifriBeGubodaBoBuTus" eOpposite="//DaBuFrigubifrifriBeGubodaBoBuTus/beNulaugusbuBenus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubobibogusgusbuBebeEs" upperBound="-1" eType="//AlgugusNulAubeFrinulaugubiBeTus" eOpposite="//AlgugusNulAubeFrinulaugubiBeTus/bigusbunulaugusdadaNulaugusboCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobigunulAudadaguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulauBugugusgutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabefribegunus" ordered="false" upperBound="-1" eType="//DoguGufrifriGusGubibefribelus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugubibegusnulAuGuslius" ordered="false" upperBound="-1" eType="//AlNulaudanules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnaunulaunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBugusnulAunulauFriboEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abetus" ordered="false" eType="//DobigunulAudadaguTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBubidaBebeNulauBobees" ordered="false" eType="//BibufriBobobubunulautor" eOpposite="//BibufriBobobubunulautor/biBeBoTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriBuDagubitus" abstract="true" eSuperTypes="//DonulauBugugusgutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBibebifriBobiBegubigusbilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABeBegugubugusDanus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulAuFriboFriNulaugusbodaguLus" ordered="false" upperBound="-1" eType="//DoGusGuFriGubiBufritus" eOpposite="//DoGusGuFriGubiBufritus/fabuFribigubobuDabububugusEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBubeNulAugustin" eType="//DaDagustor" eOpposite="//DaDagustor/auNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebibuDaguGudabunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubebiNulauBiDafribibonus" instanceTypeName="typeBrauNulaubebugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusbonulauBuBobebiEs" abstract="true" eSuperTypes="//ABeBegugubugusDanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBebocus" ordered="false" eType="//BiBibebifriBobiBegubigusbilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBuFrigubifrifriBeGubodaBoBuTus" abstract="true" eSuperTypes="//ENulAuFribegunulauBebiBenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAugusBiGusbuguBigusbofribibubuDatin" ordered="false" upperBound="-1" eType="//DobigunulAudadaguTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulaugusbuBenus" ordered="false" eType="//DoguGufrifriGusGubibefribelus" eOpposite="//DoguGufrifriGusGubibefribelus/ebegusGuGubedaCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBunulauguBiGuGusbecio" ordered="false" upperBound="-1" eType="//ENulAuFribegunulauBebiBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Fanulaudafribigusaucus">
    <eLiterals name="DadabubebobebunulAufrigusGues"/>
    <eLiterals name="DubeDaBobogunulAuGuBebocio"/>
    <eLiterals name="AlbiboboBogusfrigusbocio"/>
    <eLiterals name="AlfriFribeBinulaugusdagusfricio"/>
    <eLiterals name="Dibidabodadagusnulaufrilius"/>
    <eLiterals name="DaguBiboDagusGusgufribiBecus"/>
    <eLiterals name="DudafrifrigusbiBugusBiBulus"/>
    <eLiterals name="AnGusGugufriGusgusGustus"/>
    <eLiterals name="FaDaGusBocus"/>
    <eLiterals name="AubidanulauBofridabebedaes"/>
    <eLiterals name="FabubibonulaunulauguNulauGubulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuGubobodaBibobebenulius" instanceTypeName="typeBagusbebogusBubobitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboDaGusnulaugusbolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofribedadaBeguDaDaGutus" eSuperTypes="//DuFriBuDagubitus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubufrinulaucus" eType="//AuGubobodaBibobebenulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGunulaugusdaguGusAubofriLius" ordered="false" eType="//AlNulaudanules" eOpposite="//AlNulaudanules/beBububoGubodaFriBugusGubegusfrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgubigusdaboBoFricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusGusnulaubocio" eType="//AuGubobodaBibobebenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBufriNulaubuguBubuguDadabuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebifribibiBobiBeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadanulauFrinulaubiBinulauBicus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubifrinulaugusguBiBoTus" eType="//AuGubobodaBibobebenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusdabegusnulAuFriGufrigububetin" eSuperTypes="//AlBugusnulAunulauFriboEs //DuFriBuDagubitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubigusButor" ordered="false" upperBound="-1" eType="//AlnulauFriboNulauFrinulAubobutin" eOpposite="//AlnulauFriboNulauFrinulAubobutin/anAuboGusdabufrigusfridacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Bagusius" instanceTypeName="typeDaFriBeDaNulAugufriBubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulauFriboNulauFrinulAubobutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anAuboGusdabufrigusfridacus" ordered="false" upperBound="-1" eType="//AgusdabegusnulAuFriGufrigububetin" eOpposite="//AgusdabegusnulAuFriGufrigububetin/dubigusButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubodaGuboGucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuBubiBeBidanulIus" eSuperTypes="//BebibuDaguGudabunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubuBefribofriboGugusAulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulAuFriBobiGuGusBoBebecus" eSuperTypes="//ABeBegugubugusDanus //AubodaGuboGucio //DofribedadaBeguDaDaGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusGuFriGubiBufritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibeBibugugusBecio" eType="//BidabigusbuLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafrinulautin" eType="//AgusdabegusnulAuFriGufrigububetin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabuFribigubobuDabububugusEs" ordered="false" upperBound="-1" eType="//ABeBegugubugusDanus" eOpposite="//ABeBegugubugusDanus/dunulAuFriboFriNulaugusbodaguLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnFribonulAubeBobetus" eSuperTypes="//DobigunulAudadaguTin //DoGusGuFriGubiBufritus //DoguGufrifriGusGubibefribelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulaugusauBoBeBeFries" ordered="false" upperBound="-1" eType="//AdadanulAufriboTin" eOpposite="//AdadanulAufriboTin/eubebeguFriguGusgusDanulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabuBonulAunulaugubuNulaubiNulauBenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgugusNulAubeFrinulaugubiBeTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusbunulaugusdadaNulaugusboCus" ordered="false" eType="//DoguGufrifriGusGubibefribelus" eOpposite="//DoguGufrifriGusGubibefribelus/eubobibogusgusbuBebeEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibibufrifribubigusius" ordered="false" eType="//FaGusbenulaugubeguboFriGuBenulIus" eOpposite="//FaGusbenulaugubeguboFriGuBenulIus/aunulaugusbeBobeNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BefribubuBiDagusbibocio" abstract="true" eSuperTypes="//AnaunulaunulEs //AnFribonulAubeBobetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiguGuGusbugubodafridagusDatus" abstract="true" eSuperTypes="//BeBufriNulaubuguBubuguDadabuCio //DoguGufrifriGusGubibefribelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubiNulaubiBebeBofriBuBuGusNus" eType="//AugusBodaGusbubuGusBufries" eOpposite="//AugusBodaGusbubuGusBufries/danulaubinulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Dogunulaudabulus">
    <eLiterals name="DoBebubefribiBiNulauboBilius"/>
    <eLiterals name="FafriFriFriFriGuBiButus"/>
    <eLiterals name="AunulAuboBocio"/>
    <eLiterals name="AuBeguBiLius"/>
    <eLiterals name="AlbuboNulius"/>
    <eLiterals name="DaBedaBeFritus"/>
    <eLiterals name="FagusDaguBibibucus"/>
    <eLiterals name="BrAubudagugusnulaufriguboLius"/>
    <eLiterals name="EunulAuFribobunus"/>
    <eLiterals name="AguBobiBenulaubibedacus"/>
    <eLiterals name="EnulAubibeFrigubebues"/>
    <eLiterals name="DigubibufribigubenulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibudaDaBeGugusbebotin" abstract="true" eSuperTypes="//AgusdabegusnulAuFriGufrigububetin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DibubibubinulAubebegugutin">
    <eLiterals name="DibiBubiguBibuLius"/>
    <eLiterals name="AufriBeBudabolus"/>
    <eLiterals name="EgusdabugudaBigusBidabubeDabeBidadatus"/>
    <eLiterals name="AlfribuNulaunulAuBuNulAugunules"/>
    <eLiterals name="BibofribebidafriGugugusaubebiguscus"/>
    <eLiterals name="AngusbinulAufrifriboGubeBogudabebitin"/>
    <eLiterals name="EbuguDaFriboBenulaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusbenulaugubeguboFriGuBenulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulIus" eType="//Bagusius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulaugusbeBobeNules" upperBound="-1" eType="//AlgugusNulAubeFrinulaugubiBeTus" eOpposite="//AlgugusNulAubeFrinulaugubiBeTus/bibibufrifribubigusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusbuGufridator" eSuperTypes="//DubuBefribofriboGugusAulius //DoguGufrifriGusGubibefribelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulaudanulAugubocio" ordered="false" eType="//BiguGuGusbugubodafridagusDatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBeGunulautor" eType="//Fanulaudafribigusaucus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusbebeBoGusdaFriboBilus" ordered="false" eType="//AgusdabegusnulAuFriGufrigububetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBonulauGusfribonus" eSuperTypes="//DofribedadaBeguDaDaGutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBudafriGusfriBogusAubelius" eType="//AlBugusnulAunulauFriboEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbebebunulAugusbifries">
    <eLiterals name="EuBenulaubedagusbunulaufries"/>
    <eLiterals name="DibodaGubidaBobibuBeNulAulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAunulAudabebodanulAugubibecio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beFrinules" eType="//Fanulaudafribigusaucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBobutor" instanceTypeName="typeAnbebiGusBubogubugusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbububugubogusBenus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dunulAuFrigufribeFribiFribuboNus" eType="//DibubibubinulAubebegugutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBeBuBiDaNulaufribeBegusboCus" eSuperTypes="//BebifribibiBobiBeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebububuBubububinus" eSuperTypes="//AnaunulaunulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FafriDaBegusbebobibecio" instanceTypeName="typeDaGusbuGuguBofriGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgubiGusbodadadabiGubegudaGuBuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabugusBidadafrigusGuTor" ordered="false" eType="//DigusbuGufridator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabubuBibobibubefridaLus" ordered="false" eType="//AlgusbonulauBuBobebiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgugusbenulauguDagusAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBigusBobobuNulaubicio" abstract="true" eSuperTypes="//AlgusbonulauBuBobebiEs //ENulAuFribegunulauBebiBenus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigusBedabiFriBogusdadagubelius" eType="//AlbebebunulAugusbifries" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigufrinulAububebotor" upperBound="-1" eType="//FadanulauFrinulaubiBinulauBicus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eDagunulAubeBulius" eType="//FafriDaBegusbebobibecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabububobeNulauBefridabubebinulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebobobedadacio" ordered="false" upperBound="-1" eType="//AlgusbonulauBuBobebiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboBeBeGuBegudabubulus" eSuperTypes="//BiBibebifriBobiBegubigusbilus //AlnulauFriboNulauFrinulAubobutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBegudabibuGusnulaulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugusbeguBonulaugustor" instanceTypeName="typeAlBonulAunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriNulauBebiBebibubuGusaubulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBoGusAufrinulautin" ordered="false" upperBound="-1" eType="//BidabigusbuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bebubugubidanulaufrilius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuBibuBibuboboBenulaufrinus">
    <eLiterals name="DoBigububuBoBiBibiGusBoCio"/>
    <eLiterals name="DadadaBudabebicio"/>
    <eLiterals name="BedafrigubegudaNulIus"/>
    <eLiterals name="AlNulAudafriCio"/>
    <eLiterals name="BrAuguGusbebiDabenulAubotus"/>
    <eLiterals name="AuBifribobibuGuBunus"/>
    <eLiterals name="BraudafriGusbidabuBees"/>
    <eLiterals name="AndafribeboFribeDafribuboBogutus"/>
    <eLiterals name="AnguFribiFriGusguFribegusGuguscus"/>
    <eLiterals name="DanulaugubiGuGuGuLus"/>
    <eLiterals name="AuBibeFriBidagunulAuNulautus"/>
    <eLiterals name="DadaBubuGusbufribenulAulus"/>
    <eLiterals name="AGunulauBogustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EufriNulaugugubuFriBibiCio" eSuperTypes="//ENulAuFribegunulauBebiBenus //AubodaGuboGucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBinulauNulaubebogustor" eSuperTypes="//DibudaDaBeGugusbebotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudaFribofriNulauguguDabotin" eSuperTypes="//DaBuFrigubifrifriBeGubodaBoBuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebebeguDanulAuboDabubitor" ordered="false" upperBound="-1" eType="//AlBugusnulAunulauFriboEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albinulAuGusDadaboBigusgusDabunus" ordered="false" eType="//AuBinulauNulaubebogustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAufribolius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabudaGuboFrinulAulus" eType="//DubebiNulauBiDafribibonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGudagusauFricio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudaguDadabibeNulauGulius" ordered="false" eType="//Bebubugubidanulaufrilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubuBebiguBiBogudadanus" ordered="false" upperBound="-1" eType="//BebububuBubububinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGusbobobibofribifriCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBegusFribegunulauGusAubiFridanules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiguBoBibobibugusGububofriEs" instanceTypeName="typeFaBegugudaFritor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnGugubigunulaunulAubonules">
    <eLiterals name="DubofriDaBodabiGubiDagusbilus"/>
    <eLiterals name="DubebiDadabodaFribobudaBefriguDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlboBuBedaDadaGuGusDaCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguguscio" ordered="false" eType="//BraunulaubiboNulauguslius" eOpposite="//BraunulaubiboNulauguslius/anfribibeguBogugubetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogugusBigubuGubogusBetus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enulauBeboGubobugucus" eType="//Bagusius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabiboBebubobofribelus" eType="//AuGubobodaBibobebenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaboGubiDadaBebeDabeGusdanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfriDafribufrifrinulaunus" eSuperTypes="//AnnulAufribolius //DuFriBuDagubitus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anguGuNus" eType="//FaBobutor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlBuBedafriBebufribebubotin" instanceTypeName="typeAbibiBobotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfribeGuNulAufribitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuDaBifriGusbinulauCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duguNulaugusBodafriNus" eType="//FafriDaBegusbebobibecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBubobuNulAuBegustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobiBodaBedagubulus" eType="//DiguBoBibobibugusGububofriEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulAuGuguguGusnulAubolus" ordered="false" eType="//DuDaBifriGusbinulauCio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diFriFriBolus" eType="//EuBibuBibuboboBenulaufrinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusBodaGusbubuGusBufries" eSuperTypes="//AuBinulauNulaubebogustor //BebububuBubububinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulaubinulaucus" ordered="false" upperBound="-1" eType="//BiguGuGusbugubodafridagusDatus" eOpposite="//BiguGuGusbugubodafridagusDatus/eubiNulaubiBebeBofriBuBuGusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagubogusdadagusFritus" eSuperTypes="//DaBigusBobobuNulaubicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDafrigusBebiBufriBiBubigutor" eSuperTypes="//AlBeBuBiDaNulaufribeBegusboCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusBiBudaBobedabuGuGuGusaubotin" upperBound="-1" eType="//FaBobutor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABunulauGuBuBibenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulAunulaugunulaufriBogusbeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDabonulauBodadanulAugusgunulauLus" eSuperTypes="//EufriNulauBebiBebibubuGusaubulius //DuFriBuDagubitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaDaBubiBubebibeDafriNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braufrigustor" eSuperTypes="//AlBugusnulAunulauFriboEs //EuboBeBeGuBegudabubulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusgusFriNulaubelus" ordered="false" eType="//DuDaBifriGusbinulauCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnaufrifrinulauBobutin" abstract="true" eSuperTypes="//AfribeGuNulAufribitor //BefribubuBiDagusbibocio //AfriDafribufrifrinulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGugusgusBogusnulaubigusFrifribuboBonulautin" abstract="true" eSuperTypes="//AlgubigusdaboBoFricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebibelus" ordered="false" upperBound="-1" eType="//DiNulAuFriBobiGuGusBoBebecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuFrinulAubuBegusBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaubogubeBeBifrigunus" eSuperTypes="//DuDaBifriGusbinulauCio //AlBeBuBiDaNulaufribeBegusboCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulauFrigusnulAunus" ordered="false" eType="//DonulAunulaugunulaufriBogusbeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobeBeBoGusBotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aNulauNulaubobefribubelius" ordered="false" eType="//DiGugusgusBogusnulaubigusFrifribuboBonulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AbuBinulAuBees" instanceTypeName="typeBibifribuGusbebubebiNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauBuBofribuTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babobifriBebuGusbebefribegusius" eType="//Braufrigustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdadanulAufriboTin" eSuperTypes="//DofribedadaBeguDaDaGutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doGusNulAuGusgusfriNulIus" eType="//AbuBinulAuBees" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubebeguFriguGusgusDanulaunules" upperBound="-1" eType="//AnFribonulAubeBobetus" eOpposite="//AnFribonulAubeBobetus/donulaugusauBoBeBeFries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaubifriBoDaBiDabulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBeguFridabubegufrinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebedafriFriDaBuBudanulaubuTin" ordered="false" upperBound="-1" eType="//EbuBubiBeBidanulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibufriBobobubunulautor" eSuperTypes="//FaGusbenulaugubeguboFriGuBenulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBeBoTin" ordered="false" eType="//AlBugusnulAunulauFriboEs" eOpposite="//AlBugusnulAunulauFriboEs/eBubidaBebeNulauBobees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DibibefrigudaboNulauDaBubugusCus">
    <eLiterals name="EuBifrigusNulaudabuGubedator"/>
    <eLiterals name="BrauguNulaufrinules"/>
    <eLiterals name="BeBobebebugusNulaubeguses"/>
    <eLiterals name="FaBogubufrigustin"/>
    <eLiterals name="BibeBuGusauFriBufriBodaguscus"/>
    <eLiterals name="FanulaudaBicus"/>
    <eLiterals name="BegusAuboBiboLius"/>
    <eLiterals name="DigunulaubedagusguDaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubeguBogusGusBeBofribudaGusboguguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulaugusgusfrigusfriBugusnulius" ordered="false" upperBound="-1" eType="//EbuBubiBeBidanulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraufrigusfribuFribeguses" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaBobiDaBidabugugufriboes">
    <eLiterals name="Balius"/>
    <eLiterals name="BenulAuBibiBubocio"/>
    <eLiterals name="AlbibeNulauGusnulauDaNulauGugugusTus"/>
    <eLiterals name="AnDabebubenulAuboGubobeguButin"/>
    <eLiterals name="DiBofribinulauDaGusBenus"/>
    <eLiterals name="BrauguDafriLus"/>
    <eLiterals name="EugusaufriBofrinulaugudalus"/>
    <eLiterals name="BrauDaboDaLius"/>
    <eLiterals name="EuguGudaFricio"/>
    <eLiterals name="BrauboBoGudaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAuGubeboTor" abstract="true" eSuperTypes="//EuBonulauGusfribonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbifriGudanulauBiguDafrifrilius" eSuperTypes="//EunulauBuBofribuTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauboBibiTor" upperBound="-1" eType="//Dogunulaudabulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusfriBobeFritor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaubeGubiBiCus" ordered="false" upperBound="-1" eType="//DuDaBifriGusbinulauCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabonulaugusgusboBefrinules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibidagudacus" ordered="false" upperBound="-1" eType="//BefribubuBiDagusbibocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBoNulAuFribibugufrifritin" abstract="true" eSuperTypes="//EgugusbenulauguDagusAucio //DinulAuGubeboTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebedabiBebegusDaBilus" ordered="false" eType="//BefribubuBiDagusbibocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbunulaudaboBoGutor" instanceTypeName="typeDubobubefribugusauFriBiTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusBogusBinulaubegugutin" instanceTypeName="typeBagubobegubibetus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbeGunulAubuEs" instanceTypeName="typeAnBeGubies"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaguboBoguNulaubinulaunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubebiBigusnulAuTin" eType="//FaBobutor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faFriBofriboGubuEs" eType="//DogusBogusBinulaubegugutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabufriBubobunulAunulaubucus" eSuperTypes="//AgusdabegusnulAuFriGufrigububetin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbobobubebiBugucus">
    <eLiterals name="AlFriBoDadaBobebuDabitin"/>
    <eLiterals name="Digufribibiguses"/>
    <eLiterals name="BabenulAubodabidabodadafribiBibelius"/>
    <eLiterals name="BiNulAuGusAuNulAubinus"/>
    <eLiterals name="EubeGuBiBubobegudaCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaufriGuslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribefribuguguFriDabutus" ordered="false" eType="//BiguGuGusbugubodafridagusDatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DugusgugusbeGusbiGufriFrifriEs">
    <eLiterals name="BadagusbeBubunulaunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebuFrifridaGusauguNulauLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubibiBiBiBugubibuNus" ordered="false" upperBound="-1" eType="//DibudaDaBeGugusbebotin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigubeGuBubuBudaBolius" ordered="false" upperBound="-1" eType="//AdanulauDaBobubies" eOpposite="//AdanulauDaBobubies/anGusgufribebiDadagustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANulaudabofritin" eSuperTypes="//BidabigusbuLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audabuFrifribitin" eType="//EuBibuBibuboboBenulaufrinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBuNulauDaFrigusIus" eSuperTypes="//AlBugusnulAunulauFriboEs //AuboDaGusnulaugusbolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBunulaunulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobugusnulAulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDagustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulautin" ordered="false" eType="//ABeBegugubugusDanus" eOpposite="//ABeBegugubugusDanus/biBubeNulAugustin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="efriNulAuBifrifrinulauGusNus" ordered="false" upperBound="-1" eType="//DigusbuGufridator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldabuGusguGuNulaubedagucio" ordered="false" upperBound="-1" eType="//FabububobeNulauBefridabubebinulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DogugusNulAufribudaLus" instanceTypeName="typeDobifribibeBuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bibogusfribecus" eSuperTypes="//DiBuNulauDaFrigusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobodagusGudabigusBibubofricio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBeDaDaFribocus" eType="//DaBigusBobobuNulaubicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulius" eSuperTypes="//BeBufriNulaubuguBubuguDadabuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulaubiboNulauguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribibeguBogugubetor" ordered="false" eType="//AlboBuBedaDadaGuGusDaCus" eOpposite="//AlboBuBedaDadaGuGusDaCus/duguguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeDabubiBeDaBudabuBoDaGubuBegustin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBibebobuDaNulaubiFrinulEs" instanceTypeName="typeDubuBibeBoBedator"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubudanulauBeFrinulautus" instanceTypeName="typeDoBobugusbuboBiguBudacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbedagugunulauBifriLus" eSuperTypes="//BebifribibiBobiBeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFriBegusbobetor" eSuperTypes="//AuBegudabibuGusnulaulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BeguBeNulaugudaEs">
    <eLiterals name="EubobiguboFrifriNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DonulauBedanulaubebeboBenulAucus" instanceTypeName="typeBeDanulauFrinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EboDagubuguBoTor" eSuperTypes="//ENulAuFribegunulauBebiBenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGuguBidabofribobigufrigusBuTin" eSuperTypes="//DobeBeBoGusBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bres" eSuperTypes="//BiBunulaunulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribuBucio" ordered="false" upperBound="-1" eType="//BiGusfriBobeFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubufribedadadabubefriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabubebugubinulauFrinus" eSuperTypes="//AnaufrifrinulauBobutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ditus" eType="//DogugusNulAufribudaLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibogugudaBobubegubeguGusbinulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibebibeguGusaucus" eType="//AlbebebunulAugusbifries" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FadabiBubibogubelus" instanceTypeName="typeBraugusbuDanulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusBuBofriDabifriGusGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeguFriBibuBuGuBoguNulauBiFries" eSuperTypes="//AubodaGuboGucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebuGusauBegubobegusFriBetin" eType="//DobeBeBoGusBotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGuBiguNulaubonulaufrilus" abstract="true" eSuperTypes="//BefribubuBiDagusbibocio //AnnulAufribolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubeboGusbebogudatus" ordered="false" eType="//BeDabubiBeDaBudabuBoDaGubuBegustin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babugusbogubobenulaubenus" ordered="false" upperBound="-1" eType="//EuBonulauGusfribonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AldabiGuNulauFriBeBebotor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofrigusGusBiboGuNulautin" ordered="false" eType="//AnaunulaunulEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabidabiBiGuGusfriTor" eType="//DibogugudaBobubegubeguGusbinulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabobibuguDaBiBoBoBues" abstract="true" eSuperTypes="//Braufrigustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusFrigudabobuboBuguFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubifriDagusBubegusbuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulAunulAugusBofriboBigubenulautus" ordered="false" eType="//ABunulauGuBuBibenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulauguguGues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AunulauNulius" instanceTypeName="typeEgusAugusbofribobufriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ducus" eSuperTypes="//BiBunulaunulautus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBegusBuFribuDadagububudaNulius" instanceTypeName="typeAnbibuDabenulaugusBebegusgubucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrifriBifrifrinulauBebibefriGugusAucus" abstract="true" eSuperTypes="//ENulaubifriBoDaBiDabulius //FagusbububugubogusBenus //DaBuFrigubifrifriBeGubodaBoBuTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaubuFrigutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubobuBeguboBiNulAuCus" ordered="false" upperBound="-1" eType="//FagusbububugubogusBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Babebocus" instanceTypeName="typeBigubifridafrifriBitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafribuBobobubuBogubibutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBubuBobeGuLius" ordered="false" upperBound="-1" eType="//FabubebugubinulauFrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadanulauboFriBubetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdaBunulaugufriGuEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algusgusbeBoDacio" eType="//Bagusius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adagusTin" upperBound="-1" eType="//DibubibubinulAubebegugutin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doNulaugusTus" eType="//AuBibebobuDaNulaubiFrinulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBobuGusBegusdaDaBotus" ordered="false" upperBound="-1" eType="//Braufrigustor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doguboguNulAufriCus" eType="//AuGubobodaBibobebenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdanulauDaBobubies" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGusgufribebiDadagustor" ordered="false" eType="//BebuFrifridaGusauguNulauLus" eOpposite="//BebuFrifridaGusauguNulauLus/bigubeGuBubuBudaBolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebedaBoBebuFriBinulAutus" ordered="false" eType="//BafribuBobobubuBogubibutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulauboBedaBuBobuBeNulAutor" ordered="false" upperBound="-1" eType="//DobigunulAudadaguTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibifribuDagubeFritus" eSuperTypes="//AlgusbonulauBuBobebiEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusbidabugubibuguEs" eType="//FaBobutor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabuNulAugusauboBebuBobilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAugusdagusdabobibubuGubobobutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulaugusfriTor" eType="//AunulauNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfribidaBigudagusgusbebulus" eSuperTypes="//DonulAunulaugunulaufriBogusbeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubenulAuBubeguDaBiBudaGuguCus" eSuperTypes="//DofribedadaBeguDaDaGutus //AlgugusNulAubeFrinulaugubiBeTus //DibifribuDagubeFritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauBegudagustin" eSuperTypes="//DiNulAuFriBobiGuGusBoBebecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EugusguBeGusgubuNulAugusbogusbuBidaLius" instanceTypeName="typeDabogusBofritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuTor" abstract="true" eSuperTypes="//BebuFrifridaGusauguNulauLus //FagusbububugubogusBenus //DiGugusgusBogusnulaubigusFrifribuboBonulautin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuguGububugusEs">
    <eLiterals name="AnGusgusaubufrigusbolus"/>
    <eLiterals name="FabubogusBebibeGunus"/>
    <eLiterals name="BeGufrifrinulAubudabebotus"/>
    <eLiterals name="DoBunulauBoguBegusnulauDanulius"/>
    <eLiterals name="Enulaunulaufrifritor"/>
    <eLiterals name="BefribibobefribobunulaufribeGuscio"/>
    <eLiterals name="BrAubufrifridagustus"/>
    <eLiterals name="AnAubuBobiEs"/>
    <eLiterals name="AnfribonulAubees"/>
    <eLiterals name="AGudabobobunules"/>
    <eLiterals name="AgubeBoBebobifriBubifrilius"/>
    <eLiterals name="EuBonulaufriguEs"/>
    <eLiterals name="EugusFrifriGudabufriDanus"/>
    <eLiterals name="AlnulaubedaGubugusbenules"/>
    <eLiterals name="AnbebedagusguTin"/>
    <eLiterals name="BraunulauBenulaunulauFriDacus"/>
    <eLiterals name="EubeguBibufribufribucus"/>
    <eLiterals name="DaguGuGusBibibiGusbiNulauNus"/>
    <eLiterals name="AugufribuBodaGusBobubodaguDagusnus"/>
    <eLiterals name="BrauDagusdabebegutus"/>
    <eLiterals name="FaguDadanulAunulaubeTus"/>
  </eClassifiers>
</ecore:EPackage>
