<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dubobocus" nsURI="http://hub.de/rcore/examples/dubobocus" nsPrefix="Fqvd">
  <eClassifiers xsi:type="ecore:EClass" name="BiGusbibobidadabeDacus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubugubiNulauFrigusGusGuEs" eSuperTypes="//BiGusbibobidadabeDacus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuGusGusguFridabofriTor">
    <eLiterals name="AndanulaugusBoBogusbubeBugusbeGusCus"/>
    <eLiterals name="BraufribefriGuboGusDaGubeBobolius"/>
    <eLiterals name="BraunulaugusBoNulaubifriFriBebibutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlauTin" eSuperTypes="//AubugubiNulauFrigusGusGuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euNulaubuGuguBunulAubobiTus" eType="//DabiGusbibiDacus" eOpposite="//DabiGusbibiDacus/euboGuGuBugubodaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBoBiBiDabiBegubibuGusLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulAudaGusBecus" ordered="false" eType="//AugusaugusbubugusLius" eOpposite="//AugusaugusbubugusLius/alfribegubebuDadanulauLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eudabebubufrifritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biDadadafribiguGusbetor" upperBound="-1" eType="//AlauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EububoDaGufribicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufriBubufribuBodaGunulEs" upperBound="-1" eType="//Eudabebubufrifritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusaugusbubugusLius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugunulaudafritor" ordered="false" eType="//DiBoBiBiDabiBegubibuGusLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfribegubebuDadanulauLus" ordered="false" eType="//DiBoBiBiDabiBegubibuGusLius" eOpposite="//DiBoBiBiDabiBegubibuGusLius/enulAudaGusBecus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubegusgusbetor" eType="//AuGusGusguFridabofriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibebinulauGuBegufriGusnulius" eSuperTypes="//AlauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulauFribobeTor" ordered="false" upperBound="-1" eType="//Eudabebubufrifritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusBebunulaubegusbibidaBulus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBofriBoGudagusnulauGutin" upperBound="-1" eType="//AlauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFrinulauguGubefribobiLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufribenulaubonulaunules" ordered="false" eType="//Eudabebubufrifritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusFribeGusbunulAuBugusgusbuCio" eSuperTypes="//DibebinulauGuBegufriGusnulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusBebobubudaFrigustus" upperBound="-1" eType="//AuGusGusguFridabofriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusfriFribidagugubibeGuNulaububecus" eSuperTypes="//DaGusFribeGusbunulAuBugusgusbuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibogusbuCus" ordered="false" upperBound="-1" eType="//DibebinulauGuBegufriGusnulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBeGusbibugusdabegusCio" instanceTypeName="typeBraubogunulauGuBeboBebibebuGusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBubugusDaNulius" abstract="true" eSuperTypes="//AubugubiNulauFrigusGusGuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babuFribegusbuboBitor" ordered="false" eType="//EFrinulauguGubefribobiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBigusnulIus" eSuperTypes="//DiBoBiBiDabiBegubibuGusLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGubeNulaugubebegusdagusdaBeGucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbiboGusbogufridabiEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiDabudabotin" instanceTypeName="typeENulaububeBedabonulaubinulauNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadanulaubenulaubeFries"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBuBubuBobeFribogubeBogudaGutus" eSuperTypes="//DaGusFribeGusbunulAuBugusgusbuCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anBeBiBuFriBelus" upperBound="-1" eType="//AuGusGusguFridabofriTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabuFrifrigugusaunus" eType="//AuGusGusguFridabofriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabiGusbibiDacus" eSuperTypes="//DaGubeNulaugubebegusdagusdaBeGucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euboGuGuBugubodaCio" ordered="false" upperBound="-1" eType="//AlauTin" eOpposite="//AlauTin/euNulaubuGuguBunulAubobiTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaboBoBigusguboguBobigubinulaubetus" eSuperTypes="//DaGusFribeGusbunulAuBugusgusbuCio //DuBuBubuBobeFribogubeBogudaGutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubegusguboBeboguGuCio" eType="//AuGusGusguFridabofriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBenulaubinulauFrilius" eSuperTypes="//AubugubiNulauFrigusGusGuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbigufriGusnulauGusbobofriLus" ordered="false" upperBound="-1" eType="//BiBigusnulIus"/>
  </eClassifiers>
</ecore:EPackage>
