<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fa" nsURI="http://hub.de/rcore/examples/fa" nsPrefix="qmMA">
  <eClassifiers xsi:type="ecore:EDataType" name="EububuDaDaFrigusgusaugusLius" instanceTypeName="typeBaboFribotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EguGusAubitor" instanceTypeName="typeAdagubibunulauGusbugusBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadabifrifriBiNulAunulaunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaDagusNulAubeBubuGutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBeDabefrifridacus" eType="//BadabifrifriBiNulAunulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudanulaubuBigusBiDadator" eSuperTypes="//BadabifrifriBiNulAunulaunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriBiGuNulAutus" eSuperTypes="//FaDagusNulAubeBubuGutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodabuNulAuguLius" eSuperTypes="//AudanulaubuBigusBiDadator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefrigusBebuBubobubuFriTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBegubobeNulaugusbitin" ordered="false" upperBound="-1" eType="//BadabifrifriBiNulAunulaunules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifriDabebedacus" ordered="false" eType="//DufriBiGuNulAutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ABoGusdabibuguFribeGusCio">
    <eLiterals name="BeNulauDanulaunulAugubibuFriCio"/>
    <eLiterals name="AbebodabuFriBeLius"/>
    <eLiterals name="EgusgubogusbibonulIus"/>
    <eLiterals name="AlgusnulAuBeguNulAuGusbetin"/>
    <eLiterals name="DuBeBeBeNulauDafricio"/>
    <eLiterals name="EubuBuGubigusboBubebiGudanus"/>
    <eLiterals name="BrAuDaNulaubiFriNus"/>
    <eLiterals name="AlbeGudaCio"/>
    <eLiterals name="Binulaugusgucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGunulAudaBoFriTus" eSuperTypes="//AudanulaubuBigusBiDadator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBugusgusBeDanulAubiDabebeTin" eSuperTypes="//DodabuNulAuguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraufrinulauGusaunulAuGusBilus" abstract="true" eSuperTypes="//FaDagusNulAubeBubuGutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audaDagusDaDabiTor" ordered="false" eType="//DudabebuBoGunulius" eOpposite="//DudabebuBoGunulius/eunulauGusGudaGutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBeguBebigusboNulauGunules" eSuperTypes="//AudanulaubuBigusBiDadator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulaugubiDaboGuCus" eType="//ABoGusdabibuguFribeGusCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANulAubibeBibugubonus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabidaBegusAugubeFrifricio" instanceTypeName="typeAufrinulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAunulaubiBobinus" eSuperTypes="//EBugusgusBeDanulAubiDabebeTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGugusbucio" ordered="false" upperBound="-1" eType="//AuGunulAudaBoFriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binulaubitor" eSuperTypes="//AuGunulAudaBoFriTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBobudaGuTus" eType="//ABoGusdabibuguFribeGusCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiFrigunulAuFriBibobebuguguLius" instanceTypeName="typeAlDadaBobigusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusauFribibefriNulautin" eSuperTypes="//AudanulaubuBigusBiDadator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dudagubofribubenulaugucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBebibiDabidanulAufrifrifriBucio" upperBound="-1" eType="//FaDagusNulAubeBubuGutin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agusfriDafriBugusCio" eType="//FabidaBegusAugubeFrifricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudabebuBoGunulius" abstract="true" eSuperTypes="//Binulaubitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulauGusGudaGutus" ordered="false" eType="//BraufrinulauGusaunulAuGusBilus" eOpposite="//BraufrinulauGusaunulAuGusBilus/audaDagusDaDabiTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbefribinulaudaBeBuCus" instanceTypeName="typeENulauboBigunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBidabebogusbobedaBeBuFries" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusauBuboFricio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusbibububeguFriBuBoNus" upperBound="-1" eType="//DudabebuBoGunulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGuNulaufribufrigusnules" ordered="false" eType="//BraufrinulauGusaunulAuGusBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusBufribiboGubiDagusBoFriNus" eSuperTypes="//BeGusauFribibefriNulautin //FaBeguBebigusboNulauGunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENulauBeBuFribuDadafriNus" abstract="true" eSuperTypes="//AudanulaubuBigusBiDadator //BeGusauFribibefriNulautin //Binulaubitor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alguGusnulaunus" eType="//FabidaBegusAugubeFrifricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AgunulauguguGusgufriFriCio" instanceTypeName="typeAuNulauBobebebeBeDagusbutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuboGusbobiboBefrigunulaunulius" eSuperTypes="//FaBeguBebigusboNulauGunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfriGusnulAubeDacio" upperBound="-1" eType="//BigusauBuboFricio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adadagusFribenulAunulaufrigusBonulIus" upperBound="-1" eType="//FaDagusNulAubeBubuGutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FadaNulauDabibiBiGuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabinulauNulaunulAubigusTor" eSuperTypes="//BigusauBuboFricio //Binulaubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibibiboBiBogubinulAugubetor" eSuperTypes="//FaBeguBebigusboNulauGunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabugufrigubogusbeNulAuBoguTor" eSuperTypes="//ENulauBeBuFribuDadafriNus //ANulAubibeBibugubonus //FaBeguBebigusboNulauGunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabegusGufricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabefriBiBiDagusCus" eSuperTypes="//BanulAunulaubiBobinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBefriguBubuGugudacus" eSuperTypes="//EBugusgusBeDanulAubiDabebeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdabifriBoNulAufriboGusGusBefribetus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DagusboDanulAufriBufribugusGusfriLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabifrifrinulaubefridaLus" instanceTypeName="typeEbuBoGudaDabeDalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulAugusnulauLius"/>
</ecore:EPackage>
