<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edanulaunus" nsURI="http://hub.de/rcore/examples/edanulaunus" nsPrefix="os">
  <eClassifiers xsi:type="ecore:EClass" name="Eubofribogusbunulaubitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGusauboBotus" ordered="false" eType="//DobogugusdagusbuBolius" eOpposite="//DobogugusdagusbuBolius/diguGusbobenulaubenulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulaufrinulaugusAudatus" eSuperTypes="//Eubofribogusbunulaubitin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBuNus" instanceTypeName="typeEudanulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiboboguNulAuboNulAucio" eSuperTypes="//Eubofribogusbunulaubitin //DaNulaufrinulaugusAudatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibebobuCio" eType="//EuBuNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaubunulaunulAubegubinus" eSuperTypes="//Eubofribogusbunulaubitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibeBudafribunulauGulus" eType="//EuBuNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobogugusdagusbuBolius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diguGusbobenulaubenulEs" ordered="false" eType="//Eubofribogusbunulaubitin" eOpposite="//Eubofribogusbunulaubitin/duGusauboBotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAugusGusgusbuBibigufriGusius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baDaBiNulAufriBolus" eType="//EuBuNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuGusbibiGuDabenulAulus" instanceTypeName="typeFaBiBobibogubigusbelius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DodaNulaugububodabeboNulEs" instanceTypeName="typeBrauguGusAuBoguBuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigubobefrigusBuNulauTor" eSuperTypes="//BiboboguNulAuboNulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbedagubodadagusboBofriBuboCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBeBeNulaubuguguNulaucio" eSuperTypes="//BiboboguNulAuboNulAucio //AbedagubodadagusboBofriBuboCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="an" ordered="false" upperBound="-1" eType="//BabebebobiBifriGusBubeCio" eOpposite="//BabebebobiBifriGusBubeCio/dofriDaDabinulauNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusgusBibiguscio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBuNulaubiDaBulius" eType="//AbedagubodadagusboBofriBuboCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbogugusauguDaBofriTus" eSuperTypes="//FanulaubunulaunulAubegubinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braugugusEs" upperBound="-1" eType="//EuGusbibiGuDabenulAulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babegufridaGubeGusLus" ordered="false" eType="//DunulAugusGusgusbuBibigufriGusius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusAubegubiDabibecus" ordered="false" eType="//Eubofribogusbunulaubitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBonulaubobobiNulaudacus" instanceTypeName="typeAuBunulAubinulaugusBonulaubunulaucio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauNulaudaBoFriBedanulaububiLus">
    <eLiterals name="BraugubodanulaubunulauGuboBicus"/>
    <eLiterals name="DibiFriGuBofricio"/>
    <eLiterals name="AnbibeguBeGusbotus"/>
    <eLiterals name="DuGusGusgubedabiTin"/>
    <eLiterals name="Begusgunulius"/>
    <eLiterals name="BefriGusbuBebibibuBudabegustin"/>
    <eLiterals name="BraubububifriGusgunulius"/>
    <eLiterals name="DagusaubunulauFribuFrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabebebobiBifriGusBubeCio" eSuperTypes="//Eubofribogusbunulaubitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGuFrifrigusbifritor" eType="//DuBeBeNulaubuguguNulaucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofriDaDabinulauNulius" ordered="false" upperBound="-1" eType="//DuBeBeNulaubuguguNulaucio" eOpposite="//DuBeBeNulaubuguguNulaucio/an"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BigusFriBiFriNulAuBidaGucio" instanceTypeName="typeDibobiBugusdafridabubuGubotin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EunulAubogufrigusgusbodanulauNulius" instanceTypeName="typeBabebubuGugububutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaubuguBunulius" eSuperTypes="//BiboboguNulAuboNulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebobibibibiBobeBuFrigusbeNules" eSuperTypes="//FanulaubunulaunulAubegubinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGuBinulAufrigusGusgusNus" upperBound="-1" eType="//EunulaubuguBunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Egusaufridanulaugubenulius" instanceTypeName="typeEuNulAubedaGugusbuTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DibiBegufriGubidabebuFriCus" instanceTypeName="typeEdaBidadabibuDanulauBenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADaNulaugusdafribeCus" eSuperTypes="//DaNulaufrinulaugusAudatus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraunulaubuBogubebucio" instanceTypeName="typeBeBebuNulaugusauboes"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagubeBucio" instanceTypeName="typeAldafribobigubotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadabiGusBoFrifrifriBucus" abstract="true" eSuperTypes="//EunulaubuguBunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufribenulauBitus" abstract="true" eSuperTypes="//FanulaubunulaunulAubegubinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBecus" eType="//BraunulaubuBogubebucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnAunulAuDabibofriFriNus" instanceTypeName="typeBadabibebigusautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBebibigusgusGusdabocus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudaCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafriDafrifrigusboBudagufrilius" ordered="false" eType="//BebobibibibiBobeBuFrigusbeNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusgugubigusgusfriboes" eSuperTypes="//AbedagubodadagusboBofriBuboCio //BiboboguNulAuboNulAucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dofriBoBebinulAuGufrifriGuscio" eType="//Egusaufridanulaugubenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubegusbiGustin" abstract="true" eSuperTypes="//EunulaubuguBunulius //AuGusgusBibiguscio //AbedagubodadagusboBofriBuboCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusBeFritin" ordered="false" eType="//DaGusgugubigusgusfriboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBofribugusdabeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusBonulaugusdagusbutin" eSuperTypes="//BraubegusbiGustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobiNulaunulAugusnulaubitin" eSuperTypes="//BebobibibibiBobeBuFrigusbeNules //DuBeBeNulaubuguguNulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidadabuboBunulauBubeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAuGubefridaGubulus" abstract="true" eSuperTypes="//BidadabuboBunulauBubeTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabefrinulAuGusNulAubeBoTor" eType="//EuGusbibiGuDabenulAulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusgusbuDabugusnus" upperBound="-1" eType="//EuGusbibiGuDabenulAulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FabiBobeFrinulEs">
    <eLiterals name="AguGusauBiTus"/>
    <eLiterals name="BiDabeDanulEs"/>
    <eLiterals name="DabedaBuBiBiDabibitin"/>
    <eLiterals name="AbuBufridagudaLius"/>
    <eLiterals name="DibinulauBudafribibeDalus"/>
    <eLiterals name="BaBeFribebiNulAubibibuEs"/>
    <eLiterals name="FafridaNulAudaGudanulAuFribibiLus"/>
    <eLiterals name="BibobiNulaubunulauGusboTor"/>
    <eLiterals name="EudafriGusGuBinulauguFrinus"/>
    <eLiterals name="DuGusbobodadabiCio"/>
    <eLiterals name="DafrifrinulaubeBubebonus"/>
    <eLiterals name="BraudadaguTus"/>
    <eLiterals name="BeFriBigufribuNules"/>
    <eLiterals name="FaboboboGusboNulaubonus"/>
    <eLiterals name="BebuBigusnulAuNulaulius"/>
    <eLiterals name="AfridabibubeguNulaunulautin"/>
    <eLiterals name="BeboBinulauguBugubobodabobebubenus"/>
    <eLiterals name="Bibinulaubunulaubigunulaudadabilius"/>
    <eLiterals name="Bigubugusfribinulautus"/>
    <eLiterals name="DigudaNulaubeBinulaucus"/>
    <eLiterals name="Aubigusfribebufribogulius"/>
    <eLiterals name="AnbubenulAugugusbobonulIus"/>
    <eLiterals name="Anfrinulaugutor"/>
    <eLiterals name="AlFriGusfrinulAuNulAufrinus"/>
    <eLiterals name="BibubuNulaubigubeBebubogusNus"/>
    <eLiterals name="BigubodaGusGusguboboDaDadaTor"/>
    <eLiterals name="EFribudabuBigusfribibuFriBuNulius"/>
    <eLiterals name="DobebubuBegusauDaGusnus"/>
    <eLiterals name="AnbidabunulauGustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AguBibeGusGusauBedagutus" instanceTypeName="typeBafriBogusfribubuBiTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulaunulaubunulauBoboGutor" eSuperTypes="//Eubofribogusbunulaubitin //AnbogugusauguDaBofriTus //BraubegusbiGustin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAuBifribeBibufrigusbeDabenules">
    <eLiterals name="BidabebubuBeGunulaubebibiCio"/>
    <eLiterals name="Abodabugubidalius"/>
    <eLiterals name="AugugugusBoNus"/>
    <eLiterals name="AubebinulAuGusBugugugusdagucio"/>
    <eLiterals name="AlgubofribuBegusaugustus"/>
    <eLiterals name="DuNulauNulauBoNulaubeButin"/>
    <eLiterals name="BifribebubudabuBebiguGuslus"/>
    <eLiterals name="DubinulauNulAucus"/>
    <eLiterals name="DigusBogufrifricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adanus" eSuperTypes="//AnnulAuGubefridaGubulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafriBebofriguscus" ordered="false" upperBound="-1" eType="//BraudaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusbuboBiBeboFriBufriBigufriCus" abstract="true" eSuperTypes="//EunulaubuguBunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaguGubues" abstract="true" eSuperTypes="//DaBebibigusgusGusdabocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGubunulAubeNulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBubugusbebeGusBiboNules" eType="//EuGusbibiGuDabenulAulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaugusaunulaububedaNulIus" abstract="true" eSuperTypes="//AuGusgusBibiguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbogubebeBunulAuBububibuFriBobeBoCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edaBigusgusButor" eType="//BigusFriBiFriNulAuBidaGucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidaguDafribifriBeCio" eSuperTypes="//AnbogubebeBunulAuBububibuFriBobeBoCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufrigusfrigubiBeDaboNulaunulius" ordered="false" eType="//FanulaugusaunulaububedaNulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufriboDanulauDatus" eSuperTypes="//FanulaugusaunulaububedaNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogubiGusauboEs" eSuperTypes="//DobiNulaunulAugusnulaubitin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaBuBeBiBoBeBunus">
    <eLiterals name="BraubeGusbibobuEs"/>
    <eLiterals name="BigusauGuBubonulaubeBebobobobebotin"/>
    <eLiterals name="DobufriDabofrinulaudatus"/>
    <eLiterals name="BiBinulAuFriBoCio"/>
    <eLiterals name="AugusbibenulauGusfriCus"/>
    <eLiterals name="BeBubofrifrinulAuBodabeBeTin"/>
    <eLiterals name="AlgugusnulaudabofribeGusIus"/>
    <eLiterals name="EubegubuFriFriBebuDaDagugusbiGugucus"/>
    <eLiterals name="AuBofribeGubufriboBidabees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugugusbubodaboDacio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EunulauDagugusgusbodanules" instanceTypeName="typeEFrigusNulaugusfriTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBifriguboDadaguBibenus" instanceTypeName="typeBrAubufribogusBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiGusbetin" eSuperTypes="//Eubofribogusbunulaubitin //DadabiGusBoFrifrifriBucus //DunulAugusGusgusbuBibigufriGusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBibefrifriBoBububuGusGusGusius" ordered="false" upperBound="-1" eType="//ADaNulaugusdafribeCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfrifriBogubidalius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBudafribuNus" upperBound="-1" eType="//EunulauDagugusgusbodanules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DonulAugusbubidaBobuBoguguCus" instanceTypeName="typeAlBidadaNulAuboGugutor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiguGugufridaBiNulAuFricio">
    <eLiterals name="BabedabigusgugusEs"/>
    <eLiterals name="DaGugubugusfribenules"/>
    <eLiterals name="DogusfrigubibigusBiguBuboBiTin"/>
    <eLiterals name="DuBigusgusgugufriTus"/>
    <eLiterals name="DaBubenulAuguBoBiBebebelus"/>
    <eLiterals name="AlGusBebues"/>
    <eLiterals name="Agubobigusbebetin"/>
    <eLiterals name="AnbeboDabuDaBuguCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabibuguBinulaubutus" instanceTypeName="typeAnBoBeGufriGusdafribetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaufrigusboDaBebuNulAubees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulaubiBibiCus" eType="//AnnulAuGubefridaGubulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Angusdagusnus" instanceTypeName="typeBrAubobiBoNulaudabububucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusnulAuDaGusius" eSuperTypes="//DaBebibigusgusGusdabocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaguNulaugusgusbebucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuDaFribubelus" instanceTypeName="typeBibiGuboDatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbinulaubebunulaufriNulaubuCus" eSuperTypes="//BabebebobiBifriGusBubeCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafribogubenulaubicio" ordered="false" upperBound="-1" eType="//Adanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusgubogubugusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusdabonulauBicus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusDabenulaunulius" ordered="false" eType="//FaguGubues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Babebudafribues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anauBofribogusbubeGusfribofricio" ordered="false" upperBound="-1" eType="//ENulaufrigusboDaBebuNulAubees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubeGubetus" eSuperTypes="//AufriboDanulauDatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusbidafribugubolus" ordered="false" eType="//DobogugusdagusbuBolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFrifribebogubebodaes" ordered="false" upperBound="-1" eType="//AbedagubodadagusboBofriBuboCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubigubobebefriBelius" ordered="false" upperBound="-1" eType="//BibiguFriNulIus" eOpposite="//BibiguFriNulIus/annulAububunulAugusgusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulaubonulaudaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibibiBiDanulaubugucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edaboGuBugusgunulAuGutus" eType="//FabiBobeFrinulEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" eType="//AnbogubebeBunulAuBububibuFriBobeBoCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBogusbugubebunulaucio" abstract="true" eSuperTypes="//DubeGubetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alDaBeBoDagusbeNulautor" ordered="false" eType="//EufribenulauBitus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulAubeDabelus" eType="//AnGubinulaubeFribobuBenus" eOpposite="//AnGubinulaubeFribobuBenus/braubugugusfriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabubobiBeFribegusdadabeBodacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badafribebitin" ordered="false" eType="//ADaNulaugusdafribeCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGubinulaubeFribobuBenus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubugugusfriTor" ordered="false" upperBound="-1" eType="//EuBogusbugubebunulaucio" eOpposite="//EuBogusbugubebunulaucio/alNulAubeDabelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusgusfrinulAuCus" eSuperTypes="//AbedagubodadagusboBofriBuboCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAuguFrinulauGucus" eSuperTypes="//BrauNulaubonulaudaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibiguFriNulIus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulAububunulAugusgusNus" ordered="false" upperBound="-1" eType="//DubeGubetus" eOpposite="//DubeGubetus/aubigubobebefriBelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBoGusBifribugusaubibolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadanulAubidabugudadaCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofriboBeBigubiGuBilius" ordered="false" eType="//AlgusbuboBiBeboFriBufriBigufriCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboGusbubeNulauguLius" eSuperTypes="//BidadabuboBunulauBubeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulAugudagugububoFrilus" abstract="true" eSuperTypes="//DadabiGusBoFrifrifriBucus //BabebebobiBifriGusBubeCio //DoBofribugusdabeTus //DibibiBiDanulaubugucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifridabibiDaNulauBeBenus" ordered="false" eType="//AuGusgusBibiguscio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baboDagubiTor" ordered="false" upperBound="-1" eType="//DoBofribugusdabeTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaubunulaudabodaBunules" abstract="true" eSuperTypes="//DobiNulaunulAugusnulaubitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusBubiGubedaGusGusfrigufribeGuBibucio" eSuperTypes="//BraubegusbiGustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaBobedabibobetin" eType="//FaGubunulAubeNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagunulaubiBuBonulaucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBugusaubinulaudalus" instanceTypeName="typeBraububiFribubiBeBoBebonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobebenulauGusAugubigusDatus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braugugugugusaucus" eType="//Angusdagusnus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBuNulaunulaubolus" eType="//DoBugusaubinulaudalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiGusdabibuGuNulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBebinulaufribibunulAulius" eType="//EuBuNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabidagusnulAufriDadaguses" eSuperTypes="//AnnulAuGubefridaGubulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribugusdafrifriGusguCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difrifribeboguCio" eType="//DiguGugufridaBiNulAuFricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgubibeNulauCus" eSuperTypes="//BrauNulaubonulaudaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudabibiGugubutin" upperBound="-1" eType="//BiboGusbubeNulauguLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobudaNulaubuBibefriBugubiCio" eSuperTypes="//BidadabuboBunulauBubeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abeGuBogusdanulauboDabebuGusbitin" ordered="false" upperBound="-1" eType="//FaguGubues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eudagugubibebobolus" eSuperTypes="//BiboGusbubeNulauguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbudaguGubebibudalius" eSuperTypes="//DadabiGusBoFrifrifriBucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbobubugububefriBeGudabebedalus" upperBound="-1" eType="//FaguGubues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgubedagunulAuGubigubiBobiFries" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlboguBoboGufriboBifrilius" abstract="true" eSuperTypes="//EufribenulauBitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbibeguDabedabeBodaguDatus" eSuperTypes="//BraudaCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBonulaubeEs" eType="//BraunulaubuBogubebucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBifriBobuguBoBeTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabobuBubufriBuguBeDator" instanceTypeName="typeBrauBeBeDabubiDadaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusNulaubiNulauFrigusfries" eSuperTypes="//DogubiGusauboEs //BidaguDafribifriBeCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BegusNulaubibedagubobidaTus" instanceTypeName="typeBabuDabiFribubobebobetor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AufribedabibogunulAuboBedabonus" instanceTypeName="typeDinulauDaDanulaunulauGutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGuBeGuBeBoDaNulaulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euboFriBibodagugusBiTin" eType="//AufribedabibogunulAuboBedabonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBudadanus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaubonulAuNulAuCio" eSuperTypes="//BiboboguNulAuboNulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeDaGusdabuDabuBunulAugugudabecio" eSuperTypes="//Eubofribogusbunulaubitin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabiGusgubigufriGugustin" instanceTypeName="typeBibibibugusgusbefriBinulauBugusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braunulaulius" eSuperTypes="//AnbogugusauguDaBofriTus"/>
</ecore:EPackage>
