<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dibedatus" nsURI="http://hub.de/rcore/examples/dibedatus" nsPrefix="CNt">
  <eClassifiers xsi:type="ecore:EClass" name="Eubobudabecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobobuDabebibogulus" instanceTypeName="typeDadanulAuGucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBebogudaBeTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egunulAuBigusboBoBudagubelus" ordered="false" upperBound="-1" eType="//EdaGugusDabiDafriboboTin" eOpposite="//EdaGugusDabiDafriboboTin/dufriNulaubinulaugusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdaGugusDabiDafriboboTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufriNulaubinulaugusNus" ordered="false" upperBound="-1" eType="//EBebogudaBeTor" eOpposite="//EBebogudaBeTor/egunulAuBigusboBoBudagubelus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braunulauBedagufritor" eType="//DobobuDabebibogulus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
