<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dogusgusnulaudagusgugues" nsURI="http://hub.de/rcore/examples/dogusgusnulaudagusgugues" nsPrefix="o">
  <eClassifiers xsi:type="ecore:EClass" name="DabuguBiNulauguDaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBedaguguBunulAufritin" eSuperTypes="//DabuguBiNulauguDaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriNulaubugusdanulEs" eSuperTypes="//EuBedaguguBunulAufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBonulaugusbibibeguDaguscus" eSuperTypes="//AnfriNulaubugusdanulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfriBubedafribebeGusboCus" ordered="false" eType="//AfrifribibebibibofribuDaTin" eOpposite="//AfrifribibebibibofribuDaTin/egusBebuFrifrinulAugusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuguguGusbubuDanulauDanules" eSuperTypes="//DiBonulaugusbibibeguDaguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulauGusgutor" ordered="false" eType="//DiBonulaugusbibibeguDaguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfrifribibebibibofribuDaTin" eSuperTypes="//DiBonulaugusbibibeguDaguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusBebuFrifrinulAugusNus" ordered="false" upperBound="-1" eType="//DiBonulaugusbibibeguDaguscus" eOpposite="//DiBonulaugusbibibeguDaguscus/anfriBubedafribebeGusboCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusguBoBeFriDagusBeDabodaTin" ordered="false" upperBound="-1" eType="//DabuguBiNulauguDaTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldadafribudafribedaNules" ordered="false" eType="//AuguguGusbubuDanulauDanules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faboNulaunulAugusdanulauguGufriTor" ordered="false" upperBound="-1" eType="//DiBonulaugusbibibeguDaguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DibobofriTus" instanceTypeName="typeAnbubigusbuBenulauGuBodadator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubibeFridabobufriguNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digubinulaufribubeCus" ordered="false" eType="//AuguguGusbubuDanulauDanules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaNulaubogusCio" instanceTypeName="typeAbibegubegusGusFrigutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBebiDadagubefribebubibuGusbuguCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBenulaubiGuNulAutus" instanceTypeName="typeAfrifriguBibiNulaubucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibibubeBoGusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaGuBobedator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbubebibiBuboNulius" upperBound="-1" eType="//AnfriNulaubugusdanulEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benus" eType="//DoBenulaubiGuNulAutus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abeBibibenulaulus" eType="//DaNulaubogusCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EBibedabifrinulAulius">
    <eLiterals name="EuBibibuBeBugusFriGustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauboGudafriBogusNulAudaBobotor" eSuperTypes="//EudaGuBobedator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagusgusnulaububifribitus" eType="//DoBenulaubiGuNulAutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubebofrigufriguguDaBiNulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aufriNulaugusLius" eType="//EBibedabifrinulAulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibeGuBibees" ordered="false" eType="//EuBedaguguBunulAufritin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGubocus" ordered="false" upperBound="-1" eType="//BeBuBiboNulauGusbudadaNulauBugusius" eOpposite="//BeBuBiboNulauGusbudadaNulauBugusius/alBigusgubonulAufriGusfriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBubobobubiguCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofriguFriFriguBedabenus" abstract="true" eSuperTypes="//BrAuBubobobubiguCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enulAugusNulaunulauboBegucio" eType="//DaNulaubogusCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaguNulaufriguBinus" instanceTypeName="typeDoGuGuBeBegusnulaunulauDacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboBeBeDanulauTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigubonulauGusgugunulAububocio" ordered="false" upperBound="-1" eType="//DiBonulaugusbibibeguDaguscus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="egubuBugusAuboGusDaNulAunulauGusLius" ordered="false" eType="//DiBonulaugusbibibeguDaguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaGuboBeBefribebeGubogusFriTin" instanceTypeName="typeEubecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusBoguscio" eSuperTypes="//DibibubeBoGusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agugusnulaugusbugusbigunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofrinulAuFribees" ordered="false" upperBound="-1" eType="//EubebofrigufriguguDaBiNulIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGubigubebonulAubuGuguTor" ordered="false" eType="//EBebiDadagubefribebubibuGusbuguCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begubebuboBebitor" ordered="false" upperBound="-1" eType="//AnaubogugusgusGuboNulius" eOpposite="//AnaubogugusgusGuboNulius/eunulauBeNulaubogusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebiguFrigusgusgusguBobebolius" instanceTypeName="typeFagufribuFrifricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGunulauguDabogusBeguBebies"/>
  <eClassifiers xsi:type="ecore:EClass" name="Egusnulaubogusbebigustin" eSuperTypes="//DofriguFriFriguBedabenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofrigusgusgusnulaugulius" ordered="false" upperBound="-1" eType="//FafribibebibuGuGusnulAuBetus" eOpposite="//FafribibebibuGuGusnulAuBetus/begusdagubigubenulaugusdator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EboNulaugubedadaes" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAunulauBenulauBebebebeNulius" ordered="false" eType="//AuguguGusbubuDanulauDanules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusguBiboBiBobufriEs" abstract="true" eSuperTypes="//EBebiDadagubefribebubibuGusbuguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGufrifriDagusGufriguFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBonulaubonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubibubeDabuBeBeDaBibetor" ordered="false" eType="//BibudagubonulAufrinulaubigusdabogubunus" eOpposite="//BibudagubonulAufrinulaubigusdabogubunus/anbuBoGuguBifribiGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabidafriNulAufricus" eSuperTypes="//EugusBoguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaubogugudaNulauTus" eSuperTypes="//AnnulauboGudafriBogusNulAudaBobotor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBidabufriDaBiBebeboTus" eType="//DaNulaubogusCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebiguboGusguGubiguDaFriTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogugusgusautor" eType="//EBibedabifrinulAulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusGusfridanulauFriFriguLus" ordered="false" upperBound="-1" eType="//DibibubeBoGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubogugusgusGuboNulius" abstract="true" eSuperTypes="//BrauGufrifriDagusGufriguFritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulauBeNulaubogusius" upperBound="-1" eType="//Agugusnulaugusbugusbigunus" eOpposite="//Agugusnulaugusbugusbigunus/begubebuboBebitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubibebidabecus" ordered="false" eType="//BebiguboGusguGubiguDaFriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafribibebibuGuGusnulAuBetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusdagubigubenulaugusdator" ordered="false" upperBound="-1" eType="//Egusnulaubogusbebigustin" eOpposite="//Egusnulaubogusbebigustin/dofrigusgusgusnulaugulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AldaGuscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulaubebebefriCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdabeNulaugusguboBenulAubolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBiDabogusboDaBebunulautor" eType="//DibibubeBoGusnus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobinulius" ordered="false" eType="//EubebofrigufriguguDaBiNulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibudagubonulAufrinulaubigusdabogubunus" eSuperTypes="//AGunulauguDabogusBeguBebies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbuBoGuguBifribiGucus" ordered="false" eType="//BrauBonulaubonus" eOpposite="//BrauBonulaubonus/braubibubeDabuBeBeDaBibetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbonulAububeNulAufrifriguNus">
    <eLiterals name="AubigusdaFriBiBeTus"/>
    <eLiterals name="AnbeGusnulaunulAuBiDabofriBibolus"/>
    <eLiterals name="DogusboGunulauGusguBonulauGubonus"/>
    <eLiterals name="AgusBuDadagusfricus"/>
    <eLiterals name="EuguFribibuBiGuBulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bedabefribocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabiGunulAubebebunulaudafrigusdabobutin" abstract="true" eSuperTypes="//FafribibebibuGuGusnulAuBetus //EBebiDadagubefribebubibuGusbuguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafriFribobiguBufrinulauguEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auBoBubenulaubutin" eType="//EBibedabifrinulAulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebiGugusbebeNulaugusfriBeBunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlFrigusaulus" instanceTypeName="typeDuboDaFribetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaGusbebugusgubonulAubecus" eSuperTypes="//DofriguFriFriguBedabenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beboBibobonulaubibebiEs" ordered="false" upperBound="-1" eType="//EboNulaugubedadaes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusbogubibibuBuGucus" ordered="false" eType="//DaBidaguscus" eOpposite="//DaBidaguscus/bibiBogusbifrigufriguguTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAugusbubebiBucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBidaguscus" eSuperTypes="//EugusBoguscio //AudaGusbebugusgubonulAubecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibiBogusbifrigufriguguTor" upperBound="-1" eType="//AudaGusbebugusgubonulAubecus" eOpposite="//AudaGusbebugusgubonulAubecus/agusbogubibibuBuGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbububoGubobofricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angudabeGusdaes" ordered="false" eType="//DibibubeBoGusnus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babiNulaudadabotor" eType="//AlFrigusaulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusfribifribues" ordered="false" eType="//DabidafriNulAufricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBuBiboNulauGusbudadaNulauBugusius" eSuperTypes="//DofriguFriFriguBedabenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadadafrifridafribitus" ordered="false" eType="//DofriguFriFriguBedabenus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBigusgubonulAufriGusfriTus" ordered="false" eType="//EubebofrigufriguguDaBiNulIus" eOpposite="//EubebofrigufriguguDaBiNulIus/brauGubocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BiGusgusBoDaFrigubicio" instanceTypeName="typeBaBoboBebogubedabiBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabugusauNulaubitus" eSuperTypes="//Bedabefribocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedanulAubobogudaFrigusBobeguBeBibuCio" ordered="false" upperBound="-1" eType="//EugusBoguscio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidagusbuFribebidabegubugustus" ordered="false" upperBound="-1" eType="//AnnulauboGudafriBogusNulAudaBobotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBudabudafritor" eSuperTypes="//BrAuBubobobubiguCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abeguLius" ordered="false" eType="//EboNulaugubedadaes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beguBiBiBonulAubebibuBeDabufriNus" ordered="false" eType="//AnaubogugusgusGuboNulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aNulaugusAuFriGubeBibubedagusfricio" ordered="false" eType="//EuBedaguguBunulAufritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anbibunulaunulaubutor" eSuperTypes="//BrauBudabudafritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulAuFritus" eSuperTypes="//AnfriNulaubugusdanulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBiBobeBebebenulaufribotus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duNulaudabebugusDalus" eType="//DibobofriTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Augusius" eSuperTypes="//DofriguFriFriguBedabenus"/>
</ecore:EPackage>
