<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="al" nsURI="http://hub.de/rcore/examples/al" nsPrefix="OKiV">
  <eClassifiers xsi:type="ecore:EClass" name="FaBigusNulaubeboBebogubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bibenulaugusbogusgubibubifridalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufribeboBoBenulAuGusnulAuFries" upperBound="-1" eType="//AunulAubidalius" eOpposite="//AunulAubidalius/diGusfribudabiBufribocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugugusbigusguFriDaFricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badabebigusnulautin" ordered="false" upperBound="-1" eType="//Bibenulaugusbogusgubibubifridalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BibebibiFriBodabibinulaucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabeBuguBoBibibubiBebugusaunus" instanceTypeName="typeFabiBububegusdabiFrifribegusfriTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBiBiFrigusButor" eSuperTypes="//EugugusbigusguFriDaFricus //FaBigusNulaubeboBebogubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAububudabufriFriBobidaguslius" eSuperTypes="//DaBiBiFrigusButor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBifribebibibibufrinus" abstract="true" eSuperTypes="//EugugusbigusguFriDaFricus //FaBigusNulaubeboBebogubonus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bi" eType="//BibebibiFriBodabibinulaucus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugudaGuBebedaBees" eType="//FabeBuguBoBibibubiBebugusaunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubufriBidadabebobudanulaunus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="befrigusdaboGusdabodagubiEs" eType="//FabeBuguBoBibibubiBebugusaunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daFriGuGuBoLus" ordered="false" upperBound="-1" eType="//BanulAububudabufriFriBobidaguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebogubedaBibiguscio" instanceTypeName="typeEuFribeboNulauGugustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfriboboBoguBibobufriGuslius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAubidalius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboguBebiBogudalius" ordered="false" upperBound="-1" eType="//BaBifribebibibibufrinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGusfribudabiBufribocio" ordered="false" eType="//Bibenulaugusbogusgubibubifridalus" eOpposite="//Bibenulaugusbogusgubibubifridalus/aufribeboBoBenulAuGusnulAuFries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faFrigusgusAufridadacus" eType="//AuBonulauGuGuTus" eOpposite="//AuBonulauGuGuTus/duGusBoNulaubogusdaBugusgusauTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusFriNulauBicus" ordered="false" upperBound="-1" eType="//BrAubuBibobefribunulAuBiBodagunus" eOpposite="//BrAubuBibobefribunulAuBiBodagunus/dofribiNulauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBonulauGuGuTus" eSuperTypes="//BraubufriBidadabebobudanulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGusBoNulaubogusdaBugusgusauTor" ordered="false" eType="//AunulAubidalius" eOpposite="//AunulAubidalius/faFrigusgusAufridadacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagudaBogusBoGugububoBuboNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBedabeGusGusBebunus" eType="//BibebibiFriBodabibinulaucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusnulAububiCus" eSuperTypes="//BraubufriBidadabebobudanulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubuBibobefribunulAuBiBodagunus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agunulAubiDaTin" ordered="false" eType="//DagudaBogusBoGugububoBuboNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofribiNulauCus" eType="//AunulAubidalius" eOpposite="//AunulAubidalius/begusFriNulauBicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DagusDaguBoGubeBoguFriFrigusGusnulaulius" instanceTypeName="typeBiNulaufriBeboGusGufribetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbegusauNulautor"/>
</ecore:EPackage>
