<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fatus" nsURI="http://hub.de/rcore/examples/fatus" nsPrefix="zJFC">
  <eClassifiers xsi:type="ecore:EClass" name="EubuGudaboBucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuboFriBebubogusBodanulEs" eSuperTypes="//EubuGudaboBucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabegugusgubucus" upperBound="-1" eType="//AnulaubifriNulautus" eOpposite="//AnulaubifriNulautus/anBunulauBeGuFribubegusaubibucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaGugufriBiguboNulauFriCus">
    <eLiterals name="DiBuguBiNules"/>
    <eLiterals name="BigubibiDabiNulaunus"/>
    <eLiterals name="FanulaunulauGusbeBonus"/>
    <eLiterals name="AunulauNulauGusBoBoBibibunulAutor"/>
    <eLiterals name="AnBofribogugusNulauBicus"/>
    <eLiterals name="DobibebubobeFribobubibudatus"/>
    <eLiterals name="DaGusFribodadabeLus"/>
    <eLiterals name="BraufrigusgufrifrigusBoLius"/>
    <eLiterals name="DiGusAunulAunulaubeFribububiCus"/>
    <eLiterals name="AndafriBeboGusfrinulius"/>
    <eLiterals name="DuDabifribofriboboTor"/>
    <eLiterals name="AgusGusbegusbogubifriCus"/>
    <eLiterals name="FaNulaufribidaBogusBuGuslius"/>
    <eLiterals name="AlguguBugubebiFribies"/>
    <eLiterals name="DibibebefrinulauGubiDacus"/>
    <eLiterals name="EBodaBodaNulaugulus"/>
    <eLiterals name="AlGufribifribeFribiBobees"/>
    <eLiterals name="DagusdadagusNulaubeBugusnus"/>
    <eLiterals name="BaBobeBobubeguGuGusgusguBotus"/>
    <eLiterals name="Aufridafribudabubebonus"/>
    <eLiterals name="BefrifribobuDagudaLus"/>
    <eLiterals name="BeFribodabeBiFriBebeNulAunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Braunus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dubolus" eSuperTypes="//EubuGudaboBucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulauGusfrinulAufriguNulAunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BenulAunulAuGusbiDabibelus" instanceTypeName="typeAnGusNulauFrigusdalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbubiFribuGuBoGufribelus" abstract="true" eSuperTypes="//EunulauGusfrinulAufriguNulAunus //Braunus //DuboFriBebubogusBodanulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaDanulaugubebuboDagutin" instanceTypeName="typeBifridagubegudabubiBigucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DinulauBeFricus" instanceTypeName="typeAbegusdabibibotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBiBibobidanus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaboFrinulaugudafriLus" instanceTypeName="typeEugusbiboboBubifrigubuBoes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulaubifriNulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBunulauBeGuFribubegusaubibucio" ordered="false" eType="//DuboFriBebubogusBodanulEs" eOpposite="//DuboFriBebubogusBodanulEs/dabegugusgubucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubububuguGuguGusbifriBefries" instanceTypeName="typeBraugugusbibunulaudagudanulAuBigusguGucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugubifribibuBiBunulaubuBuDanulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeGusbodaBiCus" eSuperTypes="//DaBiBibobidanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusboGuBoguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AFrigusaugubibefrinulaunulAuNulauBuBeTin" eSuperTypes="//AnulaubifriNulautus //Dubolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGusnulauBogusBigugusbotin" ordered="false" upperBound="-1" eType="//DuboFriBebubogusBodanulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgunulAuBebobebunus" eSuperTypes="//EubuGudaboBucus //Dubolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaunulAubuDagusbuguguLus" eSuperTypes="//FagusboGuBoguscus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeBofriGubogugubuBuGusgutin" instanceTypeName="typeDinulAugudafrigusbibufribogusTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBiBigufriBibodaBeguBeGusTus" eSuperTypes="//EgunulAuBebobebunus //DanulaunulAubuDagusbuguguLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusFriNulaugusaubelus" ordered="false" upperBound="-1" eType="//AnulaubifriNulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBuboNulaubidaBiFriDaDanulAugunules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobifrigusboBuDabububobinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binulAuBubuNus" eType="//BenulAunulAuGusbiDabibelus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBefribufribuBifrifrifricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abebidabebutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBedaDabiNulaubobuNulAuBunus" ordered="false" upperBound="-1" eType="//FagusboGuBoguscus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusdadanulaubodaFribufricio" ordered="false" eType="//DaBiBibobidanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauDaBobeFriNulautin" instanceTypeName="typeBebibedaBiFriBobecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriBibuDabufriTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AboNulauGusbeFrilius" instanceTypeName="typeAndaFriDafriboBuBibuDadabofriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bebetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBibebunulauNulAuBuGusbuBugugutin" eType="//DobifrigusboBuDabububobinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EdagusnulAubeGububigusbuBulius" instanceTypeName="typeEbefriDadafrifridabigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusgusauboNulAugusGudaEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binulaugusCio" eType="//AboNulauGusbeFrilius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albebeboGusbudabetor" ordered="false" upperBound="-1" eType="//DaBiBibobidanus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fafriBonulaubiTin" eType="//EdagusnulAubeGububigusbuBulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboboBiBoBedagusnulautus" eSuperTypes="//AnulaubifriNulautus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alaunulaugubiNulAubies" eType="//DubububuguGuguGusbifriBefries" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugubebibubigubetor" ordered="false" eType="//EuBuboNulaubidaBiFriDaDanulAugunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBudadaFribedacio" eSuperTypes="//DanulaunulAubuDagusbuguguLus //Braunus //Bebetus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FafrinulaubigubeGusnus" instanceTypeName="typeDabonulauFriNulAubibebofribiLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibigugusGusBoDaNus" eSuperTypes="//BraugubifribibuBiBunulaubuBuDanulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlauGusboBonulAunulius" instanceTypeName="typeABebiFriBiboNulaubies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulAuBubeNus" eSuperTypes="//FagusboGuBoguscus //Braunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BafrinulauboNulaudaguBitus" instanceTypeName="typeBebegunulaunulAuBobugusnulAufriGustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusgusbodabobiNulAuGubegusgusgusNus" abstract="true" eSuperTypes="//BebeGusbodaBiCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebibibuBoBibebinulaunulAuGudatin" ordered="false" upperBound="-1" eType="//BiboboBiBoBedagusnulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiBodadaBodaNulaubuNulius" eSuperTypes="//BiboboBiBoBedagusnulautus //Braunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGubofribefrigusbeDabefriNules" ordered="false" upperBound="-1" eType="//AnulaubifriNulautus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubobinulauDaGustor" ordered="false" upperBound="-1" eType="//BibigugusGusBoDaNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabugusAufrinulauGuses">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aunulauguBibetor" eType="//BenulAunulAuGusbiDabibelus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Di" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudabibefriFriCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBobubebofridator" ordered="false" eType="//DuboFriBebubogusBodanulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeBeGubibibuDabuNus" eSuperTypes="//DaBiBibobidanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebogusNulauBidabeGusaugusnus" ordered="false" upperBound="-1" eType="//EgunulAuBebobebunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifridaGusnulAunulauguTus" eSuperTypes="//AlbeBeGubibibuDabuNus //AlbiBodadaBodaNulaubuNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusnulaubeBinulaubugusDaBoTin" ordered="false" eType="//DanulaunulAubuDagusbuguguLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAuBuBebuNulaubenulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBedagugusGuboGusguGusEs" ordered="false" upperBound="-1" eType="//AlbeBeGubibibuDabuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EudabobunulauCio" instanceTypeName="typeDabogusgubefribufrigusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebibibinulauGusgunulius" eSuperTypes="//EgunulAuBebobebunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabifridagubibudagutin" ordered="false" upperBound="-1" eType="//DifridaGusnulAunulauguTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagugusfrifriBecus" eSuperTypes="//AuBiBigufriBibodaBeguBeGusTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulaubiboBuFrifribugustor" eType="//Di"/>
  </eClassifiers>
</ecore:EPackage>
