<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="donulaugubedafricus" nsURI="http://hub.de/rcore/examples/donulaugubedafricus" nsPrefix="JoV">
  <eClassifiers xsi:type="ecore:EClass" name="Braudalus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBoGusbuNulAuDaGuFrifrigustin" eSuperTypes="//Braudalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofriGugusbiFribiGusguFribufridaTus" ordered="false" eType="//Braudalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaubonulaulius" ordered="false" eType="//Braudalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAutor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alAudabububobebogusBugusAubicus" ordered="false" eType="//FaBoGusbuNulAuDaGuFrifrigustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BraubiGubogubudaNulaucio">
    <eLiterals name="AlfribogusFriBobunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedadabebeguBedaguFrigufrigusBiCio" abstract="true" eSuperTypes="//Braudalus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diGusbebobobudaes" upperBound="-1" eType="//BraubiGubogubudaNulaucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusGusguBunulaugusGuscus" eSuperTypes="//FaBoGusbuNulAuDaGuFrifrigustin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulauNulEs" eType="//BraubiGubogubudaNulaucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobegubibudaBebecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabugugusAuBoDabubufriBeBiEs" eSuperTypes="//DobegubibudaBebecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFribegusfrilius" ordered="false" upperBound="-1" eType="//BrAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBibedaguBudaGusbetus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBibeBiBebibufrigufribogusCus" upperBound="-1" eType="//FaBoGusbuNulAuDaGuFrifrigustin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaudaBubefriBebiBubunulaubiDator" ordered="false" eType="//EuBobebubeboboBiGuNulauBonus" eOpposite="//EuBobebubeboboBiGuNulauBonus/fabobigusgusdaboBugusTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubebidanulAudaboBetus" eSuperTypes="//BrAutor //BedadabebeguBedaguFrigufrigusBiCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebedagusbuGuBiGusbubibudaTor" ordered="false" upperBound="-1" eType="//FabugugusAuBoDabubufriBeBiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaGugusfridaFridaBuguBogubonulaulus" instanceTypeName="typeBefriboBuGuBucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuGusbeGuBigubilus" abstract="true" eSuperTypes="//DobegubibudaBebecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubenulaudaboFribenulaunulaunulius" abstract="true" eSuperTypes="//EgusGusguBunulaugusGuscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFrigusDaFribeguBiLus" eSuperTypes="//DobegubibudaBebecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugugugusBoFrilius" eSuperTypes="//BrauFrigusDaFribeguBiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuguBuBibudanulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabuNulaubeBuBububebecio" instanceTypeName="typeEuDabuDabeGubeCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafriBobeGusFribiDaFribunulAugucus" eSuperTypes="//FaBoGusbuNulAuDaGuFrifrigustin //AnBibedaguBudaGusbetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiBufrifriGusLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbegububoDaDaBoBitor" instanceTypeName="typeBibeGusbedaNulAuGuscus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlfribenulaubuBeBilius">
    <eLiterals name="DaGusgusbefribuDaFrigusnus"/>
    <eLiterals name="BeBeBuFridaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Albefritin" instanceTypeName="typeAgudaBoBoBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dadafrinulaugusnus" abstract="true" eSuperTypes="//DubenulaudaboFribenulaunulaunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaboBegusTin" eSuperTypes="//AnBibedaguBudaGusbetus //AubebidanulAudaboBetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibogusguDaBeGunus" ordered="false" eType="//DubenulaudaboFribenulaunulaunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alnulaufrifribenus" eSuperTypes="//FabugugusAuBoDabubufriBeBiEs //EgusGusguBunulaugusGuscus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBogubegudatin" eType="//AlfribenulaubuBeBilius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baBibiGusaubetor" eType="//BaGugusfridaFridaBuguBogubonulaulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaNulaubiboGusgudabigusnulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Braugubegugunus">
    <eLiterals name="Braubidaes"/>
    <eLiterals name="DudaGuGusbeguBugudabobetus"/>
    <eLiterals name="BegubenulaufrinulaubeBucio"/>
    <eLiterals name="AnBufrigusGunulaubodaCio"/>
    <eLiterals name="EfribofribeBibiguBebifribinus"/>
    <eLiterals name="DufrinulAuboNulaubeGubegusguTor"/>
    <eLiterals name="BaBebetor"/>
    <eLiterals name="EboguBebebebobuGulus"/>
    <eLiterals name="EubeBiBodaGusbeFrifriguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulaubegudagubibogusbogues" eSuperTypes="//BrauFrigusDaFribeguBiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidabeBeBinulauBufribonulAubibufriBunulauBubeTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBogubinulauBoNulaubeBetor" ordered="false" upperBound="-1" eType="//BrauFrigusDaFribeguBiLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BidaFribigusnulaudaes" instanceTypeName="typeDoGusaunulauBudaBeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlAuBobofribodabutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diguDabegucio" ordered="false" upperBound="-1" eType="//DubenulaudaboFribenulaunulaunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabeDaguGugusbibitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebeBebubububebugubeNulius" ordered="false" eType="//FaBoGusbuNulAuDaGuFrifrigustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBoboGusbofricus" eSuperTypes="//DidabeBeBinulauBufribonulAubibufriBunulauBubeTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobogusbedagusDabebiBonus" ordered="false" eType="//Alnulaufrifribenus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibubebubobebobebofriBebeBoTin" ordered="false" eType="//AugugugusBoFrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Babinulaufricio" abstract="true" eSuperTypes="//BrauFrigusDaFribeguBiLus //Braudalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafrifribibeCio" ordered="false" eType="//BrAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoNulaugubuLus" instanceTypeName="typeAnulaudabuGuBuNulaugusDaDanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofridagusBiBubonules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBobebubeboboBiGuNulauBonus" eSuperTypes="//EudaboBegusTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alNulAugububobubotus" eType="//AlfribenulaubuBeBilius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabobigusgusdaboBugusTor" ordered="false" upperBound="-1" eType="//AnBibedaguBudaGusbetus" eOpposite="//AnBibedaguBudaGusbetus/anaudaBubefriBebiBubunulaubiDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauBuguBofrigusbibubigunulauguguscus">
    <eLiterals name="AlBinulaudaBefricus"/>
    <eLiterals name="BiFriBiGuBobegunulautor"/>
    <eLiterals name="EudaguNulauFrifricio"/>
    <eLiterals name="ENulaubidaBubitus"/>
    <eLiterals name="DuNulaubibobiFribiDacus"/>
    <eLiterals name="AudadafrifribuBonulauFribebiTor"/>
    <eLiterals name="EbinulauFriBiNulaubigulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AguBiGuFriBiFriBibobuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaboBodagusbebeCio" eSuperTypes="//DidabeBeBinulauBufribonulAubibufriBunulauBubeTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusbugudabobocus" ordered="false" upperBound="-1" eType="//DidabeBeBinulauBufribonulAubibufriBunulauBubeTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBefribubobogusAuDafritin" eSuperTypes="//BedadabebeguBedaguFrigufrigusBiCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusgububebigubegusBebibitus" ordered="false" eType="//DobegubibudaBebecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BebubobebiBinules">
    <eLiterals name="AubobeNulauBefriGuGugusCus"/>
    <eLiterals name="EunulaunulauBulius"/>
    <eLiterals name="DofriBuguses"/>
    <eLiterals name="EuBoFribiNulauboes"/>
    <eLiterals name="BrauBeGudaDabiBotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anbunulaubobibobilius" abstract="true" eSuperTypes="//FaBoGusbuNulAuDaGuFrifrigustin"/>
</ecore:EPackage>
