<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bibigusbilius" nsURI="http://hub.de/rcore/examples/bibigusbilius" nsPrefix="EBA">
  <eClassifiers xsi:type="ecore:EClass" name="AlfrifribubuFridabefrigusGuboTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubiBonulauGuguNus" ordered="false" eType="//BafriGusnulauBuBoboDanus" eOpposite="//BafriGusnulauBuBoboDanus/biGusBubefribogugusGugusdafricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dugusbedabies" eSuperTypes="//AlfrifribubuFridabefrigusGuboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafriGusnulauBuBoboDanus" eSuperTypes="//AlfrifribubuFridabefrigusGuboTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albeBifribebiBiGutus" ordered="false" upperBound="-1" eType="//AlfrifribubuFridabefrigusGuboTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusBubefribogugusGugusdafricio" eType="//AlfrifribubuFridabefrigusGuboTus" eOpposite="//AlfrifribubuFridabefrigusGuboTus/aubiBonulauGuguNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudabudagubebefriboguLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebubiBobebiLius" instanceTypeName="typeDabeFridabufrifrigusbofridaLius"/>
</ecore:EPackage>
