<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anlus" nsURI="http://hub.de/rcore/examples/anlus" nsPrefix="vjK">
  <eClassifiers xsi:type="ecore:EClass" name="EgubifriboDatus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudaBuBibegusdanulauBigusBenus" eSuperTypes="//EgubifriboDatus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiguBigusaunulauBebugusLus" instanceTypeName="typeBaDabebotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedabigubibiGubedagusbiFriBobegulus" eSuperTypes="//BraudaBuBibegusdanulauBigusBenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebinulaubenulAubefriNulaulius" ordered="false" upperBound="-1" eType="//EgubifriboDatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulaunulaubiguNulAuboTus" eType="//BiguBigusaunulauBebugusLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiDaDadagusDagusBuBudaGuGugusbitus" eSuperTypes="//BedabigubibiGubedagusbiFriBobegulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifribibeFriBinulIus" eSuperTypes="//BiDaDadagusDagusBuBudaGuGugusbitus"/>
</ecore:EPackage>
