<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="braubedalus" nsURI="http://hub.de/rcore/examples/braubedalus" nsPrefix="ze">
  <eClassifiers xsi:type="ecore:EClass" name="DobiGuFrifriBibicus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaunulAugusgubibotin" eSuperTypes="//DobiGuFrifriBibicus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audabebububibobonus" ordered="false" eType="//DobiGuFrifriBibicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusAubeBuBoBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulAuguguslius" ordered="false" eType="//BenulaunulAugusgubibotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGuGusnulauBugusgusaubidacio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Annulaudagufrigustin">
    <eLiterals name="BrAudabibitus"/>
    <eLiterals name="BeGuNulaubeBoGusBebidatus"/>
    <eLiterals name="EfriNulAugusbocio"/>
    <eLiterals name="AlFriBigustin"/>
    <eLiterals name="FaGuboGusbodaBububiboNus"/>
    <eLiterals name="EubidanulAubobelius"/>
    <eLiterals name="AuBunulaufribegusfridaFriboTin"/>
    <eLiterals name="DabedagugudafriEs"/>
    <eLiterals name="BrAuBugusfrifribiTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgubuTus" eSuperTypes="//DobiGuFrifriBibicus //BenulaunulAugusgubibotin //EugusAubeBuBoBonus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Fabodatin" instanceTypeName="typeBegusbeFrigusaugusfrigusaugusDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubobebegusbubiDabuDabuLius" eSuperTypes="//EgubuTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabebobuBobugusbutin" abstract="true"/>
</ecore:EPackage>
