<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dubicus" nsURI="http://hub.de/rcore/examples/dubicus" nsPrefix="HB">
  <eClassifiers xsi:type="ecore:EDataType" name="DufriDaBufriBegusfridadacio" instanceTypeName="typeDigusfrigugubofrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGububogubelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidabegusbeBefridagusNulauNulius" eSuperTypes="//DuGububogubelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doDator" ordered="false" upperBound="-1" eType="//DuGububogubelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBebubeFridaNulauFrifriBeBodadaguscio" abstract="true" eSuperTypes="//BidabegusbeBefridagusNulauNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbobeGusnulAuboBuTus" abstract="true" eSuperTypes="//DuGububogubelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBeboDabibebuBilius" ordered="false" eType="//BidabegusbeBefridagusNulauNulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diboBobecus" eType="//DufriDaBufriBegusfridadacio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaGusBebuTin" instanceTypeName="typeDifrigugusbobigusbedagucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuguGugusbeFriBibeBiGucio" eSuperTypes="//AnbobeGusnulAuboBuTus //BidabegusbeBefridagusNulauNulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fanulauBuBiBebedaes" eType="//DaGusBebuTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusdabibuBubobobugusgusNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbegunulaufrinulauBuboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andabiNulaudabigubudabebobolius" ordered="false" upperBound="-1" eType="//AnbobeGusnulAuboBuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbegusbibofriboFribuBoes" abstract="true" eSuperTypes="//DuGububogubelius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFribeDabobubuDagusBofribebilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bidabugubolus" eSuperTypes="//AnbobeGusnulAuboBuTus //DiBebubeFridaNulauFrifriBeBodadaguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaDabonulaugusGugububucus" eSuperTypes="//DuGububogubelius //AnbobeGusnulAuboBuTus //Bidabugubolus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubidabebeGusbobinulauLus" instanceTypeName="typeFabobugugubiGusFribuGubobiGustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifridabeDatus" abstract="true" eSuperTypes="//DuGububogubelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBiGubogufrigusCio" upperBound="-1" eType="//AnbobeGusnulAuboBuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiBuGusfriBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGubenulAunus" eSuperTypes="//BaDabonulaugusGugububucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBobedabegubogusBububuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anNulaubeBudadafriBeboBicio" ordered="false" upperBound="-1" eType="//AbegunulaufrinulauBuboes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abibinulaubiLus" eType="//DufriDaBufriBegusfridadacio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAuGunulAudanus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidabubidafriGubebebiBotin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauBenulauBiFriGusdalius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EbeguBubugubuBeDaGusLius" instanceTypeName="typeFabobubibiNulAubigusbilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaDaNulAunus" instanceTypeName="typeAboBoFribigusFrigusbebuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBeNulAutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusBuBobeCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldaBoboFribedabidaDaCio" eSuperTypes="//BaDabonulaugusGugububucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubibibobubidaDaGusnulaulius" instanceTypeName="typeAlbuGusDabeFribudacus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlGusbigusbefrifrigusbifriCus" instanceTypeName="typeAlBegusgubotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgunulaunulauBidaBobifrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBibibiBubenulaunulaugutor" ordered="false" eType="//DiBebubeFridaNulauFrifriBeBodadaguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaububuFribebibebifriLus" eSuperTypes="//EbegusbibofriboFribuBoes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBegusbiBebiFriboboTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbibobugunulAuBeguBoGusbubues" upperBound="-1" eType="//AldaBoboFribedabidaDaCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBonulAuboGugufribugusnules" ordered="false" upperBound="-1" eType="//AlNulaububuFribebibebifriLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DobegusbenulauGuNules" instanceTypeName="typeAnBiBitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FafribiNulaubogusAugubibogusbuBugucio" instanceTypeName="typeAgusbibebiFribigusGusbiNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBoBebebegusDanulauLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anBibeguNus" eType="//DobegusbenulauGuNules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBibibibubonulauBogusBufriBitor" ordered="false" upperBound="-1" eType="//DugusdabibuBubobobugusgusNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbiguBebiguslius" eSuperTypes="//AlNulaububuFribebibebifriLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badaBolius" eType="//FaDaNulAunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobeBenulaudabudabebubelius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudabudaboBedaGuBubuGusius" ordered="false" eType="//DifridabeDatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusFriBifriFrinulauCus" abstract="true" eSuperTypes="//Bidabugubolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaubebeGunulautus" eSuperTypes="//AbiguBebiguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidabeGugusbogusbubenulauLius" eSuperTypes="//DiBoBebebegusDanulauLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusdabogusbobibibecio" eType="//BaDabonulaugusGugububucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBinulauBuBiGusbebiGulus" instanceTypeName="typeAlBigubidabiBedaTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauBiBodagufriBebonulEs" instanceTypeName="typeEuguGubibotor"/>
</ecore:EPackage>
