<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bafribilus" nsURI="http://hub.de/rcore/examples/bafribilus" nsPrefix="lep">
  <eClassifiers xsi:type="ecore:EClass" name="BebugudaGuDabeFrifrigusnules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBoBigusbutor" ordered="false" upperBound="-1" eType="//AbeDagufribebefriguslus" eOpposite="//AbeDagufribebefriguslus/fafriBibobudabefriBunulaunulauButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AndaBububebenulauCus">
    <eLiterals name="DoBuGusdaBofribudadaBubiTin"/>
    <eLiterals name="DaGuboFribegubeBilus"/>
    <eLiterals name="EubiBibebofrifrinulauguscus"/>
    <eLiterals name="Aubegusgulus"/>
    <eLiterals name="DadabugugusGusbugufriLius"/>
    <eLiterals name="DubonulaubogusIus"/>
    <eLiterals name="ABoGuFribudaBubifribiNulaunus"/>
    <eLiterals name="ABoGubeGunulauguscus"/>
    <eLiterals name="AuboFridafridabiEs"/>
    <eLiterals name="BraubifrinulauNulius"/>
    <eLiterals name="AnaubibeGubobuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbeDagufribebefriguslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafriBibobudabefriBunulaunulauButor" ordered="false" eType="//BebugudaGuDabeFrifrigusnules" eOpposite="//BebugudaGuDabeFrifrigusnules/faBoBigusbutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulauGubuBofriCio" eSuperTypes="//AbeDagufribebefriguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabidaGufriGusGustor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dodabunulAubeCus" eType="//AndaBububebenulauCus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebobufriBubuDaCio" ordered="false" upperBound="-1" eType="//AbidaBogubogugubogusIus" eOpposite="//AbidaBogubogugubogusIus/dobuGusgusaunulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugusBoguNulAufrilius" instanceTypeName="typeBiBobuBiboBiBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobibunulauBubibiNulius" eSuperTypes="//AbeDagufribebefriguslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiboGuBulius" ordered="false" eType="//FanulauGubuBofriCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbidaBogubogugubogusIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobuGusgusaunulaulus" ordered="false" eType="//BabidaGufriGusGustor" eOpposite="//BabidaGufriGusGustor/bebobufriBubuDaCio"/>
  </eClassifiers>
</ecore:EPackage>
