<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dubobidagulus" nsURI="http://hub.de/rcore/examples/dubobidagulus" nsPrefix="LM">
  <eClassifiers xsi:type="ecore:EClass" name="AuNulaububuBogucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dogubuguscio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FagubonulAugufribunulaudabolus">
    <eLiterals name="AnnulAunulius"/>
    <eLiterals name="FabobefribiBuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadanulAudaNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGugusdabonulAudaDalius" eSuperTypes="//Dogubuguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusbegusDabeBedabonulAudanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuGuDaDaBoGusFrifribies" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudaBudabidabibebonulauboBegusbonus" eSuperTypes="//EGugusdabonulAudaDalius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubibobifriDaboFriGugulius" eType="//BrAuGuDaDaBoGusFrifribies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauFrigusAugusTus">
    <eLiterals name="FadafriGusguguscio"/>
    <eLiterals name="EuguBubufrigusgues"/>
    <eLiterals name="EuNulAugubufrilius"/>
    <eLiterals name="AnfriBidabugusAufriBubobubunus"/>
    <eLiterals name="DuBebunulauboboFridadaBugugunulautor"/>
    <eLiterals name="AlGusbibeBebefriFrilus"/>
    <eLiterals name="BagusBigusbugubeFridabobies"/>
    <eLiterals name="DuBedaGuboBeBeBububoBubiLus"/>
    <eLiterals name="BaBibebigufrinulAuBubuBiBigues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuGubobugudaguBebubogububutus" instanceTypeName="typeDabubobodaGusboguDaguNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DigubinulAuFrifrinulAucus" instanceTypeName="typeEBogufriFribidagulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfrinulAubeNulaudaGusGusbeDatus" eSuperTypes="//BrAuGuDaDaBoGusFrifribies"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAuguBoguGunulaubunus" abstract="true" eSuperTypes="//AfrinulAubeNulaudaGusGusbeDatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubudaTin" upperBound="-1" eType="//BeGusbegusDabeBedabonulAudanules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusnulAuBugusnulAubidagutor" eSuperTypes="//AuNulaububuBogucus //BeGusbegusDabeBedabonulAudanules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AufriBegubodadabuNulius" instanceTypeName="typeBifribeGubibiDaFridaGustus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DafridaNulAubeNulaufrifrinules">
    <eLiterals name="BeGuGugubugusdacus"/>
    <eLiterals name="DonulauFrifridagusbuGusCio"/>
    <eLiterals name="Dugubigusnulaubenulaufrinulius"/>
    <eLiterals name="ABefriguFribocus"/>
    <eLiterals name="BabeNulauBuLus"/>
    <eLiterals name="BegufrifrigudaBeNulaudagusnules"/>
    <eLiterals name="AnnulAubeFribuguBiboguGuGusgubutor"/>
    <eLiterals name="BaGudaGusauGucus"/>
    <eLiterals name="AlbiBetin"/>
    <eLiterals name="DigunulaubuGudabiCio"/>
    <eLiterals name="DugububofriNulAuBudacio"/>
    <eLiterals name="DigusfrifrigubebeNules"/>
    <eLiterals name="BraunulAuBiGusboes"/>
    <eLiterals name="BaBobeGufribebuDabubetor"/>
    <eLiterals name="DogunulaububidaBedabubibebegusLius"/>
    <eLiterals name="BebebuFribubonulaubufridaTor"/>
    <eLiterals name="AlDaBedabedabufriFriBeDabiEs"/>
    <eLiterals name="BagusbubebiBoBiBinulAunulauNules"/>
    <eLiterals name="AlbubuguboBegusaugubies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusBubuGuGufribedaGusboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dadanulaubibuBuGuslius" eType="//DafridaNulAubeNulaufrifrinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusbuFrigusboBuDagusBetin" eSuperTypes="//BeGusbegusDabeBedabonulAudanules //BrAuGuDaDaBoGusFrifribies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daGusdaNulauBebuNulAuBibubelus" upperBound="-1" eType="//AufriBegubodadabuNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DigugusFriFrinulius" instanceTypeName="typeFabegusdadafriGubiBiboGufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dibenulaugusfribonus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EunulAuBubebofriDadaguGusdaBigusGusbotus">
    <eLiterals name="EuBoNulaunulAubibiFrifrifribudator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBibebiboboGusDacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diFribuGuDaGusGusauBibuNulius" eType="//AuNulaububuBogucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DadaGubodagusGudabeBitor" abstract="true" eSuperTypes="//BaBibebiboboGusDacio //BeGusbegusDabeBedabonulAudanules //AlnulAuguBoguGunulaubunus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubodaGusBuFriGufributor" instanceTypeName="typeAl"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubinulAuDanulAuBinulAubudagugucus" eSuperTypes="//Dogubuguscio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlfribuGusGuBoNulauboNus" instanceTypeName="typeEBebuBibinulAuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABoGusaugubufrinulautin" eSuperTypes="//BaBibebiboboGusDacio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egufriCus" eType="//FagubonulAugufribunulaudabolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabubiBoNulauBoBubodaGusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubobibugusgusGusfribugusdaDacio" upperBound="-1" eType="//ADaBoBebenulautus" eOpposite="//ADaBoBebenulautus/dinulaugusfriBuDabubeFrifribugugusCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbeguDacio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusgusauDabubenulIus" ordered="false" eType="//ABoGusaugubufrinulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADaBoBebenulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaugusfriBuDabubeFrifribugugusCio" ordered="false" upperBound="-1" eType="//DabubiBoNulauBoBubodaGusNus" eOpposite="//DabubiBoNulauBoBubodaGusNus/eubobibugusgusGusfribugusdaDacio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufrinulAuGusnulaugugunus" ordered="false" eType="//ABoGusaugubufrinulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubiGusdaBiBitin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBeFrifrifrigubugutin" eSuperTypes="//DogusnulAuBugusnulAubidagutor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagusaudaguses" eType="//AuGubobugudaguBebubogububutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulAuguBuDabibedabies"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubebububoBifrigubees" instanceTypeName="typeAbefriBubenulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoboguDaBugusGutin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusbegusguEs" eType="//Dogubuguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabedabugusBidaBotor" eSuperTypes="//BaBibebiboboGusDacio //EubinulAuDanulAuBinulAubudagugucus //DadaGubodagusGudabeBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubiBubinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibenulauDaboGubugusAucio" ordered="false" upperBound="-1" eType="//BagusbuFrigusboBuDagusBetin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedadabugusFridaBinulaulius" upperBound="-1" eType="//AufriBegubodadabuNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnulAunulAubobobeDabuNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiguBubibodacio" instanceTypeName="typeBebobiguFrigusdabotin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeguBonulaunulAubuBefribebugusguBucio" instanceTypeName="typeDofrinulaubiguGusGubedaGusGuBeGusgues"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaNulAubitor">
    <eLiterals name="DuboFrigusnulAufriFriBeBoguDanulius"/>
    <eLiterals name="BefriFribifriGusbiGuguDadalius"/>
    <eLiterals name="EGubebeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBefrinulAubugusdabufriLus" instanceTypeName="typeAuBeGusaubodabodaBoTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusDabogusfriBues" abstract="true" eSuperTypes="//BeGusbegusDabeBedabonulAudanules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abugusgubibuNulaubidabebutus" ordered="false" upperBound="-1" eType="//DiBeFrifrifrigubugutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fagufrigubofridagugusdatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulaubifribobuDanulauNus" upperBound="-1" eType="//BagusbuFrigusboBuDagusBetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibibuGufrifridaNulauguBinus" eSuperTypes="//DiBeFrifrifrigubugutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anfriNulaunulAuBobeFriNus" eType="//BeguBonulaunulAubuBefribebugusguBucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egudaBiBibicio" eType="//DaNulAubitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBofriGusAugubeDabubulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBufribiBugusDaGusGuBoFriGues" eSuperTypes="//AlBofriGusAugubeDabubulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiGusgusBoFrinulauBodaFriFridacio" instanceTypeName="typeBebiBidafrifriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadaGusbegubiFriBeBobiLus" abstract="true" eSuperTypes="//DogusnulAuBugusnulAubidagutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBuDabiGusLus" ordered="false" eType="//AuNulaububuBogucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABefriGusNulAugusbobuguTin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBinulauBibodalius" ordered="false" upperBound="-1" eType="//BraudaBudabidabibebonulauboBegusbonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnFriBegufribiDanulAutus">
    <eLiterals name="AlFribunulaunulaulus"/>
    <eLiterals name="BigusbunulauGuBigusbegusauBufricus"/>
    <eLiterals name="DobiGusGudanulaugudaGusAubeNus"/>
    <eLiterals name="BraugubebiBuBegusBunulauBitor"/>
    <eLiterals name="AubiFriGugusBobutin"/>
    <eLiterals name="AldaBeBegusgubeBubuGunulius"/>
    <eLiterals name="Aubibenus"/>
  </eClassifiers>
</ecore:EPackage>
