<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aunulaubibecus" nsURI="http://hub.de/rcore/examples/aunulaubibecus" nsPrefix="FC">
  <eClassifiers xsi:type="ecore:EClass" name="BraugubobunulaubuBiBies"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusBibedabies"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AufriguBedaBinules" instanceTypeName="typeEubufribubuGusgusdaBogubidanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndaBuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubodabinulaubibuLus" eSuperTypes="//BraugubobunulaubuBiBies //FagusBibedabies"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauDaguFriBuGuNulaunules" instanceTypeName="typeBrauBiguBodaBubebonulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBibuguGubeBufriBubeBobinus" eSuperTypes="//FagusBibedabies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagutor" upperBound="-1" eType="//BraugubobunulaubuBiBies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FaBunulAuBodabetor">
    <eLiterals name="EbiFriGugudaBodaFridabeTor"/>
    <eLiterals name="AlbofrifriDaNulaubobunulaufricio"/>
    <eLiterals name="DogubobufriFriBinulius"/>
    <eLiterals name="AudaFribufriBegusfribubetin"/>
    <eLiterals name="EubeNulAugusgusBubeBubebiBuFritor"/>
    <eLiterals name="Dabebubogusbubicio"/>
    <eLiterals name="EudafrifribeboNulaubudabibubefribuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBugunulauGusGusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADagufribogubenulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusbubiFriCus" eType="//FagusBibedabies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BagusNulAugusgunulius" instanceTypeName="typeDadaBefriGuDaNulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgugusdadaFriGuFriGufriGucus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBuDagusbogubugufritor" ordered="false" eType="//DaBugunulauGusGusIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagubudatus" ordered="false" upperBound="-1" eType="//EDagusaubuButin" eOpposite="//EDagusaubuButin/braugusgunulaubidabuGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugubobiboguNulauDanus" abstract="true" eSuperTypes="//ADagufribogubenulautin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algusfrinulaunulaunulaugusbinules" eType="//FaBunulAuBodabetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbiDaBugusfriBegusgutor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euDaBogustus" eType="//FaBunulAuBodabetor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugufrigusaufriBebelius" eType="//DaBugunulauGusGusIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDagusaubuButin" eSuperTypes="//ADagufribogubenulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusgunulaubidabuGucus" ordered="false" upperBound="-1" eType="//AlgugusdadaFriGuFriGufriGucus" eOpposite="//AlgugusdadaFriGuFriGufriGucus/dagubudatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboBoguBeFribegulus" eSuperTypes="//BraugubobunulaubuBiBies //EDagusaubuButin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagunulauBeGubifribebobenulEs" abstract="true" eSuperTypes="//EbiDaBugusfriBegusgutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafriGusBoBoBegugucus" eType="//FagusBibedabies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="didaguDafriGusbunus" ordered="false" upperBound="-1" eType="//EDagusaubuButin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBeFrinulAubobunulaubeLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulAuNulAuDabigusbeTor" ordered="false" eType="//AlBibuguGubeBufriBubeBobinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbibuBoBubefrigubetus" instanceTypeName="typeEBidaBeFriBoNulauDaNulauCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeNulaugubuDabuGuboBuNulauLus" instanceTypeName="typeBebidafrifribinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidabidaBubeGudaLus" eSuperTypes="//AlBibuguGubeBufriBubeBobinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFriDaGusBigusgufrigusbuboTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGudagusbebiBeTin" ordered="false" upperBound="-1" eType="//BidabidaBubeGudaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodabebifribufriDaGuBidanulaunus" eSuperTypes="//EuboBoguBeFribegulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAufriFrinulAunulAucio" eType="//BrauDaguFriBuGuNulaunules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubudaBuFrigusguTin" eSuperTypes="//EDagusaubuButin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubenulaubebufriDabiEs" abstract="true" eSuperTypes="//DodabebifribufriDaGuBidanulaunus //EbiDaBugusfriBegusgutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Audadafridagubebidanus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dagusbiGuNus" eType="//AufriguBedaBinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubogusGusgusbobeguses" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBebidagusgusdaboguFritor" eType="//AlDabeBenulauNulaugutin" eOpposite="//AlDabeBenulauNulaugutin/duGunulauboNulauBeBetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufriNulauGuDadacio" eSuperTypes="//AubenulaubebufriDabiEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ABodagunulauGusFridaBoGunulius" instanceTypeName="typeDiBobobebiguBiBigufriDadaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauDaGusbuGusnulaudagusCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbibogusgusdagugusBobotor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubeNulauBebiGuCio" eType="//AufriguBedaBinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlDabeBenulauNulaugutin" abstract="true" eSuperTypes="//EbiDaBugusfriBegusgutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubugubiNulAuBibilius" ordered="false" upperBound="-1" eType="//EbiDaBugusfriBegusgutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGunulauboNulauBeBetin" ordered="false" upperBound="-1" eType="//AubogusGusgusbobeguses" eOpposite="//AubogusGusgusbobeguses/euBebidagusgusdaboguFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBeGusBobubogubidacus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeguBeBobinulaufrifrigusBegusBobutin" eSuperTypes="//AlgugusdadaFriGuFriGufriGucus //AubogusGusgusbobeguses">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fafribuboboFrilius" eType="//BeNulaugubuDabuGuboBuNulauLus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
