<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="benulaunulaugusaubulius" nsURI="http://hub.de/rcore/examples/benulaunulaugusaubulius" nsPrefix="mx">
  <eClassifiers xsi:type="ecore:EClass" name="AuBibeboBegusauboes" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbunulAuFriFrifriboDatin" instanceTypeName="typeDiGusbuDaNulaubotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgubebibuBuGusBobiFribogusbonulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBobuFridadabifribiBuEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eGubeBenulaubibegusFries" eType="//AbunulAuFriFrifriboDatin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BibuNulauGugusbebibiGufridagusbilus" instanceTypeName="typeBigusguBibedadafrigugusgugusbibifriGuscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobiFrigusDatus" eSuperTypes="//AnBobuFridadabifribiBuEs //AlgubebibuBuGusBobiFribogusbonulius"/>
</ecore:EPackage>
