<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="didabobebucus" nsURI="http://hub.de/rcore/examples/didabobebucus" nsPrefix="tam">
  <eClassifiers xsi:type="ecore:EDataType" name="FafridaFribunulAudaBubibecio" instanceTypeName="typeDuguBefriboDaFrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusbobubuFribiNulaubeCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubuNulaubebeBuGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobeDaBeBogubinus" eSuperTypes="//DigusbobubuFribiNulaubeCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="efritus" eType="//FafridaFribunulAudaBubibecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaguguBeGusauBubibedatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baBofriBuNulaugusFrigusFries" eType="//FafridaFribunulAudaBubibecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dagugunulaubegusbies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babigusbiBogusGuEs" ordered="false" eType="//DobeDaBeBogubinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBoBobigusFrifritin" eSuperTypes="//DigusbobubuFribiNulaubeCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabufrigusnulauBebiboFrigucio" ordered="false" eType="//DobeDaBeBogubinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuboDabibibuBugusnulAutor" eSuperTypes="//DigusbobubuFribiNulaubeCus //Dagugunulaubegusbies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobibiGubenulIus" ordered="false" upperBound="-1" eType="//DobeDaBeBogubinus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabiBigusBonulauBulus" eType="//FafridaFribunulAudaBubibecio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euBufriDabunulaunulauCus" eType="//FafridaFribunulAudaBubibecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlGugunulAuGuslius" eSuperTypes="//Dagugunulaubegusbies"/>
</ecore:EPackage>
