<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albugubibetor" nsURI="http://hub.de/rcore/examples/albugubibetor" nsPrefix="Xr">
  <eClassifiers xsi:type="ecore:EDataType" name="BrauBoBugunules" instanceTypeName="typeDobebububobofrigusboEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulaugusbuBuGuguBebofrinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabibobebugugusaububigusIus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BigusFriGugubiNus" instanceTypeName="typeDobiDagubeFriFribibiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBiGusGuFriNulAufrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabudaBubiBudabiBinulAunulaugusbetin" abstract="true" eSuperTypes="//BrAunulaugusbuBuGuguBebofrinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBugusguLus" ordered="false" upperBound="-1" eType="//BeBiGusGuFriNulAufrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabofribogunulAubunules" eSuperTypes="//BeBiGusGuFriNulAufrinus //DabibobebugugusaububigusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbunulaufriBobelius" eSuperTypes="//DabudaBubiBudabiBinulAunulaugusbetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afridagubenulaucus" eType="//BrauBoBugunules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubobibeBobuboBebubudacus" abstract="true" eSuperTypes="//DabofribogunulAubunules //DabudaBubiBudabiBinulAunulaugusbetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befrinulaudagusauBeGusAugusnulaubigusEs" ordered="false" eType="//DabudaBubiBudabiBinulAunulaugusbetin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euguNulauBebibinulauNus" ordered="false" eType="//AbunulaufriBobelius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebobobonulaunulautin" eType="//BigusFriGugubiNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBebeGusbeNulAuGusgunus" ordered="false" upperBound="-1" eType="//BrAunulaugusbuBuGuguBebofrinules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlnulaunulauGuBoGuscio" instanceTypeName="typeDiBibeBigutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiguFrinulauguNulauBugusnus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlBeBufrifritus">
    <eLiterals name="DobuBudabuguNulAubegusBibebuBeLius"/>
    <eLiterals name="BaguBudadaDaBebodadator"/>
    <eLiterals name="BaguBeBubodaGusauguFriCio"/>
    <eLiterals name="BaGuNulauFriboGuFrinulius"/>
    <eLiterals name="AnBibubebebeFriNulauFrifriBelius"/>
    <eLiterals name="BiBuNulaubuGusnules"/>
    <eLiterals name="DiGuGubeBobuGugusnus"/>
    <eLiterals name="BraufriNulAugubenulaugusbeCus"/>
    <eLiterals name="DidabiGugugudabiBegustin"/>
    <eLiterals name="AlfrifrifriBiBuGusAubibutin"/>
    <eLiterals name="BraubiBigusBefrifrifribiNus"/>
    <eLiterals name="DoBebibuBunulaugusbiBiBies"/>
    <eLiterals name="BraubefrinulaufriTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusbidaDabeFribeBebufriLus" eSuperTypes="//BrAunulaugusbuBuGuguBebofrinules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edabibububuBubotin" eType="//BigusFriGugubiNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBeNulaudaboDadabiNulauFrifrigulius" ordered="false" upperBound="-1" eType="//DabibobebugugusaububigusIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFribeBebugusFriGuguBiDadaBenus" abstract="true" eSuperTypes="//DabudaBubiBudabiBinulAunulaugusbetin //AbunulaufriBobelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubiDadaFrifribeboBibegucus" ordered="false" eType="//DabofribogunulAubunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfrinulAudafrigusbiDanulAubuDaLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfribebobeguBeGusauNus" eType="//BigusFriGugubiNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibeBebiGunulauGusbonulius" eSuperTypes="//EfrinulAudafrigusbiDanulAubuDaLus //AbunulaufriBobelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusBiGubudabodadaFrigusFrigusguscio" ordered="false" upperBound="-1" eType="//DabofribogunulAubunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBuBoBebenulaunulAuLus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DufriBubiGusfridafribuBebiNulAudanulius">
    <eLiterals name="BanulaugusbegusnulAugufribobiLius"/>
    <eLiterals name="AbidagusNus"/>
    <eLiterals name="AbuGusbubenulaubebufriDabeNulauFriNus"/>
    <eLiterals name="AuBibobubogufrigugugutor"/>
    <eLiterals name="DubonulauDaGugutus"/>
    <eLiterals name="FaGuNulauBugunulAuTor"/>
    <eLiterals name="ABogusgusgubugustor"/>
    <eLiterals name="DaBoBonulaubedalus"/>
    <eLiterals name="BebuBefriLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibuboBubufrifriguBicio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBoFribibocus" eType="//AlnulaunulauGuBoGuscio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Digunulaubebonules">
    <eLiterals name="Braubefries"/>
    <eLiterals name="Bebegubetus"/>
    <eLiterals name="BrauBeDabudafriboCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DadadagunulaufriBibiBees" instanceTypeName="typeEuGuGusbiBigunulauDabubibegusguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidaBugugustus" eSuperTypes="//EfrinulAudafrigusbiDanulAubuDaLus //AubobibeBobuboBebubudacus //EFribeBebugusFriGuguBiDadaBenus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBeboNulAuDafriboguBeNus" instanceTypeName="typeEbobefridaBeBeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EububeDafriBegusGuDagugutor" abstract="true" eSuperTypes="//BeBiGusGuFriNulAufrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubogusbubobetor" ordered="false" upperBound="-1" eType="//AbunulaufriBobelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudaBugusbugusbobodalius" eSuperTypes="//EububeDafriBegusGuDagugutor //BibeBebiGunulauGusbonulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuGuBunulauFrigucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabeguBibubefrinulauFriguFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiguBeBifrinulaufriboDabubutin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulaugunulaubidabubibeLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babeBigusGusbobetus" eType="//Digunulaubebonules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulauGugusboBobuBuBuBunulAucio" eSuperTypes="//BibuboBubufrifriguBicio"/>
</ecore:EPackage>
