<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="altus" nsURI="http://hub.de/rcore/examples/altus" nsPrefix="oJU">
  <eClassifiers xsi:type="ecore:EClass" name="AlFrinulauFribelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBuFridagusguNulaulius" abstract="true" eSuperTypes="//AlFrinulauFribelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauGuBigusBubenulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edagusAuGusNus" ordered="false" upperBound="-1" eType="//AlFrinulauFribelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudagunulAuBuBebenulAubiguses" abstract="true" eSuperTypes="//DuBuFridagusguNulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baguGuNulAubodaBegusGubibobetor" ordered="false" eType="//AlFrinulauFribelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubofriBoFriGubuguguCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufriBeNulauBugusgugugufriCio" ordered="false" upperBound="-1" eType="//AlFrinulauFribelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBuBigusgufriboDaGusdaLius" eSuperTypes="//BinulauGuBigusBubenulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufribofribugusdaBeFriBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabubeboGuBedabenulaubobegusBotin" ordered="false" upperBound="-1" eType="//AlFrinulauFribelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabufriBigusGuboBibocus" eSuperTypes="//AlFrinulauFribelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusNulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnBubodaBeFribefriguBodanus">
    <eLiterals name="BraugugunulEs"/>
    <eLiterals name="Alaugusdatus"/>
    <eLiterals name="DugusbuFribiNulaubegusBetor"/>
    <eLiterals name="ABoDagugusIus"/>
    <eLiterals name="AnFridaDafribiguguFrigusgusBeBecio"/>
    <eLiterals name="BabeguguBeBigusfribecus"/>
    <eLiterals name="DoGuBudadabiDabebeboBucio"/>
    <eLiterals name="BifrifriBifriCus"/>
    <eLiterals name="FagusGusboBifriFribiGuBoDagulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbobogusAubidaguBenulEs"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauDagusbigusgusBiDanus">
    <eLiterals name="BeBuguBibifribegusgulus"/>
    <eLiterals name="EuNulAuBobegusnus"/>
    <eLiterals name="BafriBobeGusNulaunus"/>
    <eLiterals name="AbonulAubobuguNulAuBeTin"/>
    <eLiterals name="DaGusdanulaugudaTin"/>
    <eLiterals name="DobubeBinulaufrigunulauboGusbonus"/>
    <eLiterals name="BenulAubefrigusnulAutus"/>
    <eLiterals name="AbifrinulAubibibutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bigufributor" eSuperTypes="//DubofriBoFriGubuguguCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBidagufriBoLus" ordered="false" upperBound="-1" eType="//DuBuFridagusguNulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBiFribogugusDanulAucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibebinulaugudabebelus" eType="//AnBubodaBeFribefriguBodanus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibufrifriLius" ordered="false" upperBound="-1" eType="//BabufriBigusGuboBibocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbuDaBinulAububegusnulaufribeGusnus" instanceTypeName="typeAldabuGusius"/>
</ecore:EPackage>
