<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dobotus" nsURI="http://hub.de/rcore/examples/dobotus" nsPrefix="gt">
  <eClassifiers xsi:type="ecore:EClass" name="DoBoguguBeBufriGubidafrigustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubebibiBuGubobonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlDabiFribiBudaBugusgusguBiTor" eSuperTypes="//DoBoguguBeBufriGubidafrigustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enulaulius" abstract="true" eSuperTypes="//DoBoguguBeBufriGubidafrigustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafriGutin" ordered="false" upperBound="-1" eType="//DoBoguguBeBufriGubidafrigustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DagusgufriGusbuGufrigubiGuboes" instanceTypeName="typeDiboBiboboBoDadanulauguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobugusDabeBuTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FabefriDaDaBebuGusdaFriNus">
    <eLiterals name="DoBobibebenulauGusdator"/>
    <eLiterals name="Babubodabebegufrilus"/>
    <eLiterals name="AnGusnulauBogusbubenulIus"/>
    <eLiterals name="BiBugusbiguBugusgusBulus"/>
    <eLiterals name="BafrigubefrigusaunulaudaCus"/>
    <eLiterals name="BibuGusaubenulautus"/>
    <eLiterals name="AlFriDabegusbutus"/>
    <eLiterals name="AnbebenulAufribeBuBulius"/>
    <eLiterals name="BebebifrifridabuguFrigusbefribugusBuguscio"/>
    <eLiterals name="BidaGusbonulAuGuguBuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubogunus" eSuperTypes="//DoBoguguBeBufriGubidafrigustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusgusBubeboBedacio" eSuperTypes="//AubebibiBuGubobonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogusbuBobuBobodagunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agubidanulaulius" eSuperTypes="//Enulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaubiBifriNulauBelus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubugusBinulAuBitin" eType="//DagusgufriGusbuGufrigubiGuboes" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubogusbigusfridaCus" eSuperTypes="//AubebibiBuGubobonus //DogusbuBobuBobodagunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusbuNulAugusDaDaGucio" eSuperTypes="//AlDabiFribiBudaBugusgusguBiTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibobeNulAugubobubogufrinulAugues" eType="//DogusbuBobuBobodagunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabobenulaudaBotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedanulauNulAunulaubinulauTin" ordered="false" eType="//BiBubeboGugunus" eOpposite="//BiBubeboGugunus/euFribonulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbibuNus">
    <eLiterals name="AfriboDaNulAufriEs"/>
    <eLiterals name="Fabifridabegusbelius"/>
    <eLiterals name="Danulaubetus"/>
    <eLiterals name="DaGusbugusauNulauBuCio"/>
    <eLiterals name="BiBubuBiBigusfriBitor"/>
    <eLiterals name="BeBeboGuBigufridaBogusfries"/>
    <eLiterals name="EFridadaBuBubeFriBuguFrifribeguTus"/>
    <eLiterals name="EgusBuNulAuBedagulius"/>
    <eLiterals name="AnbogusbubobiGusgusbeTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EububiBiNulAudaBefrigusgubetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aguBuDabebubonus" eType="//DagusgufriGusbuGufrigubiGuboes" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aunulauBocus" eType="//DagusgufriGusbuGufrigubiGuboes" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BraugugusGugusbuGufriDaNus">
    <eLiterals name="ABonulauFriDafrifritin"/>
    <eLiterals name="FabiBeBebobegunus"/>
    <eLiterals name="DobunulAuBunulaufribunulauboNulautus"/>
    <eLiterals name="AuNulaudabegusbebebobobiBoBenus"/>
    <eLiterals name="EubeboBigusfriBuboguscio"/>
    <eLiterals name="EugusBuGunulaubodanulauDabelus"/>
    <eLiterals name="AngubinulaudabuBoGusBiGusdafriCus"/>
    <eLiterals name="AGusGuFriDabuBububegufriBunulius"/>
    <eLiterals name="DaFrigusbiBoFriFrinulAubelus"/>
    <eLiterals name="BrAuGufriBubugusBobeboDalius"/>
    <eLiterals name="AnbiGusbogusdaTin"/>
    <eLiterals name="DobuFriNulaufriBonulAugusbinulauguboBonus"/>
    <eLiterals name="DoGudaGusbeCio"/>
    <eLiterals name="AnaubiguGuDabiBoBoBolius"/>
    <eLiterals name="FabigubifriBeFridaboboBegusbibies"/>
    <eLiterals name="DaDaFrigusdagusbiBibudafrinus"/>
    <eLiterals name="AguNulauGunulAubebilius"/>
    <eLiterals name="BabeFrigusbedaBeNulaugusBuCus"/>
    <eLiterals name="BiGusbegugusdabeFribefrilius"/>
    <eLiterals name="BraugubobubebiGuBinulAuTin"/>
    <eLiterals name="EubogusaunulaugusBiGugusnulAuCio"/>
    <eLiterals name="BibebinulAubuNulaubeDadabies"/>
    <eLiterals name="BrAuBiBoNulaufriboboFribobobelus"/>
    <eLiterals name="BrAuGuBidafrigudaDaBilius"/>
    <eLiterals name="DigugubiNulauguBuLus"/>
    <eLiterals name="DabiGusauDaboDabubobeBulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnFribiboFriNulius" instanceTypeName="typeBrauNulauBulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoGusbebofrifribobeFriEs" instanceTypeName="typeAlnulaububudaGusBubeGusaubitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofriFrigusdagunulAugudabelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibiNulAubufrifrinulAuDafritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daDabuGusbedabodagusgusbebobolius" ordered="false" eType="//BrAubogunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdaBobuguBoFrifribebeDaEs" abstract="true" eSuperTypes="//AlDabiFribiBudaBugusgusguBiTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubuBunulAugusbiboGuCio" eSuperTypes="//BraubogusbigusfridaCus //DofriFrigusdagunulAugudabelus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnguGubonulauFribeguGusbigusGuCio" instanceTypeName="typeEfribuFriguBebidadagusbeBefribotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabegudagusDagugusBeBofriLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubobebebibobuboBubuGubudagubiBuguslus" ordered="false" upperBound="-1" eType="//AubebibiBuGubobonus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBiBotin" eType="//FabefriDaDaBebuGusdaFriNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlBuBoBidaBinulAuGugusGunus" instanceTypeName="typeDuDabobinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaGuGubebiBuBoGusboLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusauGubigubebitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudabiBibonulauguguLius" eType="//AlNulaubiBifriNulauBelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBibegubogubenulauNulAutor" eSuperTypes="//DofriFrigusdagunulAugudabelus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begusnulAuBogusgusboBofries" eType="//BraugugusGugusbuGufriDaNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Bibenulaubibegusbegusbitor" instanceTypeName="typeBanulaugubeBigustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGuBiBobigusIus" eSuperTypes="//FabobenulaudaBotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babugusGudabifridaFribugusBiCio" ordered="false" eType="//AngusauGubigubebitus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baGubuBoBebuBecus" eType="//AnFribiboFriNulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBudaNulauBudaTin" eSuperTypes="//AuGuBiBobigusIus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FadabofribebinulaubeGulus">
    <eLiterals name="AnFriNulaubeDaDaGubifrigusbolus"/>
    <eLiterals name="BrAugusGuNulius"/>
    <eLiterals name="AuBibubuBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAuGuNulAuBuBebebies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigunulAudafrigusdaBiCio" eType="//Bibenulaubibegusbegusbitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBegusgunulAuFriFrifritin" eSuperTypes="//BeBudaNulauBudaTin //AdaBobuguBoFrifribebeDaEs //AubebibiBuGubobonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndabebuFribobibiNulaububeDadagunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBubeboGugunus" eSuperTypes="//EBibegubogubenulauNulAutor //DaDaGuGubebiBuBoGusboLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euFribonulautus" ordered="false" upperBound="-1" eType="//FabobenulaudaBotus" eOpposite="//FabobenulaudaBotus/bedanulauNulAunulaubinulauTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebunulaugusBigubigubebodaDaLus" ordered="false" eType="//BrAubogunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGusguBodaGufrigubees"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidaDagusnulautin" eSuperTypes="//AngusauGubigubebitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braufridalius" eType="//BraubogusbigusfridaCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusBolus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubiFriFriNulaufrinulauguEs" ordered="false" upperBound="-1" eType="//FabegudagusDagugusBeBofriLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbeBoguBoBibebobifribeDaes" eSuperTypes="//DidaDagusnulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulaunulaubodafriFriBiBeTor" eSuperTypes="//AlNulaubiBifriNulauBelus //BraubogusbigusfridaCus //EububiBiNulAudaBefrigusgubetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobuBugusgusfriFrinulaugusBiGuNules" ordered="false" upperBound="-1" eType="//AngusgusBubeboBedacio"/>
  </eClassifiers>
</ecore:EPackage>
