<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="badabilius" nsURI="http://hub.de/rcore/examples/badabilius" nsPrefix="ql">
  <eClassifiers xsi:type="ecore:EClass" name="DuFribenulauFrifrinulaubeGusnules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriDabifritus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFribebigubugusbodator"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusnulaufriBebinulaubinus" abstract="true" eSuperTypes="//DuFribenulauFrifrinulaubeGusnules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiguGusbiGufribogusbocus" eSuperTypes="//FagusnulaufriBebinulaubinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfribubuGubibuboBecio" eType="//FagusnulaufriBebinulaubinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiguBiBegunulaunulaubugunus" eSuperTypes="//BiguGusbiGufribogusbocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begububoBiBefricus" ordered="false" eType="//FagusnulaufriBebinulaubinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFrinulaudaguGulus" instanceTypeName="typeDudaBunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnauBebonulAugucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alAubibiFrinulaufriboBufridalius" eType="//EFrinulaudaguGulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBubefrinulauDadaBoFrinulaulius" ordered="false" eType="//DigusbiDabebebicio" eOpposite="//DigusbiDabebebicio/doGubegusbiLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidanulauNulAuDagusfrifrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusguGusgusbugusfriLius" eType="//AnauBebonulAugucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAubeBobedagunulius" eSuperTypes="//DiguBiBegunulaunulaubugunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaugunulauBiBobebiNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anauboBibuGusfribibecus" ordered="false" upperBound="-1" eType="//DinulaudaBodabobiGubegusBugucus" eOpposite="//DinulaudaBodabobiGubegusBugucus/biguBudaBiBibonulauBubicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusbiDabebebicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGubegusbiLius" ordered="false" eType="//AnauBebonulAugucio" eOpposite="//AnauBebonulAugucio/duBubefrinulauDadaBoFrinulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DugubobibefriguDaTus" instanceTypeName="typeAnBiGububobuBonulAubeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDabogusgusbeBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigudadagubibuLius" eType="//DidanulauNulAuDagusfrifrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BebinulauboNus">
    <eLiterals name="AlguBifrinulauGubobibofributor"/>
    <eLiterals name="AuboboFrigubigusboNulaubeLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DinulaudagufriCus">
    <eLiterals name="AnguDabilus"/>
    <eLiterals name="AlbogusfribinulauDaBigusbebecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusboNulAubuTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaudaBodabobiGubegusBugucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguBudaBiBibonulauBubicio" ordered="false" upperBound="-1" eType="//FanulaugunulauBiBobebiNus" eOpposite="//FanulaugunulauBiBobebiNus/anauboBibuGusfribibecus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulauguGuGusBogusautus" ordered="false" upperBound="-1" eType="//FagusnulaufriBebinulaubinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuguBofriBudanules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaugusBoguguboLius" eSuperTypes="//DiguBiBegunulaunulaubugunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabefrinulAubenulauboDabobiDaCus" ordered="false" eType="//BiguGusbiGufribogusbocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBunulAudabogusnulAudanulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fagudabofrifrinulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBuBeDagusfriBunulius" upperBound="-1" eType="//EFrinulaudaguGulus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
