<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bagusfribogunules" nsURI="http://hub.de/rcore/examples/bagusfribogunules" nsPrefix="Fq">
  <eClassifiers xsi:type="ecore:EDataType" name="BadagubebiBiBofrifriFrinulaudaFrilius" instanceTypeName="typeDoNulaugusGusBuguEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauDaNulauBebubobucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafriBiFridagunulaubebiBenus" eSuperTypes="//BrauDaNulauBebubobucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBegusbubegusfrinulauBiTin" ordered="false" upperBound="-1" eType="//BrauDaNulauBebubobucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albonules" ordered="false" upperBound="-1" eType="//EugusgugusFrifrifribudaBiGusbilius" eOpposite="//EugusgugusFrifrifribudaBiGusbilius/babiBinulaubonulaunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EububufriguBiGuBubutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBugusbudabocio" ordered="false" upperBound="-1" eType="//BafriBiFridagunulaubebiBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DoBiGusbobuDanulAuLius">
    <eLiterals name="DoBogustor"/>
    <eLiterals name="DoBegusbububugusguboDaNulauFrinus"/>
    <eLiterals name="BaboGusbobedagusaulius"/>
    <eLiterals name="AndagufriguGusbibeBoGusnulaubues"/>
    <eLiterals name="AnAubiNulaunulauGutus"/>
    <eLiterals name="DoGuguBeFriBebobuFridabebecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidaFriboboBifriBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebubebeBoboBelius" ordered="false" upperBound="-1" eType="//BeGusaubuFribelus" eOpposite="//BeGusaubuFribelus/aGusDaBoBunulaufrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauGusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbonulaudaboCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabudabuDafrifridafries" ordered="false" upperBound="-1" eType="//BidaFriboboBifriBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Digusfrigusbugunules" abstract="true" eSuperTypes="//BidaFriboboBifriBilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusgugusFrifrifribudaBiGusbilius" eSuperTypes="//BafriBiFridagunulaubebiBenus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubuFriBoes" eType="//DoBiGusbobuDanulAuLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFrinulaunulaufriGusbutor" ordered="false" upperBound="-1" eType="//BidaFriboboBifriBilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiBinulaubonulaunulius" ordered="false" upperBound="-1" eType="//BafriBiFridagunulaubebiBenus" eOpposite="//BafriBiFridagunulaubebiBenus/albonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAuNulauBoGuBunus" instanceTypeName="typeFaBoBoboboGusgusgusAugubobies"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaNulauBubigusnulAuBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraufriboFrilius" eSuperTypes="//BanulauGusIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBeGuFribebiboboGubodalius" upperBound="-1" eType="//BrauDaNulauBebubobucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anbedabibogugusbunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbugusGubeguguFriboes" eType="//BadagubebiBiBofrifriFrinulaudaFrilius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBeFribiguguFrinulAuGubebiLius" eType="//BanulauGusIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulaunulAuGusauBufrifrigusFriBeBebuCio" ordered="false" eType="//AnbonulaudaboCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauBeDabeBefrinus">
    <eLiterals name="AbuGunulauGuguslus"/>
    <eLiterals name="EuGudaNulaubigusbigusfriNulAuTin"/>
    <eLiterals name="Abubigusnulaubonulautus"/>
    <eLiterals name="BibiFribubiboBoguses"/>
    <eLiterals name="Abinulaubobogusnules"/>
    <eLiterals name="AngusgusGufribegubinulautor"/>
    <eLiterals name="AnNulAuFribiBidanulaubugusbogutor"/>
    <eLiterals name="BaDaboFribuNulAuboFrinus"/>
    <eLiterals name="AnbofrigusbugufrifribuGusgusLus"/>
    <eLiterals name="BrAubegusAuguguFrinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbubidaboboGuguguBigusdatin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuguBuGusfrifrinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efribigufribobinulautus" ordered="false" upperBound="-1" eType="//EububufriguBiGuBubutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusgubibuBugugusdaBobenulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBeBegusBuBoBuDaguCus" upperBound="-1" eType="//BrAuNulauBoGuBunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="befridagusnulauguboguslius" ordered="false" eType="//EububufriguBiGuBubutor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBobidafribogusGubocio" eType="//BadagubebiBiBofrifriFrinulaudaFrilius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abibinulaufriBubibubeboBefritus" eType="//BrauBeDabeBefrinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebubobobebebetus" eSuperTypes="//EububufriguBiGuBubutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraudafrinulAubobigubeNulius" instanceTypeName="typeEugudalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubenulAuGubetin" eSuperTypes="//EugusgugusFrifrifribudaBiGusbilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGunulAudaGunulAuGufribelus" eSuperTypes="//Ebubobobebebetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anboBobeDaBeTin" ordered="false" eType="//DogusgubibuBugugusdaBobenulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBugufribiguNulAucus" ordered="false" eType="//Ebubobobebebetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fabunulaugusaubegutus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauFribuBoGubiBegutor" eType="//BrauBeDabeBefrinus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="banulaunulaubitin" eType="//BrauBeDabeBefrinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusaubuFribelus" eSuperTypes="//EugusgugusFrifrifribudaBiGusbilius //DaDaNulauBubigusnulAuBinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aGusDaBoBunulaufrilius" ordered="false" eType="//BidaFriboboBifriBilus" eOpposite="//BidaFriboboBifriBilus/ebubebeBoboBelius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuNulaudaGuBenulaudabodagusgutus" ordered="false" eType="//Fabunulaugusaubegutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuboGubeTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faFriBiBebegunulIus" upperBound="-1" eType="//AnGunulAudaGunulAuGufribelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubeNulAuBiEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefrigudagusguGuscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anus" eSuperTypes="//DaDaNulauBubigusnulAuBinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguFriboBifribodacus" ordered="false" eType="//DubeNulAuBiEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibuGufriGusius" eType="//DoBiGusbobuDanulAuLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbiboboNulAubeBobeGusdaGuslus">
    <eLiterals name="EufriGusGusdanulaubiboEs"/>
    <eLiterals name="DibiBugufriguBolius"/>
    <eLiterals name="AngusnulauguGusbenulauGustin"/>
    <eLiterals name="BaBuBigusFriDatin"/>
    <eLiterals name="DogusbonulaufrigusfriGusbobiBuboTus"/>
    <eLiterals name="EuBiNulAudaBebuBebutor"/>
    <eLiterals name="DudaBuGudaGufrigusbuGutor"/>
    <eLiterals name="Dobobefrigusnulautin"/>
    <eLiterals name="BaBiBugunulAuBugugugusdabucus"/>
    <eLiterals name="DobobobiBuBiBoBeBoFribibitor"/>
    <eLiterals name="AnfridabonulauBebegubobelus"/>
    <eLiterals name="DaBinulauBenulaufriboes"/>
    <eLiterals name="DuboNulAubugusdabues"/>
    <eLiterals name="DobeBigusgubudabogusdabotin"/>
    <eLiterals name="AgusAugububefribugusfridabodadaDaFritor"/>
    <eLiterals name="FafriFriGusfribeNulAubinules"/>
    <eLiterals name="BeNulaubedanulaugusbetor"/>
    <eLiterals name="DiBibubenulaugusguNulaubuBebeGusBogutin"/>
    <eLiterals name="BraugusFriGusfribiGusGusgububitus"/>
    <eLiterals name="BrAuBeBobegufriEs"/>
    <eLiterals name="FafriBogusAubegusDaDaGustus"/>
    <eLiterals name="Braudabonulaulus"/>
    <eLiterals name="AubeNulAubutor"/>
    <eLiterals name="FaGusdaGusfribuNulauBuboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dagubufrifrinulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibonulaufrigugusTor" abstract="true" eSuperTypes="//BrauDaNulauBebubobucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaubebenulaudaTus" eSuperTypes="//Dagubufrifrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Digugusfrigusbonulaunus" eSuperTypes="//Ebubobobebebetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duguboGusgusbobefriboguEs" ordered="false" eType="//BefrigudagusguGuscio"/>
  </eClassifiers>
</ecore:EPackage>
