<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="difricus" nsURI="http://hub.de/rcore/examples/difricus" nsPrefix="LiC">
  <eClassifiers xsi:type="ecore:EClass" name="BigusbunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EboDaBidafrifriBicio" eSuperTypes="//BigusbunulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EbenulAubibubinulAucio" instanceTypeName="typeBraubodagubuBeFrigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraufribiDabuBobitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusGusgusGusBeGucus" eType="//EbenulAubibubinulAucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabubuBeNules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibedagusaubebeboTin" eType="//EbenulAubibubinulAucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albodaBubitor" ordered="false" eType="//BraufribiDabuBobitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DobuBeGugusGusFrinulauBofrigutus">
    <eLiterals name="BebuNulauGusdaBibogubiCus"/>
    <eLiterals name="DabebogusbuDadaNulEs"/>
    <eLiterals name="DagusAugusFriTin"/>
    <eLiterals name="EdadaboguBobibuDaDabigusGulius"/>
    <eLiterals name="AudabenulAuguGugusgustus"/>
    <eLiterals name="BibobobugusBufrifribubelus"/>
    <eLiterals name="BefriBebeBiBoguslus"/>
    <eLiterals name="BeboBedagubuTus"/>
    <eLiterals name="AlfriTus"/>
    <eLiterals name="DiBodaFricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufridagusaugusTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobeFriBubiEs" instanceTypeName="typeBraubibibufriBobuBoBebidaBitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABiguBubeGusbufriBuGusGusnus" eSuperTypes="//EboDaBidafrifriBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebogugusAufriBugusbees"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuboGuFriboDator" eSuperTypes="//ABiguBubeGusbufriBuGusGusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eutor" ordered="false" upperBound="-1" eType="//BebogugusAufriBugusbees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DanulaufridaDaBoNus" instanceTypeName="typeAlbubeBigusDaBebebiDabeBies"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobeGuGunulAubigusBees" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagubeCio" eType="//BraufribiDabuBobitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBebiDabiboGudafriBoBoFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulaubibenulaufriBebegustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfribebuboNulauBiNulauboguCio" eSuperTypes="//BigusbunulEs //EuboGuFriboDator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agusbinus" eType="//EbenulAubibubinulAucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabegusbogubibiBubeguslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibuFribubuBetor" ordered="false" upperBound="-1" eType="//AuBebiDabiboGudafriBoBoFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibiBubebebibifrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGufrigubobeDabifrifriBiBicus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabibuBunulaunulaubeFriNulauguscus" instanceTypeName="typeDuBiguGubiFrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufribuDabeNulAuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBubegusgusBidagusCus" eSuperTypes="//AuGufrigubobeDabifrifriBiBicus //DobeGuGunulAubigusBees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBubiFriBufrifribeBoBoTus" ordered="false" eType="//EboDaBidafrifriBicio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGusbobuboguses" ordered="false" upperBound="-1" eType="//AfribebuboNulauBiNulauboguCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBifriBibebufritin" ordered="false" eType="//BeDaFriBoDaguDabubiguGufriNulIus" eOpposite="//BeDaFriBoDaguDabubiguGufriNulIus/baFrifrigubebonulAubotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Aufrigugusnulaubobutus" instanceTypeName="typeBraubibuGusbiBibobinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBibubeBugusgudaboDanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeDaFriBoDaguDabubiguGufriNulIus" eSuperTypes="//EboDaBidafrifriBicio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugugusnulAugusdabobotor" eType="//EbenulAubibubinulAucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFrifrigubebonulAubotus" ordered="false" eType="//DiBubegusgusBidagusCus" eOpposite="//DiBubegusgusBidagusCus/beBifriBibebufritin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EufriDacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebegusAubogusnulauBecio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaGuBigusBetin" eSuperTypes="//BiNulaubibenulaufriBebegustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGuNulauBobibuGulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbubeBoNulAuNulaufrigusbugusGuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebobigusnulaubigubuFribonulAudanulaunulIus" upperBound="-1" eType="//EufriDacus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugugububugustus" ordered="false" eType="//ABiguBubeGusbufriBuGusGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulauboNulaubegusBiBocus" abstract="true" eSuperTypes="//AuBebiDabiboGudafriBoBoFritor //AbubeBoNulAuNulaufrigusbugusGuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiguDaGubufriBubiNulEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulaudabobenulauguBeFrigufriguCus" ordered="false" eType="//ABiguBubeGusbufriBuGusGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusguDabubogugubocus" eSuperTypes="//BigusbunulEs //EufribuDabeNulAuLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aFriboCus" eType="//BabibuBunulaunulaubeFriNulauguscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusgusfriDagufricio" instanceTypeName="typeAuNulaubiBeFriFrigusbibenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusGusbudabibeDaGues" eSuperTypes="//ABiguBubeGusbufriBuGusGusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDafridagusbibuBetin" ordered="false" upperBound="-1" eType="//BiNulaubibenulaufriBebegustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaudagufrigubigusfriButin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugubeFribobobeLius" instanceTypeName="typeAnFriBigunulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfrinulaubeBinulaubefrigubiLus" abstract="true" eSuperTypes="//EufriDacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albogusnulAubudabeNulautor" eType="//Aufrigugusnulaubobutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBufriBogusbedaLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daNulAuGustin" ordered="false" eType="//AufridagusaugusTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulauBodadabobibebibuFriBufribonus" eSuperTypes="//AbubeBoNulAuNulaufrigusbugusGuLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbobufriboGubebinus" eType="//BabibuBunulaunulaubeFriNulauguscus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
