<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="audabofribucio" nsURI="http://hub.de/rcore/examples/audabofribucio" nsPrefix="xdEL">
  <eClassifiers xsi:type="ecore:EClass" name="DafrigusnulAugusBoLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dabidafrigusbetin" eSuperTypes="//DafrigusnulAugusBoLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFribeBofribogusguBiBelius" eType="//DafrigusnulAugusBoLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibugubibebubugufrinulautor" ordered="false" upperBound="-1" eType="//DobuGubigubobelius" eOpposite="//DobuGubigubobelius/biBuDaFribiboTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anfribubidalus" eSuperTypes="//DafrigusnulAugusBoLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofriNulaubebiDabeguGusauGubuGusBocus" ordered="false" upperBound="-1" eType="//DafrigusnulAugusBoLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulAubefrigusnulAudabotus" eSuperTypes="//DafrigusnulAugusBoLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaNulIus" eType="//DafrigusnulAugusBoLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBeGusbogugusguGusnules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBubodagusgusBoFriEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobuGubigubobelius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBuDaFribiboTor" upperBound="-1" eType="//Dabidafrigusbetin" eOpposite="//Dabidafrigusbetin/bibugubibebubugufrinulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANulaudabibogusBeEs"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Efribifribubebugusbutus">
    <eLiterals name="BedaDabues"/>
    <eLiterals name="BeBubiBinulautin"/>
    <eLiterals name="DonulauBibibidagusbunus"/>
    <eLiterals name="AdagubobibiBofriDaGusBegues"/>
    <eLiterals name="EuFribibigusdabeGusNulAuguguFridabebies"/>
    <eLiterals name="DifridaBiLus"/>
    <eLiterals name="AunulAugusbicus"/>
    <eLiterals name="BagufribibegusAuNulAuBoCus"/>
    <eLiterals name="DaBoNulauFribubofriGuGuBiBeFrilius"/>
    <eLiterals name="DoboboBuBibobuBeFrigusBibitus"/>
    <eLiterals name="BebiBedaGusBecus"/>
    <eLiterals name="FanulauBefriBefriFriGusgucio"/>
    <eLiterals name="FabiFrigusBuTor"/>
    <eLiterals name="BafridagusBiBegusbodabinus"/>
    <eLiterals name="DaguGusGuboDanulAubocus"/>
    <eLiterals name="AlnulaunulaufridagusbebebuBufrilius"/>
    <eLiterals name="AlbibebeGusGusbutin"/>
    <eLiterals name="BagudadagudabibugusaubuDaBofribeLus"/>
    <eLiterals name="EufribiFribonulaucus"/>
    <eLiterals name="FafriDabubobugusbegubuGufrifriBiNulauNules"/>
    <eLiterals name="EgugunulAuBuBeBubelius"/>
    <eLiterals name="DaBeGusnulAuguboboDacio"/>
    <eLiterals name="DiBuBuboboEs"/>
    <eLiterals name="DubobonulaufrigunulauDatin"/>
  </eClassifiers>
</ecore:EPackage>
