<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ebubugusboes" nsURI="http://hub.de/rcore/examples/ebubugusboes" nsPrefix="SSnxQ">
  <eClassifiers xsi:type="ecore:EClass" name="DigufriGuDaBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFrifriGusfrinulauBuBoDaBugues" eSuperTypes="//DigufriGuDaBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabugubiboNulaubiBilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusbefrigusgustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabebeBoBobogubonulaugusCus" ordered="false" upperBound="-1" eType="//BabugubiboNulaubiBilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusGudaFriNulaubedadaCus" ordered="false" eType="//BabugubiboNulaubiBilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusbigusDabifrinulauBudaFrinulAudaboDagutor" ordered="false" upperBound="-1" eType="//BabugubiboNulaubiBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DaNulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BafribobubeFridabeFridagusgutin" instanceTypeName="typeAlGusbibiGusbeBogusBebogusbeDatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiDaGuBeGugusBiGusnulEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFrifrinulaunulauBeDaBitus" abstract="true" eSuperTypes="//DigufriGuDaBitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befriFribufridabees" upperBound="-1" eType="//BabugubiboNulaubiBilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibegusgusFriBegusbeBifriLius" ordered="false" upperBound="-1" eType="//AubiDaGuBeGugusBiGusnulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibobonulAuGunulauguslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulauBedaguBoDaNulauNulius" ordered="false" upperBound="-1" eType="//DigufriGuDaBitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eububugusgusgugusauBefricio" ordered="false" upperBound="-1" eType="//BaFrifriGusfrinulauBuBoDaBugues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBoBubiGufritor" abstract="true" eSuperTypes="//DiGusbefrigusgustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugubiTin"/>
</ecore:EPackage>
