<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eubodabutin" nsURI="http://hub.de/rcore/examples/eubodabutin" nsPrefix="nVtd">
  <eClassifiers xsi:type="ecore:EClass" name="AububibiBogusgunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigubugusbidaBifriBeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubibeFriGusbegusdagusaunules" abstract="true" eSuperTypes="//AububibiBogusgunulIus //DigubugusbidaBifriBeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbugusnulauDabububibiNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusbofrifriNulAugusdaGuGusbobiboes" ordered="false" eType="//DigubugusbidaBifriBeNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAuFribuNulaudaguFrinulautin" abstract="true" eSuperTypes="//DigubugusbidaBifriBeNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agugububebilus" ordered="false" eType="//EBoNulaugusFrinulauBebinus" eOpposite="//EBoNulaugusFrinulauBebinus/angusnulAubedadaBeDaNulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusbeboBobebenulaugubeNus" abstract="true" eSuperTypes="//DigubugusbidaBifriBeNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didabufridabuTus" ordered="false" upperBound="-1" eType="//BraubibeFriGusbegusdagusaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubuGuGusnulaubuguBoGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusaububuCio" eSuperTypes="//AunulAuFribuNulaudaguFrinulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braugubugugustin" eSuperTypes="//DigubugusbidaBifriBeNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diguguBeBeBofrinulaufricio" eType="//AugusbeboBobebenulaugubeNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBoNulaugusFrinulauBebinus" eSuperTypes="//AububibiBogusgunulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusnulAubedadaBeDaNulaulius" ordered="false" eType="//AunulAuFribuNulaudaguFrinulautin" eOpposite="//AunulAuFribuNulaudaguFrinulautin/agugububebilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Brius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabiboGugugubegusgulus" eSuperTypes="//EbugusnulauDabububibiNules //FagusaububuCio //AugusbeboBobebenulaugubeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufribenulAutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulaubifribufribeDaCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiGuGubuguguscio" instanceTypeName="typeBaGubegudabenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidagusBegubeboDagutor" eSuperTypes="//FagusaububuCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaBeNulAuNulAugusbiBibuEs">
    <eLiterals name="DoDaBobofribeTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFrinulaubebobobugusgubeEs" eSuperTypes="//BeNulaubifribufribeDaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFriBogusBidabedabebonulius" ordered="false" eType="//BagusNulAufriboguguGunus" eOpposite="//BagusNulAufriboguguGunus/annulaubenules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFrigusgugusBuFriGulus" eSuperTypes="//Braugubugugustin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eguBunulAugubodagusbutin" eType="//BaBeNulAuNulAugusbiBibuEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdabebiFrinulaulus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBeBegusbigusaubuTor" eType="//BaBeNulAuNulAugusbiBibuEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaFrifrinulaubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubibidabubidaTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubebebiGusBeCus" eType="//BaBeNulAuNulAugusbiBibuEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogubibobidaBegusBebefrinules" upperBound="-1" eType="//BeFrifribuGuBuBubububulus" eOpposite="//BeFrifribuGuBuBubububulus/biGuBunulAuDagudadatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibibebeBiFriBoBuNulAugusguNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBoDagusguBogusbugubuLus" ordered="false" upperBound="-1" eType="//EubibidabubidaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibiNulAuBenulAugusgusbuDanulius" abstract="true" eSuperTypes="//EdabebiFrinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusauguBobifrigusFriBuNulaubocio" eSuperTypes="//EbugusnulauDabububibiNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebobofriBibufriTus" abstract="true" eSuperTypes="//DigubugusbidaBifriBeNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugufriBobiGubinus" instanceTypeName="typeBenulAufrinulaufriCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBebiboGusbebubucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibuBuNulAudaGusbitus" eSuperTypes="//EubibidabubidaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubeDagudabuDaboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdaBefribunulaubebonulEs" eSuperTypes="//EubibidabubidaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusBegusbogusgusbiBefriguCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusfriGusbibibidanulAuTor" ordered="false" eType="//Brius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlBegusGusBugusDabefriDaLius" instanceTypeName="typeEguBidabebiBiBugusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaufrifriBifrinulaubobeEs" eSuperTypes="//BrAubeDagudabuDaboCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubeboNulaubedaNulAutin" ordered="false" upperBound="-1" eType="//BraubibeFriGusbegusdagusaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlaufrinulaudabeBibodadacio" eSuperTypes="//BabiboGugugubegusgulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdanulaufrigusAuguGunulAutin" eSuperTypes="//EBoNulaugusFrinulauBebinus //EdabebiFrinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusBoDagusfrinulauNus" eSuperTypes="//BebobofriBibufriTus //BaGusBegusbogusgusbiBefriguCio //Brius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daguBeNulauguboGusbuguBefrinus" ordered="false" eType="//ADabinulauBiBunulAuguboNus" eOpposite="//ADabinulauBiBunulAuguboNus/enulAuBefriguGusNulaugusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusbiGugufriBobubenulAubeNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeboGubicus" eSuperTypes="//BegusBoDagusfrinulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodagusgubuDanulauBogues" eSuperTypes="//BibuBuNulAudaGusbitus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babofridaBeBubenulAubiDalius" upperBound="-1" eType="//BaBeNulAuNulAugusbiBibuEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fanulaububobigugunules" eSuperTypes="//DanulaufrifriBifrinulaubobeEs"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EubebedabinulAugusbibotus">
    <eLiterals name="BifridagusnulauguBiBogusguBebies"/>
    <eLiterals name="DobibugusAugufrifribogubecio"/>
    <eLiterals name="EugudaboBebibidafrilus"/>
    <eLiterals name="BegusbiFribiTor"/>
    <eLiterals name="EnulaubenulaufribeCio"/>
    <eLiterals name="AlFriboboNulautin"/>
    <eLiterals name="DuGusDabuBedabobobogusbiLus"/>
    <eLiterals name="BiFribigunus"/>
    <eLiterals name="AuGuNulaugufrinulAuboGugubeNulauCio"/>
    <eLiterals name="BrAubuBogusboBibebiBudaBicio"/>
    <eLiterals name="DuBuGufrigugugusnulAuFrinus"/>
    <eLiterals name="AunulAububufrigusbilus"/>
    <eLiterals name="EubefriguBiBuGugugustor"/>
    <eLiterals name="DuFriGusbebubeguguslius"/>
    <eLiterals name="BabubuNulAuBugusdabiguFribidafriLus"/>
    <eLiterals name="DuFriNulaunulauboNulaubefriBonulEs"/>
    <eLiterals name="AnnulauBegubofrilius"/>
    <eLiterals name="FafribeCio"/>
    <eLiterals name="EgugusbudanulaugusFriBuBoCio"/>
    <eLiterals name="EbubeBobubebunulIus"/>
    <eLiterals name="BefriDagusaubebigufribeLus"/>
    <eLiterals name="DibobuBudacus"/>
    <eLiterals name="BebonulaubedabuBogusdabubitor"/>
    <eLiterals name="AnauNulAuguBibelus"/>
    <eLiterals name="DubeGusbifrigunus"/>
    <eLiterals name="EuBiboFriguBobegusgubelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusgusGufriBibofriBibuFribebiFriCio" abstract="true" eSuperTypes="//BrAubeDagudabuDaboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfridabiBufribenulaunulauDabutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBonulaubobeBigusfribudanus" eSuperTypes="//BeNulaubifribufribeDaCio //AlGusauguBobifrigusFriBuNulaubocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euGusBoGufriBees" eType="//DugufriBobiGubinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dotor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlgusGuBifribucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugusBedadadabiLus" instanceTypeName="typeAfridanulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBibegunulaufriBues" abstract="true" eSuperTypes="//DanulaufrifriBifrinulaubobeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulauFrilus" eSuperTypes="//Brius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aldagubebiBibubicus" eType="//EubebedabinulAugusbibotus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusfriBiBegusBegusaugusbonus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubiEs" eType="//AlBegusGusBugusDabefriDaLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Facio" instanceTypeName="typeEGuNulAuBudanulaugubebeBubiTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBubeBubebudaBidadaBeGutin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulaubibegugusgusauguLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algububefribeBeFriTin" upperBound="-1" eType="//AlgusGuBifribucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuBubenulaubeGubebegusTus" eSuperTypes="//EuNulaubibegugusgusauguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eu"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBegusbububofribufrilius" abstract="true" eSuperTypes="//AuGusfriBiBegusBegusaugusbonus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBiGuslius" upperBound="-1" eType="//DugufriBobiGubinus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabebofribinulauBifribufridafriBiGuFrifriTin" ordered="false" eType="//BegusbebofrigusdagusDabinulaucio" eOpposite="//BegusbebofrigusdagusDabinulaucio/afribubufribufribebebeguNulAuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubenulAuBoBibocio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BibeGubububuNulaubebebeBubibugubidator" instanceTypeName="typeDinulauBegubuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAuBoNulAubibecio" eSuperTypes="//AlBibegunulaufriBues //EubenulAuBoBibocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begubuguTin" upperBound="-1" eType="//DugufriBobiGubinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dudacio" abstract="true" eSuperTypes="//BebobofriBibufriTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dofriDaes" eType="//EubebedabinulAugusbibotus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDagugubobegusBinulaubuguboNus" eType="//AuBegusbububofribufrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauBegusBubububububuGustus" instanceTypeName="typeAlbegubuNulaunulauTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubegusbogudaDagubeNulautin" instanceTypeName="typeAuNulaufriGusfrigusbenulauBubiBocio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlGunulaubuBubibinus" instanceTypeName="typeAnfrifribunulaufrifriNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebibibedaNulAuGuBicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeboNulaudabobeNulaucus" eSuperTypes="//BaFrifrinulaubitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBuNulAububiBefrifriGusDaboBetor" ordered="false" upperBound="-1" eType="//EbugusDabinulius" eOpposite="//EbugusDabinulius/abebuBigubobutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusGusDaguBibigustor" eSuperTypes="//AuGusfriBiBegusBegusaugusbonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabobeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADabinulauBiBunulAuguboNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulAuBefriguGusNulaugusnus" ordered="false" upperBound="-1" eType="//BegusBoDagusfrinulauNus" eOpposite="//BegusBoDagusfrinulauNus/daguBeNulauguboGusbuguBefrinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autus" ordered="false" eType="//AlBibegunulaufriBues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabigugubibudagugusFries" instanceTypeName="typeDobuFrigubogubedabiLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibiBugubigusNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlauBofridaboguscio" instanceTypeName="typeAlbeBububiGusFrigusbefriBoes"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FaDabodabebifrifrigusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndaLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DagunulAubudaBoboNulauBidaDaCus" instanceTypeName="typeAuGusgusbigusGusBefribeGusFrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulauBuGuTin" eSuperTypes="//FagusaububuCio //DidagusBegubeboDagutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbebogusbudaGufriguscio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baNulAuGulius" eType="//DagunulAubudaBoboNulauBidaDaCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusnulAugugusbibucus" eSuperTypes="//FagusaububuCio //EubenulAuBoBibocio //AuBegusbububofribufrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusbeGudaBubefrigudaBoGugusbubenulius" ordered="false" upperBound="-1" eType="//AububibiBogusgunulIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusbedaguNulAuGusNulauCio" ordered="false" upperBound="-1" eType="//AuBonulaubobeBigusfribudanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulaunulaugubiboNulaucio" eSuperTypes="//BeNulaubifribufribeDaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abefriNulaudagusaulus" ordered="false" upperBound="-1" eType="//Dotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBoBeguDaFrigubufribiGusgusGusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabofriBugusAutor" eSuperTypes="//Eu"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BebonulAunulaudaboLius">
    <eLiterals name="AnulauFribedaguDanus"/>
    <eLiterals name="DoboguBoLus"/>
    <eLiterals name="BeGusnulauGusbigubedafribifrinus"/>
    <eLiterals name="EuDaBubofriguses"/>
    <eLiterals name="DuguNulAugubeBiFriBegusGunulAulius"/>
    <eLiterals name="DonulAugububebuBitin"/>
    <eLiterals name="AnbebobugusGusgusfriBuguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulAufrinulauCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebeGusbubuFriFriboNulAutor" ordered="false" upperBound="-1" eType="//BeboNulaudabobeNulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Algusfribefrigusgustus" eSuperTypes="//FagusgusGufriBibofriBibuFribebiFriCio //AuBonulaubobeBigusfribudanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albugugusGusnulauNulAuGusgusNulauBiguBues" ordered="false" upperBound="-1" eType="//FagusgusGufriBibofriBibuFribebiFriCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnboBubolius" eSuperTypes="//BeboGubicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulAubuNulaubiGues"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFrifribuGuBuBubububulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGuBunulAuDagudadatus" ordered="false" upperBound="-1" eType="//EubibidabubidaTus" eOpposite="//EubibidabubidaTus/dogubibobidaBegusBebefrinules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiDadadadagusnulaunulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Alaunulautin">
    <eLiterals name="BebeguBuBunulauGustin"/>
    <eLiterals name="DobogusfriNulauguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnboDaBobubinulAuBeNus" eSuperTypes="//AlaufrinulaudabeBibodadacio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aldaguNulauBeFrigubecus" upperBound="-1" eType="//BaBeNulAuNulAugusbiBibuEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubigusbubobebebobuguBetin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BiFriDanulAudaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafriguNulAubefrigusNules" abstract="true" eSuperTypes="//AububibiBogusgunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBodabebubunus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAuguBudadadaBinus">
    <eLiterals name="AlBofridafriNulauBodaBobinulius"/>
    <eLiterals name="AgusgusbufriBigufrinulAubeCus"/>
    <eLiterals name="Anbogunus"/>
    <eLiterals name="DudabobogusGudaBedaguses"/>
    <eLiterals name="AlgusGusaunulAunules"/>
    <eLiterals name="DubibebeCus"/>
    <eLiterals name="BanulaugusbuboBefriBeNus"/>
    <eLiterals name="BafribubofriBugusgustor"/>
    <eLiterals name="DiFribebebiGusgusboGusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuFribibugusdagubuNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebodanulauDanulaubebelus" ordered="false" upperBound="-1" eType="//FagusaububuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubibiBebibuFriGutus" eSuperTypes="//AlBibegunulaufriBues //AugusbeboBobebenulaugubeNus //BanulaunulaugubiboNulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuDaBofrigusbeBigustor" ordered="false" eType="//EuNulaubibegugusgusauguLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugudaBeGuBotus" eSuperTypes="//AunulAuFribuNulaudaguFrinulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidagusboboes" ordered="false" eType="//BaGusBegusbogusgusbiBefriguCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdagusBecio" eSuperTypes="//FaGuBubenulaubeGubebegusTus //Fanulaububobigugunules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabibigunulAugunulaubiBeDaFridaTin" instanceTypeName="typeBaBonulAudabobubecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubigubiGufritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubuBufribogusfriDaGusbonus" ordered="false" eType="//EubibidabubidaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnfrigubifriboNulauCus" instanceTypeName="typeAlDaDabugusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauBeNulaubugusfritus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aunulaubefribofribilius" eType="//AubegusbogudaDagubeNulautin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebuBifribedaBubitus" eType="//AlgusGuBifribucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dogufridabogusbegusdabies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusNulAufriboguguGunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulaubenules" ordered="false" upperBound="-1" eType="//BrauFrinulaubebobobugusgubeEs" eOpposite="//BrauFrinulaubebobobugusgubeEs/eFriBogusBidabedabebonulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DogubuNulaudaNulauBidafries" instanceTypeName="typeDobebebibobugugusaufribuFrilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraufriNulAufrinulaufridabucio" instanceTypeName="typeDuFribiNulAudabubinulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBoBefribeBobebogusbuTin" eSuperTypes="//FagusbebogusbudaGufriguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFrigusbibedaGusbobubetin" eSuperTypes="//FagusbebogusbudaGufriguscio //FafriguNulAubefrigusNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albibobinulaubebitus" ordered="false" eType="//BabiboGugugubegusgulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BiNulaugubunulauDabiNulauFrifribetus">
    <eLiterals name="DofribeboBoBebelius"/>
    <eLiterals name="BabibinulaubuNulaubiboNulauBigusbebiBitin"/>
    <eLiterals name="BenulauGusbeBigusAufriDagusbecio"/>
    <eLiterals name="BraudabeGusbuGuBudafries"/>
    <eLiterals name="EfriDaBibobigusfriCio"/>
    <eLiterals name="AguDaGuboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibubuBubibeGufrinulAunus" eSuperTypes="//BraugudaBeGuBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabinulaubobobibuGusaunulaubuBelius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBugusgubocus" eType="//DiGuGubuguguscio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbugusDabinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebuBigubobutin" ordered="false" eType="//BeboNulaudabobeNulaucus" eOpposite="//BeboNulaudabobeNulaucus/daBuNulAububiBefrifriGusDaboBetor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusbibobugusBiTor" eType="//DiGusbiGugufriBobubenulAubeNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusbebofrigusdagusDabinulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBiDadabogubedaNulaubues" ordered="false" upperBound="-1" eType="//BiDadadadagusnulaunulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afribubufribufribebebeguNulAuTor" upperBound="-1" eType="//AuBegusbububofribufrilius" eOpposite="//AuBegusbububofribufrilius/dabebofribinulauBifribufridafriBiGuFrifriTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlnulaudadaGusbiBobeEs" instanceTypeName="typeBafridaBoNulAuGufribocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusAugufrinulaubuNulAubefrilius" eSuperTypes="//AugusbeboBobebenulaugubeNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eudadadafrifrinulaubues" eType="//FaDabodabebifrifrigusIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusbigusboboGusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobudaBuBiGusGuDadaboBenulauFrifrilius" ordered="false" eType="//BaFrifrinulaubitor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anNulaubibiBidabebonulAunules" eType="//BrAuguBudadadaBinus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBonulauDaBogusguslius" eSuperTypes="//ADabinulauBiBunulAuguboNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DanulAuGues">
    <eLiterals name="DiDadaDagufrinulaudaBubolus"/>
    <eLiterals name="EuguFriBibonulAugucio"/>
    <eLiterals name="AlfriBeFribebuBobudanulauGuslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifridabuBobofriFriEs" abstract="true" eSuperTypes="//EubibidabubidaTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doguCus" upperBound="-1" eType="//Dotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidaguNulAugusbuNulAuguFriNulauGugusauCio" eSuperTypes="//BrAuFribibugusdagubuNulIus //BibuBuNulAudaGusbitus //BaGusBegusbogusgusbiBefriguCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fadaguBidaGusboCio" eType="//AugusBedadadabiLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibebuFriboNulAubifriLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebebiguFriCus" eType="//FabigugubibudagugusFries" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaubebuBebinulEs" eSuperTypes="//EdaBefribunulaubebonulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulAubeGusBodafriBofriGuscio" ordered="false" upperBound="-1" eType="//AlGusauguBobifrigusFriBuNulaubocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabodagugufriDaGubobebitor" eSuperTypes="//AubigusbubobebebobuguBetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusguBobubugusfriDabebibogubebiguBigustin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Algusbigusfribilus" eSuperTypes="//ADabinulauBiBunulAuguboNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DibunulaufribiEs">
    <eLiterals name="AnnulAunules"/>
    <eLiterals name="Abebubudagusgusgubibicus"/>
    <eLiterals name="FagusgusnulaubebunulauBeBuguLius"/>
    <eLiterals name="AldabiBoBedaBofritin"/>
    <eLiterals name="DofribinulAubufriFriguDalus"/>
    <eLiterals name="DibibudafriGubebiBicio"/>
    <eLiterals name="DafriBeFribobigutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoFriBobebobubuguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBodagusbogusbinulAubobuLus" eSuperTypes="//BiFrigusgugusBuFriGulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBenulAuguGuBocio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusgububocio" eType="//DagunulAubudaBoboNulauBidaDaCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifribufrinulaunulauFriDadabebues" eSuperTypes="//DaBoBefribeBobebogusbuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anbogububigunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aufribegubibecio" eSuperTypes="//AnboDaBobubinulAuBeNus //BinulAubuNulaubiGues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbedagusbegusBuboNulius" ordered="false" upperBound="-1" eType="//DoBoBeguDaFrigubufribiGusgusGusTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusbubibuBegudagudadagustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braufribolus" ordered="false" eType="//Fanulaububobigugunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulAuGuGutus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabedaDadabiBodaNulius" eSuperTypes="//BrAuBonulauDaBogusguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duNulAuBebuBebufribigubulius" ordered="false" upperBound="-1" eType="//AlaufrinulaudabeBibodadacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AubefriBobelius">
    <eLiterals name="EufribobiGudaDabeBenulauguTor"/>
    <eLiterals name="Dogutor"/>
    <eLiterals name="AlguDabebeGusBeBolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuDadaFrigusguBeBilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difribuBolius" eType="//AubefriBobelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubogusbobeguTin" eSuperTypes="//DanulAuGuGutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobobebobinulauDaBeTor" eType="//EubebedabinulAugusbibotus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DafridagusBobebegunulauBoBidalius">
    <eLiterals name="FabunulaugunulauBodanus"/>
    <eLiterals name="AugubinulAuBefridabenulAuCio"/>
    <eLiterals name="AlbeboBinulautus"/>
    <eLiterals name="Ebibibubonulaufritin"/>
    <eLiterals name="FafrigusBuBuguses"/>
    <eLiterals name="DodabedaBiboFricio"/>
    <eLiterals name="DogugusbegufriBegusdaguBugunus"/>
    <eLiterals name="BabibinulauBiBibobunulIus"/>
    <eLiterals name="BifrifrifrinulauGubiFriFriBoFritor"/>
    <eLiterals name="BebugusbefridaGuCio"/>
    <eLiterals name="AnfriguGuGusBegustin"/>
    <eLiterals name="AuBeBegusdafrigusAubuLius"/>
    <eLiterals name="AuDafriGusbuboDanulaubuBugusbecus"/>
    <eLiterals name="DudaBugusnulaugusfribobobiGusGucus"/>
    <eLiterals name="FaNulAunulauboFribobegunulaubogufricio"/>
    <eLiterals name="FanulaubedabobuBuFribonulauTin"/>
    <eLiterals name="BraububoBobuBeBubenulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBogugubobeBeGuscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubeBibiBebunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGugusbubibeBebiboGubebonus" ordered="false" upperBound="-1" eType="//AuBegusbububofribufrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eubibegusgubunulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbonulauBonulauguguFriLus" eSuperTypes="//BaFrigusbibedaGusbobubetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubifrifrigusDadanulAudaboLus" eType="//FabigugubibudagugusFries" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubeFriguBefribifrinulauboBeFrigusgusIus" instanceTypeName="typeDiNulauBiBuboGusnulAunulaubotin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrauDafrifriGusguslius">
    <eLiterals name="FaboDabegusbegusguGusGuslus"/>
    <eLiterals name="Dububefridalius"/>
    <eLiterals name="DanulAufribidadafriBebeBubidagusTus"/>
    <eLiterals name="FafrigusAuBeFrigusLius"/>
    <eLiterals name="AlbobinulauDabobies"/>
    <eLiterals name="BiGusaunulauBonulAubobutin"/>
    <eLiterals name="EubeBufrigusBegusnulaucio"/>
    <eLiterals name="DibefribeFrigubeCio"/>
    <eLiterals name="BaGubibiguTin"/>
    <eLiterals name="AlDabibeguTus"/>
    <eLiterals name="Aubegubebilius"/>
    <eLiterals name="BefriLus"/>
    <eLiterals name="AnboGugusGudaBubonulaucio"/>
    <eLiterals name="DabibebuBubuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusbuBilus"/>
</ecore:EPackage>
