<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fafrinules" nsURI="http://hub.de/rcore/examples/fafrinules" nsPrefix="Gt">
  <eClassifiers xsi:type="ecore:EClass" name="DoFrinulaugusnulAugubeBoGuGugusbocio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DigubunulAuLus">
    <eLiterals name="AngusBifrinulAububoNulius"/>
    <eLiterals name="BeBugusgugufriDaBenulaubecio"/>
    <eLiterals name="EbibidagunulauBuNus"/>
    <eLiterals name="Braunulaugusius"/>
    <eLiterals name="BagubuBonulAudaNulAuNulAuGuscus"/>
    <eLiterals name="AbobugusGues"/>
    <eLiterals name="DoBuguNulius"/>
    <eLiterals name="BrAuGusAudabiBigubeBofriDaFriLus"/>
    <eLiterals name="DanulAubobububetor"/>
    <eLiterals name="FaBoGububobugufribicus"/>
    <eLiterals name="AubigubefribegusAuTin"/>
    <eLiterals name="DaBubugubobudanulaubetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigudaBudadaBubudaBubulus" eSuperTypes="//DoFrinulaugusnulAugubeBoGuGugusbocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augusnulaufriBigusNulauNules" eType="//DigubunulAuLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgubeGudabibegusgusaudafribonus" eSuperTypes="//DoFrinulaugusnulAugubeBoGuGugusbocio //BigudaBudadaBubudaBubulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabugubuFribiDadagusguBudacus" ordered="false" eType="//DubugububuBofribitus" eOpposite="//DubugububuBofribitus/eufriBoGuBenulAugusbebigubidatin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusgunulAudacus" eType="//DuBuNulaubogubolus" eOpposite="//DuBuNulaubogubolus/duDadanulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulaufriguFrigusBibubitin" eSuperTypes="//BigudaBudadaBubudaBubulus //EgubeGudabibegusgusaudafribonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufrifridaBeguGusfriguNulaunules" ordered="false" upperBound="-1" eType="//EgubeGudabibegusgusaudafribonus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auFrifriGufriNus" eType="//DigubunulAuLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebogusBobuDaguNulaubibobeGuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebefribebufribeBiBunulaufricus" upperBound="-1" eType="//DaGusbodabinulaubenulautin" eOpposite="//DaGusbodabinulaubenulautin/fanulaufribibenulAunulaubeLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugugusaugubudaBuDalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulaubidaBuBodadagudadaTor" ordered="false" eType="//DiNulaubobugubuDaBudaBuGustus" eOpposite="//DiNulaubobugubuDaBudaBuGustus/baBifrigusgufriGuGusGusbiNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubifribeDaNulauBeBeGusBibuGuBetor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBiGubobedaBibiNulAuGusbotus" eType="//DigubunulAuLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBiFrigusbobubuBiBiBonulaucio" instanceTypeName="typeDabuGuNulaubiBiguboBunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBubiFrinulaunulaufribobifries" eSuperTypes="//EubifribeDaNulauBeBeGusBibuGuBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusbodabinulaubenulautin" eSuperTypes="//AugugusaugubudaBuDalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulaufribibenulAunulaubeLius" ordered="false" upperBound="-1" eType="//BebogusBobuDaguNulaubibobeGuCus" eOpposite="//BebogusBobuDaguNulaubibobeGuCus/ebefribebufribeBiBunulaufricus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguguBoFridaBibees" ordered="false" upperBound="-1" eType="//EubifribeDaNulauBeBeGusBibuGuBetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusbobiBebogubunulauBuLus" abstract="true" eSuperTypes="//BaNulaufriguFrigusBibubitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fadaGunulauBifrinulaubonulAuNulauguTin" eType="//DigubunulAuLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auFrifribuGusgubifriguslus" ordered="false" upperBound="-1" eType="//EBoBubobiGusbebilius" eOpposite="//EBoBubobiGusbebilius/anbebedafriFribibobuBicio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAugugusbuNulAubibiGuBegusdaguNulIus" ordered="false" eType="//BibifridadabuBebecus" eOpposite="//BibifridadabuBebecus/alGudaBofridaguboGudabeTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabiBufriBeBenulAuLius" eSuperTypes="//BaNulaufriguFrigusBibubitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egusauGugusbodagubobunus" eType="//DigubunulAuLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulaunulAuGudaBofriBeguNulAutus" ordered="false" upperBound="-1" eType="//EgubeGudabibegusgusaudafribonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BraugusGuBebogusBobuBuNulauNulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBebufrinulaugucus" instanceTypeName="typeDufriBoGusDabutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugusfridaTus" instanceTypeName="typeDuboBiBiFriBubebiBebuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFrifribogufridaTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBubofribebeGusDaBonus" upperBound="-1" eType="//AguGusFridadafriFribuGusNulauTus" eOpposite="//AguGusFridadafriFribuGusNulauTus/dabigutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibebibobibuboNulAucio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugufridanulaucio" eType="//BraugusGuBebogusBobuBuNulauNulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBoBubobiGusbebilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augusdagudaBebinulius" eType="//DiBiFrigusbobubuBiBiBonulaucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbebedafriFribibobuBicio" ordered="false" eType="//AnGusbobiBebogubunulauBuLus" eOpposite="//AnGusbobiBebogubunulauBuLus/auFrifribuGusgubifriguslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fabobubifridabulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubugububuBofribitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufriBoGuBenulAugusbebigubidatin" ordered="false" upperBound="-1" eType="//EgubeGudabibegusgusaudafribonus" eOpposite="//EgubeGudabibegusgusaudafribonus/dabugubuFribiDadagusguBudacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlDafrigubulus" instanceTypeName="typeAugusBidabigusbeGubobuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraububiguGustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaubobugubuDaBudaBuGustus" eSuperTypes="//EubifribeDaNulauBeBeGusBibuGuBetor //BebogusBobuDaguNulaubibobeGuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBifrigusgufriGuGusGusbiNulius" ordered="false" eType="//AugugusaugubudaBuDalus" eOpposite="//AugugusaugubudaBuDalus/alNulaubidaBuBodadagudadaTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AfrigusbofrinulAuBonulautin" instanceTypeName="typeFabogubeguGuboBeBetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuBuNulaulus" eSuperTypes="//BraububiguGustus //DiNulaubobugubuDaBudaBuGustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibifridadabuBebecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGudaBofridaguboGudabeTor" ordered="false" upperBound="-1" eType="//AnGusbobiBebogubunulauBuLus" eOpposite="//AnGusbobiBebogubunulauBuLus/brAugugusbuNulAubibiGuBegusdaguNulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoDadaGutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anAuBibubigusfriNulauTin" ordered="false" eType="//BrauFrifribogufridaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidabegugusnulauBiFriguBeGucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiDabeBudabobubees" eSuperTypes="//DoFrinulaugusnulAugubeBoGuGugusbocio //BibifridadabuBebecus //DiNulaubobugubuDaBudaBuGustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubibebegusbeBugugustin" eType="//AlDafrigubulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DigusDabegubobigustor">
    <eLiterals name="DobiBebibofriBudabelus"/>
    <eLiterals name="AngusgubudaGuBiBuBeNus"/>
    <eLiterals name="BraubifribodagusbiGusgubogubilius"/>
    <eLiterals name="Dugubogufribobogugulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fabobobedafrigubolus" eSuperTypes="//DabiBufriBeBenulAuLius //DaBubiFrinulaunulaufribobifries //DibebibobibuboNulAucio //BibifridadabuBebecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbibidaBuBilius" ordered="false" upperBound="-1" eType="//DaGusbodabinulaubenulautin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braugubufriFries" eType="//AfrigusbofrinulAuBonulautin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubeBobuBegubigugusius" instanceTypeName="typeBeNulaugunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuguNulaugusbebegusFriguboLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAuFribiboGuguGunulauGusbobugulius" eSuperTypes="//DubugububuBofribitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBubeboDaBinulaudagubuTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="danulaubecio" eType="//DigubunulAuLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubifrifriBefriGucus" eSuperTypes="//DabiBufriBeBenulAuLius //AnulAuFribiboGuguGunulauGusbobugulius //DaGusbodabinulaubenulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabuBobiBobinulEs" eType="//BaNulaufriguFrigusBibubitin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biNulAubues" ordered="false" upperBound="-1" eType="//BiDabeBudabobubees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BeNulAugusbeGusCus">
    <eLiterals name="DiGuGusdagusguFribecus"/>
    <eLiterals name="DobeGubeBufriFribibodadalus"/>
    <eLiterals name="DidabenulAugugusfribigusgutin"/>
    <eLiterals name="AubiboFribubibilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusfrigusbiboBodanulAubitor" abstract="true" eSuperTypes="//BigudaBudadaBubudaBubulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bidagubibubigusaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diguFrigubebuNulAugusNulEs" ordered="false" eType="//BebogusBobuDaguNulaubibobeGuCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBibiGuBebinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusbinulAugusbeBuDagusFriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufridabuFriDaBugubedagustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabiBofrinulauBiguscio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaGuBunulEs" eSuperTypes="//FaGuguNulaugusbebegusFriguboLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DugubuBenulAunulAubeGuGugucus" instanceTypeName="typeBraububogusnulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusnulaubobuBobifriBububebugusLus" abstract="true" eSuperTypes="//DabiBufriBeBenulAuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulAubedacus" ordered="false" eType="//DabudafribofribegubuDabetor" eOpposite="//DabudafribofribegubuDabetor/alBidaBegusnulAudaDalius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibuboDaGubibubebibuBuFribeGugusaulus" ordered="false" eType="//DubebofrigusaubogusBugusCio" eOpposite="//DubebofrigusaubogusBugusCio/fabigufridanulAubegunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AguGusFridadafriFribuGusNulauTus" abstract="true" eSuperTypes="//BiDabeBudabobubees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabigutin" eType="//BrauFrifribogufridaTus" eOpposite="//BrauFrifribogufridaTus/euBubofribebeGusDaBonus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAubiFridatin" ordered="false" eType="//DoFrinulaugusnulAugubeBoGuGugusbocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eufrigubufrigusbinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabegunulauDabibues" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBoLus" eType="//EgubeGudabibegusgusaudafribonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiBebuBufriBeDabogubiBogustin">
    <eLiterals name="AbogusgubugusnulaunulIus"/>
    <eLiterals name="EudabiNulaubodaGusbuFriboTor"/>
    <eLiterals name="BrAuBigubufribiGuDagunus"/>
    <eLiterals name="DubigusNulAuBuTus"/>
    <eLiterals name="BrauGusGusNulauDabebebutin"/>
    <eLiterals name="AbubiGusBeguGusaunulEs"/>
    <eLiterals name="BrauguFriGubefribufrifrigulius"/>
    <eLiterals name="DugusbuBeGusboBebiDabicio"/>
    <eLiterals name="BiFrifrifribecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DidagusAuLius" instanceTypeName="typeEGubudaboDagusbuNulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusBiFribibeGubiFrilius" eSuperTypes="//BigudaBudadaBubudaBubulus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuNulAuBebibibubobonulauTus">
    <eLiterals name="AbodabugusbebeBunulauGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BiFridadaBofriFriBuguBeLus">
    <eLiterals name="BiBodaBidabifriDabenus"/>
    <eLiterals name="BabefribobunulauguGuBebotus"/>
    <eLiterals name="DogusdaBodaNulaugunulauBunus"/>
    <eLiterals name="BeboBoGudagusbocio"/>
    <eLiterals name="DiBibidadaguTus"/>
    <eLiterals name="EuBiGugugusbibifribeGuBuBicio"/>
    <eLiterals name="Dibufribubibigusaubogusaubutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiguBenulauGusaubotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugugusBigusFrinulIus" ordered="false" eType="//AuBoDaFriGusbiBuBibuGudagusgues" eOpposite="//AuBoDaFriGusbiBuBibuGudagusgues/abegufridabedaGusbegusaubebugusbuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusBoBebiFribobuBitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobibubiBibonulaubudaFriguscus" ordered="false" upperBound="-1" eType="//DiNulaubobugubuDaBudaBuGustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBinulauNulauDalus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebibunulaubeDabuGuNulius" eSuperTypes="//AnGusbobiBebogubunulauBuLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubibobuGusfribigusnules" eType="//DidagusAuLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudaBoboFriBoBofridacio" eSuperTypes="//DidabegugusnulauBiFriguBeGucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngubegububiGusgutus" eSuperTypes="//DibuBuNulaulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibefriBudabifritor" eType="//AlDafrigubulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibudaGuFridagubiGusGusbifrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beNulauNulius" eType="//DidagusAuLius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAutin" ordered="false" upperBound="-1" eType="//EgubeGudabibegusgusaudafribonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobeGusGusnulAuGusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBoDaFriGusbiBuBibuGudagusgues" eSuperTypes="//BibifridadabuBebecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAugusAuNulAudaGusTus" ordered="false" eType="//DaBubiFrinulaunulaufribobifries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abegufridabedaGusbegusaubebugusbuLus" ordered="false" eType="//BabiguBenulauGusaubotin" eOpposite="//BabiguBenulauGusaubotin/braugugusBigusFrinulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnFrifrinulAugubuDafrinulaubenulius" instanceTypeName="typeDonulAubegusAubuFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBibubibubedatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBonulaudaBeNus" eType="//FabegunulauDabibues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auFrigusfrifribogunulAuguNulEs" ordered="false" eType="//DubifrifriBefriGucus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dicus" eType="//DigubunulAuLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBegusdabobeTin" ordered="false" upperBound="-1" eType="//AnBubeboDaBinulaudagubuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBiBeBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBuNulaubogubolus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duDadanulius" upperBound="-1" eType="//EgubeGudabibegusgusaudafribonus" eOpposite="//EgubeGudabibegusgusaudafribonus/dagusgunulAudacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusdaDaFrifribuGubibeNulaunulius" eSuperTypes="//BibifridadabuBebecus //BebibunulaubeDabuGuNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibobigusgusNulaugusdaGusGuBoLus" ordered="false" upperBound="-1" eType="//FabegunulauDabibues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusdabiBufribodacus" eSuperTypes="//DabiBofrinulauBiguscio //FaBinulauNulauDalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBuBogusFribogusgubitus" upperBound="-1" eType="//DudaBoboFriBoBofridacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnauBobofribuBodaboboGuDacio" abstract="true" eSuperTypes="//AnGusbobiBebogubunulauBuLus //BrauFrifribogufridaTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadadaguBudagusfribibeFriGusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ancus" ordered="false" eType="//FabegunulauDabibues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dafribubogusbibibelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbifrifridabeBobedanus" abstract="true" eSuperTypes="//FaBinulauNulauDalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFribeDagusnulAugufrigusnus" eSuperTypes="//DoFrinulaugusnulAugubeBoGuGugusbocio //AuBiBeBelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubibubofrinulaunulaunulauboguCus" ordered="false" upperBound="-1" eType="//AngubegububiGusgutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaFriBebebonules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euGusDabedaNulauTor" eType="//DigusDabegubobigustor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulAubeDagusbeBiguBeBibibuLius" eType="//FabufrinulaufriFridabigubuBitus" eOpposite="//FabufrinulaufriFridabigubuBitus/digubibibedagusnulaubuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaboFridaFrifribedabobonus" instanceTypeName="typeDobobuGusbuBonulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibiNulAuBibunulEs" eSuperTypes="//BabiguBenulauGusaubotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabeGusfriboguscio" ordered="false" upperBound="-1" eType="//AnulAuFribiboGuguGunulauGusbobugulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbebodaGusgusdaes" eSuperTypes="//DubugububuBofribitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusgubebigusgusBefriBobuBoDaBitin" upperBound="-1" eType="//EgubeGudabibegusgusaudafribonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeBugusgugustin" instanceTypeName="typeDiBoNulauGusbobubigusbibubuFriboguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafriBiboguBefrinulaucio" eSuperTypes="//DubifrifriBefriGucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGugusnulaubobotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulaufribuBebodaBegubogusbobicus" abstract="true" eSuperTypes="//Dafribubogusbibibelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBenulaunulAuGusgufriBebuFrilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabutin" eType="//BraugusGuBebogusBobuBuNulauNulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DafriBodagufriGuGusBoGuboTus" instanceTypeName="typeBraubofriGuFrifricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabuboNulauBogusBibinulauBocio" eSuperTypes="//Bidagubibubigusaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBoBodacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digunulaubufriCus" ordered="false" eType="//BrauFrifribogufridaTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dodaBegusbobunulAulus" eType="//DaboFridaFrifribedabobonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibuGusgunulaububegusnulauLius" eSuperTypes="//AuBiBeBelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBegusBoBobudaBeBiGubigusaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGuBeBunulaubobiDabenulaubuLius" ordered="false" eType="//EBibiGuBebinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGunulaufribiGunulaubibofrigusguslus" ordered="false" upperBound="-1" eType="//AlNulauBubobodaFribubucio" eOpposite="//AlNulauBubobodaFribubucio/eufriGubebodacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAuBegubeBubudanulAugugusLus" instanceTypeName="typeFaBoBiguBogubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bigusaugugusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugububuGudagusfribugunulaubeBogustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogusbuFriBibibiguBedanulius" eSuperTypes="//ANulaufribuBebodaBegubogusbobicus //AnBibubibubedatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogusIus" eType="//EuNulAuBebibibubobonulauTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulauBubobodaFribubucio" abstract="true" eSuperTypes="//ANulaufribuBebodaBegubogusbobicus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubudaGuNulAutin" ordered="false" eType="//DogusfrigusbiboBodanulAubitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufriGubebodacus" ordered="false" upperBound="-1" eType="//BeBegusBoBobudaBeBiGubigusaunus" eOpposite="//BeBegusBoBobudaBeBiGubigusaunus/biGunulaufribiGunulaubibofrigusguslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabugusGusbiguGusaunulAuguboLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAubibigusbuNulaufribiboBoTor" eSuperTypes="//DuBuNulaubogubolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulAufrifribugusboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbidaGugusbidaboBolius" eSuperTypes="//BibudaGuFridagubiGusGusbifrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadabuguBeNulaubocio" ordered="false" eType="//AlbebodaGusgusdaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulAuBiFridabutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaFribibofrigusBobebuGuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulauboBubiguBiCio" ordered="false" upperBound="-1" eType="//DibebibobibuboNulAucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfriGubigubees" ordered="false" eType="//DabuboNulauBogusBibinulauBocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabufrinulaufriFridabigubuBitus" eSuperTypes="//DaFriBebebonules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digubibibedagusnulaubuEs" ordered="false" upperBound="-1" eType="//DaFriBebebonules" eOpposite="//DaFriBebebonules/donulAubeDagusbeBiguBeBibibuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBuBufriNulauBufribuGusbibees"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugugusnulauboDanulaugunulAuBiNus" instanceTypeName="typeDafriGusbobeBilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGubugusnulAufriBobudaBolus" eSuperTypes="//FafriBiboguBefrinulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlAubefribobulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebocus" ordered="false" upperBound="-1" eType="//AnnulAubidabodaguBufrigusbebilius" eOpposite="//AnnulAubidabodaguBufrigusbebilius/eudagusBeguDabucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuboGubofrigusbidatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGusgusdagusDaDabobitus" upperBound="-1" eType="//BeBenulaunulAuGusgufriBebuFrilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGuBeBugusguGubuBotor" ordered="false" upperBound="-1" eType="//BaNulaufriguFrigusBibubitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbiFridabonulaubucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBobogugubodatin" ordered="false" eType="//Eufrigubufrigusbinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuguBunulauNulaubinulAugusbedacus" instanceTypeName="typeEubugusGusgusGugulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubobuBiNulAugusBobecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bagusnulaugubufrilus" eSuperTypes="//AnulAuFribiboGuguGunulauGusbobugulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaDagusNus" ordered="false" upperBound="-1" eType="//DibegusfrifribeBeGuTin" eOpposite="//DibegusfrifribeBeGuTin/bibidanulauNulaudaDanules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusgufriGuDaDabees" abstract="true" eSuperTypes="//AngubegububiGusgutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dunulaubebobuDaGusdaCus" eType="//BeBugusgugustin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBuBodagufriguBiGunulauDaLus" abstract="true" eSuperTypes="//BibiNulAuBibunulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebeBiboGusnulius" ordered="false" upperBound="-1" eType="//EbiFridabonulaubucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aguGusfriBodacio" eType="//DigusDabegubobigustor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubuGububebugusBoBubicus" eSuperTypes="//BeBegusBoBobudaBeBiGubigusaunus //AnBibubibubedatus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EugubibebufriBonus" instanceTypeName="typeBiNulauGusguBonulaubuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabudafribofribegubuDabetor" eSuperTypes="//AnulAuFribiboGuguGunulauGusbobugulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBidaBegusnulAudaDalius" ordered="false" eType="//AuGusnulaubobuBobifriBububebugusLus" eOpposite="//AuGusnulaubobuBobifriBububebugusLus/braunulAubedacus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigufriFriBoboBonules" ordered="false" eType="//BraububiguGustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbuFriBunulius" instanceTypeName="typeFabeNulaugusbidaboFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabibigugusgubiGusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobonulaububuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulAuDaNulaububufribigusautin" ordered="false" eType="//DudaBoboFriBoBofridacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubodaBubogugusdalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubudagufriBifriNulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubigusAulus" abstract="true" eSuperTypes="//Fabobubifridabulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulauBugubiBuBubigusdalus" ordered="false" upperBound="-1" eType="//AugudaBelius" eOpposite="//AugudaBelius/aDabedaFrigutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BefribubuBodabiGubotor" eSuperTypes="//AlGubugusnulAufriBobudaBolus //BibudaGuFridagubiGusGusbifrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulAudabubiBegubobiDaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBofribogubunulAubefriGusbobiNus" eSuperTypes="//DibebibobibuboNulAucio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBoTus" eType="//DidagusAuLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EdaNulaunulauDadaNulauguLus" instanceTypeName="typeDibiFrinulaubugubobegucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeBobeGusbibeGusDafriDanulAulus" instanceTypeName="typeBibibeNulAugusFribefrilus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuBeFriBuBinulAudaBogubolus">
    <eLiterals name="AlgubunulaugusnulAutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaubunulAucus" eSuperTypes="//DobonulaububuLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EbubinulAugudaboGuGuNulEs" instanceTypeName="typeEunulAubibeguboboNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriNulauBeboBiguBebogutus" eSuperTypes="//BibuGusgunulaububegusnulauLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabinulauNulAuFribigusBodatin" eSuperTypes="//DibuBuNulaulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibugusfriTus" eType="//BraugusGuBebogusBobuBuNulauNulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuDaGusbegufritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBoBigubenulaugusdaDagucio" eSuperTypes="//DobonulaububuLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DibodabofribubunulauLus" instanceTypeName="typeDibuBobebugubibiDadaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugubinulaubefrigusAulus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DodabuNulAubenulautin">
    <eLiterals name="BebodanulauFrifritor"/>
    <eLiterals name="EuBibegubuBigunulaubutin"/>
    <eLiterals name="DoBegufriDabilus"/>
    <eLiterals name="EuNulAudabibuButin"/>
    <eLiterals name="AuBebobonulaubeDaBees"/>
    <eLiterals name="AnnulauBedaDatus"/>
    <eLiterals name="BraubefriboGusguNulAuBues"/>
    <eLiterals name="ANulauGusauBebebuLius"/>
    <eLiterals name="Albudanus"/>
    <eLiterals name="AnAuGuNulaudaGufribuboFribibiBigusBebotus"/>
    <eLiterals name="DaBefricus"/>
    <eLiterals name="EuNulaudaBiGusbeBuBoboBitin"/>
    <eLiterals name="Bagusaudabedafribelius"/>
    <eLiterals name="FaFribifriNulaunulaubunulauFrinulius"/>
    <eLiterals name="DifridafriDaBiBeboguguCio"/>
    <eLiterals name="DigubibuboGusAugufrinulaubidaFriEs"/>
    <eLiterals name="BabuNulAuFriGubobinulAubenus"/>
    <eLiterals name="EboBefribigusbifrigusTor"/>
    <eLiterals name="DafriboGusaudabeGusGucus"/>
    <eLiterals name="AufriBudaGuFritin"/>
    <eLiterals name="EgubuBuNulaunulAucus"/>
    <eLiterals name="BeBebuBofrigusgutor"/>
    <eLiterals name="ANulAugubufribuBuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobedabuBiBuFribiGusCio" eSuperTypes="//BadadaguBudagusfribibeFriGusius //EuNulAuBiFridabutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bebedabonulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuboBogusbudafrigutor">
    <eLiterals name="BinulaudanulAuDadadaGutor"/>
    <eLiterals name="BaBiDagusfrinulAuboboGusboGutus"/>
    <eLiterals name="AnAuFridabobitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBugusGubugusBibeTin" eSuperTypes="//BabiguBenulauGusaubotin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DabubeboGusbibidaBeBeTin" instanceTypeName="typeAnBinulaubofriguBeGufribuBolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabebibofribenulaubebububoLus" abstract="true" eSuperTypes="//Bigusaugugusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBubedaBebobobeguButor" eSuperTypes="//FaBinulauNulauDalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusboDafrigusgubudaBiFrigulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annulaunulaunus" eType="//DigusDabegubobigustor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulauBeBebufrigusboGuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diFriBoBebugugubobutin" ordered="false" eType="//BebogusBobuDaguNulaubibobeGuCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubodabinulius" ordered="false" eType="//Dafribubogusbibibelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABiboBefribeFrinules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DinulauFribefriGuDacio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebobobobegusTus" instanceTypeName="typeBaFrifritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaDaBoBigusbufriNulAuLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dinus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulAubiBoboNulAubitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albeboBudagusBegubiboBiguTin" upperBound="-1" eType="//AugudaBelius" eOpposite="//AugudaBelius/baNulaugusNulAuboboDaBoTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobibudagunulAudabuCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Babebogusdabedator" instanceTypeName="typeBrAubudabogugusboNulaububibegusgufrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dodabufrilus" instanceTypeName="typeEubuGusdanulaubogues"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBenulAugusaudaCio" abstract="true" eSuperTypes="//DibebibobibuboNulAucio //BenulauBeBebufrigusboGuCus //DogusfrigusbiboBodanulAubitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBuBeDagugubuFries" ordered="false" eType="//AnauBobofribuBodaboboGuDacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AldabuBefrifriDadaBogusbibuDaBilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBibobigububidabubuBetin" upperBound="-1" eType="//Dafribubogusbibibelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnFrigufribodadabeBibonulautus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulauBoBebeBucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Begugusbibues" eSuperTypes="//FabufrinulaufriFridabigubuBitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBeNulaufrinulAuBedaBeFriLus" ordered="false" upperBound="-1" eType="//DubuGububebugusBoBubicus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusauTin" ordered="false" eType="//AgusbinulAugusbeBuDagusFriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BefribuguGusbiBuEs" eSuperTypes="//EBibiGuBebinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anGuNulauFribogugusbilius" eType="//DiBiFrigusbobubuBiBiBonulaucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubudaboFriBiCus" instanceTypeName="typeBagusguNulauboboguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Efribunulaubibinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusdabebebuBubolus" eSuperTypes="//DaGusbodabinulaubenulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befriNulauBifrigunus" ordered="false" upperBound="-1" eType="//AlGubugusnulAufriBobudaBolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Braugufribobedagufrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulaubiBeDaBobedabubelius" ordered="false" upperBound="-1" eType="//BrauBugusGubugusBibeTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBoNulaudadadaGuBoboBetus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulaudagusfrifriBuBubutin" eSuperTypes="//EugububuGudagusfribugunulaubeBogustus //BabinulauNulAuFribigusBodatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaboBuBudadabefrifriBiEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbibugusbigusbifrifriButin">
    <eLiterals name="DaBonulAubeDadanulauDagulius"/>
    <eLiterals name="BiDaguBoBugusboGusFriBobues"/>
    <eLiterals name="AngusdaBebobuDabeboNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubebofrigusaubogusBugusCio" eSuperTypes="//BrauGusdabiBufribodacus //BaDaBoBigusbufriNulAuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulAugubunulius" upperBound="-1" eType="//Bigusaugugusius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabigufridanulAubegunulius" upperBound="-1" eType="//AuGusnulaubobuBobifriBububebugusLus" eOpposite="//AuGusnulaubobuBobifriBububebugusLus/dibuboDaGubibubebibuBuFribeGugusaulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulaudaBibebeboDaBenulaufrifriFrinus" ordered="false" upperBound="-1" eType="//AuBubedaBebobobeguButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegufriBodabeBibubobufrilus" eSuperTypes="//FaBinulauNulauDalus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dicio" eType="//BrAuBegubeBubudanulAugugusLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndaboboguBogugusGusNulauTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugubobedadabuBuLius" eSuperTypes="//BeNulAudabubiBegubobiDaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBobidaGufriboNulauBonus" ordered="false" eType="//Dafribubogusbibibelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EufriFribogusfrigusaubobuGulus">
    <eLiterals name="Didadafritor"/>
    <eLiterals name="BabibibufriDaLius"/>
    <eLiterals name="Alnulaububebudacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DibuNulauTin" instanceTypeName="typeAnbigugusboFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuboDaFribuBobegufriNus" eSuperTypes="//DoNulAufrifribugusboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedaBoBonulaugusbigubulius" eType="//DafriBodagufriGuGusBoGuboTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daNulAufribigusdafridaNulius" ordered="false" upperBound="-1" eType="//EbiFridabonulaubucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuboDanulaubibebobogusBecio" eSuperTypes="//EudaFribibofrigusBobebuGuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGububeBiGugudanus" ordered="false" eType="//BefribuguGusbiBuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedafrifribiGuBobofrinulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duBeguBigusGunulAunulEs" eType="//BraugusGuBebogusBobuBuNulauNulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabofrigubeBebeBoGusbefridafrilius" instanceTypeName="typeDoGusboBigutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EGusdabudanulaucio" instanceTypeName="typeBraugusBiboDabeBobecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DububebeGuBibubiguBubufribidalus" eSuperTypes="//DabugusGusbiguGusaunulAuguboLus //DobeGusGusnulAuGusnus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubiBubigusaulius" instanceTypeName="typeBagusDanulauFriNulaugulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiguDaNulauBiBeBiDacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulaugusnulaunulius" eType="//EGusdabudanulaucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufribububugusAuFrigusGusBoLus" ordered="false" upperBound="-1" eType="//BegufriBodabeBibubobufrilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBeboBobegubegusAulius" ordered="false" eType="//DubugububuBofribitus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubogudabubunulAuDabibebudaBees" eType="//DigubunulAuLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aguBodabibuguBiFries" ordered="false" eType="//Efribunulaubibinulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGugubibeGusGusNulAuFriLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulAububiBiguDadanus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubeGuguGusbubebigusNulaulius" ordered="false" eType="//AuBiBeBelus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dodabegubufriBubotin" ordered="false" upperBound="-1" eType="//BraugusboDafrigusgubudaBiFrigulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBoGuBoNulaubunus" eSuperTypes="//EubifribeDaNulauBeBeGusBibuGuBetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibeGusAunulaubefribegudaBuGustor" ordered="false" upperBound="-1" eType="//BrAuBenulAugusaudaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BifrigusbeBubebodagudafrifriboGutus" instanceTypeName="typeAlnulaubofribunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABeGusbofrinulaubeBogutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubonulAugubibobebobebibibutin" ordered="false" eType="//AufridabuFriDaBugubedagustor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebebuBegusbubuFriBuNulAubiNus" ordered="false" eType="//DaBoBigubenulaugusdaDagucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogusGunulaubebeGuslus" eType="//BrAuBegubeBubudanulAugugusLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubonulaugusBoBogusfribilus" abstract="true" eSuperTypes="//AuBiBeBelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldagusbegubudaBeguNulaulus" upperBound="-1" eType="//Fabobubifridabulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAubebefricus" abstract="true" eSuperTypes="//DabudafribofribegubuDabetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldafribiboBibedaBugusBubiguboDaCio" abstract="true" eSuperTypes="//BabibigugusgubiGusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabobofriGusbiBegusbuTus" eSuperTypes="//EgubeGudabibegusgusaudafribonus //ANulaufribuBebodaBegubogusbobicus //AldabuBefrifriDadaBogusbibuDaBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFribuBegusNulAuNulaubebebuBues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibinulAubiguBububoDabiGuses" ordered="false" eType="//DabiBofrinulauBiguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidanulauguNulauBunulAubibibogusBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAuBoDaboBiGubiDafribugusNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anboGugudagunulaubinulaugusbotor" ordered="false" eType="//AngubegububiGusgutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbidaBoGudadagugusIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbiBigusnulaubeBiEs" eType="//EufriFribogusfrigusaubobuGulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BefriboBefrigusaugusbeTor" eSuperTypes="//BaboBuBudadabefrifriBiEs //AnBoBodacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiFriNulaunulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBeBobodadagubunulAulus" eType="//BigusdabebebuBubolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabebeFribiBiGunulAufriBetus" eSuperTypes="//BabibigugusgubiGusTor //DuBuNulaubogubolus //FaGugubibeGusGusNulAuFriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBodafribuDaguGubuFrinulauboTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabogunulauFriBibobiDaFricus" eType="//DodabuNulAubenulautin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DadaNulaucio" eSuperTypes="//EuNulAuBiFridabutin //Fabobobedafrigubolus //AlNulauBubobodaFribubucio //FabobofriGusbiBegusbuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbiGusgusfriNules" eType="//BaFribuBegusNulAuNulaubebebuBues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="efribegusBuNulauguBegunulAuGuLus" eType="//EdaNulaunulauDadaNulauguLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubegugusbuBubudaGusNus" eSuperTypes="//DidabegugusnulauBiFriguBeGucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdabinulauguGusbotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusBonulaubogusboGudacio" ordered="false" upperBound="-1" eType="//EnulaudagusfrifriBuBubutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudabobiGusfrifribenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albofrigusbunulaubuLus" ordered="false" upperBound="-1" eType="//BibudaGuFridagubiGusGusbifrilus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="didafriGusguses" eType="//AnbuFriBunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBobubebunulaugugusGues"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BagugusnulaunulAuBeTin" instanceTypeName="typeBraugufribiBebogusbunulAutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBuBebeDaNulAunulauGusDabiguscio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobobucus" eType="//Dodabufrilus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAubidabodaguBufrigusbebilius" abstract="true" eSuperTypes="//Fabobubifridabulius //DubudagufriBifriNulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudagusBeguDabucus" ordered="false" eType="//AlAubefribobulius" eOpposite="//AlAubefribobulius/bebocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriFriDabeGufriDaes" eSuperTypes="//DubifrifriBefriGucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBeboguGusGudabuFricus" eSuperTypes="//AlAubefribobulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebotus" upperBound="-1" eType="//EuboBogusbudafrigutor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufribefribibofriBogusaubuGusbibubobeCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abuDaes" eType="//AubiBubigusaulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafribufribenulAuGunulaufrilus" eSuperTypes="//DagusBoBebiFribobuBitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusbobunulAubofribogubebubuTor" ordered="false" eType="//DadadaBiBifribedabonus" eOpposite="//DadadaBiBifribedabonus/dufriDaGuguNulauGububitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBegusFrinulaufribofrinulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebegusdafriCio" eType="//BegufriBodabeBibubobufrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugudaBelius" eSuperTypes="//BegufriBodabeBibubobufrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baNulaugusNulAuboboDaBoTin" ordered="false" upperBound="-1" eType="//DoNulAubiBoboNulAubitus" eOpposite="//DoNulAubiBoboNulAubitus/albeboBudagusBegubiboBiguTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aDabedaFrigutor" upperBound="-1" eType="//AubigusAulus" eOpposite="//AubigusAulus/beNulauBugubiBuBubigusdalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBoBuBobuGusboBinulAucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbofribudabebedaFrigusbeBebetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AboguBebifribibicus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabobufridabibiGusBeguBuguscus" ordered="false" upperBound="-1" eType="//FaGugubibeGusGusNulAuFriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobedadanulaububuDabobuTor" abstract="true" eSuperTypes="//AuBegusFrinulaufribofrinulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdaBibeboBiFribobeboBugues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibegusfrifribeBeGuTin" eSuperTypes="//AnauBobofribuBodaboboGuDacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudabobonulaudabudaNus" ordered="false" eType="//EnulaudagusfrifriBuBubutin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibidanulauNulaudaDanules" ordered="false" upperBound="-1" eType="//Bagusnulaugubufrilus" eOpposite="//Bagusnulaugubufrilus/bedaDagusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubibiBoFrinulauBeBecio" instanceTypeName="typeBabeBobobefriFrifriFrigububenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubeNulaudaDagudagusBies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafribidafriguFridadabeguDabegustus" eType="//EuNulAuBebibibubobonulauTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DadadaBiBifribedabonus" eSuperTypes="//AnauBobofribuBodaboboGuDacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufriDaGuguNulauGububitus" ordered="false" upperBound="-1" eType="//DafribufribenulAuGunulaufrilus" eOpposite="//DafribufribenulAuGunulaufrilus/egusbobunulAubofribogubebubuTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubunulaunulauCus" ordered="false" eType="//AunulauBoBebeBucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlFridaNulauDagusfriGulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBubegusNulaufribibiFrigusnus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabogugusCus" instanceTypeName="typeEbeNulAunulaubeNulaugustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBeBegusBegudanus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibegudanulaunulAunulAuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAubuGusbeGuBefrigusCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digubudaNulauGuFridabebebuNus" ordered="false" eType="//Bagusnulaugubufrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusdafriboBobodaBicus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fadafriCio" eType="//EugubibebufriBonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaboNulaubifribebicio" eSuperTypes="//DubuGububebugusBoBubicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriboBedaBuboFribiNulauBetor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duGugunulaubebetin" eType="//DigubunulAuLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbuGuFriDaDanulAuBinulAutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbugufribuNulaubudagulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubiNulaufribogusGusbutus" ordered="false" upperBound="-1" eType="//BabiguBenulauGusaubotin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bagunulautin" eType="//EufriFribogusfrigusaubobuGulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaboFriBubogusbefriNulaubitor" instanceTypeName="typeDiBodacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABoGubiGustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBebeBegusfriDaFrifribibilus" ordered="false" eType="//AlAubefribobulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBubifrifribebutor" eSuperTypes="//EdabinulauguGusbotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibobelus" upperBound="-1" eType="//AugudaBelius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulauDagusBeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGuboGusBudabobeBigusbelus" abstract="true" eSuperTypes="//DubudagufriBifriNulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlAububuBecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibenulAuGusBoTor" eType="//DoFrinulaugusnulAugubeBoGuGugusbocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusnulauBoguDabofribuBeNulIus" eSuperTypes="//DiGugusnulaubobotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulauBodabiDagusbibeBedacus" eSuperTypes="//AnFrigufribodadabeBibonulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusboguGudabibutus" eType="//DobeGusGusnulAuGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfrifribuBonulEs" eSuperTypes="//DabugusGusbiguGusaunulAuguboLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biFriGubinulAubuBodaCus" eType="//EugubibebufriBonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BibubiBogusAuBiNulAutus">
    <eLiterals name="DaFribodafriBeboboFribebifriFriFrigusCus"/>
    <eLiterals name="DabiboGusfribogusbubunus"/>
    <eLiterals name="AnFriBibuDanulauBubofriTor"/>
    <eLiterals name="AfribeBenules"/>
    <eLiterals name="BiDafriBonulauNulaububelus"/>
    <eLiterals name="AnBobobubebegucio"/>
    <eLiterals name="DiguButus"/>
    <eLiterals name="EnulAubodaboGusButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulauBiboGuBobofribuBudabobibibebugugusdacio" eSuperTypes="//BebibunulaubeDabuGuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBebunulaudaNulauboFriGubobonulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBibogusGusdabiGugusbiBinus" eSuperTypes="//DuboDanulaubibebobogusBecio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alBubebiDaBebubegugubeGusIus" eType="//AugugusnulauboDanulaugunulAuBiNus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGubugusAuDaboGuCus" ordered="false" upperBound="-1" eType="//DoFrinulaugusnulAugubeBoGuGugusbocio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAudadabiBicio" eType="//BiFridadaBofriFriBuguBeLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabebifriguBedaBigugugulus" eSuperTypes="//AbidaGugusbidaboBolius //AnBibubibubedatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albobuguLius" ordered="false" upperBound="-1" eType="//AnulAuFribiboGuguGunulauGusbobugulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiFridagusbubibiguBudadacus" eSuperTypes="//DufriboBedaBuboFribiNulauBetor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBunus" eType="//EugubibebufriBonus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBodabibobebiBeBibicus" instanceTypeName="typeDanulaugusbobubobebiNulaunulaudalus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BrAuguGusBigubifriBiGusaubiGulius">
    <eLiterals name="DunulAugudagusFribuTus"/>
    <eLiterals name="DiFribebuNulAuGusaulius"/>
    <eLiterals name="Aubebebebubutor"/>
    <eLiterals name="Bebonules"/>
    <eLiterals name="FaguGubiBoDabobocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGuGusBuBobuGusbobebuGulus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABedabufriFribufrigunulAuBilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauFribiDabibiFribeguBeBocus" eType="//Babebogusdabedator" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EgusdagusGuBuBeBelius">
    <eLiterals name="DodadabeBogusBebobububofribuboFritor"/>
    <eLiterals name="DigusbebufriboboNulauguBitin"/>
    <eLiterals name="Algusbugunus"/>
    <eLiterals name="BraugusbinulAubiFribenulautor"/>
    <eLiterals name="EdaFrinulaubebeDacio"/>
    <eLiterals name="AugunulauguBeNulAubufritin"/>
    <eLiterals name="AldadaBebigubibogudabutin"/>
    <eLiterals name="EnulAufriguslus"/>
    <eLiterals name="BigusbogububigusBitin"/>
    <eLiterals name="DobeboFriBibiboes"/>
    <eLiterals name="DifrigusbigusbofrinulauCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodabugusAuGusBobobidalus" eSuperTypes="//FabebibofribenulaubebububoLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abigusBeBubidagusBibuBues" eType="//DabubeboGusbibidaBeBeTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebuBebugububoBitus" instanceTypeName="typeEDadanulaudagubobebeDafribuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFriDafrigunulaububocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubeFriDaFriFribofriDabocus" eSuperTypes="//FaGugubibeGusGusNulAuFriLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braunulAubugusgusaubuBigulus" eType="//EdaNulaunulauDadaNulauguLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabodagusbiboCus" instanceTypeName="typeDiBunulaubedaGusbiBiGulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubedaGusdadabebeGuscus" eSuperTypes="//Bagusnulaugubufrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifridafriBogusius" abstract="true" eSuperTypes="//FaGuguNulaugusbebegusFriguboLus //DoBoGuBoNulaubunus //FabobofriGusbiBegusbuTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibinulauGusbugubibefriDaEs" abstract="true" eSuperTypes="//AgusbinulAugusbeBuDagusFriTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebudaboGubetus" upperBound="-1" eType="//AubiBubigusaulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufribobofribibibedacus" ordered="false" upperBound="-1" eType="//BrauBugusGubugusBibeTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EdaGusAubuNulauguFrifricio">
    <eLiterals name="EbeBuBugudabebubonulius"/>
    <eLiterals name="DafrigunulAuFrigusfrifrinulauDaBiBelus"/>
    <eLiterals name="Aubugufribububebolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeboBufrifrifrinulauBeBofricio" eSuperTypes="//DabudafribofribegubuDabetor //DububebeGuBibubiguBubufribidalus //EufriNulauBeboBiguBebogutus //DoNulAufrifribugusboes"/>
</ecore:EPackage>
