<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albetor" nsURI="http://hub.de/rcore/examples/albetor" nsPrefix="pOW">
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulaubegugusBebufrinulauCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBuBufriBiNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aubibugufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoboGudaBudaBoboboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulAuBofribiBeNulaufriboNus" ordered="false" upperBound="-1" eType="//Aubibugufritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaDaNulAufrifriFritor" instanceTypeName="typeDoBoboBoBubiGubogugusdabuFriboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="EboBufriFrinulaunulAulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBoBebofricio" eType="//DoboGudaBudaBoboboes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubibugusguGusboGuBedator" ordered="false" upperBound="-1" eType="//AuBuBufriBiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusbuBiDabobobebifritus" eSuperTypes="//EboBufriFrinulaunulAulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daFridadabonulaugudagunulaulus" eType="//DaDaNulAufrifriFritor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraufriDabeGufriGusDagutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlguBobibegusdabocio" instanceTypeName="typeFaGunulaufribunulaufribunulaugulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabefriBobobugusbiGusnulAuBedaBoBebiLus" eSuperTypes="//DoboGudaBudaBoboboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusfriGuBedabecus" ordered="false" upperBound="-1" eType="//EboBufriFrinulaunulAulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabefribonulaulus" upperBound="-1" eType="//AuBuBufriBiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaFribuFribiNulauboBoTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugugusguBogudanulIus" eType="//Aubibugufritus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudabuFriBegufribibenules" ordered="false" eType="//AuBuBufriBiNus"/>
  </eClassifiers>
</ecore:EPackage>
