<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bifribitus" nsURI="http://hub.de/rcore/examples/bifribitus" nsPrefix="iUjw">
  <eClassifiers xsi:type="ecore:EClass" name="DiFridabiboLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBifriBinulaufriDaGusgutin" ordered="false" eType="//AnbubugugubunulAugusBubebidatus" eOpposite="//AnbubugugubunulAugusBubebidatus/baBebefribidaLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbubugugubunulAugusBubebidatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBebefribidaLius" eType="//DiFridabiboLus" eOpposite="//DiFridabiboLus/duBifriBinulaufriDaGusgutin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabebiBedabiBeBebebugunulius" ordered="false" upperBound="-1" eType="//DoBifribegusgusbeGusBoDadalus" eOpposite="//DoBifribegusgusbeGusBoDadalus/augubunulaugusbuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabibuFribububetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebidabonulius" ordered="false" eType="//DiFridabiboLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagusnulaugusAububeguCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuNulaugubigusFriBebogunulius" instanceTypeName="typeAlbudaBubobuboLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Algusnulaufrigusguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudaBodadafrifrifriTus" eSuperTypes="//AnbubugugubunulAugusBubebidatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulaubucio" eType="//DuNulaugubigusFriBebogunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaGubebuBebobedaBecio">
    <eLiterals name="DoGunulAuguboNulAunulIus"/>
    <eLiterals name="AngubonulaunulaufriguBibibubecio"/>
    <eLiterals name="DiBibuBunulAunulaubibigugusbobiTor"/>
    <eLiterals name="EfriguBudabocio"/>
    <eLiterals name="DubuBoBinulauBuDafriFrinulaulus"/>
    <eLiterals name="AlbeNulaugustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dubitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobefribegusBubugububuGugulus" eSuperTypes="//Algusnulaufrigusguscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efrinulaubodafriDaGusBonulauTin" ordered="false" eType="//DiFridabiboLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBifribegusgusbeGusBoDadalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augubunulaugusbuCio" upperBound="-1" eType="//AnbubugugubunulAugusBubebidatus" eOpposite="//AnbubugugubunulAugusBubebidatus/fabebiBedabiBeBebebugunulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAufriFribeBebibobeLus" eType="//DuNulaugubigusFriBebogunulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulAuBofrinulauDabifriGutor" upperBound="-1" eType="//AuFrigugusBobitin" eOpposite="//AuFrigugusBobitin/abebigusboBifriBoGuBeBugubonus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfrifriLus" ordered="false" eType="//DibenulaudaGuscio" eOpposite="//DibenulaudaGuscio/biGusBinulaunulAubifrigusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdaBegusgusGuBeBefritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubenulauboCus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BaBobobeBunulauCio">
    <eLiterals name="DaGubinulAuBenus"/>
    <eLiterals name="AlboguBibinulaucus"/>
    <eLiterals name="AgusbiDadabogububenulAucio"/>
    <eLiterals name="BibebuDaBebibetin"/>
    <eLiterals name="BegusaunulAugubobibilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBodaBodaBibebeBibotin" eSuperTypes="//DiFridabiboLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidanulAuguGuFribuBogusDalius" eType="//DuNulaugubigusFriBebogunulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BegubunulAuBeGusNulaubifribubonulAucio">
    <eLiterals name="BibeBenulAuNulIus"/>
    <eLiterals name="DabigusaubudagusbuTin"/>
    <eLiterals name="AguguBegusaugugusGusgusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EufriBubobinulaudabetus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAugusboBees" instanceTypeName="typeDoNulaunulAubibobobenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusnulauBedabedabebibugustus" eSuperTypes="//DobefribegusBubugububuGugulus //EufriBubobinulaudabetus //EdaBegusgusGuBeBefritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andabigusbodabifrinulautus" ordered="false" upperBound="-1" eType="//DoBifribegusgusbeGusBoDadalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuFrigugusBobitin" abstract="true" eSuperTypes="//DiFridabiboLus //FaBodaBodaBibebeBibotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abebigusboBifriBoGuBeBugubonus" ordered="false" upperBound="-1" eType="//DoBifribegusgusbeGusBoDadalus" eOpposite="//DoBifribegusgusbeGusBoDadalus/benulAuBofrinulauDabifriGutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGuboGubobefriBeNulAutor" eSuperTypes="//Dubitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbobidabiGusbicus" eSuperTypes="//BeGuboGubobefriBeNulAutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobeTin" eSuperTypes="//FabibuFribububetus //AnbubugugubunulAugusBubebidatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulaunulaugusbobofrifriBebiBoCio" ordered="false" eType="//DobefribegusBubugububuGugulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifriGuNulAuBubuguBiGusBuGustor" eSuperTypes="//DoBifribegusgusbeGusBoDadalus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabobedabufriLius" eType="//BaBobobeBunulauCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBogusnulauBibetus" abstract="true" eSuperTypes="//BeGuboGubobefriBeNulAutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndaBenulaubiTus" eSuperTypes="//DubenulauboCus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AgusNulaubobugusbebuGusTor" instanceTypeName="typeBeFrinulaugubeNulAubegusdaCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibenulaudaGuscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusBinulaunulAubifrigusius" ordered="false" eType="//DoBifribegusgusbeGusBoDadalus" eOpposite="//DoBifribegusgusbeGusBoDadalus/anfrifriLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulAuGusbuguBibuNulEs" ordered="false" upperBound="-1" eType="//BraudaBodadafrifrifriTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braugusauboBilius" eType="//BaBobobeBunulauCio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuDagusdafribenulius" eSuperTypes="//Dubitin //DoBifribegusgusbeGusBoDadalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaunulAufridaGusGuBecus" eSuperTypes="//EufriBubobinulaudabetus //DobeTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulauNulaubinulaudaBidatus" ordered="false" upperBound="-1" eType="//FaBodaBodaBibebeBibotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgubogubofrinulauGudanus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulaufribiBubuGusbibetin"/>
</ecore:EPackage>
