<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="braubibogugustin" nsURI="http://hub.de/rcore/examples/braubibogugustin" nsPrefix="j">
  <eClassifiers xsi:type="ecore:EClass" name="FabobonulAudabiGuboGuses"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubuFribeboBubiguTin" instanceTypeName="typeDuDaboBeguboBibibeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauBudanules" eSuperTypes="//FabobonulAudabiGuboGuses">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuboBufriBotin" eType="//EubuFribeboBubiguTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebebedabebiBebobuBefricus" eSuperTypes="//FabobonulAudabiGuboGuses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGusBogunulauGunules" ordered="false" eType="//FabobonulAudabiGuboGuses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digugufribuBufridanulius" ordered="false" upperBound="-1" eType="//FabobonulAudabiGuboGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabegusGuboBedabuGusBidaCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biNulaubenulAubecio" eType="//EubuFribeboBubiguTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AndadaGusdaBufrinulaugubutin" instanceTypeName="typeDabobebufricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlDagusbiBiDabefrigues" eSuperTypes="//BabegusGuboBedabuGusBidaCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eGubuBubedaGuBuDaBoBeLus" eType="//AndadaGusdaBufrinulaugubutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABibonulaubugubuCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusauBogusBeBiTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusnulAubefriGusBuLus" ordered="false" eType="//BanulauBudanules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugubobeGusbigusCio" ordered="false" eType="//BebebedabebiBebobuBefricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BebiboNulaugunulauBibenulIus">
    <eLiterals name="DadaBibonulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibinulaunulauGunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibogusfriNulaufriDabiGusbuguBebuEs" eSuperTypes="//FabobonulAudabiGuboGuses //BanulauBudanules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubudafriDacio" instanceTypeName="typeBenulaufriLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusbubuguBoguBucio" eSuperTypes="//DibinulaunulauGunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBibuBobubuBebuBinulIus" eType="//EubuFribeboBubiguTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodanulauguNulaugusgugusbitus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BafrinulaudagusgubedaBoGusbeGusNulAunus" instanceTypeName="typeDufribegusbibubedafrinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBuGusgusBoBiboDaBuDagubuBebutus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibuNulAuGubobees" eType="//AndadaGusdaBufrinulaugubutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibigusbidabebeBegubetin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabigusGusbuBuguBubifrigusGusgugusBilius" instanceTypeName="typeAnfrigusbeFribicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFridafribibeBuBiFriDabogunus" eSuperTypes="//BibogusfriNulaufriDabiGusbuguBebuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diboBobuGusfribudaDadanulius" ordered="false" upperBound="-1" eType="//AgusbubuguBoguBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifrifrinulAudaBodabugusbufriguBolius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuGusgugusBibeGugustor" instanceTypeName="typeAuBoBebugubogusbobibugunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbegugusNulauGusfribeBibutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnFrinulauGubibodabiCus" instanceTypeName="typeAnnulauBotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusdaFriBububecio" abstract="true" eSuperTypes="//BebebedabebiBebobuBefricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babefrinulaugubidanules" ordered="false" upperBound="-1" eType="//DifrifrinulAudaBodabugusbufriguBolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugunulauDanulauBubobidaTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusgubofribubuTin" ordered="false" upperBound="-1" eType="//BabegusGuboBedabuGusBidaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulaugububugusbunulAubeLus" eSuperTypes="//DibinulaunulauGunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBeguguNulAugusGusAuDaBofrilus" eSuperTypes="//DoNulaugububugusbunulAubeLus //DuBuGusgusBoBiboDaBuDagubuBebutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaufrifriDaboFrigudabudaGuBolus" ordered="false" upperBound="-1" eType="//DifrifrinulAudaBodabugusbufriguBolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBugubebebiNulius" ordered="false" upperBound="-1" eType="//DuBuGusgusBoBiboDaBuDagubuBebutus"/>
  </eClassifiers>
</ecore:EPackage>
