<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="an" nsURI="http://hub.de/rcore/examples/an" nsPrefix="ksZ">
  <eClassifiers xsi:type="ecore:EClass" name="Braubegusbifrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugugufridagugubotor" eSuperTypes="//Braubegusbifrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anFrifrigusBodaboGusAubucus" ordered="false" eType="//AgububifridaguBibobeTin" eOpposite="//AgububifridaguBibobeTin/dufriDaGusauGusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiDadanulauBetor" instanceTypeName="typeAnBuGubuGusaubibubigubutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusauGusbudabidabiNulauTin" eSuperTypes="//Braubegusbifrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgububifridaguBibobeTin" abstract="true" eSuperTypes="//BrAugugufridagugubotor //EugusauGusbudabidabiNulauTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufriDaGusauGusius" ordered="false" eType="//BrAugugufridagugubotor" eOpposite="//BrAugugufridagugubotor/anFrifrigusBodaboGusAubucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBobeboBunulAubiguTus" ordered="false" upperBound="-1" eType="//EugusauGusbudabidabiNulauTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBuBobotin" ordered="false" eType="//Braubegusbifrilus"/>
  </eClassifiers>
</ecore:EPackage>
