<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="da" nsURI="http://hub.de/rcore/examples/da" nsPrefix="om">
  <eClassifiers xsi:type="ecore:EEnum" name="AlGugusbofrigusgusfricus">
    <eLiterals name="Dogubutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBobobeBobeDagusbotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubodabebegusBibulius" eSuperTypes="//DiBobobeBobeDagusbotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulaubuDanulauboBilius" ordered="false" upperBound="-1" eType="//DiBobobeBobeDagusbotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubuDabogusfriNulauTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibuBoBebucio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubobobogustin" ordered="false" upperBound="-1" eType="//DubuDabogusfriNulauTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboBoboBudagusbiBenulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagubiDaBobiFridaguNulAuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebegusfrigubibufriNules" abstract="true" eSuperTypes="//BiboBoboBudagusbiBenulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBifribiBonulaunulAubiGuscus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebifribuboes" eType="//AlGugusbofrigusgusfricus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Fanulaufribebubitor">
    <eLiterals name="FagusBoboBeBidafribidanus"/>
    <eLiterals name="BabunulauGubegusius"/>
    <eLiterals name="AfriboFridadaNulAuTor"/>
    <eLiterals name="AuguBufriBoGusnulauBegusnulAugusLius"/>
    <eLiterals name="DaNulauDaNulauLus"/>
    <eLiterals name="BibidaDabinulaudacus"/>
    <eLiterals name="AufrifrifribubeBubulius"/>
    <eLiterals name="FabobibuguBuGubobetor"/>
    <eLiterals name="EbuBobuBedaGusgusBonus"/>
    <eLiterals name="BraufrifribebonulAudadadabinus"/>
    <eLiterals name="BaFridaNulAuBugudagusGufrigusfrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BigusDabugufriDabenulAubenulAucus">
    <eLiterals name="FanulauboDaBedaBoNulAuTin"/>
    <eLiterals name="DigusgusgusbeBibuguLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bidanus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diboBeBebeBugusbubegusLius" eType="//BigusDabugufriDabenulAubenulAucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Braugufrifribitus" abstract="true" eSuperTypes="//DiBobobeBobeDagusbotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DudaguBifriBuGuDadatin" instanceTypeName="typeFaDabuBigububibunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBeDagusNulAuGusbebidafries" eSuperTypes="//AuBifribiBonulaunulAubiGuscus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albibedaguBubiBoLus" eType="//Fanulaufribebubitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BagubobobodaFribifriBuBuTin" instanceTypeName="typeDugusdaBifrigutus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBodagusfrinulauNulAubiBiboLus" instanceTypeName="typeDoguFriDanulAubufriBobefriNulaugusTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubugusdabobegusAunulaugunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABeNulAuFriTus" abstract="true" eSuperTypes="//BiboBoboBudagusbiBenulautor //AnBeDagusNulAuGusbebidafries"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aunulaugusbigubonus" eSuperTypes="//AubodabebegusBibulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubeguGudaBinulauNulauNus" eType="//AlGugusbofrigusgusfricus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGusDaguDaFrifrilius" eType="//BebegusfrigubibufriNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaDaboDatin" abstract="true" eSuperTypes="//BebegusfrigubibufriNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aubufribedabonulaubegugubifritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baNulEs" ordered="false" eType="//AnBeDagusNulAuGusbebidafries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abiguBubuBotin" ordered="false" eType="//BiboBoboBudagusbiBenulautor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babedaDaBoBogusbocus" eType="//AuBodagusfrinulauNulAubiBiboLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibeNulauBibifridaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diDaBebigusDaLus" eType="//Bidanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BabuGuguBuFriNulAubogugusFrigubeBeNus">
    <eLiterals name="Eudabibofrigusnus"/>
    <eLiterals name="AnulauGusdabucio"/>
    <eLiterals name="FafriDaBebuFriGusboNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulAubefridaBeBuDaBubifribiLius" abstract="true" eSuperTypes="//Aubufribedabonulaubegugubifritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulauBebeguBinulAuDatin" eSuperTypes="//Aunulaugusbigubonus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dinulaunulaubibebilius" instanceTypeName="typeBrAubibeBiBibuboDaguEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlnulauNulAubenulauguBuCio" instanceTypeName="typeAlbugufribonulaububoGuFriguNulaufricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusBobeguGunulauBebunulautor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abibeNulaubuFriGubiTus" ordered="false" eType="//AnulauBebeguBinulAuDatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abugubububugustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulAuFriTor" eType="//AlGugusbofrigusgusfricus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babububiGusBugusdabidaBetus" upperBound="-1" eType="//BibuBoBebucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdagunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abunulaubetor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusbugusNulAugusBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBugusGusnulautin" eSuperTypes="//DibeNulauBibifridaes //ABeNulAuFriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusbobefriBugusGubibitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaDabebubeDafribobocio" ordered="false" upperBound="-1" eType="//EgusbugusNulAugusBotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeguNulAufries" eSuperTypes="//FagubiDaBobiFridaguNulAuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabigusbudacus" ordered="false" upperBound="-1" eType="//FagubiDaBobiFridaguNulAuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnBugudabeguses" instanceTypeName="typeDoboGufrifriFriBuBefriGusbitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbufriNulaubobegulus" instanceTypeName="typeBegusgusaubugusauGuFritin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraunulaubegusbibeboDanus" instanceTypeName="typeEugubugucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabiNulauboboBibiBitor" instanceTypeName="typeBibuGuNulaugusBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulAugusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubonulauFrinulAubenus" eSuperTypes="//DiBobobeBobeDagusbotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BidabefrigusaudafribeDaDacus" instanceTypeName="typeAlbibogusgufridabifriboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabibeFriDaDacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebobogusgusbobuBoFridafriBiguscus" ordered="false" upperBound="-1" eType="//Bidanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBeGuGusbubufriFriFriNulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubufriNulaubeFriFrinulAuNus" ordered="false" eType="//BrAunulaubeGusbonulaubiGuCus" eOpposite="//BrAunulaubeGusbonulaubiGuCus/doNulauBuFridaBenulauBiGusbeGucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaubinulauguBilus" abstract="true" eSuperTypes="//AubodabebegusBibulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Angusgusgusbugusgustus" eSuperTypes="//BrauBugusGusnulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babuguBoBeDadaDanulaucio" ordered="false" eType="//AubodabebegusBibulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauguNulauGusbiFrigusAugusauLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dodagusbebinulaufriGucus" ordered="false" upperBound="-1" eType="//Aubufribedabonulaubegugubifritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGusnulAugusBebenus" abstract="true" eSuperTypes="//AnBeDagusNulAuGusbebidafries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulaubeGusbonulaubiGuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duDabubeBibibiguBuguguslius" ordered="false" upperBound="-1" eType="//BenulaubinulauguBilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doNulauBuFridaBenulauBiGusbeGucio" ordered="false" eType="//DoBeGuGusbubufriFriFriNulEs" eOpposite="//DoBeGuGusbubufriFriFriNulEs/brAubufriNulaubeFriFrinulAuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusboGunulAuBuGusbiTin" eSuperTypes="//AuBifribiBonulaunulAubiGuscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriBebegunulAugusfricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBugudabebebeGubiGuguslius" eSuperTypes="//Braugufrifribitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didagusfribunulaugusBoboFribicio" ordered="false" eType="//BebegusfrigubibufriNules"/>
  </eClassifiers>
</ecore:EPackage>
