<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albegufrinus" nsURI="http://hub.de/rcore/examples/albegufrinus" nsPrefix="VWW">
  <eClassifiers xsi:type="ecore:EEnum" name="DubuBegubues">
    <eLiterals name="AnfribibofribeBifribibobeBibucio"/>
    <eLiterals name="EubibenulaunulAuBobeBiDaes"/>
    <eLiterals name="DinulauGusbugusDator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedagubobofriBoes" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusFribiboes" eSuperTypes="//BedagubobofriBoes"/>
</ecore:EPackage>
