<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bibobufrigusius" nsURI="http://hub.de/rcore/examples/bibobufrigusius" nsPrefix="sOSgw">
  <eClassifiers xsi:type="ecore:EClass" name="AnbebeBoGusBifriFribuBeGusAuCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DinulaubebogudagusGudafribeDalus">
    <eLiterals name="BedanulauGusbugusius"/>
    <eLiterals name="AuboGuFribebibedaBuDagusfribebegusfricus"/>
    <eLiterals name="AngusgunulauguNulaugusButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubuGuBeGuFribobuBiguslus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EfridafribuDanus" instanceTypeName="typeDububunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFrigusdabibuboNulaunulAuBobifrifridacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babinulaufriBobeGugusBolus" upperBound="-1" eType="//DadabefribigusaubufriFribibogusBibiNulius" eOpposite="//DadabefribigusaubufriFribibogusBibiNulius/brAububonulAubenulaubeBies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAubiBeDanulauGuGugustin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="be" upperBound="-1" eType="//FaFrigusdabibuboNulaunulAuBobifrifridacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubobufribiNulaunulAugudafriGuslius" abstract="true" eSuperTypes="//DunulAubiBeDanulauGuGugustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguDaBuFricus" upperBound="-1" eType="//AubuGuBeGuFribobuBiguslus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGufriFribuDafribuGusbiButin" ordered="false" eType="//BrauguBoBuBedadabobubigunus" eOpposite="//BrauguBoBuBedadabobubigunus/bifriboDaFriDanulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DobeBegusNulaubiguNulauGusboGusius" instanceTypeName="typeBabibiGusbibiNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dafrifribenulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefribonulauBoGusnulAutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubebeDaGuBubufriLus" ordered="false" eType="//FaFrigusdabibuboNulaunulAuBobifrifridacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DagusAunulaugubidadanulAunus" instanceTypeName="typeDiBubifriguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaunulAubinulaubogusDaCus" eSuperTypes="//FaFrigusdabibuboNulaunulAuBobifrifridacus //Dafrifribenulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifridaFriGusGufriDacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augusGuDalius" eType="//EfridafribuDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiDabuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="afriDabubuGugutus" ordered="false" upperBound="-1" eType="//DunulAubiBeDanulauGuGugustin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBeBogusGusGuBinus" eType="//EfridafribuDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBibutus" eSuperTypes="//AnbebeBoGusBifriFribuBeGusAuCus //BefribonulauBoGusnulAutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubobidabebufrigusNus" ordered="false" eType="//DunulAubiBeDanulauGuGugustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BibibiBonulAuFritin" instanceTypeName="typeAnBogusAugusGubebibibunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAubeDagusdaDaFriDaes" eSuperTypes="//DifridaFriGusGufriDacus //DunulAubiBeDanulauGuGugustin //Dafrifribenulaucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alGunulaubiGubuGusDafribonulaubutus" eType="//EfridafribuDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedabubifriBuNulaubofribonus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alaugufritin" eSuperTypes="//BenulaunulAubinulaubogusDaCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebeNulaugusBubebuDabugustus" eType="//BibibiBonulAuFritin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubeDabibegubicio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBeGusGusbibodafrifrinulaunulius" eType="//DobeBegusNulaubiguNulauGusboGusius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eDaFribidaLus" eType="//EfridafribuDanus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulAugufrigusnulauBegustus" ordered="false" eType="//AubuGuBeGuFribobuBiguslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAubugusgusboguCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulauDafrifriGubenus" upperBound="-1" eType="//BedabubifriBuNulaubofribonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eububobebicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagufrigusBoGusdalus" abstract="true" eSuperTypes="//AnBibutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagubobiGusbitin" ordered="false" eType="//DaBoBibibobebigunules" eOpposite="//DaBoBibibobebigunules/bidaguNulAubibenulaudabobeBebubobugucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusbufriNulauBolius" eSuperTypes="//FaFrigusdabibuboNulaunulAuBobifrifridacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebibobugusBuCio" eType="//DinulaubebogudagusGudafribeDalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebebeNulaudafribiGusBoBucio" abstract="true" eSuperTypes="//Alaugufritin //DifridaFriGusGufriDacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBuGufrinulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGusGugusbonulauBecus" eSuperTypes="//BiBuGufrinulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBoBibibobebigunules" abstract="true" eSuperTypes="//BebebeNulaudafribiGusBoBucio //FagufrigusBoGusdalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaguNulAubibenulaudabobeBebubobugucio" ordered="false" upperBound="-1" eType="//FagufrigusBoGusdalus" eOpposite="//FagufrigusBoGusdalus/bagubobiGusbitin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubeDaBebegusbubodaBotor" eType="//BiBuGufrinulauCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAutin" eSuperTypes="//DunulAubiBeDanulauGuGugustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulauBobiBobobibuGusDabiBigusbucus" eSuperTypes="//Alaugufritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFrigubiNulautin" ordered="false" upperBound="-1" eType="//FabobobeNulAuBuBobenulius" eOpposite="//FabobobeNulAuBuBobenulius/fanulaudaNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnaudaBedadagusFrifriGusBebotin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaubeFrigusNulIus" ordered="false" upperBound="-1" eType="//Dafrifribenulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauguBoBuBedadabobubigunus" eSuperTypes="//FagufrigusBoGusdalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifriboDaFriDanulius" ordered="false" upperBound="-1" eType="//BraubobufribiNulaunulAugudafriGuslius" eOpposite="//BraubobufribiNulaunulAugudafriGuslius/auGufriFribuDafribuGusbiButin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albodagusBies" eType="//DinulaubebogudagusGudafribeDalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBebobebeGusbubuguboDaboNulaubiNus" eSuperTypes="//BrauguBoBuBedadabobubigunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGusbiBubidadabogufrigusbudadaCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DoGuBuNulAutus">
    <eLiterals name="BifriNulaudagubigugusfriLus"/>
    <eLiterals name="BeBogubidaBofriLus"/>
    <eLiterals name="FabibedagufribiNus"/>
    <eLiterals name="AlbidaguGuBoNulAuboBiGubocus"/>
    <eLiterals name="BabububebobogusNules"/>
    <eLiterals name="AlbogusBugusnulauCio"/>
    <eLiterals name="EuBofriboGuguBuDaNulaubutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlauBobuFriFrinulAufricio" instanceTypeName="typeFanulaudaguBeBebiGuBidabobigusfriLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbudabubenulauBicio" eSuperTypes="//BiBuGufrinulauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bebubidagusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaguboGudadaBuNulaunulAuLius" eSuperTypes="//DaBebobebeGusbubuguboDaboNulaubiNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBiBeGuGusgusaugubenus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobebobeGudaLus" ordered="false" upperBound="-1" eType="//DaBoBibibobebigunules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebigunulauboguGusbufries" ordered="false" eType="//FaFrigusdabibuboNulaunulAuBobifrifridacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anulaubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaFribufriNulauFridagutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBibiBugusfriGuBiDanus" eSuperTypes="//EbudabubenulauBicio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dugusFrigusgusNulaugusbiGusbedanus" eType="//AlauBobuFriFrinulAufricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabobobeNulAuBuBobenulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulaudaNulautin" ordered="false" eType="//DonulauBobiBobobibuGusDabiBigusbucus" eOpposite="//DonulauBobiBobobibuGusDabiBigusbucus/alFrigubiNulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbubeBunulaububufritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusboBoNules" ordered="false" eType="//BedabubifriBuNulaubofribonus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogusAuBiBiGusgusNulAulius" eType="//BibibiBonulAuFritin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="betus" eType="//EfridafribuDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulauboGusBugusgububeFriCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebidaBudaGusnulaufries"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodabebugubebegufrigusfrifribubiLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBuNulAubebuFridaBubunules" eType="//DinulaubebogudagusGudafribeDalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulAubiBuDaBudaGuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifriBeboGusboGusbenulaunules" eSuperTypes="//BefribonulauBoGusnulAutin //BrauguBoBuBedadabobubigunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baNulAugusbiBebocus" eType="//DobeBegusNulaubiguNulauGusboGusius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DaNulaubuFribetor">
    <eLiterals name="DuboFridafriBiDaBebunus"/>
    <eLiterals name="BaguBoBobofrinulaugusbedabobugunus"/>
    <eLiterals name="AfribuBuFriBibinulaunus"/>
    <eLiterals name="EuGusbonulaudabubudaEs"/>
    <eLiterals name="EdaNulauFrigusguGunulauBigunulaucus"/>
    <eLiterals name="BinulAubegugubelus"/>
    <eLiterals name="FaboBoes"/>
    <eLiterals name="AndaBugusdaGusfrifrigunus"/>
    <eLiterals name="BraugubobuGutin"/>
    <eLiterals name="Didabebebutor"/>
    <eLiterals name="AufriFriNulautus"/>
    <eLiterals name="AlFribufrigusDaGusNus"/>
    <eLiterals name="DoNulauGufribonulaufribebuBodaNulautin"/>
    <eLiterals name="BeBifriguNulAuBitin"/>
    <eLiterals name="BagububibeBebiGunulauguGuBulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaubibeDaBebibufribefriBigusguDaGusbetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBiGububoguBiboGusGusbebenus" ordered="false" eType="//BefribonulauBoGusnulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaugunulauGusnulAuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibuBebifrifriboGuEs" eSuperTypes="//BaBibiBugusfriGuBiDanus //AnaudaBedadagusFrifriGusBebotin //AlBiBeGuGusgusaugubenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duDaboBubuNulaunulautus" ordered="false" upperBound="-1" eType="//BebidaBudaGusnulaufries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBigusbunulAugusDaTor" eSuperTypes="//DifriBeboGusboGusbenulaunules //DonulauBobiBobobibuGusDabiBigusbucus //Anulaubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifriFribiboBedaBobebonulaugugucio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abefriboDaGusGusGusgubebebobefriboes" ordered="false" upperBound="-1" eType="//BrAubeDabibegubicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaFrigunulaubodagubofrigudaBues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubebiDabubigusNulaudagugusIus" eSuperTypes="//AnAubugusgusboguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbidaBibibuGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadabefribigusaubufriFribibogusBibiNulius" abstract="true" eSuperTypes="//Dinulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAububonulAubenulaubeBies" ordered="false" upperBound="-1" eType="//FaFrigusdabibuboNulaunulAuBobifrifridacus" eOpposite="//FaFrigusdabibuboNulaunulAuBobifrifridacus/babinulaufriBobeGugusBolus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begusgusbobobuguBeBigusGusgues" ordered="false" eType="//AlBiBeGuGusgusaugubenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eubebebobenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbubuBoGusbuBegunulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auboNulAubotus" eType="//DaNulaubuFribetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagudaGudadadaCus" eSuperTypes="//AubebiDabubigusNulaudagugusIus //BifriFribiboBedaBobebonulaugugucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AububuDabiEs" eSuperTypes="//BrAubeDabibegubicio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAudagusAuNulaunulauNus" eType="//DaNulaubuFribetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabibugusBibetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudaGuFrigunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubuGunulauBeGuboBedagusBegucus" ordered="false" upperBound="-1" eType="//FaFrigusdabibuboNulaunulAuBobifrifridacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBoBobofriDaTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabeBoGuslius" eType="//EfridafribuDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBiBonulAubodagusGutin" eSuperTypes="//AlbubuBoGusbuBegunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBeBoGusBiBeGusfrinus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EBoFriDabebebocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobufribugudafriboboBoTor" eSuperTypes="//EGusGugusbonulauBecus //BaBibiBugusfriGuBiDanus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anfrigubeTor" eType="//DobeBegusNulaubiguNulauGusboGusius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Albebenulaugusbudabolus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aGuFrigusfriBibetus" eType="//DagusAunulaugubidadanulAunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="didagusfridabefrilius" eType="//EfridafribuDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibibibidabiFriguDaBoGusnulauBetin"/>
</ecore:EPackage>
