<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dibebonulaufricus" nsURI="http://hub.de/rcore/examples/dibebonulaufricus" nsPrefix="jH">
  <eClassifiers xsi:type="ecore:EClass" name="EubuguBeFrigusfrinulaubeFribedabetus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlGubofriNulauLus" instanceTypeName="typeAnBebodabiBuBonulAuNulAuTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBuDabefribudadabuBoBedabolius" eSuperTypes="//EubuguBeFrigusfrinulaubeFribedabetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugubobeGusBubudaes" ordered="false" eType="//EubuguBeFrigusfrinulaubeFribedabetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BebogudaGusnulauGuguGuFriFriTor" instanceTypeName="typeDubiBuFriBogubunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaGubofridabuBifribiTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABubogusbonulaubinulaubudabinus" eSuperTypes="//EubuguBeFrigusfrinulaubeFribedabetus //AnBuDabefribudadabuBoBedabolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aboBibeBeDaBoGubifriNulAulius" ordered="false" upperBound="-1" eType="//EudaGubofridabuBifribiTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DagusNulaugubogusbubeDaBobeNus" instanceTypeName="typeAbiNulaunulAubobiNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBoGuDanules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doFribebudagubegubedabilus" eType="//AlGubofriNulauLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudabodanulauboGucus" ordered="false" upperBound="-1" eType="//AnBuDabefribudadabuBoBedabolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusbegusgusgubenulEs" eSuperTypes="//ABubogusbonulaubinulaubudabinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duboBugusbolus" eType="//EudaGubofridabuBifribiTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnBeBibifriBofridadaBeTus" instanceTypeName="typeAubunulaubibugusBiboNulaugusLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBogusnulAubibogusGuGusDacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBinulaunulAugunulaulius" ordered="false" upperBound="-1" eType="//ABubogusbonulaubinulaubudabinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubuGusBiBoguTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alauGubebuCus" eType="//AlGubofriNulauLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaubegunulAubufrigusnulauCus" abstract="true" eSuperTypes="//EubuGusBiBoguTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DanulaugusBebobiboGunulAugusauNulaucio" instanceTypeName="typeFabuNulAubuGudatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBoboguBegusfriGusdaTin" eSuperTypes="//EubuguBeFrigusfrinulaubeFribedabetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguGusbeFrifribudaguBifriDaGusCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabegusbiNulaugusDaBonulAuTor" ordered="false" eType="//EuBogusnulAubibogusGuGusDacus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbogusDabeGusnulauTor" eType="//DanulaugusBebobiboGunulAugusauNulaucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiBodabibuguDabuTor" eSuperTypes="//ABubogusbonulaubinulaubudabinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBonulauNulauNulaugusaudaguTin" eType="//DanulaugusBebobiboGunulAugusauNulaucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbobubebiBunulauguslus" eSuperTypes="//EubuguBeFrigusfrinulaubeFribedabetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBeguGubibeFriGusbubinus" ordered="false" eType="//ENulaubegunulAubufrigusnulauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedaguBoFriBudalus" eSuperTypes="//EuBogusnulAubibogusGuGusDacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eDafriBugusCio" eType="//BebogudaGusnulauGuguGuFriFriTor" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
