<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="begusfridabees" nsURI="http://hub.de/rcore/examples/begusfridabees" nsPrefix="gFf">
  <eClassifiers xsi:type="ecore:EClass" name="AlBunulauFrigudaGusBicus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abobudabobebiFriNulaugubifricus" ordered="false" eType="//EuFriNulautor" eOpposite="//EuFriNulautor/anbinulaubodaboBebunulaugusbutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBidabiNus" eSuperTypes="//AlBunulauFrigudaGusBicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuFriNulautor" eSuperTypes="//AlBunulauFrigudaGusBicus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbinulaubodaboBebunulaugusbutus" eType="//AlBunulauFrigudaGusBicus" eOpposite="//AlBunulauFrigudaGusBicus/abobudabobebiFriNulaugubifricus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBibufrinulaugugubuBotor" ordered="false" eType="//BigusBebegusfribiguGufriBenulaubinulauNus" eOpposite="//BigusBebegusfribiguGufriBenulaubinulauNus/aunulauguNulauGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AgufriBoboDaboBoCus" instanceTypeName="typeAldabufriGusfriFriGusbibeBeDatus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBiBodaBeboguBufriBugusLus" instanceTypeName="typeBafriFridaFriEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusBebegusfribiguGufriBenulaubinulauNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euguGulus" eType="//FaBiBodaBeboguBufriBugusLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulauguNulauGucus" ordered="false" eType="//EuFriNulautor" eOpposite="//EuFriNulautor/euBibufrinulaugugubuBotor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabigusgusguBogusbiboDagustus" ordered="false" eType="//BeBedaBonulAubuNulaunus" eOpposite="//BeBedaBonulAubuNulaunus/alNulaufriGugusbobidaNulaugusbebecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubofrinulaubodagunulEs" eSuperTypes="//EuFriNulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebiGuFribeEs" eSuperTypes="//BigusBebegusfribiguGufriBenulaubinulauNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babeDadadadabocio" upperBound="-1" eType="//EubofrinulaubodagunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidagunulaugubigusgusnulAuguboBobetor" eSuperTypes="//BebiGuFribeEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudanulaubobuBilius" ordered="false" eType="//EuFriNulautor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alnulaucio" eType="//AgufriBoboDaboBoCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusnulaubonulAuGudaBunulAutin" eSuperTypes="//BebiGuFribeEs //EubofrinulaubodagunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaBuDagusguGusbubibenulauGuTus" eSuperTypes="//BidagunulaugubigusgusnulAuguboBobetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGufriBugusboDabuBicio" eSuperTypes="//BidagunulaugubigusgusnulAuguboBobetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibobeBebudabebitus" eSuperTypes="//EuFriNulautor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibifriDaTus" ordered="false" eType="//EubofrinulaubodagunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbuBenulaunulAugufriGusaunulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlAubeboBibidafriGusAucus" instanceTypeName="typeAbodanulaubegufrigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngugudabeBoCus" eSuperTypes="//EuGufriBugusboDabuBicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebugusbeBidaguscus" ordered="false" eType="//DoBidabiNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="augubifribeBuboGuDatin" ordered="false" eType="//EuGufriBugusboDabuBicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfribubuGuFriCio" eSuperTypes="//BebiGuFribeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbububunulAuBedaBobocio" eSuperTypes="//BebiGuFribeEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eudadafricus" eType="//AgufriBoboDaboBoCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBedaBonulAubuNulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulaufriGugusbobidaNulaugusbebecus" upperBound="-1" eType="//BigusBebegusfribiguGufriBenulaubinulauNus" eOpposite="//BigusBebegusfribiguGufriBenulaubinulauNus/dabigusgusguBogusbiboDagustus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulAuGufrigusfritor" ordered="false" upperBound="-1" eType="//BegusnulaubonulAuGudaBunulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusdaFriguNulaugusbocio" eSuperTypes="//BigusBebegusfribiguGufriBenulaubinulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dobunulaunulaugusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubebiBefribobiGuDadadaboboTin" eSuperTypes="//AngugudabeBoCus"/>
</ecore:EPackage>
