<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dugutus" nsURI="http://hub.de/rcore/examples/dugutus" nsPrefix="HFI">
  <eClassifiers xsi:type="ecore:EClass" name="AnbugububeBububuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alfribotus" eSuperTypes="//AnbugububeBububuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digunulaufriguLus" ordered="false" upperBound="-1" eType="//AnbugububeBububuLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abibeNulauBedaDabogusDalus" ordered="false" upperBound="-1" eType="//AnbugububeBububuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbigunulAugubegutus" instanceTypeName="typeDabiFriNulauBiBoBefriGusbenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulauFridadaGuses" abstract="true" eSuperTypes="//AnbugububeBububuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eNulaubuDaGubinulautin" ordered="false" upperBound="-1" eType="//AnbugububeBububuLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFribeFridafrigusDagusdanus" eSuperTypes="//AnbugububeBububuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBegusnulautus" upperBound="-1" eType="//Alfribotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfrigusbofriBubegusbetus" eSuperTypes="//Alfribotus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBoNulaububobobiDaFriBiboguDabuDacus" instanceTypeName="typeEboFriBoGusDaNulAuBeguBuGusbobonulAulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBonulauBoBucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGufriBeguBegubogusfridanulAuNus" eSuperTypes="//DuFribeFridafrigusDagusdanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuGubifribibugusFrifrinulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubonulAubibiboBilus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnBunulaudaNulaubifriguboNulius">
    <eLiterals name="AufrifribigufribuGusGulius"/>
    <eLiterals name="DubiFriBibebiBuBeBuGuGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebefriFrinulaubofriCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidaGubobeDabeBeboGubotus" eSuperTypes="//BrAubonulAubibiboBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusbeboBuGusdaNulaugusdabiBoTor" ordered="false" upperBound="-1" eType="//AnbugububeBububuLius"/>
  </eClassifiers>
</ecore:EPackage>
