<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fa" nsURI="http://hub.de/rcore/examples/fa" nsPrefix="UYV">
  <eClassifiers xsi:type="ecore:EClass" name="AlBiBegubiBodaBogusdafriguTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulaudabubotin" eSuperTypes="//AlBiBegubiBodaBogusdafriguTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibeBibelius" ordered="false" upperBound="-1" eType="//AlBiBegubiBodaBogusdafriguTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufribefribiDabobubenulaugues" eSuperTypes="//AlBiBegubiBodaBogusdafriguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogusBoboBobigudabigububelus" eSuperTypes="//DufribefribiDabobubenulaugues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaudaBoBunulaubenulaubebecus" abstract="true" eSuperTypes="//AlBiBegubiBodaBogusdafriguTin //DufribefribiDabobubenulaugues"/>
  <eClassifiers xsi:type="ecore:EClass" name="Binulaugubecio" eSuperTypes="//DufribefribiDabobubenulaugues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBobebonulauBenulauBebulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnDaboGusFriGubebubegufriBiBoTus" eSuperTypes="//AlBobebonulauBenulauBebulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugubibeBufriBuBoGudaes" eSuperTypes="//BiNulaudabubotin //AnDaboGusFriGubebubegufriBiBoTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiDaBubiBegudaBotin"/>
</ecore:EPackage>
