<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fadatin" nsURI="http://hub.de/rcore/examples/fadatin" nsPrefix="e">
  <eClassifiers xsi:type="ecore:EClass" name="BiBugusNulaunulaufrigucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaubeBeGusbedaguGugubuGuslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbugusGubuNulaudafrinulauguFritin" eSuperTypes="//BiBugusNulaunulaufrigucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBibedafricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaBobibudanulaufritin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlauguguGusbiEs" instanceTypeName="typeEnulaudanulaubibibofrifribobedagusTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AFridaboGuBiGunulaudagusius" eSuperTypes="//EuBibedafricus //EudaBobibudanulaufritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaGudaguGusbilus" ordered="false" upperBound="-1" eType="//EuBibedafricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGugusFrifribibigues" eSuperTypes="//AlbugusGubuNulaudafrinulauguFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBibunulauBeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugugufriBugusnulius" abstract="true" eSuperTypes="//BrauGugusFrifribibigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbiNulaubofrinulaubebibogues" eSuperTypes="//EuBibedafricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBoGusfriBebiBeGusgusAuGucus" ordered="false" upperBound="-1" eType="//DaBibunulauBeEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babeguNulauNulaubibunulautin" ordered="false" upperBound="-1" eType="//EuDaBugusbufrigucio" eOpposite="//EuDaBugusbufrigucio/anulauBubilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiFrigunulaudabuBuguscus" eSuperTypes="//EudaBobibudanulaufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuDaBugusbufrigucio" eSuperTypes="//EuBibedafricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulauBubilus" ordered="false" upperBound="-1" eType="//EbiNulaubofrinulaubebibogues" eOpposite="//EbiNulaubofrinulaubebibogues/babeguNulauNulaubibunulautin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulauGuBegufriguBitin" eType="//AlauguguGusbiEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAudanulAuGusbegusbocus" eSuperTypes="//EudaBobibudanulaufritin //EbiNulaubofrinulaubebibogues //AFridaboGuBiGunulaudagusius"/>
</ecore:EPackage>
