<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="di" nsURI="http://hub.de/rcore/examples/di" nsPrefix="Mn">
  <eClassifiers xsi:type="ecore:EDataType" name="AlgusboGusbiNulAuguses" instanceTypeName="typeDubegugusdaBogusnus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AubinulAuguBoGuGustus" instanceTypeName="typeBefrifribiNulauBenulaubetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodagufribobugusBeGuDanulaubiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogusnulauGugusbeboGusCus" eSuperTypes="//DodagufribobugusBeGuDanulaubiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBefribebobubifritus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulAubiDabugustus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubofriboBibefribiGudalius" eSuperTypes="//DuBefribebobubifritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBobogubugunulaugusnulauNulius" ordered="false" upperBound="-1" eType="//BenulaudanulAuBilus" eOpposite="//BenulaudanulAuBilus/dagubiNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifriguBuGubogusDaGusbeDabubotus" abstract="true" eSuperTypes="//DuBefribebobubifritus //DodagufribobugusBeGuDanulaubiLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauLus" instanceTypeName="typeFabibigudadabobibilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABegusbibuDagubeBobenus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Eugugusnulaubobugusbibegusdagustus" instanceTypeName="typeBaFribibocio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DunulaunulAugusgububodagubelius" instanceTypeName="typeAlgusbebiFrifriBugubiboBibibetus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubobebeDabulus" instanceTypeName="typeAuguBubofributin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BeBebefriguGuBegusnus">
    <eLiterals name="DuFribebebifrifriBonulAulius"/>
    <eLiterals name="DoboGuGusdaGubogusbubobudaBecio"/>
    <eLiterals name="AuBebuBobidafritor"/>
    <eLiterals name="DubiGuGufrigufribeBeguBoboboBeboCio"/>
    <eLiterals name="BagusboboguFribelius"/>
    <eLiterals name="BraubuGusfridacus"/>
    <eLiterals name="DibibeBicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaufribuDacio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enulaubonulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBunus" eType="//ABegusbibuDagubeBobenus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusBuFribitus" eType="//EubofriboBibefribiGudalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaDaBuboBeNulaubuGusGusbuBeguBoboTus" eSuperTypes="//EubofriboBibefribiGudalius //ABegusbibuDagubeBobenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebubenulaugusnulauBigubodator" eType="//DifriguBuGubogusDaGusbeDabubotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnauBoguguboguGusBifrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBodadaBuBofrigusnus" abstract="true" eSuperTypes="//DaNulAubiDabugustus //DuBefribebobubifritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibibedaFriBibiFriLus" ordered="false" upperBound="-1" eType="//BrAucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabuFriNulAudanulAuDaBiguguFriBocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabiBibigugutus" upperBound="-1" eType="//AubinulAuguBoGuGustus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aubobubugusdatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubibunulaubelus" ordered="false" eType="//DinulaufribuDacio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBuBigusbonulaubonulAugusius" ordered="false" upperBound="-1" eType="//Enulaubonulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfribugubuBubucio" eSuperTypes="//DinulaufribuDacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbudabuboFriNulauDagusTus" eSuperTypes="//DodagufribobugusBeGuDanulaubiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauBebuboNulaubudagusnulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiDaguguBenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaudanulAuBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagubiNules" upperBound="-1" eType="//EubofriboBibefribiGudalius" eOpposite="//EubofriboBibefribiGudalius/faBobogubugunulaugusnulauNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbibibebuDabibeDabigusNus">
    <eLiterals name="DabubebiNulAuGunulauBoTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabubiNulautus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biNulaunulAunulAutor" eType="//AubinulAuguBoGuGustus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBugubebedaBenulaubogusnules" abstract="true" eSuperTypes="//DuBefribebobubifritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angubogubinulAunulaulus" ordered="false" upperBound="-1" eType="//DogusnulauGugusbeboGusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusfriFribegugugusfrifrigusfriGuslus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiGusaubiBidagudagunules" instanceTypeName="typeBeBedabetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidaGufriBubenulAubiFrifribegubeNulAucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefriBogubuBibeBitin" eSuperTypes="//FabuFriNulAudanulAuDaBiguguFriBocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaubebunulAulius" ordered="false" upperBound="-1" eType="//DiBodadaBuBofrigusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubeBoguLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beNulaubiBebibobeboBubuBucus" ordered="false" eType="//DifriguBuGubogusDaGusbeDabubotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EufriGutus" instanceTypeName="typeBeBubobofribodacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusGudaNulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBebobiNulAububibenulauguBotus" ordered="false" eType="//DaNulAubiDabugustus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ADanulaugusaubitor" instanceTypeName="typeDagusbinulaubibofriDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFriBocus" eSuperTypes="//AlbudabuboFriNulauDagusTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbugusfrifrigusnulAubibifridaDaBunulius" eType="//DubeBoguLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DibiGusbeBofridalus" instanceTypeName="typeBibobegusBegusguGutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBibudaguGusaubebuNulIus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babebudaEs" eType="//BrauLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaFribegusBoguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulaugusbidagutor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBuFriBebuBubibedafriGuguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euboguGusbogufribubetus" eType="//EubofriboBibefribiGudalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusnulAugubigudaFriNus" eSuperTypes="//BefriBogubuBibeBitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulauBudaGuguGunulaubiCus" eSuperTypes="//FabuFriNulAudanulAuDaBiguguFriBocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGudaGusguBobeBebogudabecio" ordered="false" upperBound="-1" eType="//DubinulAugusTin" eOpposite="//DubinulAugusTin/augusBubedaBogusbodaguTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfrigusnulAuNulaufriLius" eSuperTypes="//DifriguBuGubogusDaGusbeDabubotus //DaFribegusBoguLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagubiBebedanulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigufriBogubiCus" ordered="false" eType="//BraugusnulAugubigudaFriNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagugusBiDaNulAuBuFrigunulAuFritor" eSuperTypes="//DiBuFriBebuBubibedafriGuguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfrifriFriboGusfriEs" abstract="true" eSuperTypes="//FabuFriNulAudanulAuDaBiguguFriBocio //BabubiNulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuDaguBidanulAuNules" eSuperTypes="//EuBugubebedaBenulaubogusnules //DaNulAubiDabugustus //BabubiNulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulauboDadafribegutor" eSuperTypes="//BaDaBuboBeNulaubuGusGusbuBeguBoboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuboDaboBitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubiguguBegusGuscio" ordered="false" upperBound="-1" eType="//DiBuFriBebuBubibedafriGuguslius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euGusgusBibibegusgusFritin" eType="//DibiGusbeBofridalus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlBudaBoBigugusFrinulauBeFricus" instanceTypeName="typeFaguDaBifrigusNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dadabutin" instanceTypeName="typeBagugusgusBunulAubiDaGuGuBiTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBufriBeBitin" eSuperTypes="//DifriguBuGubogusDaGusbeDabubotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulauguFrigusgufribuTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alboFrigusgusCus" eType="//DunulaunulAugusgububodagubelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusgusdafriGusnulaufribigusCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ABeGusdagusbigugusgusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubinulAugusTin" eSuperTypes="//Enulaubonulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusBubedaBogusbodaguTor" ordered="false" upperBound="-1" eType="//DanulauBudaGuguGunulaubiCus" eOpposite="//DanulauBudaGuguGunulaubiCus/auGudaGusguBobeBebogudabecio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doboboBubugudafribilius" ordered="false" upperBound="-1" eType="//DaNulaugusbidagutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBeFriNulauBiBiGubigusAutor" abstract="true" eSuperTypes="//FanulauboDadafribegutor //AlbudabuboFriNulauDagusTus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Augusgusfribobotor">
    <eLiterals name="EuBubofriGusboboGusGusFrifriNulauDaEs"/>
    <eLiterals name="BabinulAunulaudaBuFribuDaNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraudabebogusfridaBolius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binulAudabedabotin" eType="//BrauLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBigusauGugusBonulauGugusBenulEs" instanceTypeName="typeDuFribolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadadafriFribobiTin" eSuperTypes="//FagubiBebedanulius //DubinulAugusTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBiDabiFribebecio" eType="//AubinulAuguBoGuGustus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBuFrigusBeGuguBeLus" eSuperTypes="//FagusfriFribegugugusfrifrigusfriGuslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBodabeguguBugudabunules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbiBugusNulaubeGububutor" abstract="true" eSuperTypes="//Aubobubugusdatin //AnauBoguguboguGusBifrilus //EubofriboBibefribiGudalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBibuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biFribeGububuFrigudabibiTin" ordered="false" eType="//DiBodadaBuBofrigusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaFriBeboDaDaboLus" instanceTypeName="typeFaBeBebiNulauBeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubiBoGusBebuBiBinulAudagusEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egubeFrifrifricus" eType="//EfrigusnulAuNulaufriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGuBibinulaubeBilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlfrigusbuBuBubeBigububonules" instanceTypeName="typeAnbuGugunulAubobobeBocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubeDadaBifrifribiDanulaudator" eSuperTypes="//EubofriboBibefribiGudalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabegubidaGusbugugusLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="danulAuNulauCus" upperBound="-1" eType="//DiGusaubiBidagudagunules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebegunulAububebuguguBiguTor" ordered="false" eType="//EubofriboBibefribiGudalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuboBunulAufriBidabubuBotus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBoGusgusgusBelius" ordered="false" eType="//BidaGufriBubenulAubiFrifribegubeNulAucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AuFridabedabeTin" instanceTypeName="typeDiguboguBonulauguboguGunulautus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnGudagusboGuNulAubebiFriFridabotus" instanceTypeName="typeDiBebububidaBiFribotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefribegusBofriguNulaubonulaunus" eSuperTypes="//FagugusBiDaNulAuBuFrigunulAuFritor //FaBeFriNulauBiBiGubigusAutor //BadadafriFribobiTin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EBobeFribegunulAuboguNulaufriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiboGugusboFriboGuslius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabebenulauBeFriBiGusbinulAutus" ordered="false" eType="//BrauBibudaguGusaubebuNulIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofrinulaubigusbebefrinulauBubefriTus" eType="//DogusnulauGugusbeboGusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Danulaunulaubebecus" eSuperTypes="//DaNulaugusbidagutor //BabubiNulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algubububeNulaugunulaugugunus" ordered="false" eType="//FaGuBibinulaubeBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBofrinulaudanulauBibocio" eSuperTypes="//AlbudabuboFriNulauDagusTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraudaBibobeGusgusnulaubuBenulius" instanceTypeName="typeAugufriBuDabebeGudaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusaubibugusdaBuguNulAubuNus" eSuperTypes="//BefribegusBofriguNulaubonulaunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="andanulIus" upperBound="-1" eType="//Augusgusfribobotor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBobunulauGugusdabulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusbigubonulaubigucus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubugusDaFribibiBoBocus" ordered="false" eType="//Danulaunulaubebecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Audagusgusdafribegusgusgulius" instanceTypeName="typeEfridaGudagusBobegusgusCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBinulauBibobunulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusgusbibuDabobugufriBinulauGusius" eSuperTypes="//DubinulAugusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusbidafribibuLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfrigubuFricio" eSuperTypes="//BaDaBuboBeNulaubuGusGusbuBeguBoboTus //BraugusaubibugusdaBuguNulAubuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabobubeBeGusIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babigusfribocio" eType="//AlgusboGusbiNulAuguses" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubibebeBogusBodaLius" eSuperTypes="//DaNulAubiDabugustus //EfrifriFriboGusfriEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabobenulaufrigusBedadabeButus" ordered="false" eType="//DuDaguBidanulAuNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulauBeBetus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulauDabibibiNus" eType="//DuBefribebobubifritus"/>
  </eClassifiers>
</ecore:EPackage>
