<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="alnulaubocio" nsURI="http://hub.de/rcore/examples/alnulaubocio" nsPrefix="WUm">
  <eClassifiers xsi:type="ecore:EDataType" name="BedaboFriFriFrifrigubibenus" instanceTypeName="typeFaBiNulaubebiguGusbeBibocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DofrigusbubibuBedaCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBigusbifridagusbues" ordered="false" upperBound="-1" eType="//DadaguboBobonulAubobebedabuCio" eOpposite="//DadaguboBobonulAubobebedabuCio/duboBeBibeFrinulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBegunulaunulaububuBeBinulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusbibenulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnulaubufriBedabeBugusgusIus" instanceTypeName="typeBaBububunulaubuDabobuBugusgusnulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnDanulAudafriGuBugucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dufribedagusbocio" ordered="false" upperBound="-1" eType="//Albubifribotus" eOpposite="//Albubifribotus/aBunulaubeboNulaunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboBoGubeBibeGusgusLius" eSuperTypes="//DofrigusbubibuBedaCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulaubidabedaGusgubobebeTor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BefriguFriBifriFribelus">
    <eLiterals name="DibubeNulautor"/>
    <eLiterals name="DaboBubuGusbeBoGusfribebobutus"/>
    <eLiterals name="DibefrigufribuNulAuNus"/>
    <eLiterals name="AunulaubinulAuDaFricio"/>
    <eLiterals name="BigunulAufribobecio"/>
    <eLiterals name="AlFribugusgusbefriGuFrinulAutor"/>
    <eLiterals name="BrauBoguBeBeFrifries"/>
    <eLiterals name="AnDadaguBebobibedaBetus"/>
    <eLiterals name="AuBogusFrifrigusBigustin"/>
    <eLiterals name="AudabeGubebubegustin"/>
    <eLiterals name="DigusbibifrifrifrigusNulAububulius"/>
    <eLiterals name="EuGusbuboFrifriBigugubugustus"/>
    <eLiterals name="BrAuboDanulaugusbidalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFribebobiNus" eSuperTypes="//EnulaubidabedaGusgubobebeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauNulaubufrifriNus" ordered="false" upperBound="-1" eType="//AnBegunulaunulaububuBeBinulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubeGusFribuGubies" abstract="true" eSuperTypes="//DiboBoGubeBibeGusgusLius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EgusaubuBuBibinulaufribolus">
    <eLiterals name="AuBigusdaBibifridadabinulaunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DadaguboBobonulAubobebedabuCio" eSuperTypes="//EubeGusFribuGubies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duboBeBibeFrinulAutin" ordered="false" upperBound="-1" eType="//DofrigusbubibuBedaCus" eOpposite="//DofrigusbubibuBedaCus/faBigusbifridagusbues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnDaBifribiGuguNulaudabogubitus" instanceTypeName="typeDifriGuBobedafriBenulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGunulAugusdalius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabeGubebuDabubenulius" eSuperTypes="//DiboBoGubeBibeGusgusLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euBoFrigubebubenulius" eType="//AnulaubufriBedabeBugusgusIus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBiBunules" abstract="true" eSuperTypes="//AnBegunulaunulaububuBeBinulautor //EubeGusFribuGubies"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugufribugusguBuGugusfriLius" eSuperTypes="//DadaguboBobonulAubobebedabuCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DifribeBenulAudanulAubuCus">
    <eLiterals name="DoBobobebubudaFrigusBogusauFriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBobebibifriguBeBubunules" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusauNulauGusBinulAubogububuLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebiDagusfriNulius" ordered="false" eType="//EubiFrigusauBudabebiFrinus" eOpposite="//EubiFrigusauBudabebiFrinus/efriBibubedabodabogusgutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbeBoBunulaufrigusGuscus">
    <eLiterals name="EbenulaunulAuBenulauboboLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlauguDabobutor" abstract="true" eSuperTypes="//FabeGubebuDabubenulius //DugufribugusguBuGugusfriLius //BaBobebibifriguBeBubunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubidanulAuBodabeguGusfricio" eSuperTypes="//BigusauNulauGusBinulAubogububuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibefribibebefrifrifriNulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobubufritus" eType="//AnbeBoBunulaufrigusGuscus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFribubofriNulauBogues" ordered="false" eType="//FaGunulAugusdalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubenulauBiBibibubibeGucio" abstract="true" eSuperTypes="//FaBiBunules //EnulaubidabedaGusgubobebeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babobobebodabogusbuLius" ordered="false" upperBound="-1" eType="//FaBiBunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnfribogudaFribocus">
    <eLiterals name="EbubeboBiBebinules"/>
    <eLiterals name="AbobugusbiBuBubiTin"/>
    <eLiterals name="ENulAuBuBuboguFrinulaulus"/>
    <eLiterals name="AuguGusgugusBubeGubigulus"/>
    <eLiterals name="Ebigudalius"/>
    <eLiterals name="EubunulauFriBeBogugusbegucio"/>
    <eLiterals name="AugusguNulaunulauguBofrinules"/>
    <eLiterals name="BadagubenulaudaGusBegusbugutor"/>
    <eLiterals name="EubedaBibocio"/>
    <eLiterals name="EugusaudagusnulaugusbobeBubelus"/>
    <eLiterals name="AnfrinulauBugusbiCus"/>
    <eLiterals name="EdaBiNulauboGudagusCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bibobebubibenulius" eSuperTypes="//FaBiBunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulAunulauBidatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabibugusgusfribegusbuGusFriBifriEs" eSuperTypes="//AnDanulAudafriGuBugucio //EnulaubidabedaGusgubobebeTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DagubigusFriGuBues" instanceTypeName="typeAlnulAuFrinulaubidafribubonulaufries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifrifriBegufribobigubiDagugusFrifriTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babugusBebubiFribunulautin" ordered="false" eType="//BabibugusgusfribegusbuGusFriBifriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabebuBobuboBibiGubiBebubuNulAuNulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugugusBuGunulauguNulauBicus" ordered="false" upperBound="-1" eType="//DubenulauBiBibibubibeGucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBiFribufribubiBeBenulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBudaBudabebiguslus" ordered="false" upperBound="-1" eType="//BabibugusgusfribegusbuGusFriBifriEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBeBobonulAuGusauFrilius" ordered="false" upperBound="-1" eType="//Bibobebubibenulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegufribuBiNulaudaDaFrigugusboGuGubeCus" abstract="true" eSuperTypes="//BegusbibenulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enulAuGusdaCus" upperBound="-1" eType="//BefriguFriBifriFribelus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusgusgugusCio" ordered="false" eType="//DugufribugusguBuGugusfriLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFridabuBufritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudabobocio" ordered="false" eType="//BrauFribebobiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabigusnulaubobeboBogusBicus" eSuperTypes="//DofrigusbubibuBedaCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alboGubidaDaGusCus" ordered="false" eType="//DaBibibodabifribulus" eOpposite="//DaBibibodabifribulus/braubibibodabugulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlFribenus" instanceTypeName="typeDiBobodafrinulAuguGuBecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Albubifribotus" eSuperTypes="//FabeGubebuDabubenulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBugudanulAububogudanulius" ordered="false" eType="//EubidanulAuBodabeguGusfricio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBebebidabinulaunulaugusfridalius" ordered="false" upperBound="-1" eType="//BegufribuBiNulaudaDaFrigugusboGuGubeCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBunulaubeboNulaunulEs" ordered="false" upperBound="-1" eType="//AnDanulAudafriGuBugucio" eOpposite="//AnDanulAudafriGuBugucio/dufribedagusbocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinulAuDanulAulius">
    <eLiterals name="DiBeDaBugufrifrigustin"/>
    <eLiterals name="Bigufrifriguslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusbuTor" eSuperTypes="//BaBobebibifriguBeBubunules //FabeGubebuDabubenulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eDaboGusauBecus" ordered="false" eType="//DabigusnulaubobeboBogusBicus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuguGusfriDabodabigutor" ordered="false" upperBound="-1" eType="//DaNulaugusguDagubiFriboBoBulius" eOpposite="//DaNulaugusguDagubiFriboBoBulius/euDabugubedanulAubeEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFribigugusbenus" instanceTypeName="typeBeDadaGudabufriBiguCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobibegubeBeBonus" instanceTypeName="typeDabogubeBodaGusnulaunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fagufrigubunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusBeBuguBogustus" eSuperTypes="//Bibobebubibenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaBegusbuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babegusbegubegustus" eSuperTypes="//BigusauNulauGusBinulAubogububuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubunulAudagusBedabodaes" eSuperTypes="//EudaBegusbuLus //DibefribibebefrifrifriNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBoBitor" abstract="true" eSuperTypes="//BrauFribebobiNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibeBebedabuBogusaubiNules" ordered="false" upperBound="-1" eType="//AlauguDabobutor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibiGusbubunulAubefriFriNus" eType="//AnfribogudaFribocus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AdanulaubebiboBoFribuLus" instanceTypeName="typeAlbubibeGudagusBeNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubegusboNulAuGulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAunulautus" ordered="false" eType="//Albubifribotus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabuBeBoboGunulAufrigusnulIus" ordered="false" upperBound="-1" eType="//BabibugusgusfribegusbuGusFriBifriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Aubunulaudaguscio" instanceTypeName="typeAlAuBeNulaugusNulaudaFribebebucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulAugudagusbuGuGubobinus" eSuperTypes="//BeGusbuTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiFribiNulaubebonulAuTin" ordered="false" eType="//BabibugusgusfribegusbuGusFriBifriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlauGusfriFriboGusbibudaBiDaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulAuGusBobuBulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diBugufribedagustor" eType="//DobibegubeBeBonus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="e" eType="//AdanulaubebiboBoFribuLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baGusguGusAucus" ordered="false" upperBound="-1" eType="//DadaguboBobonulAubobebedabuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibebenulauGusBulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogubebuBonulauDagusBitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daNulauGusgugubibodabubobenulAubeDabunus" upperBound="-1" eType="//AnBegunulaunulaububuBeBinulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnulauDanulaugusCus" eSuperTypes="//DagusBeBuguBogustus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubidacio" eType="//AdanulaubebiboBoFribuLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriBeBubebifriBefriBinulius" eSuperTypes="//DonulAunulauBidatin //AnulauDanulaugusCus //BeGusbuTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabobububiNules" ordered="false" upperBound="-1" eType="//BabonulaubuBeguBucio" eOpposite="//BabonulaubuBeguBucio/ebofribobidaNulAubebiButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfribonulaubugusdadabeguTus" eSuperTypes="//AubegusboNulAuGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusgusgugunulAufrigusgusfribibotor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dagunulauNulAunulauGuNulAugulius" eType="//EgusaubuBuBibinulaufribolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Digunulaucio" eSuperTypes="//DibebenulauGusBulius //BeGusbuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBeBugunulaufriboBefricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubeBuGusbodanulauFriBugusgusCus" eSuperTypes="//EnulAugudagusbuGuGubobinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badaguGugubidaFriBiBoes" eType="//AnfribogudaFribocus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Benus">
    <eLiterals name="AuDabogugusguGusfribubebuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulaugusGusnulauBibies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebobobeGuBibotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBiBigusaugusDabeBonus" ordered="false" eType="//EnulAugudagusbuGuGubobinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBibibodabifribulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubibibodabugulius" eType="//DabigusnulaubobeboBogusBicus" eOpposite="//DabigusnulaubobeboBogusBicus/alboGubidaDaGusCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diFridafriBuGusbebiNulauNulaulius" ordered="false" eType="//DibebenulauGusBulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulaugusguDagubiFriboBoBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euDabugubedanulAubeEs" ordered="false" upperBound="-1" eType="//BeGusbuTor" eOpposite="//BeGusbuTor/brAuguGusfriDabodabigutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuguboguDabiBeguFrifriBifries" instanceTypeName="typeAnaubebobeBiGuGuGububedaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbiBoboFribiBebodagustus" eSuperTypes="//EubeBuGusbodanulauFriBugusgusCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusnulauBidaBibubicio" eSuperTypes="//DoBiFribufribubiBeBenulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGuGusfrinulaufrinus" ordered="false" eType="//EnulAugudagusbuGuGubobinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BafriBogusbebodabunulAuGusbucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulAuBigubugusbigufrinus" ordered="false" upperBound="-1" eType="//BebobobeGuBibotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulAunulauGubinulIus" abstract="true" eSuperTypes="//DaNulaugusguDagubiFriboBoBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andabobuBiBibedabulius" ordered="false" eType="//BrAuGusbuBibubibegulius" eOpposite="//BrAuGusbuBibubibegulius/danulaubiNulaubiBeGuBogusnulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fagusbobudafribubotor" abstract="true" eSuperTypes="//BrAunulaugusGusnulauBibies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulaububebogufricio" ordered="false" eType="//BrAunulaugusGusnulauBibies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusdafribiBibobogusgusbubibudator"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BraubiFrigusbebibodaGuscio">
    <eLiterals name="BagusGusBinulAuNulaufriBoNulAuBuCus"/>
    <eLiterals name="AububofriNulaugusbudaBigusius"/>
    <eLiterals name="DoNulAubeFribeButus"/>
    <eLiterals name="EgunulAuFribobubobonulaubedaDabicus"/>
    <eLiterals name="BiNulAubugugusBuBogusdafritus"/>
    <eLiterals name="BaBibugusboFriGusFrigusaubebonules"/>
    <eLiterals name="AuNulAuboBibofribibifrifricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabubibobugubiguboGuscio" eSuperTypes="//DofrigusbubibuBedaCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albigusAubegusboFrigusLus" eType="//BraubiFrigusbebibodaGuscio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodagufribufriFribibudaBenules" eSuperTypes="//DugufribugusguBuGugusfriLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faFriBiGubogugusnulAugutin" ordered="false" upperBound="-1" eType="//AnfriBeBubebifriBefriBinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dabegusbobebubodafrigusbenulaucus" eSuperTypes="//BeGusbuTor //BraubunulAudagusBedabodaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAufriDabuFribibifricus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulAugusbubifrinules" ordered="false" eType="//BrAunulaugusGusnulauBibies"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubugubodaBidafritin" eType="//Benus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBonus" eType="//AlFribenus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biDaGuguFriGugunulAubonulaulus" ordered="false" upperBound="-1" eType="//BabibugusgusfribegusbuGusFriBifriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fafrigusbedagufribees" eSuperTypes="//DugufribugusguBuGugusfriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebeGusfridabugutin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigubegusbifriboDalius" eSuperTypes="//AnulauDanulaugusCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubiNulauBugudaboBoes" upperBound="-1" eType="//DubenulauBiBibibubibeGucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duNulAuBidaBidadaNulAutor" ordered="false" eType="//Dabegusbobebubodafrigusbenulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DidagusnulaubeBenulius" instanceTypeName="typeDafrigufribibutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FagufriGubeDaGunulAubuNulius" instanceTypeName="typeEubobiguNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbugusguBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusfrinulAubibigusdaBuguscio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EgubeBinulaufribubeTin" instanceTypeName="typeDufribuBenulaunulAufridabitus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaguBigudafriFribunulAubifrigucus">
    <eLiterals name="BrAufriboGubobedacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiNulaugusAubeBubeboNulaudadanulautus">
    <eLiterals name="AlAubibobiBiBotor"/>
    <eLiterals name="AlnulauBefriBigusFriBegustin"/>
    <eLiterals name="BibeBoBonus"/>
    <eLiterals name="Enulaubobofridanulautus"/>
    <eLiterals name="AlNulaubebenulAutus"/>
    <eLiterals name="DobibubegufribobebidaBegusaugunus"/>
    <eLiterals name="BiBebenulauGububocio"/>
    <eLiterals name="BeNulauboboBoCio"/>
    <eLiterals name="BefriboBiboboBubobiBiBibubebiboGusDaNus"/>
    <eLiterals name="DabobiBulus"/>
    <eLiterals name="AubonulaugusnulauNulaubeFribeTus"/>
    <eLiterals name="BibunulaububeBiFriGubugusaucus"/>
    <eLiterals name="AubigusbinulAuGusCio"/>
    <eLiterals name="DuGusdagusdadafriFribinulaunus"/>
    <eLiterals name="BrauFriBebobiGuguGusgulius"/>
    <eLiterals name="EBebeBeBuBuBibofriBegusFrinus"/>
    <eLiterals name="BaGubibebeboBudalius"/>
    <eLiterals name="BiDafrinulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugufribeGuNulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaubiBuBeFriFrinules" eSuperTypes="//EubebeGusfridabugutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abubibodanulauGububues" eType="//DagubigusFriGuBues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnulaubiNulauLius">
    <eLiterals name="BraufriBobifriDafribocio"/>
    <eLiterals name="AldaguboGusdadaFridacus"/>
    <eLiterals name="AngusGusfridadaguBogusGuDacio"/>
    <eLiterals name="BraugusgusfrigusgusnulaunulAuNules"/>
    <eLiterals name="DofrifriFritin"/>
    <eLiterals name="AufriBoDaBegusDagusGuFribubunus"/>
    <eLiterals name="BrAuDaTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubibebedabebutor" instanceTypeName="typeAlgunulaudafriBogubonulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuDabegugusbifrinulaufrigulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="acio" ordered="false" upperBound="-1" eType="//AnulauDanulaugusCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudadabubeFridabufrinulauLus" eType="//AlBeBugunulaufriboBefricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBuBoGusbiGugunulaubudabeBilius" eSuperTypes="//DugufribugusguBuGugusfriLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBunulAugusDabebebidabiGugusBocus" eType="//BraubiFrigusbebibodaGuscio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFrigusDabubedaDabenulauTin" ordered="false" eType="//AugufribeGuNulauNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubeBubiDaguGububuBinus" ordered="false" upperBound="-1" eType="//Babegusbegubegustus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babubiBobenulAuDaNulAufries" upperBound="-1" eType="//BafriBogusbebodabunulAuGusbucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaboFribuGusBinulAuDaNulaudabitor" eSuperTypes="//BrauFribebobiNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGusbudaBibubodanules" ordered="false" upperBound="-1" eType="//BinulaubiBuBeFriFrinules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibeBububuBuFriBefribodabodacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabonulaubuBeguBucio" eSuperTypes="//DonulAunulauBidatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebofribobidaNulAubebiButor" ordered="false" upperBound="-1" eType="//AnfriBeBubebifriBefriBinulius" eOpposite="//AnfriBeBubebifriBefriBinulius/dabobububiNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgusbefrigusnulAufribubobiTor" instanceTypeName="typeBabidagudabebinulAubobegusgusBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuboFribegusdaDaGusdabitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebufrinulaubibubiguLius" eSuperTypes="//Dabegusbobebubodafrigusbenulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafrifribubuBunus" ordered="false" upperBound="-1" eType="//BifrifriBegufribobigubiDagugusFrifriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlauGusaubigusFriBeboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaubobifriboBibelius" eSuperTypes="//DonulAunulauBidatin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bedaNulauboBuBuTus" eType="//EnulaubiNulauLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaguBiFribeBoguGusbunus" eSuperTypes="//BrauFribebobiNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EboBefriBufriguFrinulAutor" instanceTypeName="typeEubigubugusguDadagustin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeboBonulauBubufriguBoEs" instanceTypeName="typeBeBinulAubebugubiGuBigusfriTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDafribubiBigusnulauGues"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DobebiFrigubitin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulaubegusAudaDaboBoGusnulius" eSuperTypes="//AugufribeGuNulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulAuboBoNulaudaFridaFriEs" eSuperTypes="//EubebeGusfridabugutin //AnfribonulaubugusdadabeguTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBenulauguNulaugusnus" eSuperTypes="//AlBoBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidafribogusbiDaNulaufritus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibudabenulauBunulAudaBoDalus" eType="//AlFribenus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBeBoBubiGusaububebecus" ordered="false" upperBound="-1" eType="//BrauFribebobiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EububoFribifriBicio" eSuperTypes="//DibeBububuBuFriBefribodabodacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusBobibibuGusAunules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AufribuguDabiguGusbiBebidaLus" instanceTypeName="typeDuBonulaubenulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulauNulAugufridacus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusauDadaDabubefribobeGuguTin" abstract="true" eSuperTypes="//EububoFribifriBicio //EubeGusFribuGubies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agubiDabutin" ordered="false" upperBound="-1" eType="//BebobobeGuBibotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeboFribudafriBiBufries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubibedabuGubucio" ordered="false" eType="//AnbiBoboFribiBebodagustus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euFrinulAugusbiboCus" eType="//DiNulaugusAubeBubeboNulaudadanulautus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBuBubeBegusBedabocio" instanceTypeName="typeBebufrigusbiGusbeGuNulauDaguDafriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldaBiDaButor" eSuperTypes="//DibefribibebefrifrifriNulIus //DaNulaugusguDagubiFriboBoBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubeGunulauBinulIus" ordered="false" eType="//BraunulaubegusAudaDaboBoGusnulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBeBiDafriTus" eSuperTypes="//BraugusgusgugunulAufrigusgusfribibotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubebinulaubiNulauDaBiGuslus" eSuperTypes="//BeGusbuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAuguFriBuBeboBibidadabofritin" eSuperTypes="//BabonulaubuBeguBucio //DiBeBiDafriTus //Fagusbobudafribubotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBugusaudagubobuDagunus" eSuperTypes="//BegufribuBiNulaudaDaFrigugusboGuGubeCus //BinulAunulauGubinulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euFribonulaubiBigucus" ordered="false" eType="//AugusauDadaDabubefribobeGuguTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbigusfriDabenulautus" eSuperTypes="//BifrifriBegufribobigubiDagugusFrifriTus //BinulAunulauGubinulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebogusgusauGububiCus" eSuperTypes="//BraugusgusgugunulAufrigusgusfribibotor //BifrifriBegufribobigubiDagugusFrifriTus //BegusbibenulEs //Albubifribotus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dudaLus" eType="//DidagusnulaubeBenulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daFribiboboBofriguNus" eType="//DiNulaugusAubeBubeboNulaudadanulautus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBonulAugusTus" eSuperTypes="//AugufribeGuNulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboNulaudagusnulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baNulaubunulaufriguBubitus" ordered="false" upperBound="-1" eType="//BiBugusaudagubobuDagunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbeGubogusgusGusGusgunulAunulauBotus" ordered="false" eType="//EnulAugudagusbuGuGubobinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBubibebubobies"/>
  <eClassifiers xsi:type="ecore:EClass" name="Digugusnulaubububunus" eSuperTypes="//BebogusgusauGububiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubiFrigusauBudabebiFrinus" eSuperTypes="//DaBibibodabifribulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efriBibubedabodabogusgutin" ordered="false" eType="//BigusauNulauGusBinulAubogububuLius" eOpposite="//BigusauNulauGusBinulAubogububuLius/bebiDagusfriNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DaBigusfriguGunus">
    <eLiterals name="EguDaboBeguCio"/>
    <eLiterals name="DaBebufriFridaDalius"/>
    <eLiterals name="FadabobeBefribidagusGusTor"/>
    <eLiterals name="AnbubebuDaBebuBotus"/>
    <eLiterals name="BraugusBigusbefriNulauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dulus" eSuperTypes="//BrauFribebobiNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bafribebubitor" eType="//AnfribogudaFribocus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulAudabeCio" eType="//BeboBonulauBubufriguBoEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuFrigusaubigubiNulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuBebuBubiguBibebuFrinus">
    <eLiterals name="AlguFriGunulAugusgunus"/>
    <eLiterals name="BebebenulAunulaudaTin"/>
    <eLiterals name="DabufribobibubeBobebebeguTin"/>
    <eLiterals name="DubibibodafriBiguLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubenulAugubebudabiBegusbelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuGusbuBibubibegulius" eSuperTypes="//AlauGusfriFriboGusbibudaBiDaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulaubiNulaubiBeGuBogusnulautin" ordered="false" upperBound="-1" eType="//BinulAunulauGubinulIus" eOpposite="//BinulAunulauGubinulIus/andabobuBiBibedabulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuguBunulaubebobegudabudanulaubeEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifriFridaBuBubiGusbebibegunulaubilus" eSuperTypes="//AlauguDabobutor //Digunulaucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eboBobubegusDaboGusboGustus" ordered="false" eType="//EubeBuGusbodanulauFriBugusgusCus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufriNulaubocus" eType="//DaguBigudafriFribunulAubifrigucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbebugusNulAugufrigucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlNulaugusbeFriGusboguEs" eSuperTypes="//AnfriBeBubebifriBefriBinulius //BebogusgusauGububiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobiboBoboboguslus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Dofribebinulius">
    <eLiterals name="DaGubogusfribonulaunulIus"/>
    <eLiterals name="AnbubedagugufrinulAubigusius"/>
    <eLiterals name="DidabefrigugusBudagusius"/>
    <eLiterals name="DaGusbudaGusBiBeNulauGusdator"/>
    <eLiterals name="EnulaubebogufribebuEs"/>
    <eLiterals name="DadadagubebunulauguGufribebofriBiTin"/>
    <eLiterals name="Aubunulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBubidanulAugusGusBoLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebibobenulAuBilius" ordered="false" upperBound="-1" eType="//BraubebinulaubiNulauDaBiGuslus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulauDaguBiFriBonulAugucus" ordered="false" upperBound="-1" eType="//AubegusboNulAuGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauDanulAubogusNulautin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Autor">
    <eLiterals name="FaguboBubuBubiBogufriGuscio"/>
    <eLiterals name="DoguBibibugusguboGusbunus"/>
    <eLiterals name="BrauboboNulauBinulAuDagugusnus"/>
    <eLiterals name="AndanulAuBoDagusbudaNus"/>
    <eLiterals name="DadaBoDabidaDabogusFribiBofrinules"/>
    <eLiterals name="BibudaDaboguBoDaNus"/>
    <eLiterals name="AlDabubifribunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifribogusBobunulAuBobefriTus" eSuperTypes="//BebufrinulaubibubiguLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGufribegusbebebobuFriBobogucio" ordered="false" upperBound="-1" eType="//DadaguboBobonulAubobebedabuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudanulaubifriFribebebefrinulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulauBebogubebobobifribeguslus" ordered="false" upperBound="-1" eType="//BrauBubidanulAugusGusBoLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoFriBugubobonulAubidanulauNules" eSuperTypes="//BiNulAuGusBobuBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguNulEs" ordered="false" upperBound="-1" eType="//Digunulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibigusBofrinus" eSuperTypes="//DadaguboBobonulAubobebedabuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eboguBeBuguFribogusDadabegusbeLius" ordered="false" upperBound="-1" eType="//AnnulauNulAugufridacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobenulauguGubedanulEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedaGusBuDafribofrigusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angubibogusius" ordered="false" upperBound="-1" eType="//DaNulaugusguDagubiFriboBoBulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubofrifribibobogusTin" instanceTypeName="typeAubebuGuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusaubunulaugusBefrilus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BagusBeBebofrifriboGusgusNulIus">
    <eLiterals name="AlguBoguGuNulAucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogufribibiBeNulauTor" eSuperTypes="//BrauBenulauguNulaugusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusbinulaububoGusBebubifries" ordered="false" eType="//EubebeGusfridabugutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAubegusaunulaugububeFricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulauBetus" upperBound="-1" eType="//Benus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauTus" instanceTypeName="typeBagunulAunulaunulaubifriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbeNus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBobefribotin" ordered="false" eType="//AnBegunulaunulaububuBeBinulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dunulaudabinulaunulaubitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euFriNulAugusBuguslius" upperBound="-1" eType="//Digugusnulaubububunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabiNulAuBobobonules" eType="//BifribogusBobunulAuBobefriTus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algusnulAugusBeNulauboFrilus" eType="//DaBigusfriguGunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulAuFriGugusguCio" eType="//BraubiFrigusbebibodaGuscio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiFribogues" instanceTypeName="typeAnBubuguBeBoFribunulAucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusBuDaGusdanulAubegusgusius" eSuperTypes="//DifriFridaBuBubiGusbebibegunulaubilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBudabuBodabuDator" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabigugubibuNulAutin" eSuperTypes="//DaNulaugusguDagubiFriboBoBulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiboboGusgusnulAubefrifricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGuNulaubiBuGusfribeBeBigusFrigucus" eSuperTypes="//AnnulauNulAugufridacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafribeBegudaBibeGusbees"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAugusFriGububeGusnulaubiboTin" eSuperTypes="//BrauBenulauguNulaugusnus //BrauBubidanulAugusGusBoLus //BafriBogusbebodabunulAuGusbucio //FabeGubebuDabubenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbidanulAuDatus" abstract="true" eSuperTypes="//BrauBenulauguNulaugusnus //FaBudabuBodabuDator //DaDafribubiBigusnulauGues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulaubiDaGubebofries" eType="//AlFribenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafriguBibufridafriBibuguscus" eSuperTypes="//Fagufrigubunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgunulAudaFribogusnulaufrigusBifriFriFries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebilus" upperBound="-1" eType="//Aubunulaudaguscio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubiBobodatin" eType="//DaDafribubiBigusnulauGues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusbenulauBufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusBiNulauguBunulAugugubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldaBeBigusfriFribibubunus" eSuperTypes="//AnnulauNulAugufridacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfribiBubibinulaubenulaulius" eSuperTypes="//BidafribogusbiDaNulaufritus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babibubegusbodaboBebifricus" ordered="false" eType="//FaBudabuBodabuDator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="efrigusgufriBeguGudabonulius" ordered="false" upperBound="-1" eType="//AlBeBugunulaufriboBefricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaubogufribudaCio" eSuperTypes="//AnfribonulaubugusdadabeguTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebubogusfriDabogunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbuGugugubugusbues" eSuperTypes="//BiBuBoGusbiGugunulaubudabeBilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBuBogusNulaudaCio" eType="//AnDaBifribiGuguNulaudabogubitus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebidafritus" eType="//EboBefriBufriguFrinulAutor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubiBebugusDaBebeGubibegusaulius" eSuperTypes="//DofrigusbubibuBedaCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dagubinus" eType="//BedaboFriFriFrifrigubibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBubegusauFriBoBeBibibuboTus" eSuperTypes="//Digugusnulaubububunus //BebobobeGuBibotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibibigusGubodabeboBicus" abstract="true" eSuperTypes="//DaNulaugusguDagubiFriboBoBulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bacus" upperBound="-1" eType="//DiFribogues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DudadanulauGusnulauBeBobutor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuDabebebigusnulAuTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albigusaubitin" eType="//AufribuguDabiguGusbiBebidaLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusAubuguBeNulauguses" eSuperTypes="//BeboFribudafriBiBufries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibeBubibugunules" eSuperTypes="//DiGusBobibibuGusAunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babudabeDaBecio" ordered="false" upperBound="-1" eType="//DobenulauguGubedanulEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbonulauDaGubebifricus" ordered="false" upperBound="-1" eType="//DigubegusbifriboDalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaufrigudanulauBoguscus" abstract="true" eSuperTypes="//EfribiBubibinulaubenulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaudabonulauBobodator" eSuperTypes="//BegusbibenulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBoDafriNulaufrifriCio" eType="//Autor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlaugusdaNulaufriBebulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubugusFribibuNulius" ordered="false" eType="//AlauGusfriFriboGusbibudaBiDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaguBobogusauBobobiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulAugusnulauboBibenulautin" eSuperTypes="//EubeGusFribuGubies //BraugusgusgugunulAufrigusgusfribibotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babogugusnulaugusdabobitus" eSuperTypes="//BeGusbuTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusnulAulius" eType="//EgusaubuBuBibinulaufribolus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beGusbiFrifrigusEs" eType="//DaBigusfriguGunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabuGuguDadabuBigudacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagubefriBobiBelus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Aubofribobebegusbetus" eSuperTypes="//BibigusBofrinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adafriGusNulaubocus" ordered="false" eType="//AlauguDabobutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DabiguGusnulaugusgusGuGues">
    <eLiterals name="Angusdafrinules"/>
    <eLiterals name="AnulauBoBubebegulus"/>
    <eLiterals name="EGusfriGububebobeBudadaLus"/>
    <eLiterals name="FafribubiGuguBodabogucus"/>
    <eLiterals name="DafriBoguBuguGusTin"/>
    <eLiterals name="FaBuDadafrigusNulauBebutin"/>
    <eLiterals name="AudaBebubonulaunulAuDacio"/>
    <eLiterals name="AnbidabiguBubodabobobuboBiDanulAulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubefrigusfriBiBifriboguEs" eSuperTypes="//BabibugusgusfribegusbuGusFriBifriEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuDagusauguscio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euboBinulauGuBobogufrinus" ordered="false" eType="//DabubibobugubiguboGuscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafriNulaudaLus" eSuperTypes="//BrauBubidanulAugusGusBoLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBebibeBonulauBuBuTin" ordered="false" upperBound="-1" eType="//AlauGusfriFriboGusbibudaBiDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobebubinulAuGutus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauBibifrigusaufrifrinulAuBeCus" eType="//DidagusnulaubeBenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anbogububitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadabiGusfridagusFriBotin" eType="//DadaguboBobonulAubobebedabuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagugusbobubunulaudabebunulAulius" eSuperTypes="//AgunulAudaFribogusnulaufrigusBifriFriFries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabibenulauFribiDafriDanulaudaGustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauDabuboBeGugugusnulaugusgustor" ordered="false" upperBound="-1" eType="//AnbiBoboFribiBebodagustus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albefriFriCio" eType="//AufribuguDabiguGusbiBebidaLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaububogusAuBegusgusBoNulAulus" ordered="false" upperBound="-1" eType="//AnbidanulAuDatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alnulaunulaubugusbubibonulAububiCus" eType="//DabiguGusnulaugusgusGuGues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifribeBibies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAunulaugusgusdabubofribofridafriFrigulus" eType="//EgusaubuBuBibinulaufribolus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusnulauboBoBeBedagusDabutus" eSuperTypes="//FaGunulAugusdalius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FanulAubebodaBinulIus" instanceTypeName="typeEbofriBudafribifrinulauGusaunulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBifridabeBegusNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AGusAuGusdabibiTus" instanceTypeName="typeBrauFriBibiboBoGuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudaDaFribeDaTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusfribufrifrigusFritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euFribufriDatin" upperBound="-1" eType="//DidagusnulaubeBenulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauboFribiGusbeBoBedaguLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBedabeBodabogusbunulius" ordered="false" upperBound="-1" eType="//DibebenulauGusBulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFriGusgusgusBuBudafrigubibofriBoFrinulautin" instanceTypeName="typeBraubobiGugusgusboDaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiDalius" abstract="true" eSuperTypes="//AnfriBeBubebifriBefriBinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBiGusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusbobobebiBiguBidaTus" eSuperTypes="//DogufribibiBeNulauTor //EgusnulauBidaBibubicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubeBuFribuBobidagusfrigusDacus" ordered="false" upperBound="-1" eType="//Anbogububitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaugubibeDabobefribubiLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabobebogusdadafrigusNules" eType="//BeboBonulauBubufriguBoEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlboBogusnulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiDanulaugusnus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBuGusfrigusauboBedabebeGutus" ordered="false" upperBound="-1" eType="//AlauguDabobutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabidaGusGuNulAubuBolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBeboGusBoBeFrinulaucus" ordered="false" upperBound="-1" eType="//EbeNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DobenulauBebogusbogusbifriboguTin">
    <eLiterals name="BrAuBodabebobegubunus"/>
    <eLiterals name="AlbubeGubeBoFriBobuGuCus"/>
    <eLiterals name="BiDaGuBoGubinus"/>
    <eLiterals name="AnBibeGuNulaubiNus"/>
    <eLiterals name="BeDabiBeboGusguBugusFribibigubolus"/>
    <eLiterals name="Babobogusgusdatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubeBugusbibogusbebelus" eSuperTypes="//AunulAufriDabuFribibifricus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubibeBogugubitus" upperBound="-1" eType="//DuDabebebigusnulAuTor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBuGuscio" eType="//BedaboFriFriFrifrigubibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabubebiBibufriNulautor" instanceTypeName="typeAlAubuFrigugusAububuGusGusbetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriBuBugusbiDafribufriBifribolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnAuboBoBebigusBinulaugusaucus" eSuperTypes="//BiNulAuGusBobuBulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBeBobubifrigusAubitus" ordered="false" eType="//BedaGusBuDafribofrigusnus"/>
  </eClassifiers>
</ecore:EPackage>
