<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fagusgusgufribies" nsURI="http://hub.de/rcore/examples/fagusgusgufribies" nsPrefix="Xw">
  <eClassifiers xsi:type="ecore:EEnum" name="AuBebiboBiGusBetin">
    <eLiterals name="Bebogusgubenulaudabobinus"/>
    <eLiterals name="AugusdabiDaes"/>
    <eLiterals name="AngugusbuBuBiGusbobonules"/>
    <eLiterals name="AlgusboNulauGuBogusgusnus"/>
    <eLiterals name="DagusnulauNulaubibeBuboNulauguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusbogusbidabeBodabotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubuBedaBebinulauDaguslus" ordered="false" upperBound="-1" eType="//EubefriBoboBiNulAubulius" eOpposite="//EubefriBoboBiNulAubulius/braugubifriBebebeBedanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BiguboBubiDadabuboTor" instanceTypeName="typeAbibenulauGusdaDafrifriBuBuGugusTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBeDaguBeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGuBegusguBebigububiTor" eSuperTypes="//EgusbogusbidabeBodabotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faboBinulAuDaNulauGusbegubiGunules" ordered="false" eType="//ABiNulAubogusgugusbeBudalus" eOpposite="//ABiNulAubogusgugusbeBudalus/brAuFribicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoFribugusauTus" eSuperTypes="//BrauGuBegusguBebigububiTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgunulauNulauBuBoCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBidaNulaubifridagusbiboes" ordered="false" eType="//DoFribugusauTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABiNulAubogusgugusbeBudalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuFribicus" ordered="false" eType="//BrauGuBegusguBebigububiTor" eOpposite="//BrauGuBegusguBebigububiTor/faboBinulAuDaNulauGusbegubiGunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbibebuBifribuGusbibuboNulaubidadafribeFries" eSuperTypes="//DoFribugusauTus //ABiNulAubogusgugusbeBudalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diFrinulaugudabebigutus" ordered="false" upperBound="-1" eType="//ABiNulAubogusgugusbeBudalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DububuBefribeBibedabuBubiBoBunulautus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbubuBobodaBoBeguFribufritor" ordered="false" upperBound="-1" eType="//DoBeDaguBeTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BidaBedabigusGusbigusAudabibenus" instanceTypeName="typeDigusbeDafridabibudabobugusfritor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DububeGusbegusgubulus">
    <eLiterals name="DifribigusBugusbeBuBiCio"/>
    <eLiterals name="BrauboGusbibedagusDanulAuCus"/>
    <eLiterals name="AlnulAuboboNulaunulautor"/>
    <eLiterals name="DaBidaBibibuGuBofribobibeNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubefriBoboBiNulAubulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auboBubeboLius" eType="//BiguboBubiDadabuboTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugubifriBebebeBedanus" ordered="false" eType="//EgusbogusbidabeBodabotin" eOpposite="//EgusbogusbidabeBodabotin/brAubuBedaBebinulauDaguslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbeboBobodabuDaes" eSuperTypes="//DoBeDaguBeTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbibugusDaGunus" instanceTypeName="typeAndabefrigusbegunulauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebegusgubufrifriGusnus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doNulaufriFribegusNulaucio" upperBound="-1" eType="//AbufriBeBugusAudator" eOpposite="//AbufriBeBugusAudator/benulaubiboDaFriguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBoBoBuGubugusnus" abstract="true" eSuperTypes="//ABiNulAubogusgugusbeBudalus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlfriGusgusBigusGuslus" instanceTypeName="typeBibobibubigubegusbolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBoBunulautor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabodagusnulaunus" ordered="false" eType="//BrauGuBegusguBebigububiTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusbogusBeNus" ordered="false" upperBound="-1" eType="//BebegusgubufrifriGusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubeDabebodabonulAubobuBoNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anbibegusbegulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAudabugububoBiDabelius" abstract="true" eSuperTypes="//BrauBoBunulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgufridaBees" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBibiBoGuBenulIus" ordered="false" eType="//FadafridabobiBofridalius" eOpposite="//FadafridabobiBofridalius/beBunulAuBigugubiguguBobeguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidagugusgunulauBiTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EububeBegusnulAuGusFrifricus" instanceTypeName="typeDubebibubilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaufriBeBugubebodaNules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuGusbibodafrifrilius">
    <eLiterals name="DugusBigusAubinulEs"/>
    <eLiterals name="DiNulaufriBinulaudaNulaubonulauTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubiNulaufribiFriBoboGulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biGudabuguboBiLius" eType="//AbibugusDaGunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudanulauguguBeGuBibitus" eSuperTypes="//DidagugusgunulauBiTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnboDafrigubobobeTor" instanceTypeName="typeEuNulaubibunulaufribedabelus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabubububoBugubebubuBodagutin" eSuperTypes="//DidagugusgunulauBiTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabofriBodabonules" instanceTypeName="typeAlbebiBebofrigues"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABedabogububiEs" eSuperTypes="//DububuBefribeBibedabuBubiBoBunulautus //AlnulaufriBeBugubebodaNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBiBenulauBeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadafridabobiBofridalius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBunulAuBigugubiguguBobeguscus" ordered="false" upperBound="-1" eType="//EgufridaBees" eOpposite="//EgufridaBees/beBibiBoGuBenulIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabiguBububeGuslus" upperBound="-1" eType="//DabubububoBugubebubuBodagutin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algufriDaBudaGufriNulEs" ordered="false" upperBound="-1" eType="//BrAubiNulaufribiFriBoboGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobibuguBiguGubies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euGusdabugububoBoTor" eType="//FabofriBodabonules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnfriNulauBibiBugusnulauFriLus">
    <eLiterals name="BiBegusbobinulauBebiCio"/>
    <eLiterals name="AudagufribofriDanus"/>
    <eLiterals name="Adagusbegusfridalus"/>
    <eLiterals name="FadagusbunulaudabebuBinulaubonulauBoBuBegusFriGucus"/>
    <eLiterals name="BigusboboBeguTin"/>
    <eLiterals name="DuBebogudagunulAulius"/>
    <eLiterals name="Algusnulaubebenulautin"/>
    <eLiterals name="AlaububeGubebonulauBibugusAuGunulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBoBuNulauDagugusgusbofriNulEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AugusBoguFriDabeFrigusLus" instanceTypeName="typeFabuFrinulaunulAuNulAuBebotor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiBofrifrinulauFridadaCus" instanceTypeName="typeAbunulaugubeBuNulAububulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulaubogusbifriBeBebofriguTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aldaBuNulaubuBoBetor" ordered="false" upperBound="-1" eType="//ABegudafribuFries" eOpposite="//ABegudafribuFries/dadagusbigubedaNulaubiNulauBebobenules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaguBiBidabibenulAulius" instanceTypeName="typeBraunulauBuBinulauGusDagusnus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EgusNulauBilus" instanceTypeName="typeAguNulAunulauLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAunulauBudaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annulaugubuNus" ordered="false" eType="//EudanulauguguBeGuBibitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaFribunulAububebonulAuCio" instanceTypeName="typeBefrinulauBuBogusgubuFribotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriBibibinulAunulaubibudaEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubugunulaubudaNulaudaLius" ordered="false" upperBound="-1" eType="//ABedabogububiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebuGusBoGubees" eSuperTypes="//ABiNulAubogusgugusbeBudalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobeBiNulAuBubutin" eSuperTypes="//DoFribugusauTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dadabeguBeboBofriBubuGufries" eType="//EububeBegusnulAuGusFrifricus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BafridaFriGuBebilus" instanceTypeName="typeBigusgubibiGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADaNulauGusGusbilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DidaBufribiGusnulaunus" instanceTypeName="typeDudabebebufribifribedabucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANulaubebecus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabedadadaGusnus" eType="//AuBebiboBiGusBetin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beboBobuGusfriDabuboBulus" eType="//BidaBedabigusGusbigusAudabibenus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubuGusbefriBobubebibebeBucio" instanceTypeName="typeBiguguFrifridanulaubotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABegudafribuFries" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadagusbigubedaNulaubiNulauBebobenules" ordered="false" eType="//ANulaubogusbifriBeBebofriguTin" eOpposite="//ANulaubogusbifriBeBebofriguTin/aldaBuNulaubuBoBetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeGusbefribebidanulaufriLus" eSuperTypes="//EuBiBenulauBeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbinulaugubefrinulAubedabunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EDabiguBitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafriGubudabugusBulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbobebifriBobogubinulaubiBiguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusdaFridabenulius" eSuperTypes="//ABiNulAubogusgugusbeBudalus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="afrinulAuCio" ordered="false" upperBound="-1" eType="//EbobebifriBobogubinulaubiBiguTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBugusbonulAuBibinulius" eSuperTypes="//BrAubiNulaufribiFriBoboGulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beFriGudaGunulauGusnulaudaBeFrinus" ordered="false" upperBound="-1" eType="//EudanulauguguBeGuBibitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbufriBeBugusAudator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="benulaubiboDaFriguses" ordered="false" upperBound="-1" eType="//BebegusgubufrifriGusnus" eOpposite="//BebegusgubufrifriGusnus/doNulaufriFribegusNulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Beguses">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fanulauBiGusaudabuBebeEs" eType="//DaguBiBidabibenulAulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBonulauNulAucio" eType="//AugusBoguFriDabeFrigusLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoboBoBubifritus" eSuperTypes="//ANulaubogusbifriBeBebofriguTin //DidagugusgunulauBiTus //ANulaubebecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusgubibibefrilius" eSuperTypes="//ABedabogububiEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubebeBogusgusbegugusBoboboDaNulIus" instanceTypeName="typeAnBuBunulaububuFriCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubebuBubebonulAutin" eSuperTypes="//EubefriBoboBiNulAubulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusGugusTus" eSuperTypes="//EubeDabebodabonulAubobuBoNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobebibuDabetus" eSuperTypes="//EudanulauguguBeGuBibitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifriBibonulAuGusbolius" ordered="false" upperBound="-1" eType="//AlgunulauNulauBuBoCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulAudaGusDaGusGusdanus" ordered="false" upperBound="-1" eType="//EuBiBenulauBeNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EuDabudafridaguBifriLus">
    <eLiterals name="BeguFribogusnulaugusgugunulAuboboes"/>
    <eLiterals name="Aubogubonulius"/>
    <eLiterals name="BebunulAuNulaunulauBugusNules"/>
    <eLiterals name="DuFriGudaDaBuGudaFribodaBebibunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiboNulAuBobeguBebeFrinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibuboBeBugugubogustus" upperBound="-1" eType="//AnbeboBobodabuDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AngusbedabebiboBofribocus" instanceTypeName="typeBaDaNulAufriGusnulaubebiNulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DububuFribidanulAuFriGuslus" abstract="true" eSuperTypes="//ABedabogububiEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eDaFriBeGufriGuscus" eType="//DaguBiBidabibenulAulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbegunulaugusBugufribicus" instanceTypeName="typeAlbiguBigusgusgunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ebogusnulaufritin" abstract="true" eSuperTypes="//AlnulAunulauBudaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaBubiBebeTor" ordered="false" eType="//EudanulauguguBeGuBibitus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubonulaugusbudaDabebotus" ordered="false" upperBound="-1" eType="//BebuGusBoGubees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AngusdanulAunulaucio">
    <eLiterals name="BeFriDanulAudabebuLus"/>
    <eLiterals name="BiDafriGusguguBiFriGusnus"/>
    <eLiterals name="BefriBibubibibinules"/>
    <eLiterals name="FaDabibigusgudanulius"/>
    <eLiterals name="DifriGusbibubodaguguguNulAulus"/>
    <eLiterals name="DadaNulauNulaunulaunus"/>
    <eLiterals name="DaBobuboBibeBebunus"/>
    <eLiterals name="AngufribeFrigusaunulAubeBibuBifrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibidadaNulauDafrigusFrifridaguBiNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DinulAuguboBudabubeBuguTus" instanceTypeName="typeDoBuDadanulAuGusDabeBuNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Babebogusgusbenulaubegubelus" eSuperTypes="//ABegudafribuFries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daguBiBugusBefribubogutin" ordered="false" eType="//DobibuguBiguGubies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobudaguDabeLus" eSuperTypes="//EubeDabebodabonulAubobuBoNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diNulaugusbuFrigugubuBiboCus" ordered="false" upperBound="-1" eType="//ABedabogububiEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAunulaubiBegusBibegufrifrinulaudaTus" eSuperTypes="//AlnulaufriBeBugubebodaNules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afribogusbegugusGuNus" eType="//AnboDafrigubobobeTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBuNulaubedadator" eSuperTypes="//EudanulauguguBeGuBibitus //AlnulAunulauBudaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubeBegusaugusLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digusbofriDaBifribebiGuTus" eType="//AngusbedabebiboBofribocus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aububugubobufriBuboboTin" ordered="false" upperBound="-1" eType="//BrauGuBegusguBebigububiTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibeFribiBifribuGusdabeLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaDabibeBuDabibebubebotin" instanceTypeName="typeEuGusbuBeGugugubefriNulaubebetor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbidagusboDaLus">
    <eLiterals name="BaboNulaufries"/>
    <eLiterals name="Dogusbufrigusnulaugudalius"/>
    <eLiterals name="AgusauBoBufribunulAubibubiEs"/>
    <eLiterals name="AlbuGubegufricio"/>
    <eLiterals name="DonulAuBubiGubuGusAunulautus"/>
    <eLiterals name="BinulAugubebeBuLus"/>
    <eLiterals name="AnFrigusGusGusBoBebebogubebolus"/>
    <eLiterals name="FadaBibodaTor"/>
    <eLiterals name="AlbebebigusnulaubuguDabebedatin"/>
    <eLiterals name="DogusBobifriBuCio"/>
    <eLiterals name="FagusnulauDaBefribiguboBobeDabebilus"/>
    <eLiterals name="AnBedanulaufrifrifridaGugusbegucus"/>
    <eLiterals name="DoGuGusdafrigufribuGubelus"/>
    <eLiterals name="Braubobedagusgubebicio"/>
    <eLiterals name="DabuBiBebebobeBiBeEs"/>
    <eLiterals name="BafriNulaubedaNulAuFriNulaubifriNulius"/>
    <eLiterals name="FaGusNulAuNulaubiGusLius"/>
    <eLiterals name="BaboDaBebibegusfribubenulaunulautin"/>
    <eLiterals name="Begudabibedanulauguscus"/>
    <eLiterals name="AubebeDadabofriBiTor"/>
    <eLiterals name="DobibuBebecus"/>
    <eLiterals name="BrAuGusFribufriGusaufributus"/>
    <eLiterals name="ABiNulauDaGuboguBibuTor"/>
    <eLiterals name="FaDanulaudaBibogusguBibitin"/>
    <eLiterals name="AbogufriDaBiTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BidabuNulaubobebeGuGusdator" instanceTypeName="typeDinulauboBudabifrigucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusBibiguscio" eSuperTypes="//AlnulAunulauBudaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDabebuguGusFrigusnulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusBedaDaBenulauFriGubudagucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauDagusgusbiguGusaubeBeGubibutin" ordered="false" upperBound="-1" eType="//BrAubiNulaufribiFriBoboGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubeguBuboTus" instanceTypeName="typeDafrifriFrinulAuNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBiGusNulAugusnulEs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusdaBogubitus" ordered="false" eType="//AnbeboBobodabuDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabinulaubuGuBegusBebicus" instanceTypeName="typeDaNulauGusnulaufridafrifribiBobeguscio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgufrinulaunulAugusnules" instanceTypeName="typeDuDanulauGusBeFriFricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBoGusnulaugusLus" eSuperTypes="//AnbeboBobodabuDaes //AlnulaufriBeBugubebodaNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebobenulAubegunulAuBuBebicus" eType="//EgufridaBees"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaGusboBiboBobunus" upperBound="-1" eType="//EuBiGusNulAugusnulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabifrifriLus" instanceTypeName="typeFagusAuBubudabifriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndanulAuGuBuDabugutus" eSuperTypes="//BrauBoBuNulauDagugusgusbofriNulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaugufriGusdacus" ordered="false" upperBound="-1" eType="//AlnulaufriBeBugubebodaNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaBiBiGuBunulaudabegufrifritor">
    <eLiterals name="AugusnulaubiGuGunulauguTor"/>
    <eLiterals name="DiGuDabiBoBuguGusFrifrigusbonulAuguNulauNus"/>
    <eLiterals name="BaFriBudagunulAuBuDagusgustor"/>
    <eLiterals name="EDaboButus"/>
    <eLiterals name="BibuGusgusnulauFricus"/>
    <eLiterals name="DibeguFriboBiFriBoFritor"/>
    <eLiterals name="BenulAuguGusbofriGusnulAuGusBeFribibotin"/>
    <eLiterals name="BraubidabinulauBulius"/>
    <eLiterals name="EbebigugusBiFries"/>
    <eLiterals name="FadagunulAufrifribubeBubeBigusbotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaguNulaufribibugusdagustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbudaBoGuBubicio" ordered="false" eType="//EudanulauguguBeGuBibitus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digubiBuBibufriBilus" ordered="false" eType="//EubefriBoboBiNulAubulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabubobibebibunulAuFrifribuDaboGudator" eSuperTypes="//AlgunulauNulauBuBoCio //DububuFribidanulAuFriGuslus //DoFribugusauTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBoNulaubedaGuGubigubobiBiCus" ordered="false" eType="//AlgusBedaDaBenulauFriGubudagucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagugusBiGufribobugusdaes" eSuperTypes="//DoFribugusauTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiboBuGuNulEs" ordered="false" eType="//DigusGugusTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulAufribuNulaububulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfrigusBinus" eSuperTypes="//BagusdaFridabenulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DabobibebobebuFriboDafribiDatin">
    <eLiterals name="AlboBibebiGufriNulauguCus"/>
    <eLiterals name="Alnulaubifribifribibotin"/>
    <eLiterals name="AuFrigusbiCus"/>
    <eLiterals name="DigusBifriCus"/>
    <eLiterals name="DuGufriBeNulauGusbues"/>
    <eLiterals name="DabubuBudanulauBodabinulaubuFrifritus"/>
    <eLiterals name="FanulauGubiguscio"/>
    <eLiterals name="BaboBidafribifriDabuNus"/>
    <eLiterals name="ENulAuBobenulAubinulautus"/>
    <eLiterals name="BefriNulaubifriGuBilus"/>
    <eLiterals name="DiboFrifrigusnulaufriFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebiBegugusaunulius" eSuperTypes="//DuGusgubibibefrilius //BebegusgubufrifriGusnus //DobebibuDabetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBiboBibubilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibiGusbigusGusauguTor" eType="//BaBiBiGuBunulaudabegufrifritor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBudaBogudaBoguGusaubolus" instanceTypeName="typeEuDagusgustus"/>
</ecore:EPackage>
