<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="alautor" nsURI="http://hub.de/rcore/examples/alautor" nsPrefix="NXq">
  <eClassifiers xsi:type="ecore:EClass" name="BafridabiNulaunulAubobetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anaububenulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaunulAubefritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbubuFries" abstract="true" eSuperTypes="//BafridabiNulaunulAubobetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusbufribobenus" eType="//AFriNulAuDadabefrinulauDabubitin" eOpposite="//AFriNulAuDadabefrinulauDabubitin/baBofribunulAudaboBuBiBofribonulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AFriNulAuDadabefrinulauDabubitin" eSuperTypes="//AnbubuFries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBofribunulAudaboBuBiBofribonulIus" ordered="false" eType="//AnbubuFries" eOpposite="//AnbubuFries/fagusbufribobenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AubunulaugugusgusAuFriBetin" eSuperTypes="//AFriNulAuDadabefrinulauDabubitin //Anaububenulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dububebufrigunulaunulius" abstract="true"/>
</ecore:EPackage>
