<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="albegusbobobinulius" nsURI="http://hub.de/rcore/examples/albegusbobobinulius" nsPrefix="fr">
  <eClassifiers xsi:type="ecore:EClass" name="EGusbibenulaudabubofriboboLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBoGusauBeBegububoguBidabeCus" ordered="false" upperBound="-1" eType="//BegusbinulauBodacus" eOpposite="//BegusbinulauBodacus/brauGusdabifribifriGucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnFrigusbinulAubeguGulius" abstract="true" eSuperTypes="//EGusbibenulaudabubofriboboLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BeDabibebibugusLus" instanceTypeName="typeDubugusbeNulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusBuBibudagusnulauBeBufriTin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BinulaunulAubiBuboGuNulaugusTor">
    <eLiterals name="BrauBuGubutus"/>
    <eLiterals name="BraudaGusbobebubeboGunulauguCio"/>
    <eLiterals name="EugusauNulAugusfriNulaububucio"/>
    <eLiterals name="AlbobiBugusgufribeFriBobuGutor"/>
    <eLiterals name="DaGubefriDaBibeBuGusbedacio"/>
    <eLiterals name="DogufrigubiboBubuBenulAutor"/>
    <eLiterals name="BegusBeBobofribibetin"/>
    <eLiterals name="AdafridaguGusFriBuGusfribebeBiBiGubilus"/>
    <eLiterals name="FabebuBegudaGusFrigusFriGubofrilius"/>
    <eLiterals name="BrAunulaugusbuDaGusGusbenules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibedaBefrifrinulaunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobegusBeboboguscus" eType="//BeDabibebibugusLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGuNulaubibudabubibebugugusButor" ordered="false" upperBound="-1" eType="//ENulauGubufribubiBibidaTus" eOpposite="//ENulauGubufribubiBibidaTus/audagusGubugufriDabitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGubobiFriGuBedaguFribiBecio" abstract="true" eSuperTypes="//AugusBuBibudagusnulauBeBufriTin //EGusbibenulaudabubofriboboLus //AnFrigusbinulAubeguGulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braububobuGubibitin" eType="//BeDabibebibugusLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afriboBeGusnulauNulauBuBoNulaugusGubugudaLius" ordered="false" eType="//EugusgusNulaubibinulius" eOpposite="//EugusgusNulaubibinulius/dubiBenulaunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusFriDaBitus" eSuperTypes="//BibedaBefrifrinulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubiGusfribuBeCus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiDabeGusbebiFribigusfriDaEs">
    <eLiterals name="DibogusbuNulAubedabifriCio"/>
    <eLiterals name="BibeBoFribeBoboguscio"/>
    <eLiterals name="AnauboBebeFriboBinus"/>
    <eLiterals name="BrauGunulaugusGuboBiLius"/>
    <eLiterals name="DodagusbugusbifribigubeDadabiCio"/>
    <eLiterals name="DoBedafribebeGusLius"/>
    <eLiterals name="AlaubebuNulaugusBubuBotin"/>
    <eLiterals name="EDagufribuBodadabolius"/>
    <eLiterals name="DabebibudadagugusfriBees"/>
    <eLiterals name="BabiBigusbobogusfriBobees"/>
    <eLiterals name="AnbobubeNulAuBoBobiGusnulEs"/>
    <eLiterals name="ABeNulauDabiBeCio"/>
    <eLiterals name="EnulAugusGuscus"/>
    <eLiterals name="BiBiFriGusGuboGudagubibufrigunus"/>
    <eLiterals name="AnbibobiGubebobuGuDabegutor"/>
    <eLiterals name="Aubefrifribunules"/>
    <eLiterals name="EBefribebigusbigunulAubibebobigutin"/>
    <eLiterals name="EnulaubiBobuDaDaFridanulAuGues"/>
    <eLiterals name="BraubeDaBiBebobeGubebeTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BifriBinulaugunus" eSuperTypes="//EGusbibenulaudabubofriboboLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusBidabufrigusdanulauBogusAutin" ordered="false" upperBound="-1" eType="//EGusbibenulaudabubofriboboLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuguGudabuNulauGuBenulAunules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braufribibees" eType="//BeDabibebibugusLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegusbinulauBodacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGusdabifribifriGucus" eType="//EGusbibenulaudabubofriboboLus" eOpposite="//EGusbibenulaudabubofriboboLus/duBoGusauBeBegububoguBidabeCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusgusDabiDator" eSuperTypes="//BibedaBefrifrinulaunus //AnFrigusbinulAubeguGulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anAuBegudabegusgusgusdadaBiBoEs" ordered="false" upperBound="-1" eType="//AugusBuBibudagusnulauBeBufriTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daGuGudaGubunulAudaNulautus" ordered="false" eType="//DubiGusfribuBeCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiNulaububuguboboBuBuTin">
    <eLiterals name="BibufrinulAubebeDaBebotin"/>
    <eLiterals name="DoGubefrigusbibeDagusLus"/>
    <eLiterals name="EbubebodaboLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabubigusgufriGusGuBebinulauCus" eSuperTypes="//AuguGudabuNulauGuBenulAunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dodabogusautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebebibeDabogusbobodabugugufriBonus" eSuperTypes="//EGusbibenulaudabubofriboboLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubefribegusbobugubuBiGutor" ordered="false" eType="//EuGubobiFriGuBedaguFribiBecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusgusNulaubibinulius" eSuperTypes="//AnFrigusbinulAubeguGulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eudaFrinulaubeguBolius" eType="//BeDabibebibugusLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubiBenulaunulEs" ordered="false" upperBound="-1" eType="//EuGubobiFriGuBedaguFribiBecio" eOpposite="//EuGubobiFriGuBedaguFribiBecio/afriboBeGusnulauNulauBuBoNulaugusGubugudaLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubogusBuGusGusboFridaNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdabuGusnulauguBuguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaDadanulaufrinulius" eSuperTypes="//BegusbinulauBodacus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulauBodaGudagusgusgusnulAuNus" ordered="false" eType="//DubiGusfribuBeCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabedafriBobebuNulautor" eSuperTypes="//EuGubobiFriGuBedaguFribiBecio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBodafriNulaubuTus" eType="//DiDabeGusbebiFribigusfriDaEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBedaGuBiBoBubucio" ordered="false" eType="//BebebibeDabogusbobodabugugufriBonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulaugusbubibiDaBotin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusBebogusbobucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENulauGubufribubiBibidaTus" eSuperTypes="//DodaDadanulaufrinulius //EgusgusDabiDator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audagusGubugufriDabitus" ordered="false" upperBound="-1" eType="//BibedaBefrifrinulaunus" eOpposite="//BibedaBefrifrinulaunus/doGuNulaubibudabubibebugugusButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFridabudagusBiBogubebitin" eSuperTypes="//DubiGusfribuBeCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euDaBoBibobogusBeNus" ordered="false" eType="//Egusbubigusbicio" eOpposite="//Egusbubigusbicio/eGusBebiBeguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BibiBebiGuGusfridaDaCus" instanceTypeName="typeDonulauBebibeDaBebuBeguNulAuFricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EunulAubibebuTor" eSuperTypes="//EuGubobiFriGuBedaguFribiBecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbifriguFridafribubegunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaguscio" ordered="false" eType="//AdabuGusnulauguBuguCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGubogudabiBibiGuBeDaBodanulEs" abstract="true" eSuperTypes="//EgusgusDabiDator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoboBoGusfribinulIus" abstract="true" eSuperTypes="//BebebibeDabogusbobodabugugufriBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBefribubiBibefriDaguguEs" ordered="false" eType="//FabigusAuBinulauBenulIus" eOpposite="//FabigusAuBinulauBenulIus/edagufribeBeBebedagusbuDaTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DubiGuscio" instanceTypeName="typeAbugubobiBeFribiEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaFrigubeboNulaubebedanulAugusTus" instanceTypeName="typeAnBubigusAuBeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabeGusbodadaBebufribiGuBotus" abstract="true" eSuperTypes="//EubogusBuGusGusboFridaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibodafriBeBudabuGuTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibiBuguDanulauFriBebebotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braubogutus" eSuperTypes="//DibodafriBeBudabuGuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigubibogubobuNulEs" abstract="true" eSuperTypes="//BanulaugusbubibiDaBotin //BebebibeDabogusbobodabugugufriBonus //AdabuGusnulauguBuguCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagubebibegusaugufrigusbiLius" upperBound="-1" eType="//DubiGuscio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubeguboboBoguBibibeBebibefrinules" eSuperTypes="//DabubigusgufriGusGuBebinulauCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="banulauBinulAuGusguNulauboNulAuGubenus" ordered="false" eType="//BaGubogudabiBibiGuBeDaBodanulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugugububugusfriCio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulAufriGusAugusFrigusTin" ordered="false" eType="//BrauGusBebogusbobucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgusgusBibedabuCus" eSuperTypes="//EgusgusDabiDator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulauBobibeNulauDanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubuFrifrigusaufribuGuCio" eSuperTypes="//DabubigusgufriGusGuBebinulauCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidafrifrigusFritin" eSuperTypes="//BebebibeDabogusbobodabugugufriBonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusfriNus" eSuperTypes="//AlbibiBuguDanulauFriBebebotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBebebeGusbofrigusbutor" abstract="true" eSuperTypes="//EugusgusNulaubibinulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubonulaubuBoGusBolius" eType="//BeDabibebibugusLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlAuGusBebigusautor" instanceTypeName="typeDoboguBiGuBiBudaGuscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulAubebuGugusbeBibubuGusaulus" eSuperTypes="//EuGubobiFriGuBedaguFribiBecio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuNulauBogusgusBinulauBunules" ordered="false" eType="//EugusgusNulaubibinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BafrinulAuGusboFridabidaguGuBeFribubees" eSuperTypes="//AugusBuBibudagusnulauBeBufriTin //EubeguboboBoguBibibeBebibefrinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="Egusbubigusbicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eGusBebiBeguscus" ordered="false" upperBound="-1" eType="//BiFridabudagusBiBogubebitin" eOpposite="//BiFridabudagusBiBogubebitin/euDaBoBibobogusBeNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusfrigugusFriLus" eSuperTypes="//EubeguboboBoguBibibeBebibefrinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufrifribogusaudagusFriNulaulus" ordered="false" upperBound="-1" eType="//BaGubogudabiBibiGuBeDaBodanulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusBigusdabeBoguBigudatus" eSuperTypes="//FabeGusbodadaBebufribiGuBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauDaBuguBogusguDagubotin" eSuperTypes="//AdabuGusnulauguBuguCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiNulAugusbigulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DibiBeBoNulAulus">
    <eLiterals name="BrAuBubobobigusnulAuTus"/>
    <eLiterals name="BaguboGugusNulaudaguBobigusgugufrinules"/>
    <eLiterals name="BraubiBugugusbedagusaugutin"/>
    <eLiterals name="AnGuBinulaulius"/>
    <eLiterals name="AbuBufribuBubifriBeGusCus"/>
    <eLiterals name="DafridanulaubenulAuBubuBeGuGusbetin"/>
    <eLiterals name="DibibuBenulaulus"/>
    <eLiterals name="ANulAubebifribebiBiBinulauBotin"/>
    <eLiterals name="AnulAuGusaulus"/>
    <eLiterals name="DanulAudaDabedatus"/>
    <eLiterals name="BeBoBugusbebeBugubegutin"/>
    <eLiterals name="Anbogusbebibutor"/>
    <eLiterals name="EBubeguBeDaBebuBoes"/>
    <eLiterals name="DoGuguBiNulaububiGutin"/>
    <eLiterals name="AngusfrifribiBudacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeBudabiFriBoguDabuBoBugufribufritus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebubonulAuGutus" instanceTypeName="typeAuBoGuBitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusGusgugusAubigusnules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubifriguBebeguscio" ordered="false" upperBound="-1" eType="//AnbifriguFridafribubegunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ABibuFribuDaDaBiGusGufriDaFrinus" instanceTypeName="typeAlgusnulaugunulaubufrifriBibobotor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBobebegubitor" instanceTypeName="typeDoFrifribubunulauBeEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubogusNulauBibobofrigufrinulaugusbitus" instanceTypeName="typeBrauboNulauGufriGubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabigusAuBinulauBenulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edagufribeBeBebedagusbuDaTin" ordered="false" eType="//DoboBoGusfribinulIus" eOpposite="//DoboBoGusfribinulIus/anBefribubiBibefriDaguguEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbubiboBubogusFrigugubunulautor" abstract="true" eSuperTypes="//DodaDadanulaufrinulius //EugusgusNulaubibinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeGuBenulius" eSuperTypes="//BiFridabudagusBiBogubebitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begusdaguBibitus" upperBound="-1" eType="//BebubonulAuGutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlnulauNulauBiguBinulAulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBogusAugusgusdadaGusLius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusfriBibugubufriEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAuGuFriBoNulaubonulAuguCio" instanceTypeName="typeBaBoNulauBeguEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboBedaBoFribiBicio" eSuperTypes="//BrAulus //EunulAubibebuTor //BiNulAugusbigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbofrifriBebiBiBunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibubeBefriDabulius" upperBound="-1" eType="//DaFrigubeboNulaubebedanulAugusTus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
