<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="donulaunulautus" nsURI="http://hub.de/rcore/examples/donulaunulautus" nsPrefix="BCEC">
  <eClassifiers xsi:type="ecore:EClass" name="AuGunulaugusnulaugues" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EugufriBidabubebebeGusnus" instanceTypeName="typeDobibeBegusbubobibibeLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnBenulAunulAucio" instanceTypeName="typeBibonulaugusGuscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusaunulauDabenulaubugusguslus" abstract="true" eSuperTypes="//AuGunulaugusnulaugues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulauGubeFribebebinulauNus" upperBound="-1" eType="//AuGunulaugusnulaugues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusBibuFridabiCio" eSuperTypes="//AuGunulaugusnulaugues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubebobeFrifrigusbigusLus" ordered="false" upperBound="-1" eType="//Albebifrilus" eOpposite="//Albebifrilus/dibegusbeBeNulaudanulautus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGuBiNulaubeBodabeBicus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doBebobodaguboes" eType="//EugufriBidabubebebeGusnus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abibunulauBibiBuEs" eType="//AnBenulAunulAucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Albebifrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baNulaugusfries" ordered="false" eType="//AuGunulaugusnulaugues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibegusbeBeNulaudanulautus" eType="//AlGusBibuFridabiCio" eOpposite="//AlGusBibuFridabiCio/eubebobeFrifrigusbigusLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGusBoGufribibeNulaubiNulaudaEs" eSuperTypes="//DaGuBiNulaubeBodabeBicus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnbubiDaDagusguBedadanus" instanceTypeName="typeBaBigugusFrinulAufribibicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibuBeBinulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AudadafrifriBicus" instanceTypeName="typeDaGusFrinulaunulAubenulaunulaufrinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugufriLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubububugubiBonulauNulEs" instanceTypeName="typeDobubogusnulaugubogustin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FabinulAufriFrigulius" instanceTypeName="typeBrauButus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBebebigusauGufriBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaubobenulauBiEs" eSuperTypes="//BibuBeBinulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulaubigusbibubiFriDabecus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angugugusBifribunulauGuBibiBeBicio" eType="//AnbubiDaDagusguBedadanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABubibobeDafribinulauNulaufrinulIus" eSuperTypes="//AuBebebigusauGufriBinus //DaGuBiNulaubeBodabeBicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuFriBiBibebuFrigusius" eSuperTypes="//AlGusBibuFridabiCio //Albebifrilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alBiBeBeBiguTor" eType="//AudadafrifriBicus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulauDadaGulius" upperBound="-1" eType="//AnBenulAunulAucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugusNulAuGugusbinulautus" eSuperTypes="//AuGunulaugusnulaugues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaBubuDaBidabodabugusgusauBulius" abstract="true" eSuperTypes="//AuGunulaugusnulaugues"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufribuFrigubiboBigugucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENulAuguBoBoBubeboboTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AngusbugudaBuGunulaubolius" instanceTypeName="typeBanulaugugusFrigunulaubiLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BibububeboBeNulauBibubucio" instanceTypeName="typeBabonulaunulauBiBicus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuFribifribifrifriguguTus" eSuperTypes="//DaGuBiNulaubeBodabeBicus //ENulAuguBoBoBubeboboTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abufriNulaubuguNulauDagusBubutor" ordered="false" upperBound="-1" eType="//AGusBoGufribibeNulaubiNulaudaEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabibefriDagusdaGusguGubenus" eSuperTypes="//Albebifrilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebibubiGusboBinulauTin" ordered="false" upperBound="-1" eType="//AGusBoGufribibeNulaubiNulaudaEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusbogubuFrigusbubenulautin" abstract="true" eSuperTypes="//ENulAuguBoBoBubeboboTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuBebobebububibebiBiBeFriLius" instanceTypeName="typeAlBebibobufriBufricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusBobeFrinulius" eSuperTypes="//EugufriLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebegugusnulAubuguDanus" ordered="false" upperBound="-1" eType="//DiGusaunulauDabenulaubugusguslus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusbodaBuDaGubuNus" upperBound="-1" eType="//ABubibobeDafribinulauNulaufrinulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlGuBonulAuBuBofrigutus" eSuperTypes="//AGusBoGufribibeNulaubiNulaudaEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braububonulaubefrifridabetor" eType="//EubububugubiBonulauNulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADabuguGuGuGusgugusGusius" abstract="true" eSuperTypes="//DanulaubobenulauBiEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiFrifriguBeGusgubofriButus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubebodaBoguBodaboBucus" eSuperTypes="//AlGusBibuFridabiCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeDaBogusgusGuscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBeBufribugusBoLius" abstract="true" eSuperTypes="//DiGusaunulauDabenulaubugusguslus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlnulAubegubiGugusBegustus">
    <eLiterals name="AnbobuBubebubenulius"/>
    <eLiterals name="FadadafriguFridaboNulaubocus"/>
    <eLiterals name="DaBebubebonulAuboboLius"/>
    <eLiterals name="AuGuboBunulAugufridatus"/>
    <eLiterals name="BabedabiBugusdanulauGulus"/>
    <eLiterals name="ABunulauboBobofriBibenus"/>
  </eClassifiers>
</ecore:EPackage>
