<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="babobibonus" nsURI="http://hub.de/rcore/examples/babobibonus" nsPrefix="BsX">
  <eClassifiers xsi:type="ecore:EClass" name="BedaBunulaudagusbebugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fafriguguslus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobenulAubefridaNus" ordered="false" upperBound="-1" eType="//BedaBunulaudagusbebugutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulaubedaDafrinulaufriCio" ordered="false" upperBound="-1" eType="//DagusguTus" eOpposite="//DagusguTus/braubebuNulAucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulAugugusbubidaLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafribuFrigusaubeboGuguGuLus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EgugubefriDagusbobigubitin" instanceTypeName="typeBeNulAugusbiNulaudabees"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusfrifriDadagustin" abstract="true" eSuperTypes="//BedaBunulaudagusbebugutor //BafribuFrigusaubeboGuguGuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubuBogusAugugubonulaudaBeFriBotin" abstract="true" eSuperTypes="//Fafriguguslus //BafribuFrigusaubeboGuguGuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agubedafribunulaubuBegubiTus" ordered="false" eType="//BafribuFrigusaubeboGuguGuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadabegusbuGubidagustor" eSuperTypes="//AubuBogusAugugubonulaudaBeFriBotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egugugusgusNus" eType="//EgugubefriDagusbobigubitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBufribuBobubugusbifriBenulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulaubibebuBecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogusBufrifrinulauGuBitor" eSuperTypes="//ENulAugugusbubidaLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doBebuguslius" eType="//EgugubefriDagusbobigubitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabifriFriguBobubigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbibugusgusbiCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulaubuGubocus" ordered="false" upperBound="-1" eType="//DaNulaubibebuBecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulauGunulaudafribenus" eSuperTypes="//BedaBunulaudagusbebugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlboBifrigubudatus" eSuperTypes="//DanulauGunulaudafribenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusguTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doBeDaBidaBebugusautor" eType="//EgugubefriDagusbobigubitin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubebuNulAucus" ordered="false" upperBound="-1" eType="//Fafriguguslus" eOpposite="//Fafriguguslus/dinulaubedaDafrinulaufriCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alAugugulius" eType="//BedaBunulaudagusbebugutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ADaguGuFrigusdabuNulaubibeboLius" instanceTypeName="typeDiboNulAubedadaBobiBibeDator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugusDabogusgusBotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aunulaububebunulauTin" eType="//EgugubefriDagusbobigubitin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibibifriBifridaguBiLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldaBoGuDabebeBugusBonules" eSuperTypes="//BedaBunulaudagusbebugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubugubedaGusdabuGusbebubuTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBoBiBees" ordered="false" eType="//BabifriFriguBobubigulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubobiGusgusbecus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebufridanulauBugusNulaubecio" eType="//ADaguGuFrigusdabuNulaubibeboLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AgusAufrigusnulAulius" instanceTypeName="typeBibubudagusdalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBebuFriBobibuBoFriLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulaubebebibedabubuFribigusbitor" ordered="false" eType="//DanulauGunulaudafribenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBuDaBubigudabobiEs" eSuperTypes="//BedaBunulaudagusbebugutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusnulaufrinulauDanulius" eSuperTypes="//BrAugusDabogusgusBotin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagusbibegusbiNulautin" eType="//AgusAufrigusnulAulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFriNulauGubiBofrigubububutus" eSuperTypes="//BafribuFrigusaubeboGuguGuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufriFrinulAunulEs" ordered="false" upperBound="-1" eType="//DiBufribuBobubugusbifriBenulaucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auDabuNulAuguGusBegusNules" ordered="false" eType="//BabifriFriguBobubigulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibufricio" eType="//AgusAufrigusnulAulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibobebobedagusbuBegugusgusgusCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubeBidabobiBoBonulAunulaulus" eType="//AgusAufrigusnulAulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibubugufriFribugufribolius" ordered="false" eType="//DibibifriBifridaguBiLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulaubuDaBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Badafridabulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusBuBeBoBiCus" ordered="false" eType="//AlboBifrigubudatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difrifrifrigusGubegusFrinulIus" ordered="false" upperBound="-1" eType="//BibobebobedagusbuBegugusgusgusCus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebobebiFriBonulEs" eType="//ADaguGuFrigusdabuNulaubibeboLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabeboCio" eSuperTypes="//AlboBifrigubudatus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BigubiGusguguGusgulius">
    <eLiterals name="BaNulaubobigubugutin"/>
    <eLiterals name="DaBobuNulAubiFrinulauGuGuboGusfritor"/>
    <eLiterals name="FadagusgusbiGusBibegudaGubibibeLius"/>
    <eLiterals name="AubofrinulAunulauBufribogusBeBogustor"/>
    <eLiterals name="EBubufribibeDaboBoBilus"/>
    <eLiterals name="BrAubebobebeguTor"/>
    <eLiterals name="DibuGubenulius"/>
    <eLiterals name="EfriNulAugudabufriGunus"/>
    <eLiterals name="DuBubibibefrilus"/>
    <eLiterals name="DobibedabeBigucio"/>
    <eLiterals name="AuguGubeBebubiBolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGusfribobibuBunulaugusBelius" eSuperTypes="//AlboBifrigubudatus"/>
</ecore:EPackage>
