<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="babegustin" nsURI="http://hub.de/rcore/examples/babegustin" nsPrefix="PqT">
  <eClassifiers xsi:type="ecore:EDataType" name="EFribigusdatus" instanceTypeName="typeAubifrigusbonulAubiBodadabugusNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlAufrigubuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBuGububefrinulAugunulEs" eSuperTypes="//AlAufrigubuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidanulaufribiFridabetin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDaboGusdadaGunulAunulaubibiBuBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudadagusfriNulauBiBilius" abstract="true" eSuperTypes="//AlAufrigubuNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulauFrinulaugusFriBidafriNulauGugusgusBoNus" ordered="false" eType="//DaDaboGusdadaGunulAunulaubibiBuBinus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dafriFrifrifrifriBugusNulauTin" upperBound="-1" eType="//EFribigusdatus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodabonulAubinulAuTin" eSuperTypes="//DaDaboGusdadaGunulAunulaubibiBuBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudabobubuFriguses" eSuperTypes="//DudadagusfriNulauBiBilius //DodabonulAubinulAuTin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobubonulaubuBobiBegusBuTor" instanceTypeName="typeABegufribibidabeGuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusauNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudadaBeBibuFriBuLius" eSuperTypes="//EudabobubuFriguses //BidanulaufribiFridabetin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auDaDagusdaes" eType="//EFribigusdatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGububonulauFribuBuButus" ordered="false" upperBound="-1" eType="//DudadagusfriNulauBiBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abubutin" eSuperTypes="//DodabonulAubinulAuTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badaboBubifribebonus" ordered="false" upperBound="-1" eType="//DubinulAubeDaCus" eOpposite="//DubinulAubeDaCus/alDabonulaunulAunulAuBunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusbobuguBedadabigusnulIus" eSuperTypes="//DudadagusfriNulauBiBilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fagubuCus" eType="//DobubonulaubuBobiBegusBuTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlDaBiBigunulAugusBedadabiLus" instanceTypeName="typeDogusdaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABuBonulaudagubecio" eSuperTypes="//AlAufrigubuNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FanulAubeBigufriNulAuboTin" instanceTypeName="typeBaboFriBigusbiBinulAubibibiNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudagubuguDafribiEs" eSuperTypes="//DaDaboGusdadaGunulAunulaubibiBuBinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agubibidabunulius" eType="//EFribigusdatus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusgudabuNules" ordered="false" upperBound="-1" eType="//DiGusbobuguBedadabigusnulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbibefrigusdagudabobeFribuboBuBuLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eboGusBoBeNulaudanulauGuBobocio" ordered="false" eType="//BidanulaufribiFridabetin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusnulauFriGusBebubebinulaulus" ordered="false" eType="//DudadagusfriNulauBiBilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaBiBunulautin">
    <eLiterals name="AlGuGusgufribofrigusbuCio"/>
    <eLiterals name="DabuguDanulius"/>
    <eLiterals name="BifrinulaunulauTus"/>
    <eLiterals name="EnulaunulauguDaBeGusbugues"/>
    <eLiterals name="Danulaudagubibutus"/>
    <eLiterals name="EgubigusBiguGudanulaubetus"/>
    <eLiterals name="AgusBegusFriBebitor"/>
    <eLiterals name="DuBoDagusbuboDaCus"/>
    <eLiterals name="BaDabogusauguBiguTor"/>
    <eLiterals name="DiGugusbenulaugusbobegusbubebucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabiBebinulAunulAubiNulAubefriBuBulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaGubigubobubonulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eugudaNulaugustin" eType="//BaBiBunulautin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagufriFriDaboDaCus" upperBound="-1" eType="//DugugusaubiboboGusdafribefriBocus" eOpposite="//DugugusaubiboboGusdafribefriBocus/anbuBebibebubibegusfribues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusbunulauGusnulauFriBiboNulauBubifrilius" abstract="true" eSuperTypes="//AlAufrigubuNules //DiGusbobuguBedadabigusnulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aNulaubedaguDaBedadaDadabenulauGuslus" ordered="false" eType="//ABuBonulaudagubecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DabobiguGudabugusfrigulus" instanceTypeName="typeFabibogusDadabofrigusCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabefriguboBonulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBoBeBogubotin" eSuperTypes="//BraudagubuguDafribiEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="didaDaDagusgulus" upperBound="-1" eType="//FanulAubeBigufriNulAuboTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBoDadaGusnulAubecus" eSuperTypes="//Abubutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibiGubeFrigunus" upperBound="-1" eType="//DobubonulaubuBobiBegusBuTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlFribiboFribubebebiBuDadaEs">
    <eLiterals name="DobudabuGuNulaufriDabobubiCus"/>
    <eLiterals name="BabiBoBobefribenulautin"/>
    <eLiterals name="BibiBebuNulaucio"/>
    <eLiterals name="DabiBigubigusgusTor"/>
    <eLiterals name="AndaBobibenulius"/>
    <eLiterals name="AlnulAuFriBufritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubinulAubeDaCus" eSuperTypes="//Abubutin //BrauBoDadaGusnulAubecus //DuBuGububefrinulAugunulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBuBonulauFriCio" eType="//DobubonulaubuBobiBegusBuTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alDabonulaunulAunulAuBunus" ordered="false" upperBound="-1" eType="//Abubutin" eOpposite="//Abubutin/badaboBubifribebonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bibobinulauboes"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulAubegusguslus" eSuperTypes="//DudadagusfriNulauBiBilius //DagusbunulauGusnulauFriBiboNulauBubifrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugugusaubiboboGusdafribefriBocus" eSuperTypes="//DiGusbobuguBedadabigusnulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabibubunulaufriFriGusfriBifrigugustin" ordered="false" eType="//DaDaboGusdadaGunulAunulaubibiBuBinus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbuBebibebubibegusfribues" upperBound="-1" eType="//AudaGubigubobubonulius" eOpposite="//AudaGubigubobubonulius/fagufriFriDaboDaCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FabiNulAubobebiGuBudabogusius">
    <eLiterals name="DoBoboBugusBibiguslius"/>
    <eLiterals name="DabenulaugusguGusbidacus"/>
    <eLiterals name="EdaDaDaDafribuDaNulAunus"/>
    <eLiterals name="DoBuBues"/>
    <eLiterals name="EDabugufrigusNus"/>
    <eLiterals name="DabubigusaubeBubues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbebigusbubogusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifriDaBudaGufrilius" eSuperTypes="//DugusbibefrigusdagudabobeFribuboBuBuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBibifridabifribebubedabetin" eSuperTypes="//Abubutin //DugusbibefrigusdagudabobeFribuboBuBuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DudaNulAugusBebufriNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGusfridaBiDabeBubuTin" upperBound="-1" eType="//DiGusbobuguBedadabigusnulIus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datus" eType="//AlDaBiBigunulAugusBedadabiLus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
