<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dunulius" nsURI="http://hub.de/rcore/examples/dunulius" nsPrefix="Zza">
  <eClassifiers xsi:type="ecore:EClass" name="BabeguboBugusboBebocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begubiBogunulAuBufridabegubuguBugubuLus" ordered="false" eType="//DidadagusbiDaTor" eOpposite="//DidadagusbiDaTor/fabuguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidadagusbiDaTor" abstract="true" eSuperTypes="//BabeguboBugusboBebocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabuguscio" upperBound="-1" eType="//BabeguboBugusboBebocus" eOpposite="//BabeguboBugusboBebocus/begubiBogunulAuBufridabegubuguBugubuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGuGunulAububiNulAugubeFriEs" eSuperTypes="//DidadagusbiDaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubibububidadabeguboGuDacus" eSuperTypes="//DidadagusbiDaTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daDafriBoDagubebobibiBobonus" ordered="false" upperBound="-1" eType="//BabeguboBugusboBebocus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoBebugusgudagusauTor" eSuperTypes="//AuGuGunulAububiNulAugubeFriEs //AubibububidadabeguboGuDacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABiBobinulaubebobogusDabobeCus"/>
</ecore:EPackage>
