<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="braudagubucio" nsURI="http://hub.de/rcore/examples/braudagubucio" nsPrefix="BbE">
  <eClassifiers xsi:type="ecore:EClass" name="DaBoBifrinulaubigufriGusnulaufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoboBecio" abstract="true" eSuperTypes="//DaBoBifrinulaubigufriGusnulaufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusDaGusdabinulaubegustor" abstract="true" eSuperTypes="//DaBoBifrinulaubigufriGusnulaufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigusdafrigusnulAudator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebuBofribeGusbebonulAubobinulEs" ordered="false" eType="//DaBoBifrinulaubigufriGusnulaufritus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuBiBegusdabebogusbibuBilius" ordered="false" upperBound="-1" eType="//DoboBecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbuDagudadaBoguDagusnulAuBodabigusbidabucus">
    <eLiterals name="AuFrigusBubuFribetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabeBudaDabodaBiBobenus" eSuperTypes="//DaBoBifrinulaubigufriGusnulaufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbinulaunulIus" eSuperTypes="//DaBoBifrinulaubigufriGusnulaufritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBuGusNulEs" eSuperTypes="//DuGusDaGusdabinulaubegustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusauDaBibobeNulaugusGuFridabotor" ordered="false" eType="//DububeDagusnulaubifrigusdatus" eOpposite="//DububeDagusnulaubifrigusdatus/duboBibunulauBeDabiGubebifrifriLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DoNulaudaNulaugugubiboNules" instanceTypeName="typeDibufrifriGufribedadanulAuGufriCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DububeDagusnulaubifrigusdatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duboBibunulauBeDabiGubebifrifriLus" ordered="false" eType="//EBuGusNulEs" eOpposite="//EBuGusNulEs/egusauDaBibobeNulaugusGuFridabotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabugusfriBubeDalus" abstract="true" eSuperTypes="//EBuGusNulEs //BigusdafrigusnulAudator"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiGusfribubunules" eSuperTypes="//DabugusfriBubeDalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bebogubobigucio" eSuperTypes="//BigusdafrigusnulAudator"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBugusdaFriDabuBefriDaNules" instanceTypeName="typeAlbubibibeGusNulauBuBibotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabugusBoboGusNulauDaGuBoGusbugusbibeBilius" eSuperTypes="//DabugusfriBubeDalus //AnbinulaunulIus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albuBibiNulaunulaubibebufricio" eType="//DoNulaudaNulaugugubiboNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusbiboboGubitin" eSuperTypes="//BabugusBoboGusNulauDaGuBoGusbugusbibeBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaunulAubeguBuDaNulaunus" eSuperTypes="//DagusbiboboGubitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabifriGusaubebitus" eType="//DiBugusdaFriDabuBefriDaNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidaGusBuTor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algubodafridacio" eType="//DaBoBifrinulaubigufriGusnulaufritus"/>
  </eClassifiers>
</ecore:EPackage>
