<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dogusbobelius" nsURI="http://hub.de/rcore/examples/dogusbobelius" nsPrefix="GHgV">
  <eClassifiers xsi:type="ecore:EClass" name="AbibodabibibeBefrifriGusNulAugulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoNulaudadagubotin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FadadaGusGusGuboTin" instanceTypeName="typeDoBogusbuBufriBuBeGutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlbugusbubiguGusguGusgusbelius" instanceTypeName="typeAnbubeBigucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBoGufriBidadabebonus" eSuperTypes="//AbibodabibibeBefrifriGusNulAugulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="ADadabegusgugubenulAutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguGuBuCio" ordered="false" upperBound="-1" eType="//BabubinulAubuBegusguBoGulius" eOpposite="//BabubinulAubuBegusguBoGulius/eboDaDaGusauBiNulAulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubinulauBibobiDanus" abstract="true" eSuperTypes="//DaLus //AbibodabibibeBefrifriGusNulAugulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobedabunulauLus" eType="//AlbugusbubiguGusguGusgusbelius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auGubonulAunules" upperBound="-1" eType="//AlbugusbubiguGusguGusgusbelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaufriFribenulaufriBiboes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibebogubitus" eType="//AlbugusbubiguGusguGusgusbelius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedabobodagudanulauboTor" ordered="false" eType="//AubiDabibeBudaGuFribunus" eOpposite="//AubiDabibeBudaGuFribunus/eNulaubegusdaFrilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabubinulAubuBegusguBoGulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eboDaDaGusauBiNulAulus" eType="//DaLus" eOpposite="//DaLus/auguGuBuCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBubobeBiBububeBetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFriGusnulAutus" ordered="false" upperBound="-1" eType="//BabubinulAubuBegusguBoGulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBibuboNulaubobubicio" ordered="false" upperBound="-1" eType="//DonulaufriFribenulaufriBiboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFriGubibucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgubebodaboDabunulauDaDator" eSuperTypes="//DaLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabobedaTus" eType="//FadadaGusGusGuboTin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlfriBuBobubiBoBobibolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dudabegubogubotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiDabibeBudaGuFribunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eNulaubegusdaFrilus" ordered="false" upperBound="-1" eType="//DonulaufriFribenulaufriBiboes" eOpposite="//DonulaufriFribenulaufriBiboes/bedabobodagudanulauboTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusfriGudabenulAuGusbeGusLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusnulauBebodabeBifrilius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugusgusauguGububeBuBogubufrinulIus" abstract="true" eSuperTypes="//DaLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dinulauGuboBudaDaBibeTin" ordered="false" upperBound="-1" eType="//BabubinulAubuBegusguBoGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeBenulauGugusBugusTus" eSuperTypes="//AlBubobeBiBububeBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusbuGuBedafribebolus" abstract="true" eSuperTypes="//AlfriBuBobubiBoBobibolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobiFribenulaubudabuTin" ordered="false" eType="//BabubinulAubuBegusguBoGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauNulauBinulAudadabuBeNulautin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eNulAubidabicus" upperBound="-1" eType="//FadadaGusGusGuboTin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidaBibobiBiNulauguguscus" eType="//FadadaGusGusGuboTin" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
