<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anes" nsURI="http://hub.de/rcore/examples/anes" nsPrefix="PKo">
  <eClassifiers xsi:type="ecore:EClass" name="EubobogubogusgunulAufricus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBiBegusbugusius" instanceTypeName="typeDaNulAubugubenulAuboGunulaunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABiDaBuGuscus" abstract="true" eSuperTypes="//EubobogubogusgunulAufricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuGuboFriBofriGutor" eSuperTypes="//ABiDaBuGuscus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beBegusaucus" eType="//DiBiBegusbugusius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGubibebubobinulauboBiGustin" eSuperTypes="//EbuGuboFriBofriGutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBoNulauDaDaFriBububebinulaugulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BrAubeFriNulauNulaubuTin" instanceTypeName="typeDuGusfriBobigusgusbobobeBoGuNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FafrigubiBifriNulauGuslus">
    <eLiterals name="AuBugudabobiTus"/>
    <eLiterals name="BadanulaubiBenulauBeGusbuTor"/>
    <eLiterals name="DuFriNulaubigubibecus"/>
    <eLiterals name="AlgugugudaBububegugudalus"/>
    <eLiterals name="BagusdabubiNulAubedaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBigufriguguGuscio" eSuperTypes="//EubobogubogusgunulAufricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eGubobobeNulAuBodaTin" upperBound="-1" eType="//DiBiBegusbugusius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbuFribubiDaguguses">
    <eLiterals name="BigufrifribuGusDaboboBubuNulius"/>
    <eLiterals name="DiBedabobobebibiLius"/>
    <eLiterals name="AnBebenulAulus"/>
    <eLiterals name="Augubobobobobonulaubinus"/>
    <eLiterals name="AubuDafriFrigusbobobiEs"/>
    <eLiterals name="BrAubedafribuDabogusBecio"/>
    <eLiterals name="AlBoboguBibudaGuslus"/>
    <eLiterals name="EdabugusbuNulAuTin"/>
    <eLiterals name="DuFrigufrifriGusdacus"/>
    <eLiterals name="DibuNulauguFribubitor"/>
    <eLiterals name="Dibugutor"/>
    <eLiterals name="AndaDabobibiboGusAugusEs"/>
    <eLiterals name="DofrigubebogububuBuGuCus"/>
    <eLiterals name="AlgubebibibeBelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EBeGusgusBibobubeGusGusnulauLus" instanceTypeName="typeFagusDafrifridadaboBetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusGunulaubeguBeBobubobinulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="andabubobuLus" eType="//EBeGusgusBibobubeGusGusnulauLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dabidadatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfriboGudator" eType="//BiBigufriguguGuscio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbigusgusdabobofrigusbunulEs" ordered="false" eType="//AnGusGunulaubeguBeBobubobinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubinulaubiguBifriFriGusbuGugusdabonus" abstract="true" eSuperTypes="//Dabidadatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbidaNulAufriBeFritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bifrinulAuDafriBubeBobugusaugusbenus" eType="//BrAubeFriNulauNulaubuTin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abinulaugusAucus" ordered="false" eType="//ABiDaBuGuscus"/>
  </eClassifiers>
</ecore:EPackage>
