<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="brautin" nsURI="http://hub.de/rcore/examples/brautin" nsPrefix="Tlb">
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaufribegues"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubiGuBuGusfridacus" abstract="true" eSuperTypes="//FaNulaufribegues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braububeBeNulauBogusBocus" ordered="false" upperBound="-1" eType="//FaNulaufribegues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BeBeNulaugusbeGusbobobedabilus">
    <eLiterals name="Augunulaubidatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaBudabugusDabodaLius">
    <eLiterals name="BidabebofriFribibugubiBegubudalus"/>
    <eLiterals name="EfrinulauNulauNulAugusaunulauGubunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofrigugusbudaBeFrifriBebufricus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBugusbudanulauTor" instanceTypeName="typeBaBefribinulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadanulaudaboBiguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGububiguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBiFriguDabogusGusfriTor" eSuperTypes="//EuGububiguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlaugunulaubiTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusAufribigusdagufriCio" eSuperTypes="//AnBiFriguDabogusGusfriTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Anbenulaubebinulaudatus" eSuperTypes="//EuGububiguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andabifrinus" eType="//AnBiFriguDabogusGusfriTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabeguDaDaNulaubebubofrilius" eType="//FaNulaufribegues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebigufribuBedadaes" eSuperTypes="//AlaugunulaubiTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auDaBububeguLius" upperBound="-1" eType="//Anbenulaubebinulaudatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EFribiDadafribibefrinus"/>
</ecore:EPackage>
