<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eufrigunules" nsURI="http://hub.de/rcore/examples/eufrigunules" nsPrefix="lDd">
  <eClassifiers xsi:type="ecore:EClass" name="DiDaBibinulaunulaubudanulauBebetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBeDaBibenulaubegunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubunulAunulaubonulAubinulaubutus" eSuperTypes="//BiBeDaBibenulaubegunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eunulauGusnulAuBibuBogusFribulus" ordered="false" eType="//DiDaBibinulaunulaubudanulauBebetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibifriBibigubibiGubufricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusDabiGubebenulaubobibiBulius" abstract="true" eSuperTypes="//BiBeDaBibenulaubegunules //DibifriBibigubibiGubufricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbibebofriBuNulauTor" eSuperTypes="//BiBeDaBibenulaubegunules"/>
</ecore:EPackage>
