<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bedagusgucio" nsURI="http://hub.de/rcore/examples/bedagusgucio" nsPrefix="MFZK">
  <eClassifiers xsi:type="ecore:EClass" name="BraubeBeGusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBiBeboNulaufriboDator" ordered="false" eType="//BanulaugusBibobebuBilus" eOpposite="//BanulaugusBibobebuBilus/ebegunulAubegububibeLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguGuBebugufrigusfricio" upperBound="-1" eType="//DubobudagusgusGuDagucus" eOpposite="//DubobudagusgusGuDagucus/andabogusfrigulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAugusnulaunulaubolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulaugusBibobebuBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebegunulAubegububibeLius" ordered="false" eType="//BraubeBeGusNus" eOpposite="//BraubeBeGusNus/baBiBeboNulaufriboDator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusgusauBoGusfriBogusNulautor" ordered="false" upperBound="-1" eType="//FabeLius" eOpposite="//FabeLius/fadafriBogusbudafritor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobuNulAuguguDagusnulaunulAuBucio" ordered="false" upperBound="-1" eType="//BrAuBogusdaBebelus" eOpposite="//BrAuBogusdaBebelus/algugunulauFriDabebulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusBebeGuGusBubiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diNulAuBigusauFridacus" upperBound="-1" eType="//BanulaugusBibobebuBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabiBoBugusbigusguBebutus" abstract="true" eSuperTypes="//BanulaugusBibobebuBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugubuGusFriFriFrigufrifrinulAuguscio" upperBound="-1" eType="//DidaboNulIus" eOpposite="//DidaboNulIus/daBubunulaubebegusNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubufriBugudaGusTus" instanceTypeName="typeDoFrinulauGusgubuFrigusDabobuBoBinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabeLius" abstract="true" eSuperTypes="//BraubeBeGusNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaGusFriNulaulius" ordered="false" eType="//AgusBebeGuGusBubiLius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbibiNules" eType="//EubufriBugudaGusTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadafriBogusbudafritor" ordered="false" eType="//BanulaugusBibobebuBilus" eOpposite="//BanulaugusBibobebuBilus/bigusgusauBoGusfriBogusNulautor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBiFrinulaubodadanulAucus" ordered="false" eType="//BanulaugusBibobebuBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbuBoBoDaFriGuBubiBofribudalus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibegusnulAuboFriNulauBiguscus" eSuperTypes="//FagusbuBoBoDaFriGuBubiBofribudalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBebeBogusgudaLius" abstract="true" eSuperTypes="//FagusbuBoBoDaFriGuBubiBofribudalus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBiFriBudaGubeBebutor" eSuperTypes="//DibegusnulAuboFriNulauBiguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBeGusAuFrinulautin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusgusgusDaBubibubeDaDabolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGugusauBufrigubibelus" eSuperTypes="//FabeLius //EugusgusgusDaBubibubeDaDabolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobegusGusgunulaubebinus" ordered="false" upperBound="-1" eType="//FanulAugusnulaunulaubolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BafriGudaGusbuGuses" eSuperTypes="//FagusbuBoBoDaFriGuBubiBofribudalus //FabeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugugufriBobuBebobenulaulus" eSuperTypes="//FabeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafriBunulaubuBebeBeFridanulAuFrilus" ordered="false" upperBound="-1" eType="//BiBeGusAuFrinulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraunulauBibigusdabunulAunulaulus" instanceTypeName="typeAlauboFridabedagufridabiBuboboNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefrigubogusAucio" eSuperTypes="//BanulaugusBibobebuBilus //AgusBebeGuGusBubiLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AboNulauBenulaubeNules" instanceTypeName="typeBedafribobiDaBigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Digusbidabibebunus" eSuperTypes="//EugusgusgusDaBubibubeDaDabolus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DidabibobububibiBobiBubobetor" instanceTypeName="typeAldabunulAudaNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndagusbiBogubutus" eSuperTypes="//DibegusnulAuboFriNulauBiguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABudaBoBodabegusnus" eSuperTypes="//AgusBebeGuGusBubiLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faNulAuBefribuCio" eType="//EubufriBugudaGusTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubidaes" eType="//EubufriBugudaGusTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidaboNulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBubunulaubebegusNulius" ordered="false" eType="//BabiBoBugusbigusguBebutus" eOpposite="//BabiBoBugusbigusguBebutus/dugubuGusFriFriFrigufrifrinulAuguscio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBoBubibuFribobuBicus" upperBound="-1" eType="//AlgubonulAuGugusGufrifribolus" eOpposite="//AlgubonulAuGugusGufrifribolus/albibiBunulauCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulAububefrifribunulAunulaubugusCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaudaEs" ordered="false" upperBound="-1" eType="//BefrigubogusAucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBuFriboFriboboTor" eType="//EubufriBugudaGusTus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="begudafrinulauDadabubulus" eType="//BanulaugusBibobebuBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubodaGusbiGusdaBufribofrigudaNus" instanceTypeName="typeAnnulaudabiguguBifrigusCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabofriBuGusBiBoLius" instanceTypeName="typeEuFribeDaGusNulaugugutus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Babugusbunulaufrigusbebubebulus">
    <eLiterals name="AnGuBebugusauGusnulAuLus"/>
    <eLiterals name="AnbuBubeBeGuBobudalus"/>
    <eLiterals name="EubebubibuboGusgunus"/>
    <eLiterals name="EubonulauGubugusAuNulaubeLus"/>
    <eLiterals name="AnulauFribiBuGubeBonulAutin"/>
    <eLiterals name="Bebofribucio"/>
    <eLiterals name="Bagubebocus"/>
    <eLiterals name="Babifrigusfribobiguslus"/>
    <eLiterals name="FaBibigubibeDabogusnulius"/>
    <eLiterals name="EGusaubeDaBunulIus"/>
    <eLiterals name="AuBogudadaBebibolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufrinulaufriDaBuBobiNulius" abstract="true" eSuperTypes="//ABudaBoBodabegusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebofrinulauNulaubebibiTus" ordered="false" upperBound="-1" eType="//DiNulAububefrifribunulAunulaubugusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DanulaubebeCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EguBiDabenulauBeNulaudatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfriboboNulauDadabies" ordered="false" eType="//ABudaBoBodabegusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigusbiNulauboBidagusbubocio" eSuperTypes="//FabeLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlnulauNulauDabuGusboBoBocio" instanceTypeName="typeEnulauguBiCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGusgubeNulaunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbegusgubidaBuGubedacus" eSuperTypes="//BeBiFriBudaGubeBebutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGudabefricio" ordered="false" eType="//EbuboBebedabiBobelius" eOpposite="//EbuboBebedabiBobelius/braugubegufriGugudaguDanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlDadagunulauLius" instanceTypeName="typeDabeGuNulAufriBiguBuDacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusbuboboGugudaNulaudaBodaTor" eSuperTypes="//FabeLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBugusdanulAubobenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulauDanulaubeBoBilius" eSuperTypes="//AgusBebeGuGusBubiLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BabobibudagusaunulAubiCus" instanceTypeName="typeBefriguNulauBufriBobiguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadanulAuBigunulaufriguslius" eSuperTypes="//FaBebeBogusgudaLius //EbegusgubidaBuGubedacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobedafribidadabubebuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulaugubebudabuNulauFribifriFriLus" abstract="true" eSuperTypes="//DibegusnulAuboFriNulauBiguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubofriBuBudanus" eSuperTypes="//EugusgusgusDaBubibubeDaDabolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doDabobogubuGusGusnulaucio" ordered="false" eType="//BiGugusauBufrigubibelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BagusGubuBububebubonulius">
    <eLiterals name="AguBobobiBiBoNulAunus"/>
    <eLiterals name="BebiDaGubeGudanulaufribefriBoTor"/>
    <eLiterals name="EdagunulAugufribicio"/>
    <eLiterals name="EuguguGusnulaubibugusautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Benulaubibues" eSuperTypes="//EugusgusgusDaBubibubeDaDabolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaFrigunulaulius" eSuperTypes="//DobedafribidadabubebuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGunulauNulauguGugugusnulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EunulAuFriBuBofritor" instanceTypeName="typeDibebunulauBifriFrigusbenules"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabogubobiGuboBifriDator" eSuperTypes="//FabeLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doguFribuBuGusnules" ordered="false" upperBound="-1" eType="//BanulaugusBibobebuBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibiGusLius" eSuperTypes="//AgusBebeGuGusBubiLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badabeGufrigugusDatin" eType="//EunulAuFriBuBofritor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubebubigusauFribebeBebenulaudatus" abstract="true" eSuperTypes="//FabeLius //BigusbiNulauboBidagusbubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafrinulauBuNulaugunulAudabunulaunules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braufrifrigugudaDabitus" ordered="false" eType="//DobedafribidadabubebuNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusdaGusdafrinulAubuGubebenus" eSuperTypes="//BaGunulauNulauguGugugusnulius //BafriGudaGusbuGuses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albufribenulAuboboBoGusfriNulius" ordered="false" eType="//BigusbiNulauboBidagusbubocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeDaDagusbobogubofriTor" instanceTypeName="typeEdanulaugusbuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafrigusdagusfribogusFribiBitin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BibegusFriBonulAufricio" instanceTypeName="typeDoGusDabiBetin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BraubiboGuboBogusbubegugusNulAucio">
    <eLiterals name="BenulaugusauGuFritin"/>
    <eLiterals name="Bidagusgubenulaufribefribecio"/>
    <eLiterals name="AndabobunulAuGusfriBugusBeGunus"/>
    <eLiterals name="AnFribogusAuFribubuLus"/>
    <eLiterals name="AbonulauNulauNulAuGuGusBeLius"/>
    <eLiterals name="FaFrinulAuFriFrigusfribugugucus"/>
    <eLiterals name="DofrigugusGubedafriboCio"/>
    <eLiterals name="AuNulaunulAunulaulus"/>
    <eLiterals name="BraunulAudadafribebodagues"/>
    <eLiterals name="BrauboBegusTor"/>
    <eLiterals name="BedabobifribidafriButor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Braubidadagudabulus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eboGusBeGuscio" eType="//AlDadagunulauLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DabibuboLius">
    <eLiterals name="DagusbibefridaGubenulaugubenulius"/>
    <eLiterals name="BeBifriNulauTin"/>
    <eLiterals name="DiBigusBudanulauBoboBetin"/>
    <eLiterals name="AuGubebidaDatus"/>
    <eLiterals name="AfribubodaGusbububiBoguses"/>
    <eLiterals name="FaBifrinulAuNulauBies"/>
    <eLiterals name="DoNulauBebuFridabobeguses"/>
    <eLiterals name="AdafribofriCus"/>
    <eLiterals name="BabiFridaboFribinus"/>
    <eLiterals name="BigugusFriNulauDaBobiGuslus"/>
    <eLiterals name="ANulauBuEs"/>
    <eLiterals name="Bigusnulaubenulaugutor"/>
    <eLiterals name="DoBebonulaubelus"/>
    <eLiterals name="AuDaGudafribebububelius"/>
    <eLiterals name="BinulaugugufrigusGusbecio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AboNulAufrigubiGuLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiDaguBuDabolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubobudagusgusGuDagucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="andabogusfrigulus" ordered="false" upperBound="-1" eType="//BraubeBeGusNus" eOpposite="//BraubeBeGusNus/biguGuBebugufrigusfricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusnulAugubibonulAubiBegutus" eSuperTypes="//DobedafribidadabubebuNulius //BagusbuboboGugudaNulaudaBodaTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enulauDaBugudaBibugusbelus" eType="//BraunulauBibigusdabunulAunulaulus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibebebofribegusgubeLus" ordered="false" upperBound="-1" eType="//BagusbuboboGugudaNulaudaBodaTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBogusdaBebelus" eSuperTypes="//ABudaBoBodabegusnus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algugunulauFriDabebulus" ordered="false" eType="//BanulaugusBibobebuBilus" eOpposite="//BanulaugusBibobebuBilus/dobuNulAuguguDagusnulaunulAuBucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BedanulAuFriboFrinulaudaCio" instanceTypeName="typeBedaBibeTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibeGusNulauNulAuLus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobogunulaubudaboBoLius" abstract="true" eSuperTypes="//DibiGusLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBoBibobufrigusbelius" ordered="false" eType="//DufrinulaufriDaBuBobiNulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBofriBugufriBofriBibiBibicus" upperBound="-1" eType="//AuboDagusdaBobofridagucus" eOpposite="//AuboDagusdaBobofridagucus/efribobobebuGusdacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bagusbubocio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAunulauLius" eType="//AboNulauBenulaubeNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlFribidanulauBebeTor" eSuperTypes="//DiNulAububefrifribunulAunulaubugusCus //EbegusgubidaBuGubedacus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alboBebobubogusBuNulaudaLius" eType="//AlnulauNulauDabuGusboBoBocio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dodadaes" eType="//BagusGubuBububebubonulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuDabeDabonulautor" eSuperTypes="//BagusbuboboGugudaNulaudaBodaTor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DonulauFribodanulAudabibicio" instanceTypeName="typeDabuDaDagusbebiguboNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DigusnulaubeFriBufrigufricus" instanceTypeName="typeAubogugubiguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuguboBinulaubiBuFribeBoGusBitor" eSuperTypes="//BafriGudaGusbuGuses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBeNulaudabebilus" ordered="false" eType="//BafrinulauBuNulaugunulAudabunulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FafribibubeFriBiDadaBugusguDaGufriCio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FaBeguGuBunulaubucus" instanceTypeName="typeBibeguDaguGunulAuGusBegubicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuboguBiBufrigudabitus" eSuperTypes="//AlFribidanulauBebeTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAudadagusNulEs" eSuperTypes="//BafrinulauBuNulaugunulAudabunulaunules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubogubobegusbocus" eType="//BagusGubuBububebubonulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnNulaunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibeBinulaugusbuGuBibolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobobefridagusGubobebuboBuguBues" ordered="false" eType="//DibiGusLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBunulaugugusbonulauFritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGuNulaunulaufribubiGuses" abstract="true" eSuperTypes="//DobogunulaubudaboBoLius //DubebubigusauFribebeBebenulaudatus //BanulaugusBibobebuBilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biBeBeBibebiBunulaunulaufrifriBolius" eType="//DidabibobububibiBobiBubobetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADafribobibeGugugubiboLus" eSuperTypes="//DiNulAububefrifribunulAunulaubugusCus //Braubidadagudabulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFricio" ordered="false" upperBound="-1" eType="//ABudaBoBodabegusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BegusbugunulEs" instanceTypeName="typeDabeGusBodaboGugusFrifries"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DunulAugusfribonulAubebeNulautor">
    <eLiterals name="FanulaugusbuBenulaugusBies"/>
    <eLiterals name="AbuboBulius"/>
    <eLiterals name="FaFriBebibibiBigufries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusfribogusaudaGusTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dunulaubeBuGusbigusFriNules" ordered="false" upperBound="-1" eType="//DubebubigusauFribebeBebenulaudatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlDaGusBibibogusBugugusDaNulAuDaTus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiFrinulAuBigugufribibigubiguLius">
    <eLiterals name="EufriGuDabegugufriTus"/>
    <eLiterals name="FagugubigubeBegucus"/>
    <eLiterals name="EunulaugusfriBubobiTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bebegusfribobicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doNulauBubuBoes" ordered="false" upperBound="-1" eType="//DubebubigusauFribebeBebenulaudatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaDaNulauFrinulaubeguboTin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBibugusauNulIus" eType="//BabofriBuGusBiBoLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBobeGubofrinulauBenus" eSuperTypes="//Bagusbubocio //Braubidadagudabulus //EbegusgubidaBuGubedacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiguBidaBubobebotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augubebubonulaudaBiGuDabefrinulIus" eType="//BrAudadagusNulEs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abubonulauNulIus" eType="//DiFrinulAuBigugufribibigubiguLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgubonulAuGugusGufrifribolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albibiBunulauCus" ordered="false" upperBound="-1" eType="//DidaboNulIus" eOpposite="//DidaboNulIus/alBoBubibuFribobuBicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabiNulaugubeFrifriguBugugusdaFriBenus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabebeBubogusbitus" ordered="false" eType="//AlgubonulAuGugusGufrifribolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DodaguBoNulauGusBinulaucio" eSuperTypes="//FabogubobiGuboBifriDator //AuguboBinulaubiBuFribeBoGusBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnGubonulAubenulauGubitus" abstract="true" eSuperTypes="//ABudaBoBodabegusnus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anfrigubidalus" eType="//DonulauFribodanulAudabibicio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albenulaucus" eType="//AubodaGusbiGusdaBufribofrigudaNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusdaDaboGusBebodabuGutin" eSuperTypes="//DiNulauDanulaubeBoBilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabiBeGusgusgubobilius" eSuperTypes="//DobedafribidadabubebuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuDaNulaubefribubilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebuGubifriguGuBeCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auboDadabibibunulius" eType="//BabobibudagusaunulAubiCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BrauDabiBubinules" instanceTypeName="typeBebobebuBudanulaufries"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBeFribubigusauNulAudatin" eSuperTypes="//FafribibubeFriBiDadaBugusguDaGufriCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigusBoNulauButor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBegusaufriDabucio" abstract="true" eSuperTypes="//DiBobeGubofrinulauBenus //ABudaBoBodabegusnus //FabogubobiGuboBifriDator"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufribonulaugusbebibiGusbuEs" eSuperTypes="//Bebegusfribobicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifrinulauBegudaboBefrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboDagusdaBobofridagucus" eSuperTypes="//BafriGudaGusbuGuses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efribobobebuGusdacio" ordered="false" eType="//DobogunulaubudaboBoLius" eOpposite="//DobogunulaubudaboBoLius/daBofriBugufriBofriBibiBibicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Dutin" instanceTypeName="typeBraufrifriTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlauFrigunulaubogusfriboes" instanceTypeName="typeEuboBebunulaufrinulauguEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaNulaugubenulAuboNulauBunulaubuFribotin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbuFriNulius" ordered="false" upperBound="-1" eType="//DaFrigunulaulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauDaDagusbitus" eType="//DanulaubebeCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DofrigusdabofrigusBedaDatin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudabeBodafridadagusfricus" ordered="false" eType="//DibegusnulAuboFriNulauBiguscus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alauBifrigusbigubobelus" ordered="false" upperBound="-1" eType="//AlFribidanulauBebeTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubodaGusgusdabidaFridatin" eSuperTypes="//DabiNulaugubeFrifriguBugugusdaFriBenus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusaunulAubofrigunus" eSuperTypes="//DaNulaugubenulAuboNulauBunulaubuFribotin //FagusbuBoBoDaFriGuBubiBofribudalus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faDanules" eType="//BrauDabiBubinules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubugusfriboBifribofrigusgugugudaTor" instanceTypeName="typeDodabogugusauDabigufriBegusnulaucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbubedadabiguBebogusgusbiboGusLus" instanceTypeName="typeAndabubobudaguBiGuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuboBebedabiBobelius" abstract="true" eSuperTypes="//BiBegusaufriDabucio //AuBugusdanulAubobenules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugubegufriGugudaguDanus" ordered="false" upperBound="-1" eType="//EbegusgubidaBuGubedacus" eOpposite="//EbegusgubidaBuGubedacus/auGudabefricio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdaFriBoFrigusdaFrigugububutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuGubofrigusAuBiBibubugusLus" ordered="false" eType="//BrAuBogusdaBebelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FagusFriDanus" instanceTypeName="typeDuBobubuFribuBiBunulauTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EufriGusGunulaubibufricus" abstract="true" eSuperTypes="//BiBegusaufriDabucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Doboguses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biBefriguboGuNulaubuDagusgunus" ordered="false" upperBound="-1" eType="//BafrinulauBuNulaugunulAudabunulaunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbinulaufribuNus" eSuperTypes="//AuboDagusdaBobofridagucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brauNulaubibudafrinus" eType="//AbubedadabiguBebogusgusbiboGusLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabunulaudafriBiguDabeNulaulus" ordered="false" eType="//BrAudadagusNulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Badadagubedabibibenulaulus" eSuperTypes="//DufrinulaufriDaBuBobiNulius //EuDaNulaubefribubilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubodaGufriNulAulius" ordered="false" upperBound="-1" eType="//BiGugusauBufrigubibelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibeDatus" eSuperTypes="//DaGuNulaunulaufribubiGuses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibeGusNulaudanulauBibonus" ordered="false" upperBound="-1" eType="//BagusbuboboGugudaNulaudaBodaTor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anguses" upperBound="-1" eType="//AlDadagunulauLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriBebegusgubinulAulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BafriGuLius" instanceTypeName="typeAubibigusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusBedagusnulAubudadaGuscus" eSuperTypes="//BadanulAuBigunulaufriguslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBitin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabefriboGusbifrigulius" eType="//BafriGuLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBuguFrinulaubiNus" abstract="true" eSuperTypes="//ADafribobibeGugugubiboLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiboGusguFrinulaudabebeLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibobuBuFriBibenulauTor" eType="//DigusnulaubeFriBufrigufricus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaBinulAunulaudanulIus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBogusBogusgusbibiNules" ordered="false" upperBound="-1" eType="//DiDaguBuDabolius"/>
  </eClassifiers>
</ecore:EPackage>
