<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="efrigudabetor" nsURI="http://hub.de/rcore/examples/efrigudabetor" nsPrefix="kx">
  <eClassifiers xsi:type="ecore:EClass" name="BiguBedabiDaBuGusgubolius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EnulauDabuGusBegusaugutin" instanceTypeName="typeAnbibibebubebobiDabobogugubibelius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuboBoDaGusDaNulauGusBecus">
    <eLiterals name="AbinulaubobobeBegunulius"/>
    <eLiterals name="DiBedabibubidagubofriGusGugusius"/>
    <eLiterals name="DanulAuFriDaNulaunulaufrinus"/>
    <eLiterals name="AlaugusfriGugusnulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGusGuBefriFriBigustin" eSuperTypes="//BiguBedabiDaBuGusgubolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Binulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DunulauGugubeGusBibubedaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baboguguGusguslus" ordered="false" upperBound="-1" eType="//BiguBedabiDaBuGusgubolius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daguBebiBotin" eType="//EnulauDabuGusBegusaugutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DonulaubidafridaLus">
    <eLiterals name="DabeNulaugusAugudaboGuBegusboBocio"/>
    <eLiterals name="DaDaBinulauBobedadaGuguses"/>
    <eLiterals name="BeDanulaubifrigufribubiEs"/>
    <eLiterals name="BegunulaubibuNulAuGusgutor"/>
    <eLiterals name="BrauNulaudaBugugusDafribuBecio"/>
    <eLiterals name="BaBebefribobubiDaBiguGuTus"/>
    <eLiterals name="FabobufriCio"/>
    <eLiterals name="DuBobiBubeTin"/>
    <eLiterals name="DaNulaubobobogusnulaucus"/>
    <eLiterals name="BabibuFribuGuBububulus"/>
    <eLiterals name="AnBiGusbuBeguBebedaboes"/>
    <eLiterals name="DagugusdaguGusbifricio"/>
    <eLiterals name="Dugudagusgusbogusbobobulius"/>
    <eLiterals name="Albibeguscio"/>
    <eLiterals name="BabogusdaBiGubucio"/>
    <eLiterals name="Dobodafribinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AudaGuBubuBuCus" eSuperTypes="//Binulius //BiguBedabiDaBuGusgubolius //DunulauGugubeGusBibubedaes //EGusGuBefriFriBigustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAubebiFribofribifribuguLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabeGusbebuBobegusbofritor" eSuperTypes="//BiguBedabiDaBuGusgubolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudagubebodabeboBubulus" ordered="false" upperBound="-1" eType="//BiguBedabiDaBuGusgubolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbugusguBonulAuFritus" eSuperTypes="//BiguBedabiDaBuGusgubolius //DabeGusbebuBobegusbofritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdaBibeGusNulauboGusbegubigutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobudaBegububiBubebuDacio" eSuperTypes="//DunulauGugubeGusBibubedaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusgusbodagusBogusaubutus" ordered="false" upperBound="-1" eType="//EGusGuBefriFriBigustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AboBoBibofribeBigulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuDaDabibufriBelius" instanceTypeName="typeAbeLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaboguBoBocio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EunulaubonulAugusEs">
    <eLiterals name="AlbuGusaubiboNulaubefrilus"/>
    <eLiterals name="FaboNulaubigusGutin"/>
    <eLiterals name="DabubeBunulAutor"/>
    <eLiterals name="EgusbubodabuBoguboFriLus"/>
    <eLiterals name="AnbonulauBeguBiTus"/>
    <eLiterals name="EboBoguguBinulaubegubudagusbelus"/>
    <eLiterals name="BeBeBiDagufriGugunulAuTus"/>
    <eLiterals name="EugubobobofridabeEs"/>
    <eLiterals name="BraubebeguGunulius"/>
    <eLiterals name="Bibibecus"/>
    <eLiterals name="EubiguNulAuBubidafribobolus"/>
    <eLiterals name="DibodaGuBobiButor"/>
    <eLiterals name="BebibibogusgufriGustin"/>
    <eLiterals name="BedaBudagubebenules"/>
    <eLiterals name="EBibigusfriBiFrilus"/>
    <eLiterals name="BagugubobeboNulAuBecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABuFriBedabeBetor" eSuperTypes="//DabeGusbebuBobegusbofritor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlbufribuLus">
    <eLiterals name="BabugusBies"/>
    <eLiterals name="AlbebubobububuGubuBotor"/>
    <eLiterals name="EubeGusboNulaucio"/>
    <eLiterals name="BrAububoBofriGustor"/>
    <eLiterals name="AbegusnulaufriNulEs"/>
    <eLiterals name="AnGusnulauBinulaugulius"/>
    <eLiterals name="FagunulaubebeBidagugusbubedaBugubedaLius"/>
    <eLiterals name="BagusfrigubuBigusaubonulaubibodaboCus"/>
    <eLiterals name="BabedabuNulaubeboes"/>
    <eLiterals name="DubinulauFries"/>
    <eLiterals name="EbuBeDabebubigudadaGucio"/>
    <eLiterals name="BeFriguGuGugubiGunulius"/>
    <eLiterals name="FagusaunulauGusbeNulAuGuTin"/>
    <eLiterals name="AndanulauFribeBiboboGusaunulaudagusBuFridabibutus"/>
    <eLiterals name="DaNulaufriFribiBeDadafribeLus"/>
    <eLiterals name="AubeboGusBeguBeGuBobicio"/>
    <eLiterals name="BaBuBinulauFriBeBiDabodaes"/>
    <eLiterals name="DuBuBeDafriDaBibutus"/>
    <eLiterals name="BinulaubiBuNulAubeBunulauLius"/>
    <eLiterals name="DibogudaBuDaBonules"/>
    <eLiterals name="AlBudabeBeNulaugudafriboCio"/>
    <eLiterals name="BadaguguGusgusButor"/>
    <eLiterals name="AuGusAugusdaGudagutus"/>
    <eLiterals name="DiNulaubugubofridabedacio"/>
    <eLiterals name="AuDabobububinulAuboGubufrifriguses"/>
    <eLiterals name="EBubofriBodacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonulauNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboboGusDaFriDaguslus" ordered="false" upperBound="-1" eType="//DabeGusbebuBobegusbofritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiBobeFrigusgusNulaubutus" eSuperTypes="//BiguBedabiDaBuGusgubolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibofribobudaBotus" abstract="true" eSuperTypes="//BiguBedabiDaBuGusgubolius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbenulAuFribobubeBidabilius" instanceTypeName="typeAdabebobeBuBebiBolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EBoBobenulaubegubonus" eSuperTypes="//DunulauGugubeGusBibubedaes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusboDaBebinulAudagunulAulus" eType="//DonulaubidafridaLus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auNulAunulaubudagunulAudabebefridanus" ordered="false" eType="//BrAuGusaudabibobeBiBubofribebedaBilius" eOpposite="//BrAuGusaudabibobeBiBubofribebedaBilius/brAubigusdaNulAuguguBubeguFries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeNulAubobefrifridaNulautus" abstract="true" eSuperTypes="//DobudaBegububiBubebuDacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiFrifriDaBubibibicus" eSuperTypes="//EGusGuBefriFriBigustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alGubiGusGuBebecio" ordered="false" eType="//EBoBobenulaubegubonus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="falius" eType="//AboBoBibofribeBigulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebunulaugudadabofrinules" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabiguguGuCus" eType="//EuDaDabibufriBelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoFridadagububoes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogusbiBoGusGusdaGusFrigusGusbebiGuBunulius" upperBound="-1" eType="//AboBoBibofribeBigulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubebeDaDabeNulaubeguboFrinulAutus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuGusaudabibobeBiBubofribebedaBilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euguDadaBiBoGuboNules" ordered="false" eType="//DonulauNules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baDaGusbogusDafricio" ordered="false" eType="//DabeGusbebuBobegusbofritor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubigusdaNulAuguguBubeguFries" ordered="false" upperBound="-1" eType="//EBoBobenulaubegubonus" eOpposite="//EBoBobenulaubegubonus/auNulAunulaubudagunulAudabebefridanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibonulaunulaudaCus" eSuperTypes="//EBoBobenulaubegubonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digubobeGuBues" ordered="false" upperBound="-1" eType="//DonulauNules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBobigusbebibebobeFriNulAubugusius" ordered="false" upperBound="-1" eType="//EBoBobenulaubegubonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EfriboBefriguFribidabogugububoLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnBonulAubibubitus" instanceTypeName="typeEbeGunulaubodabefribofrifrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabuFribebebunulaubegusbiBubibibiTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dunulaubigubonulEs" eType="//EnulauDabuGusBegusaugutin" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufriGuBiNulaunulaucus" upperBound="-1" eType="//AlbufribuLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagubunulaunulaugusNulaulus" abstract="true" eSuperTypes="//EdaBibeGusNulauboGusbegubigutor //EGusGuBefriFriBigustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbufrigugugues" ordered="false" upperBound="-1" eType="//DonulauNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugufriBoFriBegusNulauBobebogutin" eSuperTypes="//DubebeDaDabeNulaubeguboFrinulAutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeBedaBiBibugusBoGusaunulauTin" eSuperTypes="//BrAubebiFribofribifribuguLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dubuGusfribudaGusBubeTus" eType="//AlbufribuLus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbufrinulauBuBibiBudafrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbebiBiLus" eSuperTypes="//AbufrinulauBuBibiBudafrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusfribofrigusbobibiTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dububonulaubububeTus" ordered="false" eType="//EBoBobenulaubegubonus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faNulAubutus" eType="//EuDaDabibufriBelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EFriFriboFribibibegusGuLius" instanceTypeName="typeDabigunulaugustin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuguGusaugusboBobebuBedaEs">
    <eLiterals name="DuNulAububedabuNulaulius"/>
    <eLiterals name="AnBoBodadadadabuBeFrigusaunulaudatin"/>
    <eLiterals name="EubugubeguBodaBuBidadacus"/>
    <eLiterals name="AlgusBebibodagubucus"/>
    <eLiterals name="DidabebeguFribodaBoDator"/>
    <eLiterals name="DiDabeDafriboBudabeGustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AButin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AufriBeBegusbudafriGutin" instanceTypeName="typeBraubeguBoBebogutus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Begusfridabonulaulus">
    <eLiterals name="BraufriBitin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBiNulAuFribuBelius" eSuperTypes="//DonulauNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbonulaubibuBiNulaufriguscio" eSuperTypes="//DugufriBoFriBegusNulauBobebogutin //FagubunulaunulaugusNulaulus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AugusbeBibebegubudafrigusbuBebotin">
    <eLiterals name="FaBoGusboGulius"/>
    <eLiterals name="DunulauBobodaguBuGusnulaugugugusTor"/>
    <eLiterals name="Anbobigudabigusgusbicus"/>
    <eLiterals name="EuboboGusBenulauboNulaububebocus"/>
    <eLiterals name="DaGugusbiBidabebolus"/>
    <eLiterals name="DaboGusBeNulauNulaugusfrilius"/>
    <eLiterals name="AlFriDagubofribunulauboBubudafriDaCio"/>
    <eLiterals name="DubofribidaNulAuFribiTor"/>
    <eLiterals name="AugusGuFribebeFriguNulaubilus"/>
    <eLiterals name="EguGudabeGusnulAuGunulauboTus"/>
    <eLiterals name="Befribetus"/>
    <eLiterals name="AfrifrifriGubeBenulaubebuBegusBogusnus"/>
    <eLiterals name="BebedafrinulauGuTus"/>
    <eLiterals name="EBinulAunus"/>
    <eLiterals name="BabofriBonulAudaDaFriGuBofrinulautor"/>
    <eLiterals name="EuguGubefriGuguFriBubifrigubotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfriGugudaguBiGuDaes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusnulaugustus" ordered="false" upperBound="-1" eType="//DunulauGugubeGusBibubedaes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGuBibobobobebocio" ordered="false" eType="//BabeBedaBiBibugusBoGusaunulauTin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babiBiNulauboboTin" ordered="false" upperBound="-1" eType="//BiFrifriDaBubibibicus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubuBobebiBenus" instanceTypeName="typeAlguFrifriboBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbebufriBoFribofriEs" eSuperTypes="//BrAuGusaudabibobeBiBubofribebedaBilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braunulaudabeFriTin" eType="//EuDaDabibufriBelius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugusfriguboGugubegusBinulaufriCio" eSuperTypes="//DibonulaunulaudaCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diboBunulaufriboBufrigubiNules" eType="//Begusfridabonulaulus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FanulAubeGusbegusGunus" instanceTypeName="typeDigusgugusbobudafribobubedagulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuBuBubufriFriboGuBuEs">
    <eLiterals name="DobefribeNulaunus"/>
    <eLiterals name="BraunulaugunulaugusBobobeDatus"/>
    <eLiterals name="AgugusdaguTin"/>
    <eLiterals name="BaFrifrifridabigusgusBelius"/>
    <eLiterals name="BaGuCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DidaBibidaTin" eSuperTypes="//AButin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begubeBoBobufrigubiTor" eType="//EunulaubonulAugusEs" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
