<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anbitor" nsURI="http://hub.de/rcore/examples/anbitor" nsPrefix="c">
  <eClassifiers xsi:type="ecore:EDataType" name="AldabubububebuGuBobicio" instanceTypeName="typeAlgugudaGuboBoCio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AufribiBubuBebuboBifriGuBegucus">
    <eLiterals name="AnNulaubibegusbobobegues"/>
    <eLiterals name="DuDabodaes"/>
    <eLiterals name="BiBiDaBoBuBebetus"/>
    <eLiterals name="EbeDabiBigusGufriTus"/>
    <eLiterals name="BibodaNulaubinulauFribubugusBetor"/>
    <eLiterals name="DoNulaubonus"/>
    <eLiterals name="BiNulaunulAuGuBeGusAuGucio"/>
    <eLiterals name="EunulAuGusDaGustin"/>
    <eLiterals name="BidabuGuGusgusaubeBenulAubububuBoGusBucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuDabogusgusBubugusdaDabicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EugusBibonulaubeEs" eSuperTypes="//DuDabogusgusBubugusdaDabicio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibuDabubiBegubufriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabobiBoGues" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begulus" eType="//AldabubububebuGuBobicio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dufribies" eType="//AufribiBubuBebuboBifriGuBegucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAufribuNulAuGusguBiBetin" eSuperTypes="//DuDabogusgusBubugusdaDabicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anNulaugusfribebobuguBeDacio" ordered="false" eType="//AGuDaGuBoGudaCus" eOpposite="//AGuDaGuBoGudaCus/bidaBefribeguBuNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafriboBeBogububogunulauguslius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGuDaGuBoGudaCus" eSuperTypes="//DuDabogusgusBubugusdaDabicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaBefribeguBuNulius" ordered="false" upperBound="-1" eType="//BrAufribuNulAuGusguBiBetin" eOpposite="//BrAufribuNulAuGusguBiBetin/anNulaugusfribebobuguBeDacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagufribibudaguBedalius" abstract="true" eSuperTypes="//DafriboBeBogububogunulauguslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biGusNulAugubeGusdanulaubotus" ordered="false" eType="//AGuDaGuBoGudaCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EboBibofriDagubunulaubugunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobobibobedaGusius" eSuperTypes="//EboBibofriDagubunulaubugunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="babiGusbuBegubiFribeNus" eType="//AufribiBubuBebuboBifriGuBegucus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusbobifrigusgusnulautin" ordered="false" upperBound="-1" eType="//DafriboBeBogububogunulauguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubobufriGusauCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbinulAuDabuGubefries" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abeBeNulaubogusnulAuNus" ordered="false" eType="//DuDabogusgusBubugusdaDabicio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bafritus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaboDabudabuNules"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabofriGuNulAubobogusbiGusbeTor" eSuperTypes="//EboBibofriDagubunulaubugunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eBifribuBofritus" eType="//AldabubububebuGuBobicio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DodaDaBunulAuBegudacus" instanceTypeName="typeBabobidabecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBuFriGusdanulaunus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbudagusnulauGugugusdabugutor" eSuperTypes="//BrAufribuNulAuGusguBiBetin //FabofriGuNulAubobogusbiGusbeTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadaDaguBuBibigusGufricio" upperBound="-1" eType="//EbinulAuDabuGubefries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AdabinulaubebiNulAuGusNulaufricus">
    <eLiterals name="EugusAuboBudanulAugubedaNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DibinulauFriboDadafriFribies">
    <eLiterals name="EugudaNulAuBuBinulaubiTus"/>
    <eLiterals name="BedabeboBugubenus"/>
    <eLiterals name="BiBeBiGubobigusbobotin"/>
    <eLiterals name="DobuBuFrigusgusTor"/>
    <eLiterals name="Anbububebubegustus"/>
    <eLiterals name="Dobibibogusdagubolius"/>
    <eLiterals name="EuBuNulaugusdaCio"/>
    <eLiterals name="FabobedaDagusFrinulius"/>
    <eLiterals name="DaGubedagudaboGusbiBelus"/>
    <eLiterals name="DobiFridabies"/>
    <eLiterals name="BraudaBubigusNulaubulius"/>
    <eLiterals name="DunulauGusbobobocio"/>
    <eLiterals name="DabobebugusnulAubobigugucio"/>
    <eLiterals name="EBugufrigusTus"/>
    <eLiterals name="ABiboGusdanulaubufribobebuNulius"/>
    <eLiterals name="BadaguBenulauGusgusbinulaudaTor"/>
    <eLiterals name="EbufriFriNulaugunulaubocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulauDagusaubiBiNules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="augusBeBoBeGubelus" eType="//DibinulauFriboDadafriFribies" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifriguGusNulAudadaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baguBububuGuBenus" ordered="false" upperBound="-1" eType="//BaboDabudabuNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbibobobeGusGusdagusFribiDalius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eFriBenulauBodafriTus" eType="//DodaDaBunulAuBegudacus" transient="true"/>
  </eClassifiers>
</ecore:EPackage>
