<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dufrinulautus" nsURI="http://hub.de/rcore/examples/dufrinulautus" nsPrefix="aU">
  <eClassifiers xsi:type="ecore:EClass" name="AlbiguBigusNulauFritor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Bigubegusbifrinulaubogusdafrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bebigusnus" eSuperTypes="//AlbiguBigusNulauFritor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlGusBiGuNulaugulius">
    <eLiterals name="Dafrigusdabolius"/>
    <eLiterals name="EugubofribibiguGubuBunulEs"/>
    <eLiterals name="DugusNulauBoGunulaugusBefribogusBulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngubuBogubinulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabifrinulaufridalius" ordered="false" upperBound="-1" eType="//Bebigusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibebifriboDaCio" abstract="true" eSuperTypes="//AngubuBogubinulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfrigusbigusbebuBifriGusAunulaubiguboCus" ordered="false" upperBound="-1" eType="//AlbiguBigusNulauFritor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbebefriGugugubiBetor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuBedatus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AlFrifribebinulaubogunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaFriGusbidaboboguBinus" eSuperTypes="//AngubuBogubinulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedabobogusbebudaCus" upperBound="-1" eType="//Bebigusnus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albegusfribuDabubibegufriBogucus" ordered="false" eType="//AngubeNulaufries" eOpposite="//AngubeNulaufries/edagugusDaBogubonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngubeNulaufries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bifriguboboGusbiGudaBebitor" upperBound="-1" eType="//AlbiguBigusNulauFritor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edagugusDaBogubonus" ordered="false" eType="//DaFriGusbidaboboguBinus" eOpposite="//DaFriGusbidaboboguBinus/albegusfribuDabubibegufriBogucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBogugusnulaudadanus" ordered="false" upperBound="-1" eType="//Bebigusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaGububegusBuGuBebotus" eSuperTypes="//AlbiguBigusNulauFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaunulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alFribuNulaufridalus" ordered="false" eType="//BibebifriboDaCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusgufriDaboNus" eSuperTypes="//DaFriGusbidaboboguBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibibebubeBoNulaudabotor" eSuperTypes="//DaGububegusBuGuBebotus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DinulaubogusAufrinulAuBiGubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadaGudanules" eSuperTypes="//EbuBedatus //FaNulaunulaucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anBeNulaugusnus" eType="//AlGusBiGuNulaugulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbegusgusbobegusDaDafricio" eSuperTypes="//AlbiguBigusNulauFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubibebuBebibilius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EudabeNulauDaLus" abstract="true" eSuperTypes="//DaFriGusbidaboboguBinus //AbebefriGugugubiBetor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EunulaudaFribegunulautor"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadabuNulAuDagusgusguGusauNus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoNulauDafribebobibetor" instanceTypeName="typeDafribuboBibobiboguboguFrinulauboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebobedanulAuNus" abstract="true" eSuperTypes="//FadaGudanules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuboFribubiNulautin" instanceTypeName="typeFaBubugusbubuNulAuBuBeDadadabubiLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauDadadaDaGusBubuFribulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begusBuGusbonulauBifriguLius" eType="//DoNulauDafribebobibetor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BeNulAuboFridaBetus">
    <eLiterals name="DugunulAuBobibucio"/>
    <eLiterals name="AuGusbogusguguguBebobeBiNulAulius"/>
    <eLiterals name="EdabobiDaBibeBeFriBudaGuBolus"/>
    <eLiterals name="DifrifridabuNulAunulaugucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdabebuGusbiTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufrinulauBeboGudaEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daguGusgufriguboDabibubufriCus" ordered="false" eType="//Bebigusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ABoDagusGusnulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusBoBeBeBoBuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugusbifriboNulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabubobuGuBebefriGusBiBibetor" ordered="false" eType="//FagusBoBeBeBoBuCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbubegusgusBoBiNulautin" eSuperTypes="//FadaGudanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbobuGusbiBibuFritor" eSuperTypes="//AubibebuBebibilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabigusguGusbenulaudabidadaBogues" eSuperTypes="//AlbegusgusbobegusDaDafricio //FadaGudanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbubiBigusfriDabobuBucio" eSuperTypes="//AlbiguBigusNulauFritor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiNulaunulauBoFribuGuFriFribotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DagusbigusBoGubinus" eSuperTypes="//FadabuNulAuDagusgusguGusauNus //DiNulaunulauBoFribuGuFriFribotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbigusaudaGugunulAuGuTin" eSuperTypes="//DufrinulauBeboGudaEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuguFriFribedaBuBiCio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EunulauBoBonulaubobeCus" instanceTypeName="typeDoGusDaDaBiBobigutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbogububoGuboCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnguboFriGuGufridanulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DiFrigusTus">
    <eLiterals name="EDaBetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaBibeGusbebogusFribebuTor" eSuperTypes="//DabigusguGusbenulaudabidadaBogues"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabubuBobeBetor" eSuperTypes="//EbubegusgusBoBiNulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusbiNulaunulaubilius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibogusdabubies" eType="//BeNulAuboFridaBetus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebebunulAubodaguGuGusgunus" eType="//AbogububoGuboCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DafridanulAubiGutus" instanceTypeName="typeEgusfrinulauNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusfriBigugusDaDabitor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobeBobobitin" eType="//DiFrigusTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusgusbunulAubofritor" eSuperTypes="//AngubuBogubinulaucus //AbobuGusbiBibuFritor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Dagugunules">
    <eLiterals name="AnbeBebebiFrinulauguBenus"/>
    <eLiterals name="EuBiBodagusbiLus"/>
    <eLiterals name="AgusbuBebobibebiBocio"/>
    <eLiterals name="AngusboFrinulAugusgucus"/>
    <eLiterals name="FaBiFribibogufriBetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgusBoGunulaugustus" eSuperTypes="//AubibebuBebibilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusdagusBebobogugusguBonules" ordered="false" eType="//AlbiguBigusNulauFritor"/>
  </eClassifiers>
</ecore:EPackage>
