<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="da" nsURI="http://hub.de/rcore/examples/da" nsPrefix="myr">
  <eClassifiers xsi:type="ecore:EClass" name="BraunulAuNulaubeguBiGusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbuGusfridaNulAulius" eSuperTypes="//BraunulAuNulaubeguBiGusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dububigugugusdagusius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaguBubenulAudabuBiBitor" instanceTypeName="typeDoBufribiBigusboNulaugusBebitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegusGubiDabigulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albiNulautin" ordered="false" upperBound="-1" eType="//BraunulAuNulaubeguBiGusIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ABubobebonulauGuBuBetus" instanceTypeName="typeDubuBuBiguGubegusgusBubefrigusauCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufrigunulaubuGubilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafriBoBegusgufridabibucus" eSuperTypes="//Dububigugugusdagusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiboGuboGugusbibibogudagutus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eTin" eType="//ABubobebonulauGuBuBetus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anfribidaguses" eType="//ABubobebonulauGuBuBetus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dunulaufribibinulaubotus" abstract="true" eSuperTypes="//Dububigugugusdagusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobudafrinulAubutor" upperBound="-1" eType="//DufrigunulaubuGubilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndabugusNulAuDaBofricio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubodanulAuBidanulaubobilius" ordered="false" eType="//BafriBoBegusgufridabibucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguGusNulAuBuBuBibotin" ordered="false" upperBound="-1" eType="//EbuGusfridaNulAulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugufriDanulaugucus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebenulauFriBobuCio" upperBound="-1" eType="//ABubobebonulauGuBuBetus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufrifrifridabeDadaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbobobuEs" abstract="true" eSuperTypes="//BafriBoBegusgufridabibucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBobudabibeDafriCio" ordered="false" eType="//Dububigugugusdagusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ebubefrigugusbees"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulaubeFriBubinulaugusbofribugutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFribuDafrinulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibeBibubeBuguGusauGusfribuBubuBibibulius" abstract="true" eSuperTypes="//AlbobobuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AunulaunulauguGugunulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagugugunulauBuLius" ordered="false" upperBound="-1" eType="//DiboGuboGugusbibibogudagutus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabebibigusBubiNulaugusbibetin" ordered="false" upperBound="-1" eType="//Dububigugugusdagusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusfriBuguDaFriNulaubeBiBogubutin" eSuperTypes="//AunulaunulauguGugunulaucus //EbuGusfridaNulAulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doNulaubeguBuBobegubitor" eType="//DaguBubenulAudabuBiBitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubuBogusguGuboNulaufriBebiBues" eSuperTypes="//Dububigugugusdagusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aboguGudaNulAuGuButus" ordered="false" eType="//Dunulaufribibinulaubotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobugusbidaguDanulaugusnulEs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogubogubodator" eType="//DaguBubenulAudabuBiBitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBubidabuNus" eSuperTypes="//Dububigugugusdagusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaFribuBudabenus" eSuperTypes="//BraunulAuNulaubeguBiGusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiDanulaugusBibenulaugufriLius" eSuperTypes="//Ebubefrigugusbees">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benulauFriBeBugudabeLus" eType="//DaguBubenulAudabuBiBitor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alAugubiNulaufrifricio" upperBound="-1" eType="//DaguBubenulAudabuBiBitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigufriBugusBoGubeDaBitin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubufribuboBibifribolus" ordered="false" upperBound="-1" eType="//BafriBoBegusgufridabibucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alauBoNulaufribibutus" ordered="false" upperBound="-1" eType="//BafriBoBegusgufridabibucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGuFrinulAubonulAubuGuscio" ordered="false" upperBound="-1" eType="//AugufriDanulaugucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaFriFrigusbibibetus" eSuperTypes="//DiDanulaugusBibenulaugufriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EfrigubigusbibinulauboBolius" eSuperTypes="//FaFribuDafrinulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubegufriBodaBoboGuTus" ordered="false" eType="//Ebubefrigugusbees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusGusDabudaGusauGusfrifribenules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBuBies" ordered="false" eType="//FaFribuDafrinulaulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eunulaubodacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigubububufrinulauBunulauGuses" ordered="false" eType="//DiDanulaugusBibenulaugufriLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebogusFrifridafries" ordered="false" upperBound="-1" eType="//Ebubefrigugusbees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuGugusbibebibeboNulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraufridabogusbuFribobonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBeFribigunulauFribefridator" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibebogugusfribiGugusCus" ordered="false" eType="//AlbobobuEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraunulauBefrigudaboNulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abubuDabobeFriDadaCus" eType="//ABubobebonulauGuBuBetus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eubibogusboBeEs" eType="//DaguBubenulAudabuBiBitor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBodabogunus" ordered="false" eType="//AlfribiNulaunulAudagubitus" eOpposite="//AlfribiNulaunulAudagubitus/dobiGusBobiBodagudaTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbiGusdagusfriboBeBotus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafriguDabedanulAuboBefriBiBeBuCus" eSuperTypes="//DobugusbidaguDanulaugusnulEs //DufrigunulaubuGubilus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dububobutus" eType="//ABubobebonulauGuBuBetus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibefribiBuButor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bagubefridaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfribiNulaunulAudagubitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobiGusBobiBodagudaTor" ordered="false" eType="//BraunulauBefrigudaboNulius" eOpposite="//BraunulauBefrigudaboNulius/beBodabogunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anDagubiBuboFridaBiFriCio" ordered="false" upperBound="-1" eType="//Eunulaubodacio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBenulaugugubuTor" eSuperTypes="//DiDanulaugusBibenulaugufriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuDaBedabiboGusaubogusaubufrilius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufrifribeboDaGusBunulaufrinus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DigusBegugusfribibebiNulAunulaudaes" instanceTypeName="typeAlgusbugusbebenulautor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DugububibobobobefriBoGusguLus">
    <eLiterals name="DifribefribogusfribibibofriBubobitor"/>
    <eLiterals name="Digusdafribubudagusius"/>
    <eLiterals name="DoNulauFriBocio"/>
    <eLiterals name="DiguBufriDaguBiboLius"/>
    <eLiterals name="DibeDaboNulAucus"/>
    <eLiterals name="BrauFriNulaubues"/>
    <eLiterals name="AldagusfriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGugubuFriBedadagusbunulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ebegubobegusbegubutor" abstract="true" eSuperTypes="//AlbobobuEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibeboBeGuboNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FaBotor">
    <eLiterals name="AfrigusnulaubobiCus"/>
    <eLiterals name="Eubibolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiDagusbiBobuguBebiBoDaes" eSuperTypes="//DaFriFrigusbibibetus //DufrigunulaubuGubilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaNulauBubeNulAuguTus" instanceTypeName="typeAubofriGusgusFriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndabefribiDanulaugusguTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulaubonulaubugubigusBeLius" eSuperTypes="//DibeboBeGuboNus //DiDanulaugusBibenulaugufriLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufrigusdadagugusBeTin" abstract="true" eSuperTypes="//DuGusGusDabudaGusauGusfrifribenules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafriBiboBeBuBeTus" ordered="false" upperBound="-1" eType="//BraufridabogusbuFribobonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulaunulauGusGuBigusIus" eSuperTypes="//DufrigunulaubuGubilus //EubuBogusguGuboNulaufriBebiBues"/>
</ecore:EPackage>
