<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="braunules" nsURI="http://hub.de/rcore/examples/braunules" nsPrefix="s">
  <eClassifiers xsi:type="ecore:EClass" name="DibegudaboDaBoDaGusbigubobidaBobuCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubebonulAuNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubunulAudabefritin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dafriboguboBifrigufritus" ordered="false" eType="//EubebonulAuNulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabiFribiGusbibeBedaGuNulaubefriNulius" ordered="false" upperBound="-1" eType="//EubebonulAuNulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGugusDabigubuDaboCio" eSuperTypes="//EubebonulAuNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusDaDagusboDabeTor" ordered="false" upperBound="-1" eType="//DubunulAudabefritin"/>
  </eClassifiers>
</ecore:EPackage>
