<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dobidabobigusfrifritor" nsURI="http://hub.de/rcore/examples/dobidabobigusfrifritor" nsPrefix="u">
  <eClassifiers xsi:type="ecore:EClass" name="FaBububobububoguscus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Befribedabogubogusdanulaugubecus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibeGuguBenulauBeguscio" ordered="false" eType="//FaBububobububoguscus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAudagusgunulius" ordered="false" eType="//FaBububobububoguscus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="egusNulaugusgugudagusbegubibodaLius" ordered="false" eType="//FaBinulAudadaGuDafrigubegusIus" eOpposite="//FaBinulAudadaGuDafrigubegusIus/bidaBubeGububugusBuGuguDalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrauDaGusbuGuslius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGudabofriGuses" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibonulaubiGugudagusgusgusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulaugusbecio" ordered="false" eType="//BrauDaGusbuGuslius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daboFribubigububuDacus" ordered="false" upperBound="-1" eType="//Befribedabogubogusdanulaugubecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Danulaunulaugusfribocus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugubobigusdaGusdaBebeFrifriDadaes" abstract="true" eSuperTypes="//BrauDaGusbuGuslius //FaBububobububoguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBebigusgutin" ordered="false" upperBound="-1" eType="//BeGudabofriGuses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anboBiBidafriDafrinulAubiDacus" upperBound="-1" eType="//Befribedabogubogusdanulaugubecus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusbeboBibiGubodabufritin" eSuperTypes="//Befribedabogubogusdanulaugubecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFriNulauGusbebudadabebugusIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebuBigusFries" ordered="false" upperBound="-1" eType="//FaBububobububoguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fabegubogubucus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Braubobolus" eSuperTypes="//BrauDaGusbuGuslius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaufrifrifriboboboNulaubufriguBolus" ordered="false" eType="//AnFriNulauGusbebudadabebugusIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbunulaubiBobiDabufribubofrilius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaBugugubiNulaugusbubulius"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DugusAufrifribibibegusdatin">
    <eLiterals name="EDaBufridafriguBunus"/>
    <eLiterals name="AnbobonulAuBeNulauBebigulus"/>
    <eLiterals name="DoGusaunulaudaGusDadaboTin"/>
    <eLiterals name="FaBegusGusauBiGunulaudabibeguBonus"/>
    <eLiterals name="EnulaugusBoDabugufriFribubeTus"/>
    <eLiterals name="Fabibedagucus"/>
    <eLiterals name="BaGusauguDabefrifricio"/>
    <eLiterals name="DonulaufrigusbobigusfribebeBotor"/>
    <eLiterals name="EBibubuBoboTor"/>
    <eLiterals name="AldagubonulAufriTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbiBiBifriFriBuboNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbubeBoFriGugusDabeNulIus">
    <eLiterals name="DaGusdabobeguguDadaes"/>
    <eLiterals name="AbiBiBiboBeguGusAunulautin"/>
    <eLiterals name="BeGusBubonulauButor"/>
    <eLiterals name="AngusGugudafrinules"/>
    <eLiterals name="BigusbibedabenulaubeBoEs"/>
    <eLiterals name="BrAuBebiBoNulaubodacio"/>
    <eLiterals name="BebuboBefriDaFribiGudadaBecio"/>
    <eLiterals name="Dibobicio"/>
    <eLiterals name="AlBuboDabunulaudaDaGuslus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Bebububofribubutin">
    <eLiterals name="BefrifribebeBunulaugusAugusnulius"/>
    <eLiterals name="AnbugusbubeBibobifribenulAutus"/>
    <eLiterals name="Anbibifribidatus"/>
    <eLiterals name="DuGuboBibebubitin"/>
    <eLiterals name="Fagubudanulius"/>
    <eLiterals name="EufriguTus"/>
    <eLiterals name="EubofriDaGugusTor"/>
    <eLiterals name="Fagusbobugusbobigutus"/>
    <eLiterals name="BeBonulauBebiCus"/>
    <eLiterals name="AudaBobiguNulaugugusdabuboguNulIus"/>
    <eLiterals name="ANulaubobedaBugusdaBofriGusnulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Babinulaunus">
    <eLiterals name="BrauboEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubibinulAubobebonules" instanceTypeName="typeFabebebeNulauBinus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Eunulaugulius" instanceTypeName="typeDuboGubugusbubibigusgudagutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaBinulAudadaGuDafrigubegusIus" eSuperTypes="//FaBububobububoguscus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaBubeGububugusBuGuguDalius" ordered="false" eType="//Befribedabogubogusdanulaugubecus" eOpposite="//Befribedabogubogusdanulaugubecus/egusNulaugusgugudagusbegubibodaLius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadaguTor" ordered="false" eType="//Braubobolus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AubogugusaubugugusfriBocio" instanceTypeName="typeBraubebeGufriGusdaBodabuFriguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlGusbobidadaGuGusGuGudadaDabolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgunulAubotor" abstract="true" eSuperTypes="//Befribedabogubogusdanulaugubecus //BeGudabofriGuses"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBibofribuNulaubidadalius" instanceTypeName="typeBeGusBoNulauGusbobiCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlBofridaGusdaBofribobeGusGuGusguslus" abstract="true" eSuperTypes="//FaBububobububoguscus //AbiBiBifriFriBuboNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulauGunulAuBolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibebuGugusboFribees" ordered="false" upperBound="-1" eType="//AlbibonulaubiGugudagusgusgusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiboguguBubefridaBebolius" eSuperTypes="//AbunulaubiBobiDabufribubofrilius //FaBinulAudadaGuDafrigubegusIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulaufribogubiTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DinulaunulaubiGunus" abstract="true" eSuperTypes="//AlGusbobidadaGuGusGuGudadaDabolus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="FafrifribeBibebeGuGunulaubedaNulIus" instanceTypeName="typeDuFribodanulAunules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGubeGubigubugusnus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebuFriboBegusdafribibiguses" eSuperTypes="//Danulaunulaugusfribocus"/>
</ecore:EPackage>
