<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dogusbocio" nsURI="http://hub.de/rcore/examples/dogusbocio" nsPrefix="bhFj">
  <eClassifiers xsi:type="ecore:EClass" name="DogugunulauGuNulAugusboBoTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edabebigubeNus" ordered="false" eType="//EbugusbogusguGuDaEs" eOpposite="//EbugusbogusguGuDaEs/beFrifriguboDaFriBibiGulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugufribibogusbebuFrifriBiFrigues" ordered="false" upperBound="-1" eType="//DubiBugusauBefriNulaubunulauGustin" eOpposite="//DubiBugusauBefriNulaubunulauGustin/alauguNulauLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubidabuBifriDagusbugusGulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbugusbogusguGuDaEs" eSuperTypes="//BraubidabuBifriDagusbugusGulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beFrifriguboDaFriBibiGulus" ordered="false" upperBound="-1" eType="//DogugunulauGuNulAugusboBoTus" eOpposite="//DogugunulauGuNulAugusboBoTus/edabebigubeNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euGuguBobogusgucio" ordered="false" upperBound="-1" eType="//AlbedaFriBifriBiBelus" eOpposite="//AlbedaFriBifriBiBelus/aunulAubenulaugusdacus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="donulAuBenulaubofriDaBenulius" ordered="false" upperBound="-1" eType="//DagusBenulAunulauNus" eOpposite="//DagusBenulAunulauNus/aufrigunulAulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulaubudabebucus" abstract="true" eSuperTypes="//EbugusbogusguGuDaEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="befriDaBuBucus" eType="//DogugunulauGuNulAugusboBoTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibiBeBinulAuBiBogulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGubeBigusbonus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DobibugubuguBegusnus">
    <eLiterals name="EGudaBies"/>
    <eLiterals name="AubiNulauBubebogubidaguTin"/>
    <eLiterals name="DiGusbubeBubugusBobobufribeBibulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DobuGuguGufriBufribonulEs" instanceTypeName="typeAnGugubibegusBegusgusBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbedaFriBifriBiBelus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAubenulaugusdacus" ordered="false" upperBound="-1" eType="//EbugusbogusguGuDaEs" eOpposite="//EbugusbogusguGuDaEs/euGuguBobogusgucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auBiGubiNulAubuGuGubocio" ordered="false" eType="//DubiBuDagusBugubiTus" eOpposite="//DubiBuDagusBugubiTus/alAubonulAugusAugulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubiBuDagusBugubiTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alAubonulAugusAugulus" ordered="false" eType="//AlbedaFriBifriBiBelus" eOpposite="//AlbedaFriBifriBiBelus/auBiGubiNulAubuGuGubocio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabeNulauBodabeNulius" ordered="false" upperBound="-1" eType="//AlbedaFriBifriBiBelus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubuBebigubues" upperBound="-1" eType="//DogusbugusNulAubiBegusDaCio" eOpposite="//DogusbugusNulAubiBegusDaCio/babodadabugusbugubefrifriBenulauTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugusnulauguBibiguBenus" eSuperTypes="//BrAunulaubudabebucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBoBibebidaGusgutus" ordered="false" upperBound="-1" eType="//AlbedaFriBifriBiBelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulAuguBolus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubebubeGusdaBinulEs" ordered="false" upperBound="-1" eType="//BibiBeBinulAuBiBogulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusdabobeNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauGusnulAubibobeBoLius" eSuperTypes="//DubiBuDagusBugubiTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusbigusbifrifribelius" ordered="false" upperBound="-1" eType="//BibiBeBinulAuBiBogulius"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adaDadaLus" eType="//DobuGuguGufriBufribonulEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugudanulAuFrifriGunulAuFribilus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBunulaudabunus" instanceTypeName="typeDabinulaugusbogusBuNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnFriGusbugudanulaudaGutin" eSuperTypes="//AlbedaFriBifriBiBelus //BraubidabuBifriDagusbugusGulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgunulaubobubifriCus" instanceTypeName="typeBeBuBibinulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbugusBidafriNulAubufrilius" eSuperTypes="//AugusnulauguBibiguBenus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuBogusgunules" eType="//DobibugubuguBegusnus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGubuNulaubilus" abstract="true" eSuperTypes="//EugudanulAuFrifriGunulAuFribilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBodabobues" ordered="false" upperBound="-1" eType="//BraubidabuBifriDagusbugusGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EbugufribugusnulauboBoBeNus">
    <eLiterals name="AlnulAufribubobufribogusBuBelius"/>
    <eLiterals name="AlAuDanulauboGusdanulAudafrinulIus"/>
    <eLiterals name="FagusauGudabifrigusaubiTin"/>
    <eLiterals name="BrAubiDaFriFriguguslus"/>
    <eLiterals name="BrauBunulAubufrinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DubiBugusauBefriNulaubunulauGustin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dies" eType="//DobuGuguGufriBufribonulEs" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alauguNulauLius" ordered="false" upperBound="-1" eType="//DogugunulauGuNulAugusboBoTus" eOpposite="//DogugunulauGuNulAugusboBoTus/eugufribibogusbebuFrifriBiFrigues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbodabodaDaBiBiguBiBefricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulAuGusnulAubefriboBugudaBinulIus" eSuperTypes="//AlbedaFriBifriBiBelus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DinulauboFribegufriGusbiCus" instanceTypeName="typeDabiFriguTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusBoBonulauguGuslus" eSuperTypes="//BraubidabuBifriDagusbugusGulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBoBubibebububofriBulius" ordered="false" upperBound="-1" eType="//AbodabodaDaBiBiguBiBefricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiFriBufrigugusNulaucio" eSuperTypes="//DubiBugusauBefriNulaubunulauGustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braunulaudagubigutor" ordered="false" eType="//BraubidabuBifriDagusbugusGulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusBenulAunulauNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aufrigunulAulius" ordered="false" upperBound="-1" eType="//EbugusbogusguGuDaEs" eOpposite="//EbugusbogusguGuDaEs/donulAuBenulaubofriDaBenulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobeGusBedabebenulauboBogusbubiTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguBigusGusDaboGusBufridaes" ordered="false" upperBound="-1" eType="//AnFriGusbugudanulaudaGutin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dodagusboguboboBobiLius" ordered="false" eType="//BrauGusnulAubibobeBoLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eudabonulaugunulautus" eSuperTypes="//AbodabodaDaBiBiguBiBefricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algusbibobefriBugulius" eType="//DinulauboFribegufriGusbiCus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubefrifriBufriFriEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dogugudaboguBuboBicio" ordered="false" upperBound="-1" eType="//DubiBuDagusBugubiTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difriboNulAunulaufriTus" ordered="false" upperBound="-1" eType="//AugusnulauguBibiguBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DaguFrinulaunulaugubebeboNulius" instanceTypeName="typeDoBobebifriNulaububodadaBonulAuLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBuNulaufriFribeCus" instanceTypeName="typeAlbenulAudaNulaunulAufribibutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBigubofriLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriDabubiboGusGubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBufribebubeBunulaudaBidabolius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="egugugusbibonulius" upperBound="-1" eType="//EubefrifriBufriFriEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Dibies" instanceTypeName="typeBrauBegusbinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AldaDaBonulAubudanulaufricio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBibeboGuBibiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didabibugufribebeEs" ordered="false" eType="//BibiBeBinulAuBiBogulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaFriBibunulautin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euBogusgusBeEs" eType="//DoBunulaudabunus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braubebibuguNulaucus" ordered="false" eType="//AbodabodaDaBiBiguBiBefricus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebobubedafriGusauBegusbogusnulauTus" ordered="false" upperBound="-1" eType="//BrAunulaubudabebucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusbugusNulAubiBegusDaCio" eSuperTypes="//BaFriBibunulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGuBidagusdaguscio" ordered="false" eType="//FaNulAuGusnulAubefriboBugudaBinulIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBogubobeBeBinulautus" ordered="false" upperBound="-1" eType="//DogugunulauGuNulAugusboBoTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babodadabugusbugubefrifriBenulauTor" ordered="false" upperBound="-1" eType="//DubiBuDagusBugubiTus" eOpposite="//DubiBuDagusBugubiTus/dubuBebigubues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabeDadabufrifrifrigusnulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGuBedabuBubebeGuFributus" ordered="false" eType="//AugusnulauguBibiguBenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnulaubuBoFribobubelus" eSuperTypes="//DogusbugusNulAubiBegusDaCio //DagusBenulAunulauNus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBiguBudabibebitus" instanceTypeName="typeDadagubifridaBuLus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DufridafribebububiGugusdaTus">
    <eLiterals name="BrauBobugusgusauBubeBidadanus"/>
    <eLiterals name="BifriBoGubodabeFriLus"/>
    <eLiterals name="Antin"/>
    <eLiterals name="ABogubiBoDaFrigusbibuBofriBoBufribobolius"/>
    <eLiterals name="Dadanulaufridanulaunus"/>
    <eLiterals name="EfriGusguBigusbenulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusBeGusbofridadagunulaunulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadanulAubobodaButor" abstract="true" eSuperTypes="//AnFriGusbugudanulaudaGutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabubeBebogustin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beboboBenulaubiTus" eType="//DobibugubuguBegusnus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfriDadabodagusBicus" eType="//DoBunulaudabunus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulAuDabodagusbeFribubucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauNulaugusbubugusCio" eSuperTypes="//BaGubeBigusbonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusbibubinulEs" ordered="false" eType="//AbugusBidafriNulAubufrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbodabebufriguGusauBunulAutus" eSuperTypes="//DufriDabubiboGusGubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusBidabiLus" eSuperTypes="//DabeDadabufrifrifrigusnulaulus //AlnulAuDabodagusbeFribubucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Begusnulaubutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabebeBogusbigucio" ordered="false" eType="//DabubeBebogustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusgubeBegusbigubuNules" abstract="true" eSuperTypes="//DabeDadabufrifrifrigusnulaulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FanulauFrigubefribenulauFriBeBetin" eSuperTypes="//EgusBidabiLus //BibiBeBinulAuBiBogulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anDabunulius" ordered="false" upperBound="-1" eType="//DabubeBebogustin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusaudaguBuBobobedaEs"/>
</ecore:EPackage>
