<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="be" nsURI="http://hub.de/rcore/examples/be" nsPrefix="vuNU">
  <eClassifiers xsi:type="ecore:EClass" name="BraugusnulAuBiGuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulaugusaunulaugusbiBetus" ordered="false" eType="//BrAufriguBubedagutin" eOpposite="//BrAufriguBubedagutin/duNulAunulAufrinulautor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabegugubuDaNus" eSuperTypes="//BraugusnulAuBiGuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agubobolus" ordered="false" upperBound="-1" eType="//BedaBobubibigubigustus" eOpposite="//BedaBobubibigubigustus/fanulaubobebeguBibeBuBonules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBonulaunulEs" abstract="true" eSuperTypes="//BraugusnulAuBiGuNus //FabegugubuDaNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGuBobobibufries" eSuperTypes="//EBonulaunulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnBudabunulaufrigusguEs" eSuperTypes="//BraugusnulAuBiGuNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fabebeFribuguboBiGunus" ordered="false" upperBound="-1" eType="//EBonulaunulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbodaDaBenulaunulAufriDanules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabudaBuBiGusFricus" ordered="false" eType="//BraugusnulAuBiGuNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBubobibenulaudaBobegusBoGusFriGuscio" ordered="false" eType="//BanulaugusAulus" eOpposite="//BanulaugusAulus/abufrinulaubedaFrigusbotor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bebobobugusbinulaubunulaulius" eSuperTypes="//FabegugubuDaNus //AbodaDaBenulaunulAufriDanules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusaudabeboFritor" ordered="false" upperBound="-1" eType="//AnBudabunulaufrigusguEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugusBobeBibogusGubotus" ordered="false" upperBound="-1" eType="//AnBudabunulaufrigusguEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusBufridaBuGuBecio" eSuperTypes="//BraugusnulAuBiGuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FadaGusGusdagusauguBoboBocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuDagusBeDabofribocio" eSuperTypes="//BraugusnulAuBiGuNus //FadaGusGusdagusauguBoboBocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGusgubeDafrinulAuguGuslus" ordered="false" upperBound="-1" eType="//FadaGusGusdagusauguBoboBocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafriNulauBebiBoDabinulaudadatus" eSuperTypes="//DaGuBobobibufries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angusdagusBuGusNus" ordered="false" eType="//BedaBobubibigubigustus" eOpposite="//BedaBobubibigubigustus/doguDadaBubibitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubiBuBinulaunulauBilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaBuBebebuBoguBenulIus" eSuperTypes="//FadaGusGusdagusauguBoboBocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudagusbefribobinulaubofrinulautin" eType="//BraugugusbenulauGusnulauNus" eOpposite="//BraugugusbenulauGusnulauNus/dadabibeGusbinulaunulauLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusbeGunus" eSuperTypes="//AuDagusBeDabofribocio //BraubiBuBinulaunulauBilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aunulAuBiBeDaGuNulAuBunulAugusEs" ordered="false" eType="//DaDabefriNus" eOpposite="//DaDabefriNus/dobifribobonulaugusGusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EnulAugusGuGuguGugusguDanulius" instanceTypeName="typeBiDagusdabuFrigubifriboLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibuguboGubigusbuTor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlgudaboFriDaFriboGuGusgusbebidabedaBetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBiBuguDanulaubeLius" upperBound="-1" eType="//DuGusbeGunus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBoBotus" ordered="false" upperBound="-1" eType="//DaGuBobobibufries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alguBobiBifrigusbubees" ordered="false" eType="//AnBonulaububibefribugufriBoTin" eOpposite="//AnBonulaububibefribugufriBoTin/bagusGusFriDaDabodaboBiNulaubonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnboBeFribeBobocus" instanceTypeName="typeAgusgugunulaubocio"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABogusdaGuLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diGunulAuFriFriBoboBufricio" upperBound="-1" eType="//AuDagusBeDabofribocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlboDanulaunulaububoBoBeGuguGuscus" instanceTypeName="typeBabibiDaBunulAufribilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BifriDabebogusGubobudaboDafribiguDaTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eDaDanulauFriBiguGusBufrilius" ordered="false" upperBound="-1" eType="//DonulauBibiBibeFriFriDalus" eOpposite="//DonulauBibiBibeFriFriDalus/baFrifriGusguGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadagusbofriBubutor" eSuperTypes="//BraugusnulAuBiGuNus //ABogusdaGuLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBedaBuboDaLius" upperBound="-1" eType="//Bebobobugusbinulaubunulaulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="euDabegusbobibiboTin" ordered="false" eType="//DaGuBobobibufries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DodabofrifrinulauNulauGuscus">
    <eLiterals name="BebeGufriDadafriBeLius"/>
    <eLiterals name="BanulAubinulauguscus"/>
    <eLiterals name="AnbogusDadafribubudaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibeDadabodacus" abstract="true" eSuperTypes="//DaBuBebebuBoguBenulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusAubuBubiDagugufriDadaLius" ordered="false" upperBound="-1" eType="//AuDagusBeDabofribocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubibeboGusbugusBogusbeDanus" instanceTypeName="typeAufriBubiGunulaubodanulautin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDabefriNus" abstract="true" eSuperTypes="//AbodaDaBenulaunulAufriDanules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobifribobonulaugusGusCus" ordered="false" upperBound="-1" eType="//DuGusbeGunus" eOpposite="//DuGusbeGunus/aunulAuBiBeDaGuNulAuBunulAugusEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebogusdabofridabeNulaugusBocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubefriNulaufribugubudabeBifriTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="daBebinulaubebobiDacus" ordered="false" eType="//DaDabefriNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAufriguBubedagutin" eSuperTypes="//AuDagusBeDabofribocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duNulAunulAufrinulautor" ordered="false" upperBound="-1" eType="//BraugusnulAuBiGuNus" eOpposite="//BraugusnulAuBiGuNus/fanulaugusaunulaugusbiBetus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusDafriBunulAugusbiBoFries" ordered="false" eType="//BraugusnulAuBiGuNus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobegusnulauGusbenulAudaLius" upperBound="-1" eType="//DafriNulauBebiBoDabinulaudadatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabeBucus" eType="//AnboBeFribeBobocus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedaBobubibigubigustus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fanulaubobebeguBibeBuBonules" ordered="false" eType="//FabegugubuDaNus" eOpposite="//FabegugubuDaNus/agubobolus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doguDadaBubibitus" ordered="false" upperBound="-1" eType="//DafriNulauBebiBoDabinulaudadatus" eOpposite="//DafriNulauBebiBoDabinulaudadatus/angusdagusBuGusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBonulaububibefribugufriBoTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagusGusFriDaDabodaboBiNulaubonus" ordered="false" eType="//AlgudaboFriDaFriboGuGusgusbebidabedaBetor" eOpposite="//AlgudaboFriDaFriboGuGusgusbebidabedaBetor/alguBobiBifrigusbubees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibobiboGusnulaugusbedabodatin" eSuperTypes="//DuGusbeGunus //BeGusBufridaBuGuBecio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biboguBugues" ordered="false" upperBound="-1" eType="//FaGusnulaufrigusfriBoDalius" eOpposite="//FaGusnulaufrigusfriBoDalius/dubefriguFricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraugugusbenulauGusnulauNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadabibeGusbinulaunulauLus" ordered="false" eType="//DaBuBebebuBoguBenulIus" eOpposite="//DaBuBebebuBoguBenulIus/eudagusbefribobinulaubofrinulautin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabenulaugusfribidaBunulautin" eSuperTypes="//BibobiboGusnulaugusbedabodatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusfrinulauNulaububotor" eSuperTypes="//BebogusdabofridabeNulaugusBocus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anBinulaubebotus" eType="//AnboBeFribeBobocus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBeNulaunulauFribuboTus" ordered="false" eType="//AnGusbobedaBebebofrigudabudaTin" eOpposite="//AnGusbobedaBebebofrigudabudaTin/beBuboFribobonulaudabenules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="efriBogusbonulius" upperBound="-1" eType="//DiBoguboFriBigusauGusNulAuBeBuTus" eOpposite="//DiBoguboFriBigusauGusNulAuBeBuTus/brAuGusbeguBugusCus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Didagubodanus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibubegusgubiNulAuGuslius" eType="//AlboDanulaunulaububoBoBeGuguGuscus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FagusfriboFrifrigusdabucio" instanceTypeName="typeDies"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeBibibobidaLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbedabenulAubufriBuCio" eType="//BraubibeboGusbugusBogusbeDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulaububenulauGubuTus" eSuperTypes="//Didagubodanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubiDaNulAufribues" ordered="false" eType="//DaDabefriNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBuNulAubebubulius" eSuperTypes="//BraugugusbenulauGusnulauNus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ABeboBigusboBeBoguCio">
    <eLiterals name="EuGufribuDagusAugunulaudatus"/>
    <eLiterals name="Dabegusbunules"/>
    <eLiterals name="DoDaboBenulAunus"/>
    <eLiterals name="AlFriNulAubuBuNulIus"/>
    <eLiterals name="AldabugusbugusNulauLius"/>
    <eLiterals name="AlBenulaugusbuNulAuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulaudabibiBuNus" eSuperTypes="//BebogusdabofridabeNulaugusBocus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aGusBubedaEs" eType="//BraubibeboGusbugusBogusbeDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoguFrifrifritor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angubebebudaGusBenulaucio" eType="//BraubibeboGusbugusBogusbeDanus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabufribudaguGubofriTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebobeboguguNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulaunulAubeDabuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusBoNulAubutor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dodanulaufriboBubidagunulautus" eType="//EnulAugusGuGuguGugusguDanulius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DunulauGubofriGusBeEs" instanceTypeName="typeFaBeBunulauBiBugubifribiCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdaGusbibobeGusautus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoGusAudabogusbibubeCus" instanceTypeName="typeBebigusauguses"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlboboboBubeBeguses" instanceTypeName="typeDifrigustus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGubeDadadaEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bidaBogubiBibibibubigugusbetor" ordered="false" eType="//FadaGusGusdagusauguBoboBocio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnGusbobedaBebebofrigudabudaTin" abstract="true" eSuperTypes="//FadaGusGusdagusauguBoboBocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBuboFribobonulaudabenules" ordered="false" eType="//DoGusfrinulauNulaububotor" eOpposite="//DoGusfrinulauNulaububotor/diBeNulaunulauFribuboTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobiFrinulaugucus" eSuperTypes="//DaDabefriNus //BraugugusbenulauGusnulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABuguBenulAubobifribugunules" abstract="true" eSuperTypes="//BedaBobubibigubigustus //BeGusBufridaBuGuBecio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulauBoguBigusNulAudaCio" eSuperTypes="//DoGusfrinulauNulaububotor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BigusBobiNulaubibutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonulauBibiBibeFriFriDalus" eSuperTypes="//DaGubeDadadaEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baFrifriGusguGuses" ordered="false" upperBound="-1" eType="//BifriDabebogusGubobudaboDafribiguDaTin" eOpposite="//BifriDabebogusGubobudaboDafribiguDaTin/eDaDanulauFriBiguGusBufrilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuBedagusCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoBegusDabobibubibeLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faBugusAugusBobodagusauNulauBogusnus" eType="//FagusfriboFrifrigusdabucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alnulaugusbigusfribeCus" upperBound="-1" eType="//BabufribudaguGubofriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AbeFriBoDagubiBubeTus" instanceTypeName="typeBigugugufribefribibeguTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauFriBebeBuNulAunulauBolius" eSuperTypes="//DaBuBebebuBoguBenulIus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobubofrifrinulaudaTus" ordered="false" upperBound="-1" eType="//BraugusnulAuBiGuNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BanulaugusAulus" eSuperTypes="//DafriNulauBebiBoDabinulaudadatus //BedaBobubibigubigustus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biFribogudabidabuboes" ordered="false" eType="//BrauFriBebeBuNulAunulauBolius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abufrinulaubedaFrigusbotor" ordered="false" upperBound="-1" eType="//AbodaDaBenulaunulAufriDanules" eOpposite="//AbodaDaBenulaunulAufriDanules/diBubobibenulaudaBobegusBoGusFriGuscio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duFriBobegunulius" upperBound="-1" eType="//BaBugusnulauBuBufriBebibilius" eOpposite="//BaBugusnulauBuBufriBebibilius/anBubiBobeDabunulAugucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusbefriDaBodaguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufriNulaubigubuGusBiguGuNulAubetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusnulAufribibubiBuguEs" eSuperTypes="//DibuguboGubigusbuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBeDaGusaufriGuBeLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AnaudabifrigusBuDagusgubeLius" instanceTypeName="typeDugugubigusauTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibonulAuBigudadaDanus" eSuperTypes="//DuNulaububenulauGubuTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DunulAufriDaboGuNulautin" instanceTypeName="typeDabeBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbuguFribidafribidaLius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BebiBuBibogusdaEs" instanceTypeName="typeDoBedabuDabogufrigusBiBoCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaGusnulaufrigusfriBoDalius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubefriguFricus" upperBound="-1" eType="//BibobiboGusnulaugusbedabodatin" eOpposite="//BibobiboGusnulaugusbedabodatin/biboguBugues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlguGusauguboDaFrifrigusaububigusTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BibebebegusfriDabuguBubugubucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dudabobogutin" upperBound="-1" eType="//DonulauBibiBibeFriFriDalus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugubedagusGusfribebubeFridanus" ordered="false" upperBound="-1" eType="//EBonulaunulEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anaugusbiBidaLus" ordered="false" upperBound="-1" eType="//DaGubeDadadaEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBiBiFriBiFriBilus" eSuperTypes="//FadaGusGusdagusauguBoboBocio //DafriNulauBebiBoDabinulaudadatus //BaBeDaGusaufriGuBeLius //ABogusdaGuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudagusnulAubeNulaubutus" abstract="true" eSuperTypes="//Bebobobugusbinulaubunulaulius //BabenulaugusfribidaBunulautin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="audaGunulAuGusbegusdabobuguTor" ordered="false" upperBound="-1" eType="//AlBiBiFriBiFriBilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bigusboDabibicus" eType="//DaBuBebebuBoguBenulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AldagusnulAubotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbifridadagusguDanus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGusNulauFriBefriBitin" eSuperTypes="//FadagusbofriBubutor //AgusnulAufribibubiBuguEs //DoGusBoNulAubutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulaunulAutin" eSuperTypes="//BibeDadabodacus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bibubibegusbudanulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiGusgugubobobidaBoes" eSuperTypes="//BeBibibobidaLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doNulaubogudabubodagusBunus" eType="//FagusfriboFrifrigusdabucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbugusbeFrigubebunulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eubibifribucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBugusnulauBuBufriBebibilius" eSuperTypes="//AldagusnulAubotin //DoGusBoNulAubutor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBubiBobeDabunulAugucio" ordered="false" upperBound="-1" eType="//BanulaugusAulus" eOpposite="//BanulaugusAulus/duFriBobegunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diguslus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeFribuBuDabifribiCus" eSuperTypes="//AnbifridadagusguDanus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fagusguFribonulaubeTor" ordered="false" upperBound="-1" eType="//DonulauBibiBibeFriFriDalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubofribigusnulaubiBedabilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duNulaubibenulauBeBibolus" upperBound="-1" eType="//BraubiBuBinulaunulauBilus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EubegusGusdabufribibolius" instanceTypeName="typeEubibigufriFrigusAudadaDaNulAuNulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabogunulAugufrinulAugusbutor" eSuperTypes="//DoguFrifrifritor //BibobiboGusnulaugusbedabodatin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobebebuBiBiBuTor" upperBound="-1" eType="//AnboBeFribeBobocus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusguBegusaubebeboboBiTor" eSuperTypes="//AnBonulaububibefribugufriBoTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubugusdaboBiBenulauBiGusius" ordered="false" eType="//BaBugusnulauBuBufriBebibilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguBinulAubibinulaugusFriguBiGubecio" eType="//DibuguboGubigusbuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DaboBiLius" eSuperTypes="//ENulaudabibiBuNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnfriBobebibubobiDaDaLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibogufribeBubobebebuNulius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="andagugufrinulAuboGufrigunulautus" eType="//FagusfriboFrifrigusdabucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AugudanulauBonulaucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodabeDagusBiguGunus" eSuperTypes="//AlgudaboFriDaFriboGuGusgusbebidabedaBetor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audaBeFricus" eType="//AlboboboBubeBeguses" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eboDaguDaFriBubugunus" ordered="false" eType="//DafriFriDaBibicus" eOpposite="//DafriFriDaBibicus/bafrigusbubodaGusfriLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbedabeGuDabufribies"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusdabucus" eSuperTypes="//BibobiboGusnulaugusbedabodatin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiBifrifrigusnulaubodabibigubonus" instanceTypeName="typeFabefribobibeBifrigusbeBubiCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusgugunulauguBunulauBibelus" eSuperTypes="//BraugugusbenulauGusnulauNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badabibofriDabobilus" eType="//AnaudabifrigusBuDagusgubeLius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeDabebidabuGufriGusdaGusbuNules"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BiDabogusbibogusnulIus" instanceTypeName="typeAuBubiBeboBonulAugusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiBoguboFriBigusauGusNulAuBeBuTus" eSuperTypes="//BiGusgugubobobidaBoes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAuGusbeguBugusCus" ordered="false" eType="//DoGusfrinulauNulaububotor" eOpposite="//DoGusfrinulauNulaububotor/efriBogusbonulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DibufrigusBinulauGusgusDaBiNulautin">
    <eLiterals name="EuBegubogubeDacus"/>
    <eLiterals name="DabebebodanulaudabodaBuCio"/>
    <eLiterals name="BrauBiboBigubidagustin"/>
    <eLiterals name="FabodagusfrinulAutor"/>
    <eLiterals name="Angudagusfributor"/>
    <eLiterals name="DuBegusdanulaugusgusgulius"/>
    <eLiterals name="BrAuBeFribuboBolius"/>
    <eLiterals name="AngusBuNulauguBebonulIus"/>
    <eLiterals name="EGusbebiguslius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafriFriDaBibicus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafrigusbubodaGusfriLus" ordered="false" eType="//DodabeDagusBiguGunus" eOpposite="//DodabeDagusBiguGunus/eboDaguDaFriBubugunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAufriGudagusGuGusTus" eSuperTypes="//FaGusnulaufrigusfriBoDalius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DigugusDagugusnulaunulauBubifriFrilus" instanceTypeName="typeDobuGugusfrigunulAuguCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaGuBogubobuGusbebeLius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebefribegudabiBuTus" upperBound="-1" eType="//BaGusNulauFriBefriBitin"/>
  </eClassifiers>
</ecore:EPackage>
