<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="donulaufritus" nsURI="http://hub.de/rcore/examples/donulaufritus" nsPrefix="ZHi">
  <eClassifiers xsi:type="ecore:EClass" name="AnboGusboboDaNulaufrigufriLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulAugugusdaBiBigusbigugusDaes" ordered="false" upperBound="-1" eType="//AunulauBubugusBiLius" eOpposite="//AunulauBubugusBiLius/difriBibonulaudaguscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbubeGuGuBebobeDaDafrilius" eSuperTypes="//AnboGusboboDaNulaufrigufriLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eudaNulAuBugusbugusbofriGusgudanulAuTin" eType="//BabeNulaubeCus" eOpposite="//BabeNulaubeCus/babodabobibiNulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnGusaubogusDanules" instanceTypeName="typeDunulaufrigubufridadaBobuGubees"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBofrigunulauFribegufries" eSuperTypes="//AlbubeGuGuBebobeDaDafrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dodabeGubobuNulauNulius" ordered="false" upperBound="-1" eType="//AlbubeGuGuBebobeDaDafrilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duNulaugusfribegugusaubebogubolius" ordered="false" upperBound="-1" eType="//AnboGusboboDaNulaufrigufriLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaNulAubigugusnulaubudaBobofricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angusfriGubibees" upperBound="-1" eType="//AnGusaubogusDanules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AunulauBubugusBiLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alBeBogusgubibogusdalus" eType="//AnGusaubogusDanules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difriBibonulaudaguscus" eType="//AnboGusboboDaNulaufrigufriLus" eOpposite="//AnboGusboboDaNulaufrigufriLus/anulAugugusdaBiBigusbigugusDaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dodagusbubogusdalus" eSuperTypes="//DuBofrigunulauFribegufries //FaNulAubigugusnulaubudaBobofricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbegusfrigubiNules" eSuperTypes="//AnboGusboboDaNulaufrigufriLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DidanulAubogubonulautor" eSuperTypes="//AunulauBubugusBiLius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibefries" eType="//AnGusaubogusDanules" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adabebiFrigusDabuNulauGues" eType="//AbegusfrigubiNules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBibeGudabitor" ordered="false" upperBound="-1" eType="//AnboGusboboDaNulaufrigufriLus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="daboDaNulauboBebigusfribufrigutus" ordered="false" upperBound="-1" eType="//BabeNulaubeCus" eOpposite="//BabeNulaubeCus/anBobogubegugugusnus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBefriFriBubutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeNulaubeCus" eSuperTypes="//AunulauBubugusBiLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBobogubegugugusnus" ordered="false" eType="//DidanulAubogubonulautor" eOpposite="//DidanulAubogubonulautor/daboDaNulauboBebigusfribufrigutus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="babodabobibiNulaucus" ordered="false" upperBound="-1" eType="//AlbubeGuGuBebobeDaDafrilius" eOpposite="//AlbubeGuGuBebobeDaDafrilius/eudaNulAuBugusbugusbofriGusgudanulAuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuFrigusfriBiGusbuCus" abstract="true" eSuperTypes="//AlBefriFriBubutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anGusgusAuguguGusfribuNules" eType="//BidaBebonulauLus" eOpposite="//BidaBebonulauLus/duGusboBuguNulAutin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AfriGusBiGubufriBufritin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alguBoboboBegusTin" eType="//AnGusaubogusDanules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BaNulauFriBidabobigusaucio" instanceTypeName="typeAnauBinulaubinulAunus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BidaBebonulauLus" eSuperTypes="//FaNulAubigugusnulaubudaBobofricus //AnboGusboboDaNulaufrigufriLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eufriNulauGuBubufriBonulAuBibeLius" ordered="false" upperBound="-1" eType="//AlBefriFriBubutus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auGusFriGubobegusgucus" eType="//BaNulauFriBidabobigusaucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duGusboBuguNulAutin" ordered="false" upperBound="-1" eType="//DuFrigusfriBiGusbuCus" eOpposite="//DuFrigusfriBiGusbuCus/anGusgusAuguguGusfribuNules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="audafribiNulaubeGusdaGusAuTin" ordered="false" eType="//FaFribodabidagusauNus" eOpposite="//FaFribodabidagusauNus/bafrinulaugusbibilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="andagusboEs" upperBound="-1" eType="//EubiGudabiBugusius" eOpposite="//EubiGudabiBugusius/faBobiBibigugububuBebebegusLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbedanulAunulAubufricio" instanceTypeName="typeDagusnulaubogusbicio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AlgubeDagubobubunulAuDabigusnus" instanceTypeName="typeFaGusdaGudabebegucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulauNulaubifrinulaubetus" eSuperTypes="//DuBofrigunulauFribegufries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabububeLius" eType="//BidaBebonulauLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaFribodabidagusauNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bafrinulaugusbibilus" ordered="false" upperBound="-1" eType="//BidaBebonulauLus" eOpposite="//BidaBebonulauLus/audafribiNulaubeGusdaGusAuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DogubiFrinulAubibecus" instanceTypeName="typeDuGubuGusbuBunulaunulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaDaGusDaBoBiBibibuDatin" instanceTypeName="typeEuguNulauBubefrifriTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriBiNus" eSuperTypes="//BinulauNulaubifrinulaubetus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulauboBunulaubibebobinus" eSuperTypes="//AlBefriFriBubutus //DidanulAubogubonulautor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audafrigusnulauFrifriNus" upperBound="-1" eType="//AlgubeDagubobubunulAuDabigusnus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBenulAunulAubiGustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulaunulauCio" eSuperTypes="//AfriGusBiGubufriBufritin //DuFrigusfriBiGusbuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibibegusGuFribogusbeTor" eType="//FaFribodabidagusauNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbofribubuguFriGusnulaubebufriFricus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agusbicus" eType="//AlgubeDagubobubunulAuDabigusnus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digugubiFrinulaubigusaudalus" ordered="false" eType="//EubiGudabiBugusius" eOpposite="//EubiGudabiBugusius/braugubolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusgusbegusbofribeNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbobeFribeBufricio" ordered="false" eType="//Dodagusbubogusdalus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anulAuboBebegusgudacus" eType="//EbedanulAunulAubufricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnBuBibunulAuBibegubudator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogusFrifrigudadaBuEs" eType="//BaNulauFriBidabobigusaucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DogudagusgudaFriFribunulAutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuGugusAudadabetin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubegusgusnulAubeguLus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="andaBiboNulaunus" eType="//DogubiFrinulAubibecus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBobuGulius" ordered="false" upperBound="-1" eType="//FaNulAubigugusnulaubudaBobofricus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FabefriguGuBobigusaufriBiBiGuCio" instanceTypeName="typeDobeBuboNulAugusboboDagudaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AngusnulauGusfriboBibubuBunulauNus" eSuperTypes="//AunulauBubugusBiLius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufribidaTor" eSuperTypes="//AbegusfrigubiNules //FagusgusbegusbofribeNules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubiBiGugudaboGusBoNulaudanus" eType="//EuNulaubububiBubebigusBobiBolus" eOpposite="//EuNulaubububiBubebigusBobiBolus/eFridaFriBobibuDagusboes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabudaFriGuGusgustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugudafriBeFriBegusbeBegusIus" ordered="false" upperBound="-1" eType="//BinulauNulaubifrinulaubetus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AnBidaBoNulAubiDaNulIus" instanceTypeName="typeAnulAuGusgudagusGubebunules"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DoBunulauBobidanulaubiTus">
    <eLiterals name="BabebeFribeBibobubobubebutin"/>
    <eLiterals name="DugusaubodafriNulAuBoDaGusDator"/>
    <eLiterals name="DibiBoDafriBeNulaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EubiGudabiBugusius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="faBobiBibigugububuBebebegusLus" eType="//BidaBebonulauLus" eOpposite="//BidaBebonulauLus/andagusboEs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubugudaBedaLius" ordered="false" upperBound="-1" eType="//DuFrigusfriBiGusbuCus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugubolius" eType="//AlbofribubuguFriGusnulaubebufriFricus" eOpposite="//AlbofribubuguFriGusnulaubebufriFricus/digugubiFrinulaubigusaudalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlaubebibeBeguBibeDagusLus" eSuperTypes="//BabeNulaubeCus //EubiGudabiBugusius //EnulauboBunulaubibebobinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beBugugubofrifribiBogusEs" ordered="false" upperBound="-1" eType="//Dodagusbubogusdalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBoGusbobibegusfribees" eSuperTypes="//FaFribodabidagusauNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anboCio" eType="//AnGusaubogusDanules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EudaDaBiBudagutin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enulaunulauBiBoDatus" ordered="false" eType="//BraubegusgusnulAubeguLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaGuDaNulauDabobuLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabuguBegusbobobofritus" eSuperTypes="//AufribidaTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiBeDalus" abstract="true" eSuperTypes="//AfriGusBiGubufriBufritin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AugusAugubiFrigufribiBegubuLius">
    <eLiterals name="AubibubeguNulaubiBeBinulIus"/>
    <eLiterals name="DufribeNulAugusbeBegunulAubiLus"/>
    <eLiterals name="DaguNulauDaBonulAuboTor"/>
    <eLiterals name="DoNulaubutor"/>
    <eLiterals name="AGubuBeGuGusboLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubiBiBudaGusnulaubunulaubelius" abstract="true" eSuperTypes="//BabeNulaubeCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BeGugufrifriFries"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbeBiBiFriGusCio" abstract="true" eSuperTypes="//EBenulAunulAubiGustor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anbeBobubebeNulAutin" eType="//DoBunulauBobidanulaubiTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DuGusbubibedaguboBoes" instanceTypeName="typeAboBubegusboBibocus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EuBuBeBiCio" instanceTypeName="typeBabebubedadabifribodabolus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuboguGusGusAugubobinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anulAuBuGusBefridaBoGusbeBulius" ordered="false" eType="//DabuguBegusbobobofritus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AlfriFridabufriDabeGuNules" instanceTypeName="typeAgudadabunulauBuBiGusBotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbebobiFrigubuDaGubuBubobubucio" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ABifribuBubiGucus" eSuperTypes="//BidaBebonulauLus //AngusnulauGusfriboBibubuBunulauNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulAuguNulauGufrifricus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbebeBoBegusboguCio" abstract="true" eSuperTypes="//Dodagusbubogusdalus //AlBefriFriBubutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agusbogubigusAugusBobonus" ordered="false" upperBound="-1" eType="//DufriBiNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aubogusnulaugudanulaulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="difriBiNulaubonulauFridatus" upperBound="-1" eType="//AnbebobiFrigubuDaGubuBubobubucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FabebebugudabinulauboboDagutor" eSuperTypes="//BaNulaunulauCio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alGunulauGusbiDabuTor" eType="//AlfriFridabufriDabeGuNules" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdabegusgusAuCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauGusBuNulaugusbeBoFriFribifritor" ordered="false" eType="//EbeBiBiFriGusCio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EunulaufrifribiGusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabuBobefrinulAuFribeNulius" ordered="false" eType="//AbegusfrigubiNules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulaubububiBubebigusBobiBolus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFridaFriBobibuDagusboes" ordered="false" eType="//AufribidaTor" eOpposite="//AufribidaTor/aubiBiGugudaboGusBoNulaudanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigufribuEs"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DaGuNulAugusgubiCus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BagubefrifridafrinulAunus">
    <eLiterals name="DodabobuDanulAunulaubodatus"/>
    <eLiterals name="BrAuguguGusguGulius"/>
    <eLiterals name="AnBiboFriBoDaCio"/>
    <eLiterals name="AldaGusgusbilius"/>
    <eLiterals name="FaNulauNulaugusdabobitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusnulAuFriNulaunulAuDacio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eunulaugufriBoNulAucio" eType="//EuBuBeBiCio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anfrinulAuboBiDaNulaugusBoGuscus" ordered="false" eType="//DuGugusAudadabetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinulaugusgusGusTor" eSuperTypes="//BraubegusgusnulAubeguLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugusbigufrigusnulaulus" ordered="false" eType="//AngusnulauGusfriboBibubuBunulauNus"/>
  </eClassifiers>
</ecore:EPackage>
