<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dabibulius" nsURI="http://hub.de/rcore/examples/dabibulius" nsPrefix="HW">
  <eClassifiers xsi:type="ecore:EClass" name="BiGuguboBedanulauNulaubibinus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaboDafrinulauNules" instanceTypeName="typeBebodanulAufriGuFridagugusTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaGusnulAuGusBodabofribenulEs" eSuperTypes="//BiGuguboBedanulauNulaubibinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diguBofriBodafribufrigucio" ordered="false" upperBound="-1" eType="//BiGuguboBedanulauNulaubibinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusgusfriBegububinulaucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAugusnulauNulaunulaububiTor" eSuperTypes="//BiGuguboBedanulauNulaubibinus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beGusbegusBebuNulauGucus" ordered="false" eType="//AgusgusfriBegububinulaucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DinulaubuNulauBenulauGuboboButus" instanceTypeName="typeDodabudabuGusbebecus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoBugusbiBubitin" instanceTypeName="typeBafrinulaubodator"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusdaFriBeBelus" eSuperTypes="//AgusgusfriBegububinulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doGusguEs" ordered="false" eType="//BrAugusnulauNulaunulaububiTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bedaDabunulaudabiGudadaTor" upperBound="-1" eType="//BiGuguboBedanulauNulaubibinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DabubinulaudaBugusbibigulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AufrigusbinulaubonulaugunulauboDadaTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlguDaguBofribeBibotus" eSuperTypes="//BrAugusnulauNulaunulaububiTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abidaNus" eType="//DinulaubuNulauBenulauGuboboButus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibobubuBefrinulauBiBoCio" ordered="false" eType="//BrAugusnulauNulaunulaububiTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgusBoBiBobilus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="algubufriboGuBiBogusnulauGucio" upperBound="-1" eType="//AlguDaguBofribeBibotus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibofriBiBenules" eSuperTypes="//AgusgusfriBegububinulaucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anBobudabenules" ordered="false" eType="//AgusBoBiBobilus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afrifrigusauDabubobuBuguNus" ordered="false" upperBound="-1" eType="//BiGuguboBedanulauNulaubibinus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbeGuboFribeNulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubogubobebedaGusgubeFribetor" ordered="false" eType="//AufrigusbinulaubonulaugunulauboDadaTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Dufrigubenus">
    <eLiterals name="Dudagufrinulaunulaubifritor"/>
    <eLiterals name="DabiNulaugusbiboboGulus"/>
  </eClassifiers>
</ecore:EPackage>
