<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aboguses" nsURI="http://hub.de/rcore/examples/aboguses" nsPrefix="yY">
  <eClassifiers xsi:type="ecore:EDataType" name="AboNulaugusguguDaTus" instanceTypeName="typeBrAubobuFrinulAutin"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoFribibebiGufrigubitus" instanceTypeName="typeEbuBibuGusDanulAutor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EbobebenulAubuGuBiGusboGusbeGubeGustus" instanceTypeName="typeBrAuguBugubiGusCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogusdaDabuDabubitus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebuGufricus" upperBound="-1" eType="//AboNulaugusguguDaTus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AboboBeFribogusbecus" instanceTypeName="typeDaFrifriguboboboTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGuGusGusgusBoguFritor" abstract="true" eSuperTypes="//DogusdaDabuDabubitus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubefribebeGusbogusbedaes" abstract="true" eSuperTypes="//AGuGusGusgusBoguFritor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anGugusguTin" eType="//DoFribibebiGufrigubitus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuBugusnulaubegusFrinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aubeGubeDagudabububucio" eType="//DogusdaDabuDabubitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebegusbebibofriBiBeDaLius" eSuperTypes="//AGuGusGusgusBoguFritor //AuBugusnulaubegusFrinulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fafribubigusaubeNulIus" ordered="false" upperBound="-1" eType="//BagugusNulaubifrinus" eOpposite="//BagugusNulaubifrinus/eubugusBinulauboboBebuTin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DobonulaubeFrigusNus">
    <eLiterals name="DuDabodabodafriCio"/>
    <eLiterals name="BeguBobobiGugusfriBubobuGudalus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuFrigunulAubunulAubuBegudaBefriFribuEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagugusNulaubifrinus" eSuperTypes="//AuFrigunulAubunulAubuBegudaBefriFribuEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubugusBinulauboboBebuTin" ordered="false" upperBound="-1" eType="//BebegusbebibofriBiBeDaLius" eOpposite="//BebegusbebibofriBiBeDaLius/fafribubigusaubeNulIus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlnulaubiBebibeFriTin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Dafrinulaugubelus">
    <eLiterals name="BaGusbofriBefrigudabeTor"/>
    <eLiterals name="EBugubinulauGuses"/>
    <eLiterals name="EbebiDaBodabuBedadaBoTin"/>
    <eLiterals name="DiBebogusguGusgusnulAuBufribucus"/>
    <eLiterals name="BrAufrinulauGusbees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BedaFridaFrigusgusbeboDaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlnulaufribeFriboBobitin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraudaGunulaubiBofritus" abstract="true" eSuperTypes="//AlnulaufribeFriboBobitin //AubefribebeGusbogusbedaes"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiFrinulaubofrifrifriTor" instanceTypeName="typeDubifridadaGufriBinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebubofrigusfriBobenulAudaGustin" eSuperTypes="//BedaFridaFrigusgusbeboDaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DunulAufridaNulauNulauguDalus" eSuperTypes="//AGuGusGusgusBoguFritor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anboNulauBebubeLius" ordered="false" upperBound="-1" eType="//DogusdaDabuDabubitus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aBonulauBonulaubudaes" eType="//DobonulaubeFrigusNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaBuGusguDabees" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faFrinulauBiboBeGudagusgusguscus" eType="//DiFrinulaubofrifrifriTor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EufriboBobodafribebutus">
    <eLiterals name="AGusbibiBeFrinulAubebulius"/>
    <eLiterals name="AlgusbuDabugubefriGusbenus"/>
    <eLiterals name="DuBebenulaudaBuGustor"/>
    <eLiterals name="EuGubogudagusbiNulAugusBiBegusTor"/>
    <eLiterals name="BraufribugusbeBigugugusFributor"/>
    <eLiterals name="DubofriDabifritus"/>
    <eLiterals name="DabubigusBiTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeGusbunulauBobeboTor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="biguDaboBogusfridabobibigues" ordered="false" upperBound="-1" eType="//AubefribebeGusbogusbedaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgugusbogusDaBinulaubogugulius" eSuperTypes="//AubefribebeGusbogusbedaes"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eudabebufrilus" abstract="true" eSuperTypes="//BagugusNulaubifrinus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daFriFriBofriBunulAudaGulius" eType="//EufriboBobodafribebutus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BibuFricus">
    <eLiterals name="DonulauBeBubofriBeboBies"/>
    <eLiterals name="FagufribudabobuboLius"/>
    <eLiterals name="BenulauBinulauFribegusfritus"/>
    <eLiterals name="BraubiNulauguBiGusnulauNulAubegusbetor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ABenulaubuDabubiBoNulaufrigustin">
    <eLiterals name="DugusbudabibifridadaNulIus"/>
    <eLiterals name="DoDaBegudaes"/>
    <eLiterals name="ABuDabiBiNulaugusnulAubicio"/>
    <eLiterals name="EubigusfriboDaDabudabolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AufribebeBeFribuBubidaboguslus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DanulauGufribeBiBoBelius">
    <eLiterals name="DadagusfribiBeBecus"/>
    <eLiterals name="BafridagusgusBebebiTin"/>
    <eLiterals name="FagusgudaGusdagusaubegusbigunules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FaFribebebegusgusdaBubufricio" instanceTypeName="typeDufrinulaufribobubees"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedafriBuboDatin" eSuperTypes="//AuBugusnulaubegusFrinulius //EgugusbogusDaBinulaubogugulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EudaFribebiFriguDabetin" instanceTypeName="typeAnbiNulaububoFriBenulauDaFrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuBeBufrinulaunulAutin" eSuperTypes="//BedaFridaFrigusgusbeboDaCio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabeGusbuBigugusdanulaubetin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubegufriNulaubifriGusCus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidaGuslus" upperBound="-1" eType="//ABenulaubuDabubiBoNulaufrigustin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBifribuBoboBegusbodabitin" eSuperTypes="//DunulAufridaNulauNulauguDalus //AuBugusnulaubegusFrinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fafrigusgugugunulaunus" eSuperTypes="//BebubofrigusfriBobenulAudaGustin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobigubedaBiDatus" ordered="false" upperBound="-1" eType="//AubefribebeGusbogusbedaes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BifribofribebufribigusguNulauBobidacus" instanceTypeName="typeDaBiBugusbodagunulAufridanulius"/>
</ecore:EPackage>
