<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="braububitus" nsURI="http://hub.de/rcore/examples/braububitus" nsPrefix="ub">
  <eClassifiers xsi:type="ecore:EClass" name="DubegusNulaunulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doBebiDafrifrigugufriBogusNus" ordered="false" eType="//DugudanulAuGusfribues" eOpposite="//DugudanulAuGusfribues/babenus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuNulAubudabunulaunulAufrifriBubebiBubutus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DugudanulAuGusfribues" eSuperTypes="//DuNulAubudabunulaunulAufrifriBubebiBubutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="babenus" ordered="false" eType="//DubegusNulaunulaunus" eOpposite="//DubegusNulaunulaunus/doBebiDafrifrigugufriBogusNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuDaBubibobobubeTus" eSuperTypes="//DubegusNulaunulaunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abogugusbeCus" eType="//DugudanulAuGusfribues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebobodanulAubobuboTus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuBiBefriboboFridabibubotor" instanceTypeName="typeDaBenulAuguBotor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DodaGusbedanulauGusdatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBodadabenulaubugusgubiDabobotin" ordered="false" eType="//BiBunulauCio" eOpposite="//BiBunulauCio/anDaBinulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ABoGusdafribuBugusbibiboNus" instanceTypeName="typeDubegunulaububogubuguBoguses"/>
  <eClassifiers xsi:type="ecore:EClass" name="EGuboBenulAudabues" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EbofriBebobudabibeTin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DigufriGubeDanulaubibugusNus">
    <eLiterals name="DibeFriBebiDabifrilus"/>
    <eLiterals name="AldabiBeguBefribolius"/>
    <eLiterals name="BraugusBiBunulaugusbeFribolius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BadabedaNulAuFribitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albeNulauBuDadafribuFrinus" upperBound="-1" eType="//DuNulAubudabunulaunulAufrifriBubebiBubutus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baBibubegusnulAuBifriNulius" eType="//DigufriGubeDanulaubibugusNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaNulaubifriguGuTor" abstract="true" eSuperTypes="//DuNulAubudabunulaunulAufrifriBubebiBubutus //DuDaBubibobobubeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbenulauBiguboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BiFrigusnulAugusGusboFrinules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="doboBuBuFrigugusGubeButus" ordered="false" eType="//EGuboBenulAudabues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaFrinulauboBigusbibolius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubefriBobenulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="Annulaugustor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ebugudaBiTus" eType="//ABoGusdafribuBugusbibiboNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeBenulaubodanulauLus" eSuperTypes="//EGuboBenulAudabues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brAuguBiFribunus" eType="//ABoGusdafribuBugusbibiboNus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FagusbiBuBoGubetor" eSuperTypes="//DuDaBubibobobubeTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BenulAuBiBebofrigusdabufrilius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auguBubeDafriGuscio" ordered="false" upperBound="-1" eType="//Annulaugustor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBeGusboBibiGusIus" ordered="false" upperBound="-1" eType="//AuGusfrinulaunulAutus" eOpposite="//AuGusfrinulaunulAutus/adabebobububeFriDanus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigubeNulAuBigustus" eSuperTypes="//FagusbiBuBoGubetor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alboGuBibenulAuBidagusFridabolus" ordered="false" upperBound="-1" eType="//BaNulaubifriguGuTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBodabufriBodadagugusgusgusBobuTin" eSuperTypes="//BadabedaNulAuFribitus //Annulaugustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboBufriBubuGusNulauBigusfriTus" abstract="true" eSuperTypes="//FagusbiBuBoGubetor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AGusguBedafriFrigusbobiTin" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DifrinulauGubodabuDabiGusnus" instanceTypeName="typeDuboGubibugusBiBogubinulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbiBebogubebuDafribufriguTus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="augusdaguDaNulauBuNus" ordered="false" upperBound="-1" eType="//FagusbiBuBoGubetor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aBiNulAufriGubeBiGusius" ordered="false" upperBound="-1" eType="//DogusnulaugubebenulaunulauLus" eOpposite="//DogusnulaugubebenulaunulauLus/aguBofriBebegunulauGuBelus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BabegusdafriGubuDaBegugugutin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BegugusGusguscio" abstract="true" eSuperTypes="//Annulaugustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="euBoDadabenulius" ordered="false" upperBound="-1" eType="//BadabedaNulAuFribitus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaDaBeBuBubiboGubifriGuCio" eSuperTypes="//BenulAuBiBebofrigusdabufrilius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Dabudanulaubodafrigusbilius" instanceTypeName="typeEgusBobobuBinulAudagusEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="DafriBibibiDafrigusGusnulaufriguNus" eSuperTypes="//AlbeBenulaubodanulauLus //AlbiBebogubebuDafribufriguTus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fabuBoNulAuBilius" eType="//Dabudanulaubodafrigusbilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusnulaugubebenulaunulauLus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aguBofriBebegunulauGuBelus" ordered="false" upperBound="-1" eType="//AlbiBebogubebuDafribufriguTus" eOpposite="//AlbiBebogubebuDafribufriguTus/aBiNulAufriGubeBiGusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbubeGugugusLius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbobebenulauDafriguFribofrinus" ordered="false" upperBound="-1" eType="//BegugusGusguscio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuGusfrinulaunulAutus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adabebobububeFriDanus" ordered="false" eType="//BenulAuBiBebofrigusdabufrilius" eOpposite="//BenulAuBiBebofrigusdabufrilius/diBeGusboBibiGusIus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAubibibibubebugusbenulautor" ordered="false" upperBound="-1" eType="//DugudanulAuGusfribues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="braubogudagusbeNus" upperBound="-1" eType="//AuBiBefriboboFridabibubotor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BiBunulauCio" abstract="true" eSuperTypes="//AnboBufriBubuGusNulauBigusfriTus //AlbiBebogubebuDafribufriguTus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anDaBinulius" ordered="false" upperBound="-1" eType="//DodaGusbedanulauGusdatus" eOpposite="//DodaGusbedanulauGusdatus/brauBodadabenulaubugusgubiDabobotin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagugusnulAuDabogubuBobuguguBilus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dububegunus" eSuperTypes="//FaDaBeBuBubiboGubifriGuCio //AlbeBenulaubodanulauLus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FagusdagusbobibeBufriguTin" eSuperTypes="//EBodabufriBodadagugusgusgusBobuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BafriDabinulaubudagunulauBonus" eSuperTypes="//DafriBibibiDafrigusGusnulaufriguNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="albibofriBebiboFriCus" eType="//DifrinulauGubodabuDabiGusnus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnguBudagusDabibibebonulaubees" eSuperTypes="//FaFrinulauboBigusbibolius //BaNulaubifriguGuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BedadagusauLus" eSuperTypes="//BafriDabinulaubudagunulauBonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgusGusGusbidabeBiFrifrinules" abstract="true" eSuperTypes="//FaFrinulauboBigusbibolius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ADafriBudaboGusbees" instanceTypeName="typeADabodabudaBubugugusgusFriGuNulAuFrinules"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBeboBibetor" eSuperTypes="//AubefriBobenulIus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbobedaFriBoGusFriBiGusbigusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaBuboNulauDabocus" abstract="true" eSuperTypes="//BagugusnulAuDabogubuBobuguguBilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgusGudaFriBigubibuFriGubibunulaubotor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubibiGusbiBudaGusnulaulus" eType="//DifrinulauGubodabuDabiGusnus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuGusauGusbedanulAuboBobodatus" eSuperTypes="//FagusbiBuBoGubetor //BafriDabinulaubudagunulauBonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dagusaubofribebubebidaGucus" eType="//Annulaugustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DibobubeFrifrigusnulAucus" eSuperTypes="//AlbobedaFriBoGusFriBiGusbigusius //BaNulaubifriguGuTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubibibugudaguTus"/>
</ecore:EPackage>
