<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dibobegufrigulus" nsURI="http://hub.de/rcore/examples/dibobegufrigulus" nsPrefix="Au">
  <eClassifiers xsi:type="ecore:EClass" name="BrAugusbugubeFrinulaubebudafrigusaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibodagusguBiBubonus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alfridabiBetus" ordered="false" upperBound="-1" eType="//BrAugusbugubeFrinulaubebudafrigusaucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EugusBibifribobiBebonulEs" eSuperTypes="//DibodagusguBiBubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaDabeDaGusbibuBedagusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DaguNulAugudaDacio" abstract="true" eSuperTypes="//BrAugusbugubeFrinulaubebudafrigusaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alaubofribitus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobebiBiNulaubofrinus" ordered="false" upperBound="-1" eType="//DibodagusguBiBubonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DanulauBinulaugusboDabogusnus">
    <eLiterals name="BefriBogusBigusNulaugusbeFrilius"/>
    <eLiterals name="AbunulaubiGuBugusdabuboNulAuBulus"/>
    <eLiterals name="EufridanulauNulauBuDaGufrigucio"/>
    <eLiterals name="BegubedagusGusBulus"/>
    <eLiterals name="DabiBebegusfriBuBoDaDacus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafribobeEs" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrauBigugugusGudabedabulius" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AuNulaubiBilius" instanceTypeName="typeBebubebobugusFrigusbifrigutor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriboguGulius" eSuperTypes="//EugusBibifribobiBebonulEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BaBegusBenulauDabegusfriDaGusnus" instanceTypeName="typeAubuBebegudaGusFries"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaDaNulAubobobees" instanceTypeName="typeFabobufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoguBubeBedaGusFrinulaunulauTor" eSuperTypes="//DibodagusguBiBubonus //Alaubofribitus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AbububodaBufrifribibubuNus" instanceTypeName="typeAnaugudabofriBubeBebibebuTin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DubuBifrigusius">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begubibibiGuguTor" eType="//BaBegusBenulauDabegusfriDaGusnus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EuNulAufridaDagustor" eSuperTypes="//DubuBifrigusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbeFriBubiguDaBuBuBitus" eSuperTypes="//DibodagusguBiBubonus //DubuBifrigusius //BrAugusbugubeFrinulaubebudafrigusaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DadaboGubibobuTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BigubebigusgusdafriguLus" instanceTypeName="typeDofriBiNulaugusAubigusgubefrinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbebebuDanulAunulauCus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabobebuboes" eType="//DaDaNulAubobobees" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dibibeFridafrinulautor" eType="//AuNulaubiBilius" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnAuBiGusgusDatin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinulAuNulaudagudaboButin" abstract="true" eSuperTypes="//EuNulAufridaDagustor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Aubobues" instanceTypeName="typeDogusbebefriNulaubotus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FabeBugunulauGusbonus" eSuperTypes="//DaDabeDaGusbibuBedagusius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubigustus" ordered="false" eType="//DadaboGubibobuTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadabiFriGusgusnulAutus" ordered="false" eType="//DaDabeDaGusbibuBedagusius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlbibebeNulAugusius" eSuperTypes="//DoguBubeBedaGusFrinulaunulauTor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EBufribigunulauNulaugubefrigustor">
    <eLiterals name="Eugusnulaugusnulaudatin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobuBuguNulAubiboBodabiBegusbonulauTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusNulaugusbebugusFriGusEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubebolus" ordered="false" upperBound="-1" eType="//DufriboguGulius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBeFrigubobeGuNulautor" ordered="false" eType="//AbebebuDanulAunulauCus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bibeBugubebotus" eType="//Aubobues" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DufriDabigusBeBobifribufribenulEs"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlbobeBiGuBebefriBiBeTus" eSuperTypes="//DadaboGubibobuTus //DaguNulAugudaDacio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGusbogusgusGusnulauboBuGues" ordered="false" upperBound="-1" eType="//DugusbudanulaubeBobocio" eOpposite="//DugusbudanulaubeBobocio/alboGusbeDaGufriTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DugusbudanulaubeBobocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alboGusbeDaGufriTus" ordered="false" eType="//AlbobeBiGuBebefriBiBeTus" eOpposite="//AlbobeBiGuBebefriBiBeTus/auGusbogusgusGusnulauboBuGues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AldaBebuDabuBoFribibiBegusBifritin" eSuperTypes="//DibodagusguBiBubonus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufriNulauGugufriboNulius"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraugusBugusbebegubinulaucus" instanceTypeName="typeBaBeBidagubedabebobutor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AuDabugusbenulAubiBeBodadaDaEs">
    <eLiterals name="EubiboBibudagubucus"/>
    <eLiterals name="BibodadaBifriBeNus"/>
    <eLiterals name="Aubegusbubidanulaulus"/>
    <eLiterals name="DuBoguBeDaGubees"/>
    <eLiterals name="Adabogudalus"/>
    <eLiterals name="EgubeFridaBubunulautus"/>
    <eLiterals name="DiGusGusNulauDaBegusguses"/>
    <eLiterals name="BeGubogusNulAunulaunulius"/>
    <eLiterals name="BaFribobenulautin"/>
    <eLiterals name="ENulAucus"/>
    <eLiterals name="Banulaugubebies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlBobifribogusbobiCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BagusAuDafribetor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AgufrifriBidanulaucio" instanceTypeName="typeDibibububibobolus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DogusfribibiGufribibobolus" instanceTypeName="typeEuBubeNulauguboguTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="EubeFrigusAubibubobudaTor" eSuperTypes="//DufriDabigusBeBobifribufribenulEs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baBuboNulaubudabebobubiTin" ordered="false" upperBound="-1" eType="//EugusBibifribobiBebonulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BegufribuBobeboes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auGubuGusnulaubunulaufricio" ordered="false" eType="//DadaboGubibobuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlDabuDabobenulautus">
    <eLiterals name="DuGusGubuNulAugusNus"/>
  </eClassifiers>
</ecore:EPackage>
