<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bagusaubodadabinulautin" nsURI="http://hub.de/rcore/examples/bagusaubodadabinulautin" nsPrefix="F">
  <eClassifiers xsi:type="ecore:EClass" name="BiGuBiBogusBebuguBufributus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraubudaBobiDaboBulus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DaBoFriGusbeBugubeGusTor" instanceTypeName="typeBraugubogusfriGubodabefribulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DufrifridaboDaboBoDadatus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="didadaBogusnulauBunulauBegusauTin" ordered="false" eType="//BiGuBiBogusBebuguBufributus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dugusdafribifrigusbubuGulus" ordered="false" eType="//BraubudaBobiDaboBulus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofriGunulAuguDadabebubigubefribenulaubutus" ordered="false" upperBound="-1" eType="//EbibuNulauFrigusbobegusTin" eOpposite="//EbibuNulauFrigusbobegusTin/ebiNulaubigusgusBeBies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBudabutus" ordered="false" eType="//EbibuNulauFrigusbobegusTin" eOpposite="//EbibuNulauFrigusbobegusTin/anbuBebububibilius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnNulAuBedabodabobonulaufriTor" eSuperTypes="//BraubudaBobiDaboBulus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="duboGuBedabegunulaubilius" eType="//EbibuNulauFrigusbobegusTin" eOpposite="//EbibuNulauFrigusbobegusTin/bibedabuBubodaBebiBeguguses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BeguBoguBogudagusBinules" instanceTypeName="typeDabegudabigusbebuGusboTus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebeBibenulaugusbucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binulAubibuBeBeguNus" ordered="false" eType="//DufrifridaboDaboBoDadatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EbibuNulauFrigusbobegusTin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebiNulaubigusgusBeBies" ordered="false" upperBound="-1" eType="//DufrifridaboDaboBoDadatus" eOpposite="//DufrifridaboDaboBoDadatus/dofriGunulAuguDadabebubigubefribenulaubutus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibedabuBubodaBebiBeguguses" ordered="false" upperBound="-1" eType="//AnNulAuBedabodabobonulaufriTor" eOpposite="//AnNulAuBedabodabobonulaufriTor/duboGuBedabegunulaubilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anbuBebububibilius" ordered="false" upperBound="-1" eType="//DufrifridaboDaboBoDadatus" eOpposite="//DufrifridaboDaboBoDadatus/diBudabutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EfriFriDagusBubecio" instanceTypeName="typeFaguguBiBeGusboNulauFritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiguBiFriBoNulaudanules"/>
  <eClassifiers xsi:type="ecore:EClass" name="BadabiBifriNulaudaBugusBofriCio" eSuperTypes="//DiguBiFriBoNulaudanules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brauBegusnulAuBees" ordered="false" eType="//AudaDaBeGusFridalius" eOpposite="//AudaDaBeGusFridalius/dobibigusguBenulaufriGunus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuBoBubugusgufrigudaNulaubebocio" abstract="true" eSuperTypes="//BiGuBiBogusBebuguBufributus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BraubebugusFridaDabolius" instanceTypeName="typeDobogubitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnulAudabebibedabeBinus" eSuperTypes="//BraubudaBobiDaboBulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="FafribudaBeboFriboNus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BebogusBuboBugusLius" eSuperTypes="//BiGuBiBogusBebuguBufributus //FafribudaBeboFriboNus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="daBibuguboGudabobodator" eType="//EfriFriDagusBubecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnbobodagubefrigudaGuscus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bebebubonulaulius" eType="//EfriFriDagusBubecio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aububedabufriFricio" eType="//DaBoFriGusbeBugubeGusTor" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dofriBinulauBibuDanus" ordered="false" upperBound="-1" eType="//BebiGubobugusBuGugunulaubuFrinulaugucus" eOpposite="//BebiGubobugusBuGugunulaubuFrinulaugucus/dadaguDadabifribibubeNus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENulauNulautus"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulAububobiguGufriTus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EubibubuBebenulaulus" instanceTypeName="typeDobofritor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EuBobudagusButin">
    <eLiterals name="DibegugusgusdanulauBecus"/>
    <eLiterals name="DububegubedabuboDaLius"/>
    <eLiterals name="FabudadadanulAuboBoBobiTor"/>
    <eLiterals name="BaBoBobuDabudabiGuBubonus"/>
    <eLiterals name="DuboBiGusnulaugubulus"/>
    <eLiterals name="DabinulaugusAubobefribucus"/>
    <eLiterals name="BraugusaunulauBifribuguTus"/>
    <eLiterals name="Eugusgubegucio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Algubefrigusfribibegulius" instanceTypeName="typeBrauBobibuguBenulAuguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AudaDaBeGusFridalius" eSuperTypes="//AnbobodagubefrigudaGuscus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alAubiNulaudafrinulaugusbibotus" eType="//Algubefrigusfribibegulius" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dobibigusguBenulaufriGunus" ordered="false" upperBound="-1" eType="//BadabiBifriNulaudaBugusBofriCio" eOpposite="//BadabiBifriNulaudaBugusBofriCio/brauBegusnulAuBees"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebiGubobugusBuGugunulaubuFrinulaugucus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dadaguDadabifribibubeNus" ordered="false" upperBound="-1" eType="//AnbobodagubefrigudaGuscus" eOpposite="//AnbobodagubefrigudaGuscus/dofriBinulauBibuDanus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="befribubofrifriTus" eType="//EfriFriDagusBubecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AbuguBibobugusbogugusLus" instanceTypeName="typeAlgusbubibenulauNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DifribiGuboboGudagusBibigusgutin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annulaubefrigusnulaufriboFriguBibulius" eType="//EfriFriDagusBubecio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnbubiNulAubibeNulAufribeGusCus">
    <eLiterals name="AnfriBunulaubuDaGubonus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FanulAufridagusNus" eSuperTypes="//BraubudaBobiDaboBulus //BebeBibenulaugusbucio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abedaDaGufrinulaubiboFrigusbicio" ordered="false" upperBound="-1" eType="//BanulAububobiguGufriTus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eBifridaboGubiboBegubelus" ordered="false" upperBound="-1" eType="//AnbobodagubefrigudaGuscus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANulIus" eSuperTypes="//FafribudaBeboFriboNus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alNulaufriDaBudator" eType="//BrAuBoBubugusgufrigudaNulaubebocio"/>
  </eClassifiers>
</ecore:EPackage>
