<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dagusgulus" nsURI="http://hub.de/rcore/examples/dagusgulus" nsPrefix="EmS">
  <eClassifiers xsi:type="ecore:EClass" name="Aucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="EububufribiGuses" abstract="true" eSuperTypes="//Aucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DanulaubugusnulAucus" instanceTypeName="typeBagubobeBoNulaugunulauBubuBinus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnboBigusBoBocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubodabeguboDaGusBubebonulEs" ordered="false" upperBound="-1" eType="//Do" eOpposite="//Do/dibogusBugusbubifrigutor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusNulAunulaudaFriNulauBeFricio" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dobibebububitin" eType="//DanulaubugusnulAucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EuGubobobefricio" instanceTypeName="typeAnguguscio"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdaNulaububuGusaubububebiGuButin" eSuperTypes="//DagusNulAunulaudaFriNulauBeFricio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diBiGuboFrinulAufridaes" ordered="false" upperBound="-1" eType="//EububufribiGuses"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigusgusbigudaDabebiguCio" eType="//DanulaubugusnulAucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraufrinulaudaGusfrinulauBucio" eSuperTypes="//EububufribiGuses"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnulAugusGuBebufribucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubebibegusauguDaBudaGusGustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuDafriNulaubenulIus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbibunulAubobees" abstract="true" eSuperTypes="//AubebibegusauguDaBudaGusGustor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abeDadabiBefriEs" eType="//DanulaubugusnulAucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DogusbiNulauBobinulaulius" eSuperTypes="//EububufribiGuses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="auFriBibiBeGusgucus" upperBound="-1" eType="//AuDafriNulaubenulIus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aubenulAuGuslius" upperBound="-1" eType="//DanulaubugusnulAucus" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DagusnulaubibugugudaGusbinulaubeCus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuGusBegunulaudaBebonulauNulAunulAunus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abiGugugusGusBibobifriNulaunus" ordered="false" upperBound="-1" eType="//EububufribiGuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Do" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eubufrigusbeBidaNulaugufriNulauBegusNulauCio" ordered="false" upperBound="-1" eType="//Aucio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alfridaboFriBibebegusbegusGuslus" eType="//EuGubobobefricio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dibogusBugusbubifrigutor" ordered="false" eType="//AnboBigusBoBocus" eOpposite="//AnboBigusBoBocus/eubodabeguboDaGusBubebonulEs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBeBebenulAubebeLius" eSuperTypes="//Aucio"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnulaubidanulauguBonulaucio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BabeNulauBofridadagucus" abstract="true" eSuperTypes="//DagusnulaubibugugudaGusbinulaubeCus"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuBoGudadaNulauCio" eSuperTypes="//AnboBigusBoBocus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diNulAudabiboBebeDafrinulAutin" ordered="false" eType="//EBeBebenulAubebeLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiGubeDafriboFribegusboDadagusguTor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoGusgusBotin"/>
  <eClassifiers xsi:type="ecore:EClass" name="DobunulAufrigustor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="euboGuBegusbugustor" eType="//EuGubobobefricio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuBuBeFribobubuDaes" abstract="true" eSuperTypes="//AubebibegusauguDaBudaGusGustor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BefribedabubufrigubeEs" eSuperTypes="//Aucio //BabeNulauBofridadagucus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnaugubunulaubuBobuDaLus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="danulaubenulauDaBebiCio" ordered="false" upperBound="-1" eType="//DigusbobiBobibolius" eOpposite="//DigusbobiBobibolius/efriGugubodaBoBunulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DobigusfridabuBidabiBibubebudaNulAubenus" eSuperTypes="//Aucio //AnbibunulAubobees">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudanulauguscus" ordered="false" upperBound="-1" eType="//EnulAugusGuBebufribucus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dubuBubibuGusauNulauTin" ordered="false" eType="//AubebibegusauguDaBudaGusGustor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EbibubidaDaBufribinulAuguBiEs" instanceTypeName="typeEbobuGusAubibefribuguBoTor"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AnBibobugugudabiFriBuBiBenulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DibiGusdaDadabuNulauBeNulauBunus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dogusaudaBoGusFriGunus" eType="//AnulaubidanulauguBonulaucio" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbebobobobobobegusbeBuFrilius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aboDabugugubodabiLius" eType="//AnboBigusBoBocus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bibodabeBuBigusbigutus" ordered="false" eType="//BraufrinulaudaGusfrinulauBucio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faGusbugufribeTus" ordered="false" upperBound="-1" eType="//DiGubeDafriboFribegusboDadagusguTor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BigubuguCus">
    <eLiterals name="DogubobobebibubuTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DafribigusfriBogusaucus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DuGudabuBoFriGusBoBobiTin" instanceTypeName="typeEubinulAubefriGusius"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiGusdafricus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DobibeBibuTor" instanceTypeName="typeDoBobuGubiguFrigubees"/>
  <eClassifiers xsi:type="ecore:EClass" name="BrAunulaunulauguFridaCio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="albuboDaBigusnulEs" upperBound="-1" eType="//AnaugubunulaubuBobuDaLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BibibobeBunulAunulauboGugusEs" eSuperTypes="//Aucio"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DubufriDanus" instanceTypeName="typeFagunulAufribeBulus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbefriNulaunulauBiFrifritus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anGugusBugusdaFridacus" eType="//AnulaubidanulauguBonulaucio" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="donulauFriDaboBoLius" eType="//EbibubidaDaBufribinulAuguBiEs" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigusbobiBobibolius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="efriGugubodaBoBunulius" ordered="false" eType="//AnaugubunulaubuBobuDaLus" eOpposite="//AnaugubunulaubuBobuDaLus/danulaubenulauDaBebiCio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duBogusBebedabudaBebudaGuCio" ordered="false" upperBound="-1" eType="//AbebobobobobobegusbeBuFrilius"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="brAufriFriFriBugusfribugudator" ordered="false" upperBound="-1" eType="//BabeNulauBofridadagucus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BraubeBugusAuNulAugufritin"/>
  <eClassifiers xsi:type="ecore:EClass" name="BanulaudadagusTus" eSuperTypes="//BabeNulauBofridadagucus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digusgubunulaubeLus" ordered="false" upperBound="-1" eType="//DagusnulaubibugugudaGusbinulaubeCus"/>
  </eClassifiers>
</ecore:EPackage>
