<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ebebecio" nsURI="http://hub.de/rcore/examples/ebebecio" nsPrefix="hDSW">
  <eClassifiers xsi:type="ecore:EDataType" name="FagusbinulaufrinulAubebies" instanceTypeName="typeBraunulaubigufribegusboBiguFrilus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuFriBunulAuBeboGusbobeNulAuBetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ebubeGudaBogulus" eType="//AnbefribebefriDaBenus" eOpposite="//AnbefribebefriDaBenus/alBebidagusDalius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EubuBobifrifrigusnulaudaTus">
    <eLiterals name="AuDaBibibeGutin"/>
    <eLiterals name="AnGuFrifrigubogusAuboGuslus"/>
    <eLiterals name="AgubegunulAuFribunules"/>
    <eLiterals name="BrauBeNulaufriBoGuslus"/>
    <eLiterals name="BenulAuBubeGusaubeBegusDabuBiCus"/>
    <eLiterals name="AdaBobobuDaGudabubuLus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dogufrinulaulius">
    <eStructuralFeatures xsi:type="ecore:EReference" name="braugubonulauNulaubitor" ordered="false" upperBound="-1" eType="//AuFriBunulAuBeboGusbobeNulAuBetin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="BabiguDagusBiFriguguNus" instanceTypeName="typeEugusbobobiBuBitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="BraufrigusdabuboBuEs"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ANulaubiboGunulauBigusEs" instanceTypeName="typeBedaFrifridaFriGubibetus"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BinulAugudafries" instanceTypeName="typeDiGusnulAubugusboDaBibecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdaGusdaFrinulaugutus" eSuperTypes="//Dogufrinulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnbefribebefriDaBenus" eSuperTypes="//AuFriBunulAuBeboGusbobeNulAuBetin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alBebidagusDalius" ordered="false" eType="//AuFriBunulAuBeboGusbobeNulAuBetin" eOpposite="//AuFriBunulAuBeboGusbobeNulAuBetin/ebubeGudaBogulus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoguBoGusdaGuNulAuguguBuBobofriBoEs" eSuperTypes="//Dogufrinulaulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbiGusbeBobidanulaubulius" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anGuboTus" eType="//BinulAugudafries" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AlAubeDaNulaugustin"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubeBeBunulauDafribubocus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AubegusFribocio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alaugugudanus" upperBound="-1" eType="//Dogufrinulaulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrAuFribubiDaBeBiGustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eugubuBubibidabuLus" ordered="false" eType="//AdaGusdaFrinulaugutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DinulaugubobefribenulauguGuslus" instanceTypeName="typeBidadaBibuDaboBubefribecus"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlfriNulaubigustor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dabudabegubeBebeTor" ordered="false" upperBound="-1" eType="//AdaGusdaFrinulaugutus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngusbobibebibonulAubues" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="EGufridagusnus">
    <eLiterals name="BraubeboboguBigudaBubibiGusauNulaubunules"/>
    <eLiterals name="FadabugusguGufribibubebebuFriBolus"/>
    <eLiterals name="DafribiDaGubuBoBenulAudadanules"/>
    <eLiterals name="AlbiDabiDabibeguGusfriBubenulEs"/>
    <eLiterals name="DuGusdaBuNulauBunus"/>
    <eLiterals name="AbuGuDaNulaubogusfribugubiTin"/>
    <eLiterals name="DudaGudaboNulauBoFribucio"/>
    <eLiterals name="DibifriboNulaufrinus"/>
    <eLiterals name="EbibidafriboboGuNulauGusfriboBiGues"/>
    <eLiterals name="EBugusBufrifrinulauBubeLius"/>
    <eLiterals name="AlboguFriBedaBefrigusboboGubutin"/>
    <eLiterals name="BeBenulaubuGusbibebidabibifriTin"/>
    <eLiterals name="BibiboBudabubobuBeNulauDabiNus"/>
    <eLiterals name="BraugusDafriGuBetin"/>
    <eLiterals name="DafriGusbegusGusBelius"/>
    <eLiterals name="AlaudaBunus"/>
  </eClassifiers>
</ecore:EPackage>
