<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fa" nsURI="http://hub.de/rcore/examples/fa" nsPrefix="OOrz">
  <eClassifiers xsi:type="ecore:EEnum" name="DibedabiBugugusFrinulAutin">
    <eLiterals name="AubigubibiBegusdagusAudalus"/>
    <eLiterals name="DugubibedagusAuFriLius"/>
    <eLiterals name="DadaBebegusbebebegusbiTus"/>
    <eLiterals name="BibigusboGunulAudanulauLius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndaBoboBofrifribidafrinulaufribogusTor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="begusbegubolus" eType="//DibedabiBugugusFrinulAutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BebedaguFrigusbegusBefribiBodacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaboBiBuButus" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DogubofribegusdagugusTus" eSuperTypes="//BebedaguFrigusbegusBefribiBodacio"/>
  <eClassifiers xsi:type="ecore:EClass" name="DabobiCus" eSuperTypes="//BaboBiBuButus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bebifriBibofriDabiBenus" ordered="false" eType="//AndaBoboBofrifribidafrinulaufribogusTor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="braudagugusdaboes" ordered="false" eType="//DogubofribegusdagugusTus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdafriguFribuBeNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="EuBunulAuGusfribigufriboNulAutus" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dabibinulaufrifridatin" eType="//DibedabiBugugusFrinulAutin" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifriBuGunulaufriFribetor" abstract="true" eSuperTypes="//EdafriguFribuBeNulius"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuDaBugusGubiBecio" abstract="true" eSuperTypes="//BaboBiBuButus"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AubuBunulauDabeButin">
    <eLiterals name="DubeBetor"/>
    <eLiterals name="AnulaufrigusBubiFriGubogulius"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BefribifribuCus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begubefriBedabogucus" eType="//DogubofribegusdagugusTus"/>
  </eClassifiers>
</ecore:EPackage>
