/**
 *
 * $Id$
 */
package rdsSimplified.validation;

import org.eclipse.emf.common.util.EList;

import rdsSimplified.Reference;

/**
 * A sample validator interface for {@link rdsSimplified.Column}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ColumnValidator {
	boolean validate();

	boolean validateForeignReferences(EList<Reference> value);

	boolean validatePrimaryReferences(EList<Reference> value);
}
