/**
 *
 * $Id$
 */
package rdsSimplified.validation;

import org.eclipse.emf.common.util.EList;

import rdsSimplified.Column;
import rdsSimplified.Index;

/**
 * A sample validator interface for {@link rdsSimplified.Table}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableValidator {
	boolean validate();

	boolean validateColumns(EList<Column> value);

	boolean validateIndexes(EList<Index> value);
}
